CasADi: casadi::GenericMatrix< MatType > Class Template Reference
casadi::GenericMatrix< MatType > Class Template Reference
Matrix base class.
#include <generic_matrix.hpp>
Detailed Description
template<typename MatType>
class casadi::GenericMatrix< MatType >
This is a common base class for MX and Matrix<>, introducing a uniform syntax and implementing common functionality using the curiously recurring template pattern (CRTP) idiom.
The class is designed with the idea that "everything is a matrix", that is, also scalars and vectors.
This philosophy makes it easy to use and to interface in particularly with Python and Matlab/Octave.
The syntax tries to stay as close as possible to the ublas syntax when it comes to vector/matrix operations.
Index starts with 0.
Index vec happens as follows: (rr, cc) -> k = rr+cc*size1()
Vectors are column vectors.
The storage format is Compressed Column Storage (CCS), similar to that used for sparse matrices in Matlab,
but unlike this format, we do allow for elements to be structurally non-zero but numerically zero.
The sparsity pattern, which is reference counted and cached, can be accessed with Sparsity& sparsity()
Author
Joel Andersson
Date
2012
Definition at line 72 of file generic_matrix.hpp.
Public Member Functions
int nnz () const
Get the number of (structural) non-zero elements.
int nnz_lower () const
Get the number of non-zeros in the lower triangular half.
int nnz_upper () const
Get the number of non-zeros in the upper triangular half.
int nnz_diag () const
Get get the number of non-zeros on the diagonal.
int numel () const
Get the number of elements.
int numel (int i) const
Get the number of elements in slice (cf. MATLAB)
int size1 () const
Get the first dimension (i.e. number of rows)
int size2 () const
Get the second dimension (i.e. number of columns)
std::string dim () const
Get string representation of dimensions. The representation is (nrow x ncol = numel | size)
std::pair< int, int > size () const
Get the shape.
int size (int axis) const
Get the size along a particular dimensions.
bool is_empty (bool both=false) const
Check if the sparsity is empty, i.e. if one of the dimensions is zero (or optionally both dimensions)
bool is_dense () const
Check if the matrix expression is dense.
bool is_scalar (bool scalar_and_dense=false) const
Check if the matrix expression is scalar.
bool is_square () const
Check if the matrix expression is square.
bool is_vector () const
Check if the matrix is a row or column vector.
bool is_row () const
Check if the matrix is a row vector (i.e. size1()==1)
bool is_column () const
Check if the matrix is a column vector (i.e. size2()==1)
bool is_triu () const
Check if the matrix is upper triangular.
bool is_tril () const
Check if the matrix is lower triangular.
std::vector< int > find (bool ind1=SWIG_IND1) const
Get the location of all non-zero elements as they would appear in a Dense matrix A : DenseMatrix 4 x 3 B : SparseMatrix 4 x 3 , 5 structural non-zeros.
SWIG_CONSTREF (Sparsity) sparsity() const
Get the sparsity pattern.
Sparsity & sparsityRef ()
Access the sparsity, make a copy if there are multiple references to it.
template<typename K >
const MatType operator[] (const K &k) const
Get vector nonzero or slice of nonzeros.
template<typename K >
NonZeros< MatType, K > operator[] (const K &k)
Access vector nonzero or slice of nonzeros.
template<typename RR >
const MatType operator() (const RR &rr) const
Get vector element or slice.
template<typename RR , typename CC >
const MatType operator() (const RR &rr, const CC &cc) const
Get Matrix element or slice.
template<typename RR >
SubIndex< MatType, RR > operator() (const RR &rr)
Access Matrix elements (one argument)
template<typename RR , typename CC >
SubMatrix< MatType, RR, CC > operator() (const RR &rr, const CC &cc)
Access Matrix elements (two arguments)
template<>
SX sym (const string &name, const Sparsity &sp)
template<>
SX sym (const std::string &name, const Sparsity &sp)
template<>
MX sym (const std::string &name, const Sparsity &sp)
template<>
MX sym (const std::string &name, const Sparsity &sp)
std::vector< int > get_row () const
Get the sparsity pattern. See the Sparsity class for details.
std::vector< int > get_colind () const
Get the sparsity pattern. See the Sparsity class for details.
const int * row () const
Get the sparsity pattern. See the Sparsity class for details.
const int * colind () const
Get the sparsity pattern. See the Sparsity class for details.
int row (int el) const
Get the sparsity pattern. See the Sparsity class for details.
int colind (int col) const
Get the sparsity pattern. See the Sparsity class for details.
Static Public Member Functions
static std::vector
< std::vector< MatType > > blocksplit (const MatType &x, const std::vector< int > &vert_offset, const std::vector< int > &horz_offset)
static std::vector
< std::vector< MatType > > blocksplit (const MatType &x, int vert_incr, int horz_incr)
static MatType veccat (const std::vector< MatType > &x)
static MatType vec (const MatType &x)
static MatType repmat (const MatType &x, int n, int m=1)
static MatType repmat (const MatType &A, const std::pair< int, int > &rc)
static std::vector< int > offset (const std::vector< MatType > &v, bool vert=true)
static std::vector< MatType > diagsplit (const MatType &x, const std::vector< int > &output_offset)
static std::vector< MatType > diagsplit (const MatType &x, int incr)
static std::vector< MatType > diagsplit (const MatType &x, int incr1, int incr2)
static MatType mtimes (const std::vector< MatType > &args)
static std::vector< MatType > horzsplit (const MatType &x, int incr)
static std::vector< MatType > vertsplit (const MatType &x, int incr)
static int sprank (const MatType &x)
Accessed by friend functions.
static int norm_0_mul (const MatType &x, const MatType &y)
Accessed by friend functions.
static MatType tril (const MatType &x, bool includeDiagonal=true)
Accessed by friend functions.
static MatType triu (const MatType &x, bool includeDiagonal=true)
Accessed by friend functions.
static MatType sum_square (const MatType &x)
Accessed by friend functions.
static MatType linspace (const MatType &a, const MatType &b, int nsteps)
Accessed by friend functions.
static MatType cross (const MatType &a, const MatType &b, int dim=-1)
Accessed by friend functions.
static MatType skew (const MatType &a)
Accessed by friend functions.
static MatType inv_skew (const MatType &a)
Accessed by friend functions.
static MatType tril2symm (const MatType &x)
Accessed by friend functions.
static MatType triu2symm (const MatType &x)
Accessed by friend functions.
static MatType repsum (const MatType &x, int n, int m=1)
Accessed by friend functions.
Construct symbolic primitives
The "sym" function is intended to work in a similar way as "sym" used in the Symbolic Toolbox for Matlab but instead creating a CasADi symbolic primitive.
static MatType sym (const std::string &name, int nrow=1, int ncol=1)
Create an nrow-by-ncol symbolic primitive.
static MatType sym (const std::string &name, const std::pair< int, int > &rc)
Construct a symbolic primitive with given dimensions.
static MatType sym (const std::string &name, const Sparsity &sp)
Create symbolic primitive with a given sparsity pattern.
static std::vector< MatType > sym (const std::string &name, const Sparsity &sp, int p)
Create a vector of length p with with matrices with symbolic primitives of given sparsity.
static std::vector< MatType > sym (const std::string &name, int nrow, int ncol, int p)
Create a vector of length p with nrow-by-ncol symbolic primitives.
static std::vector
< std::vector< MatType > > sym (const std::string &name, const Sparsity &sp, int p, int r)
Create a vector of length r of vectors of length p with symbolic primitives with given sparsity.
static std::vector
< std::vector< MatType > > sym (const std::string &name, int nrow, int ncol, int p, int r)
Create a vector of length r of vectors of length p with nrow-by-ncol symbolic primitives.
static MatType zeros (int nrow=1, int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MatType zeros (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MatType zeros (const std::pair< int, int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MatType ones (int nrow=1, int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static MatType ones (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static MatType ones (const std::pair< int, int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries one.
Protected Member Functions
const MatType & self () const
MatType & self ()
Friends
MatType sum_square (const MatType &x)
Calculate some of squares: sum_ij X_ij^2.
MatType linspace (const MatType &a, const MatType &b, int nsteps)
Matlab's linspace command.
MatType cross (const MatType &a, const MatType &b, int dim=-1)
Matlab's cross command.
MatType skew (const MatType &a)
Generate a skew symmetric matrix from a 3-vector.
MatType inv_skew (const MatType &a)
Generate the 3-vector progenitor of a skew symmetric matrix.
MatType det (const MatType &A)
Matrix determinant (experimental)
MatType inv (const MatType &A)
Matrix inverse (experimental)
MatType trace (const MatType &x)
Matrix trace.
MatType tril2symm (const MatType &a)
Convert a lower triangular matrix to a symmetric one.
MatType triu2symm (const MatType &a)
Convert a upper triangular matrix to a symmetric one.
MatType norm_F (const MatType &x)
Frobenius norm.
MatType norm_2 (const MatType &x)
2-norm
MatType norm_1 (const MatType &x)
1-norm
MatType norm_inf (const MatType &x)
Infinity-norm.
MatType sum1 (const MatType &x)
Return a row-wise summation of elements.
MatType sum2 (const MatType &x)
Return a column-wise summation of elements.
MatType dot (const MatType &x, const MatType &y)
Inner product of two matrices with x and y matrices of the same dimension.
MatType nullspace (const MatType &A)
Computes the nullspace of a matrix A.
MatType polyval (const MatType &p, const MatType &x)
Evaluate a polynomial with coefficients p in x.
MatType diag (const MatType &A)
Get the diagonal of a matrix or construct a diagonal When the input is square, the diagonal elements are returned. If the input is vector-like, a diagonal matrix is constructed with it.
MatType unite (const MatType &A, const MatType &B)
Unite two matrices no overlapping sparsity.
MatType densify (const MatType &x)
Make the matrix dense if not already.
MatType densify (const MatType &x, const MatType &val)
Make the matrix dense and assign nonzeros to a value.
MatType project (const MatType &A, const Sparsity &sp, bool intersect=false)
Create a new matrix with a given sparsity pattern but with the nonzeros taken from an existing matrix.
MatType if_else (const MatType &cond, const MatType &if_true, const MatType &if_false, bool short_circuit=true)
Branching on MX nodes Ternary operator, "cond ? if_true : if_false".
MatType conditional (const MatType &ind, const std::vector< MatType > &x, const MatType &x_default, bool short_circuit=true)
Create a switch.
bool depends_on (const MatType &f, const MatType &arg)
Check if expression depends on the argument The argument must be symbolic.
MatType substitute (const MatType &ex, const MatType &v, const MatType &vdef)
Substitute variable v with expression vdef in an expression ex.
std::vector< MatType > substitute (const std::vector< MatType > &ex, const std::vector< MatType > &v, const std::vector< MatType > &vdef)
Substitute variable var with expression expr in multiple expressions.
void substitute_inplace (const std::vector< MatType > &v, std::vector< MatType > &inout_vdef, std::vector< MatType > &inout_ex, bool reverse=false)
Inplace substitution with piggyback expressions Substitute variables v out of the expressions vdef sequentially, as well as out of a number of other expressions piggyback.
MatType solve (const MatType &A, const MatType &b)
Solve a system of equations: A*x = b The solve routine works similar to Matlab's backslash when A is square and nonsingular. The algorithm used is the following:
MatType solve (const MatType &A, const MatType &b, const std::string &lsolver, const Dict &dict=Dict())
Solve a system of equations: A*x = b.
MatType pinv (const MatType &A)
Computes the Moore-Penrose pseudo-inverse.
MatType pinv (const MatType &A, const std::string &lsolver, const Dict &dict=Dict())
Computes the Moore-Penrose pseudo-inverse.
MatType jtimes (const MatType &ex, const MatType &arg, const MatType &v, bool tr=false)
Calculate the Jacobian and multiply by a vector from the right This is equivalent to mul(jacobian(ex, arg), v) or mul(jacobian(ex, arg).T, v) for tr set to false and true respectively. If contrast to these expressions, it will use directional derivatives which is typically (but not necessarily) more efficient if the complete Jacobian is not needed and v has few rows.
int n_nodes (const MatType &A)
MatType simplify (const MatType &x)
Simplify an expression.
std::string print_operator (const MatType &xb, const std::vector< std::string > &args)
Get a string representation for a binary MatType, using custom arguments.
void shared (std::vector< MatType > &ex, std::vector< MatType > &v, std::vector< MatType > &vdef, const std::string &v_prefix="v_", const std::string &v_suffix="")
Extract shared subexpressions from an set of expressions.
void shared (const std::vector< MatType > &ex, std::vector< MatType > &ex_output, std::vector< MatType > &v, std::vector< MatType > &vdef, const std::string &v_prefix="v_", const std::string &v_suffix="")
Extract shared subexpressions from an set of expressions.
MatType repsum (const MatType &A, int n, int m=1)
Given a repeated matrix, computes the sum of repeated parts.
MatType jacobian (const MatType &ex, const MatType &arg, bool symmetric=false)
Calculate Jacobian.
MatType gradient (const MatType &ex, const MatType &arg)
Calculate Jacobian.
MatType tangent (const MatType &ex, const MatType &arg)
Calculate Jacobian.
MatType hessian (const MatType &ex, const MatType &arg)
MatType hessian (const MatType &ex, const MatType &arg, MatType &output_g)
std::vector< bool > nl_var (const MatType &expr, const MatType &var)
Find out which variables enter nonlinearly.
static MatType bilin (const MatType &A, const MatType &x, const MatType &y)
Matrix power x^n.
MatType mpower (const MatType &x, const MatType &n)
Matrix power x^n.
MatType mrdivide (const MatType &x, const MatType &n)
Matrix divide (cf. slash '/' in MATLAB)
MatType mldivide (const MatType &x, const MatType &n)
Matrix divide (cf. backslash '\' in MATLAB)
std::vector< MatType > symvar (const MatType &x)
Get all symbols contained in the supplied expression Get all symbols on which the supplied expression depends.
MatType bilin (const MatType &A, const MatType &x, const MatType &y)
Calculate bilinear form x^T A y.
static MatType rank1 (const MatType &A, const MatType &alpha, const MatType &x, const MatType &y)
Make a rank-1 update to a matrix A Calculates A + 1/2 * alpha * x*y'.
MatType rank1 (const MatType &A, const MatType &alpha, const MatType &x, const MatType &y)
Make a rank-1 update to a matrix A Calculates A + 1/2 * alpha * x*y'.
Member Function Documentation
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::bilin (const MatType & A, const MatType & x, const MatType & y) static
template<typename MatType> std::vector< std::vector< MatType > > casadi::SparsityInterface< MatType >::blocksplit (const MatType & x, const std::vector< int > & vert_offset, const std::vector< int > & horz_offset) static inherited
Definition at line 551 of file sparsity_interface.hpp.
{
     std::vector<MatType> rows = MatType::vertsplit(x, vert_offset);
     std::vector< std::vector< MatType > > ret;
     for (auto&& r : rows) ret.push_back(MatType::horzsplit(r, horz_offset));
     return ret;
   }
template<typename MatType> std::vector< std::vector< MatType > > casadi::SparsityInterface< MatType >::blocksplit (const MatType & x, int vert_incr, int horz_incr) static inherited
Definition at line 562 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(horz_incr>=1);
     casadi_assert(vert_incr>=1);
     int sz1 = x.size1();
     std::vector<int> offset1 = range(0, sz1, vert_incr);
     offset1.push_back(sz1);
     int sz2 = x.size2();
     std::vector<int> offset2 = range(0, sz2, horz_incr);
     offset2.push_back(sz2);
     return blocksplit(x, offset1, offset2);
   }
template<typename MatType> const int* casadi::GenericMatrix< MatType >::colind () const inline
Definition at line 147 of file generic_matrix.hpp.
Referenced by casadi::SnoptInterface::init(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::SnoptInterface::solve(), and casadi::SnoptInterface::userfun().
 { return sparsity().colind(); }
template<typename MatType> int casadi::GenericMatrix< MatType >::colind (int col) const inline
Definition at line 150 of file generic_matrix.hpp.
 { return sparsity().colind(col); }
template<typename MatType> MatType casadi::GenericMatrix< MatType >::cross (const MatType & a, const MatType & b, int dim = -1) static
Definition at line 778 of file generic_matrix.hpp.
{
     casadi_assert_message(a.size1()==b.size1() && a.size2()==b.size2(),
                           "cross(a, b): Inconsistent dimensions. Dimension of a ("
                           << a.dim() << " ) must equal that of b ("
                           << b.dim() << ").");
     casadi_assert_message(a.size1()==3 || a.size2()==3,
                           "cross(a, b): One of the dimensions of a should have length 3, but got "
                           << a.dim() << ".");
     casadi_assert_message(dim==-1 || dim==1 || dim==2,
                           "cross(a, b, dim): Dim must be 1, 2 or -1 (automatic).");
     std::vector<MatType> ret(3);
     bool t = a.size1()==3;
     if (dim==1) t = true;
     if (dim==2) t = false;
     MatType a1 = t ? a(0, Slice()) : a(Slice(), 0);
     MatType a2 = t ? a(1, Slice()) : a(Slice(), 1);
     MatType a3 = t ? a(2, Slice()) : a(Slice(), 2);
     MatType b1 = t ? b(0, Slice()) : b(Slice(), 0);
     MatType b2 = t ? b(1, Slice()) : b(Slice(), 1);
     MatType b3 = t ? b(2, Slice()) : b(Slice(), 2);
     ret[0] = a2*b3-a3*b2;
     ret[1] = a3*b1-a1*b3;
     ret[2] = a1*b2-a2*b1;
     return t ? vertcat(ret) : horzcat(ret);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, const std::vector< int > & output_offset) static inherited
Definition at line 597 of file sparsity_interface.hpp.
{
     casadi_assert_message(x.is_square(), "diagsplit(x,incr)::input must be square but got "
                           << x.dim()  << ".");
     return MatType::diagsplit(x, output_offset, output_offset);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, int incr) static inherited
Definition at line 605 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr>=1);
     casadi_assert_message(x.is_square(), "diagsplit(x,incr)::input must be square but got "
                           << x.dim()  << ".");
     std::vector<int> offset2 = range(0, x.size2(), incr);
     offset2.push_back(x.size2());
     return MatType::diagsplit(x, offset2);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, int incr1, int incr2) static inherited
Definition at line 616 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr1>=1);
     casadi_assert(incr2>=1);
     std::vector<int> offset1 = range(0, x.size1(), incr1);
     offset1.push_back(x.size1());
     std::vector<int> offset2 = range(0, x.size2(), incr2);
     offset2.push_back(x.size2());
     return MatType::diagsplit(x, offset1, offset2);
   }
template<typename MatType > std::string casadi::GenericMatrix< MatType >::dim () const
Definition at line 723 of file generic_matrix.hpp.
Referenced by casadi::Assertion::Assertion(), casadi::MX::attachAssert(), casadi::MXNode::getBinarySwitch(), casadi::MXNode::getMultiplication(), casadi::Inverse::Inverse(), casadi::MX::mac(), and casadi::Multiplication::Multiplication().
{
     return sparsity().dim();
   }
template<typename MatType> std::vector<int> casadi::GenericMatrix< MatType >::find (bool ind1 = SWIG_IND1) const inline
k = A.find() A[k] will contain the elements of A that are non-zero in B
Definition at line 160 of file generic_matrix.hpp.
 { return sparsity().find(ind1);}
template<typename MatType> std::vector<int> casadi::GenericMatrix< MatType >::get_colind () const inline
Definition at line 144 of file generic_matrix.hpp.
 { return sparsity().get_colind(); }
template<typename MatType> std::vector<int> casadi::GenericMatrix< MatType >::get_row () const inline
Definition at line 143 of file generic_matrix.hpp.
 { return sparsity().get_row(); }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::horzsplit (const MatType & x, int incr) static inherited
Definition at line 637 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr>=1);
     int sz2 = x.size2();
     std::vector<int> offset2 = range(0, sz2, incr);
     offset2.push_back(sz2);
     return MatType::horzsplit(x, offset2);
   }
template<typename MatType> MatType casadi::GenericMatrix< MatType >::inv_skew (const MatType & a) static
Definition at line 824 of file generic_matrix.hpp.
{
     casadi_assert_message(a.size1()==3 && a.size2()==3,
                           "inv_skew(a): Expecting 3-by-3 matrix, got " << a.dim() << ".");
     return 0.5*vertcat(std::vector<MatType>({a(2, 1)-a(1, 2), a(0, 2)-a(2, 0), a(1, 0)-a(0, 1)}));
   }
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_column () const inline
Definition at line 133 of file generic_matrix.hpp.
Referenced by casadi::DaeBuilder::attribute(), casadi::DaeBuilder::der(), casadi::Find::Find(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::Matrix< Scalar >::get_nz(), casadi::MX::get_nz(), casadi::is_slice(), casadi::MX::MX(), casadi::DaeBuilder::nominal(), casadi::MX::norm_2(), casadi::MX::polyval(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::DaeBuilder::set_attribute(), casadi::DaeBuilder::set_nominal(), casadi::DaeBuilder::unit(), and casadi::MX::vertsplit().
 { return sparsity().is_column();}
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_dense () const inline
Definition at line 118 of file generic_matrix.hpp.
Referenced by casadi::MX::densify(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::MXNode::getBinary(), casadi::MXNode::getMultiplication(), casadi::is_slice(), casadi::MX::MX(), casadi::MX::polyval(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), and casadi::MX::set_nz().
 { return sparsity().is_dense();}
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_empty (bool both = false) const inline
Definition at line 115 of file generic_matrix.hpp.
Referenced by casadi::DaeBuilder::add_lc(), casadi::SymbolicMX::join_primitives(), casadi::MX::project(), casadi::GenericCall::projectArg(), casadi::MX::simplify(), and casadi::DaeBuilder::unit().
 { return sparsity().is_empty(both);}
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_row () const inline
Definition at line 130 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::Matrix< Scalar >::get_nz(), and casadi::MX::get_nz().
 { return sparsity().is_row();}
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_scalar (bool scalar_and_dense = false) const
Definition at line 728 of file generic_matrix.hpp.
Referenced by casadi::Assertion::Assertion(), casadi::MX::attachAssert(), casadi::ConstantMX::create(), casadi::MX::densify(), casadi::BinaryMX< ScX, ScY >::evalAdj(), casadi::Matrix< Scalar >::get(), casadi::Matrix< Scalar >::get_nz(), casadi::MXNode::getBinarySwitch(), casadi::is_slice(), casadi::MX::mac(), casadi::MX::mldivide(), casadi::MX::mpower(), casadi::MX::mrdivide(), casadi::MX::mtimes(), casadi::MX::MX(), casadi::GenericCall::projectArg(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), and casadi::to_slice().
{
     return sparsity().is_scalar(scalar_and_dense);
   }
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_square () const inline
Definition at line 124 of file generic_matrix.hpp.
Referenced by casadi::MX::trace().
 { return sparsity().is_square();}
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_tril () const inline
Definition at line 139 of file generic_matrix.hpp.
 { return sparsity().is_tril();}
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_triu () const inline
Definition at line 136 of file generic_matrix.hpp.
 { return sparsity().is_triu();}
template<typename MatType> bool casadi::GenericMatrix< MatType >::is_vector () const inline
Definition at line 127 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::get(), and casadi::MX::get().
 { return sparsity().is_vector();}
template<typename MatType> MatType casadi::GenericMatrix< MatType >::linspace (const MatType & a, const MatType & b, int nsteps) static
Definition at line 765 of file generic_matrix.hpp.
{
     std::vector<MatType> ret(nsteps);
     ret[0] = a;
     MatType step = (b-a)/(nsteps-1);
     for (int i=1; i<nsteps-1; ++i)
       ret[i] = ret[i-1] + step;
     ret[nsteps-1] = b;
     return vertcat(ret);
   }
template<typename MatType> MatType casadi::SparsityInterface< MatType >::mtimes (const std::vector< MatType > & args) static inherited
Definition at line 627 of file sparsity_interface.hpp.
{
     casadi_assert_message(args.size()>=1,
                           "mul(std::vector<MatType> &args): "
                           "supplied list must not be empty.");
     MatType ret = args[0];
     for (int i=1; i<args.size(); ++i) ret = MatType::mtimes(ret, args[i]);
     return ret;
   }
template<typename MatType > int casadi::GenericMatrix< MatType >::nnz () const
Definition at line 678 of file generic_matrix.hpp.
Referenced by casadi::DaeBuilder::attribute(), casadi::ConstantMX::create(), casadi::MX::depends_on(), casadi::Diagsplit::Diagsplit(), casadi::HorzRepmat::evalGen(), casadi::MXFunction::expand(), casadi::HorzRepmat::generate(), casadi::MX::get_nz(), casadi::Constant< Value >::getBinary(), casadi::MXNode::getBinarySwitch(), casadi::SnoptInterface::init(), casadi::Scpgen::init(), casadi::SnoptInterface::init_memory(), casadi::SymbolicQr::linsol_eval_sx(), casadi::Monitor::Monitor(), casadi::mtaylor_recursive(), casadi::DaeBuilder::nominal(), casadi::MX::polyval(), casadi::Reshape::Reshape(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::DaeBuilder::set_attribute(), casadi::DaeBuilder::set_nominal(), casadi::MX::set_nz(), casadi::SnoptInterface::solve(), casadi::HorzRepmat::spAdj(), and casadi::HorzRepmat::spFwd().
{
     return sparsity().nnz();
   }
template<typename MatType > int casadi::GenericMatrix< MatType >::nnz_diag () const
Definition at line 693 of file generic_matrix.hpp.
{
     return sparsity().nnz_diag();
   }
template<typename MatType > int casadi::GenericMatrix< MatType >::nnz_lower () const
Definition at line 683 of file generic_matrix.hpp.
{
     return sparsity().nnz_lower();
   }
template<typename MatType > int casadi::GenericMatrix< MatType >::nnz_upper () const
Definition at line 688 of file generic_matrix.hpp.
{
     return sparsity().nnz_upper();
   }
template<typename MatType> static int casadi::GenericMatrix< MatType >::norm_0_mul (const MatType & x, const MatType & y) inline static
Definition at line 176 of file generic_matrix.hpp.
{
       return Sparsity::norm_0_mul(x.sparsity(), y.sparsity());
     }
template<typename MatType > int casadi::GenericMatrix< MatType >::numel () const
Definition at line 698 of file generic_matrix.hpp.
{
     return sparsity().numel();
   }
template<typename MatType> int casadi::GenericMatrix< MatType >::numel (int i) const inline
Definition at line 94 of file generic_matrix.hpp.
 { return 1;}
template<typename MatType> std::vector< int > casadi::SparsityInterface< MatType >::offset (const std::vector< MatType > & v, bool vert = true) static inherited
Definition at line 576 of file sparsity_interface.hpp.
{
     std::vector<int> ret(v.size()+1);
     ret[0]=0;
     for (int i=0; i<v.size(); ++i) {
       ret[i+1] = ret[i] + (vert ? v[i].size1() : v[i].size2());
     }
     return ret;
   }
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::ones (int nrow = 1, int ncol = 1) inline static
Definition at line 658 of file generic_matrix.hpp.
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::ones().
 { return ones(Sparsity::dense(nrow, ncol)); }
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::ones (const Sparsity & sp) inline static
Definition at line 659 of file generic_matrix.hpp.
 { return MatType(sp, 1, false);}
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::ones (const std::pair< int, int > & rc) inline static
Definition at line 660 of file generic_matrix.hpp.
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::ones().
 { return ones(rc.first, rc.second);}
template<typename MatType> template<typename RR > const MatType casadi::GenericMatrix< MatType >::operator() (const RR & rr) const inline
Definition at line 212 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr);
       return ret;
     }
template<typename MatType> template<typename RR , typename CC > const MatType casadi::GenericMatrix< MatType >::operator() (const RR & rr, const CC & cc) const inline
Definition at line 220 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr, cc);
       return ret;
     }
template<typename MatType> template<typename RR > SubIndex<MatType, RR> casadi::GenericMatrix< MatType >::operator() (const RR & rr) inline
Definition at line 228 of file generic_matrix.hpp.
{
       return SubIndex<MatType, RR>(self(), rr);
     }
template<typename MatType> template<typename RR , typename CC > SubMatrix<MatType, RR, CC> casadi::GenericMatrix< MatType >::operator() (const RR & rr, const CC & cc) inline
Definition at line 234 of file generic_matrix.hpp.
{
       return SubMatrix<MatType, RR, CC>(self(), rr, cc);
     }
template<typename MatType> template<typename K > const MatType casadi::GenericMatrix< MatType >::operator[] (const K & k) const inline
Definition at line 198 of file generic_matrix.hpp.
{
       MatType ret;
       self().get_nz(ret, false, k);
       return ret;
     }
template<typename MatType> template<typename K > NonZeros<MatType, K> casadi::GenericMatrix< MatType >::operator[] (const K & k) inline
Definition at line 206 of file generic_matrix.hpp.
{
       return NonZeros<MatType, K>(self(), k);
     }
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::rank1 (const MatType & A, const MatType & alpha, const MatType & x, const MatType & y) static
template<typename MatType> MatType casadi::SparsityInterface< MatType >::repmat (const MatType & x, int n, int m = 1) static inherited
Definition at line 544 of file sparsity_interface.hpp.
{
     MatType allrows = vertcat(std::vector<MatType>(n, x));
     return horzcat(std::vector<MatType>(m, allrows));
   }
template<typename MatType> static MatType casadi::SparsityInterface< MatType >::repmat (const MatType & A, const std::pair< int, int > & rc) inline static inherited
Definition at line 179 of file sparsity_interface.hpp.
{
       return MatType::repmat(A, rc.first, rc.second);
     }
template<typename MatType> MatType casadi::GenericMatrix< MatType >::repsum (const MatType & x, int n, int m = 1) static
Definition at line 844 of file generic_matrix.hpp.
{
     casadi_assert(x.size1() % n==0);
     casadi_assert(x.size2() % m==0);
     std::vector< std::vector< MatType> > s =
       blocksplit(x, x.size1()/n, x.size2()/m);
     MatType sum = 0;
     for (int i=0;i<s.size();++i) {
       for (int j=0;j<s[i].size();++j) {
         sum = sum + s[i][j];
       }
     }
     return sum;
   }
template<typename MatType> const int* casadi::GenericMatrix< MatType >::row () const inline
Definition at line 146 of file generic_matrix.hpp.
Referenced by casadi::MX::set(), casadi::SnoptInterface::solve(), and casadi::SnoptInterface::userfun().
 { return sparsity().row(); }
template<typename MatType> int casadi::GenericMatrix< MatType >::row (int el) const inline
Definition at line 149 of file generic_matrix.hpp.
 { return sparsity().row(el); }
template<typename MatType> const MatType& casadi::SparsityInterface< MatType >::self () const inline protected inherited
Definition at line 51 of file sparsity_interface.hpp.
 { return static_cast<const MatType&>(*this); }
template<typename MatType> MatType& casadi::SparsityInterface< MatType >::self () inline protected inherited
Definition at line 52 of file sparsity_interface.hpp.
 { return static_cast<MatType&>(*this); }
template<typename MatType > std::pair< int, int > casadi::GenericMatrix< MatType >::size () const
Definition at line 713 of file generic_matrix.hpp.
Referenced by casadi::MXNode::addDependency(), casadi::MX::blockcat(), casadi::MX::densify(), casadi::BinaryMX< ScX, ScY >::evalAdj(), casadi::MXFunction::generate_lifted(), casadi::MXNode::getBinary(), casadi::MXNode::getBinarySwitch(), casadi::SymbolicMX::join_primitives(), casadi::MX::kron(), casadi::MXNode::ndep(), casadi::GenericCall::projectArg(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), and casadi::MXNode::toMatrix().
{
     return sparsity().size();
   }
template<typename MatType > int casadi::GenericMatrix< MatType >::size (int axis) const
Definition at line 718 of file generic_matrix.hpp.
{
     return sparsity().size(axis);
   }
template<typename MatType > int casadi::GenericMatrix< MatType >::size1 () const
Definition at line 703 of file generic_matrix.hpp.
Referenced by casadi::MX::diagsplit(), casadi::Constant< Value >::getBinary(), casadi::MXNode::getDot(), casadi::MXNode::getMultiplication(), casadi::Inverse::Inverse(), casadi::MX::kron(), casadi::SymbolicQr::linsol_eval_sx(), casadi::MX::mac(), casadi::Multiplication::Multiplication(), casadi::MX::MX(), casadi::Matrix< Scalar >::pinv(), casadi::MX::pinv(), casadi::GenericCall::projectArg(), casadi::MX::reshape(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::RkIntegrator::setupFG(), casadi::simpleIRK(), casadi::Solve< Tr >::Solve(), casadi::MX::sum1(), and casadi::MX::vertsplit().
{
     return sparsity().size1();
   }
template<typename MatType > int casadi::GenericMatrix< MatType >::size2 () const
Definition at line 708 of file generic_matrix.hpp.
Referenced by casadi::bisect(), casadi::MX::diagsplit(), casadi::Mapaccum::get_reverse(), casadi::Constant< Value >::getBinary(), casadi::MXNode::getDot(), casadi::MXNode::getMultiplication(), casadi::HorzRepsum::HorzRepsum(), casadi::MX::horzsplit(), casadi::Inverse::Inverse(), casadi::MX::kron(), casadi::CsparseInterface::linsol_factorize(), casadi::MX::mac(), casadi::Multiplication::Multiplication(), casadi::Matrix< Scalar >::pinv(), casadi::MX::pinv(), casadi::GenericCall::projectArg(), casadi::MX::reshape(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::RkIntegrator::setupFG(), casadi::Matrix< Scalar >::solve(), casadi::Solve< Tr >::Solve(), casadi::SnoptInterface::solve(), casadi::MX::solve(), casadi::MX::sum2(), and casadi::MX::trace().
{
     return sparsity().size2();
   }
template<typename MatType> MatType casadi::GenericMatrix< MatType >::skew (const MatType & a) static
Definition at line 813 of file generic_matrix.hpp.
{
     casadi_assert_message(a.is_vector() && (a.size1()==3 || a.size2()==3),
                           "skew(a): Expecting 3-vector, got " << a.dim() << ".");
     MatType x = a(0);
     MatType y = a(1);
     MatType z = a(2);
     return blockcat(std::vector< std::vector<MatType> >({{0, -z, y}, {z, 0, -x}, {-y, x, 0}}));
   }
template<typename MatType > Sparsity & casadi::GenericMatrix< MatType >::sparsityRef ()
Definition at line 673 of file generic_matrix.hpp.
{
     return self().sparsityRef();
   }
template<typename MatType> static int casadi::GenericMatrix< MatType >::sprank (const MatType & x) inline static
Definition at line 175 of file generic_matrix.hpp.
 { return Sparsity::sprank(x.sparsity());}
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::sum_square (const MatType & x) inline static
Definition at line 185 of file generic_matrix.hpp.
 { return dot(x, x);}
template<typename MatType> casadi::GenericMatrix< MatType >::SWIG_CONSTREF (Sparsity) const
template<> SX casadi::GenericMatrix< SX >::sym (const string & name, const Sparsity & sp)
Definition at line 88 of file matrix.cpp.
References casadi::Sparsity::is_scalar(), and casadi::Sparsity::nnz().
{
     // Create a dense n-by-m matrix
     vector<SXElem> retv;
     // Check if individial names have been provided
     if (name[0]=='[') {
       // Make a copy of the string and modify it as to remove the special characters
       string modname = name;
       for (string::iterator it=modname.begin(); it!=modname.end(); ++it) {
         switch (*it) {
         case '(': case ')': case '[': case ']': case '{': case '}': case ',': case ';': *it = ' ';
         }
       }
       istringstream iss(modname);
       string varname;
       // Loop over elements
       while (!iss.fail()) {
         // Read the name
         iss >> varname;
         // Append to the return vector
         if (!iss.fail())
           retv.push_back(SXElem::sym(varname));
       }
     } else if (sp.is_scalar(true)) {
       retv.push_back(SXElem::sym(name));
     } else {
       // Scalar
       stringstream ss;
       for (int k=0; k<sp.nnz(); ++k) {
         ss.str("");
         ss << name << "_" << k;
         retv.push_back(SXElem::sym(ss.str()));
       }
     }
     // Determine dimensions automatically if empty
     if (sp.is_scalar(true)) {
       return SX(retv);
     } else {
       return SX(sp, retv, false);
     }
   }
template<> MX casadi::GenericMatrix< MX >::sym (const std::string & name, const Sparsity & sp)
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::sym (const std::string & name, int nrow = 1, int ncol = 1) inline static
Definition at line 615 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol));
     }
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::sym (const std::string & name, const std::pair< int, int > & rc) inline static
Definition at line 620 of file generic_matrix.hpp.
{
       return sym(name, rc.first, rc.second);
     }
template<typename MatType > MatType casadi::GenericMatrix< MatType >::sym (const std::string & name, const Sparsity & sp) static
Definition at line 760 of file generic_matrix.hpp.
{
     throw CasadiException("\"sym\" not defined for instantiation");
   }
template<typename MatType > std::vector< MatType > casadi::GenericMatrix< MatType >::sym (const std::string & name, const Sparsity & sp, int p) static
Definition at line 735 of file generic_matrix.hpp.
{
     std::vector<MatType> ret(p);
     std::stringstream ss;
     for (int k=0; k<p; ++k) {
       ss.str("");
       ss << name << k;
       ret[k] = sym(ss.str(), sp);
     }
     return ret;
   }
template<typename MatType> static std::vector<MatType > casadi::GenericMatrix< MatType >::sym (const std::string & name, int nrow, int ncol, int p) inline static
Definition at line 632 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p);
     }
template<typename MatType > std::vector< std::vector< MatType > > casadi::GenericMatrix< MatType >::sym (const std::string & name, const Sparsity & sp, int p, int r) static
Definition at line 748 of file generic_matrix.hpp.
{
     std::vector<std::vector<MatType> > ret(r);
     for (int k=0; k<r; ++k) {
       std::stringstream ss;
       ss << name << "_" << k;
       ret[k] = sym(ss.str(), sp, p);
     }
     return ret;
   }
template<typename MatType> static std::vector<std::vector<MatType> > casadi::GenericMatrix< MatType >::sym (const std::string & name, int nrow, int ncol, int p, int r) inline static
Definition at line 644 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p, r);
     }
template<> MX casadi::GenericMatrix< MX >::sym (const std::string & name, const Sparsity & sp)
Definition at line 746 of file mx.cpp.
References casadi::Sparsity::nnz().
{
     if (sp.nnz()==0) {
       return MX(sp);
     } else {
       return MX::create(new SymbolicMX(name, sp));
     }
   }
template<> SX casadi::GenericMatrix< SX >::sym (const std::string & name, const Sparsity & sp)
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::tril (const MatType & x, bool includeDiagonal = true) inline static
Definition at line 179 of file generic_matrix.hpp.
{
       return project(x, Sparsity::tril(x.sparsity(), includeDiagonal));
     }
template<typename MatType> MatType casadi::GenericMatrix< MatType >::tril2symm (const MatType & x) static
Definition at line 833 of file generic_matrix.hpp.
{
     casadi_assert_message(x.is_square(),
                           "Shape error in tril2symm. Expecting square shape but got "
                           << x.dim());
     casadi_assert_message(x.nnz_upper()-x.nnz_diag()==0,
                           "Sparsity error in tril2symm. Found above-diagonal entries in argument: "
                           << x.dim());
     return x +  x.T() - diag(diag(x));
   }
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::triu (const MatType & x, bool includeDiagonal = true) inline static
Definition at line 182 of file generic_matrix.hpp.
{
       return project(x, Sparsity::triu(x.sparsity(), includeDiagonal));
     }
template<typename MatType> MatType casadi::GenericMatrix< MatType >::triu2symm (const MatType & x) static
Definition at line 859 of file generic_matrix.hpp.
{
     casadi_assert_message(x.is_square(),
                           "Shape error in triu2symm. Expecting square shape but got "
                           << x.dim());
     casadi_assert_message(x.nnz_lower()-x.nnz_diag()==0,
                           "Sparsity error in triu2symm. Found below-diagonal entries in argument: "
                           << x.dim());
     return x + x.T() - diag(diag(x));
   }
template<typename MatType> MatType casadi::SparsityInterface< MatType >::vec (const MatType & x) static inherited
Definition at line 539 of file sparsity_interface.hpp.
{
     return reshape(x, x.numel(), 1);
   }
template<typename MatType> MatType casadi::SparsityInterface< MatType >::veccat (const std::vector< MatType > & x) static inherited
Definition at line 586 of file sparsity_interface.hpp.
{
     std::vector< MatType > x_vec = x;
     for (typename std::vector< MatType >::iterator it=x_vec.begin();
          it!=x_vec.end(); ++it) {
       *it = vec(*it);
     }
     return vertcat(x_vec);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::vertsplit (const MatType & x, int incr) static inherited
Definition at line 646 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr>=1);
     int sz1 = x.size1();
     std::vector<int> offset1 = range(0, sz1, incr);
     offset1.push_back(sz1);
     return MatType::vertsplit(x, offset1);
   }
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::zeros (int nrow = 1, int ncol = 1) inline static
Definition at line 651 of file generic_matrix.hpp.
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::zeros().
 { return zeros(Sparsity::dense(nrow, ncol)); }
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::zeros (const Sparsity & sp) inline static
Definition at line 652 of file generic_matrix.hpp.
 { return MatType(sp, 0, false);}
template<typename MatType> static MatType casadi::GenericMatrix< MatType >::zeros (const std::pair< int, int > & rc) inline static
Definition at line 653 of file generic_matrix.hpp.
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::zeros().
 { return zeros(rc.first, rc.second);}
Friends And Related Function Documentation
template<typename MatType> MatType casadi::GenericMatrix< MatType >::bilin (const MatType & A, const MatType & x, const MatType & y) friend
Definition at line 273 of file generic_matrix.hpp.
{
       return MatType::bilin(A, x, y);
     }
template<typename MatType> MatType conditional (const MatType & ind, const std::vector< MatType > & x, const MatType & x_default, bool short_circuit = true) friend
If the condition
Parameters
ind evaluates to the integer k, where 0<=k<f.size(), then x[k] will be returned, otherwise
x_default will be returned.
Definition at line 428 of file generic_matrix.hpp.
{
       return MatType::conditional(ind, x, x_default, short_circuit);
     }
template<typename MatType> MatType cross (const MatType & a, const MatType & b, int dim = -1) friend
Definition at line 305 of file generic_matrix.hpp.
{
       return MatType::cross(a, b, dim);
     }
template<typename MatType> MatType densify (const MatType & x) friend
Definition at line 397 of file generic_matrix.hpp.
{
       return MatType::densify(x);
     }
template<typename MatType> MatType densify (const MatType & x, const MatType & val) friend
Definition at line 403 of file generic_matrix.hpp.
{
       return MatType::densify(x, val);
     }
template<typename MatType> bool depends_on (const MatType & f, const MatType & arg) friend
Definition at line 436 of file generic_matrix.hpp.
{
       return MatType::depends_on(f, arg);
     }
template<typename MatType> MatType det (const MatType & A) friend
Definition at line 322 of file generic_matrix.hpp.
 { return MatType::det(A);}
template<typename MatType> MatType diag (const MatType & A) friend
Definition at line 385 of file generic_matrix.hpp.
{
       return MatType::diag(A);
     }
template<typename MatType> MatType dot (const MatType & x, const MatType & y) friend
Definition at line 359 of file generic_matrix.hpp.
{
       return MatType::dot(x, y);
     }
template<typename MatType> MatType gradient (const MatType & ex, const MatType & arg) friend
Definition at line 524 of file generic_matrix.hpp.
{
       return MatType::gradient(ex, arg);
     }
template<typename MatType> MatType hessian (const MatType & ex, const MatType & arg) friend
Definition at line 546 of file generic_matrix.hpp.
{
       return MatType::hessian(ex, arg);
     }
template<typename MatType> MatType hessian (const MatType & ex, const MatType & arg, MatType & output_g) friend
Definition at line 549 of file generic_matrix.hpp.
{
       return MatType::hessian(ex, arg, output_g);
     }
template<typename MatType> MatType if_else (const MatType & cond, const MatType & if_true, const MatType & if_false, bool short_circuit = true) friend
Definition at line 418 of file generic_matrix.hpp.
{
       return MatType::if_else(cond, if_true, if_false, short_circuit);
     }
template<typename MatType> MatType inv (const MatType & A) friend
Definition at line 325 of file generic_matrix.hpp.
 { return MatType::inv(A);}
template<typename MatType> MatType inv_skew (const MatType & a) friend
Definition at line 317 of file generic_matrix.hpp.
{
       return MatType::inv_skew(a);
     }
template<typename MatType> MatType jacobian (const MatType & ex, const MatType & arg, bool symmetric = false) friend
Definition at line 521 of file generic_matrix.hpp.
{
       return MatType::jacobian(ex, arg, symmetric);
     }
template<typename MatType> MatType jtimes (const MatType & ex, const MatType & arg, const MatType & v, bool tr = false) friend
Definition at line 539 of file generic_matrix.hpp.
{
       return MatType::jtimes(ex, arg, v, tr);
     }
template<typename MatType> MatType linspace (const MatType & a, const MatType & b, int nsteps) friend
Definition at line 299 of file generic_matrix.hpp.
{
       return MatType::linspace(a, b, nsteps);
     }
template<typename MatType> MatType mldivide (const MatType & x, const MatType & n) friend
Definition at line 258 of file generic_matrix.hpp.
{
       return MatType::mldivide(x, n);
     }
template<typename MatType> MatType mrdivide (const MatType & x, const MatType & n) friend
Definition at line 252 of file generic_matrix.hpp.
{
       return MatType::mrdivide(x, n);
     }
template<typename MatType> int n_nodes (const MatType & A) friend
Count number of nodes
Definition at line 562 of file generic_matrix.hpp.
{
       return MatType::n_nodes(A);
     }
template<typename MatType> std::vector<bool> nl_var (const MatType & expr, const MatType & var) friend
Definition at line 556 of file generic_matrix.hpp.
{
       return MatType::nl_var(expr, var);
     }
template<typename MatType> MatType norm_1 (const MatType & x) friend
Definition at line 345 of file generic_matrix.hpp.
 { return MatType::norm_1(x);}
template<typename MatType> MatType norm_2 (const MatType & x) friend
Definition at line 342 of file generic_matrix.hpp.
 { return MatType::norm_2(x);}
template<typename MatType> MatType norm_F (const MatType & x) friend
Definition at line 339 of file generic_matrix.hpp.
 { return MatType::norm_F(x);}
template<typename MatType> MatType norm_inf (const MatType & x) friend
Definition at line 348 of file generic_matrix.hpp.
 { return MatType::norm_inf(x);}
template<typename MatType> MatType nullspace (const MatType & A) friend
Finds Z m-by-(m-n) such that AZ = 0 with A n-by-m with m > n
Assumes A is full rank
Inspired by Numerical Methods in Scientific Computing by Ake Bjorck
Definition at line 372 of file generic_matrix.hpp.
{
       return MatType::nullspace(A);
     }
template<typename MatType> MatType pinv (const MatType & A) friend
If the matrix A is fat (size1<size2), mul(A, pinv(A)) is unity.
pinv(A)' = (AA')^(-1) A
If the matrix A is slender (size1>size2), mul(pinv(A), A) is unity.
pinv(A) = (A'A)^(-1) A'
Definition at line 503 of file generic_matrix.hpp.
{
       return MatType::pinv(A);
     }
template<typename MatType> MatType pinv (const MatType & A, const std::string & lsolver, const Dict & dict = Dict()) friend
If the matrix A is fat (size1>size2), mul(A, pinv(A)) is unity. If the matrix A is slender (size2<size1), mul(pinv(A), A) is unity.
Definition at line 513 of file generic_matrix.hpp.
{
       return MatType::pinv(A, lsolver, dict);
     }
template<typename MatType> MatType polyval (const MatType & p, const MatType & x) friend
Definition at line 378 of file generic_matrix.hpp.
{
       return MatType::polyval(p, x);
     }
template<typename MatType> std::string print_operator (const MatType & xb, const std::vector< std::string > & args) friend
Definition at line 573 of file generic_matrix.hpp.
{
       return MatType::print_operator(xb, args);
     }
template<typename MatType> MatType project (const MatType & A, const Sparsity & sp, bool intersect = false) friend
Definition at line 410 of file generic_matrix.hpp.
{
       return MatType::project(A, sp, intersect);
     }
template<typename MatType> MatType casadi::GenericMatrix< MatType >::rank1 (const MatType & A, const MatType & alpha, const MatType & x, const MatType & y) friend
Definition at line 283 of file generic_matrix.hpp.
{
       return MatType::rank1(A, alpha, x, y);
     }
template<typename MatType> MatType repsum (const MatType & A, int n, int m = 1) friend
Definition at line 599 of file generic_matrix.hpp.
{
       return MatType::repsum(A, n, m);
     }
template<typename MatType> void shared (std::vector< MatType > & ex, std::vector< MatType > & v, std::vector< MatType > & vdef, const std::string & v_prefix = "v_", const std::string & v_suffix = "") friend
Definition at line 578 of file generic_matrix.hpp.
{
       MatType::shared(ex, v, vdef, v_prefix, v_suffix);
     }
template<typename MatType> void shared (const std::vector< MatType > & ex, std::vector< MatType > & ex_output, std::vector< MatType > & v, std::vector< MatType > & vdef, const std::string & v_prefix = "v_", const std::string & v_suffix = "") friend
Definition at line 587 of file generic_matrix.hpp.
{
       ex_output = ex;
       shared(ex_output, v, vdef, v_prefix, v_suffix);
     }
template<typename MatType> MatType simplify (const MatType & x) friend
Definition at line 567 of file generic_matrix.hpp.
{
       return MatType::simplify(x);
     }
template<typename MatType> MatType skew (const MatType & a) friend
Definition at line 311 of file generic_matrix.hpp.
{
       return MatType::skew(a);
     }
template<typename MatType> MatType solve (const MatType & A, const MatType & b) friend
A simple forward or backward substitution if A is upper or lower triangular
If the linear system is at most 3-by-3, form the inverse via minor expansion and multiply
Permute the variables and equations as to get a (structurally) nonzero diagonal, then perform a QR factorization without pivoting and solve the factorized system.
Note 1: If there are entries of the linear system known to be zero, these will be removed. Elements that are very small, or will evaluate to be zero, can still cause numerical errors, due to the lack of pivoting (which is not possible since cannot compare the size of entries)
Note 2: When permuting the linear system, a BLT (block lower triangular) transformation is formed. Only the permutation part of this is however used. An improvement would be to solve block-by-block if there are multiple BLT blocks.
Definition at line 479 of file generic_matrix.hpp.
{
       return MatType::solve(A, b);
     }
template<typename MatType> MatType solve (const MatType & A, const MatType & b, const std::string & lsolver, const Dict & dict = Dict()) friend
Definition at line 485 of file generic_matrix.hpp.
{
       return MatType::solve(A, b, lsolver, dict);
     }
template<typename MatType> MatType substitute (const MatType & ex, const MatType & v, const MatType & vdef) friend
Definition at line 441 of file generic_matrix.hpp.
{
       return MatType::substitute(ex, v, vdef);
     }
template<typename MatType> std::vector<MatType> substitute (const std::vector< MatType > & ex, const std::vector< MatType > & v, const std::vector< MatType > & vdef) friend
Definition at line 448 of file generic_matrix.hpp.
{
       return MatType::substitute(ex, v, vdef);
     }
template<typename MatType> void substitute_inplace (const std::vector< MatType > & v, std::vector< MatType > & inout_vdef, std::vector< MatType > & inout_ex, bool reverse = false) friend
Definition at line 457 of file generic_matrix.hpp.
{
       return MatType::substitute_inplace(v, inout_vdef, inout_ex, reverse);
     }
template<typename MatType> MatType sum1 (const MatType & x) friend
Definition at line 351 of file generic_matrix.hpp.
 { return MatType::sum1(x);}
template<typename MatType> MatType sum2 (const MatType & x) friend
Definition at line 354 of file generic_matrix.hpp.
 { return MatType::sum2(x);}
template<typename MatType> MatType sum_square (const MatType & x) friend
Definition at line 293 of file generic_matrix.hpp.
{
       return MatType::sum_square(x);
     }
template<typename MatType> std::vector<MatType> symvar (const MatType & x) friend
See also
SXFunction::getFree(), MXFunction::getFree()
Definition at line 266 of file generic_matrix.hpp.
{
       return MatType::symvar(x);
     }
template<typename MatType> MatType tangent (const MatType & ex, const MatType & arg) friend
Definition at line 527 of file generic_matrix.hpp.
{
       return MatType::tangent(ex, arg);
     }
template<typename MatType> MatType trace (const MatType & x) friend
Definition at line 328 of file generic_matrix.hpp.
 { return MatType::trace(x);}
template<typename MatType> MatType tril2symm (const MatType & a) friend
Definition at line 332 of file generic_matrix.hpp.
 { return MatType::tril2symm(a);}
template<typename MatType> MatType triu2symm (const MatType & a) friend
Definition at line 336 of file generic_matrix.hpp.
 { return MatType::triu2symm(a);}
template<typename MatType> MatType unite (const MatType & A, const MatType & B) friend
Definition at line 391 of file generic_matrix.hpp.
{
       return MatType::unite(A, B);
     }
The documentation for this class was generated from the following file:
generic_matrix.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge