CasADi: casadi::LibOracle< LibType > Class Template Reference
casadi::LibOracle< LibType > Class Template Reference
#include <oracle.hpp>
Detailed Description
template<typename LibType>
class casadi::LibOracle< LibType >
Problem stored externally
Definition at line 154 of file oracle.hpp.
Public Member Functions
LibOracle (const LibType &libtype, const std::string &all_io)
virtual ~LibOracle ()
virtual Oracle * clone () const
virtual const Sparsity & sparsity_in (int i) const
virtual const Sparsity & sparsity_out (int i) const
virtual Function create (const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const std::vector< LinComb > &lincomb, const Dict &opts) const
virtual std::string type_name () const
Get type name.
virtual Oracle * expand () const
virtual std::string name_in (int i) const
virtual std::string name_out (int i) const
virtual std::vector< bool > nl_var (const std::string &s_in, const std::vector< std::string > &s_out) const
Which variables enter nonlinearly.
virtual Function all_io (const std::string &fname="all_io", const Dict &opts=Dict()) const
Generate a function with all inputs and outputs.
Static Public Member Functions
static Oracle * construct (const std::vector< SX > &in, const std::vector< SX > &out, const std::vector< std::string > &ischeme, const std::vector< std::string > &oscheme)
static Oracle * construct (const std::vector< MX > &in, const std::vector< MX > &out, const std::vector< std::string > &ischeme, const std::vector< std::string > &oscheme)
static Oracle * construct (const std::string &fname, const std::string &all_io="all_io")
static Oracle * construct (const Compiler &compiler, const std::string &all_io="all_io")
Constructor & Destructor Documentation
template<typename LibType > casadi::LibOracle< LibType >::LibOracle (const LibType & libtype, const std::string & all_io)
Definition at line 270 of file oracle.cpp.
References casadi::external().
     : libtype_(libtype) {
     all_io_ = external(all_io, libtype);
   }
template<typename LibType> virtual casadi::LibOracle< LibType >::~LibOracle () inline virtual
Definition at line 163 of file oracle.hpp.
 {}
Member Function Documentation
Function casadi::Oracle::all_io (const std::string & fname = "all_io", const Dict & opts = Dict()) const virtual inherited
Reimplemented in casadi::XOracle< XType >.
Definition at line 260 of file oracle.cpp.
Referenced by casadi::Oracle::expand(), and casadi::Nlpsol::generate_dependencies().
{
     casadi_error("'all_io' not defined for " + type_name());
   }
template<typename LibType> virtual Oracle* casadi::LibOracle< LibType >::clone () const inline virtual
Implements casadi::Oracle.
Definition at line 166 of file oracle.hpp.
 { return new LibOracle(*this);}
Oracle * casadi::Oracle::construct (const std::vector< SX > & in, const std::vector< SX > & out, const std::vector< std::string > & ischeme, const std::vector< std::string > & oscheme) static inherited
Definition at line 214 of file oracle.cpp.
Referenced by casadi::Oracle::expand(), casadi::Nlpsol::fun2problem(), casadi::Integrator::fun2problem(), casadi::Nlpsol::map2problem(), and casadi::Integrator::map2problem().
{
     return new XOracle<SX>(in, out, ischeme, oscheme);
   }
Oracle * casadi::Oracle::construct (const std::vector< MX > & in, const std::vector< MX > & out, const std::vector< std::string > & ischeme, const std::vector< std::string > & oscheme) static inherited
Definition at line 221 of file oracle.cpp.
{
     return new XOracle<MX>(in, out, ischeme, oscheme);
   }
Oracle * casadi::Oracle::construct (const std::string & fname, const std::string & all_io = "all_io") static inherited
Definition at line 232 of file oracle.cpp.
{
     // If fname ends with .c, JIT
     if (fname.size()>2 && fname.compare(fname.size()-2, fname.size(), ".c")==0) {
       Compiler compiler(fname, "clang");
       return construct(compiler, all_io);
     } else {
       return new LibOracle<std::string>(fname, all_io);
     }
   }
Oracle * casadi::Oracle::construct (const Compiler & compiler, const std::string & all_io = "all_io") static inherited
Definition at line 228 of file oracle.cpp.
{
     return new LibOracle<Compiler>(compiler, all_io);
   }
template<typename LibType > Function casadi::LibOracle< LibType >::create (const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const std::vector< LinComb > & lincomb, const Dict & opts) const virtual
Implements casadi::Oracle.
Definition at line 286 of file oracle.cpp.
References casadi::external(), casadi::Function::n_in(), and casadi::Function::n_out().
{
     Function ret = external(fname, libtype_, opts);
     casadi_assert(s_in.size()==ret.n_in());
     casadi_assert(s_out.size()==ret.n_out());
     return ret;
   }
Oracle * casadi::Oracle::expand () const virtual inherited
Definition at line 302 of file oracle.cpp.
References casadi::Oracle::all_io(), casadi::Oracle::construct(), casadi::Function::expand(), casadi::Function::is_a(), casadi::Function::name_in(), casadi::Function::name_out(), and casadi::Function::sx_in().
Referenced by casadi::Integrator::init(), and casadi::Nlpsol::init().
{
     // Get a MX function from all inputs to all outputs
     Function f = all_io();
     // Expand to SX
     if (!f.is_a("sxfunction")) {
       f = f.expand();
     }
     // Get expressions
     vector<SX> arg = f.sx_in();
     vector<SX> res = f(arg);
     // Construct SX oracle
     return construct(arg, res, f.name_in(), f.name_out());
   }
std::string casadi::Oracle::name_in (int i) const virtual inherited
Reimplemented in casadi::XOracle< XType >.
Definition at line 247 of file oracle.cpp.
{
     casadi_error("'name_in' not defined for " + type_name());
   }
std::string casadi::Oracle::name_out (int i) const virtual inherited
Reimplemented in casadi::XOracle< XType >.
Definition at line 251 of file oracle.cpp.
{
     casadi_error("'name_out' not defined for " + type_name());
   }
std::vector< bool > casadi::Oracle::nl_var (const std::string & s_in, const std::vector< std::string > & s_out) const virtual inherited
Reimplemented in casadi::XOracle< XType >.
Definition at line 242 of file oracle.cpp.
Referenced by casadi::Nlpsol::nl_var().
{
     casadi_error("'nl_var' not defined for " + type_name());
   }
template<typename LibType > const Sparsity & casadi::LibOracle< LibType >::sparsity_in (int i) const virtual
Implements casadi::Oracle.
Definition at line 276 of file oracle.cpp.
{
     return all_io_.sparsity_in(i);
   }
template<typename LibType > const Sparsity & casadi::LibOracle< LibType >::sparsity_out (int i) const virtual
Implements casadi::Oracle.
Definition at line 281 of file oracle.cpp.
{
     return all_io_.sparsity_out(i);
   }
template<typename LibType > std::string casadi::LibOracle< LibType >::type_name () const virtual
Implements casadi::Oracle.
Definition at line 298 of file oracle.cpp.
{
     return "LibOracle";
   }
The documentation for this class was generated from the following files:
oracle.hpp
oracle.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge