CasADi: casadi::Nlpsol Class Reference
casadi::Nlpsol Class Reference abstract
NLP solver storage class.
#include <nlpsol_impl.hpp>
Detailed Description
Author
Joel Andersson
Date
2010-2013
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". casadi::FunctionInternal
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
eval_errors_fatal OT_BOOL When errors occur during evaluation of f,g,...,stop the iterations casadi::Nlpsol
expand OT_BOOL Replace MX with SX expressions in problem formulation [false] casadi::Nlpsol
gather_stats OT_BOOL Flag to indicate whether statistics must be gathered casadi::FunctionInternal
ignore_check_vec OT_BOOL If set to true, the input shape of F will not be checked. casadi::Nlpsol
input_scheme OT_STRINGVECTOR Custom input scheme casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
iteration_callback OT_FUNCTION A function that will be called at each iteration with the solver as input. Check documentation of Callback. casadi::Nlpsol
iteration_callback_ignore_errors OT_BOOL If set to true, errors thrown by iteration_callback will be ignored. casadi::Nlpsol
iteration_callback_step OT_INT Only call the callback function every few iterations. casadi::Nlpsol
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
monitor OT_STRINGVECTOR Monitors to be activated casadi::FunctionInternal
output_scheme OT_STRINGVECTOR Custom output scheme casadi::FunctionInternal
print_time OT_BOOL print information about execution time casadi::Nlpsol
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::FunctionInternal
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::FunctionInternal
verbose_init OT_BOOL Print out timing information about the different stages of initialization casadi::Nlpsol
warn_initial_bounds OT_BOOL Warn if the initial guess does not satisfy LBX and UBX casadi::Nlpsol
Definition at line 59 of file nlpsol_impl.hpp.
Classes
struct Exposed
Public Types
typedef Nlpsol *(* Creator)(const std::string &name, Oracle *nlp)
typedef int(* RegFcn)(Plugin *plugin)
Public Member Functions
Nlpsol (const std::string &name, Oracle *nlp)
Constructor.
virtual ~Nlpsol ()=0
Destructor.
virtual void init (const Dict &opts)
Initialize.
virtual void * alloc_memory () const
Create memory block.
virtual void free_memory (void *mem) const
Free memory block.
virtual void init_memory (void *mem) const
Initalize memory block.
virtual void checkInputs (void *mem) const
Check if the inputs correspond to a well-posed problem.
virtual double default_in (int ind) const
Get default input value.
virtual void set_work (void *mem, const double **&arg, double **&res, int *&iw, double *&w) const
Set the (persistent) work vectors.
virtual void set_temp (void *mem, const double **arg, double **res, int *iw, double *w) const
Set the (temporary) work vectors.
Function create_function (const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const std::vector< LinComb > &lincomb=std::vector< LinComb >(), const Dict &opts=Dict(), bool reg=true)
void register_function (const Function &fcn)
std::vector< bool > nl_var (const std::string &s_in, const std::vector< std::string > &s_out) const
Which variables enter nonlinearly.
virtual void eval (void *mem, const double **arg, double **res, int *iw, double *w) const
Evaluate numerically.
virtual void solve (void *mem) const =0
int calc_function (NlpsolMemory *m, const Function &fcn, std::initializer_list< const double * > arg, std::initializer_list< double * > res) const
void print_fstats (const NlpsolMemory *m) const
Print statistics.
virtual Dict get_stats (void *mem) const
Get all statistics.
virtual void generate_dependencies (const std::string &fname, const Dict &opts)
Export / Generate C code for the dependency function.
virtual DM getReducedHessian ()
virtual void setOptionsFromFile (const std::string &file)
Read options from parameter xml.
virtual std::string getAdaptorSolverName () const
Obtain solver name from Adaptor.
void construct (const Dict &opts)
Construct Prepares the function for evaluation.
virtual void finalize ()
Finalize the object creation This function, which visits the class hierarchy in reverse order is run after init() has been completed.
Function function () const
Get a public class instance.
virtual bool spCanEvaluate (bool fwd)
Is the class able to propagate seeds through the algorithm?
virtual void simple (const double *arg, double *res)
Evaluate numerically, simplied syntax.
virtual void eval_sx (const SXElem **arg, SXElem **res, int *iw, SXElem *w, int mem)
Evaluate with symbolic scalars.
template<typename M >
void call (const std::vector< M > &arg, std::vector< M > &res, bool always_inline, bool never_inline)
Call a function, templated.
template<typename M >
void checkArg (const std::vector< M > &arg, bool hcat=false) const
Check if input arguments have correct length and dimensions.
template<typename M >
void checkRes (const std::vector< M > &res) const
Check if output arguments have correct length and dimensions.
template<typename M >
bool matchingArg (const std::vector< M > &arg, bool hcat=false) const
Check if input arguments that needs to be replaced.
template<typename M >
bool matchingRes (const std::vector< M > &arg) const
Check if output arguments that needs to be replaced.
template<typename M >
std::vector< M > replaceArg (const std::vector< M > &arg, bool hcat=false) const
Replace 0-by-0 inputs.
template<typename M >
std::vector< M > replaceRes (const std::vector< M > &res) const
Replace 0-by-0 outputs.
template<typename M >
std::vector< std::vector< M > > replaceFwdSeed (const std::vector< std::vector< M > > &fseed) const
Replace 0-by-0 forward seeds.
template<typename M >
std::vector< std::vector< M > > replaceAdjSeed (const std::vector< std::vector< M > > &aseed) const
Replace 0-by-0 reverse seeds.
virtual std::vector< MX > create_call (const std::vector< MX > &arg)
Create call.
template<typename M >
void forward (const std::vector< M > &arg, const std::vector< M > &res, const std::vector< std::vector< M > > &fseed, std::vector< std::vector< M > > &fsens, bool always_inline, bool never_inline)
Forward mode AD, templated.
template<typename M >
void reverse (const std::vector< M > &arg, const std::vector< M > &res, const std::vector< std::vector< M > > &aseed, std::vector< std::vector< M > > &asens, bool always_inline, bool never_inline)
Reverse mode AD, templated.
bool hasDerivative () const
Can derivatives be calculated in any way?
virtual double adWeight ()
Weighting factor for chosing forward/reverse mode.
virtual double adWeightSp ()
Weighting factor for chosing forward/reverse mode, sparsity propagation.
virtual MX grad_mx (int iind=0, int oind=0)
Gradient expression.
virtual MX tang_mx (int iind=0, int oind=0)
Tangent expression.
virtual MX jac_mx (int iind=0, int oind=0, bool compact=false, bool symmetric=false, bool always_inline=true, bool never_inline=false)
Jacobian expression.
virtual SX grad_sx (int iind=0, int oind=0)
Gradient expression.
virtual SX tang_sx (int iind=0, int oind=0)
Tangent expression.
virtual SX jac_sx (int iind=0, int oind=0, bool compact=false, bool symmetric=false, bool always_inline=true, bool never_inline=false)
Jacobian expression.
virtual SX hess_sx (int iind=0, int oind=0)
Hessian expression.
virtual std::vector< MX > free_mx () const
Get free variables (MX)
virtual SX free_sx () const
Get free variables (SX)
virtual bool has_free () const
Does the function have free variables.
virtual void generate_lifted (Function &vdef_fcn, Function &vinit_fcn)
Extract the functions needed for the Lifted Newton method.
virtual int getAlgorithmSize () const
Get the number of atomic operations.
virtual int getWorkSize () const
Get the length of the work vector.
virtual int getAtomicOperation (int k) const
Get an atomic operation operator index.
virtual std::pair< int, int > getAtomicInput (int k) const
Get the (integer) input arguments of an atomic operation.
virtual double getAtomicInputReal (int k) const
Get the floating point output argument of an atomic operation.
virtual int getAtomicOutput (int k) const
Get the (integer) output argument of an atomic operation.
virtual int n_nodes () const
Number of nodes in the algorithm.
Function wrapMXFunction ()
Create a helper MXFunction with some properties copied.
virtual void generateFunction (CodeGenerator &g, const std::string &fname, bool decl_static) const
Generate code the function.
void generateMeta (CodeGenerator &g, const std::string &fname) const
Generate meta-information allowing a user to evaluate a generated function.
virtual bool simplifiedCall () const
Use simplified signature.
virtual std::string codegen_name (const CodeGenerator &g) const
Get name in codegen.
virtual void addDependency (CodeGenerator &g) const
Add a dependent function.
virtual void codegen_incref (CodeGenerator &g) const
Codegen incref for dependencies.
virtual void codegen_decref (CodeGenerator &g) const
Codegen decref for dependencies.
std::string signature (const std::string &fname) const
Code generate the function.
virtual void generateDeclarations (CodeGenerator &g) const
Generate code for the declarations of the C function.
virtual void generateBody (CodeGenerator &g) const
Generate code for the function body.
virtual void print (std::ostream &stream) const
Print.
virtual void repr (std::ostream &stream) const
Print.
virtual void checkInputs () const
Check if the numerical values of the supplied bounds make sense.
void printDimensions (std::ostream &stream) const
Print dimensions of inputs and outputs.
void printOptions (std::ostream &stream) const
Print list of options.
void printOption (const std::string &name, std::ostream &stream) const
Print all information there is to know about a certain option.
void getPartition (int iind, int oind, Sparsity &D1, Sparsity &D2, bool compact, bool symmetric)
Get the unidirectional or bidirectional partition.
bool verbose () const
Verbose mode?
bool monitored (const std::string &mod) const
Is function fcn being monitored.
const std::string & name () const
Name of the function.
virtual Sparsity getJacSparsity (int iind, int oind, bool symmetric)
Generate the sparsity of a Jacobian block.
template<bool fwd>
Sparsity getJacSparsityGen (int iind, int oind, bool symmetric, int gr_i=1, int gr_o=1)
Get the sparsity pattern, forward mode.
Sparsity getJacSparsityHierarchical (int iind, int oind)
A flavor of getJacSparsity that does hierarchical block structure recognition.
Sparsity getJacSparsityHierarchicalSymm (int iind, int oind)
void set_jac_sparsity (const Sparsity &sp, int iind, int oind, bool compact)
Generate the sparsity of a Jacobian block.
Sparsity & sparsity_jac (int iind, int oind, bool compact, bool symmetric)
Get, if necessary generate, the sparsity of a Jacobian block.
virtual std::vector< MX > symbolicOutput (const std::vector< MX > &arg)
Get a vector of symbolic variables corresponding to the outputs.
virtual int index_in (const std::string &name) const
Get input scheme index by name.
virtual int index_out (const std::string &name) const
Get output scheme index by name.
virtual std::string name_in (int ind) const
Get input scheme name by index.
virtual std::string name_out (int ind) const
Get output scheme name by index.
void log (const std::string &msg) const
Log the status of the solver.
void log (const std::string &fcn, const std::string &msg) const
Log the status of the solver, function given.
Function dynamicCompilation (Function f, std::string fname, std::string fdescr, std::string compiler)
Codegen function.
virtual void spFwd (const bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem)
Propagate sparsity forward.
virtual void spAdj (bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem)
Propagate sparsity backwards.
void sz_work (size_t &sz_arg, size_t &sz_res, size_t &sz_iw, size_t &sz_w) const
Get number of temporary variables needed.
size_t sz_arg () const
Get required length of arg field.
size_t sz_res () const
Get required length of res field.
size_t sz_iw () const
Get required length of iw field.
size_t sz_w () const
Get required length of w field.
void alloc_arg (size_t sz_arg, bool persistent=false)
Ensure required length of arg field.
void alloc_res (size_t sz_res, bool persistent=false)
Ensure required length of res field.
void alloc_iw (size_t sz_iw, bool persistent=false)
Ensure required length of iw field.
void alloc_w (size_t sz_w, bool persistent=false)
Ensure required length of w field.
void alloc (const Function &f, bool persistent=false)
Ensure work vectors long enough to evaluate function.
void * memory (int ind) const
Memory objects.
virtual int n_mem () const
Maximum number of memory objects.
void clear_memory ()
Clear all memory (called from destructor)
int checkout ()
Checkout a memory object.
void release (int mem)
Release a memory object.
virtual std::string type_name () const
Get type name.
virtual bool is_a (const std::string &type, bool recursive) const
Check if the function is of a particular type.
template<typename MatType >
std::vector< std::vector
< MatType > > symbolicFwdSeed (int nfwd, const std::vector< MatType > &v)
Symbolic expressions for the forward seeds.
template<typename MatType >
std::vector< std::vector
< MatType > > symbolicAdjSeed (int nadj, const std::vector< MatType > &v)
Symbolic expressions for the adjoint seeds.
int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
virtual const char * plugin_name () const =0
virtual size_t get_n_in ()
Number of function inputs and outputs.
virtual size_t get_n_out ()
Number of function inputs and outputs.
virtual Sparsity get_sparsity_in (int i)
Sparsities of function inputs and outputs.
virtual Sparsity get_sparsity_out (int i)
Sparsities of function inputs and outputs.
virtual std::string get_name_in (int i)
Names of function input and outputs.
virtual std::string get_name_out (int i)
Names of function input and outputs.
void _eval (const double **arg, double **res, int *iw, double *w, int mem)
Evaluate numerically.
void _eval (const SXElem **arg, SXElem **res, int *iw, SXElem *w, int mem)
Evaluate a function, overloaded.
void _eval (const bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem)
Evaluate a function, overloaded.
virtual void eval_mx (const MXVector &arg, MXVector &res, bool always_inline, bool never_inline)
Evaluate with symbolic matrices.
void _call (const MXVector &arg, MXVector &res, bool always_inline, bool never_inline)
Call a function, overloaded.
template<typename D >
void _call (const std::vector< Matrix< D > > &arg, std::vector< Matrix< D > > &res, bool always_inline, bool never_inline)
Call a function, overloaded.
virtual void forward_mx (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens, bool always_inline, bool never_inline)
Forward mode AD, virtual functions overloaded in derived classes.
virtual void forward_sx (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &fseed, std::vector< std::vector< SX > > &fsens, bool always_inline, bool never_inline)
Forward mode AD, virtual functions overloaded in derived classes.
virtual void forward_dm (const std::vector< DM > &arg, const std::vector< DM > &res, const std::vector< std::vector< DM > > &fseed, std::vector< std::vector< DM > > &fsens, bool always_inline, bool never_inline)
Forward mode AD, virtual functions overloaded in derived classes.
void _forward (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens, bool always_inline, bool never_inline)
Forward mode AD, overloaded.
void _forward (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &fseed, std::vector< std::vector< SX > > &fsens, bool always_inline, bool never_inline)
Forward mode AD, overloaded.
void _forward (const std::vector< DM > &arg, const std::vector< DM > &res, const std::vector< std::vector< DM > > &fseed, std::vector< std::vector< DM > > &fsens, bool always_inline, bool never_inline)
Forward mode AD, overloaded.
Function forward (int nfwd)
Return function that calculates forward derivatives forward(nfwd) returns a cached instance if available, and calls Function get_forward(int nfwd) if no cached version is available.
virtual Function get_forward (const std::string &name, int nfwd, Dict &opts)
Return function that calculates forward derivatives forward(nfwd) returns a cached instance if available, and calls Function get_forward(int nfwd) if no cached version is available.
virtual int get_n_forward () const
Return function that calculates forward derivatives forward(nfwd) returns a cached instance if available, and calls Function get_forward(int nfwd) if no cached version is available.
void set_forward (const Function &fcn, int nfwd)
Return function that calculates forward derivatives forward(nfwd) returns a cached instance if available, and calls Function get_forward(int nfwd) if no cached version is available.
virtual void reverse_mx (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens, bool always_inline, bool never_inline)
Reverse mode, virtual functions overloaded in derived classes.
virtual void reverse_sx (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &aseed, std::vector< std::vector< SX > > &asens, bool always_inline, bool never_inline)
Reverse mode, virtual functions overloaded in derived classes.
virtual void reverse_dm (const std::vector< DM > &arg, const std::vector< DM > &res, const std::vector< std::vector< DM > > &aseed, std::vector< std::vector< DM > > &asens, bool always_inline, bool never_inline)
Reverse mode, virtual functions overloaded in derived classes.
void _reverse (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens, bool always_inline, bool never_inline)
Reverse mode AD, overloaded.
void _reverse (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &aseed, std::vector< std::vector< SX > > &asens, bool always_inline, bool never_inline)
Reverse mode AD, overloaded.
void _reverse (const std::vector< DM > &arg, const std::vector< DM > &res, const std::vector< std::vector< DM > > &aseed, std::vector< std::vector< DM > > &asens, bool always_inline, bool never_inline)
Reverse mode AD, overloaded.
Function reverse (int nadj)
Return function that calculates adjoint derivatives reverse(nadj) returns a cached instance if available, and calls Function get_reverse(int nadj) if no cached version is available.
virtual Function get_reverse (const std::string &name, int nadj, Dict &opts)
Return function that calculates adjoint derivatives reverse(nadj) returns a cached instance if available, and calls Function get_reverse(int nadj) if no cached version is available.
virtual int get_n_reverse () const
Return function that calculates adjoint derivatives reverse(nadj) returns a cached instance if available, and calls Function get_reverse(int nadj) if no cached version is available.
void set_reverse (const Function &fcn, int nadj)
Return function that calculates adjoint derivatives reverse(nadj) returns a cached instance if available, and calls Function get_reverse(int nadj) if no cached version is available.
std::vector< std::vector< MX > > map_mx (const std::vector< std::vector< MX > > &arg, const std::string &parallelization)
Parallel evaluation.
std::vector< MX > map_mx (const std::vector< MX > &arg, const std::string &parallelization)
Parallel evaluation.
std::vector< MX > mapsum_mx (const std::vector< MX > &arg, const std::string &parallelization)
Parallel evaluation.
Function hessian (int iind, int oind)
Return Hessian function.
virtual Function getHessian (int iind, int oind)
Return Hessian function.
Function gradient (int iind, int oind)
Return gradient function.
virtual Function getGradient (const std::string &name, int iind, int oind, const Dict &opts)
Return gradient function.
Function tangent (int iind, int oind)
Return tangent function.
virtual Function getTangent (const std::string &name, int iind, int oind, const Dict &opts)
Return tangent function.
Function jacobian (int iind, int oind, bool compact, bool symmetric)
Return Jacobian function.
void setJacobian (const Function &jac, int iind, int oind, bool compact)
Return Jacobian function.
virtual Function getJacobian (const std::string &name, int iind, int oind, bool compact, bool symmetric, const Dict &opts)
Return Jacobian function.
virtual Function getNumericJacobian (const std::string &name, int iind, int oind, bool compact, bool symmetric, const Dict &opts)
Return Jacobian function.
Function fullJacobian ()
Return Jacobian of all input elements with respect to all output elements.
virtual bool hasFullJacobian () const
Return Jacobian of all input elements with respect to all output elements.
virtual Function getFullJacobian (const std::string &name, const Dict &opts)
Return Jacobian of all input elements with respect to all output elements.
virtual const SX sx_in (int ind) const
Get function input(s) and output(s)
virtual const std::vector< SX > sx_in () const
Get function input(s) and output(s)
virtual const SX sx_out (int ind) const
Get function input(s) and output(s)
virtual const std::vector< SX > sx_out () const
Get function input(s) and output(s)
virtual const MX mx_in (int ind) const
Get function input(s) and output(s)
virtual const std::vector< MX > mx_in () const
Get function input(s) and output(s)
virtual const MX mx_out (int ind) const
Get function input(s) and output(s)
virtual const std::vector< MX > mx_out () const
Get function input(s) and output(s)
int n_in () const
Number of function inputs and outputs.
int n_out () const
Number of function inputs and outputs.
int nnz_in () const
Number of input/output nonzeros.
int nnz_in (int ind) const
Number of input/output nonzeros.
int nnz_out () const
Number of input/output nonzeros.
int nnz_out (int ind) const
Number of input/output nonzeros.
int numel_in () const
Number of input/output elements.
int numel_in (int ind) const
Number of input/output elements.
int numel_out (int ind) const
Number of input/output elements.
int numel_out () const
Number of input/output elements.
int size1_in (int ind) const
Input/output dimensions.
int size2_in (int ind) const
Input/output dimensions.
int size1_out (int ind) const
Input/output dimensions.
int size2_out (int ind) const
Input/output dimensions.
std::pair< int, int > size_in (int ind) const
Input/output dimensions.
std::pair< int, int > size_out (int ind) const
Input/output dimensions.
const Sparsity & sparsity_in (int ind) const
Get sparsity of a given input.
const Sparsity & sparsity_in (const std::string &iname) const
Get sparsity of a given input.
const Sparsity & sparsity_out (int ind) const
Get sparsity of a given output.
const Sparsity & sparsity_out (const std::string &iname) const
Get sparsity of a given output.
virtual Dict _get_stats (int mem) const
virtual void _set_work (const double **&arg, double **&res, int *&iw, double *&w, int mem) const
Set the (persistent) work vectors.
virtual void _set_temp (const double **arg, double **res, int *iw, double *w, int mem) const
Set the (temporary) work vectors.
void setup (void *mem, const double **arg, double **res, int *iw, double *w) const
Set the (persistent and temporary) work vectors.
void _setup (const double **arg, double **res, int *iw, double *w, int mem) const
Set the (persistent and temporary) work vectors.
virtual bool fwdViaJac (int nfwd)
Calculate derivatives by multiplying the full Jacobian and multiplying.
virtual bool adjViaJac (int nadj)
Calculate derivatives by multiplying the full Jacobian and multiplying.
virtual void linsol_factorize (void *mem, const double *A) const
virtual void linsol_solve (void *mem, double *x, int nrhs, bool tr) const
virtual MX linsol_solve (const MX &A, const MX &B, bool tr)
virtual void linsol_spsolve (bvec_t *X, const bvec_t *B, bool tr) const
virtual void linsol_spsolve (DM &X, const DM &B, bool tr) const
virtual void linsol_solveL (void *mem, double *x, int nrhs, bool tr) const
virtual Sparsity linsol_cholesky_sparsity (void *mem, bool tr) const
virtual DM linsol_cholesky (void *mem, bool tr) const
virtual void linsol_eval_sx (const SXElem **arg, SXElem **res, int *iw, SXElem *w, int mem, bool tr, int nrhs)
virtual void linsol_forward (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens, bool tr)
virtual void linsol_reverse (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens, bool tr)
virtual void linsol_spFwd (const bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem, bool tr, int nrhs)
virtual void linsol_spAdj (bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem, bool tr, int nrhs)
Static Public Member Functions
static std::string shortname ()
Short name.
template<typename Type >
static void append_to_vec (GenericType &t, Type el)
WORKAROUND: Add an element to an std::vector stored in a GenericType:
template<typename XType >
static Oracle * map2problem (const std::map< std::string, XType > &d)
Convert dictionary to Problem.
template<typename XType >
static Oracle * fun2problem (Function nlp)
Get the (legacy) dae forward function.
static bool checkMat (const Sparsity &arg, const Sparsity &inp, bool hcat=false)
template<typename MatType >
static bool purgable (const std::vector< MatType > &seed)
Can a derivative direction be skipped.
static bool hasPlugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin loadPlugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static Nlpsol * instantiatePlugin (const std::string &fname, const std::string &pname, Problem problem)
Public Attributes
int nx_
Number of variables.
int ng_
Number of constraints.
int np_
Number of parameters.
Function fcallback_
callback function, executed at each iteration
int callback_step_
Execute the callback function only after this amount of iterations.
bool eval_errors_fatal_
bool warn_initial_bounds_
bool iteration_callback_ignore_errors_
bool print_time_
std::vector< Function > all_functions_
std::vector< Sparsity > isp_
Input and output sparsity.
std::vector< Sparsity > osp_
std::vector< std::string > ischeme_
Input and output scheme.
std::vector< std::string > oscheme_
bool verbose_
Verbose – for debugging purposes.
bool jit_
Use just-in-time compiler.
eval_t eval_
Numerical evaluation redirected to a C function.
simple_t simple_
std::set< std::string > monitors_
Set of module names which are extra monitored.
Dict stats_
Dict of statistics (resulting from evaluate)
bool gather_stats_
Flag to indicate whether statistics must be gathered.
bool has_refcount_
Reference counting in codegen?
std::vector< WeakRef > derivative_fwd_
Cache for functions to evaluate directional derivatives (new)
std::vector< WeakRef > derivative_adj_
WeakRef full_jacobian_
Cache for full Jacobian.
SparseStorage< Sparsity > jac_sparsity_
Cache for sparsities of the Jacobian blocks.
SparseStorage< Sparsity > jac_sparsity_compact_
SparseStorage< WeakRef > jac_
Cache for Jacobians.
SparseStorage< WeakRef > jac_compact_
Function derivative_of_
If the function is the derivative of another function.
void * user_data_
User-set field.
std::string name_
Name.
std::string compilerplugin_
Just-in-time compiler.
Compiler compiler_
Dict jit_options_
double jac_penalty_
double ad_weight_
double ad_weight_sp_
bool monitor_inputs_
bool monitor_outputs_
bool regularity_check_
Errors are thrown when NaN is produced.
bool inputs_check_
Errors are thrown if numerical values of inputs look bad.
Static Public Attributes
static std::map< std::string,
Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "nlpsol"
Infix.
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
static Options options_
Options.
virtual const Options & get_options () const
Options.
Member Typedef Documentation
typedef Nlpsol*(* casadi::Nlpsol::Creator)(const std::string &name, Oracle *nlp)
Definition at line 174 of file nlpsol_impl.hpp.
typedef int(* casadi::PluginInterface< Nlpsol >::RegFcn)(Plugin *plugin) inherited
Definition at line 85 of file plugin_interface.hpp.
Constructor & Destructor Documentation
casadi::Nlpsol::Nlpsol (const std::string & name, Oracle * nlp)
Definition at line 151 of file nlpsol.cpp.
References callback_step_, eval_errors_fatal_, iteration_callback_ignore_errors_, print_time_, and warn_initial_bounds_.
     : FunctionInternal(name), nlp_(nlp) {
     // Set default options
     callback_step_ = 1;
     eval_errors_fatal_ = false;
     warn_initial_bounds_ = false;
     iteration_callback_ignore_errors_ = false;
     print_time_ = true;
   }
casadi::Nlpsol::~Nlpsol () pure virtual
Definition at line 162 of file nlpsol.cpp.
References casadi::FunctionInternal::clear_memory().
                   {
     if (nlp_) delete nlp_;
     clear_memory();
   }
Member Function Documentation
void casadi::FunctionInternal::_call (const MXVector & arg, MXVector & res, bool always_inline, bool never_inline) inline inherited
Definition at line 142 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), and casadi::FunctionInternal::call().
{
       eval_mx(arg, res, always_inline, never_inline);
     }
template<typename D > void casadi::FunctionInternal::_call (const std::vector< Matrix< D > > & arg, std::vector< Matrix< D > > & res, bool always_inline, bool never_inline) inherited
Definition at line 943 of file function_internal.hpp.
References casadi::FunctionInternal::_call(), casadi::FunctionInternal::_eval(), casadi::get_ptr(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::project(), casadi::FunctionInternal::sparsity_in(), casadi::FunctionInternal::sparsity_out(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     casadi_assert_message(!never_inline, "Call-nodes only possible in MX expressions");
     // Get the number of inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Check if matching input sparsity
     bool matching_sparsity = true;
     casadi_assert(arg.size()==n_in);
     for (int i=0; matching_sparsity && i<n_in; ++i)
       matching_sparsity = arg[i].sparsity()==sparsity_in(i);
     // Correct input sparsity if needed
     if (!matching_sparsity) {
       std::vector<Matrix<D> > arg2(arg);
       for (int i=0; i<n_in; ++i)
         if (arg2[i].sparsity()!=sparsity_in(i))
           arg2[i] = project(arg2[i], sparsity_in(i));
       return _call(arg2, res, always_inline, never_inline);
     }
     // Allocate results
     res.resize(n_out);
     for (int i=0; i<n_out; ++i) {
       if (res[i].sparsity()!=sparsity_out(i)) {
         res[i] = Matrix<D>::zeros(sparsity_out(i));
       }
     }
     // Allocate temporary memory if needed
     std::vector<int> iw_tmp(sz_iw());
     std::vector<D> w_tmp(sz_w());
     // Get pointers to input arguments
     std::vector<const D*> argp(sz_arg());
     for (int i=0; i<n_in; ++i) argp[i]=get_ptr(arg[i]);
     // Get pointers to output arguments
     std::vector<D*> resp(sz_res());
     for (int i=0; i<n_out; ++i) resp[i]=get_ptr(res[i]);
     // Call memory-less
     _eval(get_ptr(argp), get_ptr(resp), get_ptr(iw_tmp), get_ptr(w_tmp), 0);
   }
void casadi::FunctionInternal::_eval (const double ** arg, double ** res, int * iw, double * w, int mem) inherited
Definition at line 372 of file function_internal.cpp.
References casadi::FunctionInternal::eval(), casadi::FunctionInternal::eval_, casadi::FunctionInternal::memory(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::simple(), casadi::FunctionInternal::simple_, and casadi::FunctionInternal::simplifiedCall().
Referenced by casadi::FunctionInternal::_call().
{
     if (simplifiedCall()) {
       // Copy arguments to input buffers
       const double* arg1=w;
       for (int i=0; i<this->n_in(); ++i) {
         *w++ = arg[i] ? *arg[i] : 0;
       }
       // Evaluate
       if (simple_) {
         simple_(arg1, w);
       } else {
         simple(arg1, w);
       }
       // Get outputs
       for (int i=0; i<this->n_out(); ++i) {
         if (res[i]) *res[i] = *w;
         ++w;
       }
     } else {
       if (eval_) {
         eval_(arg, res, iw, w, mem);
       } else {
         eval(memory(mem), arg, res, iw, w);
       }
     }
   }
void casadi::FunctionInternal::_eval (const SXElem ** arg, SXElem ** res, int * iw, SXElem * w, int mem) inherited
Definition at line 401 of file function_internal.cpp.
References casadi::FunctionInternal::eval_sx().
{
     eval_sx(arg, res, iw, w, mem);
   }
void casadi::FunctionInternal::_eval (const bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem) inherited
Definition at line 405 of file function_internal.cpp.
References casadi::FunctionInternal::spFwd().
{
     spFwd(arg, res, iw, w, mem);
   }
void casadi::FunctionInternal::_forward (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens, bool always_inline, bool never_inline) inline inherited
Definition at line 222 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward().
{
       forward_mx(arg, res, fseed, fsens, always_inline, never_inline);
     }
void casadi::FunctionInternal::_forward (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & fseed, std::vector< std::vector< SX > > & fsens, bool always_inline, bool never_inline) inline inherited
Definition at line 229 of file function_internal.hpp.
{
       forward_sx(arg, res, fseed, fsens, always_inline, never_inline);
     }
void casadi::FunctionInternal::_forward (const std::vector< DM > & arg, const std::vector< DM > & res, const std::vector< std::vector< DM > > & fseed, std::vector< std::vector< DM > > & fsens, bool always_inline, bool never_inline) inline inherited
Definition at line 236 of file function_internal.hpp.
{
       forward_dm(arg, res, fseed, fsens, always_inline, never_inline);
     }
virtual Dict casadi::FunctionInternal::_get_stats (int mem) const inline virtual inherited
Get all statistics
Definition at line 705 of file function_internal.hpp.
 { return get_stats(memory(mem));}
void casadi::FunctionInternal::_reverse (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens, bool always_inline, bool never_inline) inline inherited
Definition at line 270 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::reverse().
{
       reverse_mx(arg, res, aseed, asens, always_inline, never_inline);
     }
void casadi::FunctionInternal::_reverse (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & aseed, std::vector< std::vector< SX > > & asens, bool always_inline, bool never_inline) inline inherited
Definition at line 277 of file function_internal.hpp.
{
       reverse_sx(arg, res, aseed, asens, always_inline, never_inline);
     }
void casadi::FunctionInternal::_reverse (const std::vector< DM > & arg, const std::vector< DM > & res, const std::vector< std::vector< DM > > & aseed, std::vector< std::vector< DM > > & asens, bool always_inline, bool never_inline) inline inherited
Definition at line 284 of file function_internal.hpp.
{
       reverse_dm(arg, res, aseed, asens, always_inline, never_inline);
     }
virtual void casadi::FunctionInternal::_set_temp (const double ** arg, double ** res, int * iw, double * w, int mem) const inline virtual inherited
Definition at line 722 of file function_internal.hpp.
{
       set_temp(memory(mem), arg, res, iw, w);
     }
virtual void casadi::FunctionInternal::_set_work (const double **& arg, double **& res, int *& iw, double *& w, int mem) const inline virtual inherited
Definition at line 712 of file function_internal.hpp.
{
       set_work(memory(mem), arg, res, iw, w);
     }
void casadi::FunctionInternal::_setup (const double ** arg, double ** res, int * iw, double * w, int mem) const inline inherited
Definition at line 731 of file function_internal.hpp.
{
       setup(memory(mem), arg, res, iw, w);
     }
void casadi::FunctionInternal::addDependency (CodeGenerator & g) const virtual inherited
Reimplemented in casadi::External.
Definition at line 2111 of file function_internal.cpp.
References casadi::CodeGenerator::added_dependencies_, casadi::CodeGenerator::body, casadi::FunctionInternal::codegen_decref(), casadi::FunctionInternal::codegen_incref(), casadi::FunctionInternal::generateFunction(), casadi::FunctionInternal::has_refcount_, casadi::FunctionInternal::simplifiedCall(), and casadi::CodeGenerator::to_string().
Referenced by casadi::Call::addDependency(), casadi::Switch::generateDeclarations(), casadi::KernelSum::generateDeclarations(), casadi::SymbolicQr::generateDeclarations(), casadi::Mapaccum::generateDeclarations(), casadi::PureMap::generateDeclarations(), and casadi::MapSum::generateDeclarations().
{
     // Get the current number of functions before looking for it
     size_t num_f_before = g.added_dependencies_.size();
     // Get index of the pattern
     int& ind = g.added_dependencies_[this];
     // Generate it if it does not exist
     if (g.added_dependencies_.size() > num_f_before) {
       // Add at the end
       ind = num_f_before;
       // Give it a name
       string name = "f" + CodeGenerator::to_string(ind);
       // Print to file
       generateFunction(g, "CASADI_PREFIX(" + name + ")", true);
       // Shorthand
       if (simplifiedCall()) {
         g.body
           << "#define " << name << "(arg, res) "
           << "CASADI_PREFIX(" << name << ")(arg, res)" << endl << endl;
       } else {
         g.body
           << "#define " << name << "(arg, res, iw, w, mem) "
           << "CASADI_PREFIX(" << name << ")(arg, res, iw, w, mem)" << endl << endl;
       }
       // Codegen reference count functions, if needed
       if (has_refcount_) {
         // Increase reference counter
         g.body << "void CASADI_PREFIX(" << name << "_incref)(void) {" << endl;
         codegen_incref(g);
         g.body
           << "}" << endl
           << "#define " << name << "_incref() "
           << "CASADI_PREFIX(" << name << "_incref)()" << endl << endl;
         // Decrease reference counter
         g.body << "void CASADI_PREFIX(" << name << "_decref)(void) {" << endl;
         codegen_decref(g);
         g.body
           << "}" << endl
           << "#define " << name << "_decref() "
           << "CASADI_PREFIX(" << name << "_decref)()" << endl << endl;
       }
     }
   }
bool casadi::FunctionInternal::adjViaJac (int nadj) virtual inherited
Definition at line 2325 of file function_internal.cpp.
References casadi::FunctionInternal::adWeight(), casadi::FunctionInternal::get_n_forward(), casadi::FunctionInternal::get_n_reverse(), casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::nnz_in(), and casadi::FunctionInternal::nnz_out().
Referenced by casadi::FunctionInternal::reverse_mx().
{
     if (get_n_reverse()==0) return true;
     if (jac_penalty_==-1) return false;
     // Heuristic 1: Jac calculated via reverse mode likely cheaper
     if (jac_penalty_*nnz_out()<nadj) return true;
     // Heuristic 2: Jac calculated via forward mode likely cheaper
     double w = adWeight();
     if (get_n_forward()>0 && jac_penalty_*w*nnz_in()<(1-w)*nadj)
       return true;
     return false;
   }
double casadi::FunctionInternal::adWeight () virtual inherited
Definition at line 2545 of file function_internal.cpp.
References casadi::FunctionInternal::ad_weight_, casadi::FunctionInternal::get_n_forward(), and casadi::FunctionInternal::get_n_reverse().
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::getFullJacobian(), casadi::FunctionInternal::getPartition(), and casadi::FunctionInternal::wrapMXFunction().
{
     // If reverse mode derivatives unavailable, use forward
     if (get_n_reverse()==0) return 0;
     // If forward mode derivatives unavailable, use reverse
     if (get_n_forward()==0) return 1;
     // Use the (potentially user set) option
     return ad_weight_;
   }
double casadi::FunctionInternal::adWeightSp () virtual inherited
Definition at line 2556 of file function_internal.cpp.
References casadi::FunctionInternal::ad_weight_sp_, and casadi::FunctionInternal::spCanEvaluate().
Referenced by casadi::FunctionInternal::getJacSparsity(), casadi::FunctionInternal::getJacSparsityHierarchical(), and casadi::FunctionInternal::wrapMXFunction().
{
     // If reverse mode propagation unavailable, use forward
     if (!spCanEvaluate(false)) return 0;
     // If forward mode propagation unavailable, use reverse
     if (!spCanEvaluate(true)) return 1;
     // Use the (potentially user set) option
     return ad_weight_sp_;
   }
void casadi::FunctionInternal::alloc (const Function & f, bool persistent = false) inherited
Definition at line 2292 of file function_internal.cpp.
References casadi::FunctionInternal::alloc_arg(), casadi::FunctionInternal::alloc_iw(), casadi::FunctionInternal::alloc_res(), casadi::FunctionInternal::alloc_w(), casadi::SharedObject::is_null(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), and casadi::Function::sz_work().
Referenced by casadi::Switch::init(), casadi::Rootfinder::init(), casadi::QpToNlp::init(), casadi::ImplicitToNlp::init(), casadi::Integrator::init(), casadi::SymbolicQr::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::IdasInterface::init(), casadi::CvodesInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), init(), casadi::ImplicitFixedStepIntegrator::init(), register_function(), casadi::RkIntegrator::setupFG(), and casadi::CollocationIntegrator::setupFG().
{
     if (f.is_null()) return;
     size_t sz_arg, sz_res, sz_iw, sz_w;
     f.sz_work(sz_arg, sz_res, sz_iw, sz_w);
     alloc_arg(sz_arg, persistent);
     alloc_res(sz_res, persistent);
     alloc_iw(sz_iw, persistent);
     alloc_w(sz_w, persistent);
   }
void casadi::FunctionInternal::alloc_arg (size_t sz_arg, bool persistent = false) inherited
Definition at line 2260 of file function_internal.cpp.
References casadi::FunctionInternal::sz_arg().
Referenced by casadi::FunctionInternal::alloc(), casadi::Mapaccum::init(), casadi::KernelSum::init(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::PureMap::init(), and casadi::MapSum::init().
{
     if (persistent) {
       sz_arg_per_ += sz_arg;
     } else {
       sz_arg_tmp_ = max(sz_arg_tmp_, sz_arg);
     }
   }
void casadi::FunctionInternal::alloc_iw (size_t sz_iw, bool persistent = false) inherited
Definition at line 2276 of file function_internal.cpp.
References casadi::FunctionInternal::sz_iw().
Referenced by casadi::FunctionInternal::alloc(), casadi::Mapaccum::init(), casadi::KernelSum::init(), casadi::OoqpInterface::init(), casadi::External::init(), casadi::GurobiInterface::init(), casadi::MXFunction::init(), casadi::PureMap::init(), and casadi::MapSum::init().
{
     if (persistent) {
       sz_iw_per_ += sz_iw;
     } else {
       sz_iw_tmp_ = max(sz_iw_tmp_, sz_iw);
     }
   }
virtual void* casadi::Nlpsol::alloc_memory () const inline virtual
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::IpoptInterface, casadi::Scpgen, casadi::Sqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
Definition at line 131 of file nlpsol_impl.hpp.
 { return new NlpsolMemory();}
void casadi::FunctionInternal::alloc_res (size_t sz_res, bool persistent = false) inherited
Definition at line 2268 of file function_internal.cpp.
References casadi::FunctionInternal::sz_res().
Referenced by casadi::FunctionInternal::alloc(), casadi::Mapaccum::init(), casadi::KernelSum::init(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::PureMap::init(), and casadi::MapSum::init().
{
     if (persistent) {
       sz_res_per_ += sz_res;
     } else {
       sz_res_tmp_ = max(sz_res_tmp_, sz_res);
     }
   }
void casadi::FunctionInternal::alloc_w (size_t sz_w, bool persistent = false) inherited
Definition at line 2284 of file function_internal.cpp.
References casadi::FunctionInternal::sz_w().
Referenced by casadi::FunctionInternal::alloc(), casadi::Jit::init(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Mapaccum::init(), casadi::OoqpInterface::init(), casadi::QpToNlp::init(), casadi::KernelSum::init(), casadi::ImplicitToNlp::init(), casadi::Newton::init(), casadi::External::init(), casadi::Integrator::init(), casadi::SymbolicQr::init(), casadi::GurobiInterface::init(), casadi::KnitroInterface::init(), casadi::QpoasesInterface::init(), casadi::SundialsInterface::init(), casadi::MXFunction::init(), casadi::KinsolInterface::init(), casadi::SnoptInterface::init(), casadi::WorhpInterface::init(), casadi::CplexInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::SimplifiedExternal::init(), casadi::IpoptInterface::init(), casadi::PureMap::init(), casadi::MapSum::init(), and casadi::SXFunction::init().
{
     if (persistent) {
       sz_w_per_ += sz_w;
     } else {
       sz_w_tmp_ = max(sz_w_tmp_, sz_w);
     }
   }
template<typename Type > static void casadi::Nlpsol::append_to_vec (GenericType & t, Type el) inline static
Definition at line 209 of file nlpsol_impl.hpp.
{
       std::vector<Type> v = t;
       v.push_back(el);
       t = v;
     }
int casadi::Nlpsol::calc_function (NlpsolMemory * m, const Function & fcn, std::initializer_list< const double * > arg, std::initializer_list< double * > res) const
Definition at line 563 of file nlpsol.cpp.
References casadi::WorkMemory::arg, casadi::InterruptHandler::check(), casadi::NlpsolMemory::fstats, casadi::WorkMemory::iw, casadi::Function::n_in(), casadi::FunctionInternal::n_in(), casadi::Function::n_out(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name(), casadi::Function::name(), casadi::Function::name_out(), casadi::Function::nnz_out(), casadi::WorkMemory::res, casadi::FStats::tic(), casadi::FStats::toc(), and casadi::WorkMemory::w.
Referenced by casadi::KnitroInterface::callback(), casadi::IpoptUserClass::eval_f(), casadi::IpoptUserClass::eval_g(), casadi::IpoptUserClass::eval_grad_f(), casadi::IpoptUserClass::eval_h(), casadi::IpoptUserClass::eval_jac_g(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), and casadi::SnoptInterface::userfun().
{
     // Respond to a possible Crl+C signals
     InterruptHandler::check();
     // Get statistics structure
     FStats& fstats = m->fstats.at(fcn.name());
     // Prepare stats, start timer
     fstats.tic();
     // Number of inputs and outputs
     int n_in = fcn.n_in(), n_out = fcn.n_out();
     // Input buffers
     fill_n(m->arg, n_in, nullptr);
     auto arg_it = arg.begin();
     for (int i=0; i<n_in; ++i) m->arg[i] = *arg_it++;
     casadi_assert(arg_it==arg.end());
     // Output buffers
     fill_n(m->res, n_out, nullptr);
     auto res_it = res.begin();
     for (int i=0; i<n_out; ++i) m->res[i] = *res_it++;
     casadi_assert(res_it==res.end());
     // Evaluate memory-less
     try {
       fcn(m->arg, m->res, m->iw, m->w, 0);
     } catch(exception& ex) {
       // Fatal error
       userOut<true, PL_WARN>()
         << name() << ":" << fcn.name() << " failed:" << ex.what() << endl;
       return 1;
     }
     // Make sure not NaN or Inf
     for (int i=0; i<n_out; ++i) {
       if (!m->res[i]) continue;
       if (!all_of(m->res[i], m->res[i]+fcn.nnz_out(i), [](double v) { return isfinite(v);})) {
         userOut<true, PL_WARN>()
           << name() << ":" << fcn.name() << " failed: NaN or Inf detected for output "
           << fcn.name_out(i) << endl;
         return -1;
       }
     }
     // Update stats
     fstats.toc();
     // Success
     return 0;
   }
template<typename M > void casadi::FunctionInternal::call (const std::vector< M > & arg, std::vector< M > & res, bool always_inline, bool never_inline) inherited
Definition at line 931 of file function_internal.hpp.
References casadi::FunctionInternal::_call(), casadi::FunctionInternal::matchingArg(), and casadi::FunctionInternal::replaceArg().
Referenced by casadi::MXFunction::expand().
{
     // Check if inputs need to be replaced
     if (!matchingArg(arg)) {
       return call(replaceArg(arg), res, always_inline, never_inline);
     }
     // Call the type-specific method
     _call(arg, res, always_inline, never_inline);
   }
template<typename M > void casadi::FunctionInternal::checkArg (const std::vector< M > & arg, bool hcat = false) const inherited
Parameters
hcat check if horizontal repetion of the function input is allowed
Definition at line 1063 of file function_internal.hpp.
References casadi::FunctionInternal::checkMat(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::name_in(), casadi::FunctionInternal::size_in(), and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::matchingArg(), and casadi::FunctionInternal::reverse().
{
     int n_in = this->n_in();
     casadi_assert_message(arg.size()==n_in, "Incorrect number of inputs: Expected "
                           << n_in << ", got " << arg.size());
     for (int i=0; i<n_in; ++i) {
       casadi_assert_message(checkMat(arg[i].sparsity(), sparsity_in(i), hcat),
                             "Input " << i << " (" << name_in(i) << ") has mismatching shape. "
                             << "Expected " << size_in(i) << ", got " << arg[i].size());
     }
   }
void casadi::Nlpsol::checkInputs (void * mem) const virtual
Definition at line 308 of file nlpsol.cpp.
References casadi::inf, casadi::FunctionInternal::inputs_check_, ng_, nx_, and warn_initial_bounds_.
{
     auto m = static_cast<NlpsolMemory*>(mem);
     // Skip check?
     if (!inputs_check_) return;
     const double inf = std::numeric_limits<double>::infinity();
     // Number of equality constraints
     int n_eq = 0;
     // Detect ill-posed problems (simple bounds)
     for (int i=0; i<nx_; ++i) {
       double lbx = m->lbx ? m->lbx[i] : 0;
       double ubx = m->ubx ? m->ubx[i] : 0;
       double x0 = m->x0 ? m->x0[i] : 0;
       casadi_assert_message(!(lbx==inf || lbx>ubx || ubx==-inf),
                             "Ill-posed problem detected (x bounds)");
       if (warn_initial_bounds_ && (x0>ubx || x0<lbx)) {
         casadi_warning("Nlpsol: The initial guess does not satisfy LBX and UBX. "
                        "Option 'warn_initial_bounds' controls this warning.");
         break;
       }
       if (lbx==ubx) n_eq++;
     }
     // Detect ill-posed problems (nonlinear bounds)
     for (int i=0; i<ng_; ++i) {
       double lbg = m->lbg ? m->lbg[i] : 0;
       double ubg = m->ubg ? m->ubg[i] : 0;
       casadi_assert_message(!(lbg==inf || lbg>ubg || ubg==-inf),
                             "Ill-posed problem detected (g bounds)");
       if (lbg==ubg) n_eq++;
     }
     // Make sure enough degrees of freedom
     using casadi::to_string; // Workaround, MingGW bug, cf. CasADi issue #890
     casadi_assert_message(n_eq <= nx_, "NLP is overconstrained: There are " + to_string(n_eq)
                          + " equality constraints but only " + to_string(nx_) + " variables.");
   }
virtual void casadi::FunctionInternal::checkInputs () const inline virtual inherited
Definition at line 496 of file function_internal.hpp.
Referenced by casadi::OoqpInterface::eval(), casadi::QpoasesInterface::eval(), casadi::CplexInterface::eval(), casadi::SqicInterface::evaluate(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), and casadi::IpoptInterface::solve().
 {}
bool casadi::FunctionInternal::checkMat (const Sparsity & arg, const Sparsity & inp, bool hcat = false) static inherited
Helper function
Definition at line 2857 of file function_internal.cpp.
References casadi::Sparsity::is_column(), casadi::Sparsity::is_empty(), casadi::Sparsity::is_scalar(), casadi::Sparsity::size(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
Referenced by casadi::FunctionInternal::checkArg(), casadi::FunctionInternal::checkRes(), casadi::FunctionInternal::forward(), and casadi::FunctionInternal::reverse().
{
     return arg.size()==inp.size() || arg.is_empty() || arg.is_scalar() ||
       (inp.size2()==arg.size1() && inp.size1()==arg.size2()
        && (arg.is_column() || inp.is_column())) ||
       (hcat && arg.size1()==inp.size1() && arg.size2() % inp.size2()==0);
   }
int casadi::FunctionInternal::checkout () inherited
Definition at line 2931 of file function_internal.cpp.
References casadi::FunctionInternal::alloc_memory(), casadi::FunctionInternal::init_memory(), and casadi::FunctionInternal::n_mem().
Referenced by casadi::FunctionInternal::finalize().
{
     if (unused_.empty()) {
       // Allocate a new memory object
       int n_mem = this->n_mem();
       casadi_assert_message(n_mem==0 || mem_.size()<n_mem,
                             "Too many memory objects");
       void* m = alloc_memory();
       mem_.push_back(m);
       if (m) init_memory(m);
       return mem_.size()-1;
     } else {
       // Use an unused memory object
       int m = unused_.top();
       unused_.pop();
       return m;
     }
   }
template<typename M > void casadi::FunctionInternal::checkRes (const std::vector< M > & res) const inherited
Definition at line 1075 of file function_internal.hpp.
References casadi::FunctionInternal::checkMat(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_out(), casadi::FunctionInternal::size_out(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::matchingRes(), and casadi::FunctionInternal::reverse().
{
     int n_out = this->n_out();
     casadi_assert_message(res.size()==n_out, "Incorrect number of outputs: Expected "
                           << n_out << ", got " << res.size());
     for (int i=0; i<n_out; ++i) {
       casadi_assert_message(checkMat(res[i].sparsity(), sparsity_out(i)),
                             "Output " << i << " (" << name_out(i) << ") has mismatching shape. "
                             "Expected " << size_out(i) << ", got " << res[i].size());
     }
   }
void casadi::FunctionInternal::clear_memory () inherited
Definition at line 2874 of file function_internal.cpp.
References casadi::FunctionInternal::free_memory().
Referenced by casadi::CplexInterface::~CplexInterface(), casadi::CsparseInterface::~CsparseInterface(), casadi::CvodesInterface::~CvodesInterface(), casadi::External::~External(), casadi::FixedStepIntegrator::~FixedStepIntegrator(), casadi::GurobiInterface::~GurobiInterface(), casadi::IdasInterface::~IdasInterface(), casadi::ImplicitToNlp::~ImplicitToNlp(), casadi::IpoptInterface::~IpoptInterface(), casadi::KinsolInterface::~KinsolInterface(), casadi::KnitroInterface::~KnitroInterface(), casadi::LapackLu::~LapackLu(), casadi::LapackQr::~LapackQr(), casadi::Newton::~Newton(), ~Nlpsol(), casadi::QpoasesInterface::~QpoasesInterface(), casadi::Scpgen::~Scpgen(), casadi::SnoptInterface::~SnoptInterface(), casadi::Sqpmethod::~Sqpmethod(), casadi::SymbolicQr::~SymbolicQr(), and casadi::WorhpInterface::~WorhpInterface().
{
     for (auto&& i : mem_) {
       if (i!=0) free_memory(i);
     }
     mem_.clear();
   }
virtual void casadi::FunctionInternal::codegen_decref (CodeGenerator & g) const inline virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 475 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::addDependency(), and casadi::FunctionInternal::generateMeta().
 {}
virtual void casadi::FunctionInternal::codegen_incref (CodeGenerator & g) const inline virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 472 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::addDependency(), and casadi::FunctionInternal::generateMeta().
 {}
std::string casadi::FunctionInternal::codegen_name (const CodeGenerator & g) const virtual inherited
Reimplemented in casadi::External.
Definition at line 2099 of file function_internal.cpp.
References casadi::CodeGenerator::added_dependencies_.
Referenced by casadi::Call::codegen_decref(), casadi::Call::codegen_incref(), and casadi::CodeGenerator::operator()().
{
     // Get the index of the function
     auto it=g.added_dependencies_.find(this);
     casadi_assert(it!=g.added_dependencies_.end());
     int f = it->second;
     // Construct the name
     stringstream ss;
     ss << "f" << f;
     return ss.str();
   }
void casadi::FunctionInternal::construct (const Dict & opts) inherited
Definition at line 105 of file function_internal.cpp.
References casadi::FunctionInternal::finalize(), casadi::Options::find(), casadi::FunctionInternal::get_options(), casadi::has_dot(), casadi::has_null(), casadi::FunctionInternal::init(), casadi::FunctionInternal::printOption(), casadi::Options::suggestions(), and casadi::Options::Entry::type.
Referenced by casadi::Function::conditional(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::Callback::create(), casadi::external(), casadi::Function::if_else(), casadi::integrator(), casadi::jit(), casadi::Function::kernel_sum(), casadi::linsol(), casadi::nlpsol(), casadi::qpsol(), and casadi::rootfinder().
{
     // Drop nulls
     if (has_null(opts)) {
       // Create a new dictionary without the null entries
       Dict mod_opts;
       for (auto&& op : opts) {
         if (!op.second.is_null()) mod_opts[op.first] = op.second;
       }
       // Call recursively
       return construct(mod_opts);
     }
     //  Treat the case where any of the options have a dot (dictionary shorthand)
     if (has_dot(opts)) {
       // New options dictionary being constructed
       Dict mod_opts;
       // Sub-dictionary and corresponding name being constructed
       Dict sopts;
       std::string sname;
       // Process options
       for (auto&& op : opts) {
         // Find the dot if any
         string::size_type dotpos = op.first.find('.'), dotpos_end;
         if (dotpos==string::npos) {
           dotpos = op.first.find("__");
           if (dotpos!=string::npos) dotpos_end = dotpos+2;
         } else {
           dotpos_end = dotpos+1;
         }
         // Flush last sub-dictionary
         if (!sname.empty() && (dotpos==string::npos
                                || op.first.compare(0, dotpos, sname)!=0)) {
           mod_opts[sname] = sopts;
           sname.clear();
           sopts.clear();
         }
         // Add to dictionary
         if (dotpos != string::npos) {
           sname = op.first.substr(0, dotpos);
           sopts[op.first.substr(dotpos_end)] = op.second;
         } else {
           mod_opts[op.first] = op.second;
         }
       }
       // Flush trailing sub-dictionary
       if (!sname.empty()) {
         mod_opts[sname] = sopts;
       }
       // Call recursively
       return construct(mod_opts);
     }
     // Get a reference to the options structure
     const Options& options = get_options();
     // Make sure all options exist and have the correct type
     for (auto&& op : opts) {
       const Options::Entry* entry = options.find(op.first);
       // Informative error message if option does not exist
       if (entry==0) {
         stringstream ss;
         ss << "Unknown option: " << op.first << endl;
         ss << endl;
         ss << "Did you mean one of the following?" << endl;
         for (auto&& s : options.suggestions(op.first)) {
           printOption(s, ss);
         }
         ss << "Use printOptions() to get a full list of options." << endl;
         casadi_error(ss.str());
       }
       // Check type
       casadi_assert_message(op.second.can_cast_to(entry->type),
                             "Illegal type for " + op.first);
     }
     // Initialize the class hierarchy
     init(opts);
     // Revisit class hierarchy in reverse order
     finalize();
   }
std::vector< MX > casadi::FunctionInternal::create_call (const std::vector< MX > & arg) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 1764 of file function_internal.cpp.
References casadi::Call::create().
Referenced by casadi::MXFunction::create_call(), and casadi::FunctionInternal::eval_mx().
{
     return Call::create(function(), arg);
   }
Function casadi::Nlpsol::create_function (const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const std::vector< LinComb > & lincomb = std::vector<LinComb>(), const Dict & opts = Dict(), bool reg = true)
Create an NLP function
Definition at line 625 of file nlpsol.cpp.
References casadi::Oracle::create(), and register_function().
Referenced by casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::WorhpInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), and casadi::IpoptInterface::init().
{
     // Generate the function
     casadi_assert(nlp_!=0);
     Function ret = nlp_->create(fname, s_in, s_out, lincomb, opts);
     if (reg) register_function(ret);
     return ret;
   }
virtual double casadi::Nlpsol::default_in (int ind) const inline virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 143 of file nlpsol_impl.hpp.
References casadi::nlpsol_default_in().
 { return nlpsol_default_in(ind);}
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
Function casadi::FunctionInternal::dynamicCompilation (Function f, std::string fname, std::string fdescr, std::string compiler) inherited
Definition at line 2173 of file function_internal.cpp.
References casadi::CodeGenerator::add(), casadi::CodeGenerator::compile(), casadi::external(), and casadi::Function::name().
Referenced by casadi::SymbolicQr::init().
{
     // Codegen and compile
     CodeGenerator g;
     g.add(f);
     string dlname = g.compile(fname, compiler);
     // Load it
     return external(f.name(), dlname);
   }
void casadi::Nlpsol::eval (void * mem, const double ** arg, double ** res, int * iw, double * w) const virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 364 of file nlpsol.cpp.
References casadi::FunctionInternal::setup(), and solve().
{
     // Reset the solver, prepare for solution
     setup(mem, arg, res, iw, w);
     // Solve the NLP
     solve(mem);
   }
void casadi::FunctionInternal::eval_mx (const MXVector & arg, MXVector & res, bool always_inline, bool never_inline) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 1751 of file function_internal.cpp.
References casadi::Function::call(), casadi::FunctionInternal::create_call(), and casadi::FunctionInternal::wrapMXFunction().
Referenced by casadi::MXFunction::eval_mx().
{
     // The code below creates a call node, to inline, wrap in an MXFunction
     if (always_inline) {
       casadi_assert_message(!never_inline, "Inconsistent options");
       Function f = wrapMXFunction();
       return f.call(arg, res, true);
     }
     // Create a call-node
     res = create_call(arg);
   }
void casadi::FunctionInternal::eval_sx (const SXElem ** arg, SXElem ** res, int * iw, SXElem * w, int mem) virtual inherited
Reimplemented in casadi::MapSum, casadi::PureMap, casadi::MXFunction, casadi::SXFunction, casadi::Mapaccum, and casadi::Linsol.
Definition at line 1445 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::FunctionInternal::_eval().
{
     casadi_error("'eval_sx' not defined for " + type_name());
   }
void casadi::FunctionInternal::finalize () virtual inherited
Reimplemented in casadi::CallbackInternal.
Definition at line 350 of file function_internal.cpp.
References casadi::CodeGenerator::add(), casadi::FunctionInternal::checkout(), casadi::FunctionInternal::compiler_, casadi::FunctionInternal::compilerplugin_, casadi::FunctionInternal::eval_, casadi::CodeGenerator::generate(), casadi::Compiler::get_function(), casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::name(), and casadi::FunctionInternal::simple_.
Referenced by casadi::FunctionInternal::construct(), and casadi::CallbackInternal::finalize().
{
     if (jit_) {
       CodeGenerator gen;
       gen.add(function());
       gen.generate("jit_tmp.c");
       compiler_ = Compiler("jit_tmp.c", compilerplugin_, jit_options_);
       // Try to load with simplified syntax
       simple_ = (simple_t)compiler_.get_function(name() + "_simple");
       // If not succesful, try generic syntax
       if (simple_==0) {
         eval_ = (eval_t)compiler_.get_function(name());
         casadi_assert_message(eval_!=0, "Cannot load JIT'ed function.");
       }
     }
     // Create memory object
     int mem = checkout();
     casadi_assert(mem==0);
   }
template<typename M > void casadi::FunctionInternal::forward (const std::vector< M > & arg, const std::vector< M > & res, const std::vector< std::vector< M > > & fseed, std::vector< std::vector< M > > & fsens, bool always_inline, bool never_inline) inherited
Definition at line 992 of file function_internal.hpp.
References casadi::FunctionInternal::_forward(), casadi::FunctionInternal::checkArg(), casadi::FunctionInternal::checkMat(), casadi::FunctionInternal::checkRes(), casadi::FunctionInternal::matchingArg(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::name_in(), casadi::FunctionInternal::replaceFwdSeed(), casadi::FunctionInternal::size_in(), and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::Function::forward(), and casadi::FunctionInternal::forward_mx().
{
     // Check inputs
     checkArg(arg);
     checkRes(res);
     // Check forward mode seeds dimensions
     int n_in = this->n_in();
     for (int d=0; d<fseed.size(); ++d) {
       casadi_assert_message(fseed[d].size()==n_in,
                             "Incorrect number of forward seeds for direction " << d
                             << ": Expected " << n_in << ", got " << fseed[d].size());
       for (int i=0; i<n_in; ++i) {
         casadi_assert_message(checkMat(fseed[d][i].sparsity(), sparsity_in(i)),
                               "Forward seed " << i << "(" << name_in(i) << ") for direction " << d
                               << " has mismatching shape. Expected " << size_in(i)
                               << ", got " << fseed[d][i].size());
       }
     }
     // Check if forward mode seeds need to be replaced
     for (int d=0; d<fseed.size(); ++d) {
       if (!matchingArg(fseed[d])) {
         return forward(arg, res, replaceFwdSeed(fseed), fsens,
                        always_inline, never_inline);
       }
     }
     // Call the type-specific method
     _forward(arg, res, fseed, fsens, always_inline, never_inline);
   }
Function casadi::FunctionInternal::forward (int nfwd) inherited
Definition at line 1502 of file function_internal.cpp.
References casadi::FunctionInternal::compilerplugin_, casadi::FunctionInternal::derivative_fwd_, casadi::FunctionInternal::get_forward(), casadi::FunctionInternal::get_n_forward(), casadi::FunctionInternal::ischeme_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_options_, casadi::Function::n_in(), casadi::FunctionInternal::n_in(), casadi::Function::n_out(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name(), casadi::FunctionInternal::name_, casadi::FunctionInternal::oscheme_, casadi::shared_cast(), casadi::Sparsity::size(), casadi::Function::size_in(), casadi::Function::size_out(), casadi::FunctionInternal::sparsity_in(), and casadi::FunctionInternal::sparsity_out().
{
     casadi_assert(nfwd>=0);
     // Check if there are enough forward directions allocated
     if (nfwd>=derivative_fwd_.size()) {
       derivative_fwd_.resize(nfwd+1);
     }
     // Quick return if already cached
     if (derivative_fwd_[nfwd].alive()) {
       return shared_cast<Function>(derivative_fwd_[nfwd].shared());
     }
     // Give it a suitable name
     stringstream ss;
     ss << "fwd" << nfwd << "_" << name_;
     string name = ss.str();
     // Get the number of inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Names of inputs
     std::vector<std::string> i_names;
     i_names.reserve(n_in + n_out + n_in*nfwd);
     // Nondifferentiated inputs
     for (int i=0; i<n_in; ++i) {
       i_names.push_back("der_" + ischeme_.at(i));
     }
     // Nondifferentiated outputs (given)
     for (int i=0; i<n_out; ++i) {
       i_names.push_back("der_" + oscheme_.at(i));
     }
     // Forward seeds
     for (int d=0; d<nfwd; ++d) {
       for (int i=0; i<n_in; ++i) {
         ss.str(string());
         ss << "fwd" << d << "_" << ischeme_.at(i);
         i_names.push_back(ss.str());
       }
     }
     // Names of outputs
     std::vector<std::string> o_names;
     o_names.reserve(n_out*nfwd);
     // Forward sensitivities
     for (int d=0; d<nfwd; ++d) {
       for (int i=0; i<n_out; ++i) {
         ss.str(string());
         ss << "fwd" << d << "_" << oscheme_.at(i);
         o_names.push_back(ss.str());
       }
     }
     // Options
     Dict opts = {{"input_scheme", i_names},
                  {"output_scheme", o_names},
                  {"jit", jit_},
                  {"compiler", compilerplugin_},
                  {"jit_options", jit_options_},
                  {"derivative_of", function()}};
     // Return value
     casadi_assert(get_n_forward()>0);
     Function ret = get_forward(name, nfwd, opts);
     // Consistency check for inputs
     for (int i=0; i<ret.n_in(); ++i) {
       const Sparsity& sp = i<n_in ? sparsity_in(i) :
         i<n_in+n_out ? sparsity_out(i-n_in) :
         sparsity_in((i-n_in-n_out) % n_in);
       casadi_assert_message(ret.size_in(i)==sp.size(),
                             "Incorrect shape for " << ret << " input " << i << " \""
                             << i_names.at(i) << "\". Expected " << sp.size()
                             << " but got " << ret.size_in(i));
     }
     // Consistency check for outputs
     for (int i=0; i<ret.n_out(); ++i) {
       const Sparsity& sp = sparsity_out(i % n_out);
       casadi_assert_message(ret.size_out(i)==sp.size(),
                             "Incorrect shape for " << ret << " output " << i << " \""
                             << o_names.at(i) << "\". Expected " << sp.size()
                             << " but got " << ret.size_out(i));
     }
     // Save to cache
     derivative_fwd_[nfwd] = ret;
     // Return generated function
     return ret;
   }
void casadi::FunctionInternal::forward_dm (const std::vector< DM > & arg, const std::vector< DM > & res, const std::vector< std::vector< DM > > & fseed, std::vector< std::vector< DM > > & fsens, bool always_inline, bool never_inline) virtual inherited
Definition at line 2530 of file function_internal.cpp.
{
     casadi_error("Not implemented");
   }
void casadi::FunctionInternal::forward_mx (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens, bool always_inline, bool never_inline) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2341 of file function_internal.cpp.
References casadi::Call::create(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::fullJacobian(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::hasDerivative(), casadi::mtimes(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::numel_out(), casadi::FunctionInternal::size_out(), and casadi::FunctionInternal::type_name().
Referenced by casadi::MXFunction::forward_mx().
{
     casadi_assert_message(!(always_inline && never_inline), "Inconsistent options");
     casadi_assert_message(!always_inline, "Class " + type_name() +
                           " cannot be inlined in an MX expression");
     // Derivative information must be available
     casadi_assert(hasDerivative());
     // Number of directional derivatives
     int nfwd = fseed.size();
     fsens.resize(nfwd);
     // Quick return if no seeds
     if (nfwd==0) return;
     // Number inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Calculating full Jacobian and then multiplying
     if (fwdViaJac(nfwd)) {
       // Join forward seeds
       vector<MX> v(nfwd);
       for (int d=0; d<nfwd; ++d) {
         v[d] = veccat(fseed[d]);
       }
       // Multiply the Jacobian from the right
       MX J = fullJacobian()(arg).at(0);
       v = horzsplit(mtimes(J, horzcat(v)));
       // Vertical offsets
       vector<int> offset(n_out+1, 0);
       for (int i=0; i<n_out; ++i) {
         offset[i+1] = offset[i]+numel_out(i);
       }
       // Collect forward sensitivities
       for (int d=0; d<nfwd; ++d) {
         fsens[d] = vertsplit(v[d], offset);
         for (int i=0; i<n_out; ++i) {
           fsens[d][i] = reshape(fsens[d][i], size_out(i));
         }
       }
       return;
     }
     // All inputs and seeds
     vector<MX> darg;
     darg.reserve(n_in + n_out + n_in*nfwd);
     darg.insert(darg.end(), arg.begin(), arg.end());
     darg.insert(darg.end(), res.begin(), res.end());
     for (int d=0; d<nfwd; ++d) {
       darg.insert(darg.end(), fseed[d].begin(), fseed[d].end());
     }
     // Create derivative function
     Function dfcn = forward(nfwd);
     // Create the evaluation node
     vector<MX> x = Call::create(dfcn, darg);
     vector<MX>::iterator x_it = x.begin();
     // Retrieve sensitivities
     for (int d=0; d<nfwd; ++d) {
       fsens[d].resize(n_out);
       for (int i=0; i<n_out; ++i) {
         fsens[d][i] = *x_it++;
       }
     }
     casadi_assert(x_it==x.end());
   }
void casadi::FunctionInternal::forward_sx (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & fseed, std::vector< std::vector< SX > > & fsens, bool always_inline, bool never_inline) virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2504 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_assert_message(!(always_inline && never_inline), "Inconsistent options");
     if (fseed.empty()) { // Quick return if no seeds
       fsens.clear();
       return;
     }
     casadi_error("'forward' (SX) not defined for " + type_name());
   }
virtual void casadi::Nlpsol::free_memory (void * mem) const inline virtual
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::IpoptInterface, casadi::Scpgen, casadi::Sqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
Definition at line 134 of file nlpsol_impl.hpp.
 { delete static_cast<NlpsolMemory*>(mem);}
std::vector< MX > casadi::FunctionInternal::free_mx () const virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2653 of file function_internal.cpp.
{
     casadi_error("'free_mx' only defined for 'mxfunction'");
   }
SX casadi::FunctionInternal::free_sx () const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2657 of file function_internal.cpp.
{
     casadi_error("'free_sx' only defined for 'sxfunction'");
   }
Function casadi::FunctionInternal::fullJacobian () inherited
Definition at line 1775 of file function_internal.cpp.
References casadi::WeakRef::alive(), casadi::FunctionInternal::full_jacobian_, casadi::FunctionInternal::getFullJacobian(), casadi::FunctionInternal::ischeme_, casadi::Function::n_in(), casadi::FunctionInternal::n_in(), casadi::Function::n_out(), casadi::WeakRef::shared(), and casadi::shared_cast().
Referenced by casadi::FunctionInternal::forward_mx(), casadi::Function::fullJacobian(), and casadi::FunctionInternal::reverse_mx().
{
     if (full_jacobian_.alive()) {
       // Return cached Jacobian
       return shared_cast<Function>(full_jacobian_.shared());
     } else {
       // Options
       string name = name_ + "_jac";
       Dict opts;
       opts["input_scheme"] = ischeme_;
       opts["output_scheme"] = std::vector<std::string>(1, "jac");
       opts["derivative_of"] = function();
       Function ret = getFullJacobian(name, opts);
       // Consistency check
       casadi_assert(ret.n_in()==n_in());
       casadi_assert(ret.n_out()==1);
       // Cache it for reuse and return
       full_jacobian_ = ret;
       return ret;
     }
   }
template<typename XType > Oracle * casadi::Nlpsol::fun2problem (Function nlp) static
Definition at line 244 of file nlpsol_impl.hpp.
References casadi::Oracle::construct(), casadi::NL_INPUTS, and casadi::NL_OUTPUTS.
{
     std::vector<XType> nl_in = XType::get_input(nlp);
     std::vector<XType> nl_out = nlp(nl_in);
     return Oracle::construct(nl_in, nl_out, NL_INPUTS, NL_OUTPUTS);
   }
Function casadi::FunctionInternal::function () const inline inherited
Definition at line 106 of file function_internal.hpp.
 { return shared_from_this<Function>();}
bool casadi::FunctionInternal::fwdViaJac (int nfwd) virtual inherited
Definition at line 2310 of file function_internal.cpp.
References casadi::FunctionInternal::adWeight(), casadi::FunctionInternal::get_n_forward(), casadi::FunctionInternal::get_n_reverse(), casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::nnz_in(), and casadi::FunctionInternal::nnz_out().
Referenced by casadi::FunctionInternal::forward_mx().
{
     if (get_n_forward()==0) return true;
     if (jac_penalty_==-1) return false;
     // Heuristic 1: Jac calculated via forward mode likely cheaper
     if (jac_penalty_*nnz_in()<nfwd) return true;
     // Heuristic 2: Jac calculated via reverse mode likely cheaper
     double w = adWeight();
     if (get_n_reverse()>0 && jac_penalty_*(1-w)*nnz_out()<w*nfwd)
       return true;
     return false;
   }
void casadi::Nlpsol::generate_dependencies (const std::string & fname, const Dict & opts) virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 618 of file nlpsol.cpp.
References casadi::CodeGenerator::add(), all_functions_, casadi::Oracle::all_io(), and casadi::CodeGenerator::generate().
{
     CodeGenerator gen(opts);
     gen.add(nlp_->all_io("nlp"));
     for (const Function& f : all_functions_) gen.add(f);
     gen.generate(fname);
   }
void casadi::FunctionInternal::generate_lifted (Function & vdef_fcn, Function & vinit_fcn) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2661 of file function_internal.cpp.
{
     casadi_error("'generate_lifted' only defined for 'mxfunction'");
   }
void casadi::FunctionInternal::generateBody (CodeGenerator & g) const virtual inherited
Reimplemented in casadi::MapSum, casadi::SXFunction, casadi::PureMap, casadi::Mapaccum, casadi::MXFunction, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::SymbolicQr, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::KernelSum, casadi::Switch, and casadi::Jit.
Definition at line 2165 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::FunctionInternal::generateFunction().
{
     casadi_error("'generateBody' not defined for " + type_name());
   }
void casadi::FunctionInternal::generateDeclarations (CodeGenerator & g) const virtual inherited
Reimplemented in casadi::MapSum, casadi::SXFunction, casadi::PureMap, casadi::Mapaccum, casadi::MXFunction, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::SymbolicQr, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::KernelSum, and casadi::Switch.
Definition at line 2161 of file function_internal.cpp.
Referenced by casadi::FunctionInternal::generateFunction().
{
     // Nothing to declare
   }
void casadi::FunctionInternal::generateFunction (CodeGenerator & g, const std::string & fname, bool decl_static) const virtual inherited
Definition at line 1859 of file function_internal.cpp.
References casadi::CodeGenerator::addAuxiliary(), casadi::CodeGenerator::addInclude(), casadi::CodeGenerator::AUX_SIGN, casadi::CodeGenerator::AUX_SQ, casadi::CodeGenerator::body, casadi::CodeGenerator::cpp, casadi::FunctionInternal::generateBody(), casadi::FunctionInternal::generateDeclarations(), casadi::FunctionInternal::signature(), and casadi::FunctionInternal::simplifiedCall().
Referenced by casadi::CodeGenerator::add(), and casadi::FunctionInternal::addDependency().
{
     // Add standard math
     g.addInclude("math.h");
     // Add auxiliaries. TODO: Only add the auxiliaries that are actually used
     g.addAuxiliary(CodeGenerator::AUX_SQ);
     g.addAuxiliary(CodeGenerator::AUX_SIGN);
     // Generate declarations
     generateDeclarations(g);
     // Define function
     g.body << "/* " << name_ << " */" << endl;
     if (decl_static) {
       g.body << "static ";
     } else if (g.cpp) {
       g.body << "extern \"C\" ";
     }
     g.body << signature(fname) << " {" << endl;
     // Insert the function body
     generateBody(g);
     // Finalize the function
     if (!simplifiedCall()) g.body << "  return 0;" << endl;
     g.body << "}" << endl << endl;
   }
void casadi::FunctionInternal::generateMeta (CodeGenerator & g, const std::string & fname) const inherited
Definition at line 1896 of file function_internal.cpp.
References casadi::CodeGenerator::addSparsity(), casadi::CodeGenerator::body, casadi::FunctionInternal::codegen_decref(), casadi::FunctionInternal::codegen_incref(), casadi::CodeGenerator::declare(), casadi::CodeGenerator::from_mex(), casadi::CodeGenerator::main, casadi::CodeGenerator::mex, casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_in(), casadi::FunctionInternal::name_out(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::CodeGenerator::printf(), casadi::FunctionInternal::simplifiedCall(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sparsity_in(), casadi::FunctionInternal::sparsity_out(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::CodeGenerator::to_mex(), and casadi::CodeGenerator::to_string().
Referenced by casadi::CodeGenerator::add().
{
     // Short-hands
     int n_in = this->n_in();
     int n_out = this->n_out();
     stringstream &s = g.body;
     // Reference counter routines
     s << g.declare("void " + fname + "_incref(void)") << " {" << endl;
     codegen_incref(g);
     s << "}" << endl << endl;
     s << g.declare("void " + fname + "_decref(void)") << " {" << endl;
     codegen_decref(g);
     s << "}" << endl << endl;
     // Number of inputs and outptus
     s << g.declare("int " + fname + "_n_in(void)")
       << " { return " << n_in << ";}" << endl << endl;
     s << g.declare("int " + fname + "_n_out(void)")
       << " { return " << n_out << ";}" << endl << endl;
     // Input names
     s << g.declare("const char* " + fname + "_name_in(int i)") << "{" << endl
       << "  switch (i) {" << endl;
     for (int i=0; i<n_in; ++i) {
       s << "  case " << i << ": return \"" << name_in(i) << "\";" << endl;
     }
     s << "  default: return 0;" << endl
       << "  }" << endl
       << "}" << endl << endl;
     // Output names
     s << g.declare("const char* " + fname + "_name_out(int i)") << "{" << endl
       << "  switch (i) {" << endl;
     for (int i=0; i<n_out; ++i) {
       s << "  case " << i << ": return \"" << name_out(i) << "\";" << endl;
     }
     s << "  default: return 0;" << endl
       << "  }" << endl
       << "}" << endl << endl;
     // Quick return if simplified syntax
     if (simplifiedCall()) {
       return;
     }
     // Input sparsities
     s << g.declare("const int* " + fname + "_sparsity_in(int i)") << " {" << endl
       << "  switch (i) {" << endl;
     for (int i=0; i<n_in; ++i) {
       s << "  case " << i << ": return s" << g.addSparsity(sparsity_in(i)) << ";" << endl;
     }
     s << "  default: return 0;" << endl
       << "  }" << endl
       << "}" << endl << endl;
     // Output sparsities
     s << g.declare("const int* " + fname + "_sparsity_out(int i)") << " {" << endl
       << "  switch (i) {" << endl;
     for (int i=0; i<n_out; ++i) {
       s << "  case " << i << ": return s" << g.addSparsity(sparsity_out(i)) << ";" << endl;
     }
     s << "  default: return 0;" << endl
       << "  }" << endl
       << "}" << endl << endl;
     // Function that returns work vector lengths
     s << g.declare("int " + fname + "_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w)");
     s << " {" << endl;
     s << "  if (sz_arg) *sz_arg = " << sz_arg() << ";" << endl;
     s << "  if (sz_res) *sz_res = " << sz_res() << ";" << endl;
     s << "  if (sz_iw) *sz_iw = " << sz_iw() << ";" << endl;
     s << "  if (sz_w) *sz_w = " << sz_w() << ";" << endl;
     s << "  return 0;" << endl;
     s << "}" << endl;
     s << endl;
     // Generate mex gateway for the function
     if (g.mex) {
       // Begin conditional compilation
       s << "#ifdef MATLAB_MEX_FILE" << endl;
       // Declare wrapper
       s << "void mex_" << fname
              << "(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {" << endl
              << "  int i, j;" << endl;
       // Check arguments
       s << "  if (argc>" << n_in << ") mexErrMsgIdAndTxt(\"Casadi:RuntimeError\","
              << "\"Evaluation of \\\"" << fname << "\\\" failed. Too many input arguments "
              << "(%d, max " << n_in << ")\", argc);" << endl;
       s << "  if (resc>" << n_out << ") mexErrMsgIdAndTxt(\"Casadi:RuntimeError\","
              << "\"Evaluation of \\\"" << fname << "\\\" failed. "
              << "Too many output arguments (%d, max " << n_out << ")\", resc);" << endl;
       // Work vectors, including input and output buffers
       int i_nnz = nnz_in(), o_nnz = nnz_out();
       size_t sz_w = this->sz_w();
       for (int i=0; i<n_in; ++i) {
         const Sparsity& s = sparsity_in(i);
         sz_w = max(sz_w, static_cast<size_t>(s.size1())); // To be able to copy a column
         sz_w = max(sz_w, static_cast<size_t>(s.size2())); // To be able to copy a row
       }
       sz_w += i_nnz + o_nnz;
       s << "  int iw[" << sz_iw() << "];" << endl;
       s << "  real_t w[" << sz_w << "];" << endl;
       string fw = "w+" + g.to_string(i_nnz + o_nnz);
       // Copy inputs to buffers
       int offset=0;
       s << "  const real_t* arg[" << n_in << "] = {0};" << endl;
       for (int i=0; i<n_in; ++i) {
         std::string p = "argv[" + g.to_string(i) + "]";
         s << "  if (--argc>=0) arg[" << i << "] = "
           << g.from_mex(p, "w", offset, sparsity_in(i), fw) << endl;
         offset += nnz_in(i);
       }
       // Allocate output buffers
       s << "  real_t* res[" << n_out << "] = {0};" << endl;
       for (int i=0; i<n_out; ++i) {
         if (i==0) {
           // if i==0, always store output (possibly ans output)
           s << "  --resc;" << endl
             << "  ";
         } else {
           // Store output, if it exists
           s << "  if (--resc>=0) ";
         }
         // Create and get pointer
         s << "res[" << i << "] = w+" << g.to_string(offset) << ";" << endl;
         offset += nnz_out(i);
       }
       // Call the function
       s << "  i = " << fname << "(arg, res, iw, " << fw << ", 0);" << endl;
       s << "  if (i) mexErrMsgIdAndTxt(\"Casadi:RuntimeError\",\"Evaluation of \\\"" << fname
         << "\\\" failed.\");" << endl;
       // Save results
       for (int i=0; i<n_out; ++i) {
         string res_i = "res[" + g.to_string(i) + "]";
         s << "  if (" << res_i << ") resv[" << i << "] = "
           << g.to_mex(sparsity_out(i), res_i) << endl;
       }
       // End conditional compilation and function
       s << "}" << endl
         << "#endif" << endl << endl;
     }
     if (g.main) {
       // Declare wrapper
       s << "int main_" << fname << "(int argc, char* argv[]) {" << endl;
       // Work vectors and input and output buffers
       size_t nr = sz_w() + nnz_in() + nnz_out();
       s << "  int iw[" << sz_iw() << "];" << endl
         << "  real_t w[" << nr << "];" << endl;
       // Input buffers
       s << "  const real_t* arg[" << sz_arg() << "] = {";
       int off=0;
       for (int i=0; i<n_in; ++i) {
         if (i!=0) s << ", ";
         s << "w+" << off;
         off += nnz_in(i);
       }
       s << "};" << endl;
       // Output buffers
       s << "  real_t* res[" << sz_res() << "] = {";
       for (int i=0; i<n_out; ++i) {
         if (i!=0) s << ", ";
         s << "w+" << off;
         off += nnz_out(i);
       }
       s << "};" << endl;
       // TODO(@jaeandersson): Read inputs from file. For now; read from stdin
       s << "  int j;" << endl
         << "  real_t* a = w;" << endl
         << "  for (j=0; j<" << nnz_in() << "; ++j) "
         << "scanf(\"%lf\", a++);" << endl;
       // Call the function
       s << "  int flag = " << fname << "(arg, res, iw, w+" << off << ", 0);" << endl
         << "  if (flag) return flag;" << endl;
       // TODO(@jaeandersson): Write outputs to file. For now: print to stdout
       s << "  const real_t* r = w+" << nnz_in() << ";" << endl
         << "  for (j=0; j<" << nnz_out() << "; ++j) "
         << g.printf("%g ", "*r++") << endl;
       // End with newline
       s << "  " << g.printf("\\n") << endl;
       // Finalize function
       s << "  return 0;" << endl
         << "}" << endl << endl;
     }
   }
Function casadi::FunctionInternal::get_forward (const std::string & name, int nfwd, Dict & opts) virtual inherited
Reimplemented in casadi::MapSum, casadi::PureMap, casadi::Integrator, casadi::External, casadi::Mapaccum, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::KernelSum, casadi::Rootfinder, casadi::CallbackInternal, and casadi::Switch.
Definition at line 1718 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::FunctionInternal::forward().
{
     // TODO(@jaeandersson): Fallback on finite differences
     casadi_error("'get_forward' not defined for " + type_name());
   }
virtual int casadi::FunctionInternal::get_n_forward () const inline virtual inherited
Reimplemented in casadi::MapSum, casadi::PureMap, casadi::Integrator, casadi::External, casadi::Mapaccum, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::KernelSum, casadi::Rootfinder, casadi::CallbackInternal, and casadi::Switch.
Definition at line 350 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::adWeight(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::getFullJacobian(), casadi::FunctionInternal::getPartition(), and casadi::FunctionInternal::hasDerivative().
 { return 0;}
virtual size_t casadi::Nlpsol::get_n_in () inline virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 105 of file nlpsol_impl.hpp.
References casadi::NLPSOL_NUM_IN.
 { return NLPSOL_NUM_IN;}
virtual size_t casadi::Nlpsol::get_n_out () inline virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 106 of file nlpsol_impl.hpp.
References casadi::NLPSOL_NUM_OUT.
 { return NLPSOL_NUM_OUT;}
virtual int casadi::FunctionInternal::get_n_reverse () const inline virtual inherited
Reimplemented in casadi::MapSum, casadi::PureMap, casadi::Integrator, casadi::External, casadi::Mapaccum, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::KernelSum, casadi::Rootfinder, casadi::CallbackInternal, and casadi::Switch.
Definition at line 362 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::adWeight(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::getFullJacobian(), casadi::FunctionInternal::getPartition(), casadi::FunctionInternal::hasDerivative(), and casadi::FunctionInternal::reverse().
 { return 0;}
virtual std::string casadi::Nlpsol::get_name_in (int i) inline virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 117 of file nlpsol_impl.hpp.
References casadi::nlpsol_in().
 { return nlpsol_in(i);}
virtual std::string casadi::Nlpsol::get_name_out (int i) inline virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 118 of file nlpsol_impl.hpp.
References casadi::nlpsol_out().
 { return nlpsol_out(i);}
virtual const Options& casadi::Nlpsol::get_options () const inline virtual
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::IpoptInterface, casadi::Scpgen, casadi::Sqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
Definition at line 124 of file nlpsol_impl.hpp.
 { return options_;}
Function casadi::FunctionInternal::get_reverse (const std::string & name, int nadj, Dict & opts) virtual inherited
Reimplemented in casadi::MapSum, casadi::PureMap, casadi::Integrator, casadi::External, casadi::Mapaccum, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::KernelSum, casadi::Rootfinder, casadi::CallbackInternal, and casadi::Switch.
Definition at line 1723 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::FunctionInternal::reverse().
{
     casadi_error("'get_reverse' not defined for " + type_name());
   }
Sparsity casadi::Nlpsol::get_sparsity_in (int i) virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 167 of file nlpsol.cpp.
References get_sparsity_out(), casadi::NL_P, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G0, casadi::NLPSOL_LAM_X0, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_NUM_IN, casadi::NLPSOL_P, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, casadi::NLPSOL_X, casadi::NLPSOL_X0, and casadi::Oracle::sparsity_in().
Referenced by get_sparsity_out().
{
     switch (static_cast<NlpsolInput>(i)) {
     case NLPSOL_X0:
     case NLPSOL_LBX:
     case NLPSOL_UBX:
     case NLPSOL_LAM_X0:
       return get_sparsity_out(NLPSOL_X);
     case NLPSOL_LBG:
     case NLPSOL_UBG:
     case NLPSOL_LAM_G0:
       return get_sparsity_out(NLPSOL_G);
     case NLPSOL_P:
       return nlp_->sparsity_in(NL_P);
     case NLPSOL_NUM_IN: break;
     }
     return Sparsity();
   }
Sparsity casadi::Nlpsol::get_sparsity_out (int i) virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 185 of file nlpsol.cpp.
References get_sparsity_in(), casadi::NL_G, casadi::NL_X, casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_P, casadi::NLPSOL_LAM_X, casadi::NLPSOL_NUM_OUT, casadi::NLPSOL_P, casadi::NLPSOL_X, casadi::Sparsity::scalar(), casadi::Oracle::sparsity_in(), and casadi::Oracle::sparsity_out().
Referenced by get_sparsity_in().
{
     switch (static_cast<NlpsolOutput>(i)) {
     case NLPSOL_F:
       return Sparsity::scalar();
     case NLPSOL_X:
     case NLPSOL_LAM_X:
       return nlp_->sparsity_in(NL_X);
     case NLPSOL_LAM_G:
     case NLPSOL_G:
       return nlp_->sparsity_out(NL_G);
     case NLPSOL_LAM_P:
       return get_sparsity_in(NLPSOL_P);
     case NLPSOL_NUM_OUT: break;
     }
     return Sparsity();
   }
Dict casadi::Nlpsol::get_stats (void * mem) const virtual
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::IpoptInterface, and casadi::Scpgen.
Definition at line 550 of file nlpsol.cpp.
Referenced by casadi::Scpgen::get_stats(), and casadi::IpoptInterface::get_stats().
{
     auto m = static_cast<NlpsolMemory*>(mem);
     // Add timing statistics
     Dict stats;
     for (auto&& s : m->fstats) {
       stats["n_call_" +s.first] = s.second.n_call;
       stats["t_wall_" +s.first] = s.second.t_wall;
       stats["t_proc_" +s.first] = s.second.t_proc;
     }
     return stats;
   }
virtual std::string casadi::FunctionInternal::getAdaptorSolverName () const inline virtual inherited
Definition at line 79 of file function_internal.hpp.
 { return ""; }
int casadi::FunctionInternal::getAlgorithmSize () const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2666 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'getAlgorithmSize' not defined for " + type_name());
   }
std::pair< int, int > casadi::FunctionInternal::getAtomicInput (int k) const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2678 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'getAtomicInput' not defined for " + type_name());
   }
double casadi::FunctionInternal::getAtomicInputReal (int k) const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2682 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'getAtomicInputReal' not defined for " + type_name());
   }
int casadi::FunctionInternal::getAtomicOperation (int k) const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2674 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'getAtomicOperation' not defined for " + type_name());
   }
int casadi::FunctionInternal::getAtomicOutput (int k) const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2686 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'getAtomicOutput' not defined for " + type_name());
   }
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
Function casadi::FunctionInternal::getFullJacobian (const std::string & name, const Dict & opts) virtual inherited
Reimplemented in casadi::External, casadi::Jit, and casadi::CallbackInternal.
Definition at line 1799 of file function_internal.cpp.
References casadi::FunctionInternal::adWeight(), casadi::FunctionInternal::get_n_forward(), casadi::FunctionInternal::get_n_reverse(), casadi::MX::jac(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::sparsity_in(), casadi::GenericMatrix< MX >::sym(), and casadi::FunctionInternal::symbolicOutput().
Referenced by casadi::FunctionInternal::fullJacobian(), and casadi::External::getFullJacobian().
{
     casadi_assert(get_n_forward()>0 || get_n_reverse()>0);
     // Number inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Symbolic inputs of the full Jacobian function under construction
     vector<MX> ret_argv = mx_in(), argv, resv;
     // Symbolic input of the SISO function formed for generating the Jacobian
     MX arg;
     // Reuse the same symbolic primitives, if single input
     if (n_in==1) {
       argv = ret_argv;
       arg = argv.front();
       resv = symbolicOutput(argv);
     } else {
       // Collect Sparsity patterns of inputs
       vector<Sparsity> sp_argv(n_in);
       vector<int> row_offset(n_in+1, 0);
       for (int i=0; i<n_in; ++i) {
         sp_argv[i] = vec(sparsity_in(i));
         row_offset[i+1] = row_offset[i]+sp_argv[i].numel();
       }
       Sparsity sp_arg = vertcat(sp_argv);
       // Create symbolic primitive
       arg = MX::sym("x", sp_arg);
       // Split up and reshape to correct shape
       argv = vertsplit(arg, row_offset);
       for (int i=0; i<n_in; ++i) {
         argv[i] = reshape(argv[i], sparsity_in(i));
       }
       // Evaluate symbolically
       resv = function()(argv);
     }
     // Reuse the same output, if possible
     MX res = n_out==1 ? resv.front() : veccat(resv);
     // Form Jacobian
     MX J;
     {
       Function tmp("tmp", {arg}, {res}, {{"ad_weight", adWeight()}});
       J = MX::jac(tmp);
     }
     // Make sure argv is the input of J
     if (n_in!=1) {
       J = substitute(J, arg, veccat(ret_argv));
     }
     // Form an expression for the full Jacobian
     return Function(name, ret_argv, {J}, opts);
   }
Function casadi::FunctionInternal::getGradient (const std::string & name, int iind, int oind, const Dict & opts) virtual inherited
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 510 of file function_internal.cpp.
References casadi::Function::gradient(), and casadi::FunctionInternal::wrapMXFunction().
Referenced by casadi::FunctionInternal::gradient().
{
     Function f = wrapMXFunction();
     return f.gradient(iind, oind);
   }
Function casadi::FunctionInternal::getHessian (int iind, int oind) virtual inherited
Definition at line 549 of file function_internal.cpp.
References casadi::FunctionInternal::gradient(), casadi::Function::jacobian(), and casadi::FunctionInternal::log().
Referenced by casadi::FunctionInternal::hessian().
{
     log("FunctionInternal::getHessian");
     // Create gradient function
     log("FunctionInternal::getHessian generating gradient");
     Function g = gradient(iind, oind);
     // Return the Jacobian of the gradient, exploiting symmetry (the gradient has output index 0)
     log("FunctionInternal::getHessian generating Jacobian of gradient");
     return g.jacobian(iind, 0, false, true);
   }
Function casadi::FunctionInternal::getJacobian (const std::string & name, int iind, int oind, bool compact, bool symmetric, const Dict & opts) virtual inherited
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 1497 of file function_internal.cpp.
References casadi::FunctionInternal::getNumericJacobian().
Referenced by casadi::FunctionInternal::jacobian().
{
     return getNumericJacobian(name, iind, oind, compact, symmetric, opts);
   }
Sparsity casadi::FunctionInternal::getJacSparsity (int iind, int oind, bool symmetric) virtual inherited
Definition at line 1245 of file function_internal.cpp.
References casadi::FunctionInternal::adWeightSp(), casadi::bvec_size, casadi::Sparsity::dense(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::GlobalOptions::hierarchical_sparsity, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::spCanEvaluate(), and casadi::Sparsity::T().
Referenced by casadi::FunctionInternal::sparsity_jac().
{
     // Check if we are able to propagate dependencies through the function
     if (spCanEvaluate(true) || spCanEvaluate(false)) {
       Sparsity sp;
       if (nnz_in(iind)>3*bvec_size && nnz_out(oind)>3*bvec_size &&
             GlobalOptions::hierarchical_sparsity) {
         if (symmetric) {
           sp = getJacSparsityHierarchicalSymm(iind, oind);
         } else {
           sp = getJacSparsityHierarchical(iind, oind);
         }
       } else {
         // Number of nonzero inputs and outputs
         int nz_in = nnz_in(iind);
         int nz_out = nnz_out(oind);
         // Number of forward sweeps we must make
         int nsweep_fwd = nz_in/bvec_size;
         if (nz_in%bvec_size) nsweep_fwd++;
         // Number of adjoint sweeps we must make
         int nsweep_adj = nz_out/bvec_size;
         if (nz_out%bvec_size) nsweep_adj++;
         // Get weighting factor
         double w = adWeightSp();
         // Use forward mode?
         if (w*nsweep_fwd <= (1-w)*nsweep_adj) {
           sp = getJacSparsityGen<true>(iind, oind, false);
         } else {
           sp = getJacSparsityGen<false>(iind, oind, false);
         }
       }
       // There may be false positives here that are not present
       // in the reverse mode that precedes it.
       // This can lead to an assymetrical result
       //  cf. #1522
       if (symmetric) sp=sp*sp.T();
       return sp;
     } else {
       // Dense sparsity by default
       return Sparsity::dense(nnz_out(oind), nnz_in(iind));
     }
   }
template<bool fwd> Sparsity casadi::FunctionInternal::getJacSparsityGen (int iind, int oind, bool symmetric, int gr_i = 1, int gr_o = 1) inherited
Definition at line 624 of file function_internal.cpp.
References casadi::bvec_size, casadi::get_ptr(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::numel(), casadi::Sparsity::size(), casadi::swap(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::triplet(), casadi::userOut(), and casadi::FunctionInternal::verbose().
{
     // Number of nonzero inputs and outputs
     int nz_in = nnz_in(iind);
     int nz_out = nnz_out(oind);
     // Evaluation buffers
     vector<typename JacSparsityTraits<fwd>::arg_t> arg(sz_arg(), 0);
     vector<bvec_t*> res(sz_res(), 0);
     vector<int> iw(sz_iw());
     vector<bvec_t> w(sz_w(), 0);
     // Seeds and sensitivities
     vector<bvec_t> seed(nz_in, 0);
     arg[iind] = get_ptr(seed);
     vector<bvec_t> sens(nz_out, 0);
     res[oind] = get_ptr(sens);
     if (!fwd) std::swap(seed, sens);
     // Number of forward sweeps we must make
     int nsweep = seed.size() / bvec_size;
     if (seed.size() % bvec_size) nsweep++;
     // Print
     if (verbose()) {
       userOut() << "FunctionInternal::getJacSparsityGen<" << fwd << ">: "
                 << nsweep << " sweeps needed for " << seed.size() << " directions" << endl;
     }
     // Progress
     int progress = -10;
     // Temporary vectors
     std::vector<int> jcol, jrow;
     // Loop over the variables, bvec_size variables at a time
     for (int s=0; s<nsweep; ++s) {
       // Print progress
       if (verbose()) {
         int progress_new = (s*100)/nsweep;
         // Print when entering a new decade
         if (progress_new / 10 > progress / 10) {
           progress = progress_new;
           userOut() << progress << " %"  << endl;
         }
       }
       // Nonzero offset
       int offset = s*bvec_size;
       // Number of local seed directions
       int ndir_local = seed.size()-offset;
       ndir_local = std::min(bvec_size, ndir_local);
       for (int i=0; i<ndir_local; ++i) {
         seed[offset+i] |= bvec_t(1)<<i;
       }
       // Propagate the dependencies
       JacSparsityTraits<fwd>::sp(this, get_ptr(arg), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
       // Loop over the nonzeros of the output
       for (int el=0; el<sens.size(); ++el) {
         // Get the sparsity sensitivity
         bvec_t spsens = sens[el];
         if (!fwd) {
           // Clear the sensitivities for the next sweep
           sens[el] = 0;
         }
         // If there is a dependency in any of the directions
         if (spsens!=0) {
           // Loop over seed directions
           for (int i=0; i<ndir_local; ++i) {
             // If dependents on the variable
             if ((bvec_t(1) << i) & spsens) {
               // Add to pattern
               jcol.push_back(el);
               jrow.push_back(i+offset);
             }
           }
         }
       }
       // Remove the seeds
       for (int i=0; i<ndir_local; ++i) {
         seed[offset+i] = 0;
       }
     }
     // Construct sparsity pattern and return
     if (!fwd) swap(jrow, jcol);
     Sparsity ret = Sparsity::triplet(nz_out, nz_in, jcol, jrow);
     casadi_msg("Formed Jacobian sparsity pattern (dimension " << ret.size() << ", "
                << ret.nnz() << " nonzeros, " << (100.0*ret.nnz())/ret.numel() << " % nonzeros).");
     casadi_msg("FunctionInternal::getJacSparsity end ");
     return ret;
   }
Sparsity casadi::FunctionInternal::getJacSparsityHierarchical (int iind, int oind) inherited
Decide which ad_mode to take
Definition at line 951 of file function_internal.cpp.
References casadi::FunctionInternal::adWeightSp(), casadi::bvec_or(), casadi::bvec_size, casadi::bvec_toggle(), casadi::Sparsity::colind(), casadi::Sparsity::dense(), casadi::Sparsity::dim(), casadi::fill(), casadi::Sparsity::get_nz(), casadi::get_ptr(), casadi::lookupvector(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::numel(), casadi::range(), casadi::Sparsity::row(), casadi::Sparsity::size(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::spAdj(), casadi::Matrix< Scalar >::sparsity(), casadi::FunctionInternal::spFwd(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::T(), casadi::Sparsity::triplet(), casadi::Matrix< int >::triplet(), and casadi::Sparsity::uni_coloring().
Referenced by casadi::FunctionInternal::getJacSparsity().
{
     // Number of nonzero inputs
     int nz_in = nnz_in(iind);
     // Number of nonzero outputs
     int nz_out = nnz_out(oind);
     // Seeds and sensitivities
     vector<bvec_t> s_in(nz_in, 0);
     vector<bvec_t> s_out(nz_out, 0);
     // Evaluation buffers
     vector<const bvec_t*> arg_fwd(sz_arg(), 0);
     vector<bvec_t*> arg_adj(sz_arg(), 0);
     arg_fwd[iind] = arg_adj[iind] = get_ptr(s_in);
     vector<bvec_t*> res(sz_res(), 0);
     res[oind] = get_ptr(s_out);
     vector<int> iw(sz_iw());
     vector<bvec_t> w(sz_w());
     // Sparsity triplet accumulator
     std::vector<int> jcol, jrow;
     // Cols of the coarse blocks
     std::vector<int> coarse_col(2, 0); coarse_col[1] = nz_out;
     // Rows of the coarse blocks
     std::vector<int> coarse_row(2, 0); coarse_row[1] = nz_in;
     // Cols of the fine blocks
     std::vector<int> fine_col;
     // Rows of the fine blocks
     std::vector<int> fine_row;
     // In each iteration, subdivide each coarse block in this many fine blocks
     int subdivision = bvec_size;
     Sparsity r = Sparsity::dense(1, 1);
     // The size of a block
     int granularity_row = nz_in;
     int granularity_col = nz_out;
     bool use_fwd = true;
     int nsweeps = 0;
     bool hasrun = false;
     // Get weighting factor
     double sp_w = adWeightSp();
     // Lookup table for bvec_t
     std::vector<bvec_t> bvec_lookup;
     bvec_lookup.reserve(bvec_size);
     for (int i=0;i<bvec_size;++i) {
       bvec_lookup.push_back(bvec_t(1) << i);
     }
     while (!hasrun || coarse_col.size()!=nz_out+1 || coarse_row.size()!=nz_in+1) {
       casadi_msg("Block size: " << granularity_col << " x " << granularity_row);
       // Clear the sparsity triplet acccumulator
       jcol.clear();
       jrow.clear();
       // Clear the fine block structure
       fine_row.clear();
       fine_col.clear();
       // r transpose will be needed in the algorithm
       Sparsity rT = r.T();
       // Forward mode
       Sparsity D1 = rT.uni_coloring(r);
       // Adjoint mode
       Sparsity D2 = r.uni_coloring(rT);
       casadi_msg("Coloring on " << r.dim() << " (fwd seeps: " << D1.size2() <<
                  " , adj sweeps: " << D2.size1() << ")");
       // Use forward mode?
       int fwd_cost = use_fwd ? granularity_row: granularity_col;
       int adj_cost = use_fwd ? granularity_col: granularity_row;
       // Use whatever required less colors if we tried both (with preference to forward mode)
       if ((sp_w*D1.size2()*fwd_cost <= (1-sp_w)*D2.size2()*adj_cost)) {
         use_fwd = true;
         casadi_msg("Forward mode chosen (fwd cost: " << sp_w*D1.size2()*fwd_cost << ", adj cost: "
                    << (1-sp_w)*D2.size2()*adj_cost << ")");
       } else {
         use_fwd = false;
         casadi_msg("Adjoint mode chosen (adj cost: " << sp_w*D1.size2()*fwd_cost << ", adj cost: "
                    << (1-sp_w)*D2.size2()*adj_cost << ")");
       }
       // Get seeds and sensitivities
       bvec_t* seed_v = use_fwd ? get_ptr(s_in) : get_ptr(s_out);
       bvec_t* sens_v = use_fwd ? get_ptr(s_out) : get_ptr(s_in);
       // The number of zeros in the seed and sensitivity directions
       int nz_seed = use_fwd ? nz_in  : nz_out;
       int nz_sens = use_fwd ? nz_out : nz_in;
       // Clear the seeds
       for (int i=0; i<nz_seed; ++i) seed_v[i]=0;
       // Choose the active jacobian coloring scheme
       Sparsity D = use_fwd ? D1 : D2;
       // Adjoint mode amounts to swapping
       if (!use_fwd) {
         std::swap(coarse_col, coarse_row);
         std::swap(granularity_col, granularity_row);
         std::swap(r, rT);
       }
       // Subdivide the coarse block cols
       for (int k=0;k<coarse_col.size()-1;++k) {
         int diff = coarse_col[k+1]-coarse_col[k];
         int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<int> temp = range(coarse_col[k], coarse_col[k+1], new_diff);
         fine_col.insert(fine_col.end(), temp.begin(), temp.end());
       }
       // Subdivide the coarse block rows
       for (int k=0;k<coarse_row.size()-1;++k) {
         int diff = coarse_row[k+1]-coarse_row[k];
         int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<int> temp = range(coarse_row[k], coarse_row[k+1], new_diff);
         fine_row.insert(fine_row.end(), temp.begin(), temp.end());
       }
       if (fine_row.back()!=coarse_row.back()) fine_row.push_back(coarse_row.back());
       if (fine_col.back()!=coarse_col.back()) fine_col.push_back(coarse_col.back());
       granularity_col = fine_col[1] - fine_col[0];
       granularity_row = fine_row[1] - fine_row[0];
       // The index into the bvec bit vector
       int bvec_i = 0;
       // Create lookup tables for the fine blocks
       std::vector<int> fine_col_lookup = lookupvector(fine_col, nz_sens+1);
       std::vector<int> fine_row_lookup = lookupvector(fine_row, nz_seed+1);
       // Triplet data used as a lookup table
       std::vector<int> lookup_col;
       std::vector<int> lookup_row;
       std::vector<int> lookup_value;
       // Loop over all coarse seed directions from the coloring
       for (int csd=0; csd<D.size2(); ++csd) {
         // The maximum number of fine blocks contained in one coarse block
         int n_fine_blocks_max = fine_row_lookup[coarse_row[1]]-fine_row_lookup[coarse_row[0]];
         int fci_offset = 0;
         int fci_cap = bvec_size-bvec_i;
         // Flag to indicate if all fine blocks have been handled
         bool f_finished = false;
         // Loop while not finished
         while (!f_finished) {
           // Loop over all coarse rows that are found in the coloring for this coarse seed direction
           for (int k=D.colind(csd); k<D.colind(csd+1); ++k) {
             int cci = D.row(k);
             // The first and last rows of the fine block
             int fci_start = fine_row_lookup[coarse_row[cci]];
             int fci_end   = fine_row_lookup[coarse_row[cci+1]];
             // Local counter that modifies index into bvec
             int bvec_i_mod = 0;
             int value = -bvec_i + fci_offset + fci_start;
             // Loop over the rows of the fine block
             for (int fci = fci_offset; fci<min(fci_end-fci_start, fci_cap); ++fci) {
               // Loop over the coarse block cols that appear in the coloring
               // for the current coarse seed direction
               for (int cri=rT.colind(cci);cri<rT.colind(cci+1);++cri) {
                 lookup_col.push_back(rT.row(cri));
                 lookup_row.push_back(bvec_i+bvec_i_mod);
                 lookup_value.push_back(value);
               }
               // Toggle on seeds
               bvec_toggle(seed_v, fine_row[fci+fci_start], fine_row[fci+fci_start+1],
                           bvec_i+bvec_i_mod);
               bvec_i_mod++;
             }
           }
           // Bump bvec_i for next major coarse direction
           bvec_i+= min(n_fine_blocks_max, fci_cap);
           // Check if bvec buffer is full
           if (bvec_i==bvec_size || csd==D.size2()-1) {
             // Calculate sparsity for bvec_size directions at once
             // Statistics
             nsweeps+=1;
             // Construct lookup table
             IM lookup = IM::triplet(lookup_row, lookup_col, lookup_value, bvec_size,
                                     coarse_col.size());
             // Propagate the dependencies
             if (use_fwd) {
               spFwd(get_ptr(arg_fwd), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
             } else {
               fill(w.begin(), w.end(), 0);
               spAdj(get_ptr(arg_adj), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
             }
             // Temporary bit work vector
             bvec_t spsens;
             // Loop over the cols of coarse blocks
             for (int cri=0;cri<coarse_col.size()-1;++cri) {
               // Loop over the cols of fine blocks within the current coarse block
               for (int fri=fine_col_lookup[coarse_col[cri]];
                    fri<fine_col_lookup[coarse_col[cri+1]];++fri) {
                 // Lump individual sensitivities together into fine block
                 bvec_or(sens_v, spsens, fine_col[fri], fine_col[fri+1]);
                 // Next iteration if no sparsity
                 if (!spsens) continue;
                 // Loop over all bvec_bits
                 for (int bvec_i=0;bvec_i<bvec_size;++bvec_i) {
                   if (spsens & bvec_lookup[bvec_i]) {
                     // if dependency is found, add it to the new sparsity pattern
                     int ind = lookup.sparsity().get_nz(bvec_i, cri);
                     if (ind==-1) continue;
                     jrow.push_back(bvec_i+lookup->at(ind));
                     jcol.push_back(fri);
                   }
                 }
               }
             }
             // Clear the forward seeds/adjoint sensitivities, ready for next bvec sweep
             fill(s_in.begin(), s_in.end(), 0);
             // Clear the adjoint seeds/forward sensitivities, ready for next bvec sweep
             fill(s_out.begin(), s_out.end(), 0);
             // Clean lookup table
             lookup_col.clear();
             lookup_row.clear();
             lookup_value.clear();
           }
           if (n_fine_blocks_max>fci_cap) {
             fci_offset += min(n_fine_blocks_max, fci_cap);
             bvec_i = 0;
             fci_cap = bvec_size;
           } else {
             f_finished = true;
           }
         }
       }
       // Swap results if adjoint mode was used
       if (use_fwd) {
         // Construct fine sparsity pattern
         r = Sparsity::triplet(fine_row.size()-1, fine_col.size()-1, jrow, jcol);
         coarse_col = fine_col;
         coarse_row = fine_row;
       } else {
         // Construct fine sparsity pattern
         r = Sparsity::triplet(fine_col.size()-1, fine_row.size()-1, jcol, jrow);
         coarse_col = fine_row;
         coarse_row = fine_col;
       }
       hasrun = true;
     }
     casadi_msg("Number of sweeps: " << nsweeps);
     casadi_msg("Formed Jacobian sparsity pattern (dimension " << r.size() <<
                ", " << r.nnz() << " nonzeros, " << (100.0*r.nnz())/r.numel() << " % nonzeros).");
     return r.T();
   }
Sparsity casadi::FunctionInternal::getJacSparsityHierarchicalSymm (int iind, int oind) inherited
A flavor of getJacSparsity that does hierarchical block structure recognition for symmetric Jacobians
Definition at line 728 of file function_internal.cpp.
References casadi::bvec_or(), casadi::bvec_size, casadi::bvec_toggle(), casadi::Sparsity::colind(), casadi::Sparsity::dense(), casadi::Sparsity::dim(), casadi::fill(), casadi::Sparsity::get_nz(), casadi::get_ptr(), casadi::lookupvector(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::numel(), casadi::range(), casadi::Sparsity::row(), casadi::Sparsity::size(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::sparsify(), casadi::Matrix< Scalar >::sparsity(), casadi::FunctionInternal::spCanEvaluate(), casadi::FunctionInternal::spFwd(), casadi::Sparsity::star_coloring(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::T(), casadi::Sparsity::triplet(), and casadi::Matrix< int >::triplet().
Referenced by casadi::FunctionInternal::getJacSparsity().
{
     casadi_assert(spCanEvaluate(true));
     // Number of nonzero inputs
     int nz = nnz_in(iind);
     casadi_assert(nz==nnz_out(oind));
     // Evaluation buffers
     vector<const bvec_t*> arg(sz_arg(), 0);
     vector<bvec_t*> res(sz_res(), 0);
     vector<int> iw(sz_iw());
     vector<bvec_t> w(sz_w());
     // Seeds
     vector<bvec_t> seed(nz, 0);
     arg[iind] = get_ptr(seed);
     // Sensitivities
     vector<bvec_t> sens(nz, 0);
     res[oind] = get_ptr(sens);
     // Sparsity triplet accumulator
     std::vector<int> jcol, jrow;
     // Cols/rows of the coarse blocks
     std::vector<int> coarse(2, 0); coarse[1] = nz;
     // Cols/rows of the fine blocks
     std::vector<int> fine;
     // In each iteration, subdivide each coarse block in this many fine blocks
     int subdivision = bvec_size;
     Sparsity r = Sparsity::dense(1, 1);
     // The size of a block
     int granularity = nz;
     int nsweeps = 0;
     bool hasrun = false;
     while (!hasrun || coarse.size()!=nz+1) {
       casadi_msg("Block size: " << granularity);
       // Clear the sparsity triplet acccumulator
       jcol.clear();
       jrow.clear();
       // Clear the fine block structure
       fine.clear();
       Sparsity D = r.star_coloring();
       casadi_msg("Star coloring on " << r.dim() << ": " << D.size2() << " <-> " << D.size1());
       // Clear the seeds
       fill(seed.begin(), seed.end(), 0);
       // Subdivide the coarse block
       for (int k=0; k<coarse.size()-1; ++k) {
         int diff = coarse[k+1]-coarse[k];
         int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<int> temp = range(coarse[k], coarse[k+1], new_diff);
         fine.insert(fine.end(), temp.begin(), temp.end());
       }
       if (fine.back()!=coarse.back()) fine.push_back(coarse.back());
       granularity = fine[1] - fine[0];
       // The index into the bvec bit vector
       int bvec_i = 0;
       // Create lookup tables for the fine blocks
       std::vector<int> fine_lookup = lookupvector(fine, nz+1);
       // Triplet data used as a lookup table
       std::vector<int> lookup_col;
       std::vector<int> lookup_row;
       std::vector<int> lookup_value;
       // Loop over all coarse seed directions from the coloring
       for (int csd=0; csd<D.size2(); ++csd) {
         // The maximum number of fine blocks contained in one coarse block
         int n_fine_blocks_max = fine_lookup[coarse[1]]-fine_lookup[coarse[0]];
         int fci_offset = 0;
         int fci_cap = bvec_size-bvec_i;
         // Flag to indicate if all fine blocks have been handled
         bool f_finished = false;
         // Loop while not finished
         while (!f_finished) {
           // Loop over all coarse rows that are found in the coloring for this coarse seed direction
           for (int k=D.colind(csd); k<D.colind(csd+1); ++k) {
             int cci = D.row(k);
             // The first and last rows of the fine block
             int fci_start = fine_lookup[coarse[cci]];
             int fci_end   = fine_lookup[coarse[cci+1]];
             // Local counter that modifies index into bvec
             int bvec_i_mod = 0;
             int value = -bvec_i + fci_offset + fci_start;
             //casadi_assert(value>=0);
             // Loop over the rows of the fine block
             for (int fci = fci_offset;fci<min(fci_end-fci_start, fci_cap);++fci) {
               // Loop over the coarse block cols that appear in the
               // coloring for the current coarse seed direction
               for (int cri=r.colind(cci);cri<r.colind(cci+1);++cri) {
                 lookup_col.push_back(r.row(cri));
                 lookup_row.push_back(bvec_i+bvec_i_mod);
                 lookup_value.push_back(value);
               }
               // Toggle on seeds
               bvec_toggle(get_ptr(seed), fine[fci+fci_start], fine[fci+fci_start+1],
                           bvec_i+bvec_i_mod);
               bvec_i_mod++;
             }
           }
           // Bump bvec_i for next major coarse direction
           bvec_i+= min(n_fine_blocks_max, fci_cap);
           // Check if bvec buffer is full
           if (bvec_i==bvec_size || csd==D.size2()-1) {
             // Calculate sparsity for bvec_size directions at once
             // Statistics
             nsweeps+=1;
             // Construct lookup table
             IM lookup = IM::triplet(lookup_row, lookup_col, lookup_value,
                                     bvec_size, coarse.size());
             std::reverse(lookup_col.begin(), lookup_col.end());
             std::reverse(lookup_row.begin(), lookup_row.end());
             std::reverse(lookup_value.begin(), lookup_value.end());
             IM duplicates =
               IM::triplet(lookup_row, lookup_col, lookup_value, bvec_size, coarse.size())
               - lookup;
             duplicates = sparsify(duplicates);
             lookup(duplicates.sparsity()) = -bvec_size;
             // Propagate the dependencies
             spFwd(get_ptr(arg), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
             // Temporary bit work vector
             bvec_t spsens;
             // Loop over the cols of coarse blocks
             for (int cri=0; cri<coarse.size()-1; ++cri) {
               // Loop over the cols of fine blocks within the current coarse block
               for (int fri=fine_lookup[coarse[cri]];fri<fine_lookup[coarse[cri+1]];++fri) {
                 // Lump individual sensitivities together into fine block
                 bvec_or(get_ptr(sens), spsens, fine[fri], fine[fri+1]);
                 // Loop over all bvec_bits
                 for (int bvec_i=0;bvec_i<bvec_size;++bvec_i) {
                   if (spsens & (bvec_t(1) << bvec_i)) {
                     // if dependency is found, add it to the new sparsity pattern
                     int ind = lookup.sparsity().get_nz(bvec_i, cri);
                     if (ind==-1) continue;
                     int lk = lookup->at(ind);
                     if (lk>-bvec_size) {
                       jrow.push_back(bvec_i+lk);
                       jcol.push_back(fri);
                       jrow.push_back(fri);
                       jcol.push_back(bvec_i+lk);
                     }
                   }
                 }
               }
             }
             // Clear the forward seeds/adjoint sensitivities, ready for next bvec sweep
             fill(seed.begin(), seed.end(), 0);
             // Clean lookup table
             lookup_col.clear();
             lookup_row.clear();
             lookup_value.clear();
           }
           if (n_fine_blocks_max>fci_cap) {
             fci_offset += min(n_fine_blocks_max, fci_cap);
             bvec_i = 0;
             fci_cap = bvec_size;
           } else {
             f_finished = true;
           }
         }
       }
       // Construct fine sparsity pattern
       r = Sparsity::triplet(fine.size()-1, fine.size()-1, jrow, jcol);
       // There may be false positives here that are not present
       // in the reverse mode that precedes it.
       // This can lead to an assymetrical result
       //  cf. #1522
       r=r*r.T();
       coarse = fine;
       hasrun = true;
     }
     casadi_msg("Number of sweeps: " << nsweeps);
     casadi_msg("Formed Jacobian sparsity pattern (dimension " << r.size() <<
                ", " << r.nnz() << " nonzeros, " << (100.0*r.nnz())/r.numel() << " % nonzeros).");
     return r.T();
   }
Function casadi::FunctionInternal::getNumericJacobian (const std::string & name, int iind, int oind, bool compact, bool symmetric, const Dict & opts) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 1769 of file function_internal.cpp.
References casadi::FunctionInternal::getNumericJacobian(), and casadi::FunctionInternal::wrapMXFunction().
Referenced by casadi::FunctionInternal::getJacobian(), and casadi::FunctionInternal::getNumericJacobian().
{
     Function f = wrapMXFunction();
     return f->getNumericJacobian(name, iind, oind, compact, symmetric, opts);
   }
void casadi::FunctionInternal::getPartition (int iind, int oind, Sparsity & D1, Sparsity & D2, bool compact, bool symmetric) inherited
Definition at line 1355 of file function_internal.cpp.
References casadi::FunctionInternal::adWeight(), casadi::FunctionInternal::get_n_forward(), casadi::FunctionInternal::get_n_reverse(), casadi::SharedObject::is_null(), casadi::FunctionInternal::log(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sparsity_jac(), casadi::Sparsity::star_coloring(), casadi::Sparsity::T(), casadi::Sparsity::uni_coloring(), casadi::userOut(), and casadi::FunctionInternal::verbose().
{
     log("FunctionInternal::getPartition begin");
     // Sparsity pattern with transpose
     Sparsity &AT = sparsity_jac(iind, oind, compact, symmetric);
     Sparsity A = symmetric ? AT : AT.T();
     // Get seed matrices by graph coloring
     if (symmetric) {
       casadi_assert(get_n_forward()>0);
       // Star coloring if symmetric
       log("FunctionInternal::getPartition star_coloring");
       D1 = A.star_coloring();
       casadi_msg("Star coloring completed: " << D1.size2() << " directional derivatives needed ("
                  << A.size1() << " without coloring).");
     } else {
       casadi_assert(get_n_forward()>0 || get_n_reverse()>0);
       // Get weighting factor
       double w = adWeight();
       // Which AD mode?
       bool test_ad_fwd=w<1, test_ad_adj=w>0;
       // Best coloring encountered so far (relatively tight upper bound)
       double best_coloring = numeric_limits<double>::infinity();
       // Test forward mode first?
       bool test_fwd_first = test_ad_fwd && w*A.size1() <= (1-w)*A.size2();
       int mode_fwd = test_fwd_first ? 0 : 1;
       // Test both coloring modes
       for (int mode=0; mode<2; ++mode) {
         // Is this the forward mode?
         bool fwd = mode==mode_fwd;
         // Skip?
         if (!test_ad_fwd && fwd) continue;
         if (!test_ad_adj && !fwd) continue;
         // Perform the coloring
         if (fwd) {
           log("FunctionInternal::getPartition unidirectional coloring (forward mode)");
           int max_colorings_to_test = best_coloring>=w*A.size1() ? A.size1() :
             floor(best_coloring/w);
           D1 = AT.uni_coloring(A, max_colorings_to_test);
           if (D1.is_null()) {
             if (verbose()) userOut() << "Forward mode coloring interrupted (more than "
                                << max_colorings_to_test << " needed)." << endl;
           } else {
             if (verbose()) userOut() << "Forward mode coloring completed: "
                                << D1.size2() << " directional derivatives needed ("
                                << A.size1() << " without coloring)." << endl;
             D2 = Sparsity();
             best_coloring = w*D1.size2();
           }
         } else {
           log("FunctionInternal::getPartition unidirectional coloring (adjoint mode)");
           int max_colorings_to_test = best_coloring>=(1-w)*A.size2() ? A.size2() :
             floor(best_coloring/(1-w));
           D2 = A.uni_coloring(AT, max_colorings_to_test);
           if (D2.is_null()) {
             if (verbose()) userOut() << "Adjoint mode coloring interrupted (more than "
                                << max_colorings_to_test << " needed)." << endl;
           } else {
             if (verbose()) userOut() << "Adjoint mode coloring completed: "
                                << D2.size2() << " directional derivatives needed ("
                                << A.size2() << " without coloring)." << endl;
             D1 = Sparsity();
             best_coloring = (1-w)*D2.size2();
           }
         }
       }
     }
     log("FunctionInternal::getPartition end");
   }
static Plugin& casadi::PluginInterface< Nlpsol >::getPlugin (const std::string & pname) static inherited
DM casadi::Nlpsol::getReducedHessian () virtual
Definition at line 353 of file nlpsol.cpp.
{
     casadi_error("Nlpsol::getReducedHessian not defined for class "
                  << typeid(*this).name());
     return DM();
   }
Function casadi::FunctionInternal::getTangent (const std::string & name, int iind, int oind, const Dict & opts) virtual inherited
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 516 of file function_internal.cpp.
References casadi::Function::tangent(), and casadi::FunctionInternal::wrapMXFunction().
Referenced by casadi::FunctionInternal::tangent().
{
     Function f = wrapMXFunction();
     return f.tangent(iind, oind);
   }
int casadi::FunctionInternal::getWorkSize () const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2670 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'getWorkSize' not defined for " + type_name());
   }
MX casadi::FunctionInternal::grad_mx (int iind = 0, int oind = 0) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2567 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::MX::grad().
{
     casadi_error("'grad_mx' not defined for " + type_name());
   }
SX casadi::FunctionInternal::grad_sx (int iind = 0, int oind = 0) virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2580 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'grad_sx' not defined for " + type_name());
   }
Function casadi::FunctionInternal::gradient (int iind, int oind) inherited
Definition at line 445 of file function_internal.cpp.
References casadi::FunctionInternal::compilerplugin_, casadi::FunctionInternal::getGradient(), casadi::FunctionInternal::ischeme_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_, casadi::FunctionInternal::oscheme_, and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::getHessian(), and casadi::Function::gradient().
{
     // Assert scalar
     casadi_assert_message(sparsity_out(oind).is_scalar(),
                           "Only gradients of scalar functions allowed. Use jacobian instead.");
     // Give it a suitable name
     stringstream ss;
     ss << "gradient_" << name_ << "_" << iind << "_" << oind;
     // Output names
     std::vector<std::string> ionames;
     ionames.reserve(1 + n_out());
     ionames.push_back("grad");
     for (int i=0; i<n_out(); ++i) {
       ionames.push_back(oscheme_.at(i));
     }
     // Generate gradient function
     Dict opts = {{"input_scheme", ischeme_},
                  {"output_scheme", ionames},
                  {"jit", jit_},
                  {"compiler", compilerplugin_},
                  {"jit_options", jit_options_},
                  {"derivative_of", function()}};
     return getGradient(ss.str(), iind, oind, opts);
   }
virtual bool casadi::FunctionInternal::has_free () const inline virtual inherited
Reimplemented in casadi::MXFunction, and casadi::SXFunction.
Definition at line 418 of file function_internal.hpp.
 { return false;}
bool casadi::FunctionInternal::hasDerivative () const inherited
Definition at line 2306 of file function_internal.cpp.
References casadi::FunctionInternal::get_n_forward(), casadi::FunctionInternal::get_n_reverse(), and casadi::FunctionInternal::hasFullJacobian().
Referenced by casadi::FunctionInternal::forward_mx(), and casadi::FunctionInternal::reverse_mx().
{
     return get_n_forward()>0 || get_n_reverse()>0 || hasFullJacobian();
   }
bool casadi::FunctionInternal::hasFullJacobian () const virtual inherited
Reimplemented in casadi::External, casadi::Jit, and casadi::CallbackInternal.
Definition at line 2302 of file function_internal.cpp.
References casadi::WeakRef::alive(), and casadi::FunctionInternal::full_jacobian_.
Referenced by casadi::FunctionInternal::hasDerivative(), and casadi::External::hasFullJacobian().
{
     return full_jacobian_.alive();
   }
static bool casadi::PluginInterface< Nlpsol >::hasPlugin (const std::string & pname, bool verbose = false) static inherited
SX casadi::FunctionInternal::hess_sx (int iind = 0, int oind = 0) virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2593 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'hess_sx' not defined for " + type_name());
   }
Function casadi::FunctionInternal::hessian (int iind, int oind) inherited
Definition at line 499 of file function_internal.cpp.
References casadi::FunctionInternal::getHessian(), casadi::FunctionInternal::log(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::Function::hessian().
{
     log("FunctionInternal::hessian");
     // Assert scalar
     casadi_assert_message(sparsity_out(oind).is_scalar(),
                           "Only hessians of scalar functions allowed.");
     // Generate gradient function
     return getHessian(iind, oind);
   }
virtual int casadi::FunctionInternal::index_in (const std::string & name) const inline virtual inherited
Definition at line 578 of file function_internal.hpp.
{
       const std::vector<std::string>& v=ischeme_;
       for (std::vector<std::string>::const_iterator i=v.begin(); i!=v.end(); ++i) {
         size_t col = i->find(':');
         if (i->compare(0, col, name)==0) return i-v.begin();
       }
       casadi_error("FunctionInternal::index_in: could not find entry \""
                    << name << "\". Available names are: " << v << ".");
       return -1;
     }
virtual int casadi::FunctionInternal::index_out (const std::string & name) const inline virtual inherited
Definition at line 590 of file function_internal.hpp.
{
       const std::vector<std::string>& v=oscheme_;
       for (std::vector<std::string>::const_iterator i=v.begin(); i!=v.end(); ++i) {
         size_t col = i->find(':');
         if (i->compare(0, col, name)==0) return i-v.begin();
       }
       casadi_error("FunctionInternal::index_out: could not find entry \""
                    << name << "\". Available names are: " << v << ".");
       return -1;
     }
void casadi::Nlpsol::init (const Dict & opts) virtual
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::IpoptInterface, casadi::Scpgen, casadi::Sqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
Definition at line 237 of file nlpsol.cpp.
References casadi::FunctionInternal::alloc(), callback_step_, eval_errors_fatal_, casadi::Oracle::expand(), fcallback_, casadi::FunctionInternal::init(), casadi::SharedObject::is_null(), iteration_callback_ignore_errors_, casadi::Function::n_in(), casadi::Function::n_out(), casadi::FunctionInternal::n_out(), ng_, casadi::NLPSOL_G, casadi::NLPSOL_P, casadi::NLPSOL_X, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), np_, casadi::Function::numel_out(), nx_, print_time_, casadi::Function::size_in(), casadi::FunctionInternal::size_out(), casadi::Function::sparsity_in(), casadi::FunctionInternal::sparsity_out(), and warn_initial_bounds_.
Referenced by casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::WorhpInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), and casadi::IpoptInterface::init().
{
     // Call the initialization method of the base class
     FunctionInternal::init(opts);
     // Default options
     bool expand = false;
     // Read options
     for (auto&& op : opts) {
       if (op.first=="expand") {
         expand = op.second;
       } else if (op.first=="iteration_callback") {
         fcallback_ = op.second;
       } else if (op.first=="iteration_callback_step") {
         callback_step_ = op.second;
       } else if (op.first=="eval_errors_fatal") {
         eval_errors_fatal_ = op.second;
       } else if (op.first=="warn_initial_bounds") {
         warn_initial_bounds_ = op.second;
       } else if (op.first=="iteration_callback_ignore_errors") {
         iteration_callback_ignore_errors_ = op.second;
       } else if (op.first=="print_time") {
         print_time_ = op.second;
       }
     }
     // Replace MX oracle with SX oracle?
     if (expand && nlp_) {
       Oracle* nlp_new = nlp_->expand();
       delete nlp_;
       nlp_ = nlp_new;
     }
     // Get dimensions
     nx_ = nnz_out(NLPSOL_X);
     np_ = nnz_in(NLPSOL_P);
     ng_ = nnz_out(NLPSOL_G);
     if (!fcallback_.is_null()) {
       // Consistency checks
       casadi_assert(!fcallback_.is_null());
       casadi_assert_message(fcallback_.n_out()==1 && fcallback_.numel_out()==1,
                             "Callback function must return a scalar");
       casadi_assert_message(fcallback_.n_in()==n_out(),
                             "Callback input signature must match the NLP solver output signature");
       for (int i=0; i<n_out(); ++i) {
         casadi_assert_message(fcallback_.size_in(i)==size_out(i),
                               "Callback function input size mismatch");
         // TODO(@jaeandersson): Wrap fcallback_ in a function with correct sparsity
         casadi_assert_message(fcallback_.sparsity_in(i)==sparsity_out(i),
                               "Not implemented");
       }
       // Allocate temporary memory
       alloc(fcallback_);
     }
   }
void casadi::Nlpsol::init_memory (void * mem) const virtual
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::IpoptInterface, casadi::Scpgen, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
Definition at line 295 of file nlpsol.cpp.
References all_functions_, and casadi::NlpsolMemory::fstats.
Referenced by casadi::KnitroInterface::init_memory(), casadi::SnoptInterface::init_memory(), casadi::WorhpInterface::init_memory(), casadi::Scpgen::init_memory(), and casadi::IpoptInterface::init_memory().
{
     auto m = static_cast<NlpsolMemory*>(mem);
     // Create statistics
     for (const Function& f : all_functions_) {
       m->fstats[f.name()] = FStats();
     }
     m->fstats["mainloop"] = FStats();
     m->fstats["callback_fun"] = FStats();
     m->fstats["callback_prep"] = FStats();
   }
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
static Nlpsol * casadi::PluginInterface< Nlpsol >::instantiatePlugin (const std::string & fname, const std::string & pname, Problem problem) static inherited
bool casadi::FunctionInternal::is_a (const std::string & type, bool recursive) const virtual inherited
Reimplemented in casadi::SXFunction, casadi::MXFunction, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 2649 of file function_internal.cpp.
Referenced by casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >::is_a().
{
     return type == "function";
   }
MX casadi::FunctionInternal::jac_mx (int iind = 0, int oind = 0, bool compact = false, bool symmetric = false, bool always_inline = true, bool never_inline = false) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2575 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::MX::jac().
{
     casadi_error("'jac_mx' not defined for " + type_name());
   }
SX casadi::FunctionInternal::jac_sx (int iind = 0, int oind = 0, bool compact = false, bool symmetric = false, bool always_inline = true, bool never_inline = false) virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2588 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'jac_sx' not defined for " + type_name());
   }
Function casadi::FunctionInternal::jacobian (int iind, int oind, bool compact, bool symmetric) inherited
Definition at line 1449 of file function_internal.cpp.
References casadi::WeakRef::alive(), casadi::FunctionInternal::compilerplugin_, casadi::FunctionInternal::getJacobian(), casadi::FunctionInternal::ischeme_, casadi::FunctionInternal::jac_, casadi::FunctionInternal::jac_compact_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_, casadi::FunctionInternal::name_in(), casadi::FunctionInternal::name_out(), casadi::FunctionInternal::oscheme_, casadi::WeakRef::shared(), casadi::shared_cast(), and casadi::FunctionInternal::verbose_.
Referenced by casadi::Function::jacobian().
{
     // Return value
     WeakRef cached = compact ? jac_compact_.elem(oind, iind) : jac_.elem(oind, iind);
     // Check if cached
     if (cached.alive()) {
       // Return an owning reference
       return shared_cast<Function>(cached.shared());
     } else {
       // Give it a suitable name
       stringstream ss;
       ss << "jacobian_" << name_ << "_" << iind << "_" << oind;
       // Output names
       std::vector<std::string> ionames;
       ionames.reserve(1 + n_out());
       ionames.push_back("d" + name_out(oind) + "_d" + name_in(iind));
       for (int i=0; i<n_out(); ++i) {
         ionames.push_back(oscheme_.at(i));
       }
       // Generate a Jacobian
       Dict opts = {{"verbose", verbose_},
                    {"input_scheme", ischeme_},
                    {"output_scheme", ionames},
                    {"jit", jit_},
                    {"compiler", compilerplugin_},
                    {"jit_options", jit_options_},
                    {"derivative_of", function()}};
       Function ret = getJacobian(ss.str(), iind, oind, compact, symmetric, opts);
       // Save in cache
       compact ? jac_compact_.elem(oind, iind) : jac_.elem(oind, iind) = ret;
       return ret;
     }
   }
DM casadi::FunctionInternal::linsol_cholesky (void * mem, bool tr) const virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::CSparseCholeskyInterface.
Definition at line 2722 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_cholesky' not defined for " + type_name());
   }
Sparsity casadi::FunctionInternal::linsol_cholesky_sparsity (void * mem, bool tr) const virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::CSparseCholeskyInterface.
Definition at line 2718 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_cholesky_sparsity' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_eval_sx (const SXElem ** arg, SXElem ** res, int * iw, SXElem * w, int mem, bool tr, int nrhs) virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::SymbolicQr, and casadi::Linsol.
Definition at line 2727 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_eval_sx' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_factorize (void * mem, const double * A) const virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::LapackLu, casadi::SymbolicQr, casadi::LapackQr, casadi::CSparseCholeskyInterface, and casadi::CsparseInterface.
Definition at line 2694 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::Linsol::eval().
{
     casadi_error("'linsol_factorize' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_forward (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens, bool tr) virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::Linsol.
Definition at line 2733 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_forward' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_reverse (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens, bool tr) virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::Linsol.
Definition at line 2740 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_reverse' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_solve (void * mem, double * x, int nrhs, bool tr) const virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::LapackLu, casadi::SymbolicQr, casadi::LapackQr, casadi::CSparseCholeskyInterface, and casadi::CsparseInterface.
Definition at line 2698 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_solve' not defined for " + type_name());
   }
MX casadi::FunctionInternal::linsol_solve (const MX & A, const MX & B, bool tr) virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::Linsol.
Definition at line 2702 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_solve' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_solveL (void * mem, double * x, int nrhs, bool tr) const virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::CSparseCholeskyInterface.
Definition at line 2714 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_solveL' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_spAdj (bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem, bool tr, int nrhs) virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::Linsol.
Definition at line 2753 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_spAdj' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_spFwd (const bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem, bool tr, int nrhs) virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::Linsol.
Definition at line 2747 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_spFwd' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_spsolve (bvec_t * X, const bvec_t * B, bool tr) const virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::Linsol.
Definition at line 2706 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_spsolve' not defined for " + type_name());
   }
void casadi::FunctionInternal::linsol_spsolve (DM & X, const DM & B, bool tr) const virtual inherited
Linear solver specific (cf. Linsol class)
Reimplemented in casadi::Linsol.
Definition at line 2710 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'linsol_spsolve' not defined for " + type_name());
   }
static Plugin casadi::PluginInterface< Nlpsol >::loadPlugin (const std::string & pname, bool register_plugin = true) static inherited
void casadi::FunctionInternal::log (const std::string & msg) const inherited
Referenced by casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::CvodesInterface::bjac(), casadi::IdasInterface::bjac(), casadi::CvodesInterface::bjacB(), casadi::IdasInterface::bjacB(), casadi::IdasInterface::correctInitialConditions(), casadi::CvodesInterface::djac(), casadi::IdasInterface::djac(), casadi::CvodesInterface::djacB(), casadi::IdasInterface::djacB(), casadi::Newton::eval(), casadi::MXFunction::eval_mx(), casadi::MXFunction::evalAdj(), casadi::MXFunction::evalFwd(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::getHessian(), casadi::FunctionInternal::getPartition(), casadi::FunctionInternal::hessian(), casadi::MXFunction::init(), casadi::IdasInterface::init(), casadi::CvodesInterface::init(), casadi::Scpgen::init(), casadi::IdasInterface::init_memory(), casadi::IdasInterface::initAdj(), casadi::IpoptInterface::intermediate_callback(), casadi::CvodesInterface::jtimes(), casadi::IdasInterface::jtimes(), casadi::CvodesInterface::jtimesB(), casadi::IdasInterface::jtimesB(), casadi::IdasInterface::lsetup(), casadi::IdasInterface::lsetupB(), casadi::CvodesInterface::lsolve(), casadi::IdasInterface::lsolve(), casadi::CvodesInterface::lsolveB(), casadi::IdasInterface::lsolveB(), casadi::CvodesInterface::psetup(), casadi::IdasInterface::psetup(), casadi::CvodesInterface::psetupB(), casadi::IdasInterface::psetupB(), casadi::IdasInterface::psolve(), casadi::IdasInterface::psolveB(), casadi::IdasInterface::res(), casadi::IdasInterface::resB(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::IdasInterface::resS(), casadi::CvodesInterface::rhs(), casadi::CvodesInterface::rhsB(), casadi::IdasInterface::rhsQ(), casadi::IdasInterface::rhsQB(), casadi::IdasInterface::rhsQS(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Integrator::spAdj(), and casadi::Integrator::spFwd().
void casadi::FunctionInternal::log (const std::string & fcn, const std::string & msg) const inherited
template<typename XType > Oracle * casadi::Nlpsol::map2problem (const std::map< std::string, XType > & d) static
Definition at line 225 of file nlpsol_impl.hpp.
References casadi::Oracle::construct(), casadi::NL_F, casadi::NL_G, casadi::NL_INPUTS, casadi::NL_NUM_IN, casadi::NL_NUM_OUT, casadi::NL_OUTPUTS, casadi::NL_P, and casadi::NL_X.
{
     std::vector<XType> nl_in(NL_NUM_IN), nl_out(NL_NUM_OUT);
     for (auto&& i : d) {
       if (i.first=="x") {
         nl_in[NL_X]=i.second;
       } else if (i.first=="p") {
         nl_in[NL_P]=i.second;
       } else if (i.first=="f") {
         nl_out[NL_F]=i.second;
       } else if (i.first=="g") {
         nl_out[NL_G]=i.second;
       } else {
         casadi_error("No such field: " + i.first);
       }
     }
     return Oracle::construct(nl_in, nl_out, NL_INPUTS, NL_OUTPUTS);
   }
std::vector< std::vector< MX > > casadi::FunctionInternal::map_mx (const std::vector< std::vector< MX > > & arg, const std::string & parallelization) inherited
Definition at line 2759 of file function_internal.cpp.
References casadi::FunctionInternal::matchingArg(), casadi::FunctionInternal::replaceArg(), casadi::FunctionInternal::size2_out(), casadi::swapIndices(), and casadi::trans().
Referenced by casadi::FunctionInternal::map_mx().
{
     if (x.empty()) return x;
     // Check if arguments match
     int n = x.size();
     bool matching=true;
     for (int i=0; i<n; ++i) {
       matching = matchingArg(x[i]) && matching; // non-short circuiting
     }
     // Replace arguments if needed
     if (!matching) {
       vector<vector<MX> > x_new(n);
       for (int i=0; i<n; ++i) x_new[i] = replaceArg(x[i]);
       return map_mx(x_new, parallelization);
     }
     vector< vector<MX> > trans = swapIndices(x);
     vector< MX > x_cat(trans.size());
     for (int i=0;i<trans.size();++i) {
       x_cat[i] = horzcat(trans[i]);
     }
     // Call the internal function
     vector< MX > ret_cat = map_mx(x_cat, parallelization);
     vector< vector<MX> > ret;
     for (int i=0;i<ret_cat.size();++i) {
       ret.push_back(horzsplit(ret_cat[i], size2_out(i)));
     }
     return swapIndices(ret);
   }
std::vector< MX > casadi::FunctionInternal::map_mx (const std::vector< MX > & arg, const std::string & parallelization) inherited
Definition at line 2794 of file function_internal.cpp.
References casadi::FunctionInternal::map_mx(), casadi::FunctionInternal::matchingArg(), casadi::FunctionInternal::replaceArg(), and casadi::FunctionInternal::size2_in().
{
     if (x.empty()) return x;
     // Replace arguments if needed
     if (!matchingArg(x, true)) {
       vector< MX > x_new = replaceArg(x, true);
       return map_mx(x_new, parallelization);
     }
     int n = 1;
     for (int i=0;i<x.size();++i) {
       n = max(x[i].size2()/size2_in(i), n);
     }
     vector<int> reduce_in;
     for (int i=0;i<x.size();++i) {
       if (x[i].size2()/size2_in(i)!=n) {
         reduce_in.push_back(i);
       }
     }
     // Call the internal function
     Function ms;
     if (reduce_in.size()>0) {
       ms = function().
         map("mapsum", parallelization, n, reduce_in, std::vector<int>());
     } else {
       ms = function().map("map", parallelization, n);
     }
     // Call the internal function
     return ms(x);
   }
std::vector< MX > casadi::FunctionInternal::mapsum_mx (const std::vector< MX > & arg, const std::string & parallelization) inherited
Definition at line 2829 of file function_internal.cpp.
References casadi::FunctionInternal::matchingArg(), casadi::FunctionInternal::n_out(), casadi::range(), casadi::FunctionInternal::replaceArg(), and casadi::FunctionInternal::size2_in().
{
     if (x.empty()) return x;
     // Replace arguments if needed
     if (!matchingArg(x, true)) {
       vector< MX > x_new = replaceArg(x, true);
       return mapsum_mx(x_new, parallelization);
     }
     int n = 1;
     for (int i=0;i<x.size();++i) {
       n = max(x[i].size2()/size2_in(i), n);
     }
     vector<int> reduce_in;
     for (int i=0;i<x.size();++i) {
       if (x[i].size2()/size2_in(i)!=n) {
         reduce_in.push_back(i);
       }
     }
     Function ms = function().map("mapsum", parallelization, n, reduce_in, range(n_out()));
     // Call the internal function
     return ms(x);
   }
template<typename M > bool casadi::FunctionInternal::matchingArg (const std::vector< M > & arg, bool hcat = false) const inherited
Parameters
hcat check if horizontal repetion of the function input is allowed
Definition at line 1087 of file function_internal.hpp.
References casadi::FunctionInternal::checkArg(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::size1_in(), casadi::FunctionInternal::size2_in(), and casadi::FunctionInternal::size_in().
Referenced by casadi::FunctionInternal::call(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::map_mx(), and casadi::FunctionInternal::mapsum_mx().
{
     checkArg(arg, hcat);
     int n_in = this->n_in();
     for (int i=0; i<n_in; ++i) {
       if (hcat) {
         if (arg.at(i).size1()!=size1_in(i)) return false;
         if (arg.at(i).size2() % size2_in(i)!=0 || arg.at(i).size2()==0) return false;
       } else {
         if (arg.at(i).size()!=size_in(i)) return false;
       }
     }
     return true;
   }
template<typename M > bool casadi::FunctionInternal::matchingRes (const std::vector< M > & arg) const inherited
Definition at line 1102 of file function_internal.hpp.
References casadi::FunctionInternal::checkRes(), casadi::FunctionInternal::n_out(), and casadi::FunctionInternal::size_out().
Referenced by casadi::FunctionInternal::reverse().
{
     checkRes(res);
     int n_out = this->n_out();
     for (int i=0; i<n_out; ++i) {
       if (res.at(i).size()!=size_out(i)) return false;
     }
     return true;
   }
void * casadi::FunctionInternal::memory (int ind) const inherited
Definition at line 2927 of file function_internal.cpp.
Referenced by casadi::FunctionInternal::_eval().
{
     return mem_.at(ind);
   }
bool casadi::FunctionInternal::monitored (const std::string & mod) const inherited
Definition at line 577 of file function_internal.cpp.
References casadi::FunctionInternal::monitors_.
Referenced by casadi::KinsolInterface::djac(), casadi::KinsolInterface::func(), casadi::FunctionInternal::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::jtimesB(), casadi::IdasInterface::psolveB(), casadi::IdasInterface::res(), casadi::IdasInterface::resB(), and casadi::IdasInterface::rhsQB().
{
     return monitors_.count(mod)>0;
   }
const MX casadi::FunctionInternal::mx_in (int ind) const virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2621 of file function_internal.cpp.
References casadi::FunctionInternal::sparsity_in(), casadi::GenericMatrix< MX >::sym(), and casadi::CodeGenerator::to_string().
{
     return MX::sym("x_" + CodeGenerator::to_string(ind), sparsity_in(ind));
   }
const std::vector< MX > casadi::FunctionInternal::mx_in () const virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2629 of file function_internal.cpp.
References casadi::FunctionInternal::n_in().
Referenced by casadi::FunctionInternal::getFullJacobian(), and casadi::FunctionInternal::wrapMXFunction().
{
     vector<MX> ret(n_in());
     for (int i=0; i<ret.size(); ++i) {
       ret[i] = mx_in(i);
     }
     return ret;
   }
const MX casadi::FunctionInternal::mx_out (int ind) const virtual inherited
Definition at line 2625 of file function_internal.cpp.
References casadi::FunctionInternal::sparsity_out(), casadi::GenericMatrix< MX >::sym(), and casadi::CodeGenerator::to_string().
{
     return MX::sym("r_" + CodeGenerator::to_string(ind), sparsity_out(ind));
   }
const std::vector< MX > casadi::FunctionInternal::mx_out () const virtual inherited
Definition at line 2637 of file function_internal.cpp.
References casadi::FunctionInternal::n_out().
{
     vector<MX> ret(n_out());
     for (int i=0; i<ret.size(); ++i) {
       ret[i] = mx_out(i);
     }
     return ret;
   }
int casadi::FunctionInternal::n_in () const inline inherited
Definition at line 518 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::_eval(), casadi::KinsolInterface::bjac(), calc_function(), casadi::FunctionInternal::checkArg(), casadi::KinsolInterface::djac(), casadi::Switch::eval(), casadi::QpToNlp::eval(), casadi::ImplicitToNlp::eval(), casadi::MXFunction::eval(), casadi::Newton::eval(), casadi::KinsolInterface::eval(), casadi::MXFunction::eval_mx(), casadi::SXFunction::evalAdj(), casadi::MXFunction::evalAdj(), casadi::SXFunction::evalFwd(), casadi::PureMap::evalGen(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::forward_mx(), casadi::FunctionInternal::fullJacobian(), casadi::KinsolInterface::func(), casadi::MXFunction::generateBody(), casadi::PureMap::generateBody(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getFullJacobian(), casadi::Jit::init(), casadi::Switch::init(), casadi::ImplicitToNlp::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::SimplifiedExternal::init(), casadi::SXFunction::init(), casadi::KinsolInterface::jtimes(), casadi::FunctionInternal::matchingArg(), casadi::FunctionInternal::mx_in(), casadi::Function::n_in(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::numel_in(), casadi::FunctionInternal::printDimensions(), casadi::KinsolInterface::psetup(), casadi::Rootfinder::reverse(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::reverse_mx(), casadi::Rootfinder::spAdj(), casadi::Integrator::spAdj(), casadi::PureMap::spAdj(), casadi::MXFunction::spAdj(), casadi::FunctionInternal::spAdj(), casadi::Rootfinder::spFwd(), casadi::Integrator::spFwd(), casadi::MXFunction::spFwd(), casadi::FunctionInternal::spFwd(), and casadi::FunctionInternal::sx_in().
 { return isp_.size();}
virtual int casadi::FunctionInternal::n_mem () const inline virtual inherited
Reimplemented in casadi::GenericExternal.
Definition at line 697 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::checkout().
 { return 0;}
int casadi::FunctionInternal::n_nodes () const virtual inherited
Reimplemented in casadi::MXFunction, and casadi::SXFunction.
Definition at line 2690 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'n_nodes' not defined for " + type_name());
   }
int casadi::FunctionInternal::n_out () const inline inherited
Definition at line 520 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::_eval(), casadi::KinsolInterface::bjac(), calc_function(), casadi::FunctionInternal::checkRes(), casadi::KinsolInterface::djac(), casadi::Switch::eval(), casadi::QpToNlp::eval(), casadi::ImplicitToNlp::eval(), casadi::MXFunction::eval(), casadi::Newton::eval(), casadi::KinsolInterface::eval(), casadi::SXFunction::evalAdj(), casadi::SXFunction::evalFwd(), casadi::MXFunction::evalFwd(), casadi::PureMap::evalGen(), casadi::Rootfinder::forward(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::forward_mx(), casadi::KinsolInterface::func(), casadi::MXFunction::generate_lifted(), casadi::MXFunction::generateBody(), casadi::PureMap::generateBody(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getFullJacobian(), casadi::FunctionInternal::gradient(), casadi::Jit::init(), casadi::Switch::init(), casadi::FunctionInternal::init(), init(), casadi::SimplifiedExternal::init(), casadi::FunctionInternal::jacobian(), casadi::KinsolInterface::jtimes(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::matchingRes(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::numel_out(), casadi::FunctionInternal::printDimensions(), casadi::KinsolInterface::psetup(), casadi::Rootfinder::reverse(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::reverse_mx(), casadi::Rootfinder::spAdj(), casadi::Integrator::spAdj(), casadi::PureMap::spAdj(), casadi::MXFunction::spAdj(), casadi::FunctionInternal::spAdj(), casadi::Rootfinder::spFwd(), casadi::Integrator::spFwd(), casadi::MXFunction::spFwd(), casadi::FunctionInternal::spFwd(), casadi::FunctionInternal::sx_out(), and casadi::FunctionInternal::tangent().
 { return osp_.size();}
const std::string& casadi::FunctionInternal::name () const inline inherited
Definition at line 551 of file function_internal.hpp.
Referenced by calc_function(), casadi::casadi_register_nlpsol_snopt(), casadi::casadi_register_qpsol_cplex(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::WorhpInterface::init(), and casadi::Scpgen::init().
 { return name_;}
virtual std::string casadi::FunctionInternal::name_in (int ind) const inline virtual inherited
Definition at line 602 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::checkArg(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::printDimensions(), and casadi::XFunction< DerivedType, MatType, NodeType >::XFunction().
{
       return ischeme_.at(ind);
     }
virtual std::string casadi::FunctionInternal::name_out (int ind) const inline virtual inherited
Definition at line 607 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::checkRes(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::printDimensions(), and casadi::FunctionInternal::reverse().
{
       return oscheme_.at(ind);
     }
std::vector< bool > casadi::Nlpsol::nl_var (const std::string & s_in, const std::vector< std::string > & s_out) const
Definition at line 646 of file nlpsol.cpp.
References casadi::Oracle::nl_var().
Referenced by casadi::IpoptInterface::init().
{
     return nlp_->nl_var(s_in, s_out);
   }
int casadi::FunctionInternal::nnz_in () const inherited
Definition at line 1727 of file function_internal.cpp.
References casadi::FunctionInternal::n_in().
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::QpToNlp::eval(), casadi::OoqpInterface::eval(), casadi::KinsolInterface::eval(), casadi::CplexInterface::eval(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsity(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::OoqpInterface::init(), casadi::ImplicitToNlp::init(), casadi::QpoasesInterface::init(), casadi::CplexInterface::init(), init(), casadi::CsparseInterface::init_memory(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), and casadi::FunctionInternal::spFwd().
{
     int ret=0;
     for (int iind=0; iind<n_in(); ++iind) ret += nnz_in(iind);
     return ret;
   }
int casadi::FunctionInternal::nnz_in (int ind) const inline inherited
Definition at line 527 of file function_internal.hpp.
 { return sparsity_in(ind).nnz(); }
int casadi::FunctionInternal::nnz_out () const inherited
Definition at line 1733 of file function_internal.cpp.
References casadi::FunctionInternal::n_out().
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::MXFunction::eval(), casadi::KinsolInterface::eval(), casadi::MXFunction::eval_sx(), casadi::FunctionInternal::fwdViaJac(), casadi::MXFunction::generateBody(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsity(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), init(), casadi::MXFunction::spAdj(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), casadi::MXFunction::spFwd(), and casadi::FunctionInternal::spFwd().
{
     int ret=0;
     for (int oind=0; oind<n_out(); ++oind) ret += nnz_out(oind);
     return ret;
   }
int casadi::FunctionInternal::nnz_out (int ind) const inline inherited
Definition at line 529 of file function_internal.hpp.
 { return sparsity_out(ind).nnz(); }
int casadi::FunctionInternal::numel_in () const inherited
Definition at line 1739 of file function_internal.cpp.
References casadi::FunctionInternal::n_in().
Referenced by casadi::FunctionInternal::reverse_mx(), and casadi::FunctionInternal::sparsity_jac().
{
     int ret=0;
     for (int iind=0; iind<n_in(); ++iind) ret += numel_in(iind);
     return ret;
   }
int casadi::FunctionInternal::numel_in (int ind) const inline inherited
Definition at line 535 of file function_internal.hpp.
 { return sparsity_in(ind).numel(); }
int casadi::FunctionInternal::numel_out (int ind) const inline inherited
Definition at line 536 of file function_internal.hpp.
 { return sparsity_out(ind).numel(); }
int casadi::FunctionInternal::numel_out () const inherited
Definition at line 1745 of file function_internal.cpp.
References casadi::FunctionInternal::n_out().
Referenced by casadi::FunctionInternal::forward_mx(), and casadi::FunctionInternal::sparsity_jac().
{
     int ret=0;
     for (int oind=0; oind<n_out(); ++oind) ret += numel_out(oind);
     return ret;
   }
virtual const char* casadi::PluginInterface< Nlpsol >::plugin_name () const pure virtual inherited
Implemented in casadi::IpoptInterface, casadi::Scpgen, casadi::Sqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
static Plugin casadi::PluginInterface< Nlpsol >::pluginFromRegFcn (RegFcn regfcn) static inherited
void casadi::FunctionInternal::print (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Reimplemented in casadi::MapSum, casadi::SXFunction, casadi::Mapaccum, casadi::KernelSum, casadi::MXFunction, and casadi::Switch.
Definition at line 437 of file function_internal.cpp.
References casadi::FunctionInternal::printDimensions().
Referenced by casadi::MXFunction::print(), and casadi::SXFunction::print().
{
     printDimensions(stream);
   }
void casadi::Nlpsol::print_fstats (const NlpsolMemory * m) const
Definition at line 464 of file nlpsol.cpp.
References casadi::NlpsolMemory::fstats, casadi::FStats::n_call, casadi::print_stats_line(), casadi::FStats::t_proc, casadi::FStats::t_wall, and casadi::userOut().
Referenced by casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), and casadi::IpoptInterface::solve().
{
     size_t maxNameLen=0;
     // Retrieve all nlp keys
     std::vector<std::string> keys;
     std::vector<std::string> keys_other;
     for (auto &&s : m->fstats) {
       maxNameLen = max(s.first.size(), maxNameLen);
       if (s.first.find("nlp")!=std::string::npos) {
         keys.push_back(s.first);
       } else if (s.first.find("mainloop")==std::string::npos) {
         keys_other.push_back(s.first);
       } else {
         continue;
       }
     }
     maxNameLen = max(std::string("all previous").size(), maxNameLen);
     maxNameLen = max(std::string("solver").size(), maxNameLen);
     // Print header
     std::stringstream s;
     std::string blankName(maxNameLen, ' ');
     s
       << blankName
       << "      proc           wall      num           mean             mean"
       << endl << blankName
       << "      time           time     evals       proc time        wall time";
     userOut() << s.str() << endl;
     // Sort the keys according to order
     std::vector<std::string> keys_order0;
     std::vector<std::string> keys_order1;
     std::vector<std::string> keys_order2;
     for (auto k : keys) {
       if (k.find("hess")!=std::string::npos) {
         keys_order2.push_back(k);
         continue;
       }
       if (k.find("grad")!=std::string::npos ||
           k.find("jac")!=std::string::npos) {
         keys_order1.push_back(k);
         continue;
       }
       keys_order0.push_back(k);
     }
     // Print all NLP stats
     for (auto keys : {&keys_order0, &keys_order1, &keys_order2}) {
         std::sort(keys->begin(), keys->end());
         for (auto k : *keys) {
           const FStats& fs = m->fstats.at(k);
           print_stats_line(maxNameLen, k, fs.n_call, fs.t_proc, fs.t_wall);
         }
     }
     // Sum the previously printed stats
     double t_wall_all_previous = 0;
     double t_proc_all_previous = 0;
     for (auto k : keys) {
       const FStats& fs = m->fstats.at(k);
       t_proc_all_previous += fs.t_proc;
       t_wall_all_previous += fs.t_wall;
     }
     print_stats_line(maxNameLen, "all previous", -1, t_proc_all_previous, t_wall_all_previous);
     // Sort and show the remainder of keys
     std::sort(keys_other.begin(), keys_other.end());
     for (std::string k : keys_other) {
       const FStats& fs = m->fstats.at(k);
       print_stats_line(maxNameLen, k, fs.n_call, fs.t_proc, fs.t_wall);
       t_proc_all_previous += fs.t_proc;
       t_wall_all_previous += fs.t_wall;
     }
     // Show the mainloop stats
     const FStats& fs_mainloop = m->fstats.at("mainloop");
     if (fs_mainloop.n_call>0) {
       print_stats_line(maxNameLen, "solver", -1,
         fs_mainloop.t_proc-t_proc_all_previous, fs_mainloop.t_wall-t_wall_all_previous);
       print_stats_line(maxNameLen, "mainloop", -1, fs_mainloop.t_proc, fs_mainloop.t_wall);
     }
   }
void casadi::FunctionInternal::printDimensions (std::ostream & stream) const inherited
Definition at line 409 of file function_internal.cpp.
References casadi::Sparsity::dim(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_in(), casadi::FunctionInternal::name_out(), casadi::FunctionInternal::sparsity_in(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::print().
{
     stream << " Number of inputs: " << n_in() << endl;
     for (int i=0; i<n_in(); ++i) {
       stream << "  Input " << i  << " (\"" << name_in(i) << "\"): "
              << sparsity_in(i).dim() << endl;
     }
     stream << " Number of outputs: " << n_out() << endl;
     for (int i=0; i<n_out(); ++i) {
       stream << "  Output " << i  << " (\"" << name_out(i) << "\"): "
              << sparsity_out(i).dim() << endl;
     }
   }
void casadi::FunctionInternal::printOption (const std::string & name, std::ostream & stream) const inherited
Definition at line 428 of file function_internal.cpp.
References casadi::Options::find(), casadi::FunctionInternal::get_options(), and casadi::Options::Entry::print().
Referenced by casadi::FunctionInternal::construct().
{
     const Options::Entry* entry = get_options().find(name);
     if (entry!=0) {
       entry->print(name, stream);
     } else {
       stream << "  \"" << name << "\" does not exist.";
     }
   }
void casadi::FunctionInternal::printOptions (std::ostream & stream) const inherited
Definition at line 422 of file function_internal.cpp.
References casadi::FunctionInternal::get_options(), and casadi::Options::print().
{
     stream << "\"Option name\" [type] = value" << endl;
     get_options().print(stream);
     stream << endl;
   }
template<typename MatType > bool casadi::FunctionInternal::purgable (const std::vector< MatType > & seed) static inherited
Definition at line 874 of file function_internal.hpp.
Referenced by casadi::MXFunction::evalAdj(), and casadi::MXFunction::evalFwd().
{
     for (typename std::vector<MatType>::const_iterator i=v.begin(); i!=v.end(); ++i) {
       if (!i->is_zero()) return false;
     }
     return true;
   }
void casadi::Nlpsol::register_function (const Function & fcn)
Register the function for evaluation and statistics gathering
Definition at line 637 of file nlpsol.cpp.
References all_functions_, casadi::FunctionInternal::alloc(), and casadi::Function::name().
Referenced by create_function(), and casadi::IpoptInterface::init().
{
     // Make sure that the function names are unique
     for (const Function& f : all_functions_) casadi_assert(fcn.name()!=f.name());
     // Add to the list
     all_functions_.push_back(fcn);
     alloc(fcn);
   }
static void casadi::PluginInterface< Nlpsol >::registerPlugin (const Plugin & plugin) static inherited
Referenced by casadi::casadi_load_nlpsol_snopt().
static void casadi::PluginInterface< Nlpsol >::registerPlugin (RegFcn regfcn) static inherited
void casadi::FunctionInternal::release (int mem) inherited
Definition at line 2949 of file function_internal.cpp.
{
     unused_.push(mem);
   }
template<typename M > std::vector< std::vector< M > > casadi::FunctionInternal::replaceAdjSeed (const std::vector< std::vector< M > > & aseed) const inherited
Definition at line 1158 of file function_internal.hpp.
References casadi::FunctionInternal::replaceRes().
Referenced by casadi::FunctionInternal::reverse().
{
     std::vector<std::vector<M> > r(aseed.size());
     for (int d=0; d<r.size(); ++d) r[d] = replaceRes(aseed[d]);
     return r;
   }
template<typename M > std::vector< M > casadi::FunctionInternal::replaceArg (const std::vector< M > & arg, bool hcat = false) const inherited
Parameters
hcat check if horizontal repetion of the function input is allowed
Definition at line 1135 of file function_internal.hpp.
References casadi::replaceMat(), and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::FunctionInternal::call(), casadi::FunctionInternal::map_mx(), casadi::FunctionInternal::mapsum_mx(), and casadi::FunctionInternal::replaceFwdSeed().
{
     std::vector<M> r(arg.size());
     for (int i=0; i<r.size(); ++i) r[i] = replaceMat(arg[i], sparsity_in(i), hcat);
     return r;
   }
template<typename M > std::vector< std::vector< M > > casadi::FunctionInternal::replaceFwdSeed (const std::vector< std::vector< M > > & fseed) const inherited
Definition at line 1150 of file function_internal.hpp.
References casadi::FunctionInternal::replaceArg().
Referenced by casadi::FunctionInternal::forward().
{
     std::vector<std::vector<M> > r(fseed.size());
     for (int d=0; d<r.size(); ++d) r[d] = replaceArg(fseed[d]);
     return r;
   }
template<typename M > std::vector< M > casadi::FunctionInternal::replaceRes (const std::vector< M > & res) const inherited
Definition at line 1142 of file function_internal.hpp.
References casadi::replaceMat(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::replaceAdjSeed().
{
     std::vector<M> r(res.size());
     for (int i=0; i<r.size(); ++i) r[i] = replaceMat(res[i], sparsity_out(i));
     return r;
   }
void casadi::FunctionInternal::repr (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Definition at line 441 of file function_internal.cpp.
References casadi::FunctionInternal::name_.
Referenced by casadi::MXFunction::eval(), and casadi::SXFunction::eval().
{
     stream << name_;
   }
template<typename M > void casadi::FunctionInternal::reverse (const std::vector< M > & arg, const std::vector< M > & res, const std::vector< std::vector< M > > & aseed, std::vector< std::vector< M > > & asens, bool always_inline, bool never_inline) inherited
Definition at line 1028 of file function_internal.hpp.
References casadi::FunctionInternal::_reverse(), casadi::FunctionInternal::checkArg(), casadi::FunctionInternal::checkMat(), casadi::FunctionInternal::checkRes(), casadi::FunctionInternal::matchingRes(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_out(), casadi::FunctionInternal::replaceAdjSeed(), casadi::FunctionInternal::size_out(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::Function::reverse(), and casadi::FunctionInternal::reverse_mx().
{
     // Check inputs
     checkArg(arg);
     checkRes(res);
     // Check reverse mode seeds dimensions
     int n_out = this->n_out();
     for (int d=0; d<aseed.size(); ++d) {
       casadi_assert_message(aseed[d].size()==n_out,
                             "Incorrect number of adjoint seeds for direction " << d
                             << ": Expected " << n_out << ", got " << aseed[d].size());
       for (int i=0; i<n_out; ++i) {
         casadi_assert_message(checkMat(aseed[d][i].sparsity(), sparsity_out(i)),
                               "Adjoint seed " << i << " (" << name_out(i) << ") for direction " << d
                               << " has mismatching shape. Expected " << size_out(i)
                               << ", got " << aseed[d][i].size());
       }
     }
     // Check if reverse mode seeds need to be replaced
     for (int d=0; d<aseed.size(); ++d) {
       if (!matchingRes(aseed[d])) {
         return reverse(arg, res, replaceAdjSeed(aseed), asens,
                        always_inline, never_inline);
       }
     }
     // Call the type-specific method
     _reverse(arg, res, aseed, asens, always_inline, never_inline);
   }
Function casadi::FunctionInternal::reverse (int nadj) inherited
Definition at line 1599 of file function_internal.cpp.
References casadi::FunctionInternal::compilerplugin_, casadi::FunctionInternal::derivative_adj_, casadi::FunctionInternal::get_n_reverse(), casadi::FunctionInternal::get_reverse(), casadi::FunctionInternal::ischeme_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_options_, casadi::Function::n_in(), casadi::FunctionInternal::n_in(), casadi::Function::n_out(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_, casadi::FunctionInternal::oscheme_, casadi::shared_cast(), casadi::Sparsity::size(), casadi::Function::size_in(), casadi::Function::size_out(), casadi::FunctionInternal::sparsity_in(), and casadi::FunctionInternal::sparsity_out().
{
     casadi_assert(nadj>=0);
     // Check if there are enough adjoint directions allocated
     if (nadj>=derivative_adj_.size()) {
       derivative_adj_.resize(nadj+1);
     }
     // Quick return if already cached
     if (derivative_adj_[nadj].alive()) {
       return shared_cast<Function>(derivative_adj_[nadj].shared());
     }
     // Give it a suitable name
     stringstream ss;
     ss << "adj" << nadj << "_" << name_;
     string name = ss.str();
     // Get the number of inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Names of inputs
     std::vector<std::string> i_names;
     i_names.reserve(n_in + n_out + n_out*nadj);
     // Nondifferentiated inputs
     for (int i=0; i<n_in; ++i) {
       i_names.push_back("der_" + ischeme_.at(i));
     }
     // Nondifferentiated outputs (given)
     for (int i=0; i<n_out; ++i) {
       i_names.push_back("der_" + oscheme_.at(i));
     }
     // Adjoint seeds
     for (int d=0; d<nadj; ++d) {
       for (int i=0; i<n_out; ++i) {
         ss.str(string());
         ss << "adj" << d << "_" << oscheme_.at(i);
         i_names.push_back(ss.str());
       }
     }
     // Names of outputs
     std::vector<std::string> o_names;
     o_names.reserve(n_in*nadj);
     // Adjoint sensitivities
     for (int d=0; d<nadj; ++d) {
       for (int i=0; i<n_in; ++i) {
         ss.str(string());
         ss << "adj" << d << "_" << ischeme_.at(i);
         o_names.push_back(ss.str());
       }
     }
     // Options
     Dict opts = {{"input_scheme", i_names},
                  {"output_scheme", o_names},
                  {"jit", jit_},
                  {"compiler", compilerplugin_},
                  {"jit_options", jit_options_},
                  {"derivative_of", function()}};
     // Return value
     casadi_assert(get_n_reverse()>0);
     Function ret = get_reverse(name, nadj, opts);
     // Consistency check for inputs
     for (int i=0; i<ret.n_in(); ++i) {
       const Sparsity& sp = i<n_in ? sparsity_in(i) :
         i<n_in+n_out ? sparsity_out(i-n_in) :
         sparsity_out((i-n_in-n_out) % n_out);
       casadi_assert_message(ret.size_in(i)==sp.size(),
                             "Incorrect shape for " << ret << " input " << i << " \""
                             << i_names.at(i) << "\". Expected " << sp.size()
                             << " but got " << ret.size_in(i));
     }
     // Consistency check for outputs
     for (int i=0; i<ret.n_out(); ++i) {
       const Sparsity& sp = sparsity_in(i % n_in);
       casadi_assert_message(ret.size_out(i)==sp.size(),
                             "Incorrect shape for " << ret << " output " << i << " \""
                             << o_names.at(i) << "\". Expected " << sp.size()
                             << " but got " << ret.size_out(i));
     }
     // Save to cache
     derivative_adj_[nadj] = ret;
     // Return generated function
     return ret;
   }
void casadi::FunctionInternal::reverse_dm (const std::vector< DM > & arg, const std::vector< DM > & res, const std::vector< std::vector< DM > > & aseed, std::vector< std::vector< DM > > & asens, bool always_inline, bool never_inline) virtual inherited
Definition at line 2538 of file function_internal.cpp.
{
     casadi_error("Not implemented");
   }
void casadi::FunctionInternal::reverse_mx (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens, bool always_inline, bool never_inline) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2418 of file function_internal.cpp.
References casadi::FunctionInternal::adjViaJac(), casadi::Call::create(), casadi::FunctionInternal::fullJacobian(), casadi::FunctionInternal::hasDerivative(), casadi::mtimes(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::FunctionInternal::numel_in(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::size_in(), casadi::MX::T(), and casadi::FunctionInternal::type_name().
Referenced by casadi::MXFunction::reverse_mx().
{
     casadi_assert_message(!(always_inline && never_inline), "Inconsistent options");
     casadi_assert_message(!always_inline, "Class " + type_name() +
                           " cannot be inlined in an MX expression");
     // Derivative information must be available
     casadi_assert(hasDerivative());
     // Number of directional derivatives
     int nadj = aseed.size();
     asens.resize(nadj);
     // Quick return if no seeds
     if (nadj==0) return;
     // Number inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Calculating full Jacobian and then multiplying likely cheaper
     if (adjViaJac(nadj)) {
       // Join adjoint seeds
       vector<MX> v(nadj);
       for (int d=0; d<nadj; ++d) {
         v[d] = veccat(aseed[d]);
       }
       // Multiply the transposed Jacobian from the right
       MX J = fullJacobian()(arg).at(0);
       v = horzsplit(mtimes(J.T(), horzcat(v)));
       // Vertical offsets
       vector<int> offset(n_in+1, 0);
       for (int i=0; i<n_in; ++i) {
         offset[i+1] = offset[i]+numel_in(i);
       }
       // Collect adjoint sensitivities
       for (int d=0; d<nadj; ++d) {
         asens[d].resize(n_in);
         vector<MX> a = vertsplit(v[d], offset);
         for (int i=0; i<n_in; ++i) {
           if (asens[d][i].is_empty(true)) {
             asens[d][i] = reshape(a[i], size_in(i));
           } else {
             asens[d][i] += reshape(a[i], size_in(i));
           }
         }
       }
       return;
     }
     // All inputs and seeds
     vector<MX> darg;
     darg.reserve(n_in + n_out + n_out*nadj);
     darg.insert(darg.end(), arg.begin(), arg.end());
     darg.insert(darg.end(), res.begin(), res.end());
     for (int d=0; d<nadj; ++d) {
       darg.insert(darg.end(), aseed[d].begin(), aseed[d].end());
     }
     // Create derivative function
     Function dfcn = reverse(nadj);
     // Create the evaluation node
     vector<MX> x = Call::create(dfcn, darg);
     vector<MX>::iterator x_it = x.begin();
     // Retrieve sensitivities
     for (int d=0; d<nadj; ++d) {
       asens[d].resize(n_in);
       for (int i=0; i<n_in; ++i) {
         if (asens[d][i].is_empty(true)) {
           asens[d][i] = *x_it++;
         } else {
           asens[d][i] += *x_it++;
         }
       }
     }
     casadi_assert(x_it==x.end());
   }
void casadi::FunctionInternal::reverse_sx (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & aseed, std::vector< std::vector< SX > > & asens, bool always_inline, bool never_inline) virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2517 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_assert_message(!(always_inline && never_inline), "Inconsistent options");
     if (aseed.empty()) { // Quick return if no seeds
       asens.clear();
       return;
     }
     casadi_error("'reverse' (SX) not defined for " + type_name());
   }
void casadi::FunctionInternal::set_forward (const Function & fcn, int nfwd) inherited
Definition at line 1696 of file function_internal.cpp.
References casadi::FunctionInternal::derivative_fwd_.
{
     // Check if there are enough forward directions allocated
     if (nfwd>=derivative_fwd_.size()) {
       derivative_fwd_.resize(nfwd+1);
     }
     // Save to cache
     derivative_fwd_[nfwd] = fcn;
   }
void casadi::FunctionInternal::set_jac_sparsity (const Sparsity & sp, int iind, int oind, bool compact) inherited
Definition at line 1291 of file function_internal.cpp.
References casadi::FunctionInternal::jac_sparsity_, and casadi::FunctionInternal::jac_sparsity_compact_.
{
     if (compact) {
       jac_sparsity_compact_.elem(oind, iind) = sp;
     } else {
       jac_sparsity_.elem(oind, iind) = sp;
     }
   }
void casadi::FunctionInternal::set_reverse (const Function & fcn, int nadj) inherited
Definition at line 1707 of file function_internal.cpp.
References casadi::FunctionInternal::derivative_adj_.
{
     // Check if there are enough adjoint directions allocated
     if (nadj>=derivative_adj_.size()) {
       derivative_adj_.resize(nadj+1);
     }
     // Save to cache
     derivative_adj_[nadj] = fcn;
   }
void casadi::Nlpsol::set_temp (void * mem, const double ** arg, double ** res, int * iw, double * w) const virtual
Reimplemented from casadi::FunctionInternal.
Definition at line 397 of file nlpsol.cpp.
References casadi::WorkMemory::arg.
{
     auto m = static_cast<NlpsolMemory*>(mem);
     m->arg = arg;
     m->res = res;
     m->iw = iw;
     m->w = w;
   }
void casadi::Nlpsol::set_work (void * mem, const double **& arg, double **& res, int *& iw, double *& w) const virtual
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::IpoptInterface, casadi::Scpgen, casadi::Sqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
Definition at line 372 of file nlpsol.cpp.
References casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_G0, casadi::NLPSOL_LAM_P, casadi::NLPSOL_LAM_X, casadi::NLPSOL_LAM_X0, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_NUM_IN, casadi::NLPSOL_NUM_OUT, casadi::NLPSOL_P, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, casadi::NLPSOL_X, casadi::NLPSOL_X0, and casadi::NlpsolMemory::x0.
Referenced by casadi::KnitroInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::WorhpInterface::set_work(), casadi::Sqpmethod::set_work(), casadi::Scpgen::set_work(), and casadi::IpoptInterface::set_work().
{
     auto m = static_cast<NlpsolMemory*>(mem);
     // Get input pointers
     m->x0 = arg[NLPSOL_X0];
     m->p = arg[NLPSOL_P];
     m->lbx = arg[NLPSOL_LBX];
     m->ubx = arg[NLPSOL_UBX];
     m->lbg = arg[NLPSOL_LBG];
     m->ubg = arg[NLPSOL_UBG];
     m->lam_x0 = arg[NLPSOL_LAM_X0];
     m->lam_g0 = arg[NLPSOL_LAM_G0];
     arg += NLPSOL_NUM_IN;
     // Get output pointers
     m->x = res[NLPSOL_X];
     m->f = res[NLPSOL_F];
     m->g = res[NLPSOL_G];
     m->lam_x = res[NLPSOL_LAM_X];
     m->lam_g = res[NLPSOL_LAM_G];
     m->lam_p = res[NLPSOL_LAM_P];
     res += NLPSOL_NUM_OUT;
   }
void casadi::FunctionInternal::setJacobian (const Function & jac, int iind, int oind, bool compact) inherited
Definition at line 1488 of file function_internal.cpp.
References casadi::FunctionInternal::jac_, and casadi::FunctionInternal::jac_compact_.
Referenced by casadi::Function::setJacobian().
{
     if (compact) {
       jac_compact_.elem(oind, iind) = jac;
     } else {
       jac_.elem(oind, iind) = jac;
     }
   }
void casadi::Nlpsol::setOptionsFromFile (const std::string & file) virtual
Definition at line 359 of file nlpsol.cpp.
{
     casadi_error("Nlpsol::setOptionsFromFile not defined for class "
                  << typeid(*this).name());
   }
void casadi::FunctionInternal::setup (void * mem, const double ** arg, double ** res, int * iw, double * w) const inherited
Definition at line 2864 of file function_internal.cpp.
References casadi::FunctionInternal::set_temp(), and casadi::FunctionInternal::set_work().
Referenced by casadi::Linsol::eval(), casadi::Integrator::eval(), and eval().
{
     set_work(mem, arg, res, iw, w);
     set_temp(mem, arg, res, iw, w);
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
static std::string casadi::Nlpsol::shortname () inline static
Definition at line 200 of file nlpsol_impl.hpp.
 { return "nlpsol";}
std::string casadi::FunctionInternal::signature (const std::string & fname) const inherited
Definition at line 1888 of file function_internal.cpp.
References casadi::FunctionInternal::simplifiedCall().
Referenced by casadi::CodeGenerator::add(), casadi::External::addDependency(), and casadi::FunctionInternal::generateFunction().
{
     if (simplifiedCall()) {
       return "void " + fname + "(const real_t* arg, real_t* res)";
     } else {
       return "int " + fname + "(const real_t** arg, real_t** res, int* iw, real_t* w, int mem)";
     }
   }
void casadi::FunctionInternal::simple (const double * arg, double * res) virtual inherited
Definition at line 1441 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::FunctionInternal::_eval().
{
     casadi_error("'simple' not defined for " + type_name());
   }
virtual bool casadi::FunctionInternal::simplifiedCall () const inline virtual inherited
Reimplemented in casadi::SimplifiedExternal, and casadi::Jit.
Definition at line 463 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_eval(), casadi::FunctionInternal::addDependency(), casadi::Call::generate(), casadi::FunctionInternal::generateFunction(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::signature(), and casadi::CodeGenerator::simplifiedCall().
 { return false;}
int casadi::FunctionInternal::size1_in (int ind) const inline inherited
Definition at line 542 of file function_internal.hpp.
Referenced by casadi::Integrator::aug_adj(), casadi::SymbolicQr::init(), casadi::CsparseInterface::init_memory(), and casadi::FunctionInternal::matchingArg().
 { return sparsity_in(ind).size1(); }
int casadi::FunctionInternal::size1_out (int ind) const inline inherited
Definition at line 544 of file function_internal.hpp.
 { return sparsity_out(ind).size1(); }
int casadi::FunctionInternal::size2_in (int ind) const inline inherited
Definition at line 543 of file function_internal.hpp.
Referenced by casadi::CsparseInterface::init_memory(), casadi::FunctionInternal::map_mx(), casadi::FunctionInternal::mapsum_mx(), and casadi::FunctionInternal::matchingArg().
 { return sparsity_in(ind).size2(); }
int casadi::FunctionInternal::size2_out (int ind) const inline inherited
Definition at line 545 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::map_mx().
 { return sparsity_out(ind).size2(); }
std::pair<int, int> casadi::FunctionInternal::size_in (int ind) const inline inherited
Definition at line 546 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::checkArg(), casadi::MXFunction::evalAdj(), casadi::Rootfinder::forward(), casadi::FunctionInternal::forward(), casadi::Integrator::init(), casadi::FunctionInternal::matchingArg(), casadi::Rootfinder::reverse(), casadi::FunctionInternal::reverse_mx(), and casadi::CollocationIntegrator::setupFG().
 { return sparsity_in(ind).size(); }
std::pair<int, int> casadi::FunctionInternal::size_out (int ind) const inline inherited
Definition at line 547 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::checkRes(), casadi::MXFunction::evalFwd(), casadi::FunctionInternal::forward_mx(), casadi::Integrator::get_forward(), init(), casadi::FunctionInternal::matchingRes(), casadi::Rootfinder::reverse(), and casadi::FunctionInternal::reverse().
 { return sparsity_out(ind).size(); }
virtual void casadi::Nlpsol::solve (void * mem) const pure virtual
Implemented in casadi::IpoptInterface, casadi::Scpgen, casadi::Sqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, and casadi::KnitroInterface.
Referenced by eval().
void casadi::FunctionInternal::spAdj (bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem) virtual inherited
Reimplemented in casadi::SXFunction, casadi::MapSum, casadi::MXFunction, casadi::PureMap, casadi::Integrator, and casadi::Rootfinder.
Definition at line 2218 of file function_internal.cpp.
References casadi::Sparsity::colind(), casadi::SharedObject::is_null(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::row(), casadi::Sparsity::size2(), and casadi::FunctionInternal::sparsity_jac().
Referenced by casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::Mapaccum::spAdj(), casadi::PureMap::spAdj(), and casadi::MapSum::spAdj().
{
     // Get the number of inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Loop over outputs
     for (int oind=0; oind<n_out; ++oind) {
       // Skip if nothing to assign
       if (res[oind]==0 || nnz_out(oind)==0) continue;
       // Loop over inputs
       for (int iind=0; iind<n_in; ++iind) {
         // Skip if no seeds
         if (arg[iind]==0 || nnz_in(iind)==0) continue;
         // Get the sparsity of the Jacobian block
         Sparsity sp = sparsity_jac(iind, oind, true, false);
         if (sp.is_null() || sp.nnz() == 0) continue; // Skip if zero
         // Carry out the sparse matrix-vector multiplication
         int d1 = sp.size2();
         const int *colind = sp.colind(), *row = sp.row();
         for (int cc=0; cc<d1; ++cc) {
           for (int el = colind[cc]; el < colind[cc+1]; ++el) {
             arg[iind][cc] |= res[oind][row[el]];
           }
         }
       }
       // Clear seeds
       casadi_fill(res[oind], nnz_out(oind), bvec_t(0));
     }
   }
const Sparsity& casadi::FunctionInternal::sparsity_in (int ind) const inline inherited
Definition at line 618 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::checkArg(), casadi::Switch::eval(), casadi::OoqpInterface::eval(), casadi::GurobiInterface::eval(), casadi::QpoasesInterface::eval(), casadi::CplexInterface::eval(), casadi::SXFunction::evalAdj(), casadi::SXFunction::evalFwd(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getFullJacobian(), casadi::Switch::init(), casadi::OoqpInterface::init(), casadi::QpToNlp::init(), casadi::ImplicitToNlp::init(), casadi::SymbolicQr::init(), casadi::Sqpmethod::init(), casadi::CsparseInterface::init_memory(), casadi::CplexInterface::init_memory(), casadi::SymbolicQr::linsol_eval_sx(), casadi::Linsol::linsol_spAdj(), casadi::Linsol::linsol_spFwd(), casadi::Linsol::linsol_spsolve(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::printDimensions(), casadi::FunctionInternal::replaceArg(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::sparsity_jac(), casadi::FunctionInternal::sx_in(), and casadi::FunctionInternal::tangent().
{
       return isp_.at(ind);
     }
const Sparsity& casadi::FunctionInternal::sparsity_in (const std::string & iname) const inline inherited
Definition at line 621 of file function_internal.hpp.
{
       return sparsity_in(index_in(iname));
     }
Sparsity & casadi::FunctionInternal::sparsity_jac (int iind, int oind, bool compact, bool symmetric) inherited
Definition at line 1299 of file function_internal.cpp.
References casadi::Sparsity::enlargeColumns(), casadi::Sparsity::enlargeRows(), casadi::Sparsity::find(), casadi::FunctionInternal::getJacSparsity(), casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity_, casadi::FunctionInternal::jac_sparsity_compact_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::numel_in(), casadi::FunctionInternal::numel_out(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sparsity_in(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::getPartition(), casadi::FunctionInternal::spAdj(), and casadi::FunctionInternal::spFwd().
{
     // Get an owning reference to the block
     Sparsity jsp = compact ? jac_sparsity_compact_.elem(oind, iind)
         : jac_sparsity_.elem(oind, iind);
     // Generate, if null
     if (jsp.is_null()) {
       if (compact) {
         // Use internal routine to determine sparsity
         jsp = getJacSparsity(iind, oind, symmetric);
       } else {
         // Get the compact sparsity pattern
         Sparsity sp = sparsity_jac(iind, oind, true, symmetric);
         // Enlarge if sparse output
         if (numel_out(oind)!=sp.size1()) {
           casadi_assert(sp.size1()==nnz_out(oind));
           // New row for each old row
           vector<int> row_map = sparsity_out(oind).find();
           // Insert rows
           sp.enlargeRows(numel_out(oind), row_map);
         }
         // Enlarge if sparse input
         if (numel_in(iind)!=sp.size2()) {
           casadi_assert(sp.size2()==nnz_in(iind));
           // New column for each old column
           vector<int> col_map = sparsity_in(iind).find();
           // Insert columns
           sp.enlargeColumns(numel_in(iind), col_map);
         }
         // Save
         jsp = sp;
       }
     }
     // If still null, not dependent
     if (jsp.is_null()) {
       jsp = Sparsity(nnz_out(oind), nnz_in(iind));
     }
     // Return a reference to the block
     Sparsity& jsp_ref = compact ? jac_sparsity_compact_.elem(oind, iind) :
         jac_sparsity_.elem(oind, iind);
     jsp_ref = jsp;
     return jsp_ref;
   }
const Sparsity& casadi::FunctionInternal::sparsity_out (int ind) const inline inherited
Definition at line 629 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::checkRes(), casadi::Switch::eval(), casadi::SXFunction::evalAdj(), casadi::MXFunction::evalAdj(), casadi::SXFunction::evalFwd(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::gradient(), casadi::SXFunction::hess(), casadi::FunctionInternal::hessian(), casadi::Switch::init(), init(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::printDimensions(), casadi::FunctionInternal::replaceRes(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::sparsity_jac(), and casadi::FunctionInternal::sx_out().
{
       return osp_.at(ind);
     }
const Sparsity& casadi::FunctionInternal::sparsity_out (const std::string & iname) const inline inherited
Definition at line 632 of file function_internal.hpp.
{
       return sparsity_out(index_out(iname));
     }
virtual bool casadi::FunctionInternal::spCanEvaluate (bool fwd) inline virtual inherited
Reimplemented in casadi::SXFunction, casadi::MapSum, casadi::MXFunction, casadi::PureMap, casadi::Integrator, casadi::Mapaccum, casadi::KernelSum, and casadi::Rootfinder.
Definition at line 115 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adWeightSp(), casadi::FunctionInternal::getJacSparsity(), and casadi::FunctionInternal::getJacSparsityHierarchicalSymm().
 { return false;}
void casadi::FunctionInternal::spFwd (const bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem) virtual inherited
Reimplemented in casadi::SXFunction, casadi::MapSum, casadi::MXFunction, casadi::PureMap, casadi::Integrator, casadi::Mapaccum, casadi::KernelSum, and casadi::Rootfinder.
Definition at line 2184 of file function_internal.cpp.
References casadi::Sparsity::colind(), casadi::SharedObject::is_null(), casadi::FunctionInternal::n_in(), casadi::FunctionInternal::n_out(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::row(), casadi::Sparsity::size2(), and casadi::FunctionInternal::sparsity_jac().
Referenced by casadi::FunctionInternal::_eval(), casadi::FunctionInternal::getJacSparsityHierarchical(), and casadi::FunctionInternal::getJacSparsityHierarchicalSymm().
{
     // Get the number of inputs and outputs
     int n_in = this->n_in();
     int n_out = this->n_out();
     // Loop over outputs
     for (int oind=0; oind<n_out; ++oind) {
       // Skip if nothing to assign
       if (res[oind]==0 || nnz_out(oind)==0) continue;
       // Clear result
       casadi_fill(res[oind], nnz_out(oind), bvec_t(0));
       // Loop over inputs
       for (int iind=0; iind<n_in; ++iind) {
         // Skip if no seeds
         if (arg[iind]==0 || nnz_in(iind)==0) continue;
         // Get the sparsity of the Jacobian block
         Sparsity sp = sparsity_jac(iind, oind, true, false);
         if (sp.is_null() || sp.nnz() == 0) continue; // Skip if zero
         // Carry out the sparse matrix-vector multiplication
         int d1 = sp.size2();
         const int *colind = sp.colind(), *row = sp.row();
         for (int cc=0; cc<d1; ++cc) {
           for (int el = colind[cc]; el < colind[cc+1]; ++el) {
             res[oind][row[el]] |= arg[iind][cc];
           }
         }
       }
     }
   }
const SX casadi::FunctionInternal::sx_in (int ind) const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2597 of file function_internal.cpp.
References casadi::FunctionInternal::sparsity_in(), casadi::GenericMatrix< Matrix< SXElem > >::sym(), and casadi::CodeGenerator::to_string().
{
     return SX::sym("x_" + CodeGenerator::to_string(ind), sparsity_in(ind));
   }
const std::vector< SX > casadi::FunctionInternal::sx_in () const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2605 of file function_internal.cpp.
References casadi::FunctionInternal::n_in().
{
     vector<SX> ret(n_in());
     for (int i=0; i<ret.size(); ++i) {
       ret[i] = sx_in(i);
     }
     return ret;
   }
const SX casadi::FunctionInternal::sx_out (int ind) const virtual inherited
Definition at line 2601 of file function_internal.cpp.
References casadi::FunctionInternal::sparsity_out(), casadi::GenericMatrix< Matrix< SXElem > >::sym(), and casadi::CodeGenerator::to_string().
{
     return SX::sym("r_" + CodeGenerator::to_string(ind), sparsity_out(ind));
   }
const std::vector< SX > casadi::FunctionInternal::sx_out () const virtual inherited
Definition at line 2613 of file function_internal.cpp.
References casadi::FunctionInternal::n_out().
{
     vector<SX> ret(n_out());
     for (int i=0; i<ret.size(); ++i) {
       ret[i] = sx_out(i);
     }
     return ret;
   }
template<typename MatType > std::vector< std::vector< MatType > > casadi::FunctionInternal::symbolicAdjSeed (int nadj, const std::vector< MatType > & v) inherited
Definition at line 908 of file function_internal.hpp.
{
     std::vector<std::vector<MatType> > aseed(nadj, v);
     for (int dir=0; dir<nadj; ++dir) {
       // Replace symbolic inputs
       int oind=0;
       for (typename std::vector<MatType>::iterator i=aseed[dir].begin();
           i!=aseed[dir].end();
           ++i, ++oind) {
         // Name of the adjoint seed
         std::stringstream ss;
         ss << "a";
         if (nadj>1) ss << dir << "_";
         ss << oind;
         // Save to matrix
         *i = MatType::sym(ss.str(), i->sparsity());
       }
     }
     return aseed;
   }
template<typename MatType > std::vector< std::vector< MatType > > casadi::FunctionInternal::symbolicFwdSeed (int nfwd, const std::vector< MatType > & v) inherited
Definition at line 883 of file function_internal.hpp.
{
     std::vector<std::vector<MatType> > fseed(nfwd, v);
     for (int dir=0; dir<nfwd; ++dir) {
       // Replace symbolic inputs
       int iind=0;
       for (typename std::vector<MatType>::iterator i=fseed[dir].begin();
           i!=fseed[dir].end();
           ++i, ++iind) {
         // Name of the forward seed
         std::stringstream ss;
         ss << "f";
         if (nfwd>1) ss << dir;
         ss << "_";
         ss << iind;
         // Save to matrix
         *i = MatType::sym(ss.str(), i->sparsity());
       }
     }
     return fseed;
   }
std::vector< MX > casadi::FunctionInternal::symbolicOutput (const std::vector< MX > & arg) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 581 of file function_internal.cpp.
Referenced by casadi::FunctionInternal::getFullJacobian(), and casadi::MXFunction::symbolicOutput().
{
     return function()(arg);
   }
size_t casadi::FunctionInternal::sz_arg () const inline inherited
Definition at line 658 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_arg(), casadi::MXFunction::eval_sx(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::External::init(), and casadi::FunctionInternal::sz_work().
 { return sz_arg_per_ + sz_arg_tmp_;}
size_t casadi::FunctionInternal::sz_iw () const inline inherited
Definition at line 664 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_iw(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::External::init(), and casadi::FunctionInternal::sz_work().
 { return sz_iw_per_ + sz_iw_tmp_;}
size_t casadi::FunctionInternal::sz_res () const inline inherited
Definition at line 661 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_res(), casadi::MXFunction::eval_sx(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::External::init(), and casadi::FunctionInternal::sz_work().
 { return sz_res_per_ + sz_res_tmp_;}
size_t casadi::FunctionInternal::sz_w () const inline inherited
Definition at line 667 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_w(), casadi::SXFunction::generateBody(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::External::init(), casadi::Integrator::init(), casadi::MXFunction::init(), casadi::MXFunction::spAdj(), casadi::SXFunction::spAdj(), and casadi::FunctionInternal::sz_work().
 { return sz_w_per_ + sz_w_tmp_;}
void casadi::FunctionInternal::sz_work (size_t & sz_arg, size_t & sz_res, size_t & sz_iw, size_t & sz_w) const inherited
Definition at line 2252 of file function_internal.cpp.
References casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), and casadi::FunctionInternal::sz_w().
{
     sz_arg = this->sz_arg();
     sz_res = this->sz_res();
     sz_iw = this->sz_iw();
     sz_w = this->sz_w();
   }
MX casadi::FunctionInternal::tang_mx (int iind = 0, int oind = 0) virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 2571 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
Referenced by casadi::MX::tang().
{
     casadi_error("'tang_mx' not defined for " + type_name());
   }
SX casadi::FunctionInternal::tang_sx (int iind = 0, int oind = 0) virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 2584 of file function_internal.cpp.
References casadi::FunctionInternal::type_name().
{
     casadi_error("'tang_sx' not defined for " + type_name());
   }
Function casadi::FunctionInternal::tangent (int iind, int oind) inherited
Definition at line 472 of file function_internal.cpp.
References casadi::FunctionInternal::compilerplugin_, casadi::FunctionInternal::getTangent(), casadi::FunctionInternal::ischeme_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::n_out(), casadi::FunctionInternal::name_, casadi::FunctionInternal::oscheme_, and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::Function::tangent().
{
     // Assert scalar
     casadi_assert_message(sparsity_in(iind).is_scalar(),
                           "Only tangent of scalar input functions allowed. Use jacobian instead.");
     // Give it a suitable name
     stringstream ss;
     ss << "tangent_" << name_ << "_" << iind << "_" << oind;
     // Output names
     std::vector<std::string> ionames;
     ionames.reserve(1 + n_out());
     ionames.push_back("tangent");
     for (int i=0; i<n_out(); ++i) {
       ionames.push_back(oscheme_.at(i));
     }
     // Generate gradient function
     Dict opts = {{"input_scheme", ischeme_},
                  {"output_scheme", ionames},
                  {"jit", jit_},
                  {"compiler", compilerplugin_},
                  {"jit_options", jit_options_},
                  {"derivative_of", function()}};
     return getTangent(ss.str(), iind, oind, opts);
   }
std::string casadi::FunctionInternal::type_name () const virtual inherited
Reimplemented in casadi::SXFunction, casadi::MXFunction, casadi::External, and casadi::Jit.
Definition at line 2645 of file function_internal.cpp.
Referenced by casadi::FunctionInternal::eval(), casadi::FunctionInternal::eval_sx(), casadi::FunctionInternal::forward_mx(), casadi::FunctionInternal::forward_sx(), casadi::FunctionInternal::free_memory(), casadi::FunctionInternal::generate_dependencies(), casadi::FunctionInternal::generateBody(), casadi::FunctionInternal::get_forward(), casadi::FunctionInternal::get_reverse(), casadi::FunctionInternal::getAlgorithmSize(), casadi::FunctionInternal::getAtomicInput(), casadi::FunctionInternal::getAtomicInputReal(), casadi::FunctionInternal::getAtomicOperation(), casadi::FunctionInternal::getAtomicOutput(), casadi::FunctionInternal::getWorkSize(), casadi::FunctionInternal::grad_mx(), casadi::FunctionInternal::grad_sx(), casadi::FunctionInternal::hess_sx(), casadi::FunctionInternal::jac_mx(), casadi::FunctionInternal::jac_sx(), casadi::FunctionInternal::linsol_cholesky(), casadi::FunctionInternal::linsol_cholesky_sparsity(), casadi::FunctionInternal::linsol_eval_sx(), casadi::FunctionInternal::linsol_factorize(), casadi::FunctionInternal::linsol_forward(), casadi::FunctionInternal::linsol_reverse(), casadi::FunctionInternal::linsol_solve(), casadi::FunctionInternal::linsol_solveL(), casadi::FunctionInternal::linsol_spAdj(), casadi::FunctionInternal::linsol_spFwd(), casadi::FunctionInternal::linsol_spsolve(), casadi::FunctionInternal::n_nodes(), casadi::FunctionInternal::reverse_mx(), casadi::FunctionInternal::reverse_sx(), casadi::FunctionInternal::simple(), casadi::FunctionInternal::tang_mx(), and casadi::FunctionInternal::tang_sx().
{
     return typeid(*this).name();
   }
bool casadi::FunctionInternal::verbose () const inherited
Definition at line 573 of file function_internal.cpp.
References casadi::FunctionInternal::verbose_.
Referenced by casadi::KinsolInterface::eval(), casadi::CplexInterface::eval(), casadi::SXFunction::eval_sx(), casadi::SXFunction::evalAdj(), casadi::SXFunction::evalFwd(), casadi::KinsolInterface::func(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getPartition(), casadi::SXFunction::hess(), casadi::MXFunction::init(), casadi::SXFunction::init(), and casadi::CsparseInterface::linsol_factorize().
{
     return verbose_;
   }
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Function casadi::FunctionInternal::wrapMXFunction () inherited
Copied properties:
input/outputscheme ad_mode
The function is not initialized
Definition at line 522 of file function_internal.cpp.
References casadi::FunctionInternal::adWeight(), casadi::FunctionInternal::adWeightSp(), casadi::FunctionInternal::compilerplugin_, casadi::FunctionInternal::derivative_of_, casadi::FunctionInternal::ischeme_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::name_, and casadi::FunctionInternal::oscheme_.
Referenced by casadi::FunctionInternal::eval_mx(), casadi::FunctionInternal::getGradient(), casadi::FunctionInternal::getNumericJacobian(), and casadi::FunctionInternal::getTangent().
{
     // Construct options of the wrapping MXFunction
     Dict opts;
     // Propagate naming of inputs and outputs
     opts["input_scheme"] = ischeme_;
     opts["output_scheme"] = oscheme_;
     opts["output_scheme"] = oscheme_;
     // Propagate AD parameters
     opts["ad_weight"] = adWeight();
     opts["ad_weight_sp"] = adWeightSp();
     // Propagate information about AD
     opts["derivative_of"] = derivative_of_;
     // Propagate JIT
     opts["jit"] = jit_;
     opts["compiler"] = compilerplugin_;
     opts["jit_options"] = jit_options_;
     // Wrap the function
     vector<MX> arg = mx_in();
     vector<MX> res = function()(arg);
     return Function("wrap_" + name_, arg, res, opts);
   }
Member Data Documentation
double casadi::FunctionInternal::ad_weight_ inherited
Definition at line 806 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adWeight(), and casadi::FunctionInternal::FunctionInternal().
double casadi::FunctionInternal::ad_weight_sp_ inherited
Definition at line 806 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adWeightSp(), and casadi::FunctionInternal::FunctionInternal().
std::vector<Function> casadi::Nlpsol::all_functions_
Definition at line 90 of file nlpsol_impl.hpp.
Referenced by generate_dependencies(), init_memory(), and register_function().
int casadi::Nlpsol::callback_step_
Definition at line 75 of file nlpsol_impl.hpp.
Referenced by init(), casadi::IpoptUserClass::intermediate_callback(), and Nlpsol().
Compiler casadi::FunctionInternal::compiler_ inherited
Definition at line 799 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), and casadi::Scpgen::init().
std::string casadi::FunctionInternal::compilerplugin_ inherited
Definition at line 798 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::gradient(), casadi::FunctionInternal::init(), casadi::Scpgen::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::tangent(), and casadi::FunctionInternal::wrapMXFunction().
std::vector<WeakRef> casadi::FunctionInternal::derivative_adj_ inherited
Definition at line 777 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::set_reverse().
std::vector<WeakRef> casadi::FunctionInternal::derivative_fwd_ inherited
Definition at line 777 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), and casadi::FunctionInternal::set_forward().
Function casadi::FunctionInternal::derivative_of_ inherited
Definition at line 789 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::FunctionInternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::wrapMXFunction().
eval_t casadi::FunctionInternal::eval_ inherited
Definition at line 761 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_eval(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), and casadi::GenericExternal::GenericExternal().
bool casadi::Nlpsol::eval_errors_fatal_
Definition at line 78 of file nlpsol_impl.hpp.
Referenced by init(), and Nlpsol().
Function casadi::Nlpsol::fcallback_
Definition at line 72 of file nlpsol_impl.hpp.
Referenced by init(), casadi::IpoptInterface::intermediate_callback(), casadi::WorhpInterface::solve(), and casadi::Sqpmethod::solve().
WeakRef casadi::FunctionInternal::full_jacobian_ inherited
Definition at line 780 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::fullJacobian(), casadi::FunctionInternal::hasFullJacobian(), and casadi::Function::setFullJacobian().
bool casadi::FunctionInternal::gather_stats_ inherited
Definition at line 771 of file function_internal.hpp.
Referenced by casadi::CvodesInterface::advance(), casadi::IdasInterface::advance(), casadi::Newton::eval(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::IpoptInterface::intermediate_callback(), casadi::CvodesInterface::retreat(), casadi::IdasInterface::retreat(), and casadi::IpoptInterface::solve().
bool casadi::FunctionInternal::has_refcount_ inherited
Definition at line 774 of file function_internal.hpp.
Referenced by casadi::External::addDependency(), casadi::FunctionInternal::addDependency(), casadi::FunctionInternal::FunctionInternal(), casadi::Call::has_refcount(), casadi::External::init(), and casadi::MXFunction::init().
const std::string casadi::Nlpsol::infix_ = "nlpsol" static
Definition at line 197 of file nlpsol_impl.hpp.
bool casadi::FunctionInternal::inputs_check_ inherited
Definition at line 814 of file function_internal.hpp.
Referenced by checkInputs(), casadi::OoqpInterface::eval(), casadi::QpoasesInterface::eval(), casadi::CplexInterface::eval(), casadi::SqicInterface::evaluate(), casadi::FunctionInternal::FunctionInternal(), and casadi::FunctionInternal::init().
std::vector<std::string> casadi::FunctionInternal::ischeme_ inherited
Definition at line 752 of file function_internal.hpp.
Referenced by casadi::MXFunction::expand(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::fullJacobian(), casadi::MXFunction::generateBody(), casadi::FunctionInternal::gradient(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::tangent(), and casadi::FunctionInternal::wrapMXFunction().
std::vector<Sparsity> casadi::FunctionInternal::isp_ inherited
Definition at line 749 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::init().
bool casadi::Nlpsol::iteration_callback_ignore_errors_
Definition at line 84 of file nlpsol_impl.hpp.
Referenced by init(), casadi::IpoptInterface::intermediate_callback(), and Nlpsol().
SparseStorage<WeakRef> casadi::FunctionInternal::jac_ inherited
Definition at line 786 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::setJacobian().
SparseStorage<WeakRef> casadi::FunctionInternal::jac_compact_ inherited
Definition at line 786 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::setJacobian().
double casadi::FunctionInternal::jac_penalty_ inherited
Definition at line 803 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), and casadi::FunctionInternal::init().
SparseStorage<Sparsity> casadi::FunctionInternal::jac_sparsity_ inherited
Definition at line 783 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::init(), casadi::FunctionInternal::set_jac_sparsity(), and casadi::FunctionInternal::sparsity_jac().
SparseStorage<Sparsity> casadi::FunctionInternal::jac_sparsity_compact_ inherited
Definition at line 783 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::init(), casadi::FunctionInternal::set_jac_sparsity(), and casadi::FunctionInternal::sparsity_jac().
bool casadi::FunctionInternal::jit_ inherited
Definition at line 758 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::gradient(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::Jit::Jit(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::tangent(), and casadi::FunctionInternal::wrapMXFunction().
Dict casadi::FunctionInternal::jit_options_ inherited
Definition at line 800 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::gradient(), casadi::FunctionInternal::init(), casadi::Scpgen::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::tangent(), and casadi::FunctionInternal::wrapMXFunction().
bool casadi::FunctionInternal::monitor_inputs_ inherited
Definition at line 808 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), and casadi::FunctionInternal::init().
bool casadi::FunctionInternal::monitor_outputs_ inherited
Definition at line 808 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), and casadi::FunctionInternal::init().
std::set<std::string> casadi::FunctionInternal::monitors_ inherited
Definition at line 765 of file function_internal.hpp.
Referenced by casadi::Function::addMonitor(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::monitored().
std::string casadi::FunctionInternal::name_ inherited
Definition at line 795 of file function_internal.hpp.
Referenced by casadi::External::addDependency(), casadi::External::codegen_name(), casadi::MXFunction::eval(), casadi::SXFunction::eval(), casadi::GurobiInterface::eval(), casadi::MXFunction::expand(), casadi::External::External(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::GenericExternal::GenericExternal(), casadi::Integrator::get_forward(), casadi::External::get_n_forward(), casadi::External::get_n_in(), casadi::External::get_n_out(), casadi::External::get_n_reverse(), casadi::External::get_name_in(), casadi::External::get_name_out(), casadi::Integrator::get_reverse(), casadi::GenericExternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_out(), casadi::SXFunction::getFullJacobian(), casadi::FunctionInternal::gradient(), casadi::External::hasFullJacobian(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::GenericExternal::init(), casadi::SXFunction::init(), casadi::ImplicitFixedStepIntegrator::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::repr(), casadi::FunctionInternal::reverse(), casadi::SimplifiedExternal::SimplifiedExternal(), casadi::SnoptInterface::solve(), casadi::FunctionInternal::tangent(), and casadi::FunctionInternal::wrapMXFunction().
int casadi::Nlpsol::ng_
Definition at line 66 of file nlpsol_impl.hpp.
Referenced by checkInputs(), casadi::Scpgen::eval_vec(), casadi::IpoptUserClass::finalize_metadata(), casadi::IpoptInterface::finalize_solution(), casadi::IpoptUserClass::get_bounds_info(), casadi::IpoptInterface::get_bounds_info(), casadi::IpoptInterface::get_nlp_info(), casadi::IpoptUserClass::get_starting_point(), casadi::IpoptInterface::get_starting_point(), casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), init(), casadi::IpoptInterface::init(), casadi::IpoptInterface::init_memory(), casadi::IpoptInterface::intermediate_callback(), casadi::IpoptUserClass::IpoptUserClass(), casadi::Scpgen::line_search(), casadi::Scpgen::primalInfeasibility(), casadi::KnitroInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::WorhpInterface::set_work(), casadi::Sqpmethod::set_work(), casadi::Scpgen::set_work(), casadi::IpoptInterface::set_work(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Scpgen::solve(), casadi::IpoptInterface::solve(), and casadi::Scpgen::solve_qp().
int casadi::Nlpsol::np_
Definition at line 69 of file nlpsol_impl.hpp.
Referenced by casadi::Scpgen::init(), and init().
int casadi::Nlpsol::nx_
Definition at line 63 of file nlpsol_impl.hpp.
Referenced by checkInputs(), casadi::Scpgen::dualInfeasibility(), casadi::Scpgen::eval_mat(), casadi::Scpgen::eval_vec(), casadi::IpoptUserClass::finalize_metadata(), casadi::IpoptInterface::finalize_solution(), casadi::IpoptUserClass::get_bounds_info(), casadi::IpoptInterface::get_bounds_info(), casadi::IpoptInterface::get_nlp_info(), casadi::IpoptUserClass::get_starting_point(), casadi::IpoptInterface::get_starting_point(), casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::WorhpInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), init(), casadi::IpoptInterface::init(), casadi::IpoptInterface::init_memory(), casadi::IpoptInterface::intermediate_callback(), casadi::IpoptUserClass::IpoptUserClass(), casadi::Scpgen::line_search(), casadi::Scpgen::primalInfeasibility(), casadi::Scpgen::regularize(), casadi::KnitroInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::WorhpInterface::set_work(), casadi::Sqpmethod::set_work(), casadi::Scpgen::set_work(), casadi::IpoptInterface::set_work(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Scpgen::solve(), casadi::IpoptInterface::solve(), casadi::Scpgen::solve_qp(), and casadi::SnoptInterface::userfun().
Options casadi::Nlpsol::options_ static
Definition at line 123 of file nlpsol_impl.hpp.
std::vector<std::string> casadi::FunctionInternal::oscheme_ inherited
Definition at line 752 of file function_internal.hpp.
Referenced by casadi::MXFunction::expand(), casadi::FunctionInternal::forward(), casadi::MXFunction::generateBody(), casadi::FunctionInternal::gradient(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::tangent(), and casadi::FunctionInternal::wrapMXFunction().
std::vector<Sparsity> casadi::FunctionInternal::osp_ inherited
Definition at line 749 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::init().
bool casadi::Nlpsol::print_time_
Definition at line 87 of file nlpsol_impl.hpp.
Referenced by init(), Nlpsol(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), and casadi::IpoptInterface::solve().
bool casadi::FunctionInternal::regularity_check_ inherited
Definition at line 811 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), and casadi::IdasInterface::res().
simple_t casadi::FunctionInternal::simple_ inherited
Definition at line 762 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::_eval(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), and casadi::SimplifiedExternal::SimplifiedExternal().
std::map< std::string, Nlpsol::Plugin > casadi::Nlpsol::solvers_ static
Definition at line 194 of file nlpsol_impl.hpp.
Dict casadi::FunctionInternal::stats_ inherited
Definition at line 768 of file function_internal.hpp.
void* casadi::FunctionInternal::user_data_ inherited
Definition at line 792 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), and casadi::FunctionInternal::init().
bool casadi::FunctionInternal::verbose_ inherited
Definition at line 755 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::SXFunction::hess(), casadi::FunctionInternal::init(), casadi::Scpgen::init(), casadi::IpoptInterface::init_memory(), casadi::FunctionInternal::jacobian(), casadi::Scpgen::solve(), and casadi::FunctionInternal::verbose().
bool casadi::Nlpsol::warn_initial_bounds_
Definition at line 81 of file nlpsol_impl.hpp.
Referenced by checkInputs(), init(), and Nlpsol().
The documentation for this class was generated from the following files:
nlpsol_impl.hpp
nlpsol.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge