CasADi: casadi::Polynomial Class Reference
casadi::Polynomial Class Reference
Helper class for differentiating and integrating polynomials.
#include <polynomial.hpp>
Detailed Description
Author
Joel Andersson
Date
2014
Definition at line 37 of file polynomial.hpp.
Public Types
typedef double real_t
Floating point type.
Public Member Functions
Polynomial (real_t scalar=1)
Construct a constant polynomial.
Polynomial (real_t p0, real_t p1)
Construct a linear polynomial.
Polynomial (real_t p0, real_t p1, real_t p2)
Construct a quadratic polynomial.
Polynomial (real_t p0, real_t p1, real_t p2, real_t p3)
Construct a cubic polynomial.
template<typename T >
Polynomial (const std::vector< T > &coeff)
Construct from a vector of polynomial coefficients.
template<typename T >
T operator() (const T &x) const
Evaluate numerically.
int degree () const
Degree of the polynomial.
real_t scalar () const
Get scalar value (error if degree()!=0)
Polynomial derivative () const
Create a new polynomial for the derivative.
Polynomial anti_derivative () const
Create a new polynomial for the anti-derivative (primitive function)
void trim ()
Remove excess zeros.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
Polynomial operator+ (const Polynomial &b) const
Polynomial & operator+= (const Polynomial &b)
Polynomial operator- (const Polynomial &b) const
Polynomial & operator-= (const Polynomial &b)
Polynomial operator* (const Polynomial &b) const
Polynomial & operator*= (const Polynomial &b)
Polynomial operator/ (real_t b) const
Polynomial & operator/= (real_t b)
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
Protected Attributes
std::vector< real_t > p_
Member Typedef Documentation
typedef double casadi::Polynomial::real_t
Definition at line 40 of file polynomial.hpp.
Constructor & Destructor Documentation
casadi::Polynomial::Polynomial (real_t scalar = 1)
Definition at line 33 of file polynomial.cpp.
Referenced by anti_derivative(), derivative(), and operator*().
                                       : p_(1, scalar) {
   }
casadi::Polynomial::Polynomial (real_t p0, real_t p1)
Definition at line 36 of file polynomial.cpp.
References p_.
{
     p_.resize(2);
     p_[0] = p0;
     p_[1] = p1;
   }
casadi::Polynomial::Polynomial (real_t p0, real_t p1, real_t p2)
Definition at line 42 of file polynomial.cpp.
References p_.
{
     p_.resize(3);
     p_[0] = p0;
     p_[1] = p1;
     p_[2] = p2;
   }
casadi::Polynomial::Polynomial (real_t p0, real_t p1, real_t p2, real_t p3)
Definition at line 49 of file polynomial.cpp.
References p_.
{
     p_.resize(2);
     p_[0] = p0;
     p_[1] = p1;
     p_[2] = p2;
     p_[3] = p3;
   }
template<typename T > casadi::Polynomial::Polynomial (const std::vector< T > & coeff) inline
Definition at line 56 of file polynomial.hpp.
 : p_(coeff.begin(), coeff.end()) {}
Member Function Documentation
Polynomial casadi::Polynomial::anti_derivative () const
Definition at line 152 of file polynomial.cpp.
References p_, and Polynomial().
Referenced by casadi::CollocationIntegrator::setupFG().
{
     vector<real_t> ret_p(p_.size()+1);
     ret_p[0] = 0;
     for (int k=0; k<p_.size(); ++k) {
       ret_p[k+1] = p_[k]/(k+1);
     }
     return Polynomial(ret_p);
   }
int casadi::Polynomial::degree () const
Definition at line 76 of file polynomial.cpp.
References p_.
Referenced by scalar().
{
     return p_.size()-1;
   }
Polynomial casadi::Polynomial::derivative () const
Definition at line 144 of file polynomial.cpp.
References p_, and Polynomial().
Referenced by casadi::CollocationIntegrator::setupFG().
{
     vector<real_t> ret_p(p_.size()-1);
     for (int k=1; k<p_.size(); ++k) {
       ret_p[k-1] = k*p_[k];
     }
     return Polynomial(ret_p);
   }
std::string casadi::PrintableObject< Polynomial >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< Polynomial >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
template<typename T > T casadi::Polynomial::operator() (const T & x) const inline
Definition at line 60 of file polynomial.hpp.
{
       auto it = p_.rbegin();
       T ret = *it++;
       while (it!=p_.rend()) {
         ret *= x;
         ret += *it++;
       }
       return ret;
     }
Polynomial casadi::Polynomial::operator* (const Polynomial & b) const
Definition at line 85 of file polynomial.cpp.
References p_, and Polynomial().
{
     vector<real_t> p_ret(p_.size() + a.p_.size() - 1, 0);
     for (int d=0; d<p_.size(); ++d) {
       for (int d_a=0; d_a<a.p_.size(); ++d_a) {
         p_ret[d+d_a] += p_[d] * a.p_[d_a];
       }
     }
     return Polynomial(p_ret);
   }
Polynomial & casadi::Polynomial::operator*= (const Polynomial & b)
Definition at line 95 of file polynomial.cpp.
{
     return *this = *this*d;
   }
Polynomial casadi::Polynomial::operator+ (const Polynomial & b) const
Definition at line 112 of file polynomial.cpp.
{
     Polynomial ret = *this;
     return ret+=b;
   }
Polynomial & casadi::Polynomial::operator+= (const Polynomial & b)
Definition at line 117 of file polynomial.cpp.
References p_, and trim().
{
     p_.resize(max(p_.size(), b.p_.size()), 0);
     transform(b.p_.begin(), b.p_.end(), p_.begin(), p_.begin(), std::plus<real_t>());
     trim();
     return *this;
   }
Polynomial casadi::Polynomial::operator- (const Polynomial & b) const
Definition at line 124 of file polynomial.cpp.
{
     Polynomial ret = *this;
     return ret-=b;
   }
Polynomial & casadi::Polynomial::operator-= (const Polynomial & b)
Definition at line 129 of file polynomial.cpp.
References p_, and trim().
{
     p_.resize(max(p_.size(), b.p_.size()), 0);
     transform(p_.begin(), p_.begin()+b.p_.size(), b.p_.begin(), p_.begin(), std::minus<real_t>());
     trim();
     return *this;
   }
Polynomial casadi::Polynomial::operator/ (real_t b) const
Definition at line 99 of file polynomial.cpp.
{
     Polynomial ret = *this;
     ret/=d;
     return ret;
   }
Polynomial & casadi::Polynomial::operator/= (real_t b)
Definition at line 105 of file polynomial.cpp.
References p_.
{
     for (vector<real_t>::iterator it=p_.begin(); it!=p_.end(); ++it) {
       *it /= d;
     }
     return *this;
   }
void casadi::Polynomial::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 62 of file polynomial.cpp.
References p_.
{
     for (int d=0; d<p_.size(); ++d) {
       if (d==0) {
         stream << p_[d];
       } else if (d==1) {
         stream << " + " << p_[d] << "*x";
       } else {
         stream << " + " << p_[d] << "*x^" << d;
       }
     }
     stream << endl;
     if (trailing_newline) stream << std::endl;
   }
void casadi::Polynomial::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 57 of file polynomial.cpp.
References p_, and casadi::userOut().
{
     userOut() << "poly(" << p_ << ")" << endl;
     if (trailing_newline) stream << std::endl;
   }
Polynomial::real_t casadi::Polynomial::scalar () const
Definition at line 80 of file polynomial.cpp.
References degree(), and p_.
{
     casadi_assert(degree()==0);
     return p_.front();
   }
void casadi::Polynomial::trim ()
Definition at line 136 of file polynomial.cpp.
References p_.
Referenced by operator+=(), and operator-=().
{
     // Remove trailing zeros
     size_t new_size = p_.size();
     vector<real_t>::const_reverse_iterator it=p_.rbegin();
     while (it!=p_.rend() && 0==*it++) new_size--;
     p_.resize(new_size);
   }
Member Data Documentation
std::vector<real_t> casadi::Polynomial::p_ protected
Definition at line 117 of file polynomial.hpp.
Referenced by anti_derivative(), degree(), derivative(), operator*(), operator+=(), operator-=(), operator/=(), Polynomial(), print(), repr(), scalar(), and trim().
The documentation for this class was generated from the following files:
polynomial.hpp
polynomial.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge