CasADi: casadi::casadi_math< T > Struct Template Reference
casadi::casadi_math< T > Struct Template Reference
Easy access to all the functions for a particular type.
#include <calculus.hpp>
Detailed Description
template<typename T>
struct casadi::casadi_math< T >
Definition at line 1056 of file calculus.hpp.
Static Public Member Functions
static void fun (unsigned char op, const T &x, const T &y, T &f)
Evaluate a built in function (scalar-scalar)
static void fun (unsigned char op, const T *x, const T *y, T *f, int n)
Evaluate a built in function (vector-vector)
static void fun (unsigned char op, const T *x, const T &y, T *f, int n)
Evaluate a built in function (vector-scalar)
static void fun (unsigned char op, const T &x, const T *y, T *f, int n)
Evaluate a built in function (scalar-vector)
static void der (unsigned char op, const T &x, const T &y, const T &f, T *d)
Evaluate a built in derivative function.
static void derF (unsigned char op, const T &x, const T &y, T &f, T *d)
Evaluate the function and the derivative function.
static int ndeps (unsigned char op)
Number of dependencies.
static void print (unsigned char op, std::ostream &stream, const std::string &x, const std::string &y)
Print.
static const char * name (unsigned char op)
static void printPre (unsigned char op, std::ostream &stream)
static void printSep (unsigned char op, std::ostream &stream)
static void printPost (unsigned char op, std::ostream &stream)
Member Function Documentation
template<typename T > void casadi::casadi_math< T >::der (unsigned char op, const T & x, const T & y, const T & f, T * d) inline static
Definition at line 1251 of file calculus.hpp.
Referenced by casadi::casadi_math< int >::der(), casadi::UnaryMX::evalAdj(), casadi::BinaryMX< ScX, ScY >::evalAdj(), casadi::UnaryMX::evalFwd(), and casadi::BinaryMX< ScX, ScY >::evalFwd().
{
     // NOTE: We define the implementation in a preprocessor macro to be able to force inlining,
     // and to allow extensions in the VM
 #define CASADI_MATH_DER_BUILTIN(X, Y, F, D)                             \
     case OP_ASSIGN:    BinaryOperation<OP_ASSIGN>::der(X, Y, F, D);     break; \
   case OP_ADD:       BinaryOperation<OP_ADD>::der(X, Y, F, D);        break; \
   case OP_SUB:       BinaryOperation<OP_SUB>::der(X, Y, F, D);        break; \
   case OP_MUL:       BinaryOperation<OP_MUL>::der(X, Y, F, D);        break; \
   case OP_DIV:       BinaryOperation<OP_DIV>::der(X, Y, F, D);        break; \
   case OP_NEG:       BinaryOperation<OP_NEG>::der(X, Y, F, D);        break; \
   case OP_EXP:       BinaryOperation<OP_EXP>::der(X, Y, F, D);        break; \
   case OP_LOG:       BinaryOperation<OP_LOG>::der(X, Y, F, D);        break; \
   case OP_POW:       BinaryOperation<OP_POW>::der(X, Y, F, D);        break; \
   case OP_CONSTPOW:  BinaryOperation<OP_CONSTPOW>::der(X, Y, F, D);   break; \
   case OP_SQRT:      BinaryOperation<OP_SQRT>::der(X, Y, F, D);       break; \
   case OP_SQ:        BinaryOperation<OP_SQ>::der(X, Y, F, D);         break; \
   case OP_TWICE:     BinaryOperation<OP_TWICE>::der(X, Y, F, D);      break; \
   case OP_SIN:       BinaryOperation<OP_SIN>::der(X, Y, F, D);        break; \
   case OP_COS:       BinaryOperation<OP_COS>::der(X, Y, F, D);        break; \
   case OP_TAN:       BinaryOperation<OP_TAN>::der(X, Y, F, D);        break; \
   case OP_ASIN:      BinaryOperation<OP_ASIN>::der(X, Y, F, D);       break; \
   case OP_ACOS:      BinaryOperation<OP_ACOS>::der(X, Y, F, D);       break; \
   case OP_ATAN:      BinaryOperation<OP_ATAN>::der(X, Y, F, D);       break; \
   case OP_LT:        BinaryOperation<OP_LT>::der(X, Y, F, D);         break; \
   case OP_LE:        BinaryOperation<OP_LE>::der(X, Y, F, D);         break; \
   case OP_EQ:        BinaryOperation<OP_EQ>::der(X, Y, F, D);         break; \
   case OP_NE:        BinaryOperation<OP_NE>::der(X, Y, F, D);         break; \
   case OP_NOT:       BinaryOperation<OP_NOT>::der(X, Y, F, D);        break; \
   case OP_AND:       BinaryOperation<OP_AND>::der(X, Y, F, D);        break; \
   case OP_OR:        BinaryOperation<OP_OR>::der(X, Y, F, D);         break; \
   case OP_IF_ELSE_ZERO: BinaryOperation<OP_IF_ELSE_ZERO>::der(X, Y, F, D);         break; \
   case OP_FLOOR:     BinaryOperation<OP_FLOOR>::der(X, Y, F, D);      break; \
   case OP_CEIL:      BinaryOperation<OP_CEIL>::der(X, Y, F, D);       break; \
   case OP_FMOD:      BinaryOperation<OP_FMOD>::der(X, Y, F, D);       break; \
   case OP_FABS:      BinaryOperation<OP_FABS>::der(X, Y, F, D);       break; \
   case OP_SIGN:      BinaryOperation<OP_SIGN>::der(X, Y, F, D);       break; \
   case OP_COPYSIGN:  BinaryOperation<OP_COPYSIGN>::der(X, Y, F, D);   break; \
   case OP_ERF:       BinaryOperation<OP_ERF>::der(X, Y, F, D);        break; \
   case OP_FMIN:      BinaryOperation<OP_FMIN>::der(X, Y, F, D);       break; \
   case OP_FMAX:      BinaryOperation<OP_FMAX>::der(X, Y, F, D);       break; \
   case OP_INV:       BinaryOperation<OP_INV>::der(X, Y, F, D);        break; \
   case OP_SINH:      BinaryOperation<OP_SINH>::der(X, Y, F, D);       break; \
   case OP_COSH:      BinaryOperation<OP_COSH>::der(X, Y, F, D);       break; \
   case OP_TANH:      BinaryOperation<OP_TANH>::der(X, Y, F, D);       break; \
   case OP_ASINH:     BinaryOperation<OP_ASINH>::der(X, Y, F, D);      break; \
   case OP_ACOSH:     BinaryOperation<OP_ACOSH>::der(X, Y, F, D);      break; \
   case OP_ATANH:     BinaryOperation<OP_ATANH>::der(X, Y, F, D);      break; \
   case OP_ATAN2:     BinaryOperation<OP_ATAN2>::der(X, Y, F, D);      break; \
   case OP_ERFINV:    BinaryOperation<OP_ERFINV>::der(X, Y, F, D);     break; \
   case OP_LIFT:      BinaryOperation<OP_LIFT>::der(X, Y, F, D);       break; \
   case OP_PRINTME:   BinaryOperation<OP_PRINTME>::der(X, Y, F, D);    break;
     switch (op) {
     CASADI_MATH_DER_BUILTIN(x, y, f, d)
       }
   }
template<typename T > void casadi::casadi_math< T >::derF (unsigned char op, const T & x, const T & y, T & f, T * d) inline static
Definition at line 1310 of file calculus.hpp.
Referenced by casadi::casadi_math< int >::derF().
{
     // NOTE: We define the implementation in a preprocessor macro to be able to force inlining,
     // and to allow extensions in the VM
 #define CASADI_MATH_DERF_BUILTIN(X, Y, F, D)                            \
     case OP_ASSIGN:    DerBinaryOpertion<OP_ASSIGN>::derf(X, Y, F, D);        break; \
   case OP_ADD:       DerBinaryOpertion<OP_ADD>::derf(X, Y, F, D);        break; \
   case OP_SUB:       DerBinaryOpertion<OP_SUB>::derf(X, Y, F, D);        break; \
   case OP_MUL:       DerBinaryOpertion<OP_MUL>::derf(X, Y, F, D);        break; \
   case OP_DIV:       DerBinaryOpertion<OP_DIV>::derf(X, Y, F, D);        break; \
   case OP_NEG:       DerBinaryOpertion<OP_NEG>::derf(X, Y, F, D);        break; \
   case OP_EXP:       DerBinaryOpertion<OP_EXP>::derf(X, Y, F, D);        break; \
   case OP_LOG:       DerBinaryOpertion<OP_LOG>::derf(X, Y, F, D);        break; \
   case OP_POW:       DerBinaryOpertion<OP_POW>::derf(X, Y, F, D);        break; \
   case OP_CONSTPOW:  DerBinaryOpertion<OP_CONSTPOW>::derf(X, Y, F, D);   break; \
   case OP_SQRT:      DerBinaryOpertion<OP_SQRT>::derf(X, Y, F, D);       break; \
   case OP_SQ:        DerBinaryOpertion<OP_SQ>::derf(X, Y, F, D);         break; \
   case OP_TWICE:     DerBinaryOpertion<OP_TWICE>::derf(X, Y, F, D);      break; \
   case OP_SIN:       DerBinaryOpertion<OP_SIN>::derf(X, Y, F, D);        break; \
   case OP_COS:       DerBinaryOpertion<OP_COS>::derf(X, Y, F, D);        break; \
   case OP_TAN:       DerBinaryOpertion<OP_TAN>::derf(X, Y, F, D);        break; \
   case OP_ASIN:      DerBinaryOpertion<OP_ASIN>::derf(X, Y, F, D);       break; \
   case OP_ACOS:      DerBinaryOpertion<OP_ACOS>::derf(X, Y, F, D);       break; \
   case OP_ATAN:      DerBinaryOpertion<OP_ATAN>::derf(X, Y, F, D);       break; \
   case OP_LT:        DerBinaryOpertion<OP_LT>::derf(X, Y, F, D);         break; \
   case OP_LE:        DerBinaryOpertion<OP_LE>::derf(X, Y, F, D);         break; \
   case OP_EQ:        DerBinaryOpertion<OP_EQ>::derf(X, Y, F, D);         break; \
   case OP_NE:        DerBinaryOpertion<OP_NE>::derf(X, Y, F, D);         break; \
   case OP_NOT:       DerBinaryOpertion<OP_NOT>::derf(X, Y, F, D);        break; \
   case OP_AND:       DerBinaryOpertion<OP_AND>::derf(X, Y, F, D);        break; \
   case OP_OR:        DerBinaryOpertion<OP_OR>::derf(X, Y, F, D);         break; \
   case OP_IF_ELSE_ZERO: DerBinaryOpertion<OP_IF_ELSE_ZERO>::derf(X, Y, F, D);         break; \
   case OP_FLOOR:     DerBinaryOpertion<OP_FLOOR>::derf(X, Y, F, D);      break; \
   case OP_CEIL:      DerBinaryOpertion<OP_CEIL>::derf(X, Y, F, D);       break; \
   case OP_FMOD:      DerBinaryOpertion<OP_FMOD>::derf(X, Y, F, D);       break; \
   case OP_FABS:      DerBinaryOpertion<OP_FABS>::derf(X, Y, F, D);       break; \
   case OP_SIGN:      DerBinaryOpertion<OP_SIGN>::derf(X, Y, F, D);       break; \
   case OP_COPYSIGN:  DerBinaryOpertion<OP_COPYSIGN>::derf(X, Y, F, D);   break; \
   case OP_ERF:       DerBinaryOpertion<OP_ERF>::derf(X, Y, F, D);        break; \
   case OP_FMIN:      DerBinaryOpertion<OP_FMIN>::derf(X, Y, F, D);       break; \
   case OP_FMAX:      DerBinaryOpertion<OP_FMAX>::derf(X, Y, F, D);       break; \
   case OP_INV:       DerBinaryOpertion<OP_INV>::derf(X, Y, F, D);        break; \
   case OP_SINH:      DerBinaryOpertion<OP_SINH>::derf(X, Y, F, D);       break; \
   case OP_COSH:      DerBinaryOpertion<OP_COSH>::derf(X, Y, F, D);       break; \
   case OP_TANH:      DerBinaryOpertion<OP_TANH>::derf(X, Y, F, D);       break; \
   case OP_ASINH:     DerBinaryOpertion<OP_ASINH>::derf(X, Y, F, D);      break; \
   case OP_ACOSH:     DerBinaryOpertion<OP_ACOSH>::derf(X, Y, F, D);      break; \
   case OP_ATANH:     DerBinaryOpertion<OP_ATANH>::derf(X, Y, F, D);      break; \
   case OP_ATAN2:     DerBinaryOpertion<OP_ATAN2>::derf(X, Y, F, D);      break; \
   case OP_ERFINV:    DerBinaryOpertion<OP_ERFINV>::derf(X, Y, F, D);     break; \
   case OP_LIFT:      DerBinaryOpertion<OP_LIFT>::derf(X, Y, F, D);       break; \
   case OP_PRINTME:   DerBinaryOpertion<OP_PRINTME>::derf(X, Y, F, D);    break;
     switch (op) {
       CASADI_MATH_DERF_BUILTIN(x, y, f, d)
         }
   }
template<typename T > void casadi::casadi_math< T >::fun (unsigned char op, const T & x, const T & y, T & f) inline static
Definition at line 1169 of file calculus.hpp.
Referenced by casadi::UnarySX::create(), casadi::BinarySX::create(), casadi::UnaryMX::eval(), casadi::UnaryMX::eval_mx(), casadi::BinaryMX< ScX, ScY >::eval_mx(), casadi::UnaryMX::eval_sx(), casadi::BinaryMX< ScX, ScY >::evalGen(), casadi::casadi_math< int >::fun(), casadi::Constant< Value >::getBinary(), casadi::Constant< Value >::getUnary(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::Matrix< Scalar >::matrix_scalar(), casadi::Matrix< Scalar >::scalar_matrix(), and casadi::Matrix< Scalar >::unary().
{
     // NOTE: We define the implementation in a preprocessor macro to be able to force inlining,
     //  and to allow extensions in the VM
 #define CASADI_MATH_FUN_BUILTIN_GEN(CNAME, X, Y, F, N)                  \
     case OP_ASSIGN:    CNAME<OP_ASSIGN>::fcn(X, Y, F, N);        break; \
   case OP_ADD:       CNAME<OP_ADD>::fcn(X, Y, F, N);           break;   \
   case OP_SUB:       CNAME<OP_SUB>::fcn(X, Y, F, N);           break;   \
   case OP_MUL:       CNAME<OP_MUL>::fcn(X, Y, F, N);           break;   \
   case OP_DIV:       CNAME<OP_DIV>::fcn(X, Y, F, N);           break;   \
   case OP_NEG:       CNAME<OP_NEG>::fcn(X, Y, F, N);           break;   \
   case OP_EXP:       CNAME<OP_EXP>::fcn(X, Y, F, N);           break;   \
   case OP_LOG:       CNAME<OP_LOG>::fcn(X, Y, F, N);           break;   \
   case OP_POW:       CNAME<OP_POW>::fcn(X, Y, F, N);           break;   \
   case OP_CONSTPOW:  CNAME<OP_CONSTPOW>::fcn(X, Y, F, N);      break;   \
   case OP_SQRT:      CNAME<OP_SQRT>::fcn(X, Y, F, N);          break;   \
   case OP_SQ:        CNAME<OP_SQ>::fcn(X, Y, F, N);            break;   \
   case OP_TWICE:     CNAME<OP_TWICE>::fcn(X, Y, F, N);         break;   \
   case OP_SIN:       CNAME<OP_SIN>::fcn(X, Y, F, N);           break;   \
   case OP_COS:       CNAME<OP_COS>::fcn(X, Y, F, N);           break;   \
   case OP_TAN:       CNAME<OP_TAN>::fcn(X, Y, F, N);           break;   \
   case OP_ASIN:      CNAME<OP_ASIN>::fcn(X, Y, F, N);          break;   \
   case OP_ACOS:      CNAME<OP_ACOS>::fcn(X, Y, F, N);          break;   \
   case OP_ATAN:      CNAME<OP_ATAN>::fcn(X, Y, F, N);          break;   \
   case OP_LT:        CNAME<OP_LT>::fcn(X, Y, F, N);            break;   \
   case OP_LE:        CNAME<OP_LE>::fcn(X, Y, F, N);            break;   \
   case OP_EQ:        CNAME<OP_EQ>::fcn(X, Y, F, N);            break;   \
   case OP_NE:        CNAME<OP_NE>::fcn(X, Y, F, N);            break;   \
   case OP_NOT:       CNAME<OP_NOT>::fcn(X, Y, F, N);           break;   \
   case OP_AND:       CNAME<OP_AND>::fcn(X, Y, F, N);           break;   \
   case OP_OR:        CNAME<OP_OR>::fcn(X, Y, F, N);            break;   \
   case OP_IF_ELSE_ZERO: CNAME<OP_IF_ELSE_ZERO>::fcn(X, Y, F, N); break; \
   case OP_FLOOR:     CNAME<OP_FLOOR>::fcn(X, Y, F, N);         break;   \
   case OP_CEIL:      CNAME<OP_CEIL>::fcn(X, Y, F, N);          break;   \
   case OP_FMOD:      CNAME<OP_FMOD>::fcn(X, Y, F, N);          break;   \
   case OP_FABS:      CNAME<OP_FABS>::fcn(X, Y, F, N);          break;   \
   case OP_SIGN:      CNAME<OP_SIGN>::fcn(X, Y, F, N);          break;   \
   case OP_COPYSIGN:  CNAME<OP_COPYSIGN>::fcn(X, Y, F, N);      break;   \
   case OP_ERF:       CNAME<OP_ERF>::fcn(X, Y, F, N);           break;   \
   case OP_FMIN:      CNAME<OP_FMIN>::fcn(X, Y, F, N);          break;   \
   case OP_FMAX:      CNAME<OP_FMAX>::fcn(X, Y, F, N);          break;   \
   case OP_INV:       CNAME<OP_INV>::fcn(X, Y, F, N);           break;   \
   case OP_SINH:      CNAME<OP_SINH>::fcn(X, Y, F, N);          break;   \
   case OP_COSH:      CNAME<OP_COSH>::fcn(X, Y, F, N);          break;   \
   case OP_TANH:      CNAME<OP_TANH>::fcn(X, Y, F, N);          break;   \
   case OP_ASINH:     CNAME<OP_ASINH>::fcn(X, Y, F, N);         break;   \
   case OP_ACOSH:     CNAME<OP_ACOSH>::fcn(X, Y, F, N);         break;   \
   case OP_ATANH:     CNAME<OP_ATANH>::fcn(X, Y, F, N);         break;   \
   case OP_ATAN2:     CNAME<OP_ATAN2>::fcn(X, Y, F, N);         break;   \
   case OP_ERFINV:    CNAME<OP_ERFINV>::fcn(X, Y, F, N);        break;   \
   case OP_LIFT:      CNAME<OP_LIFT>::fcn(X, Y, F, N);          break;   \
   case OP_PRINTME:   CNAME<OP_PRINTME>::fcn(X, Y, F, N);       break;
 #define CASADI_MATH_FUN_BUILTIN(X, Y, F) CASADI_MATH_FUN_BUILTIN_GEN(BinaryOperationSS, X, Y, F, 1)
     switch (op) {
     CASADI_MATH_FUN_BUILTIN(x, y, f)
       }
   }
template<typename T > void casadi::casadi_math< T >::fun (unsigned char op, const T * x, const T * y, T * f, int n) inline static
Definition at line 1229 of file calculus.hpp.
{
     switch (op) {
       CASADI_MATH_FUN_BUILTIN_GEN(BinaryOperationVV, x, y, f, n)
         }
   }
template<typename T > void casadi::casadi_math< T >::fun (unsigned char op, const T * x, const T & y, T * f, int n) inline static
Definition at line 1236 of file calculus.hpp.
{
     switch (op) {
       CASADI_MATH_FUN_BUILTIN_GEN(BinaryOperationVS, x, y, f, n)
         }
   }
template<typename T > void casadi::casadi_math< T >::fun (unsigned char op, const T & x, const T * y, T * f, int n) inline static
Definition at line 1243 of file calculus.hpp.
{
     switch (op) {
       CASADI_MATH_FUN_BUILTIN_GEN(BinaryOperationSV, x, y, f, n)
         }
   }
template<typename T > const char * casadi::casadi_math< T >::name (unsigned char op) inline static
Definition at line 1422 of file calculus.hpp.
References casadi::OP_ACOS, casadi::OP_ACOSH, casadi::OP_ADD, casadi::OP_ADDNONZEROS, casadi::OP_AND, casadi::OP_ASIN, casadi::OP_ASINH, casadi::OP_ASSERTION, casadi::OP_ASSIGN, casadi::OP_ATAN, casadi::OP_ATAN2, casadi::OP_ATANH, casadi::OP_CALL, casadi::OP_CEIL, casadi::OP_CONST, casadi::OP_CONSTPOW, casadi::OP_COPYSIGN, casadi::OP_COS, casadi::OP_COSH, casadi::OP_DETERMINANT, casadi::OP_DIAGCAT, casadi::OP_DIAGSPLIT, casadi::OP_DIV, casadi::OP_DOT, casadi::OP_EQ, casadi::OP_ERF, casadi::OP_ERFINV, casadi::OP_EXP, casadi::OP_FABS, casadi::OP_FLOOR, casadi::OP_FMAX, casadi::OP_FMIN, casadi::OP_FMOD, casadi::OP_GETNONZEROS, casadi::OP_HORZCAT, casadi::OP_HORZSPLIT, casadi::OP_IF_ELSE_ZERO, casadi::OP_INPUT, casadi::OP_INV, casadi::OP_INVERSE, casadi::OP_LE, casadi::OP_LIFT, casadi::OP_LOG, casadi::OP_LT, casadi::OP_MTIMES, casadi::OP_MUL, casadi::OP_NE, casadi::OP_NEG, casadi::OP_NORM1, casadi::OP_NORM2, casadi::OP_NORMF, casadi::OP_NORMINF, casadi::OP_NOT, casadi::OP_OR, casadi::OP_OUTPUT, casadi::OP_PARAMETER, casadi::OP_POW, casadi::OP_PRINTME, casadi::OP_PROJECT, casadi::OP_RESHAPE, casadi::OP_SETNONZEROS, casadi::OP_SIGN, casadi::OP_SIN, casadi::OP_SINH, casadi::OP_SOLVE, casadi::OP_SQ, casadi::OP_SQRT, casadi::OP_SUB, casadi::OP_SUBASSIGN, casadi::OP_SUBREF, casadi::OP_TAN, casadi::OP_TANH, casadi::OP_TRANSPOSE, casadi::OP_TWICE, casadi::OP_VERTCAT, and casadi::OP_VERTSPLIT.
Referenced by casadi::casadi_math< int >::name().
{
       switch (op) {
       case OP_ASSIGN:         return "assign";
       case OP_ADD:            return "add";
       case OP_SUB:            return "sub";
       case OP_MUL:            return "mul";
       case OP_DIV:            return "div";
       case OP_NEG:            return "neg";
       case OP_EXP:            return "exp";
       case OP_LOG:            return "log";
       case OP_CONSTPOW:
       case OP_POW:            return "pow";
       case OP_SQRT:           return "sqrt";
       case OP_SQ:             return "sq";
       case OP_TWICE:          return "twice";
       case OP_SIN:            return "sin";
       case OP_COS:            return "cos";
       case OP_TAN:            return "tan";
       case OP_ASIN:           return "asin";
       case OP_ACOS:           return "acos";
       case OP_ATAN:           return "atan";
       case OP_LT:             return "lt";
       case OP_LE:             return "le";
       case OP_EQ:             return "eq";
       case OP_NE:             return "ne";
       case OP_NOT:            return "not";
       case OP_AND:            return "and";
       case OP_OR:             return "or";
       case OP_FLOOR:          return "floor";
       case OP_CEIL:           return "ceil";
       case OP_FMOD:           return "fmod";
       case OP_FABS:           return "fabs";
       case OP_SIGN:           return "sign";
       case OP_COPYSIGN:       return "copysign";
       case OP_IF_ELSE_ZERO:   return "if_else_zero";
       case OP_ERF:            return "erf";
       case OP_FMIN:           return "fmin";
       case OP_FMAX:           return "fmax";
       case OP_INV:            return "inv";
       case OP_SINH:           return "sinh";
       case OP_COSH:           return "cosh";
       case OP_TANH:           return "tanh";
       case OP_ASINH:          return "asinh";
       case OP_ACOSH:          return "acosh";
       case OP_ATANH:          return "atanh";
       case OP_ATAN2:          return "atan2";
       case OP_CONST:          return "const";
       case OP_INPUT:          return "input";
       case OP_OUTPUT:         return "output";
       case OP_PARAMETER:      return "parameter";
       case OP_CALL:           return "call";
       case OP_MTIMES:         return "matmul";
       case OP_SOLVE:          return "solve";
       case OP_TRANSPOSE:      return "transpose";
       case OP_DETERMINANT:    return "determinant";
       case OP_INVERSE:        return "inverse";
       case OP_DOT:            return "dot";
       case OP_HORZCAT:        return "horzcat";
       case OP_VERTCAT:        return "vertcat";
       case OP_DIAGCAT:        return "diagcat";
       case OP_HORZSPLIT:      return "horzsplit";
       case OP_VERTSPLIT:      return "vertsplit";
       case OP_DIAGSPLIT:      return "diagsplit";
       case OP_RESHAPE:        return "reshape";
       case OP_SUBREF:         return "subref";
       case OP_SUBASSIGN:      return "subassign";
       case OP_GETNONZEROS:    return "getnonzeros";
       case OP_ADDNONZEROS:    return "addnonzeros";
       case OP_SETNONZEROS:    return "setnonzeros";
       case OP_PROJECT:        return "project";
       case OP_ASSERTION:      return "assertion";
       case OP_NORM2:          return "norm2";
       case OP_NORM1:          return "norm1";
       case OP_NORMINF:        return "norminf";
       case OP_NORMF:          return "normf";
       case OP_ERFINV:         return "erfinv";
       case OP_PRINTME:        return "printme";
       case OP_LIFT:           return "lift";
       }
       return 0;
     }
template<typename T > int casadi::casadi_math< T >::ndeps (unsigned char op) inline static
Definition at line 1368 of file calculus.hpp.
References casadi::OP_CONST, casadi::OP_INPUT, and casadi::OP_PARAMETER.
Referenced by casadi::SXFunction::generateBody(), casadi::SXFunction::init(), casadi::SXElem::n_dep(), casadi::casadi_math< int >::ndeps(), and casadi::SXFunction::print().
{
 #define CASADI_MATH_BINARY_BUILTIN              \
     case OP_ADD:                                \
   case OP_SUB:                                  \
   case OP_MUL:                                  \
   case OP_DIV:                                  \
   case OP_POW:                                  \
   case OP_CONSTPOW:                             \
   case OP_LT:                                   \
   case OP_LE:                                   \
   case OP_EQ:                                   \
   case OP_NE:                                   \
   case OP_AND:                                  \
   case OP_OR:                                   \
   case OP_IF_ELSE_ZERO:                         \
   case OP_COPYSIGN:                             \
   case OP_FMOD:                                 \
   case OP_FMIN:                                 \
   case OP_FMAX:                                 \
   case OP_ATAN2:                                \
   case OP_PRINTME:                              \
   case OP_LIFT:
     switch (op) {
   case OP_CONST:
   case OP_PARAMETER:
   case OP_INPUT:
     return 0;
     CASADI_MATH_BINARY_BUILTIN
       return 2;
   default:
     return 1;
   }
   }
template<typename T > void casadi::casadi_math< T >::print (unsigned char op, std::ostream & stream, const std::string & x, const std::string & y) inline static
Definition at line 1405 of file calculus.hpp.
Referenced by casadi::Matrix< Scalar >::matrix_matrix(), and casadi::casadi_math< int >::print().
{
       if (ndeps(op)==2) {
         printPre(op, stream);
         stream << x;
         printSep(op, stream);
         stream << y;
         printPost(op, stream);
       } else {
         printPre(op, stream);
         stream << x;
         printPost(op, stream);
       }
     }
template<typename T > void casadi::casadi_math< T >::printPost (unsigned char op, std::ostream & stream) inline static
Definition at line 1546 of file calculus.hpp.
References casadi::OP_ASSIGN, and casadi::OP_IF_ELSE_ZERO.
Referenced by casadi::UnaryMX::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::SXFunction::generateBody(), casadi::UnaryMX::print(), casadi::BinaryMX< ScX, ScY >::print(), casadi::UnarySX::print(), casadi::SXFunction::print(), casadi::BinarySX::print(), and casadi::casadi_math< int >::printPost().
{
     switch (op) {
     case OP_ASSIGN:                        break;
     case OP_IF_ELSE_ZERO: stream << ":0)"; break;
     default:        stream << ")";         break;
     }
   }
template<typename T > void casadi::casadi_math< T >::printPre (unsigned char op, std::ostream & stream) inline static
Definition at line 1505 of file calculus.hpp.
References casadi::OP_ADD, casadi::OP_AND, casadi::OP_ASSIGN, casadi::OP_DIV, casadi::OP_EQ, casadi::OP_IF_ELSE_ZERO, casadi::OP_INV, casadi::OP_LE, casadi::OP_LT, casadi::OP_MUL, casadi::OP_NE, casadi::OP_NEG, casadi::OP_NOT, casadi::OP_OR, casadi::OP_SUB, and casadi::OP_TWICE.
Referenced by casadi::UnaryMX::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::SXFunction::generateBody(), casadi::UnaryMX::print(), casadi::BinaryMX< ScX, ScY >::print(), casadi::UnarySX::print(), casadi::SXFunction::print(), casadi::BinarySX::print(), and casadi::casadi_math< int >::printPre().
{
     switch (op) {
     case OP_ASSIGN:                          break;
     case OP_ADD:       stream << "(";        break;
     case OP_SUB:       stream << "(";        break;
     case OP_MUL:       stream << "(";        break;
     case OP_DIV:       stream << "(";        break;
     case OP_NEG:       stream << "(-";       break;
     case OP_TWICE:     stream << "(2.*";     break;
     case OP_LT:        stream << "(";        break;
     case OP_LE:        stream << "(";        break;
     case OP_EQ:        stream << "(";        break;
     case OP_NE:        stream << "(";        break;
     case OP_NOT:       stream << "(!";       break;
     case OP_AND:       stream << "(";        break;
     case OP_OR:        stream << "(";        break;
     case OP_IF_ELSE_ZERO: stream << "(";        break;
     case OP_INV:       stream << "(1./";     break;
     default: stream << name(op) << "("; break;
     }
   }
template<typename T > void casadi::casadi_math< T >::printSep (unsigned char op, std::ostream & stream) inline static
Definition at line 1528 of file calculus.hpp.
References casadi::OP_ADD, casadi::OP_AND, casadi::OP_DIV, casadi::OP_EQ, casadi::OP_IF_ELSE_ZERO, casadi::OP_LE, casadi::OP_LT, casadi::OP_MUL, casadi::OP_NE, casadi::OP_OR, and casadi::OP_SUB.
Referenced by casadi::BinaryMX< ScX, ScY >::generate(), casadi::SXFunction::generateBody(), casadi::BinaryMX< ScX, ScY >::print(), casadi::SXFunction::print(), casadi::BinarySX::print(), and casadi::casadi_math< int >::printSep().
{
     switch (op) {
     case OP_ADD:       stream << "+";        break;
     case OP_SUB:       stream << "-";        break;
     case OP_MUL:       stream << "*";        break;
     case OP_DIV:       stream << "/";        break;
     case OP_LT:        stream << "<";        break;
     case OP_LE:        stream << "<=";       break;
     case OP_EQ:        stream << "==";       break;
     case OP_NE:        stream << "!=";       break;
     case OP_AND:       stream << "&&";       break;
     case OP_OR:        stream << "||";       break;
     case OP_IF_ELSE_ZERO: stream << "?";     break;
     default:           stream << ",";        break;
     }
   }
The documentation for this struct was generated from the following file:
calculus.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge