CasADi: casadi::DaeBuilder Class Reference
casadi::DaeBuilder Class Reference
An initial-value problem in differential-algebraic equations.
#include <dae_builder.hpp>
Detailed Description
Independent variables:
t:      time
Time-continuous variables:
x:      states defined by ODE
s:      implicitly defined states
z:      algebraic variables
u:      control signals
q:      quadrature states
y:      outputs
Time-constant variables:
p:      free parameters
d:      dependent parameters
Dynamic constraints (imposed everywhere):
ODE                    \dot{x} ==  ode(t, x, s, z, u, p, d)
DAE or implicit ODE:         0 ==  dae(t, x, s, z, u, p, d, sdot)
algebraic equations:         0 ==  alg(t, x, s, z, u, p, d)
quadrature equations:  \dot{q} == quad(t, x, s, z, u, p, d)
dependent parameters:        d == ddef(t, x, s, z, u, p, d)
output equations:            y == ydef(t, x, s, z, u, p, d)
Point constraints (imposed pointwise):
Initial equations:           0 == init(t, x, s, z, u, p, d, sdot)
Date
2012-2015
Author
Joel Andersson
Definition at line 76 of file dae_builder.hpp.
Public Member Functions
DaeBuilder ()
Default constructor.
MX operator() (const std::string &name) const
Get variable expression by name.
MX der (const std::string &name) const
Get a derivative expression by name.
MX der (const MX &var) const
Get a derivative expression by non-differentiated expression.
double nominal (const std::string &name) const
Get the nominal value by name.
std::vector< double > nominal (const MX &var) const
Get the nominal value(s) by expression.
void set_nominal (const std::string &name, double val)
Set the nominal value by name.
void set_nominal (const MX &var, const std::vector< double > &val)
Set the nominal value(s) by expression.
double min (const std::string &name, bool normalized=false) const
Get the lower bound by name.
std::vector< double > min (const MX &var, bool normalized=false) const
Get the lower bound(s) by expression.
void set_min (const std::string &name, double val, bool normalized=false)
Set the lower bound by name.
void set_min (const MX &var, const std::vector< double > &val, bool normalized=false)
Set the lower bound(s) by expression.
double max (const std::string &name, bool normalized=false) const
Get the upper bound by name.
std::vector< double > max (const MX &var, bool normalized=false) const
Get the upper bound(s) by expression.
void set_max (const std::string &name, double val, bool normalized=false)
Set the upper bound by name.
void set_max (const MX &var, const std::vector< double > &val, bool normalized=false)
Set the upper bound(s) by expression.
double guess (const std::string &name, bool normalized=false) const
Get the initial guess by name.
std::vector< double > guess (const MX &var, bool normalized=false) const
Get the initial guess(es) by expression.
void set_guess (const std::string &name, double val, bool normalized=false)
Set the initial guess by name.
void set_guess (const MX &var, const std::vector< double > &val, bool normalized=false)
Set the initial guess(es) by expression.
double start (const std::string &name, bool normalized=false) const
Get the (optionally normalized) value at time 0 by name.
std::vector< double > start (const MX &var, bool normalized=false) const
Get the (optionally normalized) value(s) at time 0 by expression.
void set_start (const std::string &name, double val, bool normalized=false)
Set the (optionally normalized) value at time 0 by name.
void set_start (const MX &var, const std::vector< double > &val, bool normalized=false)
Set the (optionally normalized) value(s) at time 0 by expression.
double derivative_start (const std::string &name, bool normalized=false) const
Get the (optionally normalized) derivative value at time 0 by name.
std::vector< double > derivative_start (const MX &var, bool normalized=false) const
Get the (optionally normalized) derivative value(s) at time 0 by expression.
void set_derivative_start (const std::string &name, double val, bool normalized=false)
Set the (optionally normalized) derivative value at time 0 by name.
void set_derivative_start (const MX &var, const std::vector< double > &val, bool normalized=false)
Set the (optionally normalized) derivative value(s) at time 0 by expression.
std::string unit (const std::string &name) const
Get the unit for a component.
std::string unit (const MX &var) const
Get the unit given a vector of symbolic variables (all units must be identical)
void set_unit (const std::string &name, const std::string &val)
Set the unit for a component.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print representation.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print description.
void add_variable (const std::string &name, const Variable &var)
Add a variable.
MX add_variable (const std::string &name, int n=1)
Add a new variable: returns corresponding symbolic expression.
MX add_variable (const std::string &name, const Sparsity &sp)
Add a new variable: returns corresponding symbolic expression.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
Symbolic modeling
Formulate an optimal control problem
MX add_p (const std::string &name=std::string(), int n=1)
MX add_u (const std::string &name=std::string(), int n=1)
Add a new control.
MX add_x (const std::string &name=std::string(), int n=1)
Add a new differential state.
std::pair< MX, MX > add_s (const std::string &name=std::string(), int n=1)
Add a implicit state.
MX add_z (const std::string &name=std::string(), int n=1)
Add a new algebraic variable.
MX add_q (const std::string &name=std::string(), int n=1)
Add a new quadrature state.
MX add_d (const MX &new_ddef, const std::string &name=std::string())
Add a new dependent parameter.
MX add_y (const MX &new_ydef, const std::string &name=std::string())
Add a new output.
void add_ode (const MX &new_ode, const std::string &name=std::string())
Add an ordinary differential equation.
void add_dae (const MX &new_dae, const std::string &name=std::string())
Add a differential-algebraic equation.
void add_alg (const MX &new_alg, const std::string &name=std::string())
Add an algebraic equation.
void add_quad (const MX &new_quad, const std::string &name=std::string())
Add a quadrature equation.
void sanity_check () const
Check if dimensions match.
Manipulation
Reformulate the dynamic optimization problem.
void split_dae ()
Identify and separate the algebraic variables and equations in the DAE.
void eliminate_alg ()
Eliminate algebraic variables and equations transforming them into outputs.
void make_semi_explicit ()
Transform the implicit DAE to a semi-explicit DAE.
void make_explicit ()
Transform the implicit DAE or semi-explicit DAE into an explicit ODE.
void sort_d ()
Sort dependent parameters.
void split_d ()
Eliminate interdependencies amongst dependent parameters.
void eliminate_d ()
Eliminate dependent parameters.
void eliminate_quad ()
Eliminate quadrature states and turn them into ODE states.
void sort_dae ()
Sort the DAE and implicitly defined states.
void sort_alg ()
Sort the algebraic equations and algebraic states.
void scale_variables ()
Scale the variables.
void scale_equations ()
Scale the implicit equations.
Variable & variable (const std::string &name)
const Variable & variable (const std::string &name) const
Public Attributes
std::vector< MX > init
Initial conditions At t==0, 0 == init(sdot, s, ...) holds in addition to the ode and/or dae.
Variables and equations
Public data members
MX t
Independent variable (usually time)
std::vector< MX > x
Differential states defined by ordinary differential equations (ODE)
std::vector< MX > ode
Independent variable (usually time)
std::vector< MX > lam_ode
Independent variable (usually time)
std::vector< MX > s
Differential-algebraic equation (DAE) with corresponding state vector, state derivatives.
std::vector< MX > sdot
Independent variable (usually time)
std::vector< MX > dae
Independent variable (usually time)
std::vector< MX > lam_dae
Independent variable (usually time)
std::vector< MX > z
Algebraic equations and corresponding algebraic variables alg and z have matching dimensions and 0 == alg(z, ...) implicitly defines z.
std::vector< MX > alg
Independent variable (usually time)
std::vector< MX > lam_alg
Independent variable (usually time)
std::vector< MX > q
Quadrature states Quadrature states are defined by ODEs whose state does not enter in the right-hand-side.
std::vector< MX > quad
Independent variable (usually time)
std::vector< MX > lam_quad
Independent variable (usually time)
std::vector< MX > w
Local variables and corresponding definitions.
std::vector< MX > wdef
Independent variable (usually time)
std::vector< MX > lam_wdef
Independent variable (usually time)
std::vector< MX > y
Output variables and corresponding definitions.
std::vector< MX > ydef
Independent variable (usually time)
std::vector< MX > lam_ydef
Independent variable (usually time)
std::vector< MX > u
Free controls The trajectories of the free controls are decision variables of the optimal control problem. They are chosen by the optimization algorithm in order to minimize the cost functional.
std::vector< MX > p
Parameters A parameter is constant over time, but whose value is chosen by e.g. an optimization algorithm.
std::vector< MX > c
Named constants.
std::vector< MX > cdef
Independent variable (usually time)
std::vector< MX > d
Dependent parameters and corresponding definitions Interdependencies are allowed but must be non-cyclic.
std::vector< MX > ddef
Independent variable (usually time)
std::vector< MX > lam_ddef
Independent variable (usually time)
Protected Types
typedef std::map< std::string,
Variable > VarMap
Find of variable by name.
typedef double(DaeBuilder::* getAtt)(const std::string &name, bool normalized) const
Get an attribute by expression.
typedef MX(DaeBuilder::* getAttS)(const std::string &name) const
Get a symbolic attribute by expression.
typedef void(DaeBuilder::* setAtt)(const std::string &name, double val, bool normalized)
Set an attribute by expression.
typedef void(DaeBuilder::* setAttS)(const std::string &name, const MX &val)
Set a symbolic attribute by expression.
Protected Member Functions
MX read_expr (const XmlNode &odenode)
Read an equation.
Variable & read_variable (const XmlNode &node)
Read a variable.
std::vector< double > attribute (getAtt f, const MX &var, bool normalized) const
MX attribute (getAttS f, const MX &var) const
void set_attribute (setAtt f, const MX &var, const std::vector< double > &val, bool normalized)
void set_attribute (setAttS f, const MX &var, const MX &val)
Static Protected Member Functions
static std::string qualified_name (const XmlNode &nn)
Get the qualified name.
Protected Attributes
VarMap varmap_
std::map< std::string, MX > lin_comb_
Linear combinations of output expressions.
Import and export
enum DaeBuilderIn {
DAE_BUILDER_T, DAE_BUILDER_C, DAE_BUILDER_P, DAE_BUILDER_D,
DAE_BUILDER_U, DAE_BUILDER_X, DAE_BUILDER_S, DAE_BUILDER_SDOT,
DAE_BUILDER_Z, DAE_BUILDER_Q, DAE_BUILDER_W, DAE_BUILDER_Y,
DAE_BUILDER_NUM_IN
}
enum DaeBuilderOut {
DAE_BUILDER_DDEF, DAE_BUILDER_WDEF, DAE_BUILDER_ODE, DAE_BUILDER_DAE,
DAE_BUILDER_ALG, DAE_BUILDER_QUAD, DAE_BUILDER_YDEF, DAE_BUILDER_NUM_OUT
}
void parse_fmi (const std::string &filename)
std::vector< MX > input (DaeBuilderIn ind) const
std::vector< MX > output (DaeBuilderOut ind) const
std::vector< MX > input (std::vector< DaeBuilderIn > &ind) const
std::vector< MX > output (std::vector< DaeBuilderOut > &ind) const
std::vector< MX > multiplier (DaeBuilderOut ind) const
MX add_lc (const std::string &name, const std::vector< std::string > &f_out)
Add a named linear combination of output expressions.
Function create (const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out) const
Construct a function object.
static std::string name_in (DaeBuilderIn ind)
static std::string name_in ()
static DaeBuilderIn enum_in (const std::string &id)
static std::vector< DaeBuilderIn > enum_in (const std::vector< std::string > &id)
static std::string name_out (DaeBuilderOut ind)
static std::string name_out ()
static DaeBuilderOut enum_out (const std::string &id)
static std::vector< DaeBuilderOut > enum_out (const std::vector< std::string > &id)
Member Typedef Documentation
typedef double(DaeBuilder::* casadi::DaeBuilder::getAtt)(const std::string &name, bool normalized) const protected
Definition at line 450 of file dae_builder.hpp.
typedef MX(DaeBuilder::* casadi::DaeBuilder::getAttS)(const std::string &name) const protected
Definition at line 454 of file dae_builder.hpp.
typedef void(DaeBuilder::* casadi::DaeBuilder::setAtt)(const std::string &name, double val, bool normalized) protected
Definition at line 458 of file dae_builder.hpp.
typedef void(DaeBuilder::* casadi::DaeBuilder::setAttS)(const std::string &name, const MX &val) protected
Definition at line 462 of file dae_builder.hpp.
typedef std::map<std::string, Variable> casadi::DaeBuilder::VarMap protected
Definition at line 437 of file dae_builder.hpp.
Member Enumeration Documentation
enum casadi::DaeBuilder::DaeBuilderIn
Import existing problem from FMI/XML
Enumerator
DAE_BUILDER_T
DAE_BUILDER_C
DAE_BUILDER_P
DAE_BUILDER_D
DAE_BUILDER_U
DAE_BUILDER_X
DAE_BUILDER_S
DAE_BUILDER_SDOT
DAE_BUILDER_Z
DAE_BUILDER_Q
DAE_BUILDER_W
DAE_BUILDER_Y
DAE_BUILDER_NUM_IN
Definition at line 240 of file dae_builder.hpp.
                       {
       DAE_BUILDER_T,
       DAE_BUILDER_C,
       DAE_BUILDER_P,
       DAE_BUILDER_D,
       DAE_BUILDER_U,
       DAE_BUILDER_X,
       DAE_BUILDER_S,
       DAE_BUILDER_SDOT,
       DAE_BUILDER_Z,
       DAE_BUILDER_Q,
       DAE_BUILDER_W,
       DAE_BUILDER_Y,
       DAE_BUILDER_NUM_IN
     };
enum casadi::DaeBuilder::DaeBuilderOut
Import existing problem from FMI/XML
Enumerator
DAE_BUILDER_DDEF
DAE_BUILDER_WDEF
DAE_BUILDER_ODE
DAE_BUILDER_DAE
DAE_BUILDER_ALG
DAE_BUILDER_QUAD
DAE_BUILDER_YDEF
DAE_BUILDER_NUM_OUT
Definition at line 257 of file dae_builder.hpp.
{
       DAE_BUILDER_DDEF,
       DAE_BUILDER_WDEF,
       DAE_BUILDER_ODE,
       DAE_BUILDER_DAE,
       DAE_BUILDER_ALG,
       DAE_BUILDER_QUAD,
       DAE_BUILDER_YDEF,
       DAE_BUILDER_NUM_OUT
     };
Constructor & Destructor Documentation
casadi::DaeBuilder::DaeBuilder ()
Definition at line 56 of file dae_builder.cpp.
{
     this->t = MX::sym("t");
   }
Member Function Documentation
void casadi::DaeBuilder::add_alg (const MX & new_alg, const std::string & name = std::string())
Definition at line 1044 of file dae_builder.cpp.
References casadi::MX::sparsity().
{
     if (name.empty()) // Generate a name
       return add_alg(new_alg, "alg" + CodeGenerator::to_string(this->alg.size()));
     this->alg.push_back(new_alg);
     this->lam_alg.push_back(MX::sym("lam_" + name, new_alg.sparsity()));
   }
MX casadi::DaeBuilder::add_d (const MX & new_ddef, const std::string & name = std::string())
Definition at line 1010 of file dae_builder.cpp.
References casadi::MX::sparsity().
{
     if (name.empty()) // Generate a name
       return add_d(new_ddef, "d" + CodeGenerator::to_string(this->d.size()));
     MX new_d = add_variable(name, new_ddef.sparsity());
     this->d.push_back(new_d);
     this->ddef.push_back(new_ddef);
     this->lam_ddef.push_back(MX::sym("lam_" + name, new_ddef.sparsity()));
     return new_d;
   }
void casadi::DaeBuilder::add_dae (const MX & new_dae, const std::string & name = std::string())
Definition at line 1037 of file dae_builder.cpp.
References casadi::MX::sparsity().
{
     if (name.empty()) // Generate a name
       return add_dae(new_dae, "dae" + CodeGenerator::to_string(this->dae.size()));
     this->dae.push_back(new_dae);
     this->lam_dae.push_back(MX::sym("lam_" + name, new_dae.sparsity()));
   }
MX casadi::DaeBuilder::add_lc (const std::string & name, const std::vector< std::string > & f_out)
Definition at line 1610 of file dae_builder.cpp.
References casadi::dot(), and casadi::GenericMatrix< MatType >::is_empty().
{
     // Make sure object valid
     sanity_check();
     // Make sure name is valid
     casadi_assert_message(!name.empty(), "DaeBuilder::add_lc: \"name\" is empty");
     for (string::const_iterator i=name.begin(); i!=name.end(); ++i) {
       casadi_assert_message(isalnum(*i),
                             "DaeBuilder::add_lc: \"name\" must be alphanumeric");
     }
     // Get a reference to the expression
     MX& ret = lin_comb_[name];
     casadi_assert_warning(ret.is_empty(), "DaeBuilder::add_lc: Overwriting " << name);
     ret = 0;
     // Get indices of outputs
     std::vector<DaeBuilderOut> f_out_enum(f_out.size());
     std::vector<bool> in_use(DAE_BUILDER_NUM_OUT, false);
     for (int i=0; i<f_out.size(); ++i) {
       DaeBuilderOut oind = enum_out(f_out[i]);
       casadi_assert_message(oind!=DAE_BUILDER_NUM_OUT,
                             "DaeBuilder::add_lc: No output expression " << f_out[i]
                             << ". Valid expressions are " << name_out());
       casadi_assert_message(!in_use[oind],
                             "DaeBuilder::add_lc: Duplicate expression " << f_out[i]);
       in_use[oind] = true;
       // Add linear combination of expressions
       vector<MX> res=output(oind), lam_res=multiplier(oind);
       for (int i=0; i<res.size(); ++i) {
         ret += dot(lam_res[i], res[i]);
       }
     }
     // Return the (cached) expression
     return ret;
   }
void casadi::DaeBuilder::add_ode (const MX & new_ode, const std::string & name = std::string())
Definition at line 1030 of file dae_builder.cpp.
References casadi::MX::sparsity().
{
     if (name.empty()) // Generate a name
       return add_ode(new_ode, "ode" + CodeGenerator::to_string(this->ode.size()));
     this->ode.push_back(new_ode);
     this->lam_ode.push_back(MX::sym("lam_" + name, new_ode.sparsity()));
   }
MX casadi::DaeBuilder::add_p (const std::string & name = std::string(), int n = 1)
Add a new parameter
Definition at line 994 of file dae_builder.cpp.
{
     if (name.empty()) // Generate a name
       return add_p("p" + CodeGenerator::to_string(this->p.size()), n);
     MX new_p = add_variable(name, n);
     this->p.push_back(new_p);
     return new_p;
   }
MX casadi::DaeBuilder::add_q (const std::string & name = std::string(), int n = 1)
Definition at line 968 of file dae_builder.cpp.
{
     if (name.empty()) // Generate a name
       return add_q("q" + CodeGenerator::to_string(this->q.size()), n);
     MX new_q = add_variable(name, n);
     this->q.push_back(new_q);
     return new_q;
   }
void casadi::DaeBuilder::add_quad (const MX & new_quad, const std::string & name = std::string())
Definition at line 1051 of file dae_builder.cpp.
References casadi::MX::sparsity().
{
     if (name.empty()) // Generate a name
       return add_quad(new_quad, "quad" + CodeGenerator::to_string(this->quad.size()));
     this->quad.push_back(new_quad);
     this->lam_quad.push_back(MX::sym("lam_" + name, new_quad.sparsity()));
   }
std::pair< MX, MX > casadi::DaeBuilder::add_s (const std::string & name = std::string(), int n = 1)
Definition at line 976 of file dae_builder.cpp.
References casadi::Variable::d, and casadi::Variable::v.
{
     if (name.empty()) // Generate a name
       return add_s("s" + CodeGenerator::to_string(this->s.size()), n);
     Variable v(name, Sparsity::dense(n));
     add_variable(name, v);
     this->s.push_back(v.v);
     this->sdot.push_back(v.d);
     return std::pair<MX, MX>(v.v, v.d);
   }
MX casadi::DaeBuilder::add_u (const std::string & name = std::string(), int n = 1)
Definition at line 1002 of file dae_builder.cpp.
{
     if (name.empty()) // Generate a name
       return add_u("u" + CodeGenerator::to_string(this->u.size()), n);
     MX new_u = add_variable(name, n);
     this->u.push_back(new_u);
     return new_u;
   }
void casadi::DaeBuilder::add_variable (const std::string & name, const Variable & var)
Definition at line 939 of file dae_builder.cpp.
{
     // Try to find the component
     if (varmap_.find(name)!=varmap_.end()) {
       stringstream ss;
       casadi_error("Variable \"" << name << "\" has already been added.");
     }
     // Add to the map of all variables
     varmap_[name] = var;
   }
MX casadi::DaeBuilder::add_variable (const std::string & name, int n = 1)
Definition at line 950 of file dae_builder.cpp.
{
     return add_variable(name, Sparsity::dense(n));
   }
MX casadi::DaeBuilder::add_variable (const std::string & name, const Sparsity & sp)
Definition at line 954 of file dae_builder.cpp.
References casadi::Variable::v.
{
     Variable v(name, sp);
     add_variable(name, v);
     return v.v;
   }
MX casadi::DaeBuilder::add_x (const std::string & name = std::string(), int n = 1)
Definition at line 960 of file dae_builder.cpp.
{
     if (name.empty()) // Generate a name
       return add_x("x" + CodeGenerator::to_string(this->x.size()), n);
     MX new_x = add_variable(name, n);
     this->x.push_back(new_x);
     return new_x;
   }
MX casadi::DaeBuilder::add_y (const MX & new_ydef, const std::string & name = std::string())
Definition at line 1020 of file dae_builder.cpp.
References casadi::MX::sparsity().
{
     if (name.empty()) // Generate a name
       return add_y(new_ydef, "y" + CodeGenerator::to_string(this->y.size()));
     MX new_y = add_variable(name, new_ydef.sparsity());
     this->y.push_back(new_y);
     this->ydef.push_back(new_ydef);
     this->lam_ydef.push_back(MX::sym("lam_" + name, new_ydef.sparsity()));
     return new_y;
   }
MX casadi::DaeBuilder::add_z (const std::string & name = std::string(), int n = 1)
Definition at line 986 of file dae_builder.cpp.
{
     if (name.empty()) // Generate a name
       return add_z("z" + CodeGenerator::to_string(this->z.size()), n);
     MX new_z = add_variable(name, n);
     this->z.push_back(new_z);
     return new_z;
   }
std::vector< double > casadi::DaeBuilder::attribute (getAtt f, const MX & var, bool normalized) const protected
Definition at line 1289 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::MX::is_valid_input(), casadi::GenericMatrix< MatType >::nnz(), and casadi::MX::primitives().
{
     casadi_assert_message(var.is_column() && var.is_valid_input(),
                           "DaeBuilder::attribute: Argument must be a symbolic vector");
     std::vector<double> ret(var.nnz());
     std::vector<MX> prim = var.primitives();
     for (int i=0; i<prim.size(); ++i) {
       casadi_assert(prim[i].nnz()==1);
       ret[i] = (this->*f)(prim[i].name(), normalized);
     }
     return ret;
   }
MX casadi::DaeBuilder::attribute (getAttS f, const MX & var) const protected
Definition at line 1301 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::MX::is_valid_input(), casadi::MX::primitives(), and casadi::MX::sparsity().
{
     casadi_assert_message(var.is_column() && var.is_valid_input(),
                           "DaeBuilder::attribute: Argument must be a symbolic vector");
     MX ret = MX::zeros(var.sparsity());
     std::vector<MX> prim = var.primitives();
     for (int i=0; i<prim.size(); ++i) {
       casadi_assert(prim[i].nnz()==1);
       ret[i] = (this->*f)(prim[i].name());
     }
     return ret;
   }
Function casadi::DaeBuilder::create (const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out) const
Definition at line 1650 of file dae_builder.cpp.
References casadi::densify(), casadi::fill(), and casadi::MX::T().
{
     // Collect function inputs
     vector<MX> ret_in(s_in.size());
     std::vector<bool> input_used(DAE_BUILDER_NUM_IN, false);
     std::vector<bool> output_used(DAE_BUILDER_NUM_IN, false);
     for (vector<string>::const_iterator s_in_it=s_in.begin(); s_in_it!=s_in.end(); ++s_in_it) {
       // Primal variable
       DaeBuilderIn iind = enum_in(*s_in_it);
       if (iind!=DAE_BUILDER_NUM_IN) {
         casadi_assert_message(!input_used[iind],
                               "DaeBuilder::function: Duplicate expression " << *s_in_it);
         input_used[iind] = true;
         ret_in[s_in_it-s_in.begin()] = vertcat(input(iind));
         continue;
       }
       // Dual variable
       if (s_in_it->size()>4 && s_in_it->substr(0, 4)=="lam_") {
         DaeBuilderOut oind = enum_out(s_in_it->substr(4, string::npos));
         if (oind!=DAE_BUILDER_NUM_OUT) {
           casadi_assert_message(!output_used[oind],
                                 "DaeBuilder::function: Duplicate expression " << *s_in_it);
           output_used[oind] = true;
           ret_in[s_in_it-s_in.begin()] = vertcat(multiplier(oind));
           continue;
         }
       }
       // Error if reached this point
       stringstream ss;
       ss << "DaeBuilder::function: No input expression " << *s_in_it << "." << endl;
       ss << "Valid expressions are: [";
       for (int i=0; i!=DAE_BUILDER_NUM_IN; ++i) {
         if (i!=0) ss << ", ";
         ss << name_in(static_cast<DaeBuilderIn>(i));
       }
       for (int i=0; i!=DAE_BUILDER_NUM_OUT; ++i) {
         ss << ", lam_" << name_out(static_cast<DaeBuilderOut>(i));
       }
       ss << "]";
       casadi_error(ss.str());
     }
     // Function outputs
     vector<MX> ret_out(s_out.size());
     vector<bool> assigned(s_out.size(), false);
     // List of valid attributes
     enum Attributes {
       ATTR_TRANSPOSE,
       ATTR_TRIU,
       ATTR_TRIL,
       ATTR_DENSIFY};
     // Separarate attributes
     vector<vector<Attributes> > attr(s_out.size());
     vector<string> s_out_noatt = s_out;
     for (int i=0; i<s_out_noatt.size(); ++i) {
       // Currently processed string
       string& s = s_out_noatt[i];
       // Loop over attributes
       while (true) {
         // Find the first underscore separator
         size_t pos = s.find('_');
         if (pos>=s.size()) break; // No more underscore
         string a = s.substr(0, pos);
         // Abort if not attribute
         if (a=="transpose") {
           attr[i].push_back(ATTR_TRANSPOSE);
         } else if (a=="triu") {
           attr[i].push_back(ATTR_TRIU);
         } else if (a=="tril") {
           attr[i].push_back(ATTR_TRIL);
         } else if (a=="densify") {
           attr[i].push_back(ATTR_DENSIFY);
         } else {
           // No more attribute
           break;
         }
         // Strip attribute
         s = s.substr(pos+1, string::npos);
       }
     }
     // Non-differentiated outputs
     fill(output_used.begin(), output_used.end(), false);
     for (int i=0; i<s_out_noatt.size(); ++i) {
       DaeBuilderOut oind = enum_out(s_out_noatt[i]);
       if (oind!=DAE_BUILDER_NUM_OUT) {
         casadi_assert_message(!output_used[oind],
                               "DaeBuilder::function: Duplicate expression " << s_out_noatt[i]);
         output_used[oind] = true;
         ret_out[i] = vertcat(output(oind));
         assigned[i] = true;
       }
     }
     // Linear combination of outputs
     for (int i=0; i<s_out_noatt.size(); ++i) {
       if (assigned[i]) continue;
       std::map<std::string, MX>::const_iterator j=lin_comb_.find(s_out_noatt[i]);
       if (j!=lin_comb_.end()) {
         ret_out[i] = j->second;
         assigned[i] = true;
       }
     }
     // Determine which Jacobian blocks to generate
     vector<vector<int> > wanted(DAE_BUILDER_NUM_OUT, vector<int>(DAE_BUILDER_NUM_IN, -1));
     for (int i=0; i<s_out_noatt.size(); ++i) {
       if (assigned[i]) continue;
       // Get the string without attributes
       const string& so = s_out_noatt[i];
       // Find the first underscore separator
       size_t pos = so.find('_');
       if (pos>=so.size()) continue;
       // Get operation
       string s = so.substr(0, pos);
       if (s!="jac") continue;
       // Get expression to be differentiated
       size_t pos1 = so.find('_', pos+1);
       if (pos1>=so.size()) continue;
       s = so.substr(pos+1, pos1-pos-1);
       DaeBuilderOut oind = enum_out(s);
       if (oind==DAE_BUILDER_NUM_OUT) continue;
       // Jacobian with respect to what variable
       s = so.substr(pos1+1, string::npos);
       DaeBuilderIn iind = enum_in(s);
       if (iind==DAE_BUILDER_NUM_IN) continue;
       // Check if duplicate
       casadi_assert_message(wanted[oind][iind]==-1,
                             "DaeBuilder::function: Duplicate Jacobian " << so);
       wanted[oind][iind] = i;
     }
     // Generate Jacobian blocks
     for (int oind=0; oind!=DAE_BUILDER_NUM_OUT; ++oind) {
       for (int iind=0; iind!=DAE_BUILDER_NUM_IN; ++iind) {
         // Skip if not wanted
         if (wanted[oind][iind]==-1) continue;
         // List of blocks to be calculated together, starting with current
         vector<DaeBuilderIn> ib(1, static_cast<DaeBuilderIn>(iind));
         vector<DaeBuilderOut> ob(1, static_cast<DaeBuilderOut>(oind));
         // Add other blocks that can be calculated with the same inputs
         // (typically cheap if forward mode used)
         for (int oind1=oind+1; oind1!=DAE_BUILDER_NUM_OUT; ++oind1) {
           if (wanted[oind1][iind]>=0) {
             ob.push_back(static_cast<DaeBuilderOut>(oind1));
           }
         }
         // Add other blocks that can be calculated with the same outputs
         // (typically cheap if reverse mode used)
         for (int iind1=iind+1; iind1!=DAE_BUILDER_NUM_IN; ++iind1) {
           // Do we really want _all_ the input/output combinations?
           bool all_wanted = true;
           for (int k=0; k<ob.size() && all_wanted; ++k) {
             all_wanted = wanted[ob[k]][iind1]>=0;
           }
           // Add block(s)
           if (all_wanted) {
             ib.push_back(static_cast<DaeBuilderIn>(iind1));
           }
         }
         // When we know which blocks we are interested in, we form the Jacobian
         vector<MX> arg=input(ib), res=output(ob);
         MX J = jacobian(vertcat(res), vertcat(arg));
         // Divide into blocks and copy to output
         vector<vector<MX> > J_all = blocksplit(J, offset(res), offset(arg));
         for (int ki=0; ki<ib.size(); ++ki) {
           for (int ko=0; ko<ob.size(); ++ko) {
             int& ind=wanted[ob[ko]][ib[ki]];
             ret_out[ind] = J_all[ko][ki];
             assigned[ind] = true;
             ind = -1;
           }
         }
       }
     }
     // For all linear combinations
     for (std::map<std::string, MX>::const_iterator lin_comb_it=lin_comb_.begin();
          lin_comb_it!=lin_comb_.end(); ++lin_comb_it) {
       // Determine which Hessian blocks to generate
       wanted.resize(DAE_BUILDER_NUM_IN);
       fill(wanted.begin(), wanted.end(), vector<int>(DAE_BUILDER_NUM_IN, -1));
       for (int i=0; i<s_out_noatt.size(); ++i) {
         if (assigned[i]) continue;
         // Get the string without attributes
         const string& so = s_out_noatt[i];
         // Get operation
         size_t pos = so.find('_');
         if (pos>=so.size()) continue;
         string s = so.substr(0, pos);
         if (s!="hes") continue;
         // Get expression to be differentiated
         size_t pos1 = so.find('_', pos+1);
         if (pos1>=so.size()) continue;
         s = so.substr(pos+1, pos1-pos-1);
         if (s!=lin_comb_it->first) continue;
         // Get first derivative
         pos = so.find('_', pos1+1);
         if (pos>=so.size()) continue;
         s = so.substr(pos1+1, pos-pos1-1);
         DaeBuilderIn iind1 = enum_in(s);
         if (iind1==DAE_BUILDER_NUM_IN) continue;
         // Get second derivative
         s = so.substr(pos+1, string::npos);
         DaeBuilderIn iind2 = enum_in(s);
         if (iind2==DAE_BUILDER_NUM_IN) continue;
         // Check if duplicate
         casadi_assert_message(wanted[iind1][iind2]==-1,
                               "DaeBuilder::function: Duplicate Hessian " << so);
         wanted[iind1][iind2] = i;
       }
       // Created wanted Hessian blocks
       for (int iind1=0; iind1!=DAE_BUILDER_NUM_IN; ++iind1) {
         for (int iind2=0; iind2!=DAE_BUILDER_NUM_IN; ++iind2) {
           // Skip if not wanted
           if (wanted[iind1][iind2]==-1) continue;
           // List of blocks to be calculated together, starting with current
           vector<DaeBuilderIn> ib1(1, static_cast<DaeBuilderIn>(iind1));
           vector<DaeBuilderIn> ib2(1, static_cast<DaeBuilderIn>(iind2));
           // Add other blocks vertically
           for (int iind=iind1+1; iind!=DAE_BUILDER_NUM_IN; ++iind) {
             if (wanted[iind][iind2]>=0 || wanted[iind2][iind]>=0) {
               ib1.push_back(static_cast<DaeBuilderIn>(iind));
             }
           }
           // Add other blocks horizontally
           for (int iind=iind2+1; iind!=DAE_BUILDER_NUM_IN; ++iind) {
             // Do we really want _all_ the blocks?
             bool all_wanted = true;
             for (int k=0; k<ib1.size() && all_wanted; ++k) {
               all_wanted = wanted[ib1[k]][iind]>=0 || wanted[iind][ib1[k]]>=0;
             }
             // Add block(s)
             if (all_wanted) {
               ib2.push_back(static_cast<DaeBuilderIn>(iind));
             }
           }
           // Symmetric or not?
           bool symmetric=ib1.size()==ib2.size();
           for (int i=0; symmetric && i<ib1.size(); ++i) symmetric=ib1[i]==ib2[i];
           // Calculate blocks
           vector<vector<MX> > H_all;
           if (symmetric) {
             vector<MX> arg=input(ib1);
             MX H = hessian(lin_comb_it->second, vertcat(arg));
             H_all = blocksplit(H, offset(arg), offset(arg));
           } else {
             vector<MX> arg1=input(ib1), arg2=input(ib2);
             MX g = gradient(lin_comb_it->second, vertcat(arg1));
             MX J = jacobian(g, vertcat(arg2));
             H_all = blocksplit(J, offset(arg1), offset(arg2));
           }
           // Fetch the requested blocks
           for (int k1=0; k1<ib1.size(); ++k1) {
             for (int k2=0; k2<ib2.size(); ++k2) {
               int& ind=wanted[ib1[k1]][ib2[k2]];
               if (ind>=0) {
                 ret_out[ind] = H_all[k1][k2];
                 assigned[ind] = true;
                 ind = -1;
               }
             }
           }
         }
       }
     }
     // Check and post-process outputs
     for (int i=0; i<s_out.size(); ++i) {
       // Make sure all outputs have been assigned
       if (!assigned[i]) {
         casadi_error("DaeBuilder::function: Cannot treat output expression " << s_out[i]);
       }
       // Apply attributes starting from the right-most one
       MX& r = ret_out[i];
       for (auto a=attr[i].rbegin(); a!=attr[i].rend(); ++a) {
         switch (*a) {
         case ATTR_TRANSPOSE: r = r.T(); break;
         case ATTR_TRIU: r = triu(r); break;
         case ATTR_TRIL: r = tril(r); break;
         case ATTR_DENSIFY: r = densify(r); break;
         }
       }
     }
     // Generate the constructed function
     return Function(fname, ret_in, ret_out,
                     {{"input_scheme", s_in}, {"output_scheme", s_out}});
   }
MX casadi::DaeBuilder::der (const std::string & name) const
Definition at line 1159 of file dae_builder.cpp.
{
     return variable(name).d;
   }
MX casadi::DaeBuilder::der (const MX & var) const
Definition at line 1163 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::MX::is_symbolic(), and casadi::MX::sparsity().
{
     casadi_assert(var.is_column() && var.is_symbolic());
     MX ret = MX::zeros(var.sparsity());
     for (int i=0; i<ret.nnz(); ++i) {
       ret[i] = der(var[i].name());
     }
     return ret;
   }
double casadi::DaeBuilder::derivative_start (const std::string & name, bool normalized = false) const
Definition at line 1410 of file dae_builder.cpp.
References casadi::Variable::derivative_start, and casadi::Variable::nominal.
{
     const Variable& v = variable(name);
     return normalized ? v.derivative_start / v.nominal : v.derivative_start;
   }
std::vector< double > casadi::DaeBuilder::derivative_start (const MX & var, bool normalized = false) const
Definition at line 1415 of file dae_builder.cpp.
{
     return attribute(&DaeBuilder::derivative_start, var, normalized);
   }
void casadi::DaeBuilder::eliminate_alg ()
Definition at line 816 of file dae_builder.cpp.
{
     // Only works if there are no i
     eliminate_d();
     // Quick return if there are no algebraic states
     if (this->z.empty()) return;
     // Write the algebraic equations as a function of the algebraic states
     Function f("f", {vertcat(this->z)}, {vertcat(this->alg)});
     // Get the sparsity of the Jacobian which can be used to determine which
     // variable can be calculated from which other
     Sparsity sp = f.sparsity_jac();
     casadi_assert(sp.is_square());
     // BLT transformation
     vector<int> rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock;
     int nb = sp.btf(rowperm, colperm, rowblock, colblock,
                                   coarse_rowblock, coarse_colblock);
     // Resort equations and variables
     vector<MX> algnew(this->z.size()), znew(this->z.size());
     for (int i=0; i<rowperm.size(); ++i) {
       // Permute equations
       algnew[i] = this->alg[rowperm[i]];
       // Permute variables
       znew[i] = this->z[colperm[i]];
     }
     this->alg = algnew;
     this->z = znew;
     // Rewrite the sorted algebraic equations as a function of the algebraic states
     f = Function("f", {vertcat(this->z)}, {vertcat(this->alg)});
     // Variables where we have found an explicit expression and where we haven't
     vector<MX> z_exp, z_imp;
     // Explicit and implicit equations
     vector<MX> f_exp, f_imp;
     // Loop over blocks
     for (int b=0; b<nb; ++b) {
       // Get local variables
       vector<MX> zb(this->z.begin()+colblock[b], this->z.begin()+colblock[b+1]);
       // Get local equations
       vector<MX> fb(this->alg.begin()+rowblock[b], this->alg.begin()+rowblock[b+1]);
       // Get local Jacobian
       MX Jb = jacobian(vertcat(fb), vertcat(zb));
       // If Jb depends on zb, then we cannot (currently) solve for it explicitly
       if (depends_on(Jb, vertcat(zb))) {
         // Add the equations to the new list of algebraic equations
         f_imp.insert(f_imp.end(), fb.begin(), fb.end());
         // ... and the variables accordingly
         z_imp.insert(z_imp.end(), zb.begin(), zb.end());
       } else { // The variables that we wish to determine enter linearly
         // Divide fb into a part which depends on vb and a part which doesn't
         // according to "fb == mul(Jb, vb) + fb_res"
         vector<MX> fb_res = substitute(fb, zb, vector<MX>(zb.size(), 0));
         // Solve for vb
         vector<MX> fb_exp = vertsplit(solve(Jb, -vertcat(fb_res)));
         // Add to explicitly determined equations and variables
         z_exp.insert(z_exp.end(), zb.begin(), zb.end());
         f_exp.insert(f_exp.end(), fb_exp.begin(), fb_exp.end());
       }
     }
     // Eliminate inter-dependencies in fb_exp
     vector<MX> ex;
     substitute_inplace(z_exp, f_exp, ex, false);
     // Add to the beginning of the dependent variables
     // (since the other dependent variable might depend on them)
     this->d.insert(this->d.begin(), z_exp.begin(), z_exp.end());
     this->ddef.insert(this->ddef.begin(), f_exp.begin(), f_exp.end());
     // Save new algebraic equations
     this->z = z_imp;
     this->alg = f_imp;
     // Eliminate new dependent variables from the other equations
     eliminate_d();
   }
void casadi::DaeBuilder::eliminate_d ()
Definition at line 641 of file dae_builder.cpp.
{
     // Quick return if possible
     if (this->d.empty()) return;
     // Begin by sorting the dependent parameters
     sort_d();
     // Collect all expressions to be replaced
     vector<MX> ex;
     ex.insert(ex.end(), this->ode.begin(), this->ode.end());
     ex.insert(ex.end(), this->dae.begin(), this->dae.end());
     ex.insert(ex.end(), this->alg.begin(), this->alg.end());
     ex.insert(ex.end(), this->quad.begin(), this->quad.end());
     ex.insert(ex.end(), this->ydef.begin(), this->ydef.end());
     ex.insert(ex.end(), this->init.begin(), this->init.end());
     // Substitute all at once (since they may have common subexpressions)
     substitute_inplace(this->d, this->ddef, ex);
     // Get the modified expressions
     vector<MX>::const_iterator it=ex.begin();
     for (int i=0; i<this->x.size(); ++i) this->ode[i] = *it++;
     for (int i=0; i<this->s.size(); ++i) this->dae[i] = *it++;
     for (int i=0; i<this->z.size(); ++i) this->alg[i] = *it++;
     for (int i=0; i<this->q.size(); ++i) this->quad[i] = *it++;
     for (int i=0; i<this->y.size(); ++i) this->ydef[i] = *it++;
     for (int i=0; i<this->init.size(); ++i) this->init[i] = *it++;
     casadi_assert(it==ex.end());
   }
void casadi::DaeBuilder::eliminate_quad ()
Definition at line 539 of file dae_builder.cpp.
{
     // Move all the quadratures to the list of differential states
     this->x.insert(this->x.end(), this->q.begin(), this->q.end());
     this->q.clear();
   }
DaeBuilder::DaeBuilderIn casadi::DaeBuilder::enum_in (const std::string & id) static
Import existing problem from FMI/XML
Definition at line 1447 of file dae_builder.cpp.
{
     if (id=="t") {
       return DAE_BUILDER_T;
     } else if (id=="c") {
       return DAE_BUILDER_C;
     } else if (id=="p") {
       return DAE_BUILDER_P;
     } else if (id=="d") {
       return DAE_BUILDER_D;
     } else if (id=="u") {
       return DAE_BUILDER_U;
     } else if (id=="x") {
       return DAE_BUILDER_X;
     } else if (id=="s") {
       return DAE_BUILDER_S;
     } else if (id=="sdot") {
       return DAE_BUILDER_SDOT;
     } else if (id=="z") {
       return DAE_BUILDER_Z;
     } else if (id=="q") {
       return DAE_BUILDER_Q;
     } else if (id=="w") {
       return DAE_BUILDER_W;
     } else if (id=="y") {
       return DAE_BUILDER_Y;
     } else {
       return DAE_BUILDER_NUM_IN;
     }
   }
std::vector< DaeBuilder::DaeBuilderIn > casadi::DaeBuilder::enum_in (const std::vector< std::string > & id) static
Import existing problem from FMI/XML
Definition at line 1478 of file dae_builder.cpp.
{
     std::vector<DaeBuilderIn> ret(id.size());
     for (int i=0; i<id.size(); ++i) {
       ret[i] = enum_in(id[i]);
     }
     return ret;
   }
DaeBuilder::DaeBuilderOut casadi::DaeBuilder::enum_out (const std::string & id) static
Import existing problem from FMI/XML
Definition at line 1499 of file dae_builder.cpp.
{
     if (id=="ddef") {
       return DAE_BUILDER_DDEF;
     } else if (id=="wdef") {
       return DAE_BUILDER_WDEF;
     } else if (id=="ode") {
       return DAE_BUILDER_ODE;
     } else if (id=="dae") {
       return DAE_BUILDER_DAE;
     } else if (id=="alg") {
       return DAE_BUILDER_ALG;
     } else if (id=="quad") {
       return DAE_BUILDER_QUAD;
     } else if (id=="ydef") {
       return DAE_BUILDER_YDEF;
     } else {
       return DAE_BUILDER_NUM_OUT;
     }
   }
std::vector< DaeBuilder::DaeBuilderOut > casadi::DaeBuilder::enum_out (const std::vector< std::string > & id) static
Import existing problem from FMI/XML
Definition at line 1520 of file dae_builder.cpp.
{
     std::vector<DaeBuilderOut> ret(id.size());
     for (int i=0; i<id.size(); ++i) {
       ret[i] = enum_out(id[i]);
     }
     return ret;
   }
std::string casadi::PrintableObject< DaeBuilder >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< DaeBuilder >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
double casadi::DaeBuilder::guess (const std::string & name, bool normalized = false) const
Definition at line 1373 of file dae_builder.cpp.
References casadi::Variable::guess, and casadi::Variable::nominal.
{
     const Variable& v = variable(name);
     return normalized ? v.guess / v.nominal : v.guess;
   }
std::vector< double > casadi::DaeBuilder::guess (const MX & var, bool normalized = false) const
Definition at line 1378 of file dae_builder.cpp.
{
     return attribute(&DaeBuilder::guess, var, normalized);
   }
std::vector< MX > casadi::DaeBuilder::input (DaeBuilderIn ind) const
Import existing problem from FMI/XML
Definition at line 1550 of file dae_builder.cpp.
{
     switch (ind) {
     case DAE_BUILDER_T: return vector<MX>(1, this->t);
     case DAE_BUILDER_C: return this->c;
     case DAE_BUILDER_P: return this->p;
     case DAE_BUILDER_D: return this->d;
     case DAE_BUILDER_U: return this->u;
     case DAE_BUILDER_X: return this->x;
     case DAE_BUILDER_S: return this->s;
     case DAE_BUILDER_SDOT: return this->sdot;
     case DAE_BUILDER_Z: return this->z;
     case DAE_BUILDER_Q: return this->q;
     case DAE_BUILDER_W: return this->w;
     case DAE_BUILDER_Y: return this->y;
     default: return std::vector<MX>();
     }
   }
std::vector< MX > casadi::DaeBuilder::input (std::vector< DaeBuilderIn > & ind) const
Import existing problem from FMI/XML
Definition at line 1568 of file dae_builder.cpp.
{
     vector<MX> ret(ind.size());
     for (int i=0; i<ind.size(); ++i) {
       ret[i] = vertcat(input(ind[i]));
     }
     return ret;
   }
void casadi::DaeBuilder::make_explicit ()
Definition at line 910 of file dae_builder.cpp.
{
     // Only works if there are no i
     eliminate_d();
     // Start by transforming to semi-explicit form
     make_semi_explicit();
     // Then eliminate the algebraic variables
     eliminate_alg();
     // Error if still algebraic variables
     casadi_assert_message(this->z.empty(), "Failed to eliminate algebraic variables");
   }
void casadi::DaeBuilder::make_semi_explicit ()
Definition at line 729 of file dae_builder.cpp.
{
     // Only works if there are no i
     eliminate_d();
     // Separate the algebraic variables and equations
     split_dae();
     // Quick return if there are no implicitly defined states
     if (this->s.empty()) return;
     // Write the ODE as a function of the state derivatives
     Function f("tmp", {vertcat(this->sdot)}, {vertcat(this->dae)});
     // Get the sparsity of the Jacobian which can be used to determine which
     // variable can be calculated from which other
     Sparsity sp = f.sparsity_jac();
     casadi_assert(sp.is_square());
     // BLT transformation
     vector<int> rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock;
     int nb = sp.btf(rowperm, colperm, rowblock, colblock,
                                   coarse_rowblock, coarse_colblock);
     // Resort equations and variables
     vector<MX> daenew(this->s.size()), snew(this->s.size()), sdotnew(this->s.size());
     for (int i=0; i<rowperm.size(); ++i) {
       // Permute equations
       daenew[i] = this->dae[rowperm[i]];
       // Permute variables
       snew[i] = this->s[colperm[i]];
       sdotnew[i] = this->sdot[colperm[i]];
     }
     this->dae = daenew;
     this->s = snew;
     this->sdot = sdotnew;
     // Now write the sorted ODE as a function of the state derivatives
     f = Function("tmp", {vertcat(this->sdot)}, {vertcat(this->dae)});
     // Get the Jacobian
     MX J = MX::jac(f);
     // Explicit ODE
     vector<MX> new_ode;
     // Loop over blocks
     for (int b=0; b<nb; ++b) {
       // Get variables in the block
       vector<MX> xb(this->s.begin()+colblock[b], this->s.begin()+colblock[b+1]);
       vector<MX> xdotb(this->sdot.begin()+colblock[b], this->sdot.begin()+colblock[b+1]);
       // Get equations in the block
       vector<MX> fb(this->dae.begin()+rowblock[b], this->dae.begin()+rowblock[b+1]);
       // Get local Jacobian
       MX Jb = J(Slice(rowblock[b], rowblock[b+1]), Slice(colblock[b], colblock[b+1]));
       // If Jb depends on xb, then the state derivative does not enter linearly
       // in the ODE and we cannot solve for the state derivative
       casadi_assert_message(!depends_on(Jb, vertcat(xdotb)),
                             "Cannot find an explicit expression for variable(s) " << xb);
       // Divide fb into a part which depends on vb and a part which doesn't according to
       // "fb == mul(Jb, vb) + fb_res"
       vector<MX> fb_res = substitute(fb, xdotb, vector<MX>(xdotb.size(), 0));
       // Solve for vb
       vector<MX> fb_exp = vertsplit(solve(Jb, -vertcat(fb_res)));
       // Add to explicitly determined equations and variables
       new_ode.insert(new_ode.end(), fb_exp.begin(), fb_exp.end());
     }
     // Eliminate inter-dependencies
     vector<MX> ex;
     substitute_inplace(this->sdot, new_ode, ex, false);
     // Add to explicit differential states and ODE
     this->x.insert(this->x.end(), this->s.begin(), this->s.end());
     this->ode.insert(this->ode.end(), new_ode.begin(), new_ode.end());
     this->dae.clear();
     this->s.clear();
     this->sdot.clear();
   }
double casadi::DaeBuilder::max (const std::string & name, bool normalized = false) const
Definition at line 1355 of file dae_builder.cpp.
References casadi::Variable::max, and casadi::Variable::nominal.
{
     const Variable& v = variable(name);
     return normalized ? v.max / v.nominal : v.max;
   }
std::vector< double > casadi::DaeBuilder::max (const MX & var, bool normalized = false) const
Definition at line 1360 of file dae_builder.cpp.
{
     return attribute(&DaeBuilder::max, var, normalized);
   }
double casadi::DaeBuilder::min (const std::string & name, bool normalized = false) const
Definition at line 1337 of file dae_builder.cpp.
References casadi::Variable::min, and casadi::Variable::nominal.
{
     const Variable& v = variable(name);
     return normalized ? v.min / v.nominal : v.min;
   }
std::vector< double > casadi::DaeBuilder::min (const MX & var, bool normalized = false) const
Definition at line 1342 of file dae_builder.cpp.
{
     return attribute(&DaeBuilder::min, var, normalized);
   }
std::vector< MX > casadi::DaeBuilder::multiplier (DaeBuilderOut ind) const
Import existing problem from FMI/XML
Definition at line 1597 of file dae_builder.cpp.
{
     switch (ind) {
     case DAE_BUILDER_DDEF: return this->lam_ddef;
     case DAE_BUILDER_WDEF: return this->lam_wdef;
     case DAE_BUILDER_ODE: return this->lam_ode;
     case DAE_BUILDER_DAE: return this->lam_dae;
     case DAE_BUILDER_ALG: return this->lam_alg;
     case DAE_BUILDER_QUAD: return this->lam_quad;
     case DAE_BUILDER_YDEF: return this->lam_ydef;
     default: return std::vector<MX>();
     }
   }
std::string casadi::DaeBuilder::name_in (DaeBuilderIn ind) static
Import existing problem from FMI/XML
Definition at line 1429 of file dae_builder.cpp.
{
     switch (ind) {
     case DAE_BUILDER_T: return "t";
     case DAE_BUILDER_C: return "c";
     case DAE_BUILDER_P: return "p";
     case DAE_BUILDER_D: return "d";
     case DAE_BUILDER_U: return "u";
     case DAE_BUILDER_X: return "x";
     case DAE_BUILDER_S: return "s";
     case DAE_BUILDER_SDOT: return "sdot";
     case DAE_BUILDER_Z: return "z";
     case DAE_BUILDER_Q: return "q";
     case DAE_BUILDER_W: return "w";
     case DAE_BUILDER_Y: return "y";
     default: return "";
     }
   }
std::string casadi::DaeBuilder::name_in () static
Import existing problem from FMI/XML
Definition at line 1528 of file dae_builder.cpp.
{
     stringstream ss;
     ss << "[";
     for (int i=0; i!=DAE_BUILDER_NUM_IN; ++i) {
       if (i!=0) ss << ",";
       ss << name_in(static_cast<DaeBuilderIn>(i));
     }
     ss << "]";
     return ss.str();
   }
std::string casadi::DaeBuilder::name_out (DaeBuilderOut ind) static
Import existing problem from FMI/XML
Definition at line 1486 of file dae_builder.cpp.
{
     switch (ind) {
     case DAE_BUILDER_DDEF: return "ddef";
     case DAE_BUILDER_WDEF: return "wdef";
     case DAE_BUILDER_ODE: return "ode";
     case DAE_BUILDER_DAE: return "dae";
     case DAE_BUILDER_ALG: return "alg";
     case DAE_BUILDER_QUAD: return "quad";
     case DAE_BUILDER_YDEF: return "ydef";
     default: return "";
     }
   }
std::string casadi::DaeBuilder::name_out () static
Import existing problem from FMI/XML
Definition at line 1539 of file dae_builder.cpp.
{
     stringstream ss;
     ss << "[";
     for (int i=0; i!=DAE_BUILDER_NUM_OUT; ++i) {
       if (i!=0) ss << ",";
       ss << name_out(static_cast<DaeBuilderOut>(i));
     }
     ss << "]";
     return ss.str();
   }
double casadi::DaeBuilder::nominal (const std::string & name) const
Definition at line 1258 of file dae_builder.cpp.
{
     return variable(name).nominal;
   }
std::vector< double > casadi::DaeBuilder::nominal (const MX & var) const
Definition at line 1266 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::MX::is_valid_input(), casadi::GenericMatrix< MatType >::nnz(), and casadi::MX::primitives().
{
     casadi_assert_message(var.is_column() && var.is_valid_input(),
                           "DaeBuilder::nominal: Argument must be a symbolic vector");
     std::vector<double> ret(var.nnz());
     std::vector<MX> prim = var.primitives();
     for (int i=0; i<prim.size(); ++i) {
       casadi_assert(prim[i].nnz()==1);
       ret[i] = nominal(prim.at(i).name());
     }
     return ret;
   }
MX casadi::DaeBuilder::operator() (const std::string & name) const
Definition at line 1155 of file dae_builder.cpp.
{
     return variable(name).v;
   }
std::vector< MX > casadi::DaeBuilder::output (DaeBuilderOut ind) const
Import existing problem from FMI/XML
Definition at line 1576 of file dae_builder.cpp.
{
     switch (ind) {
     case DAE_BUILDER_DDEF: return this->ddef;
     case DAE_BUILDER_WDEF: return this->wdef;
     case DAE_BUILDER_ODE: return this->ode;
     case DAE_BUILDER_DAE: return this->dae;
     case DAE_BUILDER_ALG: return this->alg;
     case DAE_BUILDER_QUAD: return this->quad;
     case DAE_BUILDER_YDEF: return this->ydef;
     default: return std::vector<MX>();
     }
   }
std::vector< MX > casadi::DaeBuilder::output (std::vector< DaeBuilderOut > & ind) const
Import existing problem from FMI/XML
Definition at line 1589 of file dae_builder.cpp.
{
     vector<MX> ret(ind.size());
     for (int i=0; i<ind.size(); ++i) {
       ret[i] = vertcat(output(ind[i]));
     }
     return ret;
   }
void casadi::DaeBuilder::parse_fmi (const std::string & filename)
Import existing problem from FMI/XML
Definition at line 60 of file dae_builder.cpp.
References casadi::ALIAS, casadi::Variable::alias, casadi::CAT_ALGEBRAIC, casadi::CAT_DEPENDENT_CONSTANT, casadi::CAT_DEPENDENT_PARAMETER, casadi::CAT_DERIVATIVE, casadi::CAT_INDEPENDENT_CONSTANT, casadi::CAT_INDEPENDENT_PARAMETER, casadi::CAT_STATE, casadi::Variable::category, casadi::Variable::causality, casadi::XmlNode::checkName(), casadi::CONSTANT, casadi::CONTINUOUS, casadi::Variable::d, casadi::DISCRETE, casadi::Variable::display_unit, casadi::Variable::free, casadi::XmlNode::getAttribute(), casadi::XmlNode::getText(), casadi::Variable::guess, casadi::XmlNode::hasChild(), casadi::INPUT, casadi::INTERNAL, casadi::Variable::max, casadi::Variable::min, casadi::XmlNode::name(), casadi::NEGATED_ALIAS, casadi::NO_ALIAS, casadi::Variable::nominal, casadi::OUTPUT, casadi::PARAMETER, casadi::XmlFile::parse(), casadi::XmlNode::readAttribute(), casadi::XmlNode::size(), casadi::Variable::start, casadi::Variable::unit, casadi::Variable::v, casadi::Variable::valueReference, and casadi::Variable::variability.
{
     // Load
     XmlFile xml_file("tinyxml");
     XmlNode document = xml_file.parse(filename);
     // **** Add model variables ****
     {
       //if (verbose) userOut() << "Adding model variables." << endl;
       // Get a reference to the ModelVariables node
       const XmlNode& modvars = document[0]["ModelVariables"];
       // Add variables
       for (int i=0; i<modvars.size(); ++i) {
         // Get a reference to the variable
         const XmlNode& vnode = modvars[i];
         // Get the attributes
         string name        = vnode.getAttribute("name");
         int valueReference;
         vnode.readAttribute("valueReference", valueReference);
         string variability = vnode.getAttribute("variability");
         string causality   = vnode.getAttribute("causality");
         string alias       = vnode.getAttribute("alias");
         // Skip to the next variable if its an alias
         if (alias.compare("alias") == 0 || alias.compare("negatedAlias") == 0)
           continue;
         // Get the name
         const XmlNode& nn = vnode["QualifiedName"];
         string qn = qualified_name(nn);
         // Add variable, if not already added
         if (varmap_.find(qn)==varmap_.end()) {
           // Create variable
           Variable var(name);
           // Value reference
           var.valueReference = valueReference;
           // Variability
           if (variability.compare("constant")==0)
             var.variability = CONSTANT;
           else if (variability.compare("parameter")==0)
             var.variability = PARAMETER;
           else if (variability.compare("discrete")==0)
             var.variability = DISCRETE;
           else if (variability.compare("continuous")==0)
             var.variability = CONTINUOUS;
           else
             throw CasadiException("Unknown variability");
           // Causality
           if (causality.compare("input")==0)
             var.causality = INPUT;
           else if (causality.compare("output")==0)
             var.causality = OUTPUT;
           else if (causality.compare("internal")==0)
             var.causality = INTERNAL;
           else
             throw CasadiException("Unknown causality");
           // Alias
           if (alias.compare("noAlias")==0)
             var.alias = NO_ALIAS;
           else if (alias.compare("alias")==0)
             var.alias = ALIAS;
           else if (alias.compare("negatedAlias")==0)
             var.alias = NEGATED_ALIAS;
           else
             throw CasadiException("Unknown alias");
           // Other properties
           if (vnode.hasChild("Real")) {
             const XmlNode& props = vnode["Real"];
             props.readAttribute("unit", var.unit, false);
             props.readAttribute("displayUnit", var.display_unit, false);
             props.readAttribute("min", var.min, false);
             props.readAttribute("max", var.max, false);
             props.readAttribute("initialGuess", var.guess, false);
             props.readAttribute("start", var.start, false);
             props.readAttribute("nominal", var.nominal, false);
             props.readAttribute("free", var.free, false);
           }
           // Variable category
           if (vnode.hasChild("VariableCategory")) {
             string cat = vnode["VariableCategory"].getText();
             if (cat.compare("derivative")==0)
               var.category = CAT_DERIVATIVE;
             else if (cat.compare("state")==0)
               var.category = CAT_STATE;
             else if (cat.compare("dependentConstant")==0)
               var.category = CAT_DEPENDENT_CONSTANT;
             else if (cat.compare("independentConstant")==0)
               var.category = CAT_INDEPENDENT_CONSTANT;
             else if (cat.compare("dependentParameter")==0)
               var.category = CAT_DEPENDENT_PARAMETER;
             else if (cat.compare("independentParameter")==0)
               var.category = CAT_INDEPENDENT_PARAMETER;
             else if (cat.compare("algebraic")==0)
               var.category = CAT_ALGEBRAIC;
             else
               throw CasadiException("Unknown variable category: " + cat);
           }
           // Add to list of variables
           add_variable(qn, var);
           // Sort expression
           switch (var.category) {
           case CAT_DERIVATIVE:
             // Skip - meta information about time derivatives is
             //        kept together with its parent variable
             break;
           case CAT_STATE:
             this->s.push_back(var.v);
             this->sdot.push_back(var.d);
             break;
           case CAT_DEPENDENT_CONSTANT:
             // Skip
             break;
           case CAT_INDEPENDENT_CONSTANT:
             // Skip
             break;
           case CAT_DEPENDENT_PARAMETER:
             // Skip
             break;
           case CAT_INDEPENDENT_PARAMETER:
             if (var.free) {
               this->p.push_back(var.v);
             } else {
               // Skip
             }
             break;
           case CAT_ALGEBRAIC:
             if (var.causality == INTERNAL) {
               this->s.push_back(var.v);
               this->sdot.push_back(var.d);
             } else if (var.causality == INPUT) {
               this->u.push_back(var.v);
             }
             break;
           default:
             casadi_error("Unknown category");
           }
         }
       }
     }
     // **** Add binding equations ****
     {
       //if (verbose) userOut() << "Adding binding equations." << endl;
       // Get a reference to the BindingEquations node
       const XmlNode& bindeqs = document[0]["equ:BindingEquations"];
       for (int i=0; i<bindeqs.size(); ++i) {
         const XmlNode& beq = bindeqs[i];
         // Get the variable and binding expression
         Variable& var = read_variable(beq[0]);
         MX bexpr = read_expr(beq[1][0]);
         this->d.push_back(var.v);
         this->ddef.push_back(bexpr);
       }
     }
     // **** Add dynamic equations ****
     {
       // Get a reference to the DynamicEquations node
       const XmlNode& dyneqs = document[0]["equ:DynamicEquations"];
       // Add equations
       for (int i=0; i<dyneqs.size(); ++i) {
         // Get a reference to the variable
         const XmlNode& dnode = dyneqs[i];
         // Add the differential equation
         MX de_new = read_expr(dnode[0]);
         this->dae.push_back(de_new);
       }
     }
     // **** Add initial equations ****
     {
       // Get a reference to the DynamicEquations node
       const XmlNode& initeqs = document[0]["equ:InitialEquations"];
       // Add equations
       for (int i=0; i<initeqs.size(); ++i) {
         // Get a reference to the node
         const XmlNode& inode = initeqs[i];
         // Add the differential equations
         for (int i=0; i<inode.size(); ++i) {
           this->init.push_back(read_expr(inode[i]));
         }
       }
     }
     // **** Add optimization ****
     if (document[0].hasChild("opt:Optimization")) {
       // Get a reference to the DynamicEquations node
       const XmlNode& opts = document[0]["opt:Optimization"];
       for (int i=0; i<opts.size(); ++i) {
         // Get a reference to the node
         const XmlNode& onode = opts[i];
         // Get the type
         if (onode.checkName("opt:ObjectiveFunction")) { // mayer term
           try {
             // Add components
             for (int i=0; i<onode.size(); ++i) {
               const XmlNode& var = onode[i];
               // If string literal, ignore
               if (var.checkName("exp:StringLiteral"))
                 continue;
               // Read expression
               MX v = read_expr(var);
               // Treat as an output
               add_y(v, "mterm");
             }
           } catch(exception& ex) {
             throw CasadiException(std::string("addObjectiveFunction failed: ") + ex.what());
           }
         } else if (onode.checkName("opt:IntegrandObjectiveFunction")) {
           try {
             for (int i=0; i<onode.size(); ++i) {
               const XmlNode& var = onode[i];
               // If string literal, ignore
               if (var.checkName("exp:StringLiteral")) continue;
               // Read expression
               MX v = read_expr(var);
               // Treat as a quadrature state
               add_q("lterm");
               add_quad(v, "lterm_rhs");
             }
           } catch(exception& ex) {
             throw CasadiException(std::string("addIntegrandObjectiveFunction failed: ")
                                   + ex.what());
           }
         } else if (onode.checkName("opt:IntervalStartTime")) {
           // Ignore, treated above
         } else if (onode.checkName("opt:IntervalFinalTime")) {
           // Ignore, treated above
         } else if (onode.checkName("opt:TimePoints")) {
           // Ignore, treated above
         } else if (onode.checkName("opt:PointConstraints")) {
           casadi_warning("opt:PointConstraints not supported, ignored");
         } else if (onode.checkName("opt:Constraints")) {
           casadi_warning("opt:Constraints not supported, ignored");
         } else if (onode.checkName("opt:PathConstraints")) {
           casadi_warning("opt:PointConstraints not supported, ignored");
         } else {
           casadi_warning("DaeBuilder::addOptimization: Unknown node " << onode.name());
         }
       }
     }
     // Make sure that the dimensions are consistent at this point
     casadi_assert_warning(this->s.size()==this->dae.size(),
                           "The number of differential-algebraic equations does not match "
                           "the number of implicitly defined states.");
     casadi_assert_warning(this->z.size()==this->alg.size(),
                           "The number of algebraic equations (equations not involving "
                           "differentiated variables) does not match the number of "
                           "algebraic variables.");
   }
void casadi::DaeBuilder::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 462 of file dae_builder.cpp.
References casadi::repr(), and casadi::str().
{
     // Assert correctness
     sanity_check();
     // Print dimensions
     repr(stream);
     // Print the variables
     stream << "Variables" << endl;
     stream << "{" << endl;
     stream << "  t = " << str(this->t) << endl;
     if (!this->s.empty()) stream << "  s = " << str(this->s) << endl;
     if (!this->x.empty()) stream << "  x = " << str(this->x) << endl;
     if (!this->z.empty()) stream << "  z =  " << str(this->z) << endl;
     if (!this->q.empty()) stream << "  q =  " << str(this->q) << endl;
     if (!this->y.empty()) stream << "  y =  " << str(this->y) << endl;
     if (!this->p.empty()) stream << "  p =  " << str(this->p) << endl;
     if (!this->d.empty()) stream << "  d =  " << str(this->d) << endl;
     if (!this->u.empty()) stream << "  u =  " << str(this->u) << endl;
     stream << "}" << endl;
     if (!this->d.empty()) {
       stream << "Dependent parameters" << endl;
       for (int i=0; i<this->d.size(); ++i)
         stream << str(this->d[i]) << " == " << str(this->ddef[i]) << endl;
       stream << endl;
     }
     if (!this->dae.empty()) {
       stream << "Fully-implicit differential-algebraic equations" << endl;
       for (int k=0; k<this->dae.size(); ++k) {
         stream << "0 == " << this->dae[k] << endl;
       }
       stream << endl;
     }
     if (!this->x.empty()) {
       stream << "Differential equations" << endl;
       for (int k=0; k<this->x.size(); ++k) {
         stream << str(der(this->x[k])) << " == " << str(this->ode[k]) << endl;
       }
       stream << endl;
     }
     if (!this->alg.empty()) {
       stream << "Algebraic equations" << endl;
       for (int k=0; k<this->z.size(); ++k) {
         stream << "0 == " << str(this->alg[k]) << endl;
       }
       stream << endl;
     }
     if (!this->q.empty()) {
       stream << "Quadrature equations" << endl;
       for (int k=0; k<this->q.size(); ++k) {
         stream << str(der(this->q[k])) << " == " << str(this->quad[k]) << endl;
       }
       stream << endl;
     }
     if (!this->init.empty()) {
       stream << "Initial equations" << endl;
       for (int k=0; k<this->init.size(); ++k) {
         stream << "0 == " << str(this->init[k]) << endl;
       }
       stream << endl;
     }
     if (!this->y.empty()) {
       stream << "Output variables" << endl;
       for (int i=0; i<this->y.size(); ++i)
         stream << str(this->y[i]) << " == " << str(this->ydef[i]) << endl;
       stream << endl;
     }
     if (trailing_newline) stream << endl;
   }
std::string casadi::DaeBuilder::qualified_name (const XmlNode & nn) static protected
Definition at line 1132 of file dae_builder.cpp.
References casadi::XmlNode::getAttribute(), casadi::XmlNode::getText(), and casadi::XmlNode::size().
{
     // Stringstream to assemble name
     stringstream qn;
     for (int i=0; i<nn.size(); ++i) {
       // Add a dot
       if (i!=0) qn << ".";
       // Get the name part
       qn << nn[i].getAttribute("name");
       // Get the index, if any
       if (nn[i].size()>0) {
         int ind;
         nn[i]["exp:ArraySubscripts"]["exp:IndexExpression"]["exp:IntegerLiteral"].getText(ind);
         qn << "[" << ind << "]";
       }
     }
     // Return the name
     return qn.str();
   }
MX casadi::DaeBuilder::read_expr (const XmlNode & odenode) protected
Definition at line 352 of file dae_builder.cpp.
References casadi::Variable::d, casadi::fmax(), casadi::fmin(), casadi::XmlNode::getText(), casadi::if_else(), casadi::XmlNode::name(), and casadi::XmlNode::size().
{
     const string& fullname = node.name();
     if (fullname.find("exp:")== string::npos) {
       casadi_error("DaeBuilder::read_expr: unknown - expression is supposed to "
                    "start with 'exp:' , got " << fullname);
     }
     // Chop the 'exp:'
     string name = fullname.substr(4);
     // The switch below is alphabetical, and can be thus made more efficient,
     // for example by using a switch statement of the first three letters,
     // if it would ever become a bottleneck
     if (name.compare("Add")==0) {
       return read_expr(node[0]) + read_expr(node[1]);
     } else if (name.compare("Acos")==0) {
       return acos(read_expr(node[0]));
     } else if (name.compare("Asin")==0) {
       return asin(read_expr(node[0]));
     } else if (name.compare("Atan")==0) {
       return atan(read_expr(node[0]));
     } else if (name.compare("Cos")==0) {
       return cos(read_expr(node[0]));
     } else if (name.compare("Der")==0) {
       const Variable& v = read_variable(node[0]);
       return v.d;
     } else if (name.compare("Div")==0) {
       return read_expr(node[0]) / read_expr(node[1]);
     } else if (name.compare("Exp")==0) {
       return exp(read_expr(node[0]));
     } else if (name.compare("Identifier")==0) {
       return read_variable(node).v;
     } else if (name.compare("IntegerLiteral")==0) {
       int val;
       node.getText(val);
       return val;
     } else if (name.compare("Instant")==0) {
       double val;
       node.getText(val);
       return val;
     } else if (name.compare("Log")==0) {
       return log(read_expr(node[0]));
     } else if (name.compare("LogLeq")==0) { // Logical less than equal
       return read_expr(node[0]) <= read_expr(node[1]);
     } else if (name.compare("LogGeq")==0) { // Logical greater than equal
       return read_expr(node[0]) >= read_expr(node[1]);
     } else if (name.compare("LogLt")==0) { // Logical less than
       return read_expr(node[0]) < read_expr(node[1]);
     } else if (name.compare("LogGt")==0) { // Logical greater than
       return read_expr(node[0]) > read_expr(node[1]);
     } else if (name.compare("Max")==0) {
       return fmax(read_expr(node[0]), read_expr(node[1]));
     } else if (name.compare("Min")==0) {
       return fmin(read_expr(node[0]), read_expr(node[1]));
     } else if (name.compare("Mul")==0) { // Multiplication
       return read_expr(node[0]) * read_expr(node[1]);
     } else if (name.compare("Neg")==0) {
       return -read_expr(node[0]);
     } else if (name.compare("NoEvent")==0) {
       // NOTE: This is a workaround, we assume that whenever NoEvent occurs,
       // what is meant is a switch
       int n = node.size();
       // Default-expression
       MX ex = read_expr(node[n-1]);
       // Evaluate ifs
       for (int i=n-3; i>=0; i -= 2) ex = if_else(read_expr(node[i]), read_expr(node[i+1]), ex);
       return ex;
     } else if (name.compare("Pow")==0) {
       return pow(read_expr(node[0]), read_expr(node[1]));
     } else if (name.compare("RealLiteral")==0) {
       double val;
       node.getText(val);
       return val;
     } else if (name.compare("Sin")==0) {
       return sin(read_expr(node[0]));
     } else if (name.compare("Sqrt")==0) {
       return sqrt(read_expr(node[0]));
     } else if (name.compare("StringLiteral")==0) {
       throw CasadiException(node.getText());
     } else if (name.compare("Sub")==0) {
       return read_expr(node[0]) - read_expr(node[1]);
     } else if (name.compare("Tan")==0) {
       return tan(read_expr(node[0]));
     } else if (name.compare("Time")==0) {
       return t;
     } else if (name.compare("TimedVariable")==0) {
       return read_variable(node[0]).v;
     }
     // throw error if reached this point
     throw CasadiException(string("DaeBuilder::read_expr: Unknown node: ") + name);
   }
Variable & casadi::DaeBuilder::read_variable (const XmlNode & node) protected
Definition at line 344 of file dae_builder.cpp.
{
     // Qualified name
     string qn = qualified_name(node);
     // Find and return the variable
     return variable(qn);
   }
void casadi::DaeBuilder::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 449 of file dae_builder.cpp.
{
     stream << "DAE("
            << "#s = " << this->s.size() << ", "
            << "#x = " << this->x.size() << ", "
            << "#z = " << this->z.size() << ", "
            << "#q = " << this->q.size() << ", "
            << "#y = " << this->y.size() << ", "
            << "#p = " << this->p.size() << ", "
            << "#d = " << this->d.size() << ", "
            << "#u = " << this->u.size() << ")";
     if (trailing_newline) stream << endl;
   }
void casadi::DaeBuilder::sanity_check () const
Definition at line 1058 of file dae_builder.cpp.
{
     // Time
     casadi_assert_message(this->t.is_symbolic(), "Non-symbolic time t");
     casadi_assert_message(this->t.is_scalar(), "Non-scalar time t");
     // Differential states
     casadi_assert_message(this->x.size()==this->ode.size(),
                           "x and ode have different lengths");
     for (int i=0; i<this->x.size(); ++i) {
       casadi_assert_message(this->x[i].size()==this->ode[i].size(),
                             "ode has wrong dimensions");
       casadi_assert_message(this->x[i].is_symbolic(), "Non-symbolic state x");
     }
     // DAE
     casadi_assert_message(this->s.size()==this->sdot.size(),
                           "s and sdot have different lengths");
     casadi_assert_message(this->s.size()==this->dae.size(),
                           "s and dae have different lengths");
     for (int i=0; i<this->s.size(); ++i) {
       casadi_assert_message(this->s[i].is_symbolic(), "Non-symbolic state s");
       casadi_assert_message(this->s[i].size()==this->sdot[i].size(),
                             "sdot has wrong dimensions");
       casadi_assert_message(this->s[i].size()==this->dae[i].size(),
                             "dae has wrong dimensions");
     }
     // Algebraic variables/equations
     casadi_assert_message(this->z.size()==this->alg.size(),
                           "z and alg have different lengths");
     for (int i=0; i<this->z.size(); ++i) {
       casadi_assert_message(this->z[i].is_symbolic(), "Non-symbolic algebraic variable z");
       casadi_assert_message(this->z[i].size()==this->alg[i].size(),
                             "alg has wrong dimensions");
     }
     // Quadrature states/equations
     casadi_assert_message(this->q.size()==this->quad.size(),
                           "q and quad have different lengths");
     for (int i=0; i<this->q.size(); ++i) {
       casadi_assert_message(this->q[i].is_symbolic(), "Non-symbolic quadrature state q");
       casadi_assert_message(this->q[i].size()==this->quad[i].size(),
                             "quad has wrong dimensions");
     }
     // Intermediate variables
     casadi_assert_message(this->d.size()==this->ddef.size(),
                           "d and ddef have different lengths");
     for (int i=0; i<this->d.size(); ++i) {
       casadi_assert_message(this->d[i].is_symbolic(), "Non-symbolic dependent parameter d");
       casadi_assert_message(this->d[i].size()==this->ddef[i].size(),
                             "ddef has wrong dimensions");
     }
     // Output equations
     casadi_assert_message(this->y.size()==this->ydef.size(),
                           "y and ydef have different lengths");
     for (int i=0; i<this->y.size(); ++i) {
       casadi_assert_message(this->y[i].is_symbolic(), "Non-symbolic output y");
       casadi_assert_message(this->y[i].size()==this->ydef[i].size(),
                             "ydef has wrong dimensions");
     }
     // Control
     for (int i=0; i<this->u.size(); ++i) {
       casadi_assert_message(this->u[i].is_symbolic(), "Non-symbolic control u");
     }
     // Parameter
     for (int i=0; i<this->p.size(); ++i) {
       casadi_assert_message(this->p[i].is_symbolic(), "Non-symbolic parameter p");
     }
   }
void casadi::DaeBuilder::scale_equations ()
Definition at line 671 of file dae_builder.cpp.
{
     casadi_error("DaeBuilder::scale_equations broken");
   }
void casadi::DaeBuilder::scale_variables ()
Definition at line 545 of file dae_builder.cpp.
References casadi::Variable::d, casadi::Variable::derivative_start, casadi::Variable::guess, casadi::Variable::max, casadi::Variable::min, casadi::Variable::nominal, casadi::Variable::start, and casadi::Variable::v.
{
     // Assert correctness
     sanity_check();
     // Gather variables and expressions to replace
     vector<MX> v_id, v_rep;
     for (VarMap::iterator it=varmap_.begin(); it!=varmap_.end(); ++it) {
       if (it->second.nominal!=1) {
         Variable& v=it->second;
         casadi_assert(v.nominal!=0);
         v.min /= v.nominal;
         v.max /= v.nominal;
         v.start /= v.nominal;
         v.derivative_start /= v.nominal;
         v.guess /= v.nominal;
         v_id.push_back(v.v);
         v_id.push_back(v.d);
         v_rep.push_back(v.v * v.nominal);
         v_rep.push_back(v.d * v.nominal);
       }
     }
     // Quick return if no expressions to substitute
     if (v_id.empty()) return;
     // Collect all expressions to be replaced
     vector<MX> ex;
     ex.insert(ex.end(), this->ode.begin(), this->ode.end());
     ex.insert(ex.end(), this->dae.begin(), this->dae.end());
     ex.insert(ex.end(), this->alg.begin(), this->alg.end());
     ex.insert(ex.end(), this->quad.begin(), this->quad.end());
     ex.insert(ex.end(), this->ddef.begin(), this->ddef.end());
     ex.insert(ex.end(), this->ydef.begin(), this->ydef.end());
     ex.insert(ex.end(), this->init.begin(), this->init.end());
     // Substitute all at once (more efficient since they may have common subexpressions)
     ex = substitute(ex, v_id, v_rep);
     // Get the modified expressions
     vector<MX>::const_iterator it=ex.begin();
     for (int i=0; i<this->x.size(); ++i) this->ode[i] = *it++ / nominal(this->x[i]);
     for (int i=0; i<this->s.size(); ++i) this->dae[i] = *it++;
     for (int i=0; i<this->z.size(); ++i) this->alg[i] = *it++;
     for (int i=0; i<this->q.size(); ++i) this->quad[i] = *it++ / nominal(this->q[i]);
     for (int i=0; i<this->d.size(); ++i) this->ddef[i] = *it++ / nominal(this->d[i]);
     for (int i=0; i<this->y.size(); ++i) this->ydef[i] = *it++ / nominal(this->y[i]);
     for (int i=0; i<this->init.size(); ++i) this->init[i] = *it++;
     casadi_assert(it==ex.end());
     // Nominal value is 1 after scaling
     for (VarMap::iterator it=varmap_.begin(); it!=varmap_.end(); ++it) {
       it->second.nominal=1;
     }
   }
void casadi::DaeBuilder::set_attribute (setAtt f, const MX & var, const std::vector< double > & val, bool normalized) protected
Definition at line 1313 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::MX::is_valid_input(), casadi::GenericMatrix< MatType >::nnz(), and casadi::MX::primitives().
{
     casadi_assert_message(var.is_column() && var.is_valid_input(),
                           "DaeBuilder::set_attribute: Argument must be a symbolic vector");
     casadi_assert_message(var.nnz()==val.size(), "DaeBuilder::set_attribute: Dimension mismatch");
     std::vector<MX> prim = var.primitives();
     for (int i=0; i<prim.size(); ++i) {
       casadi_assert(prim[i].nnz()==1);
       (this->*f)(prim[i].name(), val[i], normalized);
     }
   }
void casadi::DaeBuilder::set_attribute (setAttS f, const MX & var, const MX & val) protected
Definition at line 1325 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::MX::is_valid_input(), casadi::MX::primitives(), and casadi::MX::sparsity().
{
     casadi_assert_message(var.is_column() && var.is_valid_input(),
                           "DaeBuilder::set_attribute: Argument must be a symbolic vector");
     casadi_assert_message(var.sparsity()==val.sparsity(),
                           "DaeBuilder::set_attribute: Sparsity mismatch");
     std::vector<MX> prim = var.primitives();
     for (int i=0; i<prim.size(); ++i) {
       casadi_assert(prim[i].nnz()==1);
       (this->*f)(var[i].name(), val[i]);
     }
   }
void casadi::DaeBuilder::set_derivative_start (const std::string & name, double val, bool normalized = false)
Definition at line 1419 of file dae_builder.cpp.
References casadi::Variable::derivative_start, and casadi::Variable::nominal.
{
     Variable& v = variable(name);
     v.derivative_start = normalized ? val*v.nominal : val;
   }
void casadi::DaeBuilder::set_derivative_start (const MX & var, const std::vector< double > & val, bool normalized = false)
Definition at line 1424 of file dae_builder.cpp.
{
     set_attribute(&DaeBuilder::set_derivative_start, var, val, normalized);
   }
void casadi::DaeBuilder::set_guess (const std::string & name, double val, bool normalized = false)
Definition at line 1382 of file dae_builder.cpp.
References casadi::Variable::guess, and casadi::Variable::nominal.
{
     Variable& v = variable(name);
     v.guess = normalized ? val*v.nominal : val;
   }
void casadi::DaeBuilder::set_guess (const MX & var, const std::vector< double > & val, bool normalized = false)
Definition at line 1387 of file dae_builder.cpp.
{
     set_attribute(&DaeBuilder::set_guess, var, val, normalized);
   }
void casadi::DaeBuilder::set_max (const std::string & name, double val, bool normalized = false)
Definition at line 1364 of file dae_builder.cpp.
References casadi::Variable::max, and casadi::Variable::nominal.
{
     Variable& v = variable(name);
     v.max = normalized ? val*v.nominal : val;
   }
void casadi::DaeBuilder::set_max (const MX & var, const std::vector< double > & val, bool normalized = false)
Definition at line 1369 of file dae_builder.cpp.
{
     set_attribute(&DaeBuilder::set_max, var, val, normalized);
   }
void casadi::DaeBuilder::set_min (const std::string & name, double val, bool normalized = false)
Definition at line 1346 of file dae_builder.cpp.
References casadi::Variable::min, and casadi::Variable::nominal.
{
     Variable& v = variable(name);
     v.min = normalized ? val*v.nominal : val;
   }
void casadi::DaeBuilder::set_min (const MX & var, const std::vector< double > & val, bool normalized = false)
Definition at line 1351 of file dae_builder.cpp.
{
     set_attribute(&DaeBuilder::set_min, var, val, normalized);
   }
void casadi::DaeBuilder::set_nominal (const std::string & name, double val)
Definition at line 1262 of file dae_builder.cpp.
{
     variable(name).nominal = val;
   }
void casadi::DaeBuilder::set_nominal (const MX & var, const std::vector< double > & val)
Definition at line 1278 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::MX::is_valid_input(), casadi::GenericMatrix< MatType >::nnz(), and casadi::MX::primitives().
{
     casadi_assert_message(var.is_column() && var.is_valid_input(),
                           "DaeBuilder::nominal: Argument must be a symbolic vector");
     casadi_assert_message(var.nnz()==var.nnz(), "DaeBuilder::nominal: Dimension mismatch");
     std::vector<MX> prim = var.primitives();
     for (int i=0; i<prim.size(); ++i) {
       casadi_assert(prim[i].nnz()==1);
       set_nominal(prim.at(i).name(), val.at(i));
     }
   }
void casadi::DaeBuilder::set_start (const std::string & name, double val, bool normalized = false)
Definition at line 1401 of file dae_builder.cpp.
References casadi::Variable::nominal, and casadi::Variable::start.
{
     Variable& v = variable(name);
     v.start = normalized ? val*v.nominal : val;
   }
void casadi::DaeBuilder::set_start (const MX & var, const std::vector< double > & val, bool normalized = false)
Definition at line 1406 of file dae_builder.cpp.
{
     set_attribute(&DaeBuilder::set_start, var, val, normalized);
   }
void casadi::DaeBuilder::set_unit (const std::string & name, const std::string & val)
Definition at line 1254 of file dae_builder.cpp.
{
     variable(name).unit = val;
   }
void casadi::DaeBuilder::sort_alg ()
Definition at line 703 of file dae_builder.cpp.
{
     // Quick return if no algebraic states
     if (this->z.empty()) return;
     // Find out which algebraic equation depends on which algebraic state
     Function f("tmp", {vertcat(this->z)}, {vertcat(this->alg)});
     Sparsity sp = f.sparsity_jac();
     casadi_assert(sp.is_square());
     // BLT transformation
     vector<int> rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock;
     sp.btf(rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock);
     // Resort equations and variables
     vector<MX> algnew(this->z.size()), znew(this->z.size());
     for (int i=0; i<rowperm.size(); ++i) {
       // Permute equations
       algnew[i] = this->alg[rowperm[i]];
       // Permute variables
       znew[i] = this->z[colperm[i]];
     }
     this->alg = algnew;
     this->z = znew;
   }
void casadi::DaeBuilder::sort_d ()
Definition at line 600 of file dae_builder.cpp.
{
     // Quick return if no intermediates
     if (this->d.empty()) return;
     // Find out which intermediates depends on which other
     Function f("tmp", {vertcat(this->d)}, {vertcat(this->d) - vertcat(this->ddef)});
     Sparsity sp = f.sparsity_jac();
     casadi_assert(sp.is_square());
     // BLT transformation
     vector<int> rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock;
     sp.btf(rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock);
     // Resort equations and variables
     vector<MX> ddefnew(this->d.size()), dnew(this->d.size());
     for (int i=0; i<colperm.size(); ++i) {
       // Permute equations
       ddefnew[i] = this->ddef[colperm[i]];
       // Permute variables
       dnew[i] = this->d[colperm[i]];
     }
     this->ddef = ddefnew;
     this->d = dnew;
   }
void casadi::DaeBuilder::sort_dae ()
Definition at line 675 of file dae_builder.cpp.
{
     // Quick return if no differential states
     if (this->x.empty()) return;
     // Find out which differential equation depends on which differential state
     Function f("tmp", {vertcat(this->sdot)}, {vertcat(this->dae)});
     Sparsity sp = f.sparsity_jac();
     casadi_assert(sp.is_square());
     // BLT transformation
     vector<int> rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock;
     sp.btf(rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock);
     // Resort equations and variables
     vector<MX> daenew(this->s.size()), snew(this->s.size()), sdotnew(this->s.size());
     for (int i=0; i<rowperm.size(); ++i) {
       // Permute equations
       daenew[i] = this->dae[rowperm[i]];
       // Permute variables
       snew[i] = this->s[colperm[i]];
       sdotnew[i] = this->sdot[colperm[i]];
     }
     this->dae = daenew;
     this->s = snew;
     this->sdot = sdotnew;
   }
void casadi::DaeBuilder::split_d ()
Definition at line 626 of file dae_builder.cpp.
{
     // Quick return if no intermediates
     if (this->d.empty()) return;
     // Begin by sorting the dependent parameters
     sort_d();
     // Sort the equations by causality
     vector<MX> ex;
     substitute_inplace(this->d, this->ddef, ex);
     // Make sure that the interdependencies have been properly eliminated
     casadi_assert(!depends_on(vertcat(this->ddef), vertcat(this->d)));
   }
void casadi::DaeBuilder::split_dae ()
Definition at line 1172 of file dae_builder.cpp.
References casadi::get_ptr(), and casadi::Function::nnz_in().
{
     // Only works if there are no d
     eliminate_d();
     // Quick return if no s
     if (this->s.empty()) return;
     // We investigate the interdependencies in sdot -> dae
     Function f("f", {vertcat(this->sdot)}, {vertcat(this->dae)});
     // Number of s
     int ns = f.nnz_in(0);
     casadi_assert(f.nnz_out(0)==ns);
     // Input/output buffers
     vector<bvec_t> f_sdot(ns, 1);
     vector<bvec_t> f_dae(ns, 0);
     // Propagate to f_dae
     f({get_ptr(f_sdot)}, {get_ptr(f_dae)});
     // Get the new differential and algebraic equations
     vector<MX> new_dae, new_alg;
     for (int i=0; i<ns; ++i) {
       if (f_dae[i]==bvec_t(1)) {
         new_dae.push_back(this->dae[i]);
       } else {
         casadi_assert(f_dae[i]==bvec_t(0));
         new_alg.push_back(this->dae[i]);
       }
     }
     // Seed all outputs
     std::fill(f_dae.begin(), f_dae.end(), 1);
     // Propagate to f_sdot
     std::fill(f_sdot.begin(), f_sdot.end(), 0);
     f.rev({get_ptr(f_sdot)}, {get_ptr(f_dae)});
     // Get the new algebraic variables and new states
     vector<MX> new_s, new_sdot, new_z;
     for (int i=0; i<ns; ++i) {
       if (f_sdot[i]==bvec_t(1)) {
         new_s.push_back(this->s[i]);
         new_sdot.push_back(this->sdot[i]);
       } else {
         casadi_assert(f_sdot[i]==bvec_t(0));
         new_z.push_back(this->s[i]);
       }
     }
     // Make sure split was successful
     casadi_assert(new_dae.size()==new_s.size());
     // Divide up the s and dae
     this->dae = new_dae;
     this->s = new_s;
     this->sdot = new_sdot;
     this->alg.insert(this->alg.end(), new_alg.begin(), new_alg.end());
     this->z.insert(this->z.end(), new_z.begin(), new_z.end());
   }
double casadi::DaeBuilder::start (const std::string & name, bool normalized = false) const
Definition at line 1392 of file dae_builder.cpp.
References casadi::Variable::nominal, and casadi::Variable::start.
{
     const Variable& v = variable(name);
     return normalized ? v.start / v.nominal : v.start;
   }
std::vector< double > casadi::DaeBuilder::start (const MX & var, bool normalized = false) const
Definition at line 1397 of file dae_builder.cpp.
{
     return attribute(&DaeBuilder::start, var, normalized);
   }
std::string casadi::DaeBuilder::unit (const std::string & name) const
Definition at line 1234 of file dae_builder.cpp.
{
     return variable(name).unit;
   }
std::string casadi::DaeBuilder::unit (const MX & var) const
Definition at line 1238 of file dae_builder.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_empty(), casadi::MX::is_valid_input(), and casadi::MX::primitives().
{
     casadi_assert_message(!var.is_column() && var.is_valid_input(),
                           "DaeBuilder::unit: Argument must be a symbolic vector");
     if (var.is_empty()) {
       return "n/a";
     } else {
       std::vector<MX> prim = var.primitives();
       string ret = unit(prim.at(0).name());
       for (int i=1; i<prim.size(); ++i) {
         casadi_assert_message(ret == unit(prim.at(i).name()),
                               "DaeBuilder::unit: Argument has mixed units");
       }
       return ret;
     }
   }
Variable & casadi::DaeBuilder::variable (const std::string & name)
Access a variable by name
Definition at line 928 of file dae_builder.cpp.
{
     // Find the variable
     VarMap::iterator it = varmap_.find(name);
     if (it==varmap_.end()) {
       casadi_error("No such variable: \"" << name << "\".");
     }
     // Return the variable
     return it->second;
   }
const Variable & casadi::DaeBuilder::variable (const std::string & name) const
Access a variable by name
Definition at line 924 of file dae_builder.cpp.
{
     return const_cast<DaeBuilder*>(this)->variable(name);
   }
Member Data Documentation
std::vector<MX> casadi::DaeBuilder::alg
Definition at line 102 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::c
Definition at line 131 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::cdef
Definition at line 131 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::d
Definition at line 136 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::dae
Definition at line 96 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::ddef
Definition at line 136 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::init
Definition at line 143 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::lam_alg
Definition at line 102 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::lam_dae
Definition at line 96 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::lam_ddef
Definition at line 136 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::lam_ode
Definition at line 91 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::lam_quad
Definition at line 107 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::lam_wdef
Definition at line 112 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::lam_ydef
Definition at line 116 of file dae_builder.hpp.
std::map<std::string, MX> casadi::DaeBuilder::lin_comb_ protected
Definition at line 441 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::ode
Definition at line 91 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::p
Definition at line 128 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::q
Definition at line 107 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::quad
Definition at line 107 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::s
Definition at line 96 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::sdot
Definition at line 96 of file dae_builder.hpp.
MX casadi::DaeBuilder::t
Definition at line 87 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::u
Definition at line 122 of file dae_builder.hpp.
VarMap casadi::DaeBuilder::varmap_ protected
Definition at line 438 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::w
Definition at line 112 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::wdef
Definition at line 112 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::x
Definition at line 91 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::y
Definition at line 116 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::ydef
Definition at line 116 of file dae_builder.hpp.
std::vector<MX> casadi::DaeBuilder::z
Definition at line 102 of file dae_builder.hpp.
The documentation for this class was generated from the following files:
dae_builder.hpp
dae_builder.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge