CasADi: casadi::SparsityInterface< MatType > Class Template Reference
casadi::SparsityInterface< MatType > Class Template Reference
Sparsity interface class.
#include <sparsity_interface.hpp>
Detailed Description
template<typename MatType>
class casadi::SparsityInterface< MatType >
This is a common base class for GenericMatrix (i.e. MX and Matrix<>) and Sparsity, introducing a uniform syntax and implementing common functionality using the curiously recurring template pattern (CRTP) idiom.
Author
Joel Andersson
Date
2014
Definition at line 47 of file sparsity_interface.hpp.
Static Public Member Functions
static std::vector
< std::vector< MatType > > blocksplit (const MatType &x, const std::vector< int > &vert_offset, const std::vector< int > &horz_offset)
static std::vector
< std::vector< MatType > > blocksplit (const MatType &x, int vert_incr, int horz_incr)
static MatType veccat (const std::vector< MatType > &x)
static MatType vec (const MatType &x)
static MatType repmat (const MatType &x, int n, int m=1)
static std::vector< int > offset (const std::vector< MatType > &v, bool vert=true)
static std::vector< MatType > diagsplit (const MatType &x, const std::vector< int > &output_offset)
static std::vector< MatType > diagsplit (const MatType &x, int incr)
static std::vector< MatType > diagsplit (const MatType &x, int incr1, int incr2)
static MatType mtimes (const std::vector< MatType > &args)
static std::vector< MatType > horzsplit (const MatType &x, int incr)
static std::vector< MatType > vertsplit (const MatType &x, int incr)
static MatType repmat (const MatType &A, const std::pair< int, int > &rc)
Protected Member Functions
const MatType & self () const
MatType & self ()
Friends
std::vector< MatType > make_vector (const std::map< std::string, MatType > &m, const std::vector< std::string > &s)
std::vector< std::vector
< MatType > > make_vector (const std::map< std::string, std::vector< MatType > > &m, const std::vector< std::string > &s)
std::vector< MatType > make_vector (const std::pair< std::map< std::string, MatType >, std::vector< std::string > > &ms)
std::vector< std::vector
< MatType > > make_vector (const std::pair< std::map< std::string, std::vector< MatType > >, std::vector< std::string > > &ms)
template<typename T0 >
void assign_map (const std::string &n0, T0 &x0, const std::map< std::string, MatType > &x)
template<typename T0 , typename T1 >
void assign_map (const std::string &n0, T0 &x0, const std::string &n1, T0 &x1, const std::vector< MatType > &x)
template<typename T0 , typename T1 , typename T2 >
void assign_map (const std::string &n0, T0 &x0, const std::string &n1, T0 &x1, const std::string &n2, T0 &x2, const std::vector< MatType > &x)
template<typename T0 , typename T1 , typename T2 , typename T3 >
void assign_map (const std::string &n0, T0 &x0, const std::string &n1, T0 &x1, const std::string &n2, T0 &x2, const std::string &n3, T0 &x3, const std::vector< MatType > &x)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 >
void assign_map (const std::string &n0, T0 &x0, const std::string &n1, T0 &x1, const std::string &n2, T0 &x2, const std::string &n3, T0 &x3, const std::string &n4, T0 &x4, const std::vector< MatType > &x)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
void assign_map (const std::string &n0, T0 &x0, const std::string &n1, T0 &x1, const std::string &n2, T0 &x2, const std::string &n3, T0 &x3, const std::string &n4, T0 &x4, const std::string &n5, T0 &x5, const std::vector< MatType > &x)
MatType horzcat (const std::vector< MatType > &v)
Concatenate a list of matrices horizontally Alternative terminology: horizontal stack, hstack, horizontal append, [a b].
MatType vertcat (const std::vector< MatType > &v)
Concatenate a list of matrices vertically Alternative terminology: vertical stack, vstack, vertical append, [a;b].
std::vector< MatType > horzsplit (const MatType &x, const std::vector< int > &offset)
split horizontally, retaining groups of columns
std::vector< MatType > horzsplit (const MatType &x, int incr=1)
split horizontally, retaining fixed-sized groups of columns
std::vector< MatType > vertsplit (const MatType &x, const std::vector< int > &offset)
split vertically, retaining groups of rows
std::vector< int > offset (const std::vector< MatType > &v, bool vert=true)
Helper function, get offsets corresponding to a vector of matrices.
std::vector< MatType > vertsplit (const MatType &x, int incr=1)
split vertically, retaining fixed-sized groups of rows
MatType blockcat (const std::vector< std::vector< MatType > > &v)
Construct a matrix from a list of list of blocks.
MatType blockcat (const MatType &A, const MatType &B, const MatType &C, const MatType &D)
Construct a matrix from 4 blocks.
std::vector< std::vector
< MatType > > blocksplit (const MatType &x, const std::vector< int > &vert_offset, const std::vector< int > &horz_offset)
chop up into blocks
std::vector< std::vector
< MatType > > blocksplit (const MatType &x, int vert_incr=1, int horz_incr=1)
chop up into blocks
MatType diagcat (const std::vector< MatType > &A)
Construct a matrix with given block on the diagonal.
std::vector< MatType > diagsplit (const MatType &x, const std::vector< int > &output_offset1, const std::vector< int > &output_offset2)
split diagonally, retaining square matrices
std::vector< MatType > diagsplit (const MatType &x, const std::vector< int > &output_offset)
split diagonally, retaining square matrices
std::vector< MatType > diagsplit (const MatType &x, int incr=1)
split diagonally, retaining groups of square matrices
std::vector< MatType > diagsplit (const MatType &x, int incr1, int incr2)
split diagonally, retaining fixed-sized matrices
MatType veccat (const std::vector< MatType > &x)
concatenate vertically while vectorizing all arguments with vec
MatType mtimes (const MatType &x, const MatType &y)
Matrix product of two matrices.
MatType mtimes (const std::vector< MatType > &args)
Matrix product of n matrices.
MatType mac (const MatType &x, const MatType &y, const MatType &z)
Multiply-accumulate operation Matrix product of two matrices (x and y), adding the result to a third matrix z. The result has the same sparsity pattern as C meaning that other entries of (x*y) are ignored. The operation is equivalent to: z+mtimes(x,y).project(z.sparsity()).
MatType transpose (const MatType &X)
Transpose.
MatType vec (const MatType &x)
make a vector Reshapes/vectorizes the matrix such that the shape becomes (expr.numel(), 1). Columns are stacked on top of each other. Same as reshape(expr, expr.numel(), 1)
MatType reshape (const MatType &x, int nrow, int ncol)
Returns a reshaped version of the matrix.
MatType reshape (const MatType &x, std::pair< int, int > rc)
Returns a reshaped version of the matrix, dimensions as a vector.
MatType reshape (const MatType &x, const Sparsity &sp)
Reshape the matrix.
int sprank (const MatType &x)
Obtain the structural rank of a sparsity-pattern.
int norm_0_mul (const MatType &x, const MatType &y)
0-norm (nonzero count) of a Matrix-matrix product
MatType triu (const MatType &x, bool includeDiagonal=true)
Get the upper triangular part of a matrix.
MatType tril (const MatType &x, bool includeDiagonal=true)
Get the lower triangular part of a matrix.
MatType kron (const MatType &a, const MatType &b)
Kronecker tensor product.
MatType repmat (const MatType &A, int n, int m=1)
Repeat matrix A n times vertically and m times horizontally.
MatType repmat (const MatType &A, const std::pair< int, int > &rc)
Repeat matrix A n times vertically and m times horizontally.
MatType horzcat (const MatType &x, const MatType &y)
Concatenate horizontally, two matrices.
MatType horzcat (const MatType &x, const MatType &y, const MatType &z)
Concatenate horizontally, three matrices.
MatType horzcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w)
Concatenate horizontally, four matrices.
MatType vertcat (const MatType &x, const MatType &y)
Concatenate vertically, two matrices.
MatType vertcat (const MatType &x, const MatType &y, const MatType &z)
Concatenate vertically, three matrices.
MatType vertcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w)
Concatenate vertically, four matrices.
MatType diagcat (const MatType &x, const MatType &y)
Concatenate along diagonal, two matrices.
MatType diagcat (const MatType &x, const MatType &y, const MatType &z)
Concatenate along diagonal, three matrices.
MatType diagcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w)
Concatenate along diagonal, four matrices.
Member Function Documentation
template<typename MatType> std::vector< std::vector< MatType > > casadi::SparsityInterface< MatType >::blocksplit (const MatType & x, const std::vector< int > & vert_offset, const std::vector< int > & horz_offset) static
Definition at line 551 of file sparsity_interface.hpp.
{
     std::vector<MatType> rows = MatType::vertsplit(x, vert_offset);
     std::vector< std::vector< MatType > > ret;
     for (auto&& r : rows) ret.push_back(MatType::horzsplit(r, horz_offset));
     return ret;
   }
template<typename MatType> std::vector< std::vector< MatType > > casadi::SparsityInterface< MatType >::blocksplit (const MatType & x, int vert_incr, int horz_incr) static
Definition at line 562 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(horz_incr>=1);
     casadi_assert(vert_incr>=1);
     int sz1 = x.size1();
     std::vector<int> offset1 = range(0, sz1, vert_incr);
     offset1.push_back(sz1);
     int sz2 = x.size2();
     std::vector<int> offset2 = range(0, sz2, horz_incr);
     offset2.push_back(sz2);
     return blocksplit(x, offset1, offset2);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, const std::vector< int > & output_offset) static
Definition at line 597 of file sparsity_interface.hpp.
{
     casadi_assert_message(x.is_square(), "diagsplit(x,incr)::input must be square but got "
                           << x.dim()  << ".");
     return MatType::diagsplit(x, output_offset, output_offset);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, int incr) static
Definition at line 605 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr>=1);
     casadi_assert_message(x.is_square(), "diagsplit(x,incr)::input must be square but got "
                           << x.dim()  << ".");
     std::vector<int> offset2 = range(0, x.size2(), incr);
     offset2.push_back(x.size2());
     return MatType::diagsplit(x, offset2);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, int incr1, int incr2) static
Definition at line 616 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr1>=1);
     casadi_assert(incr2>=1);
     std::vector<int> offset1 = range(0, x.size1(), incr1);
     offset1.push_back(x.size1());
     std::vector<int> offset2 = range(0, x.size2(), incr2);
     offset2.push_back(x.size2());
     return MatType::diagsplit(x, offset1, offset2);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::horzsplit (const MatType & x, int incr) static
Definition at line 637 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr>=1);
     int sz2 = x.size2();
     std::vector<int> offset2 = range(0, sz2, incr);
     offset2.push_back(sz2);
     return MatType::horzsplit(x, offset2);
   }
template<typename MatType> MatType casadi::SparsityInterface< MatType >::mtimes (const std::vector< MatType > & args) static
Definition at line 627 of file sparsity_interface.hpp.
{
     casadi_assert_message(args.size()>=1,
                           "mul(std::vector<MatType> &args): "
                           "supplied list must not be empty.");
     MatType ret = args[0];
     for (int i=1; i<args.size(); ++i) ret = MatType::mtimes(ret, args[i]);
     return ret;
   }
template<typename MatType> std::vector< int > casadi::SparsityInterface< MatType >::offset (const std::vector< MatType > & v, bool vert = true) static
Definition at line 576 of file sparsity_interface.hpp.
{
     std::vector<int> ret(v.size()+1);
     ret[0]=0;
     for (int i=0; i<v.size(); ++i) {
       ret[i+1] = ret[i] + (vert ? v[i].size1() : v[i].size2());
     }
     return ret;
   }
template<typename MatType> MatType casadi::SparsityInterface< MatType >::repmat (const MatType & x, int n, int m = 1) static
Definition at line 544 of file sparsity_interface.hpp.
{
     MatType allrows = vertcat(std::vector<MatType>(n, x));
     return horzcat(std::vector<MatType>(m, allrows));
   }
template<typename MatType> static MatType casadi::SparsityInterface< MatType >::repmat (const MatType & A, const std::pair< int, int > & rc) inline static
Definition at line 179 of file sparsity_interface.hpp.
{
       return MatType::repmat(A, rc.first, rc.second);
     }
template<typename MatType> const MatType& casadi::SparsityInterface< MatType >::self () const inline protected
Definition at line 51 of file sparsity_interface.hpp.
 { return static_cast<const MatType&>(*this); }
template<typename MatType> MatType& casadi::SparsityInterface< MatType >::self () inline protected
Definition at line 52 of file sparsity_interface.hpp.
 { return static_cast<MatType&>(*this); }
template<typename MatType> MatType casadi::SparsityInterface< MatType >::vec (const MatType & x) static
Definition at line 539 of file sparsity_interface.hpp.
{
     return reshape(x, x.numel(), 1);
   }
template<typename MatType> MatType casadi::SparsityInterface< MatType >::veccat (const std::vector< MatType > & x) static
Definition at line 586 of file sparsity_interface.hpp.
{
     std::vector< MatType > x_vec = x;
     for (typename std::vector< MatType >::iterator it=x_vec.begin();
          it!=x_vec.end(); ++it) {
       *it = vec(*it);
     }
     return vertcat(x_vec);
   }
template<typename MatType> std::vector< MatType > casadi::SparsityInterface< MatType >::vertsplit (const MatType & x, int incr) static
Definition at line 646 of file sparsity_interface.hpp.
References casadi::range().
{
     casadi_assert(incr>=1);
     int sz1 = x.size1();
     std::vector<int> offset1 = range(0, sz1, incr);
     offset1.push_back(sz1);
     return MatType::vertsplit(x, offset1);
   }
Friends And Related Function Documentation
template<typename MatType> template<typename T0 > void assign_map (const std::string & n0, T0 & x0, const std::map< std::string, MatType > & x) friend
Definition at line 97 of file sparsity_interface.hpp.
{
       x.at(n0).get(x0);
     }
template<typename MatType> template<typename T0 , typename T1 > void assign_map (const std::string & n0, T0 & x0, const std::string & n1, T0 & x1, const std::vector< MatType > & x) friend
Definition at line 104 of file sparsity_interface.hpp.
{
       assign_map(n0, x0, x);
       x.at(n1).get(x1);
     }
template<typename MatType> template<typename T0 , typename T1 , typename T2 > void assign_map (const std::string & n0, T0 & x0, const std::string & n1, T0 & x1, const std::string & n2, T0 & x2, const std::vector< MatType > & x) friend
Definition at line 113 of file sparsity_interface.hpp.
{
       assign_map(n0, x0, n1, x1, x);
       x.at(n2).get(x2);
     }
template<typename MatType> template<typename T0 , typename T1 , typename T2 , typename T3 > void assign_map (const std::string & n0, T0 & x0, const std::string & n1, T0 & x1, const std::string & n2, T0 & x2, const std::string & n3, T0 & x3, const std::vector< MatType > & x) friend
Definition at line 123 of file sparsity_interface.hpp.
{
       assign_map(n0, x0, n1, x1, n2, x2, x);
       x.at(n3).get(x3);
     }
template<typename MatType> template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 > void assign_map (const std::string & n0, T0 & x0, const std::string & n1, T0 & x1, const std::string & n2, T0 & x2, const std::string & n3, T0 & x3, const std::string & n4, T0 & x4, const std::vector< MatType > & x) friend
Definition at line 134 of file sparsity_interface.hpp.
{
       assign_map(n0, x0, n1, x1, n2, x2, n3, x3, x);
       x.at(n4).get(x4);
     }
template<typename MatType> template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > void assign_map (const std::string & n0, T0 & x0, const std::string & n1, T0 & x1, const std::string & n2, T0 & x2, const std::string & n3, T0 & x3, const std::string & n4, T0 & x4, const std::string & n5, T0 & x5, const std::vector< MatType > & x) friend
Definition at line 146 of file sparsity_interface.hpp.
{
       assign_map(n0, x0, n1, x1, n2, x2, n3, x3, n4, x4, x);
       x.at(n5).get(x5);
     }
template<typename MatType> std::vector<MatType> make_vector (const std::map< std::string, MatType > & m, const std::vector< std::string > & s) friend
Definition at line 56 of file sparsity_interface.hpp.
{
       std::vector<MatType> ret(s.size());
       for (size_t i=0; i!=s.size(); ++i) {
         typename std::map<std::string, MatType>::const_iterator it=m.find(s[i]);
         if (it!=m.end()) {
           ret[i]=it->second;
         }
       }
       return ret;
     }
template<typename MatType> std::vector<std::vector<MatType> > make_vector (const std::map< std::string, std::vector< MatType > > & m, const std::vector< std::string > & s) friend
Definition at line 70 of file sparsity_interface.hpp.
{
       std::vector<std::vector<MatType> > ret(s.size());
       for (size_t i=0; i!=s.size(); ++i) {
         typename std::map<std::string, std::vector<MatType> >::const_iterator it=m.find(s[i]);
         if (it!=m.end()) {
           ret[i]=it->second;
         }
       }
       return ret;
     }
template<typename MatType> std::vector<MatType> make_vector (const std::pair< std::map< std::string, MatType >, std::vector< std::string > > & ms) friend
Definition at line 84 of file sparsity_interface.hpp.
{
       return make_vector(ms.first, ms.second);
     }
template<typename MatType> std::vector<std::vector<MatType> > make_vector (const std::pair< std::map< std::string, std::vector< MatType > >, std::vector< std::string > > & ms) friend
Definition at line 90 of file sparsity_interface.hpp.
{
       return make_vector(ms.first, ms.second);
     }
The documentation for this class was generated from the following file:
sparsity_interface.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge