CasADi: casadi::Sparsity Class Reference
casadi::Sparsity Class Reference
General sparsity class.
#include <sparsity.hpp>
Detailed Description
The storage format is a compressed column storage (CCS) format.
In this format, the structural non-zero elements are stored in column-major order, starting from the upper left corner of the matrix and ending in the lower right corner.
In addition to the dimension (size1(), size2()), (i.e. the number of rows and the number of columns respectively), there are also two vectors of integers:
"colind" [length size2()+1], which contains the index to the first non-zero element on or after the corresponding column. All the non-zero elements of a particular i are thus the elements with index el that fulfills: colind[i] <= el < colind[i+1].
"row" [same length as the number of non-zero elements, nnz()] The rows for each of the structural non-zeros.
Note that with this format, it is cheap to loop over all the non-zero elements of a particular column, at constant time per element, but expensive to jump to access a location (i, j).
If the matrix is dense, i.e. length(row) == size1()*size2(), the format reduces to standard dense column major format, which allows access to an arbitrary element in constant time.
Since the object is reference counted (it inherits from SharedObject), several matrices are allowed to share the same sparsity pattern.
The implementations of some methods of this class has been taken from the CSparse package and modified to use C++ standard library and CasADi data structures.
See also
Matrix
Author
Joel Andersson
Date
2010-2015
Definition at line 77 of file sparsity.hpp.
Public Types
typedef SparsityInterface
< Sparsity > B
Base class.
Public Member Functions
Sparsity (int dummy=0)
Default constructor.
Sparsity (int nrow, int ncol)
Pattern with all structural zeros.
Sparsity (int nrow, int ncol, const std::vector< int > &colind, const std::vector< int > &row)
Construct from sparsity pattern vectors given in compressed column storage format.
Sparsity (int nrow, int ncol, const int *colind, const int *row)
Construct from sparsity pattern vectors given in compressed column storage format.
Sparsity (const std::pair< int, int > &rc)
Create a sparse matrix with all structural zeros.
void sanity_check (bool complete=false) const
Check if the dimensions and colind, row vectors are compatible.
Sparsity get_diag (std::vector< int > &output_mapping) const
std::vector< int > compress () const
Compress a sparsity pattern.
const SparsityInternal * operator-> () const
Access a member function or object.
const SparsityInternal & operator* () const
Reference to internal structure.
bool operator!= (const Sparsity &y) const
Check if two sparsity patterns are difference.
operator const int * () const
Implicit or explicit type conversion to C representation In the C runtime, sparsity patterns are represented as a "const int*". This enables using the C runtime functions using a natural syntax.
const int * row () const
Get a reference to row-vector, containing rows for all non-zero elements (see class description)
const int * colind () const
Get a reference to the colindex of all column element (see class description)
std::vector< int > get_row () const
Get the row for each non-zero entry Together with the column-vector, this vector gives the sparsity of the matrix in sparse triplet format, and together with the colind vector, one obtains the sparsity in column compressed format.
std::vector< int > get_colind () const
Get the column index for each column Together with the row-vector, one obtains the sparsity pattern in the column compressed format.
int colind (int cc) const
Get a reference to the colindex of column cc (see class description)
int row (int el) const
Get the row of a non-zero element.
std::vector< int > get_col () const
Get the column for each non-zero entry Together with the row-vector, this vector gives the sparsity of the matrix in sparse triplet format, i.e. the column and row for each non-zero elements.
void resize (int nrow, int ncol)
Resize.
int add_nz (int rr, int cc)
Get the index of a non-zero element Add the element if it does not exist and copy object if it's not unique.
int get_nz (int rr, int cc) const
Get the index of an existing non-zero element return -1 if the element does not exist.
bool has_nz (int rr, int cc) const
Returns true if the pattern has a non-zero at location rr, cc.
std::vector< int > get_nz (const std::vector< int > &rr, const std::vector< int > &cc) const
Get a set of non-zero element return -1 if the element does not exist.
void get_nz (std::vector< int > &SWIG_INOUT(indices)) const
Get the nonzero index for a set of elements The index vector is used both for input and outputs and must be sorted by increasing nonzero index, i.e. column-wise. Elements not found in the sparsity pattern are set to -1.
std::vector< int > get_lower () const
Get nonzeros in lower triangular part.
std::vector< int > get_upper () const
Get nonzeros in upper triangular part.
void get_ccs (std::vector< int > &output_colind, std::vector< int > &output_row) const
Get the sparsity in compressed column storage (CCS) format.
void get_crs (std::vector< int > &output_rowind, std::vector< int > &output_col) const
Get the sparsity in compressed row storage (CRS) format.
void get_triplet (std::vector< int > &output_row, std::vector< int > &output_col) const
Get the sparsity in sparse triplet format.
Sparsity sub (const std::vector< int > &rr, const std::vector< int > &cc, std::vector< int > &output_mapping, bool ind1=false) const
Get a submatrix.
Sparsity sub (const std::vector< int > &rr, const Sparsity &sp, std::vector< int > &output_mapping, bool ind1=false) const
Get a set of elements.
Sparsity T () const
Transpose the matrix.
Sparsity transpose (std::vector< int > &mapping, bool invert_mapping=false) const
Transpose the matrix and get the reordering of the non-zero entries.
bool is_transpose (const Sparsity &y) const
Check if the sparsity is the transpose of another.
bool isReshape (const Sparsity &y) const
Check if the sparsity is a reshape of another.
Sparsity pattern_inverse () const
Take the inverse of a sparsity pattern; flip zeros and non-zeros.
template<typename DataType >
void set (DataType *data, const DataType *val_data, const Sparsity &val_sp) const
template<typename DataType >
void add (DataType *data, const DataType *val_data, const Sparsity &val_sp) const
template<typename DataType >
void bor (DataType *data, const DataType *val_data, const Sparsity &val_sp) const
void assignNode (SharedObjectNode *node)
void assignNodeNoCount (SharedObjectNode *node)
Assign the node to a node class pointer without reference counting.
SharedObjectNode * get () const
Get a const pointer to the node.
int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void printPtr (std::ostream &stream=casadi::userOut()) const
bool is_null () const
Is a null pointer?
WeakRef * weak ()
Get a weak reference to the object.
size_t __hash__ () const
Returns a number that is unique for a given Node. If the Object does not point to any node, "0" is returned.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
Check if two sparsity patterns are identical
bool is_equal (const Sparsity &y) const
bool is_equal (int nrow, int ncol, const std::vector< int > &colind, const std::vector< int > &row) const
bool is_equal (int nrow, int ncol, const int *colind, const int *row) const
bool operator== (const Sparsity &y) const
Size and element counting
int size1 () const
Get the number of rows.
int size2 () const
Get the number of columns.
int numel () const
The total number of elements, including structural zeros, i.e. size2()*size1()
bool is_empty (bool both=false) const
Check if the sparsity is empty.
int nnz () const
Get the number of (structural) non-zeros.
int nnz_upper (bool strictly=false) const
Number of non-zeros in the upper triangular half, i.e. the number of elements (i, j) with j>=i.
int nnz_lower (bool strictly=false) const
Number of non-zeros in the lower triangular half, i.e. the number of elements (i, j) with j<=i.
int nnz_diag () const
Number of non-zeros on the diagonal, i.e. the number of elements (i, j) with j==i.
int bw_upper () const
Upper half-bandwidth.
int bw_lower () const
Lower half-bandwidth.
std::pair< int, int > size () const
Get the shape.
int size (int axis) const
Get the size along a particular dimensions.
Sparsity combine (const Sparsity &y, bool f0x_is_zero, bool fx0_is_zero, std::vector< unsigned char > &mapping) const
Combine two sparsity patterns Returns the new sparsity pattern as well as a mapping with the same length as the number of non-zero elements The mapping matrix contains the arguments for each nonzero, the first bit indicates if the first argument is nonzero, the second bit indicates if the second argument is nonzero (note that none of, one of or both of the arguments can be nonzero)
Sparsity combine (const Sparsity &y, bool f0x_is_zero, bool fx0_is_zero) const
Combine two sparsity patterns Returns the new sparsity pattern as well as a mapping with the same length as the number of non-zero elements The mapping matrix contains the arguments for each nonzero, the first bit indicates if the first argument is nonzero, the second bit indicates if the second argument is nonzero (note that none of, one of or both of the arguments can be nonzero)
Sparsity unite (const Sparsity &y, std::vector< unsigned char > &mapping) const
Union of two sparsity patterns.
Sparsity unite (const Sparsity &y) const
Union of two sparsity patterns.
Sparsity operator+ (const Sparsity &b) const
Union of two sparsity patterns.
Sparsity intersect (const Sparsity &y, std::vector< unsigned char > &mapping) const
Intersection of two sparsity patterns Returns the new sparsity pattern as well as a mapping with the same length as the number of non-zero elements The value is 1 if the non-zero comes from the first (i.e. this) object, 2 if it is from the second and 3 (i.e. 1 | 2) if from both.
Sparsity intersect (const Sparsity &y) const
Intersection of two sparsity patterns Returns the new sparsity pattern as well as a mapping with the same length as the number of non-zero elements The value is 1 if the non-zero comes from the first (i.e. this) object, 2 if it is from the second and 3 (i.e. 1 | 2) if from both.
Sparsity operator* (const Sparsity &b) const
Intersection of two sparsity patterns Returns the new sparsity pattern as well as a mapping with the same length as the number of non-zero elements The value is 1 if the non-zero comes from the first (i.e. this) object, 2 if it is from the second and 3 (i.e. 1 | 2) if from both.
Static Public Member Functions
static Sparsity create (SparsityInternal *node)
Create from node.
static Sparsity upper (int n)
Create a upper triangular square sparsity pattern.
static Sparsity lower (int n)
Create a lower triangular square sparsity pattern.
static Sparsity band (int n, int p)
Create a single band in a square sparsity pattern.
static Sparsity banded (int n, int p)
Create banded square sparsity pattern.
static Sparsity rowcol (const std::vector< int > &row, const std::vector< int > &col, int nrow, int ncol)
Construct a block sparsity pattern from (row, col) vectors.
static Sparsity triplet (int nrow, int ncol, const std::vector< int > &row, const std::vector< int > &col, std::vector< int > &mapping, bool invert_mapping=false)
Create a sparsity pattern given the nonzeros in sparse triplet form.
static Sparsity triplet (int nrow, int ncol, const std::vector< int > &row, const std::vector< int > &col)
Create a sparsity pattern given the nonzeros in sparse triplet form (no nonzero mapping) rows_are_sorted==true means that the row entries already in increasing order for each col and without any duplicates.
static void mul_sparsityF (const bvec_t *x, const Sparsity &x_sp, const bvec_t *y, const Sparsity &y_sp, bvec_t *z, const Sparsity &z_sp, bvec_t *w)
Propagate sparsity using 0-1 logic through a matrix product, no memory allocation: z = mul(x, y) with work vector Forward mode.
static void mul_sparsityR (bvec_t *x, const Sparsity &x_sp, bvec_t *y, const Sparsity &y_sp, bvec_t *z, const Sparsity &z_sp, bvec_t *w)
Propagate sparsity using 0-1 logic through a matrix product, no memory allocation: z = mul(x, y) with work vector Reverse mode.
static std::vector
< std::vector< Sparsity > > blocksplit (const Sparsity &x, const std::vector< int > &vert_offset, const std::vector< int > &horz_offset)
static std::vector
< std::vector< Sparsity > > blocksplit (const Sparsity &x, int vert_incr, int horz_incr)
static Sparsity veccat (const std::vector< Sparsity > &x)
static Sparsity vec (const Sparsity &x)
static Sparsity repmat (const Sparsity &x, int n, int m=1)
static Sparsity repmat (const Sparsity &A, const std::pair< int, int > &rc)
static std::vector< int > offset (const std::vector< Sparsity > &v, bool vert=true)
static std::vector< Sparsity > diagsplit (const Sparsity &x, const std::vector< int > &output_offset)
static std::vector< Sparsity > diagsplit (const Sparsity &x, int incr)
static std::vector< Sparsity > diagsplit (const Sparsity &x, int incr1, int incr2)
static Sparsity mtimes (const std::vector< Sparsity > &args)
static std::vector< Sparsity > horzsplit (const Sparsity &x, int incr)
static std::vector< Sparsity > vertsplit (const Sparsity &x, int incr)
static Sparsity scalar (bool dense_scalar=true)
Create a scalar sparsity pattern.
static Sparsity dense (int nrow, int ncol=1)
Create a dense rectangular sparsity pattern.
static Sparsity dense (const std::pair< int, int > &rc)
Create a dense rectangular sparsity pattern.
static Sparsity unit (int n, int el)
Create the sparsity pattern for a unit vector of length n and a nonzero on position el.
static Sparsity diag (int nrow)
Create diagonal sparsity pattern.
static Sparsity diag (int nrow, int ncol)
Create diagonal sparsity pattern.
static Sparsity diag (const std::pair< int, int > &rc)
Create diagonal sparsity pattern.
static Sparsity compressed (const std::vector< int > &v)
static Sparsity compressed (const int *v)
Protected Member Functions
void count_up ()
void count_down ()
const Sparsity & self () const
Sparsity & self ()
typedef
std::unordered_multimap
< std::size_t, WeakRef > CachingMap
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
void enlarge (int nrow, int ncol, const std::vector< int > &rr, const std::vector< int > &cc, bool ind1=false)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
void enlargeRows (int nrow, const std::vector< int > &rr, bool ind1=false)
Enlarge the matrix along the first dimension (i.e. insert rows)
void enlargeColumns (int ncol, const std::vector< int > &cc, bool ind1=false)
Enlarge the matrix along the second dimension (i.e. insert columns)
Sparsity makeDense (std::vector< int > &mapping) const
Make a patten dense.
std::vector< int > erase (const std::vector< int > &rr, const std::vector< int > &cc, bool ind1=false)
Erase rows and/or columns of a matrix.
std::vector< int > erase (const std::vector< int > &rr, bool ind1=false)
Erase elements of a matrix.
void append (const Sparsity &sp)
Append another sparsity patten vertically (NOTE: only efficient if vector)
void appendColumns (const Sparsity &sp)
Append another sparsity patten horizontally.
bool is_scalar (bool scalar_and_dense=false) const
Is scalar?
bool is_dense () const
Is dense?
bool is_row () const
Check if the pattern is a row vector (i.e. size1()==1)
bool is_column () const
Check if the pattern is a column vector (i.e. size2()==1)
bool is_vector () const
Check if the pattern is a row or column vector.
bool is_diag () const
Is diagonal?
bool is_square () const
Is square?
bool is_symmetric () const
Is symmetric?
bool is_triu () const
Is upper triangular?
bool is_tril () const
Is lower triangular?
bool is_singular () const
Check whether the sparsity-pattern indicates structural singularity.
bool rowsSequential (bool strictly=true) const
Do the rows appear sequentially on each column.
void removeDuplicates (std::vector< int > &mapping)
Remove duplicate entries.
std::vector< int > etree (bool ata=false) const
Calculate the elimination tree See Direct Methods for Sparse Linear Systems by Davis (2006). If the parameter ata is false, the algorithm is equivalent to MATLAB's etree(A), except that the indices are zero-based. If ata is true, the algorithm is equivalent to MATLAB's etree(A, 'col').
int dfs (int j, int top, std::vector< int > &xi, std::vector< int > &pstack, const std::vector< int > &pinv, std::vector< bool > &marked) const
Depth-first search on the adjacency graph of the sparsity See Direct Methods for Sparse Linear Systems by Davis (2006).
int scc (std::vector< int > &output_index, std::vector< int > &output_offset) const
Find the strongly connected components of the bigraph defined by the sparsity pattern of a square matrix.
int btf (std::vector< int > &output_rowperm, std::vector< int > &output_colperm, std::vector< int > &output_rowblock, std::vector< int > &output_colblock, std::vector< int > &output_coarse_rowblock, std::vector< int > &output_coarse_colblock, int seed=0) const
Calculate the block triangular form (BTF) See Direct Methods for Sparse Linear Systems by Davis (2006).
std::vector< int > find (bool ind1=SWIG_IND1) const
Get the location of all non-zero elements as they would appear in a Dense matrix A : DenseMatrix 4 x 3 B : SparseMatrix 4 x 3 , 5 structural non-zeros.
void find (std::vector< int > &loc, bool ind1=false) const
Get the location of all nonzero elements (inplace version)
Sparsity uni_coloring (const Sparsity &AT=Sparsity(), int cutoff=std::numeric_limits< int >::max()) const
Perform a unidirectional coloring: A greedy distance-2 coloring algorithm (Algorithm 3.1 in A. H. GEBREMEDHIN, F. MANNE, A. POTHEN)
Sparsity star_coloring (int ordering=1, int cutoff=std::numeric_limits< int >::max()) const
Perform a star coloring of a symmetric matrix: A greedy distance-2 coloring algorithm Algorithm 4.1 in What Color Is Your Jacobian? Graph Coloring for Computing Derivatives A. H. GEBREMEDHIN, F. MANNE, A. POTHEN SIAM Rev., 47(4), 629705 (2006)
Sparsity star_coloring2 (int ordering=1, int cutoff=std::numeric_limits< int >::max()) const
Perform a star coloring of a symmetric matrix: A new greedy distance-2 coloring algorithm Algorithm 4.1 in NEW ACYCLIC AND STAR COLORING ALGORITHMS WITH APPLICATION TO COMPUTING HESSIANS A. H. GEBREMEDHIN, A. TARAFDAR, F. MANNE, A. POTHEN SIAM J. SCI. COMPUT. Vol. 29, No. 3, pp. 10421072 (2007)
std::vector< int > largest_first () const
Order the columns by decreasing degree.
Sparsity pmult (const std::vector< int > &p, bool permute_rows=true, bool permute_columns=true, bool invert_permutation=false) const
Permute rows and/or columns Multiply the sparsity with a permutation matrix from the left and/or from the right P * A * trans(P), A * trans(P) or A * trans(P) with P defined by an index vector containing the row for each col. As an alternative, P can be transposed (inverted).
std::string dim () const
Get the dimension as a string.
void spy (std::ostream &stream=casadi::userOut()) const
Print a textual representation of sparsity.
void spy_matlab (const std::string &mfile) const
Generate a script for Matlab or Octave which visualizes the sparsity using the spy command.
void print_compact (std::ostream &stream=casadi::userOut()) const
Print a compact description of the sparsity pattern.
std::size_t hash () const
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
template<typename T >
void set (T *data, const T *val_data, const Sparsity &val_sp) const
Assign the nonzero entries of one sparsity pattern to the nonzero entries of another sparsity pattern.
template<typename T >
void add (T *data, const T *val_data, const Sparsity &val_sp) const
Add the nonzero entries of one sparsity pattern to the nonzero entries of another sparsity pattern.
template<typename T >
void bor (T *data, const T *val_data, const Sparsity &val_sp) const
Bitwise or of the nonzero entries of one sparsity pattern and the nonzero entries of another sparsity pattern.
static Sparsity horzcat (const std::vector< Sparsity > &sp)
Accessed by SparsityInterface.
static Sparsity vertcat (const std::vector< Sparsity > &sp)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity blockcat (const std::vector< std::vector< Sparsity > > &v)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity diagcat (const std::vector< Sparsity > &v)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static std::vector< Sparsity > horzsplit (const Sparsity &x, const std::vector< int > &output_offset)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static std::vector< Sparsity > vertsplit (const Sparsity &x, const std::vector< int > &output_offset)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static std::vector< Sparsity > diagsplit (const Sparsity &x, const std::vector< int > &offset1, const std::vector< int > &offset2)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity mtimes (const Sparsity &x, const Sparsity &y)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity mac (const Sparsity &x, const Sparsity &y, const Sparsity &z)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity reshape (const Sparsity &x, int nrow, int ncol)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity reshape (const Sparsity &x, const Sparsity &sp)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static int sprank (const Sparsity &x)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static int norm_0_mul (const Sparsity &x, const Sparsity &B)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity kron (const Sparsity &x, const Sparsity &b)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity triu (const Sparsity &x, bool includeDiagonal=true)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static Sparsity tril (const Sparsity &x, bool includeDiagonal=true)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
static CachingMap & getCache ()
Cached sparsity patterns.
static const Sparsity & getScalar ()
(Dense) scalar
static const Sparsity & getScalarSparse ()
(Sparse) scalar
static const Sparsity & getEmpty ()
Empty zero-by-zero.
static bool test_cast (const SharedObjectNode *ptr)
Check if a particular cast is allowed.
Member Typedef Documentation
typedef SparsityInterface<Sparsity> casadi::Sparsity::B
Definition at line 101 of file sparsity.hpp.
typedef std::unordered_multimap<std::size_t, WeakRef> casadi::Sparsity::CachingMap
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 558 of file sparsity.hpp.
Constructor & Destructor Documentation
casadi::Sparsity::Sparsity (int dummy = 0) explicit
Definition at line 64 of file sparsity.cpp.
{
     casadi_assert(dummy==0);
   }
casadi::Sparsity::Sparsity (int nrow, int ncol)
Definition at line 74 of file sparsity.cpp.
{
     std::vector<int> row, colind(ncol+1, 0);
     assign_cached(nrow, ncol, colind, row);
     sanity_check(true);
   }
casadi::Sparsity::Sparsity (int nrow, int ncol, const std::vector< int > & colind, const std::vector< int > & row)
Definition at line 86 of file sparsity.cpp.
{
     assign_cached(nrow, ncol, colind, row);
     sanity_check(true);
   }
casadi::Sparsity::Sparsity (int nrow, int ncol, const int * colind, const int * row)
Definition at line 92 of file sparsity.cpp.
{
     if (colind==0 || colind[ncol]==nrow*ncol) {
       *this = dense(nrow, ncol);
     } else {
       vector<int> colindv(colind, colind+ncol+1);
       vector<int> rowv(row, row+colind[ncol]);
       assign_cached(nrow, ncol, colindv, rowv);
       sanity_check(true);
     }
   }
casadi::Sparsity::Sparsity (const std::pair< int, int > & rc) explicit
Definition at line 80 of file sparsity.cpp.
{
     std::vector<int> row, colind(rc.second+1, 0);
     assign_cached(rc.first, rc.second, colind, row);
     sanity_check(true);
   }
Member Function Documentation
size_t casadi::SharedObject::__hash__ () const inherited
Definition at line 178 of file shared_object.cpp.
{
     return reinterpret_cast<size_t>(get());
   }
template<typename T > void casadi::Sparsity::add (T * data, const T * val_data, const Sparsity & val_sp) const
template<typename DataType > void casadi::Sparsity::add (DataType * data, const DataType * val_data, const Sparsity & val_sp) const
Definition at line 853 of file sparsity.hpp.
References colind(), dim(), is_empty(), nnz(), row(), size1(), and size2().
{
     // Get dimensions of this
     const int sz = nnz();
     const int sz1 = size1();
     const int sz2 = size2();
     const int nel = sz1*sz2;
     // Get dimensions of assigning matrix
     const int val_sz = val_sp.nnz();
     const int val_sz1 = val_sp.size1();
     const int val_sz2 = val_sp.size2();
     const int val_nel = val_sz1*val_sz2;
     // Check if sparsity matches
     if (val_sp==*this) {
       for (int k=0; k<sz; ++k) {
         data[k] += val_data[k];
       }
     } else if (this->is_empty()) {
       // Quick return
       return;
     } else if (val_sp.is_empty()) {
       // Quick return
       return;
     }  else if (val_nel==1) { // if scalar
       if (val_sz!=0) {
         for (int k=0; k<sz; ++k) {
           data[k] += val_data[0];
         }
       }
     } else {
       // Quick return if empty
       if (nel==0 && val_nel==0) return;
       // Make sure that dimension matches
       casadi_assert_message(sz2==val_sz2 && sz1==val_sz1,
                             "Sparsity::add<DataType>: shape mismatch. lhs is matrix of shape "
                             << dim() << ", while rhs is shape "
                             << val_sp.dim() << ".");
       // Sparsity
       const int* c = row();
       const int* rind = colind();
       const int* v_c = val_sp.row();
       const int* v_rind = val_sp.colind();
       // For all columns
       for (int i=0; i<sz2; ++i) {
         // Nonzero of the assigning matrix
         int v_el = v_rind[i];
         // First nonzero of the following column
         int v_el_end = v_rind[i+1];
         // Next row of the assigning matrix
         int v_j = v_el<v_el_end ? v_c[v_el] : sz1;
         // Assign all nonzeros
         for (int el=rind[i]; el!=rind[i+1]; ++el) {
           //  Get row
           int j=c[el];
           // Forward the assigning nonzero
           while (v_j<j) {
             v_el++;
             v_j = v_el<v_el_end ? v_c[v_el] : sz1;
           }
           // Assign nonzero
           if (v_j==j) {
             data[el] += val_data[v_el++];
             v_j = v_el<v_el_end ? v_c[v_el] : sz1;
           }
         }
       }
     }
   }
int casadi::Sparsity::add_nz (int rr, int cc)
Definition at line 183 of file sparsity.cpp.
References casadi::copy().
{
     // If negative index, count from the back
     if (rr<0) rr += size1();
     if (cc<0) cc += size2();
     // Check consistency
     casadi_assert_message(rr>=0 && rr<size1(), "Row index out of bounds");
     casadi_assert_message(cc>=0 && cc<size2(), "Column index out of bounds");
     // Quick return if matrix is dense
     if (is_dense()) return rr+cc*size1();
     // Get sparsity pattern
     int size1=this->size1(), size2=this->size2(), nnz=this->nnz();
     const int *colind = this->colind(), *row = this->row();
     // Quick return if we are adding an element to the end
     if (colind[cc]==nnz || (colind[cc+1]==nnz && row[nnz-1]<rr)) {
       std::vector<int> rowv(nnz+1);
       copy(row, row+nnz, rowv.begin());
       rowv[nnz] = rr;
       std::vector<int> colindv(colind, colind+size2+1);
       for (int c=cc; c<size2; ++c) colindv[c+1]++;
       assign_cached(size1, size2, colindv, rowv);
       return rowv.size()-1;
     }
     // go to the place where the element should be
     int ind;
     for (ind=colind[cc]; ind<colind[cc+1]; ++ind) { // better: loop from the back to the front
       if (row[ind] == rr) {
         return ind; // element exists
       } else if (row[ind] > rr) {
         break;                // break at the place where the element should be added
       }
     }
     // insert the element
     std::vector<int> rowv = get_row(), colindv = get_colind();
     rowv.insert(rowv.begin()+ind, rr);
     for (int c=cc+1; c<size2+1; ++c) colindv[c]++;
     // Return the location of the new element
     assign_cached(size1, size2, colindv, rowv);
     return ind;
   }
void casadi::Sparsity::append (const Sparsity & sp)
Definition at line 419 of file sparsity.cpp.
References casadi::SparsityInternal::_appendVector(), dim(), size1(), and size2().
Referenced by casadi::Constant< Value >::getVertcat().
{
     if (sp.size1()==0 && sp.size2()==0) {
       // Appending pattern is empty
       return;
     } else if (size1()==0 && size2()==0) {
       // This is empty
       *this = sp;
     } else {
       casadi_assert_message(size2()==sp.size2(),
                             "Sparsity::append: Dimension mismatch. "
                             "You attempt to append a shape " << sp.dim()
                             << " to a shape " << dim()
                             << ". The number of columns must match.");
       if (sp.size1()==0) {
         // No rows to add
         return;
       } else if (size1()==0) {
         // No rows before
         *this = sp;
       } else if (is_column()) {
         // Append to vector (inefficient)
         *this = (*this)->_appendVector(*sp);
       } else {
         // Append to matrix (inefficient)
         *this = vertcat({*this, sp});
       }
     }
   }
void casadi::Sparsity::appendColumns (const Sparsity & sp)
Definition at line 448 of file sparsity.cpp.
References casadi::SparsityInternal::_appendColumns(), dim(), size1(), and size2().
Referenced by casadi::Constant< Value >::getHorzcat().
{
     if (sp.size1()==0 && sp.size2()==0) {
       // Appending pattern is empty
       return;
     } else if (size1()==0 && size2()==0) {
       // This is empty
       *this = sp;
     } else {
       casadi_assert_message(size1()==sp.size1(),
                             "Sparsity::appendColumns: Dimension mismatch. You attempt to "
                             "append a shape " << sp.dim() << " to a shape "
                             << dim() << ". The number of rows must match.");
       if (sp.size2()==0) {
         // No columns to add
         return;
       } else if (size2()==0) {
         // No columns before
         *this = sp;
       } else {
         // Append to matrix (expensive)
         *this = (*this)->_appendColumns(*sp);
       }
     }
   }
void casadi::SharedObject::assignNode (SharedObjectNode * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 57 of file shared_object.cpp.
Referenced by casadi::Function::conditional(), casadi::Callback::construct(), casadi::MapBase::create(), casadi::Mapaccum::create(), create(), casadi::Function::create(), casadi::external(), casadi::Function::if_else(), casadi::MXFunction::init(), casadi::integrator(), casadi::jit(), casadi::Function::kernel_sum(), casadi::linsol(), casadi::nlpsol(), casadi::qpsol(), casadi::rootfinder(), and casadi::WeakRef::shared().
{
     count_down();
     node = node_;
     count_up();
   }
void casadi::SharedObject::assignNodeNoCount (SharedObjectNode * node) inherited
improper use will cause memory leaks!
Definition at line 63 of file shared_object.cpp.
{
     node = node_;
   }
Sparsity casadi::Sparsity::band (int n, int p) static
band(n, 0) is equivalent to diag(n)
band(n, -1) has a band below the diagonal
Parameters
p indicate
Definition at line 837 of file sparsity.cpp.
{
     casadi_assert_message(n>=0, "Sparsity::band expects a positive integer as argument");
     casadi_assert_message((p<0? -p : p)<n,
                           "Sparsity::band: position of band schould be smaller then size argument");
     int nc = n-(p<0? -p : p);
     std::vector< int >          row(nc);
     int offset = max(p, 0);
     for (int i=0;i<nc;i++) {
       row[i]=i+offset;
     }
     std::vector< int >          colind(n+1);
     offset = min(p, 0);
     for (int i=0;i<n+1;i++) {
       colind[i]=max(min(i+offset, nc), 0);
     }
     return Sparsity(n, n, colind, row);
   }
Sparsity casadi::Sparsity::banded (int n, int p) static
banded(n, 0) is equivalent to diag(n)
banded(n, 1) is tri-diagonal matrix
Definition at line 862 of file sparsity.cpp.
{
     // This is not an efficient implementation
     Sparsity ret = Sparsity(n, n);
     for (int i=-p;i<=p;++i) {
       ret = ret + Sparsity::band(n, i);
     }
     return ret;
   }
Sparsity casadi::Sparsity::blockcat (const std::vector< std::vector< Sparsity > > & v) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1286 of file sparsity.cpp.
{
     std::vector< Sparsity > ret;
     for (int i=0; i<v.size(); ++i)
       ret.push_back(horzcat(v[i]));
     return vertcat(ret);
   }
static std::vector< std::vector< Sparsity > > casadi::SparsityInterface< Sparsity >::blocksplit (const Sparsity & x, const std::vector< int > & vert_offset, const std::vector< int > & horz_offset) static inherited
static std::vector< std::vector< Sparsity > > casadi::SparsityInterface< Sparsity >::blocksplit (const Sparsity & x, int vert_incr, int horz_incr) static inherited
template<typename T > void casadi::Sparsity::bor (T * data, const T * val_data, const Sparsity & val_sp) const
template<typename DataType > void casadi::Sparsity::bor (DataType * data, const DataType * val_data, const Sparsity & val_sp) const
Definition at line 934 of file sparsity.hpp.
References colind(), dim(), is_empty(), nnz(), row(), size1(), and size2().
{
     // Get dimensions of this
     const int sz = nnz();
     const int sz1 = size1();
     const int sz2 = size2();
     const int nel = sz1*sz2;
     // Get dimensions of assigning matrix
     const int val_sz = val_sp.nnz();
     const int val_sz1 = val_sp.size1();
     const int val_sz2 = val_sp.size2();
     const int val_nel = val_sz1*val_sz2;
     // Check if sparsity matches
     if (val_sp==*this) {
       for (int k=0; k<sz; ++k) {
         data[k] |= val_data[k];
       }
     } else if (this->is_empty()) {
       // Quick return
       return;
     } else if (val_sp.is_empty()) {
       // Quick return
       return;
     }  else if (val_nel==1) { // if scalar
       if (val_sz!=0) {
         for (int k=0; k<sz; ++k) {
           data[k] |= val_data[0];
         }
       }
     } else {
       // Quick return if empty
       if (nel==0 && val_nel==0) return;
       // Make sure that dimension matches
       casadi_assert_message(sz2==val_sz2 && sz1==val_sz1,
                             "Sparsity::add<DataType>: shape mismatch. lhs is matrix of shape "
                             << dim() << ", while rhs is shape " << val_sp.dim() << ".");
       // Sparsity
       const int* c = row();
       const int* rind = colind();
       const int* v_c = val_sp.row();
       const int* v_rind = val_sp.colind();
       // For all columns
       for (int i=0; i<sz2; ++i) {
         // Nonzero of the assigning matrix
         int v_el = v_rind[i];
         // First nonzero of the following column
         int v_el_end = v_rind[i+1];
         // Next row of the assigning matrix
         int v_j = v_el<v_el_end ? v_c[v_el] : sz1;
         // Assign all nonzeros
         for (int el=rind[i]; el!=rind[i+1]; ++el) {
           //  Get row
           int j=c[el];
           // Forward the assigning nonzero
           while (v_j<j) {
             v_el++;
             v_j = v_el<v_el_end ? v_c[v_el] : sz1;
           }
           // Assign nonzero
           if (v_j==j) {
             data[el] |= val_data[v_el++];
             v_j = v_el<v_el_end ? v_c[v_el] : sz1;
           }
         }
       }
     }
   }
int casadi::Sparsity::btf (std::vector< int > & output_rowperm, std::vector< int > & output_colperm, std::vector< int > & output_rowblock, std::vector< int > & output_colblock, std::vector< int > & output_coarse_rowblock, std::vector< int > & output_coarse_colblock, int seed = 0) const
The function computes the Dulmage-Mendelsohn decomposition, which allows you to reorder the rows and columns of a matrix to bring it into block triangular form (BTF).
It will not consider the distance of off-diagonal elements to the diagonal: there is no guarantee you will get a block-diagonal matrix if you supply a randomly permuted block-diagonal matrix.
If your matrix is symmetrical, this method is of limited use; permutation can make it non-symmetric.
See also
scc
Examples:
matrix/btf.py.
Definition at line 558 of file sparsity.cpp.
Referenced by casadi::Linsol::Linsol(), casadi::Matrix< Scalar >::solve(), and sprank().
{
     return (*this)->btf(rowperm, colperm, rowblock, colblock,
                                       coarse_rowblock, coarse_colblock, seed);
   }
int casadi::Sparsity::bw_lower () const
Definition at line 1101 of file sparsity.cpp.
Referenced by casadi::SundialsInterface::getBandwidth(), and casadi::SundialsInterface::getBandwidthB().
{
     return (*this)->bw_lower();
   }
int casadi::Sparsity::bw_upper () const
Definition at line 1097 of file sparsity.cpp.
Referenced by casadi::SundialsInterface::getBandwidth(), and casadi::SundialsInterface::getBandwidthB().
{
     return (*this)->bw_upper();
   }
const int * casadi::Sparsity::colind () const
Definition at line 151 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes(), add(), casadi::KinsolInterface::bjac(), casadi::CvodesInterface::bjac(), casadi::IdasInterface::bjac(), casadi::CvodesInterface::bjacB(), casadi::IdasInterface::bjacB(), bor(), casadi::SparsityInternal::breadthFirstSearch(), casadi::SparsityInternal::combineGen(), casadi::SparsityInternal::counts(), casadi::KinsolInterface::djac(), casadi::CvodesInterface::djac(), casadi::IdasInterface::djac(), casadi::CvodesInterface::djacB(), casadi::IdasInterface::djacB(), casadi::OoqpInterface::eval(), casadi::GurobiInterface::eval(), casadi::QpoasesInterface::eval(), casadi::CplexInterface::eval(), casadi::IpoptUserClass::eval_h(), casadi::IpoptUserClass::eval_jac_g(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), horzsplit(), casadi::SqicInterface::init(), casadi::CsparseInterface::init_memory(), casadi::CplexInterface::init_memory(), casadi::SparsityInternal::is_equal(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::linsol_spAdj(), casadi::Linsol::linsol_spFwd(), casadi::Linsol::linsol_spsolve(), mul_sparsityF(), mul_sparsityR(), casadi::SparsityInternal::multiply(), norm_0_mul(), set(), casadi::WorhpInterface::set_work(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::spFwd(), casadi::SparsityInternal::uni_coloring(), and casadi::SnoptInterface::userfun().
{
     return (*this)->colind();
   }
int casadi::Sparsity::colind (int cc) const
Definition at line 164 of file sparsity.cpp.
{
     if (cc<0 || cc>size2()) {
       std::stringstream ss;
       ss << "Sparsity::colind: Index " << cc << " out of range [0," << size2() << "]";
       throw std::out_of_range(ss.str());
     }
     return colind()[cc];
   }
Sparsity casadi::Sparsity::combine (const Sparsity & y, bool f0x_is_zero, bool fx0_is_zero, std::vector< unsigned char > & mapping) const
Definition at line 361 of file sparsity.cpp.
References casadi::SparsityInternal::combine().
Referenced by casadi::MXNode::getBinarySwitch(), and casadi::Matrix< Scalar >::matrix_matrix().
{
     return (*this)->combine(y, f0x_is_zero, function0_is_zero, mapping);
   }
Sparsity casadi::Sparsity::combine (const Sparsity & y, bool f0x_is_zero, bool fx0_is_zero) const
Definition at line 367 of file sparsity.cpp.
References casadi::SparsityInternal::combine().
{
     return (*this)->combine(y, f0x_is_zero, function0_is_zero);
   }
std::vector< int > casadi::Sparsity::compress () const
Definition at line 1054 of file sparsity.cpp.
Referenced by casadi::CodeGenerator::addSparsity().
{
     return (*this)->sp();
   }
Sparsity casadi::Sparsity::compressed (const std::vector< int > & v) static
Create from a single vector containing the pattern in compressed column storage format: The format: The first two entries are the number of rows (nrow) and columns (ncol) The next ncol+1 entries are the column offsets (colind). Note that the last element, colind[ncol], gives the number of nonzeros The last colind[ncol] entries are the row indices
Definition at line 1058 of file sparsity.cpp.
Referenced by casadi::GenericExternal::get_sparsity_in(), and casadi::GenericExternal::get_sparsity_out().
{
     // Check consistency
     casadi_assert(v.size() >= 2);
     int nrow = v[0];
     int ncol = v[1];
     casadi_assert(v.size() >= 2 + ncol+1);
     int nnz = v[2 + ncol];
     bool dense = v.size() == 2 + ncol+1 && nrow*ncol==nnz;
     bool sparse = v.size() == 2 + ncol+1 + nnz;
     casadi_assert(dense || sparse);
     // Call array version
     return compressed(&v.front());
   }
Sparsity casadi::Sparsity::compressed (const int * v) static
Create from a single vector containing the pattern in compressed column storage format: The format: The first two entries are the number of rows (nrow) and columns (ncol) The next ncol+1 entries are the column offsets (colind). Note that the last element, colind[ncol], gives the number of nonzeros The last colind[ncol] entries are the row indices
Definition at line 1073 of file sparsity.cpp.
{
     casadi_assert(v!=0);
     // Get sparsity pattern
     int nrow = v[0];
     int ncol = v[1];
     const int *colind = v+2;
     int nnz = colind[ncol];
     if (nrow*ncol == nnz) {
       // Dense matrix
       return Sparsity::dense(nrow, ncol);
     } else {
       // Sparse matrix
       const int *row = v + 2 + ncol+1;
       return Sparsity(nrow, ncol,
                       vector<int>(colind, colind+ncol+1),
                       vector<int>(row, row+nnz));
     }
   }
void casadi::SharedObject::count_down () protected inherited
Definition at line 92 of file shared_object.cpp.
Referenced by casadi::Callback::transfer_ownership().
{
     if (node && --node->count == 0) {
       delete node;
       node = 0;
     }
   }
void casadi::SharedObject::count_up () protected inherited
Definition at line 88 of file shared_object.cpp.
{
     if (node) node->count++;
   }
Sparsity casadi::Sparsity::create (SparsityInternal * node) static
Definition at line 68 of file sparsity.cpp.
References casadi::SharedObject::assignNode().
{
     Sparsity ret;
     ret.assignNode(node);
     return ret;
   }
Sparsity casadi::Sparsity::dense (int nrow, int ncol = 1) static
Definition at line 781 of file sparsity.cpp.
Referenced by casadi::Matrix< Scalar >::densify(), casadi::MX::densify(), casadi::Linsol::get_sparsity_in(), casadi::KernelSum::get_sparsity_in(), casadi::Qpsol::get_sparsity_out(), casadi::Linsol::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), casadi::Constant< Value >::getBinary(), casadi::FunctionInternal::getJacSparsity(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::Matrix< Scalar >::inf(), casadi::SqicInterface::init(), casadi::Sqpmethod::init(), casadi::KernelSum::KernelSum(), casadi::Matrix< Scalar >::Matrix(), casadi::Matrix< Scalar >::nan(), casadi::GenericMatrix< Matrix< SXElem > >::ones(), casadi::Qpsol::Qpsol(), casadi::GenericMatrix< Matrix< SXElem > >::sym(), casadi::SymbolicMX::SymbolicMX(), and casadi::GenericMatrix< Matrix< SXElem > >::zeros().
{
     // Column offset
     std::vector<int> colind(ncol+1);
     for (int cc=0; cc<ncol+1; ++cc) colind[cc] = cc*nrow;
     // Row
     std::vector<int> row(ncol*nrow);
     for (int cc=0; cc<ncol; ++cc)
       for (int rr=0; rr<nrow; ++rr)
         row[rr+cc*nrow] = rr;
     return Sparsity(nrow, ncol, colind, row);
   }
static Sparsity casadi::Sparsity::dense (const std::pair< int, int > & rc) inline static
Definition at line 119 of file sparsity.hpp.
References dense().
Referenced by dense().
 { return dense(rc.first, rc.second);}
int casadi::Sparsity::dfs (int j, int top, std::vector< int > & xi, std::vector< int > & pstack, const std::vector< int > & pinv, std::vector< bool > & marked) const
Definition at line 548 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::scc().
{
     return (*this)->dfs(j, top, xi, pstack, pinv, marked);
   }
static Sparsity casadi::Sparsity::diag (int nrow) inline static
Definition at line 136 of file sparsity.hpp.
Referenced by casadi::Matrix< Scalar >::eye(), casadi::Integrator::spJacF(), and casadi::Integrator::spJacG().
 { return diag(nrow, nrow);}
Sparsity casadi::Sparsity::diag (int nrow, int ncol) static
Definition at line 517 of file sparsity.cpp.
References casadi::range().
{
     // Smallest dimension
     int n = min(nrow, ncol);
     // Column offset
     vector<int> colind(ncol+1, n);
     for (int cc=0; cc<n; ++cc) colind[cc] = cc;
     // Row
     vector<int> row = range(n);
     // Create pattern from vectors
     return Sparsity(nrow, ncol, colind, row);
   }
static Sparsity casadi::Sparsity::diag (const std::pair< int, int > & rc) inline static
Definition at line 138 of file sparsity.hpp.
References diag().
Referenced by diag().
 { return diag(rc.first, rc.second);}
Sparsity casadi::Sparsity::diagcat (const std::vector< Sparsity > & v) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1204 of file sparsity.cpp.
Referenced by casadi::Matrix< Scalar >::diagcat().
{
     int n = 0;
     int m = 0;
     std::vector<int> colind(1, 0);
     std::vector<int> row;
     int nz = 0;
     for (int i=0;i<v.size();++i) {
       const int* colind_ = v[i].colind();
       int ncol = v[i].size2();
       const int* row_ = v[i].row();
       int sz = v[i].nnz();
       for (int k=1; k<ncol+1; ++k) {
         colind.push_back(colind_[k]+nz);
       }
       for (int k=0; k<sz; ++k) {
         row.push_back(row_[k]+m);
       }
       n+= v[i].size2();
       m+= v[i].size1();
       nz+= v[i].nnz();
     }
     return Sparsity(m, n, colind, row);
   }
static std::vector< Sparsity > casadi::SparsityInterface< Sparsity >::diagsplit (const Sparsity & x, const std::vector< int > & output_offset) static inherited
static std::vector< Sparsity > casadi::SparsityInterface< Sparsity >::diagsplit (const Sparsity & x, int incr) static inherited
static std::vector< Sparsity > casadi::SparsityInterface< Sparsity >::diagsplit (const Sparsity & x, int incr1, int incr2) static inherited
std::vector< Sparsity > casadi::Sparsity::diagsplit (const Sparsity & x, const std::vector< int > & offset1, const std::vector< int > & offset2) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1293 of file sparsity.cpp.
References casadi::isMonotone(), size1(), and size2().
{
     // Consistency check
     casadi_assert(offset1.size()>=1);
     casadi_assert(offset1.front()==0);
     casadi_assert_message(offset1.back()==x.size1(),
                           "diagsplit(Sparsity, offset1, offset2): Last elements of offset1 "
                           "(" << offset1.back() << ") must equal the number of rows "
                           "(" << x.size1() << ")");
     casadi_assert_message(offset2.back()==x.size2(),
                           "diagsplit(Sparsity, offset1, offset2): Last elements of offset2 "
                           "(" << offset2.back() << ") must equal the number of rows "
                           "(" << x.size2() << ")");
     casadi_assert(isMonotone(offset1));
     casadi_assert(isMonotone(offset2));
     casadi_assert(offset1.size()==offset2.size());
     // Number of outputs
     int n = offset1.size()-1;
     // Return value
     std::vector<Sparsity> ret;
     // Caveat: this is a very silly implementation
     IM x2 = IM::zeros(x);
     for (int i=0; i<n; ++i) {
       ret.push_back(x2(Slice(offset1[i], offset1[i+1]),
                        Slice(offset2[i], offset2[i+1])).sparsity());
     }
     return ret;
   }
std::string casadi::Sparsity::dim () const
Definition at line 536 of file sparsity.cpp.
References casadi::SparsityInternal::dim().
Referenced by add(), append(), appendColumns(), bor(), casadi::Mapaccum::create(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::SundialsInterface::init(), casadi::Linsol::Linsol(), casadi::Mapaccum::Mapaccum(), casadi::Matrix< Scalar >::Matrix(), mul_sparsityF(), mul_sparsityR(), norm_0_mul(), casadi::FunctionInternal::printDimensions(), casadi::Qpsol::Qpsol(), and set().
{
     return (*this)->dim();
   }
void casadi::Sparsity::enlarge (int nrow, int ncol, const std::vector< int > & rr, const std::vector< int > & cc, bool ind1 = false)
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 493 of file sparsity.cpp.
Referenced by casadi::MX::enlarge().
{
     enlargeColumns(ncol, cc, ind1);
     enlargeRows(nrow, rr, ind1);
   }
void casadi::Sparsity::enlargeColumns (int ncol, const std::vector< int > & cc, bool ind1 = false)
Definition at line 499 of file sparsity.cpp.
Referenced by casadi::FunctionInternal::sparsity_jac().
{
     casadi_assert(cc.size() == size2());
     if (cc.empty()) {
       *this = Sparsity(size1(), ncol);
     } else {
       *this = (*this)->_enlargeColumns(ncol, cc, ind1);
     }
   }
void casadi::Sparsity::enlargeRows (int nrow, const std::vector< int > & rr, bool ind1 = false)
Definition at line 508 of file sparsity.cpp.
Referenced by casadi::FunctionInternal::sparsity_jac().
{
     casadi_assert(rr.size() == size1());
     if (rr.empty()) {
       *this = Sparsity(nrow, size2());
     } else {
       *this = (*this)->_enlargeRows(nrow, rr, ind1);
     }
   }
std::vector< int > casadi::Sparsity::erase (const std::vector< int > & rr, const std::vector< int > & cc, bool ind1 = false)
Definition at line 302 of file sparsity.cpp.
References casadi::SparsityInternal::_erase().
Referenced by casadi::MX::erase().
{
     vector<int> mapping;
     *this = (*this)->_erase(rr, cc, ind1, mapping);
     return mapping;
   }
std::vector< int > casadi::Sparsity::erase (const std::vector< int > & rr, bool ind1 = false)
Definition at line 309 of file sparsity.cpp.
References casadi::SparsityInternal::_erase().
{
     vector<int> mapping;
     *this = (*this)->_erase(rr, ind1, mapping);
     return mapping;
   }
std::vector< int > casadi::Sparsity::etree (bool ata = false) const
Definition at line 544 of file sparsity.cpp.
References casadi::SparsityInternal::etree().
{
     return (*this)->etree(ata);
   }
std::vector< int > casadi::Sparsity::find (bool ind1 = SWIG_IND1) const
k = A.find() A[k] will contain the elements of A that are non-zero in B
Definition at line 574 of file sparsity.cpp.
Referenced by casadi::GetNonzeros::eval_mx(), casadi::SetNonzeros< Add >::eval_mx(), casadi::GetNonzeros::evalAdj(), casadi::SetNonzeros< Add >::evalAdj(), casadi::GetNonzeros::evalFwd(), casadi::SetNonzeros< Add >::evalFwd(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), and casadi::FunctionInternal::sparsity_jac().
{
     std::vector<int> loc;
     find(loc, ind1);
     return loc;
   }
void casadi::Sparsity::find (std::vector< int > & loc, bool ind1 = false) const
Definition at line 580 of file sparsity.cpp.
{
     (*this)->find(loc, ind1);
   }
SharedObjectNode * casadi::SharedObject::get () const inherited
Definition at line 80 of file shared_object.cpp.
Referenced by casadi::CodeGenerator::addSparsity(), casadi::CodeGenerator::get_sparsity(), casadi::SparsityInternal::is_equal(), casadi::SparsityInternal::maxTransversal(), and casadi::shared_cast().
{
     return node;
   }
void casadi::Sparsity::get_ccs (std::vector< int > & output_colind, std::vector< int > & output_row) const
Definition at line 339 of file sparsity.cpp.
{
     colind = get_colind();
     row = get_row();
   }
std::vector< int > casadi::Sparsity::get_col () const
Definition at line 331 of file sparsity.cpp.
Referenced by casadi::Matrix< Scalar >::det(), casadi::GetNonzeros::eval_mx(), casadi::SetNonzeros< Add >::eval_mx(), casadi::GetNonzeros::evalAdj(), casadi::SetNonzeros< Add >::evalAdj(), casadi::GetNonzeros::evalFwd(), casadi::SetNonzeros< Add >::evalFwd(), casadi::Matrix< Scalar >::getMinor(), casadi::SnoptInterface::init(), and casadi::KnitroInterface::solve().
{
     return (*this)->get_col();
   }
std::vector< int > casadi::Sparsity::get_colind () const
Definition at line 327 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::amd().
{
     return (*this)->get_colind();
   }
void casadi::Sparsity::get_crs (std::vector< int > & output_rowind, std::vector< int > & output_col) const
Definition at line 344 of file sparsity.cpp.
{
     T().get_ccs(rowind, col);
   }
Sparsity casadi::Sparsity::get_diag (std::vector< int > & output_mapping) const
Get the diagonal of the matrix/create a diagonal matrix (mapping will contain the nonzero mapping) When the input is square, the diagonal elements are returned. If the input is vector-like, a diagonal matrix is constructed with it.
Definition at line 540 of file sparsity.cpp.
References casadi::SparsityInternal::get_diag().
Referenced by casadi::Matrix< Scalar >::diag(), and casadi::MX::diag().
{
     return (*this)->get_diag(mapping);
   }
std::vector< int > casadi::Sparsity::get_lower () const
Definition at line 757 of file sparsity.cpp.
References casadi::SparsityInternal::get_lower().
{
     return (*this)->get_lower();
   }
int casadi::Sparsity::get_nz (int rr, int cc) const
Definition at line 235 of file sparsity.cpp.
Referenced by casadi::SetNonzeros< Add >::eval_mx(), casadi::GetNonzeros::evalAdj(), casadi::GetNonzeros::evalFwd(), casadi::SetNonzeros< Add >::evalFwd(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::Matrix< Scalar >::kron(), casadi::MX::kron(), and kron().
{
     return (*this)->get_nz(rr, cc);
   }
std::vector< int > casadi::Sparsity::get_nz (const std::vector< int > & rr, const std::vector< int > & cc) const
Definition at line 248 of file sparsity.cpp.
References casadi::SparsityInternal::get_nz().
{
     return (*this)->get_nz(rr, cc);
   }
void casadi::Sparsity::get_nz (std::vector< int > & SWIG_INOUTindices) const
std::vector< int > casadi::Sparsity::get_row () const
Definition at line 335 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::amd(), and casadi::KnitroInterface::solve().
{
     return (*this)->get_row();
   }
void casadi::Sparsity::get_triplet (std::vector< int > & output_row, std::vector< int > & output_col) const
Definition at line 348 of file sparsity.cpp.
{
     row = get_row();
     col = get_col();
   }
std::vector< int > casadi::Sparsity::get_upper () const
Definition at line 761 of file sparsity.cpp.
{
     return (*this)->get_upper();
   }
Sparsity::CachingMap & casadi::Sparsity::getCache () static
Definition at line 473 of file sparsity.cpp.
{
     static CachingMap ret;
     return ret;
   }
int casadi::SharedObject::getCount () const inherited
Definition at line 159 of file shared_object.cpp.
References casadi::SharedObjectNode::getCount().
Referenced by casadi::Callback::transfer_ownership().
{
     return (*this)->getCount();
   }
std::string casadi::PrintableObject< SharedObject >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
const Sparsity & casadi::Sparsity::getEmpty () static
Definition at line 488 of file sparsity.cpp.
{
     static EmptySparsity ret;
     return ret;
   }
std::string casadi::PrintableObject< SharedObject >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
const Sparsity & casadi::Sparsity::getScalar () static
Definition at line 478 of file sparsity.cpp.
{
     static ScalarSparsity ret;
     return ret;
   }
const Sparsity & casadi::Sparsity::getScalarSparse () static
Definition at line 483 of file sparsity.cpp.
{
     static ScalarSparseSparsity ret;
     return ret;
   }
bool casadi::Sparsity::has_nz (int rr, int cc) const
Definition at line 230 of file sparsity.cpp.
Referenced by casadi::SparseStorage< casadi::Sparsity >::has_nz().
{
     return get_nz(rr, cc)!=-1;
   }
std::size_t casadi::Sparsity::hash () const
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 629 of file sparsity.cpp.
{
     return (*this)->hash();
   }
Sparsity casadi::Sparsity::horzcat (const std::vector< Sparsity > & sp) static
Definition at line 1105 of file sparsity.cpp.
References casadi::SparsityInternal::size1().
Referenced by casadi::Matrix< Scalar >::horzcat().
{
     // Quick return if possible
     if (sp.empty()) return Sparsity(0, 0);
     if (sp.size()==1) return sp.front();
     // Count total nnz
     int nnz_total = 0;
     for (int i=0; i<sp.size(); ++i) nnz_total += sp[i].nnz();
     // Construct from vectors (triplet format)
     vector<int> ret_row, ret_col;
     ret_row.reserve(nnz_total);
     ret_col.reserve(nnz_total);
     int ret_ncol = 0;
     int ret_nrow = 0;
     for (int i=0; i<sp.size() && ret_nrow==0; ++i)
       ret_nrow = sp[i].size1();
     // Append all patterns
     for (vector<Sparsity>::const_iterator i=sp.begin(); i!=sp.end(); ++i) {
       // Get sparsity pattern
       int sp_nrow = i->size1();
       int sp_ncol = i->size2();
       const int* sp_colind = i->colind();
       const int* sp_row = i->row();
       casadi_assert_message(sp_nrow==ret_nrow || sp_nrow==0,
                             "Sparsity::horzcat: Mismatching number of rows");
       // Add entries to pattern
       for (int cc=0; cc<sp_ncol; ++cc) {
         for (int k=sp_colind[cc]; k<sp_colind[cc+1]; ++k) {
           ret_row.push_back(sp_row[k]);
           ret_col.push_back(cc + ret_ncol);
         }
       }
       // Update offset
       ret_ncol += sp_ncol;
     }
     return Sparsity::triplet(ret_nrow, ret_ncol, ret_row, ret_col);
   }
static std::vector<Sparsity > casadi::SparsityInterface< Sparsity >::horzsplit (const Sparsity & x, int incr) static inherited
std::vector< Sparsity > casadi::Sparsity::horzsplit (const Sparsity & x, const std::vector< int > & output_offset) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1231 of file sparsity.cpp.
References colind(), casadi::copy(), casadi::isMonotone(), row(), size1(), and size2().
Referenced by casadi::Matrix< Scalar >::horzsplit().
{
     // Consistency check
     casadi_assert(offset.size()>=1);
     casadi_assert(offset.front()==0);
     casadi_assert_message(offset.back()==x.size2(),
                           "horzsplit(Sparsity, std::vector<int>): Last elements of offset "
                           "(" << offset.back() << ") must equal the number of columns "
                           "(" << x.size2() << ")");
     casadi_assert(isMonotone(offset));
     // Number of outputs
     int n = offset.size()-1;
     // Get the sparsity of the input
     const int* colind_x = x.colind();
     const int* row_x = x.row();
     // Allocate result
     std::vector<Sparsity> ret;
     ret.reserve(n);
     // Sparsity pattern as CCS vectors
     vector<int> colind, row;
     int ncol, nrow = x.size1();
     // Get the sparsity patterns of the outputs
     for (int i=0; i<n; ++i) {
       int first_col = offset[i];
       int last_col = offset[i+1];
       ncol = last_col - first_col;
       // Construct the sparsity pattern
       colind.resize(ncol+1);
       copy(colind_x+first_col, colind_x+last_col+1, colind.begin());
       for (vector<int>::iterator it=colind.begin()+1; it!=colind.end(); ++it) *it -= colind[0];
       colind[0] = 0;
       row.resize(colind.back());
       copy(row_x+colind_x[first_col], row_x+colind_x[last_col], row.begin());
       // Append to the list
       ret.push_back(Sparsity(nrow, ncol, colind, row));
     }
     // Return (RVO)
     return ret;
   }
Sparsity casadi::Sparsity::intersect (const Sparsity & y, std::vector< unsigned char > & mapping) const
Definition at line 380 of file sparsity.cpp.
References casadi::SparsityInternal::combine().
Referenced by casadi::MXNode::getDot(), casadi::Matrix< Scalar >::project(), and casadi::MX::project().
{
     return (*this)->combine(y, true, true, mapping);
   }
Sparsity casadi::Sparsity::intersect (const Sparsity & y) const
Definition at line 385 of file sparsity.cpp.
References casadi::SparsityInternal::combine().
{
     return (*this)->combine(y, true, true);
   }
bool casadi::Sparsity::is_column () const
Definition at line 268 of file sparsity.cpp.
Referenced by casadi::FunctionInternal::checkMat(), casadi::Rootfinder::init(), and casadi::replaceMat().
{
     return (*this)->is_column();
   }
bool casadi::Sparsity::is_dense () const
Definition at line 256 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes(), casadi::Constant< Value >::getProject(), casadi::Rootfinder::init(), casadi::Integrator::init(), and casadi::Scpgen::regularize().
{
     return (*this)->is_dense();
   }
bool casadi::Sparsity::is_diag () const
Definition at line 260 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes().
{
     return (*this)->is_diag();
   }
bool casadi::Sparsity::is_empty (bool both = false) const
A sparsity is considered empty if one of the dimensions is zero (or optionally both dimensions)
Definition at line 127 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes(), add(), bor(), casadi::FunctionInternal::checkMat(), casadi::ConstantMX::create(), casadi::ZeroByZero::getReshape(), casadi::GenericCall::projectArg(), and set().
{
     return (*this)->is_empty(both);
   }
bool casadi::Sparsity::is_equal (const Sparsity & y) const
Definition at line 393 of file sparsity.cpp.
References casadi::SparsityInternal::is_equal().
{
     return (*this)->is_equal(y);
   }
bool casadi::Sparsity::is_equal (int nrow, int ncol, const std::vector< int > & colind, const std::vector< int > & row) const
Definition at line 397 of file sparsity.cpp.
{
     return (*this)->is_equal(nrow, ncol, colind, row);
   }
bool casadi::Sparsity::is_equal (int nrow, int ncol, const int * colind, const int * row) const
Definition at line 402 of file sparsity.cpp.
{
     return (*this)->is_equal(nrow, ncol, colind, row);
   }
bool casadi::SharedObject::is_null () const inherited
Definition at line 84 of file shared_object.cpp.
Referenced by casadi::FunctionInternal::alloc(), casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::Integrator::fun2problem(), casadi::Switch::generateBody(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), casadi::SundialsInterface::getBandwidth(), casadi::SundialsInterface::getBandwidthB(), casadi::FunctionInternal::getPartition(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Newton::init(), casadi::Integrator::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::FixedStepIntegrator::init(), casadi::CvodesInterface::init_memory(), casadi::IdasInterface::init_memory(), casadi::FixedStepIntegrator::init_memory(), casadi::CvodesInterface::initIterativeLinsol(), casadi::IdasInterface::initIterativeLinsol(), casadi::CvodesInterface::initIterativeLinsolB(), casadi::IdasInterface::initIterativeLinsolB(), casadi::CvodesInterface::initUserDefinedLinsol(), casadi::IdasInterface::initUserDefinedLinsol(), casadi::CvodesInterface::initUserDefinedLinsolB(), casadi::IdasInterface::initUserDefinedLinsolB(), casadi::Integrator::Integrator(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::Linsol(), casadi::SparsityInternal::maxTransversal(), casadi::operator<<(), casadi::IdasInterface::psolveB(), casadi::Qpsol::Qpsol(), casadi::SnoptInterface::set_work(), casadi::RkIntegrator::setupFG(), casadi::CollocationIntegrator::setupFG(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Integrator::spAdj(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), casadi::Integrator::spFwd(), casadi::FunctionInternal::spFwd(), casadi::Callback::transfer_ownership(), uni_coloring(), casadi::SnoptInterface::userfun(), and casadi::Callback::~Callback().
{
     return node==0;
   }
bool casadi::Sparsity::is_row () const
Definition at line 264 of file sparsity.cpp.
{
     return (*this)->is_row();
   }
bool casadi::Sparsity::is_scalar (bool scalar_and_dense = false) const
Definition at line 252 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes(), casadi::FunctionInternal::checkMat(), and casadi::GenericMatrix< MatType >::sym().
{
     return (*this)->is_scalar(scalar_and_dense);
   }
bool casadi::Sparsity::is_singular () const
Definition at line 1048 of file sparsity.cpp.
Referenced by casadi::Rootfinder::init(), casadi::SundialsInterface::init(), casadi::Linsol::Linsol(), and casadi::CsparseInterface::linsol_factorize().
{
     casadi_assert_message(is_square(), "is_singular: only defined for square matrices, but got "
                           << dim());
     return sprank(*this)!=size2();
   }
bool casadi::Sparsity::is_square () const
Definition at line 276 of file sparsity.cpp.
{
     return (*this)->is_square();
   }
bool casadi::Sparsity::is_symmetric () const
Definition at line 280 of file sparsity.cpp.
Referenced by casadi::Qpsol::Qpsol().
{
     return (*this)->is_symmetric();
   }
bool casadi::Sparsity::is_transpose (const Sparsity & y) const
Definition at line 621 of file sparsity.cpp.
{
     return (*this)->is_transpose(*y);
   }
bool casadi::Sparsity::is_tril () const
Definition at line 284 of file sparsity.cpp.
{
     return (*this)->is_tril();
   }
bool casadi::Sparsity::is_triu () const
Definition at line 288 of file sparsity.cpp.
{
     return (*this)->is_triu();
   }
bool casadi::Sparsity::is_vector () const
Definition at line 272 of file sparsity.cpp.
Referenced by casadi::GenericCall::projectArg().
{
     return (*this)->is_vector();
   }
bool casadi::Sparsity::isReshape (const Sparsity & y) const
Definition at line 625 of file sparsity.cpp.
Referenced by casadi::MXNode::getReshape(), casadi::MX::MX(), casadi::Matrix< Scalar >::reshape(), and reshape().
{
     return (*this)->isReshape(*y);
   }
Sparsity casadi::Sparsity::kron (const Sparsity & x, const Sparsity & b) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1147 of file sparsity.cpp.
References get_nz(), size(), size1(), and size2().
{
     Sparsity filler = Sparsity(b.size());
     std::vector< std::vector< Sparsity > >
       blocks(a.size1(), std::vector< Sparsity >(a.size2(), filler));
     for (int i=0; i<a.size1(); ++i) {
       for (int j=0; j<a.size2(); ++j) {
         int k = a.get_nz(i, j);
         if (k!=-1) {
           blocks[i][j] = b;
         }
       }
     }
     return blockcat(blocks);
   }
std::vector< int > casadi::Sparsity::largest_first () const
Definition at line 604 of file sparsity.cpp.
References casadi::SparsityInternal::largest_first().
{
     return (*this)->largest_first();
   }
Sparsity casadi::Sparsity::lower (int n) static
Definition at line 816 of file sparsity.cpp.
Referenced by casadi::Matrix< Scalar >::chol().
{
     casadi_assert_message(n>=0, "Sparsity::lower expects a positive integer as argument");
     int nrow=n, ncol=n;
     std::vector<int> colind, row;
     colind.reserve(ncol+1);
     row.reserve((n*(n+1))/2);
     // Loop over columns
     colind.push_back(0);
     for (int cc=0; cc<ncol; ++cc) {
       // Loop over rows for the lower triangular half
       for (int rr=cc; rr<nrow; ++rr) {
         row.push_back(rr);
       }
       colind.push_back(row.size());
     }
     // Return the pattern
     return Sparsity(nrow, ncol, colind, row);
   }
static Sparsity casadi::Sparsity::mac (const Sparsity & x, const Sparsity & y, const Sparsity & z) inline static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 465 of file sparsity.hpp.
 { return z;}
Sparsity casadi::Sparsity::makeDense (std::vector< int > & mapping) const
Definition at line 532 of file sparsity.cpp.
References casadi::SparsityInternal::makeDense().
{
     return (*this)->makeDense(mapping);
   }
static Sparsity casadi::SparsityInterface< Sparsity >::mtimes (const std::vector< Sparsity > & args) static inherited
Sparsity casadi::Sparsity::mtimes (const Sparsity & x, const Sparsity & y) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 389 of file sparsity.cpp.
References casadi::SparsityInternal::_mtimes().
Referenced by casadi::Matrix< Scalar >::mtimes(), and casadi::MX::mtimes().
{
     return x->_mtimes(y);
   }
void casadi::Sparsity::mul_sparsityF (const bvec_t * x, const Sparsity & x_sp, const bvec_t * y, const Sparsity & y_sp, bvec_t * z, const Sparsity & z_sp, bvec_t * w) static
Definition at line 1419 of file sparsity.cpp.
References colind(), dim(), row(), size1(), and size2().
{
     // Assert dimensions
     casadi_assert_message(z_sp.size1()==x_sp.size1() && x_sp.size2()==y_sp.size1()
                           && y_sp.size2()==z_sp.size2(),
                           "Dimension error. Got x=" << x_sp.dim()
                           << ", y=" << y_sp.dim()
                           << " and z=" << z_sp.dim() << ".");
     // Direct access to the arrays
     const int* y_colind = y_sp.colind();
     const int* y_row = y_sp.row();
     const int* x_colind = x_sp.colind();
     const int* x_row = x_sp.row();
     const int* z_colind = z_sp.colind();
     const int* z_row = z_sp.row();
     // Loop over the columns of y and z
     int ncol = z_sp.size2();
     for (int cc=0; cc<ncol; ++cc) {
       // Get the dense column of z
       for (int kk=z_colind[cc]; kk<z_colind[cc+1]; ++kk) {
         w[z_row[kk]] = z[kk];
       }
       // Loop over the nonzeros of y
       for (int kk=y_colind[cc]; kk<y_colind[cc+1]; ++kk) {
         int rr = y_row[kk];
         // Loop over corresponding columns of x
         bvec_t yy = y[kk];
         for (int kk1=x_colind[rr]; kk1<x_colind[rr+1]; ++kk1) {
           w[x_row[kk1]] |= x[kk1] | yy;
         }
       }
       // Get the sparse column of z
       for (int kk=z_colind[cc]; kk<z_colind[cc+1]; ++kk) {
         z[kk] = w[z_row[kk]];
       }
     }
   }
void casadi::Sparsity::mul_sparsityR (bvec_t * x, const Sparsity & x_sp, bvec_t * y, const Sparsity & y_sp, bvec_t * z, const Sparsity & z_sp, bvec_t * w) static
Definition at line 1464 of file sparsity.cpp.
References colind(), dim(), row(), size1(), and size2().
{
     // Assert dimensions
     casadi_assert_message(z_sp.size1()==x_sp.size1() && x_sp.size2()==y_sp.size1()
                           && y_sp.size2()==z_sp.size2(),
                           "Dimension error. Got x=" << x_sp.dim()
                           << ", y=" << y_sp.dim()
                           << " and z=" << z_sp.dim() << ".");
     // Direct access to the arrays
     const int* y_colind = y_sp.colind();
     const int* y_row = y_sp.row();
     const int* x_colind = x_sp.colind();
     const int* x_row = x_sp.row();
     const int* z_colind = z_sp.colind();
     const int* z_row = z_sp.row();
     // Loop over the columns of y and z
     int ncol = z_sp.size2();
     for (int cc=0; cc<ncol; ++cc) {
       // Get the dense column of z
       for (int kk=z_colind[cc]; kk<z_colind[cc+1]; ++kk) {
         w[z_row[kk]] = z[kk];
       }
       // Loop over the nonzeros of y
       for (int kk=y_colind[cc]; kk<y_colind[cc+1]; ++kk) {
         int rr = y_row[kk];
         // Loop over corresponding columns of x
         bvec_t yy = 0;
         for (int kk1=x_colind[rr]; kk1<x_colind[rr+1]; ++kk1) {
           yy |= w[x_row[kk1]];
           x[kk1] |= w[x_row[kk1]];
         }
         y[kk] |= yy;
       }
       // Get the sparse column of z
       for (int kk=z_colind[cc]; kk<z_colind[cc+1]; ++kk) {
         z[kk] = w[z_row[kk]];
       }
     }
   }
int casadi::Sparsity::nnz () const
See also
numel()
Definition at line 131 of file sparsity.cpp.
Referenced by add(), casadi::SparsityInternal::amd(), bor(), casadi::SparsityInternal::combineGen1(), casadi::Integrator::eval(), casadi::QpoasesInterface::eval(), casadi::Scpgen::eval_mat(), casadi::SetNonzeros< Add >::eval_mx(), casadi::SetNonzeros< Add >::evalAdj(), casadi::SetNonzeros< Add >::evalFwd(), casadi::HorzRepsum::evalGen(), casadi::UnaryMX::generate(), casadi::HorzRepsum::generate(), casadi::IpoptInterface::get_nlp_info(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::MXNode::getProject(), casadi::Switch::init(), casadi::Integrator::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::IpoptInterface::init(), casadi::CsparseInterface::linsol_factorize(), casadi::Matrix< Scalar >::Matrix(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::MX::MX(), casadi::CodeGenerator::project(), casadi::Reshape::Reshape(), set(), casadi::SnoptInterface::set_work(), casadi::WorhpInterface::set_work(), casadi::Sqpmethod::set_work(), casadi::Scpgen::set_work(), casadi::IpoptInterface::set_work(), casadi::KnitroInterface::solve(), casadi::Split::spAdj(), casadi::HorzRepsum::spAdj(), casadi::FunctionInternal::spAdj(), casadi::Split::spFwd(), casadi::HorzRepsum::spFwd(), casadi::FunctionInternal::spFwd(), and casadi::GenericMatrix< MatType >::sym().
{
     return (*this)->nnz();
   }
int casadi::Sparsity::nnz_diag () const
Definition at line 323 of file sparsity.cpp.
{
     return (*this)->nnz_diag();
   }
int casadi::Sparsity::nnz_lower (bool strictly = false) const
Definition at line 315 of file sparsity.cpp.
References casadi::SparsityInternal::nnz_lower().
Referenced by casadi::WorhpInterface::set_work().
{
     return (*this)->nnz_lower(strictly);
   }
int casadi::Sparsity::nnz_upper (bool strictly = false) const
Definition at line 319 of file sparsity.cpp.
Referenced by casadi::OoqpInterface::init().
{
     return (*this)->nnz_upper(strictly);
   }
int casadi::Sparsity::norm_0_mul (const Sparsity & x, const Sparsity & B) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1337 of file sparsity.cpp.
References colind(), dim(), casadi::get_ptr(), row(), size1(), and size2().
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::norm_0_mul().
{
     // Implementation borrowed from Scipy's sparsetools/csr.h
     casadi_assert_message(A.size1()==x.size2(), "Dimension error. Got " << x.dim()
                           << " times " << A.dim() << ".");
     int n_row = A.size2();
     int n_col = x.size1();
     // Allocate work vectors
     std::vector<bool> Bwork(n_col);
     std::vector<int> Iwork(n_row+1+n_col);
     const int* Aj = A.row();
     const int* Ap = A.colind();
     const int* Bj = x.row();
     const int* Bp = x.colind();
     int *Cp = get_ptr(Iwork);
     int *mask = Cp+n_row+1;
     // Pass 1
     // method that uses O(n) temp storage
     std::fill(mask, mask+n_col, -1);
     Cp[0] = 0;
     int nnz = 0;
     for (int i = 0; i < n_row; i++) {
       int row_nnz = 0;
       for (int jj = Ap[i]; jj < Ap[i+1]; jj++) {
         int j = Aj[jj];
         for (int kk = Bp[j]; kk < Bp[j+1]; kk++) {
           int k = Bj[kk];
           if (mask[k] != i) {
             mask[k] = i;
             row_nnz++;
           }
         }
       }
       int next_nnz = nnz + row_nnz;
       nnz = next_nnz;
       Cp[i+1] = nnz;
     }
     // Pass 2
     int *next = get_ptr(Iwork) + n_row+1;
     std::fill(next, next+n_col, -1);
     std::vector<bool> & sums = Bwork;
     std::fill(sums.begin(), sums.end(), false);
     nnz = 0;
     Cp[0] = 0;
     for (int i = 0; i < n_row; i++) {
       int head   = -2;
       int length =  0;
       int jj_start = Ap[i];
       int jj_end   = Ap[i+1];
       for (int jj = jj_start; jj < jj_end; jj++) {
         int j = Aj[jj];
         int kk_start = Bp[j];
         int kk_end   = Bp[j+1];
         for (int kk = kk_start; kk < kk_end; kk++) {
           int k = Bj[kk];
           sums[k] = true;
           if (next[k] == -1) {
             next[k] = head;
             head  = k;
             length++;
           }
         }
       }
       for (int jj = 0; jj < length; jj++) {
         if (sums[head]) {
           nnz++;
         }
         int temp = head;
         head = next[head];
         next[temp] = -1; //clear arrays
         sums[temp] =  0;
       }
       Cp[i+1] = nnz;
     }
     return nnz;
   }
int casadi::Sparsity::numel () const
See also
nnz()
Definition at line 123 of file sparsity.cpp.
Referenced by casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), and casadi::FunctionInternal::getJacSparsityHierarchicalSymm().
{
     return (*this)->numel();
   }
static std::vector<int> casadi::SparsityInterface< Sparsity >::offset (const std::vector< Sparsity > & v, bool vert = true) static inherited
casadi::Sparsity::operator const int * () const
Definition at line 1333 of file sparsity.cpp.
{
     return &(*this)->sp().front();
   }
bool casadi::Sparsity::operator!= (const Sparsity & y) const inline
Definition at line 224 of file sparsity.hpp.
References casadi::is_equal().
 {return !is_equal(y);}
const SparsityInternal & casadi::Sparsity::operator* () const
Definition at line 107 of file sparsity.cpp.
{
     return *static_cast<const SparsityInternal*>(get());
   }
Sparsity casadi::Sparsity::operator* (const Sparsity & b) const
Definition at line 410 of file sparsity.cpp.
{
     std::vector< unsigned char > mapping;
     return intersect(b, mapping);
   }
Sparsity casadi::Sparsity::operator+ (const Sparsity & b) const
Definition at line 406 of file sparsity.cpp.
{
     return unite(b);
   }
const SparsityInternal * casadi::Sparsity::operator-> () const
Definition at line 103 of file sparsity.cpp.
{
     return static_cast<const SparsityInternal*>(SharedObject::operator->());
   }
bool casadi::Sparsity::operator== (const Sparsity & y) const inline
Definition at line 220 of file sparsity.hpp.
References casadi::is_equal().
 { return is_equal(y);}
Sparsity casadi::Sparsity::pattern_inverse () const
Definition at line 415 of file sparsity.cpp.
References casadi::SparsityInternal::pattern_inverse().
{
     return (*this)->pattern_inverse();
   }
Sparsity casadi::Sparsity::pmult (const std::vector< int > & p, bool permute_rows = true, bool permute_columns = true, bool invert_permutation = false) const
Definition at line 608 of file sparsity.cpp.
References casadi::SparsityInternal::pmult().
Referenced by casadi::SparsityInternal::star_coloring(), and casadi::SparsityInternal::star_coloring2().
{
     return (*this)->pmult(p, permute_rows, permute_columns, invert_permutation);
   }
void casadi::SharedObject::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 135 of file shared_object.cpp.
Referenced by casadi::CsparseInterface::linsol_factorize().
{
     if (is_null()) {
       stream << "Null pointer of class \"" << typeid(this).name() << "\"";
     } else {
       (*this)->print(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::Sparsity::print_compact (std::ostream & stream = casadi::userOut()) const
Definition at line 1093 of file sparsity.cpp.
{
     (*this)->print_compact(stream);
   }
void casadi::SharedObject::printPtr (std::ostream & stream = casadi::userOut()) const inherited
Print the pointer to the internal class
Definition at line 144 of file shared_object.cpp.
{
     stream << node;
   }
void casadi::Sparsity::removeDuplicates (std::vector< int > & mapping)
The same indices will be removed from the mapping vector, which must have the same length as the number of nonzeros
Definition at line 570 of file sparsity.cpp.
{
     *this = (*this)->_removeDuplicates(mapping);
   }
static Sparsity casadi::SparsityInterface< Sparsity >::repmat (const Sparsity & x, int n, int m = 1) static inherited
static Sparsity casadi::SparsityInterface< Sparsity >::repmat (const Sparsity & A, const std::pair< int, int > & rc) inline static inherited
Definition at line 179 of file sparsity_interface.hpp.
{
       return MatType::repmat(A, rc.first, rc.second);
     }
void casadi::SharedObject::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 121 of file shared_object.cpp.
{
     if (is_null()) {
       stream << 0;
     } else {
       (*this)->repr(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
Sparsity casadi::Sparsity::reshape (const Sparsity & x, int nrow, int ncol) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 244 of file sparsity.cpp.
References casadi::SparsityInternal::_reshape().
Referenced by casadi::Matrix< Scalar >::reshape().
{
     return x->_reshape(nrow, ncol);
   }
Sparsity casadi::Sparsity::reshape (const Sparsity & x, const Sparsity & sp) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 239 of file sparsity.cpp.
References isReshape().
{
     casadi_assert(x.isReshape(sp));
     return sp;
   }
void casadi::Sparsity::resize (int nrow, int ncol)
Definition at line 177 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::combineGen1(), casadi::Switch::init(), casadi::SparsityInternal::pmult(), and casadi::MXNode::setDependencies().
{
     if (size1()!=nrow || size2() != ncol) {
       *this = (*this)->_resize(nrow, ncol);
     }
   }
const int * casadi::Sparsity::row () const
Definition at line 147 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes(), add(), casadi::KinsolInterface::bjac(), casadi::CvodesInterface::bjac(), casadi::IdasInterface::bjac(), casadi::CvodesInterface::bjacB(), casadi::IdasInterface::bjacB(), bor(), casadi::SparsityInternal::breadthFirstSearch(), casadi::SparsityInternal::combineGen(), casadi::SparsityInternal::counts(), casadi::Matrix< Scalar >::det(), casadi::KinsolInterface::djac(), casadi::CvodesInterface::djac(), casadi::IdasInterface::djac(), casadi::CvodesInterface::djacB(), casadi::IdasInterface::djacB(), casadi::OoqpInterface::eval(), casadi::GurobiInterface::eval(), casadi::QpoasesInterface::eval(), casadi::CplexInterface::eval(), casadi::IpoptUserClass::eval_h(), casadi::IpoptUserClass::eval_jac_g(), casadi::GetNonzeros::eval_mx(), casadi::SetNonzeros< Add >::eval_mx(), casadi::SetNonzeros< Add >::evalAdj(), casadi::GetNonzeros::evalFwd(), casadi::SetNonzeros< Add >::evalFwd(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::Matrix< Scalar >::getMinor(), horzsplit(), casadi::SqicInterface::init(), casadi::CsparseInterface::init_memory(), casadi::SparsityInternal::is_equal(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::linsol_spAdj(), casadi::Linsol::linsol_spFwd(), casadi::Linsol::linsol_spsolve(), mul_sparsityF(), mul_sparsityR(), casadi::SparsityInternal::multiply(), norm_0_mul(), set(), casadi::WorhpInterface::set_work(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::spFwd(), and casadi::SparsityInternal::uni_coloring().
{
     return (*this)->row();
   }
int casadi::Sparsity::row (int el) const
Definition at line 155 of file sparsity.cpp.
{
     if (el<0 || el>=nnz()) {
       std::stringstream ss;
       ss <<  "Sparsity::row: Index " << el << " out of range [0," << nnz() << ")";
       throw std::out_of_range(ss.str());
     }
     return row()[el];
   }
Sparsity casadi::Sparsity::rowcol (const std::vector< int > & row, const std::vector< int > & col, int nrow, int ncol) static
Definition at line 878 of file sparsity.cpp.
{
     std::vector<int> all_rows, all_cols;
     all_rows.reserve(row.size()*col.size());
     all_cols.reserve(row.size()*col.size());
     for (std::vector<int>::const_iterator c_it=col.begin(); c_it!=col.end(); ++c_it) {
       casadi_assert_message(*c_it>=0 && *c_it<ncol, "Sparsity::rowcol: Column index out of bounds");
       for (std::vector<int>::const_iterator r_it=row.begin(); r_it!=row.end(); ++r_it) {
         casadi_assert_message(*r_it>=0 && *r_it<nrow, "Sparsity::rowcol: Row index out of bounds");
         all_rows.push_back(*r_it);
         all_cols.push_back(*c_it);
       }
     }
     return Sparsity::triplet(nrow, ncol, all_rows, all_cols);
   }
bool casadi::Sparsity::rowsSequential (bool strictly = true) const
Parameters
[in] strictly if true, then do not allow multiple entries
Definition at line 566 of file sparsity.cpp.
{
     return (*this)->rowsSequential(strictly);
   }
void casadi::Sparsity::sanity_check (bool complete = false) const
Parameters
complete set to true to also check elementwise throws an error as possible result
Definition at line 173 of file sparsity.cpp.
Referenced by casadi::SnoptInterface::userfun().
{
     (*this)->sanity_check(complete);
   }
static Sparsity casadi::Sparsity::scalar (bool dense_scalar = true) inline static
Definition at line 112 of file sparsity.hpp.
Referenced by casadi::Call::Call(), casadi::Switch::get_forward(), casadi::Switch::get_sparsity_in(), casadi::Jit::get_sparsity_in(), casadi::SimplifiedExternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Qpsol::get_sparsity_out(), casadi::Jit::get_sparsity_out(), casadi::Nlpsol::get_sparsity_out(), casadi::SimplifiedExternal::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), and casadi::Split::Split().
     { return dense_scalar ? dense(1, 1) : Sparsity(1, 1); }
int casadi::Sparsity::scc (std::vector< int > & output_index, std::vector< int > & output_offset) const
See Direct Methods for Sparse Linear Systems by Davis (2006). Returns:
Number of components
Offset for each components (length: 1 + number of components)
Indices for each components, component i has indices index[offset[i]], ..., index[offset[i+1]]
In the case that the matrix is symmetric, the result has a particular interpretation: Given a symmetric matrix A and n = A.scc(p, r)
=> A[p, p] will appear block-diagonal with n blocks and with the indices of the block boundaries to be found in r.
Examples:
matrix/scc.py.
Definition at line 554 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::btfUpper().
{
     return (*this)->scc(p, r);
   }
const Sparsity & casadi::SparsityInterface< Sparsity >::self () const inline protected inherited
Definition at line 51 of file sparsity_interface.hpp.
 { return static_cast<const MatType&>(*this); }
Sparsity & casadi::SparsityInterface< Sparsity >::self () inline protected inherited
Definition at line 52 of file sparsity_interface.hpp.
 { return static_cast<MatType&>(*this); }
template<typename T > void casadi::Sparsity::set (T * data, const T * val_data, const Sparsity & val_sp) const
template<typename DataType > void casadi::Sparsity::set (DataType * data, const DataType * val_data, const Sparsity & val_sp) const
Definition at line 762 of file sparsity.hpp.
References colind(), dim(), is_empty(), nnz(), row(), size1(), and size2().
{
     // Get dimensions of this
     const int sz = nnz();
     const int sz1 = size1();
     const int sz2 = size2();
     // Get dimensions of assigning matrix
     const int val_sz = val_sp.nnz();
     const int val_sz1 = val_sp.size1();
     const int val_sz2 = val_sp.size2();
     const int val_nel = val_sz1*val_sz2;
     // Check if sparsity matches
     if (val_sp==*this) {
       std::copy(val_data, val_data+sz, data);
     } else if (this->is_empty()) {
       // Quick return
       return;
     } else if (val_sp.is_empty()) {
       // Quick return
       return;
     } else if (val_nel==1) { // if scalar
       std::fill(data, data+sz, val_sz==0 ? DataType(0) : val_data[0]);
     } else if (sz2==val_sz2 && sz1==val_sz1) {
       // Matching dimensions
       // Sparsity
       const int* c = row();
       const int* rind = colind();
       const int* v_c = val_sp.row();
       const int* v_rind = val_sp.colind();
       // For all columns
       for (int i=0; i<sz2; ++i) {
         // Nonzero of the assigning matrix
         int v_el = v_rind[i];
         // First nonzero of the following column
         int v_el_end = v_rind[i+1];
         // Next row of the assigning matrix
         int v_j = v_el<v_el_end ? v_c[v_el] : sz1;
         // Assign all nonzeros
         for (int el=rind[i]; el!=rind[i+1]; ++el) {
           //  Get row
           int j=c[el];
           // Forward the assigning nonzero
           while (v_j<j) {
             v_el++;
             v_j = v_el<v_el_end ? v_c[v_el] : sz1;
           }
           // Assign nonzero
           if (v_j==j) {
             data[el] = val_data[v_el++];
             v_j = v_el<v_el_end ? v_c[v_el] : sz1;
           } else {
             data[el] = 0;
           }
         }
       }
     } else if (sz1==val_sz2 && sz2==val_sz1 && sz2 == 1) {
       // Assign transposed (this is column)
       const int* v_cind = val_sp.colind();
       const int* r = row();
       for (int el=0; el<sz; ++el) {
         int rr=r[el];
         data[el] = v_cind[rr]==v_cind[rr+1] ? 0 : val_data[v_cind[rr]];
       }
     } else if (sz1==val_sz2 && sz2==val_sz1 && sz1 == 1) {
       // Assign transposed (this is row)
       for (int el=0; el<sz; ++el) data[el] = 0;
       const int* cind = colind();
       const int* v_r = val_sp.row();
       for (int el=0; el<val_sz; ++el) {
         int rr=v_r[el];
         if (cind[rr]!=cind[rr+1]) {
           data[cind[rr]] = val_data[el];
         }
       }
     } else {
       // Make sure that dimension matches
       casadi_error("Sparsity::set<DataType>: shape mismatch. lhs is matrix of shape "
                    << dim() << ", while rhs is shape " << val_sp.dim() << ".");
     }
   }
std::pair< int, int > casadi::Sparsity::size () const
Definition at line 135 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes(), casadi::FunctionInternal::checkMat(), casadi::GetNonzeros::eval_mx(), casadi::GetNonzeros::evalFwd(), casadi::FunctionInternal::forward(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::MXNode::getBinarySwitch(), casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::Integrator::init(), kron(), casadi::MX::MX(), casadi::GenericCall::projectArg(), casadi::replaceMat(), casadi::FunctionInternal::reverse(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::simpleIntegrator(), and casadi::MXNode::toMatrix().
{
     return (*this)->size();
   }
int casadi::Sparsity::size (int axis) const
Definition at line 139 of file sparsity.cpp.
{
     switch (axis) {
     case 1: return size1();
     case 2: return size2();
     }
     casadi_error("Axis must be 1 or 2.");
   }
int casadi::Sparsity::size1 () const
Definition at line 115 of file sparsity.cpp.
References casadi::SparsityInternal::size1().
Referenced by add(), casadi::SparsityInternal::amd(), append(), appendColumns(), bor(), casadi::FunctionInternal::checkMat(), casadi::SparsityInternal::combineGen(), diagsplit(), casadi::QpoasesInterface::eval(), casadi::GetNonzeros::eval_mx(), casadi::SetNonzeros< Add >::eval_mx(), casadi::SetNonzeros< Add >::evalAdj(), casadi::GetNonzeros::evalFwd(), casadi::SetNonzeros< Add >::evalFwd(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::FunctionInternal::getPartition(), horzsplit(), casadi::SparsityInternal::is_equal(), kron(), casadi::Linsol::Linsol(), casadi::Linsol::linsol_spAdj(), casadi::Linsol::linsol_spFwd(), mul_sparsityF(), mul_sparsityR(), casadi::SparsityInternal::multiply(), norm_0_mul(), casadi::Vertcat::offset(), casadi::Diagcat::offset(), casadi::GenericCall::projectArg(), casadi::Qpsol::Qpsol(), casadi::replaceMat(), set(), casadi::simpleIntegrator(), and casadi::FunctionInternal::sparsity_jac().
{
     return (*this)->size1();
   }
int casadi::Sparsity::size2 () const
Definition at line 119 of file sparsity.cpp.
Referenced by casadi::SparsityInternal::_mtimes(), add(), casadi::SparsityInternal::amd(), append(), appendColumns(), bor(), casadi::FunctionInternal::checkMat(), casadi::SparsityInternal::combineGen(), diagsplit(), casadi::QpoasesInterface::eval(), casadi::IpoptUserClass::eval_h(), casadi::IpoptUserClass::eval_jac_g(), casadi::GetNonzeros::eval_mx(), casadi::SetNonzeros< Add >::evalAdj(), casadi::GetNonzeros::evalFwd(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::FunctionInternal::getPartition(), horzsplit(), casadi::CplexInterface::init_memory(), casadi::SparsityInternal::is_equal(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), kron(), casadi::Linsol::Linsol(), mul_sparsityF(), mul_sparsityR(), casadi::SparsityInternal::multiply(), norm_0_mul(), casadi::Horzcat::offset(), casadi::Diagcat::offset(), casadi::GenericCall::projectArg(), casadi::Qpsol::Qpsol(), casadi::replaceMat(), set(), casadi::Sqpmethod::solve(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), and casadi::FunctionInternal::spFwd().
{
     return (*this)->size2();
   }
int casadi::Sparsity::sprank (const Sparsity & x) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1327 of file sparsity.cpp.
References btf().
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::sprank().
{
     std::vector<int> rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock;
     x.btf(rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock);
     return coarse_colblock.at(3);
   }
void casadi::Sparsity::spy (std::ostream & stream = casadi::userOut()) const
Definition at line 617 of file sparsity.cpp.
{
     (*this)->spy(stream);
   }
void casadi::Sparsity::spy_matlab (const std::string & mfile) const
Definition at line 613 of file sparsity.cpp.
References casadi::SparsityInternal::spy_matlab().
{
     (*this)->spy_matlab(mfile);
   }
Sparsity casadi::Sparsity::star_coloring (int ordering = 1, int cutoff = std::numeric_limits<int>::max()) const
Ordering options: None (0), largest first (1)
Definition at line 596 of file sparsity.cpp.
References casadi::SparsityInternal::star_coloring().
Referenced by casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::FunctionInternal::getPartition(), and casadi::SparsityInternal::star_coloring().
{
     return (*this)->star_coloring(ordering, cutoff);
   }
Sparsity casadi::Sparsity::star_coloring2 (int ordering = 1, int cutoff = std::numeric_limits<int>::max()) const
Ordering options: None (0), largest first (1)
Definition at line 600 of file sparsity.cpp.
References casadi::SparsityInternal::star_coloring2().
Referenced by casadi::SparsityInternal::star_coloring2().
{
     return (*this)->star_coloring2(ordering, cutoff);
   }
Sparsity casadi::Sparsity::sub (const std::vector< int > & rr, const std::vector< int > & cc, std::vector< int > & output_mapping, bool ind1 = false) const
Returns the sparsity of the submatrix, with a mapping such that submatrix[k] = originalmatrix[mapping[k]]
Definition at line 297 of file sparsity.cpp.
References casadi::SparsityInternal::sub().
Referenced by casadi::Matrix< Scalar >::get(), and casadi::MX::get().
{
     return (*this)->sub(rr, cc, mapping, ind1);
   }
Sparsity casadi::Sparsity::sub (const std::vector< int > & rr, const Sparsity & sp, std::vector< int > & output_mapping, bool ind1 = false) const
Returns the sparsity of the corresponding elements, with a mapping such that submatrix[k] = originalmatrix[mapping[k]]
Definition at line 292 of file sparsity.cpp.
References casadi::SparsityInternal::sub().
{
     return (*this)->sub(rr, *sp, mapping, ind1);
   }
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 153 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
Sparsity casadi::Sparsity::T () const
Definition at line 357 of file sparsity.cpp.
References casadi::SparsityInternal::T().
Referenced by casadi::SparsityInternal::amd(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::Matrix< Scalar >::get_nz(), casadi::MX::get_nz(), casadi::FunctionInternal::getJacSparsity(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::FunctionInternal::getPartition(), casadi::OoqpInterface::init(), casadi::Scpgen::init(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Transpose::Transpose(), and vertsplit().
{
     return (*this)->T();
   }
bool casadi::Sparsity::test_cast (const SharedObjectNode * ptr) static
Definition at line 111 of file sparsity.cpp.
{
     return dynamic_cast<const SparsityInternal*>(ptr)!=0;
   }
Sparsity casadi::Sparsity::transpose (std::vector< int > & mapping, bool invert_mapping = false) const
Parameters
[out] mapping the non-zeros of the original matrix for each non-zero of the new matrix
Definition at line 353 of file sparsity.cpp.
References casadi::SparsityInternal::transpose().
Referenced by casadi::XFunction< DerivedType, MatType, NodeType >::jac(), and casadi::Matrix< Scalar >::T().
{
     return (*this)->transpose(mapping, invert_mapping);
   }
Sparsity casadi::Sparsity::tril (const Sparsity & x, bool includeDiagonal = true) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 749 of file sparsity.cpp.
References casadi::SparsityInternal::_tril().
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::tril().
{
     return x->_tril(includeDiagonal);
   }
Sparsity casadi::Sparsity::triplet (int nrow, int ncol, const std::vector< int > & row, const std::vector< int > & col, std::vector< int > & mapping, bool invert_mapping = false) static
Definition at line 894 of file sparsity.cpp.
References casadi::copy(), and casadi::fill().
Referenced by casadi::FunctionInternal::getJacSparsityGen(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Matrix< Scalar >::set(), and casadi::Matrix< Scalar >::triplet().
{
     // Assert dimensions
     casadi_assert_message(col.size()==row.size(), "inconsistent lengths");
     // Create the return sparsity pattern and access vectors
     std::vector<int> r_colind(ncol+1, 0);
     std::vector<int> r_row;
     r_row.reserve(row.size());
     // Consistency check and check if elements are already perfectly ordered with no duplicates
     int last_col=-1, last_row=-1;
     bool perfectly_ordered=true;
     for (int k=0; k<col.size(); ++k) {
       // Consistency check
       casadi_assert_message(col[k]>=0 && col[k]<ncol, "Col index out of bounds");
       casadi_assert_message(row[k]>=0 && row[k]<nrow, "Row index out of bounds");
       // Check if ordering is already perfect
       perfectly_ordered = perfectly_ordered && (col[k]<last_col ||
                                                 (col[k]==last_col && row[k]<=last_row));
       last_col = col[k];
       last_row = row[k];
     }
     // Quick return if perfectly ordered
     if (perfectly_ordered) {
       // Save rows
       r_row.resize(row.size());
       copy(row.begin(), row.end(), r_row.begin());
       // Find offset index
       int el=0;
       for (int i=0; i<ncol; ++i) {
         while (el<col.size() && col[el]==i) el++;
         r_colind[i+1] = el;
       }
       // Identity mapping
       mapping.resize(row.size());
       for (int k=0; k<row.size(); ++k)
         mapping[k] = k;
       // Quick return
       return Sparsity(nrow, ncol, r_colind, r_row);
     }
     // Reuse data
     std::vector<int>& mapping1 = invert_mapping ? r_row : mapping;
     std::vector<int>& mapping2 = invert_mapping ? mapping : r_row;
     // Make sure that enough memory is allocated to use as a work vector
     mapping1.reserve(std::max(nrow+1, static_cast<int>(col.size())));
     // Number of elements in each row
     std::vector<int>& rowcount = mapping1; // reuse memory
     rowcount.resize(nrow+1);
     fill(rowcount.begin(), rowcount.end(), 0);
     for (std::vector<int>::const_iterator it=row.begin(); it!=row.end(); ++it) {
       rowcount[*it+1]++;
     }
     // Cumsum to get index offset for each row
     for (int i=0; i<nrow; ++i) {
       rowcount[i+1] += rowcount[i];
     }
     // New row for each old row
     mapping2.resize(row.size());
     for (int k=0; k<row.size(); ++k) {
       mapping2[rowcount[row[k]]++] = k;
     }
     // Number of elements in each col
     std::vector<int>& colcount = r_colind; // reuse memory, r_colind is already the right size
                                            // and is filled with zeros
     for (std::vector<int>::const_iterator it=mapping2.begin(); it!=mapping2.end(); ++it) {
       colcount[col[*it]+1]++;
     }
     // Cumsum to get index offset for each col
     for (int i=0; i<ncol; ++i) {
       colcount[i+1] += colcount[i];
     }
     // New col for each old col
     mapping1.resize(col.size());
     for (std::vector<int>::const_iterator it=mapping2.begin(); it!=mapping2.end(); ++it) {
       mapping1[colcount[col[*it]]++] = *it;
     }
     // Current element in the return matrix
     int r_el = 0;
     r_row.resize(col.size());
     // Current nonzero
     std::vector<int>::const_iterator it=mapping1.begin();
     // Loop over columns
     r_colind[0] = 0;
     for (int i=0; i<ncol; ++i) {
       // Previous row (to detect duplicates)
       int j_prev = -1;
       // Loop over nonzero elements of the col
       while (it!=mapping1.end() && col[*it]==i) {
         // Get the element
         int el = *it;
         it++;
         // Get the row
         int j = row[el];
         // If not a duplicate, save to return matrix
         if (j!=j_prev)
           r_row[r_el++] = j;
         if (invert_mapping) {
           // Save to the inverse mapping
           mapping2[el] = r_el-1;
         } else {
           // If not a duplicate, save to the mapping vector
           if (j!=j_prev)
             mapping1[r_el-1] = el;
         }
         // Save row
         j_prev = j;
       }
       // Update col offset
       r_colind[i+1] = r_el;
     }
     // Resize the row vector
     r_row.resize(r_el);
     // Resize mapping matrix
     if (!invert_mapping) {
       mapping1.resize(r_el);
     }
     return Sparsity(nrow, ncol, r_colind, r_row);
   }
Sparsity casadi::Sparsity::triplet (int nrow, int ncol, const std::vector< int > & row, const std::vector< int > & col) static
Definition at line 1042 of file sparsity.cpp.
{
     std::vector<int> mapping;
     return Sparsity::triplet(nrow, ncol, row, col, mapping, false);
   }
Sparsity casadi::Sparsity::triu (const Sparsity & x, bool includeDiagonal = true) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 753 of file sparsity.cpp.
References casadi::SparsityInternal::_triu().
Referenced by casadi::GenericMatrix< Matrix< SXElem > >::triu().
{
     return x->_triu(includeDiagonal);
   }
Sparsity casadi::Sparsity::uni_coloring (const Sparsity & AT = Sparsity(), int cutoff = std::numeric_limits<int>::max()) const
Examples:
matrix/coloring.py.
Definition at line 588 of file sparsity.cpp.
References casadi::SharedObject::is_null(), and casadi::SparsityInternal::uni_coloring().
Referenced by casadi::FunctionInternal::getJacSparsityHierarchical(), and casadi::FunctionInternal::getPartition().
{
     if (AT.is_null()) {
       return (*this)->uni_coloring(T(), cutoff);
     } else {
       return (*this)->uni_coloring(AT, cutoff);
     }
   }
Sparsity casadi::Sparsity::unit (int n, int el) static
Definition at line 871 of file sparsity.cpp.
{
     std::vector<int> row(1, el), colind(2);
     colind[0] = 0;
     colind[1] = 1;
     return Sparsity(n, 1, colind, row);
   }
Sparsity casadi::Sparsity::unite (const Sparsity & y, std::vector< unsigned char > & mapping) const
Definition at line 372 of file sparsity.cpp.
References casadi::SparsityInternal::combine().
Referenced by casadi::SetNonzeros< Add >::eval_mx(), casadi::GetNonzeros::evalAdj(), casadi::SetNonzeros< Add >::evalFwd(), casadi::Switch::get_sparsity_in(), casadi::Switch::get_sparsity_out(), casadi::Matrix< Scalar >::unite(), and casadi::MX::unite().
{
     return (*this)->combine(y, false, false, mapping);
   }
Sparsity casadi::Sparsity::unite (const Sparsity & y) const
Definition at line 376 of file sparsity.cpp.
References casadi::SparsityInternal::combine().
{
     return (*this)->combine(y, false, false);
   }
Sparsity casadi::Sparsity::upper (int n) static
Definition at line 795 of file sparsity.cpp.
{
     casadi_assert_message(n>=0, "Sparsity::upper expects a positive integer as argument");
     int nrow=n, ncol=n;
     std::vector<int> colind, row;
     colind.reserve(ncol+1);
     row.reserve((n*(n+1))/2);
     // Loop over columns
     colind.push_back(0);
     for (int cc=0; cc<ncol; ++cc) {
       // Loop over rows for the upper triangular half
       for (int rr=0; rr<=cc; ++rr) {
         row.push_back(rr);
       }
       colind.push_back(row.size());
     }
     // Return the pattern
     return Sparsity(nrow, ncol, colind, row);
   }
static Sparsity casadi::SparsityInterface< Sparsity >::vec (const Sparsity & x) static inherited
static Sparsity casadi::SparsityInterface< Sparsity >::veccat (const std::vector< Sparsity > & x) static inherited
Sparsity casadi::Sparsity::vertcat (const std::vector< Sparsity > & sp) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1162 of file sparsity.cpp.
References casadi::SparsityInternal::size1().
{
     // Quick return if possible
     if (sp.empty()) return Sparsity(0, 0);
     if (sp.size()==1) return sp.front();
     // Count total nnz
     int nnz_total = 0;
     for (int i=0; i<sp.size(); ++i) nnz_total += sp[i].nnz();
     // Construct from vectors (triplet format)
     vector<int> ret_row, ret_col;
     ret_row.reserve(nnz_total);
     ret_col.reserve(nnz_total);
     int ret_nrow = 0;
     int ret_ncol = 0;
     for (int i=0; i<sp.size() && ret_ncol==0; ++i)
       ret_ncol = sp[i].size2();
     // Append all patterns
     for (vector<Sparsity>::const_iterator i=sp.begin(); i!=sp.end(); ++i) {
       // Get sparsity pattern
       int sp_nrow = i->size1();
       int sp_ncol = i->size2();
       const int* sp_colind = i->colind();
       const int* sp_row = i->row();
       casadi_assert_message(sp_ncol==ret_ncol || sp_ncol==0,
                             "Sparsity::vertcat: Mismatching number of columns");
       // Add entries to pattern
       for (int cc=0; cc<sp_ncol; ++cc) {
         for (int k=sp_colind[cc]; k<sp_colind[cc+1]; ++k) {
           ret_row.push_back(sp_row[k] + ret_nrow);
           ret_col.push_back(cc);
         }
       }
       // Update offset
       ret_nrow += sp_nrow;
     }
     return Sparsity::triplet(ret_nrow, ret_ncol, ret_row, ret_col);
   }
static std::vector<Sparsity > casadi::SparsityInterface< Sparsity >::vertsplit (const Sparsity & x, int incr) static inherited
std::vector< Sparsity > casadi::Sparsity::vertsplit (const Sparsity & x, const std::vector< int > & output_offset) static
For the matrices A to B A(m, n) length(jj)=m , length(ii)=n B(nrow, ncol)
A=enlarge(m, n, ii, jj) makes sure that
B[jj, ii] == A
Definition at line 1278 of file sparsity.cpp.
References T().
{
     std::vector<Sparsity> ret = horzsplit(x.T(), offset);
     for (std::vector<Sparsity>::iterator it=ret.begin(); it!=ret.end(); ++it) {
       *it = it->T();
     }
     return ret;
   }
WeakRef * casadi::SharedObject::weak () inherited
Definition at line 167 of file shared_object.cpp.
References casadi::SharedObjectNode::weak().
Referenced by casadi::WeakRef::WeakRef().
{
     return (*this)->weak();
   }
The documentation for this class was generated from the following files:
sparsity.hpp
sparsity.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge