CasADi: casadi::casadi_math< int > Struct Template Reference
casadi::casadi_math< int > Struct Template Reference
Specialize the class so that it can be used with integer type.
#include <calculus.hpp>
Detailed Description
template<>
struct casadi::casadi_math< int >
Definition at line 1090 of file calculus.hpp.
Static Public Member Functions
static void fun (unsigned char op, const int &x, const int &y, int &f)
Evaluate a built in function.
static void fun (unsigned char op, const int *x, const int *y, int *f, int n)
static void fun (unsigned char op, const int *x, const int &y, int *f, int n)
static void fun (unsigned char op, const int &x, const int *y, int *f, int n)
static void der (unsigned char op, const int &x, const int &y, const int &f, int *d)
Evaluate a built in derivative function.
static void derF (unsigned char op, const int &x, const int &y, int &f, int *d)
Evaluate the function and the derivative function.
static int ndeps (unsigned char op)
Number of dependencies.
static void print (unsigned char op, std::ostream &stream, const std::string &x, const std::string &y)
Print.
static void printPre (unsigned char op, std::ostream &stream)
static const char * name (unsigned char op)
static void printSep (unsigned char op, std::ostream &stream)
static void printPost (unsigned char op, std::ostream &stream)
Member Function Documentation
static void casadi::casadi_math< int >::der (unsigned char op, const int & x, const int & y, const int & f, int * d) inline static
Definition at line 1124 of file calculus.hpp.
References casadi::casadi_math< T >::der().
{
       double d_real[2] = {static_cast<double>(d[0]), static_cast<double>(d[1])};
       casadi_math<double>::der(op, static_cast<double>(x), static_cast<double>(y),
                                static_cast<double>(f), d_real);
       d[0] = static_cast<int>(d_real[0]);
       d[1] = static_cast<int>(d_real[1]);
     }
static void casadi::casadi_math< int >::derF (unsigned char op, const int & x, const int & y, int & f, int * d) inline static
Definition at line 1133 of file calculus.hpp.
References casadi::casadi_math< T >::derF().
{
       double d_real[2] = {static_cast<double>(d[0]), static_cast<double>(d[1])};
       double f_real(f);
       casadi_math<double>::derF(op, static_cast<double>(x), static_cast<double>(y), f_real, d_real);
       f = static_cast<int>(f_real);
       d[0] = static_cast<int>(d_real[0]);
       d[1] = static_cast<int>(d_real[1]);
     }
static void casadi::casadi_math< int >::fun (unsigned char op, const int & x, const int & y, int & f) inline static
Definition at line 1093 of file calculus.hpp.
References casadi::casadi_math< T >::fun().
{
       double ff(0);
       casadi_math<double>::fun(op, static_cast<double>(x), static_cast<double>(y), ff);
       f = static_cast<int>(ff);
     }
static void casadi::casadi_math< int >::fun (unsigned char op, const int * x, const int * y, int * f, int n) inline static
Definition at line 1099 of file calculus.hpp.
References casadi::casadi_math< T >::fun().
{
       for (int i=0; i<n; ++i) {
         double ff(0);
         casadi_math<double>::fun(op, static_cast<double>(*x++), static_cast<double>(*y++), ff);
         *f++ = static_cast<int>(ff);
       }
     }
static void casadi::casadi_math< int >::fun (unsigned char op, const int * x, const int & y, int * f, int n) inline static
Definition at line 1107 of file calculus.hpp.
References casadi::casadi_math< T >::fun().
{
       for (int i=0; i<n; ++i) {
         double ff;
         casadi_math<double>::fun(op, static_cast<double>(*x++), static_cast<double>(y), ff);
         *f++ = static_cast<int>(ff);
       }
     }
static void casadi::casadi_math< int >::fun (unsigned char op, const int & x, const int * y, int * f, int n) inline static
Definition at line 1115 of file calculus.hpp.
References casadi::casadi_math< T >::fun().
{
       for (int i=0; i<n; ++i) {
         double ff;
         casadi_math<double>::fun(op, static_cast<double>(x), static_cast<double>(*y++), ff);
         *f++ = static_cast<int>(ff);
       }
     }
static const char* casadi::casadi_math< int >::name (unsigned char op) inline static
Definition at line 1155 of file calculus.hpp.
References casadi::casadi_math< T >::name().
{
       return casadi_math<double>::name(op);
     }
static int casadi::casadi_math< int >::ndeps (unsigned char op) inline static
Definition at line 1143 of file calculus.hpp.
References casadi::casadi_math< T >::ndeps().
{
       return casadi_math<double>::ndeps(op);
     }
static void casadi::casadi_math< int >::print (unsigned char op, std::ostream & stream, const std::string & x, const std::string & y) inline static
Definition at line 1148 of file calculus.hpp.
References casadi::casadi_math< T >::print().
{
       casadi_math<double>::print(op, stream, x, y);
     }
static void casadi::casadi_math< int >::printPost (unsigned char op, std::ostream & stream) inline static
Definition at line 1161 of file calculus.hpp.
References casadi::casadi_math< T >::printPost().
{
       casadi_math<double>::printPost(op, stream);
     }
static void casadi::casadi_math< int >::printPre (unsigned char op, std::ostream & stream) inline static
Definition at line 1152 of file calculus.hpp.
References casadi::casadi_math< T >::printPre().
{
       casadi_math<double>::printPre(op, stream);
     }
static void casadi::casadi_math< int >::printSep (unsigned char op, std::ostream & stream) inline static
Definition at line 1158 of file calculus.hpp.
References casadi::casadi_math< T >::printSep().
{
       casadi_math<double>::printSep(op, stream);
     }
The documentation for this struct was generated from the following file:
calculus.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge