CasADi: casadi::IpoptUserClass Class Reference
casadi::IpoptUserClass Class Reference
#include <ipopt_nlp.hpp>
Detailed Description
Definition at line 55 of file ipopt_nlp.hpp.
Public Member Functions
IpoptUserClass (const IpoptInterface &ipoptInterface, IpoptMemory *mem)
virtual ~IpoptUserClass ()
virtual bool get_nlp_info (Index &n, Index &m, Index &nnz_jac_g, Index &nnz_h_lag, IndexStyleEnum &index_style)
virtual bool get_bounds_info (Index n, Number *x_l, Number *x_u, Index m, Number *g_l, Number *g_u)
virtual bool get_starting_point (Index n, bool init_x, Number *x, bool init_z, Number *z_L, Number *z_U, Index m, bool init_lambda, Number *lambda)
virtual bool eval_f (Index n, const Number *x, bool new_x, Number &obj_value)
virtual bool eval_grad_f (Index n, const Number *x, bool new_x, Number *grad_f)
virtual bool eval_g (Index n, const Number *x, bool new_x, Index m, Number *g)
virtual bool eval_jac_g (Index n, const Number *x, bool new_x, Index m, Index nele_jac, Index *iRow, Index *jCol, Number *values)
virtual bool eval_h (Index n, const Number *x, bool new_x, Number obj_factor, Index m, const Number *lambda, bool new_lambda, Index nele_hess, Index *iRow, Index *jCol, Number *values)
virtual void finalize_solution (SolverReturn status, Index n, const Number *x, const Number *z_L, const Number *z_U, Index m, const Number *g, const Number *lambda, Number obj_value, const IpoptData *ip_data, IpoptCalculatedQuantities *ip_cq)
virtual Index get_number_of_nonlinear_variables ()
virtual bool get_list_of_nonlinear_variables (Index num_nonlin_vars, Index *pos_nonlin_vars)
virtual bool intermediate_callback (AlgorithmMode mode, Index iter, Number obj_value, Number inf_pr, Number inf_du, Number mu, Number d_norm, Number regularization_size, Number alpha_du, Number alpha_pr, Index ls_trials, const IpoptData *ip_data, IpoptCalculatedQuantities *ip_cq)
virtual bool get_var_con_metadata (Index n, StringMetaDataMapType &var_string_md, IntegerMetaDataMapType &var_integer_md, NumericMetaDataMapType &var_numeric_md, Index m, StringMetaDataMapType &con_string_md, IntegerMetaDataMapType &con_integer_md, NumericMetaDataMapType &con_numeric_md)
virtual void finalize_metadata (Index n, const StringMetaDataMapType &var_string_md, const IntegerMetaDataMapType &var_integer_md, const NumericMetaDataMapType &var_numeric_md, Index m, const StringMetaDataMapType &con_string_md, const IntegerMetaDataMapType &con_integer_md, const NumericMetaDataMapType &con_numeric_md)
Constructor & Destructor Documentation
casadi::IpoptUserClass::IpoptUserClass (const IpoptInterface & ipoptInterface, IpoptMemory * mem)
Definition at line 32 of file ipopt_nlp.cpp.
References casadi::Nlpsol::ng_, and casadi::Nlpsol::nx_.
     : solver_(solver), mem_(mem) {
     n_ = solver_.nx_;
     m_ = solver_.ng_;
 #ifdef WITH_IPOPT_CALLBACK
     x_ = new double[n_];
     g_ = new double[m_];
     z_L_ = new double[n_];
     z_U_ = new double[n_];
     lambda_ = new double[m_];
 #endif // WITH_IPOPT_CALLBACK
   }
casadi::IpoptUserClass::~IpoptUserClass () virtual
Definition at line 47 of file ipopt_nlp.cpp.
{
 #ifdef WITH_IPOPT_CALLBACK
     if (x_) delete [] x_;
     if (g_) delete [] g_;
     if (z_U_) delete [] z_U_;
     if (z_L_) delete [] z_L_;
     if (lambda_) delete [] lambda_;
 #endif // WITH_IPOPT_CALLBACK
   }
Member Function Documentation
bool casadi::IpoptUserClass::eval_f (Index n, const Number * x, bool new_x, Number & obj_value) virtual
Method to return the objective value
Definition at line 87 of file ipopt_nlp.cpp.
References casadi::Nlpsol::calc_function(), and casadi::IpoptInterface::f_fcn_.
{
     return solver_.calc_function(mem_, solver_.f_fcn_, {x, mem_->p}, {&obj_value})==0;
   }
bool casadi::IpoptUserClass::eval_g (Index n, const Number * x, bool new_x, Index m, Number * g) virtual
Method to return the constraint residuals
Definition at line 97 of file ipopt_nlp.cpp.
References casadi::Nlpsol::calc_function(), and casadi::IpoptInterface::g_fcn_.
{
     return solver_.calc_function(mem_, solver_.g_fcn_, {x, mem_->p}, {g})==0;
   }
bool casadi::IpoptUserClass::eval_grad_f (Index n, const Number * x, bool new_x, Number * grad_f) virtual
Method to return the gradient of the objective
Definition at line 92 of file ipopt_nlp.cpp.
References casadi::Nlpsol::calc_function(), and casadi::IpoptInterface::grad_f_fcn_.
{
     return solver_.calc_function(mem_, solver_.grad_f_fcn_, {x, mem_->p}, {0, grad_f})==0;
   }
bool casadi::IpoptUserClass::eval_h (Index n, const Number * x, bool new_x, Number obj_factor, Index m, const Number * lambda, bool new_lambda, Index nele_hess, Index * iRow, Index * jCol, Number * values) virtual
Method to return: 1) The structure of the hessian of the Lagrangian (if "values" is NULL) 2) The values of the hessian of the Lagrangian (if "values" is not NULL)
Definition at line 127 of file ipopt_nlp.cpp.
References casadi::Nlpsol::calc_function(), casadi::Sparsity::colind(), casadi::IpoptInterface::hess_l_fcn_, casadi::IpoptInterface::hesslag_sp_, casadi::Sparsity::row(), and casadi::Sparsity::size2().
{
     if (values) {
       // Evaluate Hessian
       if (solver_.calc_function(mem_, solver_.hess_l_fcn_,
                                 {x, mem_->p, &obj_factor, lambda}, {values})) return false;
       return true;
     } else {
       // Get the sparsity pattern
       int ncol = solver_.hesslag_sp_.size2();
       const int* colind = solver_.hesslag_sp_.colind();
       const int* row = solver_.hesslag_sp_.row();
       // Pass to IPOPT
       for (int cc=0; cc<ncol; ++cc) {
         for (int el=colind[cc]; el<colind[cc+1]; ++el) {
           *iRow++ = row[el];
           *jCol++ = cc;
         }
       }
       return true;
     }
   }
bool casadi::IpoptUserClass::eval_jac_g (Index n, const Number * x, bool new_x, Index m, Index nele_jac, Index * iRow, Index * jCol, Number * values) virtual
Method to return: 1) The structure of the Jacobian (if "values" is NULL) 2) The values of the Jacobian (if "values" is not NULL)
Definition at line 102 of file ipopt_nlp.cpp.
References casadi::Nlpsol::calc_function(), casadi::Sparsity::colind(), casadi::IpoptInterface::jac_g_fcn_, casadi::IpoptInterface::jacg_sp_, casadi::Sparsity::row(), and casadi::Sparsity::size2().
{
     if (values) {
       // Evaluate Jacobian
       return solver_.calc_function(mem_, solver_.jac_g_fcn_, {x, mem_->p}, {0, values})==0;
     } else {
       // Get the sparsity pattern
       int ncol = solver_.jacg_sp_.size2();
       const int* colind = solver_.jacg_sp_.colind();
       const int* row = solver_.jacg_sp_.row();
       if (nele_jac!=colind[ncol]) return false; // consistency check
       // Pass to IPOPT
       for (int cc=0; cc<ncol; ++cc) {
         for (int el=colind[cc]; el<colind[cc+1]; ++el) {
           *iRow++ = row[el];
           *jCol++ = cc;
         }
       }
       return true;
     }
   }
void casadi::IpoptUserClass::finalize_metadata (Index n, const StringMetaDataMapType & var_string_md, const IntegerMetaDataMapType & var_integer_md, const NumericMetaDataMapType & var_numeric_md, Index m, const StringMetaDataMapType & con_string_md, const IntegerMetaDataMapType & con_integer_md, const NumericMetaDataMapType & con_numeric_md) virtual
Retrieve information about variables and constraints
Definition at line 265 of file ipopt_nlp.cpp.
References casadi::IpoptMemory::con_integer_md, casadi::IpoptMemory::con_numeric_md, casadi::IpoptMemory::con_string_md, casadi::Nlpsol::ng_, casadi::Nlpsol::nx_, casadi::IpoptMemory::var_integer_md, casadi::IpoptMemory::var_numeric_md, and casadi::IpoptMemory::var_string_md.
{
     casadi_assert(n==solver_.nx_);
     casadi_assert(m==solver_.ng_);
     mem_->var_string_md = var_string_md;
     mem_->var_integer_md = var_integer_md;
     mem_->var_numeric_md = var_numeric_md;
     mem_->con_string_md = con_string_md;
     mem_->con_integer_md = con_integer_md;
     mem_->con_numeric_md = con_numeric_md;
   }
void casadi::IpoptUserClass::finalize_solution (SolverReturn status, Index n, const Number * x, const Number * z_L, const Number * z_U, Index m, const Number * g, const Number * lambda, Number obj_value, const IpoptData * ip_data, IpoptCalculatedQuantities * ip_cq) virtual
This method is called when the algorithm is complete so the TNLP can store/write the solution
Definition at line 154 of file ipopt_nlp.cpp.
References casadi::IpoptInterface::finalize_solution(), and casadi::IpoptMemory::iter_count.
{
     solver_.finalize_solution(mem_, x, z_L, z_U, g, lambda, obj_value,
                               ip_data? ip_data->iter_count(): 0);
   }
bool casadi::IpoptUserClass::get_bounds_info (Index n, Number * x_l, Number * x_u, Index m, Number * g_l, Number * g_u) virtual
Method to return the bounds for my problem
Definition at line 69 of file ipopt_nlp.cpp.
References casadi::IpoptInterface::get_bounds_info(), casadi::Nlpsol::ng_, and casadi::Nlpsol::nx_.
{
     casadi_assert(n==solver_.nx_);
     casadi_assert(m==solver_.ng_);
     return solver_.get_bounds_info(mem_, x_l, x_u, g_l, g_u);
   }
bool casadi::IpoptUserClass::get_list_of_nonlinear_variables (Index num_nonlin_vars, Index * pos_nonlin_vars) virtual
Specify which variables that appear in the Hessian
Definition at line 249 of file ipopt_nlp.cpp.
References casadi::IpoptInterface::get_list_of_nonlinear_variables().
{
     return solver_.get_list_of_nonlinear_variables(num_nonlin_vars, pos_nonlin_vars);
   }
bool casadi::IpoptUserClass::get_nlp_info (Index & n, Index & m, Index & nnz_jac_g, Index & nnz_h_lag, IndexStyleEnum & index_style) virtual
Method to return some info about the nlp
Definition at line 58 of file ipopt_nlp.cpp.
References casadi::IpoptInterface::get_nlp_info().
{
     solver_.get_nlp_info(mem_, n, m, nnz_jac_g, nnz_h_lag);
     // use the C style indexing (0-based)
     index_style = TNLP::C_STYLE;
     return true;
   }
Index casadi::IpoptUserClass::get_number_of_nonlinear_variables () virtual
Specify the number of variables that appear in the Hessian
Definition at line 245 of file ipopt_nlp.cpp.
References casadi::IpoptInterface::get_number_of_nonlinear_variables().
{
     return solver_.get_number_of_nonlinear_variables();
   }
bool casadi::IpoptUserClass::get_starting_point (Index n, bool init_x, Number * x, bool init_z, Number * z_L, Number * z_U, Index m, bool init_lambda, Number * lambda) virtual
Method to return the starting point for the algorithm
Definition at line 77 of file ipopt_nlp.cpp.
References casadi::IpoptInterface::get_starting_point(), casadi::Nlpsol::ng_, and casadi::Nlpsol::nx_.
{
     casadi_assert(n==solver_.nx_);
     casadi_assert(m==solver_.ng_);
     return solver_.get_starting_point(mem_, init_x, x, init_z, z_L, z_U, init_lambda, lambda);
   }
bool casadi::IpoptUserClass::get_var_con_metadata (Index n, StringMetaDataMapType & var_string_md, IntegerMetaDataMapType & var_integer_md, NumericMetaDataMapType & var_numeric_md, Index m, StringMetaDataMapType & con_string_md, IntegerMetaDataMapType & con_integer_md, NumericMetaDataMapType & con_numeric_md) virtual
Allows setting information about variables and constraints
Definition at line 254 of file ipopt_nlp.cpp.
References casadi::IpoptInterface::get_var_con_metadata().
{
     return solver_.get_var_con_metadata(var_string_md, var_integer_md, var_numeric_md,
                                         con_string_md, con_integer_md, con_numeric_md);
   }
bool casadi::IpoptUserClass::intermediate_callback (AlgorithmMode mode, Index iter, Number obj_value, Number inf_pr, Number inf_du, Number mu, Number d_norm, Number regularization_size, Number alpha_du, Number alpha_pr, Index ls_trials, const IpoptData * ip_data, IpoptCalculatedQuantities * ip_cq) virtual
This method is called at every iteration
Code copied from TNLPAdapter::FinalizeSolution See also: http://list.coin-or.org/pipermail/ipopt/2010-July/002078.html
Definition at line 165 of file ipopt_nlp.cpp.
References casadi::Nlpsol::callback_step_, casadi::NlpsolMemory::fstats, and casadi::IpoptInterface::intermediate_callback().
{
     // Only do the callback every few iterations
     if (iter % solver_.callback_step_!=0) return true;
     // http://list.coin-or.org/pipermail/ipopt/2010-April/001965.html
     bool full_callback = false;
 #ifdef WITH_IPOPT_CALLBACK
     mem_->fstats.at("callback_prep").tic();
     OrigIpoptNLP* orignlp = dynamic_cast<OrigIpoptNLP*>(GetRawPtr(ip_cq->GetIpoptNLP()));
     if (!orignlp) return true;
     TNLPAdapter* tnlp_adapter = dynamic_cast<TNLPAdapter*>(GetRawPtr(orignlp->nlp()));
     if (!tnlp_adapter) return true;
     const Vector& x = *ip_data->curr()->x();
     const Vector& z_L = *ip_data->curr()->z_L();
     const Vector& z_U = *ip_data->curr()->z_U();
     const Vector& c = *ip_cq->curr_c();
     const Vector& d = *ip_cq->curr_d();
     const Vector& y_c = *ip_data->curr()->y_c();
     const Vector& y_d = *ip_data->curr()->y_d();
     std::fill_n(x_, n_, 0);
     std::fill_n(g_, m_, 0);
     std::fill_n(z_L_, n_, 0);
     std::fill_n(z_U_, n_, 0);
     std::fill_n(lambda_, m_, 0);
     tnlp_adapter->ResortX(x, x_);             // no further steps needed
     tnlp_adapter->ResortG(y_c, y_d, lambda_); // no further steps needed
     tnlp_adapter->ResortG(c, d, g_);
     // Copied from Ipopt source: To Ipopt, the equality constraints are presented with right
     // hand side zero, so we correct for the original right hand side.
     const Index* c_pos = tnlp_adapter->P_c_g_->ExpandedPosIndices();
     Index n_c_no_fixed = tnlp_adapter->P_c_g_->NCols();
     for (Index i=0; i<n_c_no_fixed; i++) {
       g_[c_pos[i]] += tnlp_adapter->c_rhs_[i];
     }
     tnlp_adapter->ResortBnds(z_L, z_L_, z_U, z_U_);
     // Copied from Ipopt source: Hopefully the following is correct to recover the bound
     // multipliers for fixed variables (sign ok?)
     if (tnlp_adapter->fixed_variable_treatment_==TNLPAdapter::MAKE_CONSTRAINT &&
         tnlp_adapter->n_x_fixed_>0) {
       const DenseVector* dy_c = static_cast<const DenseVector*>(&y_c);
       Index n_c_no_fixed = y_c.Dim() - tnlp_adapter->n_x_fixed_;
       if (!dy_c->IsHomogeneous()) {
         const Number* values = dy_c->Values();
         for (Index i=0; i<tnlp_adapter->n_x_fixed_; i++) {
           z_L_[tnlp_adapter->x_fixed_map_[i]] = Max(0., -values[n_c_no_fixed+i]);
           z_U_[tnlp_adapter->x_fixed_map_[i]] = Max(0., values[n_c_no_fixed+i]);
         }
       } else {
         double value = dy_c->Scalar();
         for (Index i=0; i<tnlp_adapter->n_x_fixed_; i++) {
           z_L_[tnlp_adapter->x_fixed_map_[i]] = Max(0., -value);
           z_U_[tnlp_adapter->x_fixed_map_[i]] = Max(0.,  value);
         }
       }
     }
     mem_->fstats.at("callback_prep").toc();
     full_callback = true;
 #endif // WITH_IPOPT_CALLBACK
     return solver_.intermediate_callback(mem_, x_, z_L_, z_U_, g_, lambda_, obj_value, iter,
                                          inf_pr, inf_du, mu, d_norm, regularization_size,
                                          alpha_du, alpha_pr, ls_trials, full_callback);
   }
The documentation for this class was generated from the following files:
ipopt_nlp.hpp
ipopt_nlp.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge