CasADi: casadi::XmlNode Class Reference
casadi::XmlNode Class Reference
#include <xml_node.hpp>
Detailed Description
Definition at line 38 of file xml_node.hpp.
Public Member Functions
XmlNode ()
~XmlNode ()
void set_attribute (const std::string &attribute_name, const std::string &attribute)
Add an attribute.
std::string getAttribute (const std::string &attribute_name) const
Get an attribute by its name.
template<typename T >
void readAttribute (const std::string &attribute_name, T &val, bool assert_existance=true) const
Read the value of an attribute.
const XmlNode & operator[] (int i) const
Get a reference to a child by its index.
XmlNode & operator[] (int i)
Get a reference to a child by its index.
const XmlNode & operator[] (const std::string &childname) const
Get a reference to a child by its name.
XmlNode & operator[] (const std::string &childname)
Get a reference to a child by its name.
bool hasChild (const std::string &childname) const
Check if a child is present.
bool hasAttribute (const std::string &attribute_name) const
Check if an attribute is present.
int size () const
Get the number of children.
const std::string & name () const
Get the name of the node.
void setName (const std::string &name)
Set the name of the node.
bool checkName (const std::string &str) const
check if the name is equal to something
std::string getText () const
Get the text field.
template<typename T >
void getText (T &val) const
Get value of text field.
void dump (std::ostream &stream, int indent=0) const
Static Public Member Functions
static void readString (const std::string &str, std::string &val)
Read the string value of a string (i.e. copy)
static void readString (const std::string &str, bool &val)
Read the boolean value of a string.
static void readString (const std::string &str, int &val)
Read the integer value of a string.
static void readString (const std::string &str, double &val)
Read the double value of a string.
Public Attributes
std::map< std::string,
std::string > attributes_
std::vector< XmlNode > children_
std::map< std::string, int > child_indices_
std::string name_
std::string comment_
std::string text_
Friends
CASADI_EXPORT friend std::ostream & operator<< (std::ostream &stream, const XmlNode &node)
Constructor & Destructor Documentation
casadi::XmlNode::XmlNode ()
Definition at line 31 of file xml_node.cpp.
                    {
   }
casadi::XmlNode::~XmlNode ()
Definition at line 34 of file xml_node.cpp.
                     {
   }
Member Function Documentation
bool casadi::XmlNode::checkName (const std::string & str) const
Definition at line 123 of file xml_node.cpp.
Referenced by casadi::DaeBuilder::parse_fmi().
{
     return name_.compare(str) == 0;
   }
void casadi::XmlNode::dump (std::ostream & stream, int indent = 0) const
Definition at line 97 of file xml_node.cpp.
Referenced by casadi::operator<<().
{
     // Print name
     stream << string(indent, ' ') << "Node: " << name_ << endl;
     // Print comment
     if (!comment_.empty()) {
       stream << string(indent, ' ') << "----- comment starts ----- "  << endl;
       stream << comment_ << endl;
       stream << string(indent, ' ') << "----- comment ends ----- "  << endl;
     }
     // Print text
     if (!text_.empty())
       stream << string(indent+2, ' ') << "Text: " << text_ << endl;
     // Print attributes
     for (map<string, string>::const_iterator it=attributes_.begin(); it != attributes_.end(); ++it)
       stream << string(indent+2, ' ') << "attribute " << it->first << " = " << it->second << endl;
     // Print Children
     for (int i=0; i<size(); ++i) {
       stream << string(indent, ' ') << "Child " << i << ":" << endl;
       (*this)[i].dump(stream, indent+2);
     }
   }
std::string casadi::XmlNode::getAttribute (const std::string & attribute_name) const inline
Definition at line 47 of file xml_node.hpp.
Referenced by casadi::DaeBuilder::parse_fmi(), and casadi::DaeBuilder::qualified_name().
{
       std::string ret;
       readAttribute(attribute_name, ret, true);
       return ret;
     }
std::string casadi::XmlNode::getText () const inline
Definition at line 100 of file xml_node.hpp.
Referenced by casadi::DaeBuilder::parse_fmi(), casadi::DaeBuilder::qualified_name(), and casadi::DaeBuilder::read_expr().
 { return text_; }
template<typename T > void casadi::XmlNode::getText (T & val) const inline
Definition at line 104 of file xml_node.hpp.
 { readString(text_, val);}
bool casadi::XmlNode::hasAttribute (const std::string & attribute_name) const
Definition at line 37 of file xml_node.cpp.
{
     map<string, string>::const_iterator it = attributes_.find(attribute_name);
     return it!=attributes_.end();
   }
bool casadi::XmlNode::hasChild (const std::string & childname) const
Definition at line 54 of file xml_node.cpp.
Referenced by casadi::DaeBuilder::parse_fmi().
{
     map<string, int>::const_iterator it = child_indices_.find(childname);
     return it!=child_indices_.end();
   }
const string & casadi::XmlNode::name () const
Definition at line 89 of file xml_node.cpp.
Referenced by casadi::TinyXmlInterface::addNode(), casadi::DaeBuilder::parse_fmi(), and casadi::DaeBuilder::read_expr().
{
     return name_;
   }
const XmlNode & casadi::XmlNode::operator[] (int i) const
Definition at line 50 of file xml_node.cpp.
{
     return const_cast<XmlNode*>(this)->operator[](i);
   }
XmlNode & casadi::XmlNode::operator[] (int i)
Definition at line 42 of file xml_node.cpp.
{
     casadi_assert_message(i>=0 && i < size(),
                           "XmlNode::operator[]: index out of bounds for element " << i
                           << " of node " << name());
     return children_.at(i);
   }
const XmlNode& casadi::XmlNode::operator[] (const std::string & childname) const
XmlNode& casadi::XmlNode::operator[] (const std::string & childname)
template<typename T > void casadi::XmlNode::readAttribute (const std::string & attribute_name, T & val, bool assert_existance = true) const inline
Definition at line 55 of file xml_node.hpp.
Referenced by casadi::DaeBuilder::parse_fmi().
{
       // find the attribute
       std::map<std::string, std::string>::const_iterator it = attributes_.find(attribute_name);
       // check if the attribute exists
       if (it == attributes_.end()) {
         casadi_assert_message(!assert_existance,
                               "Error in XmlNode::readAttribute: could not find " + attribute_name);
       } else {
         readString(it->second, val);
       }
     }
void casadi::XmlNode::readString (const std::string & str, std::string & val) static
Definition at line 127 of file xml_node.cpp.
{
     val = str;
   }
void casadi::XmlNode::readString (const std::string & str, bool & val) static
Definition at line 131 of file xml_node.cpp.
{
     if (str.compare("true")==0)
       val = true;
     else if (str.compare("false")==0)
       val = false;
     else
       throw CasadiException("XML argument not true or false");
   }
void casadi::XmlNode::readString (const std::string & str, int & val) static
Definition at line 140 of file xml_node.cpp.
{
     std::istringstream buffer(str);
     buffer >> val;
   }
void casadi::XmlNode::readString (const std::string & str, double & val) static
Definition at line 145 of file xml_node.cpp.
{
     std::istringstream buffer(str);
     buffer >> val;
   }
void casadi::XmlNode::set_attribute (const std::string & attribute_name, const std::string & attribute)
Definition at line 76 of file xml_node.cpp.
Referenced by casadi::TinyXmlInterface::addNode().
{
     attributes_[attribute_name] = attribute;
   }
void casadi::XmlNode::setName (const std::string & name)
Definition at line 93 of file xml_node.cpp.
Referenced by casadi::TinyXmlInterface::addNode().
{
     name_ = name;
   }
int casadi::XmlNode::size () const
Definition at line 85 of file xml_node.cpp.
Referenced by casadi::DaeBuilder::parse_fmi(), casadi::DaeBuilder::qualified_name(), and casadi::DaeBuilder::read_expr().
{
     return children_.size();
   }
Friends And Related Function Documentation
CASADI_EXPORT friend std::ostream& operator<< (std::ostream & stream, const XmlNode & node) friend
Member Data Documentation
std::map<std::string, std::string> casadi::XmlNode::attributes_
Definition at line 123 of file xml_node.hpp.
std::map<std::string, int> casadi::XmlNode::child_indices_
Definition at line 125 of file xml_node.hpp.
Referenced by casadi::TinyXmlInterface::addNode().
std::vector<XmlNode> casadi::XmlNode::children_
Definition at line 124 of file xml_node.hpp.
Referenced by casadi::TinyXmlInterface::addNode().
std::string casadi::XmlNode::comment_
Definition at line 129 of file xml_node.hpp.
Referenced by casadi::TinyXmlInterface::addNode().
std::string casadi::XmlNode::name_
Definition at line 128 of file xml_node.hpp.
std::string casadi::XmlNode::text_
Definition at line 130 of file xml_node.hpp.
Referenced by casadi::TinyXmlInterface::addNode().
The documentation for this class was generated from the following files:
xml_node.hpp
xml_node.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge