CasADi: casadi::XOracle< XType > Class Template Reference
casadi::XOracle< XType > Class Template Reference
#include <oracle.hpp>
Detailed Description
template<typename XType>
class casadi::XOracle< XType >
Symbolic representation of a problem
Definition at line 102 of file oracle.hpp.
Public Member Functions
XOracle (const std::vector< XType > &in, const std::vector< XType > &out, const std::vector< std::string > &ischeme, const std::vector< std::string > &oscheme)
virtual ~XOracle ()
virtual Oracle * clone () const
virtual const Sparsity & sparsity_in (int i) const
virtual const Sparsity & sparsity_out (int i) const
virtual std::string name_in (int i) const
virtual std::string name_out (int i) const
virtual Function create (const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const std::vector< LinComb > &lincomb, const Dict &opts) const
virtual std::string type_name () const
Get type name.
virtual std::vector< bool > nl_var (const std::string &s_in, const std::vector< std::string > &s_out) const
Which variables enter nonlinearly.
virtual Function all_io (const std::string &fname, const Dict &opts) const
Generate a function with all inputs and outputs.
virtual Oracle * expand () const
Static Public Member Functions
static Oracle * construct (const std::vector< SX > &in, const std::vector< SX > &out, const std::vector< std::string > &ischeme, const std::vector< std::string > &oscheme)
static Oracle * construct (const std::vector< MX > &in, const std::vector< MX > &out, const std::vector< std::string > &ischeme, const std::vector< std::string > &oscheme)
static Oracle * construct (const std::string &fname, const std::string &all_io="all_io")
static Oracle * construct (const Compiler &compiler, const std::string &all_io="all_io")
Constructor & Destructor Documentation
template<typename XType> casadi::XOracle< XType >::XOracle (const std::vector< XType > & in, const std::vector< XType > & out, const std::vector< std::string > & ischeme, const std::vector< std::string > & oscheme) inline
Definition at line 110 of file oracle.hpp.
       : in_(in), out_(out), ischeme_(ischeme), oscheme_(oscheme) {
     }
template<typename XType> virtual casadi::XOracle< XType >::~XOracle () inline virtual
Definition at line 117 of file oracle.hpp.
 {}
Member Function Documentation
template<typename XType > Function casadi::XOracle< XType >::all_io (const std::string & fname, const Dict & opts) const virtual
Reimplemented from casadi::Oracle.
Definition at line 265 of file oracle.cpp.
{
     return Function(fname, in_, out_, ischeme_, oscheme_, opts);
   }
template<typename XType> virtual Oracle* casadi::XOracle< XType >::clone () const inline virtual
Implements casadi::Oracle.
Definition at line 120 of file oracle.hpp.
 { return new XOracle(*this);}
Oracle * casadi::Oracle::construct (const std::vector< SX > & in, const std::vector< SX > & out, const std::vector< std::string > & ischeme, const std::vector< std::string > & oscheme) static inherited
Definition at line 214 of file oracle.cpp.
Referenced by casadi::Oracle::expand(), casadi::Nlpsol::fun2problem(), casadi::Integrator::fun2problem(), casadi::Nlpsol::map2problem(), and casadi::Integrator::map2problem().
{
     return new XOracle<SX>(in, out, ischeme, oscheme);
   }
Oracle * casadi::Oracle::construct (const std::vector< MX > & in, const std::vector< MX > & out, const std::vector< std::string > & ischeme, const std::vector< std::string > & oscheme) static inherited
Definition at line 221 of file oracle.cpp.
{
     return new XOracle<MX>(in, out, ischeme, oscheme);
   }
Oracle * casadi::Oracle::construct (const std::string & fname, const std::string & all_io = "all_io") static inherited
Definition at line 232 of file oracle.cpp.
{
     // If fname ends with .c, JIT
     if (fname.size()>2 && fname.compare(fname.size()-2, fname.size(), ".c")==0) {
       Compiler compiler(fname, "clang");
       return construct(compiler, all_io);
     } else {
       return new LibOracle<std::string>(fname, all_io);
     }
   }
Oracle * casadi::Oracle::construct (const Compiler & compiler, const std::string & all_io = "all_io") static inherited
Definition at line 228 of file oracle.cpp.
{
     return new LibOracle<Compiler>(compiler, all_io);
   }
template<typename XType > Function casadi::XOracle< XType >::create (const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const std::vector< LinComb > & lincomb, const Dict & opts) const virtual
Implements casadi::Oracle.
Definition at line 34 of file oracle.cpp.
References casadi::densify(), casadi::dot(), casadi::Function::free_mx(), casadi::Function::free_sx(), casadi::Function::has_free(), casadi::Function::is_a(), and casadi::project().
{
     // Create maps for all inputs and outputs
     map<string, XType> map_in, map_out;
     // Non-differentiated inputs
     for (int i=0; i<in_.size(); ++i) {
       map_in[ischeme_[i]] = in_[i];
     }
     // Non-differentiated outputs
     for (int i=0; i<out_.size(); ++i) {
       map_out[oscheme_[i]] = out_[i];
     }
     // Dual variables
     for (int i=0; i<out_.size(); ++i) {
       string dual_name = "lam_" + oscheme_[i];
       map_in[dual_name] = XType::sym(dual_name, out_[i].sparsity());
     }
     // Add linear combinations
     for (auto i : lincomb) {
       XType lc = 0;
       for (auto j : i.second) {
         lc += dot(map_in.at("lam_" + j), map_out.at(j));
       }
       map_out[i.first] = lc;
     }
     // Inputs of function being assembled
     vector<XType> ret_in(s_in.size());
     // Handle inputs
     for (int i=0; i<ret_in.size(); ++i) {
       ret_in[i] = map_in.at(s_in[i]);
     }
     // Outputs of function being assembled
     vector<XType> ret_out(s_out.size());
     // List of valid attributes
     const vector<string> all_attr = {"transpose", "triu", "tril", "densify", "sym", "withdiag"};
     // Handle outputs
     for (int i=0; i<ret_out.size(); ++i) {
       XType& r = ret_out[i];
       // Output name
       string s = s_out[i];
       // Separarate attributes
       vector<string> attr;
       while (true) {
         // Find the first underscore separator
         size_t pos = s.find('_');
         if (pos>=s.size()) break; // No more underscore
         string a = s.substr(0, pos);
         // Try to match with attributes
         auto it = std::find(all_attr.begin(), all_attr.end(), a);
         if (it==all_attr.end()) break; // No more attribute
         // Save attribute and strip from s
         attr.push_back(*it);
         s = s.substr(pos+1, string::npos);
       }
       // Try to locate in list of outputs
       auto it = map_out.find(s);
       if (it!=map_out.end()) {
         // Non-differentiated output
         r = it->second;
       } else {
         // Must be an operator
         size_t pos = s.find('_');
         casadi_assert_message(pos<s.size(), s_out[i] + " is not an output or operator");
         string op = s.substr(0, pos);
         s = s.substr(pos+1);
         // Handle different types of operators
         if (op=="grad" || op=="jac" || op=="hess") {
           // Output
           pos = s.find('_');
           casadi_assert_message(pos<s.size(), s_out[i] + " is ill-posed");
           string res = s.substr(0, pos);
           auto res_i = map_out.find(res);
           casadi_assert_message(res_i!=map_out.end(),
                                 "Unrecognized output " + res + " in " + s_out[i]);
           s = s.substr(pos+1);
           // Input
           string arg;
           if (op=="hess") {
             pos = s.find('_');
             casadi_assert_message(pos<s.size(), s_out[i] + " is ill-posed");
             arg = s.substr(0, pos);
             s = s.substr(pos+1);
             casadi_assert_message(s==arg, "Mixed Hessian terms not supported");
           } else {
             arg = s;
           }
           auto arg_i = map_in.find(arg);
           casadi_assert_message(arg_i!=map_in.end(),
                                 "Unrecognized input " + arg + " in " + s_out[i]);
           // Calculate gradient or Jacobian
           if (op=="jac") {
             r = jacobian(res_i->second, arg_i->second);
           } else if (op=="grad") {
             r = project(gradient(res_i->second, arg_i->second), arg_i->second.sparsity());
           } else {
             casadi_assert(op=="hess");
             r = triu(hessian(res_i->second, arg_i->second));
           }
         } else {
           casadi_error("Unknown operator: " + op);
         }
       }
       // Apply attributes (starting from the right-most one)
       for (auto a=attr.rbegin(); a!=attr.rend(); ++a) {
         if (*a=="transpose") {
           r = r = r.T();
         } else if (*a=="triu") {
           r = triu(r);
         } else if (*a=="tril") {
           r = tril(r);
         } else if (*a=="densify") {
           r = densify(r);
         } else if (*a=="sym") {
           r = triu2symm(r);
         } else if (*a=="withdiag") {
           r = project(r, r.sparsity() + Sparsity::diag(r.size1()));
         } else {
           casadi_assert(0);
         }
       }
     }
     // Create function and return
     Function ret(fname, ret_in, ret_out, s_in, s_out, opts);
     if (ret.has_free()) {
       stringstream ss;
       ss << "Cannot generate " << fname << " as the expressions contain free variables: ";
       if (ret.is_a("sxfunction")) {
         ss << ret.free_sx();
       } else {
         casadi_assert(ret.is_a("mxfunction"));
         ss << ret.free_mx();
       }
       casadi_error(ss.str());
     }
     return ret;
   }
Oracle * casadi::Oracle::expand () const virtual inherited
Definition at line 302 of file oracle.cpp.
References casadi::Oracle::all_io(), casadi::Oracle::construct(), casadi::Function::expand(), casadi::Function::is_a(), casadi::Function::name_in(), casadi::Function::name_out(), and casadi::Function::sx_in().
Referenced by casadi::Integrator::init(), and casadi::Nlpsol::init().
{
     // Get a MX function from all inputs to all outputs
     Function f = all_io();
     // Expand to SX
     if (!f.is_a("sxfunction")) {
       f = f.expand();
     }
     // Get expressions
     vector<SX> arg = f.sx_in();
     vector<SX> res = f(arg);
     // Construct SX oracle
     return construct(arg, res, f.name_in(), f.name_out());
   }
template<typename XType> virtual std::string casadi::XOracle< XType >::name_in (int i) const inline virtual
Reimplemented from casadi::Oracle.
Definition at line 129 of file oracle.hpp.
 { return ischeme_.at(i);}
template<typename XType> virtual std::string casadi::XOracle< XType >::name_out (int i) const inline virtual
Reimplemented from casadi::Oracle.
Definition at line 132 of file oracle.hpp.
 { return oscheme_.at(i);}
template<typename XType > std::vector< bool > casadi::XOracle< XType >::nl_var (const std::string & s_in, const std::vector< std::string > & s_out) const virtual
Reimplemented from casadi::Oracle.
Definition at line 195 of file oracle.cpp.
{
     // Input arguments
     auto it = find(ischeme_.begin(), ischeme_.end(), s_in);
     casadi_assert(it!=ischeme_.end());
     XType arg = in_.at(it-ischeme_.begin());
     // Output arguments
     vector<XType> res;
     for (auto&& s : s_out) {
       it = find(oscheme_.begin(), oscheme_.end(), s);
       casadi_assert(it!=oscheme_.end());
       res.push_back(out_.at(it-oscheme_.begin()));
     }
     // Extract variables entering nonlinearly
     return XType::nl_var(veccat(res), arg);
   }
template<typename XType> virtual const Sparsity& casadi::XOracle< XType >::sparsity_in (int i) const inline virtual
Implements casadi::Oracle.
Definition at line 123 of file oracle.hpp.
 { return in_.at(i).sparsity();}
template<typename XType> virtual const Sparsity& casadi::XOracle< XType >::sparsity_out (int i) const inline virtual
Implements casadi::Oracle.
Definition at line 126 of file oracle.hpp.
 { return out_.at(i).sparsity();}
template<typename XType > std::string casadi::XOracle< XType >::type_name () const virtual
Implements casadi::Oracle.
Definition at line 256 of file oracle.cpp.
{
     return XType::type_name() + "Oracle";
   }
The documentation for this class was generated from the following files:
oracle.hpp
oracle.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge