CasADi: casadi::Compiler Class Reference
casadi::Compiler Class Reference
Compiler.
#include <compiler.hpp>
Detailed Description
Just-in-time compilation of code
General information
List of plugins
- clang
- shell
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Compiler.doc("myextraplugin")
clang
Interface to the JIT compiler CLANG
List of available options
Id Type Description
flags OT_STRINGVECTOR Compile flags for the JIT compiler. Default: None
include_path OT_STRING Include paths for the JIT compiler. The include directory shipped with CasADi will be automatically appended.
shell
Interface to the JIT compiler SHELL
List of available options
Id Type Description
compiler OT_STRING Compiler command
compiler_setup OT_STRING Compiler setup command. Intended to be fixed. The 'flag' option is the prefered way to set custom flags.
flags OT_STRINGVECTOR Compile flags for the JIT compiler. Default: None
Author
Joris Gillis
Date
2015
Definition at line 47 of file compiler.hpp.
Public Member Functions
Compiler ()
Default constructor.
Compiler (const std::string &name, const std::string &compiler, const Dict &opts=Dict())
Compiler factory (new syntax, includes initialization)
CompilerInternal * operator-> ()
Access functions of the node.
const CompilerInternal * operator-> () const
std::string plugin_name () const
Query plugin name.
void * get_function (const std::string &symname)
Get a function pointer for numerical evaluation.
const ParsedFile & meta () const
Get meta information.
void assignNode (SharedObjectNode *node)
void assignNodeNoCount (SharedObjectNode *node)
Assign the node to a node class pointer without reference counting.
SharedObjectNode * get () const
Get a const pointer to the node.
int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void printPtr (std::ostream &stream=casadi::userOut()) const
bool is_null () const
Is a null pointer?
WeakRef * weak ()
Get a weak reference to the object.
size_t __hash__ () const
Returns a number that is unique for a given Node. If the Object does not point to any node, "0" is returned.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
Static Public Member Functions
static bool test_cast (const SharedObjectNode *ptr)
Check if a particular cast is allowed.
static bool hasPlugin (const std::string &name)
Check if a plugin is available.
static void loadPlugin (const std::string &name)
Explicitly load a plugin dynamically.
static std::string doc (const std::string &name)
Get solver specific documentation.
Protected Member Functions
void count_up ()
void count_down ()
Constructor & Destructor Documentation
casadi::Compiler::Compiler ()
Definition at line 32 of file compiler.cpp.
                      {
   }
casadi::Compiler::Compiler (const std::string & name, const std::string & compiler, const Dict & opts = Dict()) explicit
Definition at line 35 of file compiler.cpp.
{
     if (compiler=="none") {
       assignNode(new CompilerInternal(name));
     } else {
       assignNode(CompilerInternal::getPlugin(compiler).creator(name));
     }
     (*this)->construct(opts);
   }
Member Function Documentation
size_t casadi::SharedObject::__hash__ () const inherited
Definition at line 178 of file shared_object.cpp.
{
     return reinterpret_cast<size_t>(get());
   }
void casadi::SharedObject::assignNode (SharedObjectNode * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 57 of file shared_object.cpp.
Referenced by casadi::Function::conditional(), casadi::Callback::construct(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::Sparsity::create(), casadi::Function::create(), casadi::external(), casadi::Function::if_else(), casadi::MXFunction::init(), casadi::integrator(), casadi::jit(), casadi::Function::kernel_sum(), casadi::linsol(), casadi::nlpsol(), casadi::qpsol(), casadi::rootfinder(), and casadi::WeakRef::shared().
{
     count_down();
     node = node_;
     count_up();
   }
void casadi::SharedObject::assignNodeNoCount (SharedObjectNode * node) inherited
improper use will cause memory leaks!
Definition at line 63 of file shared_object.cpp.
{
     node = node_;
   }
void casadi::SharedObject::count_down () protected inherited
Definition at line 92 of file shared_object.cpp.
Referenced by casadi::Callback::transfer_ownership().
{
     if (node && --node->count == 0) {
       delete node;
       node = 0;
     }
   }
void casadi::SharedObject::count_up () protected inherited
Definition at line 88 of file shared_object.cpp.
{
     if (node) node->count++;
   }
std::string casadi::Compiler::doc (const std::string & name) static
Definition at line 66 of file compiler.cpp.
{
     return CompilerInternal::getPlugin(name).doc;
   }
SharedObjectNode * casadi::SharedObject::get () const inherited
Definition at line 80 of file shared_object.cpp.
Referenced by casadi::CodeGenerator::addSparsity(), casadi::CodeGenerator::get_sparsity(), casadi::SparsityInternal::is_equal(), casadi::SparsityInternal::maxTransversal(), and casadi::shared_cast().
{
     return node;
   }
void * casadi::Compiler::get_function (const std::string & symname)
Definition at line 74 of file compiler.cpp.
Referenced by casadi::FunctionInternal::finalize(), and casadi::JitLibrary::get().
{
     return (*this)->getFunction(symname);
   }
int casadi::SharedObject::getCount () const inherited
Definition at line 159 of file shared_object.cpp.
References casadi::SharedObjectNode::getCount().
Referenced by casadi::Callback::transfer_ownership().
{
     return (*this)->getCount();
   }
std::string casadi::PrintableObject< SharedObject >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< SharedObject >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
bool casadi::Compiler::hasPlugin (const std::string & name) static
Definition at line 58 of file compiler.cpp.
{
     return CompilerInternal::hasPlugin(name);
   }
bool casadi::SharedObject::is_null () const inherited
Definition at line 84 of file shared_object.cpp.
Referenced by casadi::FunctionInternal::alloc(), casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::Integrator::fun2problem(), casadi::Switch::generateBody(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), casadi::SundialsInterface::getBandwidth(), casadi::SundialsInterface::getBandwidthB(), casadi::FunctionInternal::getPartition(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Newton::init(), casadi::Integrator::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::FixedStepIntegrator::init(), casadi::CvodesInterface::init_memory(), casadi::IdasInterface::init_memory(), casadi::FixedStepIntegrator::init_memory(), casadi::CvodesInterface::initIterativeLinsol(), casadi::IdasInterface::initIterativeLinsol(), casadi::CvodesInterface::initIterativeLinsolB(), casadi::IdasInterface::initIterativeLinsolB(), casadi::CvodesInterface::initUserDefinedLinsol(), casadi::IdasInterface::initUserDefinedLinsol(), casadi::CvodesInterface::initUserDefinedLinsolB(), casadi::IdasInterface::initUserDefinedLinsolB(), casadi::Integrator::Integrator(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::Linsol(), casadi::SparsityInternal::maxTransversal(), casadi::operator<<(), casadi::IdasInterface::psolveB(), casadi::Qpsol::Qpsol(), casadi::SnoptInterface::set_work(), casadi::RkIntegrator::setupFG(), casadi::CollocationIntegrator::setupFG(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Integrator::spAdj(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), casadi::Integrator::spFwd(), casadi::FunctionInternal::spFwd(), casadi::Callback::transfer_ownership(), casadi::Sparsity::uni_coloring(), casadi::SnoptInterface::userfun(), and casadi::Callback::~Callback().
{
     return node==0;
   }
void casadi::Compiler::loadPlugin (const std::string & name) static
Definition at line 62 of file compiler.cpp.
{
     CompilerInternal::loadPlugin(name);
   }
const ParsedFile & casadi::Compiler::meta () const
Definition at line 78 of file compiler.cpp.
Referenced by casadi::JitLibrary::JitLibrary(), and casadi::JitLibrary::meta().
{
     return (*this)->meta_;
   }
CompilerInternal * casadi::Compiler::operator-> ()
Definition at line 46 of file compiler.cpp.
{
     return static_cast<CompilerInternal*>(SharedObject::operator->());
   }
const CompilerInternal * casadi::Compiler::operator-> () const
Definition at line 50 of file compiler.cpp.
{
     return static_cast<const CompilerInternal*>(SharedObject::operator->());
   }
std::string casadi::Compiler::plugin_name () const
Definition at line 70 of file compiler.cpp.
{
     return (*this)->plugin_name();
   }
void casadi::SharedObject::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 135 of file shared_object.cpp.
Referenced by casadi::CsparseInterface::linsol_factorize().
{
     if (is_null()) {
       stream << "Null pointer of class \"" << typeid(this).name() << "\"";
     } else {
       (*this)->print(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::SharedObject::printPtr (std::ostream & stream = casadi::userOut()) const inherited
Print the pointer to the internal class
Definition at line 144 of file shared_object.cpp.
{
     stream << node;
   }
void casadi::SharedObject::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 121 of file shared_object.cpp.
{
     if (is_null()) {
       stream << 0;
     } else {
       (*this)->repr(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 153 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
bool casadi::Compiler::test_cast (const SharedObjectNode * ptr) static
Definition at line 54 of file compiler.cpp.
{
     return dynamic_cast<const CompilerInternal*>(ptr)!=0;
   }
WeakRef * casadi::SharedObject::weak () inherited
Definition at line 167 of file shared_object.cpp.
References casadi::SharedObjectNode::weak().
Referenced by casadi::WeakRef::WeakRef().
{
     return (*this)->weak();
   }
The documentation for this class was generated from the following files:
compiler.hpp
compiler.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge