CasADi: casadi::Oracle Class Reference
casadi::Oracle Class Reference abstract
#include <oracle.hpp>
Detailed Description
Oracle abstract base class
Definition at line 38 of file oracle.hpp.
Public Member Functions
virtual ~Oracle ()
virtual Oracle * clone () const =0
virtual Oracle * expand () const
virtual const Sparsity & sparsity_in (int i) const =0
virtual const Sparsity & sparsity_out (int i) const =0
virtual std::string name_in (int i) const
virtual std::string name_out (int i) const
virtual Function create (const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const std::vector< LinComb > &lincomb=std::vector< LinComb >(), const Dict &opts=Dict()) const =0
virtual std::string type_name () const =0
Get type name.
virtual std::vector< bool > nl_var (const std::string &s_in, const std::vector< std::string > &s_out) const
Which variables enter nonlinearly.
virtual Function all_io (const std::string &fname="all_io", const Dict &opts=Dict()) const
Generate a function with all inputs and outputs.
Static Public Member Functions
static Oracle * construct (const std::vector< SX > &in, const std::vector< SX > &out, const std::vector< std::string > &ischeme, const std::vector< std::string > &oscheme)
static Oracle * construct (const std::vector< MX > &in, const std::vector< MX > &out, const std::vector< std::string > &ischeme, const std::vector< std::string > &oscheme)
static Oracle * construct (const std::string &fname, const std::string &all_io="all_io")
static Oracle * construct (const Compiler &compiler, const std::string &all_io="all_io")
Constructor & Destructor Documentation
virtual casadi::Oracle::~Oracle () inline virtual
Definition at line 61 of file oracle.hpp.
 {}
Member Function Documentation
Function casadi::Oracle::all_io (const std::string & fname = "all_io", const Dict & opts = Dict()) const virtual
Reimplemented in casadi::XOracle< XType >.
Definition at line 260 of file oracle.cpp.
Referenced by expand(), and casadi::Nlpsol::generate_dependencies().
{
     casadi_error("'all_io' not defined for " + type_name());
   }
virtual Oracle* casadi::Oracle::clone () const pure virtual
Implemented in casadi::LibOracle< LibType >, and casadi::XOracle< XType >.
Oracle * casadi::Oracle::construct (const std::vector< SX > & in, const std::vector< SX > & out, const std::vector< std::string > & ischeme, const std::vector< std::string > & oscheme) static
Definition at line 214 of file oracle.cpp.
Referenced by expand(), casadi::Nlpsol::fun2problem(), casadi::Integrator::fun2problem(), casadi::Nlpsol::map2problem(), and casadi::Integrator::map2problem().
{
     return new XOracle<SX>(in, out, ischeme, oscheme);
   }
Oracle * casadi::Oracle::construct (const std::vector< MX > & in, const std::vector< MX > & out, const std::vector< std::string > & ischeme, const std::vector< std::string > & oscheme) static
Definition at line 221 of file oracle.cpp.
{
     return new XOracle<MX>(in, out, ischeme, oscheme);
   }
Oracle * casadi::Oracle::construct (const std::string & fname, const std::string & all_io = "all_io") static
Definition at line 232 of file oracle.cpp.
{
     // If fname ends with .c, JIT
     if (fname.size()>2 && fname.compare(fname.size()-2, fname.size(), ".c")==0) {
       Compiler compiler(fname, "clang");
       return construct(compiler, all_io);
     } else {
       return new LibOracle<std::string>(fname, all_io);
     }
   }
Oracle * casadi::Oracle::construct (const Compiler & compiler, const std::string & all_io = "all_io") static
Definition at line 228 of file oracle.cpp.
{
     return new LibOracle<Compiler>(compiler, all_io);
   }
virtual Function casadi::Oracle::create (const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const std::vector< LinComb > & lincomb = std::vector< LinComb >(), const Dict & opts = Dict()) const pure virtual
Implemented in casadi::LibOracle< LibType >, and casadi::XOracle< XType >.
Referenced by casadi::Nlpsol::create_function(), and casadi::Integrator::Integrator().
Oracle * casadi::Oracle::expand () const virtual
Definition at line 302 of file oracle.cpp.
References all_io(), construct(), casadi::Function::expand(), casadi::Function::is_a(), casadi::Function::name_in(), casadi::Function::name_out(), and casadi::Function::sx_in().
Referenced by casadi::Integrator::init(), and casadi::Nlpsol::init().
{
     // Get a MX function from all inputs to all outputs
     Function f = all_io();
     // Expand to SX
     if (!f.is_a("sxfunction")) {
       f = f.expand();
     }
     // Get expressions
     vector<SX> arg = f.sx_in();
     vector<SX> res = f(arg);
     // Construct SX oracle
     return construct(arg, res, f.name_in(), f.name_out());
   }
std::string casadi::Oracle::name_in (int i) const virtual
Reimplemented in casadi::XOracle< XType >.
Definition at line 247 of file oracle.cpp.
{
     casadi_error("'name_in' not defined for " + type_name());
   }
std::string casadi::Oracle::name_out (int i) const virtual
Reimplemented in casadi::XOracle< XType >.
Definition at line 251 of file oracle.cpp.
{
     casadi_error("'name_out' not defined for " + type_name());
   }
std::vector< bool > casadi::Oracle::nl_var (const std::string & s_in, const std::vector< std::string > & s_out) const virtual
Reimplemented in casadi::XOracle< XType >.
Definition at line 242 of file oracle.cpp.
Referenced by casadi::Nlpsol::nl_var().
{
     casadi_error("'nl_var' not defined for " + type_name());
   }
virtual const Sparsity& casadi::Oracle::sparsity_in (int i) const pure virtual
Implemented in casadi::LibOracle< LibType >, and casadi::XOracle< XType >.
Referenced by casadi::Nlpsol::get_sparsity_in(), and casadi::Nlpsol::get_sparsity_out().
virtual const Sparsity& casadi::Oracle::sparsity_out (int i) const pure virtual
Implemented in casadi::LibOracle< LibType >, and casadi::XOracle< XType >.
Referenced by casadi::Nlpsol::get_sparsity_out().
virtual std::string casadi::Oracle::type_name () const pure virtual
Implemented in casadi::LibOracle< LibType >, and casadi::XOracle< XType >.
The documentation for this class was generated from the following files:
oracle.hpp
oracle.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge