CasADi: casadi::Options Struct Reference
casadi::Options Struct Reference
Options metadata for a class.
#include <options.hpp>
Detailed Description
Author
Joel Andersson, Joris Gillis
Date
2010-2016
Definition at line 39 of file options.hpp.
Classes
struct Entry
Public Member Functions
const Options::Entry * find (const std::string &name) const
void print (std::ostream &stream) const
std::vector< std::string > suggestions (const std::string &word, int amount=5) const
Get the best suggestions for a misspelled word.
void best_matches (const std::string &word, std::vector< std::pair< double, std::string > > &best) const
Find best matches.
Static Public Member Functions
static double word_distance (const std::string &a, const std::string &b)
A distance metric between two words.
Public Attributes
std::vector< Options * > bases
std::map< std::string, Entry > entries
Member Function Documentation
void casadi::Options::best_matches (const std::string & word, std::vector< std::pair< double, std::string > > & best) const
Definition at line 129 of file options.cpp.
{
     // Iterate over bases
     for (auto&& b : bases) {
       b->best_matches(word, best);
     }
     // Worst match so far
     auto worst = max_element(best.begin(), best.end());
     // Loop over entries
     for (auto&& e : entries) {
       // Get word distance
       double d = word_distance(e.first, word);
       // Keep if better than the worst amongst the suggestions
       if (d < worst->first) {
         worst->first = d;
         worst->second = e.first;
         worst = max_element(best.begin(), best.end());
       }
     }
   }
const Options::Entry * casadi::Options::find (const std::string & name) const
Definition at line 34 of file options.cpp.
Referenced by casadi::CompilerInternal::construct(), casadi::FunctionInternal::construct(), and casadi::FunctionInternal::printOption().
{
     // Check if in one of the bases
     for (auto&& b : bases) {
       const Options::Entry* entry = b->find(name);
       if (entry) return entry;
     }
     // Lookup in this class
     auto it = entries.find(name);
     if (it!=entries.end()) {
       return &it->second;
     } else {
       return 0;
     }
   }
void casadi::Options::print (std::ostream & stream) const
Definition at line 59 of file options.cpp.
References casadi::Options::Entry::print().
Referenced by casadi::FunctionInternal::printOptions().
{
     // Print bases
     for (auto&& b : bases) {
       b->print(stream);
     }
     // Print all entries
     for (auto&& e : entries) {
       e.second.print(e.first, stream);
     }
   }
vector< string > casadi::Options::suggestions (const std::string & word, int amount = 5) const
Definition at line 107 of file options.cpp.
References casadi::inf.
Referenced by casadi::FunctionInternal::construct().
{
     // Best distances so far
     const double inf = numeric_limits<double>::infinity();
     vector<pair<double, string> > best(amount, {inf, ""});
     // Iterate over elements
     best_matches(word, best);
     // Sort the elements in ascending order
     stable_sort(best.begin(), best.end());
     // Collect the values that are non-infinite
     vector<string> ret;
     ret.reserve(amount);
     for (auto&& e : best) {
       if (e.first!=inf) {
         ret.push_back(e.second);
       }
     }
     return ret;
   }
double casadi::Options::word_distance (const std::string & a, const std::string & b) static
Levenshtein edit distance
Definition at line 71 of file options.cpp.
{
     if (a == b) return 0;
     int na = a.size();
     int nb = b.size();
     if (na == 0) return nb;
     if (nb == 0) return na;
     vector<int> v0(nb+1, 0);
     vector<int> v1(nb+1, 0);
     for (int i=0;i<nb+1;++i)
       v0[i] = i;
     char s;
     char t;
     std::locale loc;
     for (int i=0;i<na;i++) {
       v1[0] = i + 1;
       for (int j=0; j<nb; j++) {
         s = std::tolower(a[i], loc);
         t = std::tolower(b[j], loc);
         int cost = 0;
         if (s != t)
           cost = 1;
         v1[j+1] = min(min(v1[j] + 1, v0[j+1] + 1), v0[j] + cost);
       }
       for (int j=0; j<nb+1; j++)
         v0[j] = v1[j];
     }
     return v1[nb];
   }
Member Data Documentation
std::vector<Options*> casadi::Options::bases
Definition at line 41 of file options.hpp.
std::map<std::string, Entry> casadi::Options::entries
Definition at line 53 of file options.hpp.
The documentation for this struct was generated from the following files:
options.hpp
options.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge