CasADi: casadi::WeakRefInternal Class Reference
casadi::WeakRefInternal Class Reference
#include <weak_ref.hpp>
Detailed Description
Definition at line 77 of file weak_ref.hpp.
Public Member Functions
WeakRefInternal (SharedObjectNode *raw)
~WeakRefInternal ()
int getCount () const
Get the reference count.
virtual void repr (std::ostream &stream) const
Print a representation of the object.
virtual void print (std::ostream &stream) const
Print a description of the object.
WeakRef * weak ()
Get a weak reference to the object.
Public Attributes
SharedObjectNode * raw_
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Constructor & Destructor Documentation
casadi::WeakRefInternal::WeakRefInternal (SharedObjectNode * raw)
Definition at line 68 of file weak_ref.cpp.
                                                         : raw_(raw) {
   }
casadi::WeakRefInternal::~WeakRefInternal ()
Definition at line 71 of file weak_ref.cpp.
{
   }
Member Function Documentation
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
void casadi::SharedObjectNode::print (std::ostream & stream) const virtual inherited
Reimplemented in casadi::FunctionInternal, casadi::SparsityInternal, casadi::MapSum, casadi::SXFunction, casadi::MXNode, casadi::Mapaccum, casadi::KernelSum, casadi::MXFunction, casadi::Switch, casadi::CompilerInternal, casadi::GenericTypeInternal< ID, T >, and casadi::XmlFileInternal.
Definition at line 148 of file shared_object.cpp.
Referenced by casadi::operator<<().
{
     // Print the name of the object by default
     stream << typeid(this).name();
   }
void casadi::SharedObjectNode::repr (std::ostream & stream) const virtual inherited
Reimplemented in casadi::FunctionInternal, casadi::SparsityInternal, casadi::MXNode, casadi::CompilerInternal, and casadi::XmlFileInternal.
Definition at line 130 of file shared_object.cpp.
References casadi::print().
{
     // Print description by default
     print(stream);
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Member Data Documentation
SharedObjectNode* casadi::WeakRefInternal::raw_
Definition at line 86 of file weak_ref.hpp.
The documentation for this class was generated from the following files:
weak_ref.hpp
weak_ref.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge