CasADi: casadi::DllLibrary Class Reference
casadi::DllLibrary Class Reference
Dynamically linked library.
#include <compiler_internal.hpp>
Detailed Description
Author
Joel Andersson
Date
2016
Definition at line 133 of file compiler_internal.hpp.
Public Member Functions
DllLibrary (const std::string &bin_name)
virtual ~DllLibrary ()
virtual bool has (const std::string &sym) const
virtual signal_t get (const std::string &sym)
virtual const ParsedFile & meta () const
int getCount () const
Get the reference count.
virtual void repr (std::ostream &stream) const
Print a representation of the object.
virtual void print (std::ostream &stream) const
Print a description of the object.
WeakRef * weak ()
Get a weak reference to the object.
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Constructor & Destructor Documentation
casadi::DllLibrary::DllLibrary (const std::string & bin_name) explicit
Definition at line 100 of file compiler_internal.cpp.
     : bin_name_(bin_name), handle_(0) {
 #ifdef WITH_DL
 #ifdef _WIN32
     handle_ = LoadLibrary(TEXT(bin_name_.c_str()));
     casadi_assert_message(handle_!=0, "CommonExternal: Cannot open \""
                           << bin_name_ << "\". Error code (WIN32): "<< GetLastError());
 #else // _WIN32
     handle_ = dlopen(bin_name_.c_str(), RTLD_LAZY);
     casadi_assert_message(handle_!=0, "CommonExternal: Cannot open \""
                           << bin_name_ << "\". Error code: "<< dlerror());
     // reset error
     dlerror();
 #endif // _WIN32
 #else // WITH_DL
     casadi_error("CommonExternal: WITH_DL  not activated");
 #endif // WITH_DL
   }
casadi::DllLibrary::~DllLibrary () virtual
Definition at line 119 of file compiler_internal.cpp.
{
 #ifdef WITH_DL
     // close the dll
 #ifdef _WIN32
     if (handle_) FreeLibrary(handle_);
 #else // _WIN32
     if (handle_) dlclose(handle_);
 #endif // _WIN32
 #endif // WITH_DL
   }
Member Function Documentation
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
signal_t casadi::DllLibrary::get (const std::string & sym) virtual
Implements casadi::LibraryInternal.
Definition at line 134 of file compiler_internal.cpp.
{
 #ifdef WITH_DL
 #ifdef _WIN32
     return (signal_t)GetProcAddress(handle_, TEXT(sym.c_str()));
 #else // _WIN32
     signal_t fcnPtr = (signal_t)dlsym(handle_, sym.c_str());
     if (dlerror()) {
       fcnPtr=0;
       dlerror(); // Reset error flags
     }
     return fcnPtr;
 #endif // _WIN32
 #endif // WITH_DL
   }
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
bool casadi::DllLibrary::has (const std::string & sym) const virtual
Implements casadi::LibraryInternal.
Definition at line 130 of file compiler_internal.cpp.
{
     return const_cast<DllLibrary*>(this)->get(sym)!=0;
   }
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
const ParsedFile & casadi::DllLibrary::meta () const virtual
Implements casadi::LibraryInternal.
Definition at line 149 of file compiler_internal.cpp.
{
     static ParsedFile singleton;
     return singleton;
   }
void casadi::SharedObjectNode::print (std::ostream & stream) const virtual inherited
Reimplemented in casadi::FunctionInternal, casadi::SparsityInternal, casadi::MapSum, casadi::SXFunction, casadi::MXNode, casadi::Mapaccum, casadi::KernelSum, casadi::MXFunction, casadi::Switch, casadi::CompilerInternal, casadi::GenericTypeInternal< ID, T >, and casadi::XmlFileInternal.
Definition at line 148 of file shared_object.cpp.
Referenced by casadi::operator<<().
{
     // Print the name of the object by default
     stream << typeid(this).name();
   }
void casadi::SharedObjectNode::repr (std::ostream & stream) const virtual inherited
Reimplemented in casadi::FunctionInternal, casadi::SparsityInternal, casadi::MXNode, casadi::CompilerInternal, and casadi::XmlFileInternal.
Definition at line 130 of file shared_object.cpp.
References casadi::print().
{
     // Print description by default
     print(stream);
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
The documentation for this class was generated from the following files:
compiler_internal.hpp
compiler_internal.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge