CasADi: casadi::ShellCompiler Class Reference
casadi::ShellCompiler Class Reference
'shell' plugin for Compiler
#include <shell_compiler.hpp>
Detailed Description
Author
Joris Gillis
Date
2015
Interface to the JIT compiler SHELL
List of available options
Id Type Description
compiler OT_STRING Compiler command
compiler_setup OT_STRING Compiler setup command. Intended to be fixed. The 'flag' option is the prefered way to set custom flags.
flags OT_STRINGVECTOR Compile flags for the JIT compiler. Default: None
List of available options
Id Type Description Used in
compiler OT_STRING Compiler command casadi::ShellCompiler
compiler_setup OT_STRING Compiler setup command. Intended to be fixed. The 'flag' option is the prefered way to set custom flags. casadi::ShellCompiler
flags OT_STRINGVECTOR Compile flags for the JIT compiler. Default: None casadi::ShellCompiler
Definition at line 49 of file shell_compiler.hpp.
Public Types
typedef CompilerInternal *(* Creator)(const std::string &name)
typedef int(* RegFcn)(Plugin *plugin)
Public Member Functions
ShellCompiler (const std::string &name)
Constructor.
virtual ~ShellCompiler ()
Destructor.
virtual void init (const Dict &opts)
Initialize.
virtual const char * plugin_name () const
Get name of plugin.
virtual void * getFunction (const std::string &symname)
Get a function pointer for numerical evaluation.
virtual void print (std::ostream &stream) const
Print.
virtual void repr (std::ostream &stream) const
Print representation.
void construct (const Dict &opts)
Construct Prepares the function for evaluation.
void get_meta (std::vector< std::string > &lines, int &offset) const
Get meta information, if any.
int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static CompilerInternal * creator (const std::string &name)
Create a new JIT function.
static std::string shortname ()
Short name.
static bool hasPlugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin loadPlugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static CompilerInternal * instantiatePlugin (const std::string &fname, const std::string &pname, Problem problem)
Public Attributes
std::string name_
C filename.
ParsedFile meta_
Meta information.
Static Public Attributes
static const std::string meta_doc
A documentation string.
static std::map< std::string,
Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "compiler"
Infix.
Protected Types
typedef void * handle_t
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Protected Attributes
std::string bin_name_
Temporary file.
handle_t handle_
static Options options_
Options.
virtual const Options & get_options () const
Options.
Member Typedef Documentation
typedef CompilerInternal*(* casadi::CompilerInternal::Creator)(const std::string &name) inherited
Definition at line 62 of file compiler_internal.hpp.
typedef void* casadi::ShellCompiler::handle_t protected
Definition at line 85 of file shell_compiler.hpp.
typedef int(* casadi::PluginInterface< CompilerInternal >::RegFcn)(Plugin *plugin) inherited
Definition at line 85 of file plugin_interface.hpp.
Constructor & Destructor Documentation
casadi::ShellCompiler::ShellCompiler (const std::string & name) explicit
Definition at line 52 of file shell_compiler.cpp.
                                                     :
     CompilerInternal(name) {
   }
casadi::ShellCompiler::~ShellCompiler () virtual
Definition at line 56 of file shell_compiler.cpp.
References bin_name_, and handle_.
{
     // Unload
     if (handle_) dlclose(handle_);
     // Delete the temporary file
     std::string rmcmd = "rm " + bin_name_;
     if (system(rmcmd.c_str())) {
       casadi_warning("Failed to delete temporary file:" + bin_name_);
     }
   }
Member Function Documentation
void casadi::CompilerInternal::construct (const Dict & opts) inherited
Definition at line 55 of file compiler_internal.cpp.
References casadi::Options::find(), casadi::CompilerInternal::get_options(), casadi::CompilerInternal::init(), and casadi::Options::Entry::type.
{
     // Get a reference to the options structure
     const Options& options = get_options();
     // Make sure all options exist and have the correct type
     for (auto&& op : opts) {
       const Options::Entry* entry = options.find(op.first);
       casadi_assert_message(entry!=0, "No such option: " + op.first);
       casadi_assert_message(op.second.can_cast_to(entry->type),
                             "Illegal type for " + op.first);
     }
     init(opts);
   }
static CompilerInternal* casadi::ShellCompiler::creator (const std::string & name) inline static
Definition at line 56 of file shell_compiler.hpp.
{
       return new ShellCompiler(name);
     }
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
void casadi::CompilerInternal::get_meta (std::vector< std::string > & lines, int & offset) const inherited
Definition at line 78 of file compiler_internal.cpp.
References casadi::CompilerInternal::name_.
Referenced by casadi::CompilerInternal::init().
{
     // Open source file and search for meta information
     ifstream file(name_);
     std::string line;
     offset = 0;
     lines.clear();
     while (getline(file, line)) {
       // Update offset
       offset++;
       // Try to find a /*CASADI delimiter
       if (line.find("/*CASADIMETA") != string::npos) {
         // Delimimiter found, find */ delimiter
         while (getline(file, line)) {
           if (line.find("*/") != string::npos) return; // Successful return
           lines.push_back(line);
         }
         casadi_error("End-of-file reached while searching for \"*/\"");
       }
     }
   }
virtual const Options& casadi::ShellCompiler::get_options () const inline virtual
Reimplemented from casadi::CompilerInternal.
Definition at line 66 of file shell_compiler.hpp.
 { return options_;}
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
void * casadi::ShellCompiler::getFunction (const std::string & symname) virtual
Reimplemented from casadi::CompilerInternal.
Definition at line 149 of file shell_compiler.cpp.
References handle_.
{
     void* ret;
     ret = reinterpret_cast<void*>(dlsym(handle_, symname.c_str()));
     if (dlerror()) {
       ret=0;
       dlerror(); // Reset error flags
     }
     return ret;
   }
static Plugin& casadi::PluginInterface< CompilerInternal >::getPlugin (const std::string & pname) static inherited
static bool casadi::PluginInterface< CompilerInternal >::hasPlugin (const std::string & pname, bool verbose = false) static inherited
void casadi::ShellCompiler::init (const Dict & opts) virtual
Reimplemented from casadi::CompilerInternal.
Definition at line 83 of file shell_compiler.cpp.
References bin_name_, handle_, casadi::CompilerInternal::init(), and casadi::CompilerInternal::name_.
{
     // Base class
     CompilerInternal::init(opts);
     // Default options
     string compiler = "gcc";
     string compiler_setup = "-fPIC -shared";
     vector<string> flags;
     // Read options
     for (auto&& op : opts) {
       if (op.first=="compiler") {
         compiler = op.second.to_string();
       } else if (op.first=="compiler_setup") {
         compiler_setup = op.second.to_string();
       } else if (op.first=="flags") {
         flags = op.second;
       }
     }
     // Construct the compiler command
     stringstream cmd;
     cmd << compiler << " " << compiler_setup;
     for (vector<string>::const_iterator i=flags.begin(); i!=flags.end(); ++i) {
       cmd << " " << *i;
     }
     // C/C++ source file
     cmd << " " << name_;
     // Name of temporary file
 #ifdef HAVE_MKSTEMPS
     // Preferred solution
     char bin_name[] = "tmp_casadi_compiler_shell_XXXXXX.so";
     if (mkstemps(bin_name, 3) == -1) {
       casadi_error("Failed to create a temporary file name");
     }
     bin_name_ = bin_name;
 #else
     // Fallback, may result in deprecation warnings
     char* bin_name = tempnam(0, "ca.so");
     bin_name_ = bin_name;
     free(bin_name);
 #endif
     // Have relative paths start with ./
     if (bin_name_.at(0)!='/') {
       bin_name_ = "./" + bin_name_;
     }
     // Temporary file
     cmd << " -o " << bin_name_;
     // Compile into a shared library
     if (system(cmd.str().c_str())) {
       casadi_error("Compilation failed. Tried \"" + cmd.str() + "\"");
     }
     // Load shared library
     handle_ = dlopen(bin_name_.c_str(), RTLD_LAZY);
     casadi_assert_message(handle_!=0, "CommonExternal: Cannot open function: "
                           << bin_name_ << ". error code: "<< dlerror());
     // reset error
     dlerror();
   }
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
static CompilerInternal * casadi::PluginInterface< CompilerInternal >::instantiatePlugin (const std::string & fname, const std::string & pname, Problem problem) static inherited
static Plugin casadi::PluginInterface< CompilerInternal >::loadPlugin (const std::string & pname, bool register_plugin = true) static inherited
virtual const char* casadi::ShellCompiler::plugin_name () const inline virtual
Reimplemented from casadi::CompilerInternal.
Definition at line 76 of file shell_compiler.hpp.
 { return "shell";}
static Plugin casadi::PluginInterface< CompilerInternal >::pluginFromRegFcn (RegFcn regfcn) static inherited
void casadi::CompilerInternal::print (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Definition at line 37 of file compiler_internal.cpp.
{
     stream << "Compiler" << endl;
   }
static void casadi::PluginInterface< CompilerInternal >::registerPlugin (const Plugin & plugin) static inherited
static void casadi::PluginInterface< CompilerInternal >::registerPlugin (RegFcn regfcn) static inherited
void casadi::CompilerInternal::repr (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Definition at line 41 of file compiler_internal.cpp.
{
     stream << "Compiler" << endl;
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
static std::string casadi::CompilerInternal::shortname () inline static inherited
Definition at line 88 of file compiler_internal.hpp.
 { return "compiler";}
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Member Data Documentation
std::string casadi::ShellCompiler::bin_name_ protected
Definition at line 82 of file shell_compiler.hpp.
Referenced by init(), and ~ShellCompiler().
handle_t casadi::ShellCompiler::handle_ protected
Definition at line 86 of file shell_compiler.hpp.
Referenced by getFunction(), init(), and ~ShellCompiler().
const std::string casadi::CompilerInternal::infix_ = "compiler" static inherited
Definition at line 85 of file compiler_internal.hpp.
ParsedFile casadi::CompilerInternal::meta_ inherited
Definition at line 103 of file compiler_internal.hpp.
Referenced by casadi::CompilerInternal::init().
const std::string casadi::ShellCompiler::meta_doc static
Initial value:
=
      "\n"
"\n"
Definition at line 73 of file shell_compiler.hpp.
std::string casadi::CompilerInternal::name_ inherited
Definition at line 100 of file compiler_internal.hpp.
Referenced by casadi::CompilerInternal::get_meta(), init(), and casadi::ClangCompiler::init().
Options casadi::ShellCompiler::options_ static
Initial value:
= {{&CompilerInternal::options_},
     {{"compiler",
       {OT_STRING,
        "Compiler command"}},
      {"compiler_setup",
       {OT_STRING,
        "Compiler setup command. Intended to be fixed."
        " The 'flag' option is the prefered way to set"
        " custom flags."}},
      {"flags",
       {OT_STRINGVECTOR,
      "Compile flags for the JIT compiler. Default: None"}}
     }
  }
Definition at line 65 of file shell_compiler.hpp.
std::map< std::string, CompilerInternal::Plugin > casadi::CompilerInternal::solvers_ static inherited
Definition at line 82 of file compiler_internal.hpp.
The documentation for this class was generated from the following files:
shell_compiler.hpp
shell_compiler.cpp
shell_compiler_meta.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge