CasADi: casadi::InterruptHandler Class Reference
casadi::InterruptHandler Class Reference
Takes care of user interrupts (Ctrl+C)
#include <casadi_interrupt.hpp>
Detailed Description
This is an internal class.
Author
Joris Gillis
Date
2015
Definition at line 47 of file casadi_interrupt.hpp.
Static Public Member Functions
static void check ()
Raises an error if an interrupt was captured.
Static Public Attributes
static bool(* checkInterrupted)()
The routine that is used for checking interrupts.
Member Function Documentation
static void casadi::InterruptHandler::check () inline static
Definition at line 62 of file casadi_interrupt.hpp.
Referenced by casadi::Nlpsol::calc_function(), casadi::MXFunction::print(), casadi::SXFunction::print(), and casadi::Matrix< Scalar >::print_sparse().
{
       casadi_assert_message(!checkInterrupted(), "Interrupted by user.");
     }
Member Data Documentation
bool(* casadi::InterruptHandler::checkInterrupted)() static
Initial value:
=
    InterruptHandler::checkInterruptedDefault
Definition at line 59 of file casadi_interrupt.hpp.
The documentation for this class was generated from the following files:
casadi_interrupt.hpp
casadi_interrupt.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge