CasADi: casadi::SharedObjectNode Class Reference
casadi::SharedObjectNode Class Reference abstract
#include <shared_object.hpp>
Detailed Description
Internal class for the reference counting framework, see comments on the public class.
Definition at line 162 of file shared_object.hpp.
Public Member Functions
SharedObjectNode ()
Default constructor.
SharedObjectNode (const SharedObjectNode &node)
Copy constructor.
SharedObjectNode & operator= (const SharedObjectNode &node)
Assignment operator.
virtual ~SharedObjectNode ()=0
Destructor.
int getCount () const
Get the reference count.
virtual void repr (std::ostream &stream) const
Print a representation of the object.
virtual void print (std::ostream &stream) const
Print a description of the object.
WeakRef * weak ()
Get a weak reference to the object.
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Friends
class SharedObject
class Memory
Constructor & Destructor Documentation
casadi::SharedObjectNode::SharedObjectNode ()
Definition at line 104 of file shared_object.cpp.
{
     count = 0;
     weak_ref_ = 0;
   }
casadi::SharedObjectNode::SharedObjectNode (const SharedObjectNode & node)
Definition at line 38 of file shared_object.cpp.
{
     count = 0; // reference counter is _not_ copied
     weak_ref_ = 0; // nor will they have the same weak references
   }
casadi::SharedObjectNode::~SharedObjectNode () pure virtual
Definition at line 109 of file shared_object.cpp.
{
     if (count!=0) {
       // Note that casadi_assert_warning cannot be used in destructors
       std::cerr << "Reference counting failure." <<
                    "Possible cause: Circular dependency in user code." << std::endl;
     }
     if (weak_ref_!=0) {
       weak_ref_->kill();
       delete weak_ref_;
     }
   }
Member Function Documentation
void casadi::SharedObjectNode::destroySingleton () inline protected
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
int casadi::SharedObjectNode::getCount () const
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
void casadi::SharedObjectNode::initSingleton () inline protected
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
SharedObjectNode & casadi::SharedObjectNode::operator= (const SharedObjectNode & node)
Definition at line 43 of file shared_object.cpp.
{
     // do _not_ copy the reference counter
     return *this;
   }
void casadi::SharedObjectNode::print (std::ostream & stream) const virtual
Reimplemented in casadi::FunctionInternal, casadi::SparsityInternal, casadi::MapSum, casadi::SXFunction, casadi::MXNode, casadi::Mapaccum, casadi::KernelSum, casadi::MXFunction, casadi::Switch, casadi::CompilerInternal, casadi::GenericTypeInternal< ID, T >, and casadi::XmlFileInternal.
Definition at line 148 of file shared_object.cpp.
Referenced by casadi::operator<<().
{
     // Print the name of the object by default
     stream << typeid(this).name();
   }
void casadi::SharedObjectNode::repr (std::ostream & stream) const virtual
Reimplemented in casadi::FunctionInternal, casadi::SparsityInternal, casadi::MXNode, casadi::CompilerInternal, and casadi::XmlFileInternal.
Definition at line 130 of file shared_object.cpp.
References casadi::print().
{
     // Print description by default
     print(stream);
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
WeakRef * casadi::SharedObjectNode::weak ()
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Friends And Related Function Documentation
friend class Memory friend
Definition at line 164 of file shared_object.hpp.
friend class SharedObject friend
Definition at line 163 of file shared_object.hpp.
The documentation for this class was generated from the following files:
shared_object.hpp
shared_object.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge