CasADi: casadi::BinaryOperation< I > Struct Template Reference
casadi::BinaryOperation< I > Struct Template Reference
#include <calculus.hpp>
Detailed Description
template<int I>
struct casadi::BinaryOperation< I >
Definition at line 345 of file calculus.hpp.
Static Public Member Functions
template<typename T >
static void fcn (const T &x, const T &y, T &f)
Function evaluation.
template<typename T >
static void der (const T &x, const T &y, const T &f, T *d)
Partial derivatives - binary function.
Member Function Documentation
template<int I> template<typename T > static void casadi::BinaryOperation< I >::der (const T & x, const T & y, const T & f, T * d) inline static
Definition at line 351 of file calculus.hpp.
References casadi::UnaryOperation< I >::der().
Referenced by casadi::BinaryOperationSS< I >::der(), casadi::BinaryOperationVV< I >::der(), casadi::BinaryOperationVS< I >::der(), casadi::BinaryOperationSV< I >::der(), and casadi::DerBinaryOpertion< I >::derf().
{
         UnaryOperation<I>::der(x, f, d); d[1]=0; }
template<int I> template<typename T > static void casadi::BinaryOperation< I >::fcn (const T & x, const T & y, T & f) inline static
Definition at line 347 of file calculus.hpp.
References casadi::UnaryOperation< I >::fcn().
Referenced by casadi::DerBinaryOpertion< I >::derf(), casadi::BinaryOperationE< I >::fcn(), casadi::BinaryOperationSS< I >::fcn(), casadi::BinaryOperationVV< I >::fcn(), casadi::BinaryOperationVS< I >::fcn(), and casadi::BinaryOperationSV< I >::fcn().
{
         UnaryOperation<I>::fcn(x, f);}
The documentation for this struct was generated from the following file:
calculus.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge