CasADi: casadi::TinyXmlInterface Class Reference
casadi::TinyXmlInterface Class Reference
'tinyxml' plugin for XmlFile
#include <tinyxml_interface.hpp>
Detailed Description
XmlFile using TinyXml
Definition at line 46 of file tinyxml_interface.hpp.
Public Types
typedef XmlFileInternal *(* Creator)()
typedef int(* RegFcn)(Plugin *plugin)
Public Member Functions
TinyXmlInterface ()
virtual const char * plugin_name () const
virtual XmlNode parse (const std::string &filename)
XmlNode addNode (TiXmlNode *n)
virtual ~TinyXmlInterface ()
virtual void print (std::ostream &stream) const
Print.
virtual void repr (std::ostream &stream) const
Print representation.
int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static XmlFileInternal * creator ()
Create a new XmlFile.
static bool hasPlugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin loadPlugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static XmlFileInternal * instantiatePlugin (const std::string &fname, const std::string &pname, Problem problem)
Public Attributes
TiXmlDocument doc_
XML file.
Static Public Attributes
static const std::string meta_doc
A documentation string.
static std::map< std::string,
Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "xmlfile"
Infix.
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Member Typedef Documentation
typedef XmlFileInternal*(* casadi::XmlFileInternal::Creator)() inherited
Definition at line 55 of file xml_file_internal.hpp.
typedef int(* casadi::PluginInterface< XmlFileInternal >::RegFcn)(Plugin *plugin) inherited
Definition at line 85 of file plugin_interface.hpp.
Constructor & Destructor Documentation
casadi::TinyXmlInterface::TinyXmlInterface ()
Definition at line 46 of file tinyxml_interface.cpp.
                                      : XmlFileInternal() {
   }
casadi::TinyXmlInterface::~TinyXmlInterface () virtual
Definition at line 49 of file tinyxml_interface.cpp.
{
   }
Member Function Documentation
XmlNode casadi::TinyXmlInterface::addNode (TiXmlNode * n)
Definition at line 58 of file tinyxml_interface.cpp.
References casadi::XmlNode::child_indices_, casadi::XmlNode::children_, casadi::XmlNode::comment_, casadi::XmlNode::name(), casadi::XmlNode::set_attribute(), casadi::XmlNode::setName(), casadi::XmlNode::text_, and casadi::userOut().
Referenced by parse().
{
     if (!n) throw CasadiException("Error in TinyXmlInterface::addNode: Node is 0");
     XmlNode ret;
     // Save name
     ret.setName(n->Value());
     // Save attributes
     int type = n->Type();
     if (type == TiXmlNode::TINYXML_ELEMENT) {
       if (n->ToElement()!=0) {
         for (TiXmlAttribute* pAttrib=n->ToElement()->FirstAttribute();
              pAttrib;
              pAttrib=pAttrib->Next()) {
           ret.set_attribute(pAttrib->Name(), pAttrib->Value());
         }
       }
     } else if (type == TiXmlNode::TINYXML_DOCUMENT) {
       // do nothing
     } else {
       throw CasadiException("TinyXmlInterface::addNode");
     }
     // Count the number of children
     int num_children = 0;
     for (TiXmlNode* child = n->FirstChild(); child != 0; child= child->NextSibling()) {
       num_children++;
     }
     ret.children_.reserve(num_children);
     // add children
     int ch = 0;
     for (TiXmlNode* child = n->FirstChild(); child != 0; child= child->NextSibling(), ++ch) {
       int childtype = child->Type();
       if (childtype == TiXmlNode::TINYXML_ELEMENT) {
         XmlNode newnode = addNode(child);
         ret.children_.push_back(newnode);
         ret.child_indices_[newnode.name()] = ch;
       } else if (childtype == TiXmlNode::TINYXML_COMMENT) {
         ret.comment_ = child->Value();
       } else if (childtype == TiXmlNode::TINYXML_TEXT) {
         ret.text_ = child->ToText()->Value();
       } else if (childtype == TiXmlNode::TINYXML_DECLARATION) {
         userOut() << "Warning: Skipped TiXmlNode::TINYXML_DECLARATION" << endl;
       } else {
         throw CasadiException("Error in TinyXmlInterface::addNode: Unknown node type");
       }
     }
     // Note: Return value optimization
     return ret;
   }
static XmlFileInternal* casadi::TinyXmlInterface::creator () inline static
Definition at line 53 of file tinyxml_interface.hpp.
     { return new TinyXmlInterface();}
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
static Plugin& casadi::PluginInterface< XmlFileInternal >::getPlugin (const std::string & pname) static inherited
static bool casadi::PluginInterface< XmlFileInternal >::hasPlugin (const std::string & pname, bool verbose = false) static inherited
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
static XmlFileInternal * casadi::PluginInterface< XmlFileInternal >::instantiatePlugin (const std::string & fname, const std::string & pname, Problem problem) static inherited
static Plugin casadi::PluginInterface< XmlFileInternal >::loadPlugin (const std::string & pname, bool register_plugin = true) static inherited
XmlNode casadi::TinyXmlInterface::parse (const std::string & filename) virtual
Reimplemented from casadi::XmlFileInternal.
Definition at line 52 of file tinyxml_interface.cpp.
References addNode(), and doc_.
{
     bool flag = doc_.LoadFile(filename.c_str());
     casadi_assert_message(flag, "Cound not open " << filename);
     return addNode(&doc_);
   }
virtual const char* casadi::TinyXmlInterface::plugin_name () const inline virtual
Implements casadi::PluginInterface< XmlFileInternal >.
Definition at line 57 of file tinyxml_interface.hpp.
 { return "tinyxml";}
static Plugin casadi::PluginInterface< XmlFileInternal >::pluginFromRegFcn (RegFcn regfcn) static inherited
void casadi::XmlFileInternal::print (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Definition at line 42 of file xml_file_internal.cpp.
{
     stream << "XmlFile" << endl;
   }
static void casadi::PluginInterface< XmlFileInternal >::registerPlugin (const Plugin & plugin) static inherited
static void casadi::PluginInterface< XmlFileInternal >::registerPlugin (RegFcn regfcn) static inherited
void casadi::XmlFileInternal::repr (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Definition at line 46 of file xml_file_internal.cpp.
{
     stream << "XmlFile" << endl;
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Member Data Documentation
TiXmlDocument casadi::TinyXmlInterface::doc_
Definition at line 72 of file tinyxml_interface.hpp.
Referenced by parse().
const std::string casadi::XmlFileInternal::infix_ = "xmlfile" static inherited
Definition at line 64 of file xml_file_internal.hpp.
const std::string casadi::TinyXmlInterface::meta_doc static
Initial value:
=
      "\n"
"XmlFile using TinyXml\n"
"\n"
"\n"
">List of available options\n"
"\n"
"+----+------+---------+-------------+\n"
"| Id | Type | Default | Description |\n"
"+====+======+=========+=============+\n"
"+----+------+---------+-------------+\n"
"\n"
"\n"
"\n"
"\n"
Definition at line 69 of file tinyxml_interface.hpp.
std::map< std::string, XmlFileInternal::Plugin > casadi::XmlFileInternal::solvers_ static inherited
Definition at line 61 of file xml_file_internal.hpp.
The documentation for this class was generated from the following files:
tinyxml_interface.hpp
tinyxml_interface.cpp
tinyxml_interface_meta.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge