CasADi: casadi::GenericType Class Reference
casadi::GenericType Class Reference
Generic data type, can hold different types such as bool, int, string etc.
#include <generic_type.hpp>
Detailed Description
Author
Joel Andersson
Date
2010
Definition at line 60 of file generic_type.hpp.
Public Types
typedef std::map< std::string,
GenericType > Dict
C++ equivalent of Python's dict or MATLAB's struct.
Public Member Functions
GenericType ()
Default constructor.
GenericType (bool b)
Constructors (implicit type conversion)
GenericType (int i)
GenericType (double d)
GenericType (const std::string &s)
GenericType (const std::vector< bool > &iv)
GenericType (const std::vector< int > &iv)
GenericType (const std::vector< std::vector< int > > &ivv)
GenericType (const std::vector< double > &dv)
GenericType (const std::vector< std::string > &sv)
GenericType (const char s[])
GenericType (const Function &f)
GenericType (const Dict &dict)
GenericType (void *ptr)
std::string get_description () const
Get a description of the object's type.
TypeID getType () const
bool can_cast_to (TypeID other) const
bool can_cast_to (const GenericType &other) const
bool operator== (const GenericType &op2) const
Equality.
bool operator!= (const GenericType &op2) const
void assignNode (SharedObjectNode *node)
void assignNodeNoCount (SharedObjectNode *node)
Assign the node to a node class pointer without reference counting.
SharedObjectNode * get () const
Get a const pointer to the node.
int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
SharedObjectNode * operator-> () const
Access a member function or object.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void printPtr (std::ostream &stream=casadi::userOut()) const
bool is_null () const
Is a null pointer?
WeakRef * weak ()
Get a weak reference to the object.
size_t __hash__ () const
Returns a number that is unique for a given Node. If the Object does not point to any node, "0" is returned.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
operator bool () const
operator int () const
operator double () const
operator std::string () const
operator std::vector< bool > () const
operator std::vector< int > () const
operator std::vector< std::vector< int > > () const
operator std::vector< double > () const
operator std::vector< std::string > () const
operator const Function & () const
operator const Dict & () const
bool is_bool () const
Check if a particular type.
bool is_int () const
Check if a particular type.
bool is_double () const
Check if a particular type.
bool is_string () const
Check if a particular type.
bool is_empty_vector () const
Check if a particular type.
bool is_int_vector () const
Check if a particular type.
bool is_int_vector_vector () const
Check if a particular type.
bool is_double_vector () const
Check if a particular type.
bool is_string_vector () const
Check if a particular type.
bool is_dict () const
Check if a particular type.
bool is_function () const
Check if a particular type.
bool is_void_pointer () const
Check if a particular type.
const bool & as_bool () const
Cast to the internal type.
const int & as_int () const
Cast to the internal type.
const double & as_double () const
Cast to the internal type.
const std::string & as_string () const
Cast to the internal type.
const std::vector< int > & as_int_vector () const
Cast to the internal type.
const std::vector< std::vector
< int > > & as_int_vector_vector () const
Cast to the internal type.
const std::vector< double > & as_double_vector () const
Cast to the internal type.
const std::vector< std::string > & as_string_vector () const
Cast to the internal type.
const Dict & as_dict () const
Cast to the internal type.
const Function & as_function () const
Cast to the internal type.
void *const & as_void_pointer () const
Cast to the internal type.
bool to_bool () const
Convert to a type.
int to_int () const
Convert to a type.
double to_double () const
Convert to a type.
std::string to_string () const
Convert to a type.
std::vector< int > to_int_vector () const
Convert to a type.
std::vector< bool > to_bool_vector () const
Convert to a type.
std::vector< std::vector< int > > to_int_vector_vector () const
Convert to a type.
std::vector< double > to_double_vector () const
Convert to a type.
std::vector< std::string > to_string_vector () const
Convert to a type.
Dict to_dict () const
Convert to a type.
Function to_function () const
Convert to a type.
void * to_void_pointer () const
Convert to a type.
Static Public Member Functions
static std::string get_type_description (TypeID type)
Get a description of a type.
static GenericType from_type (TypeID type)
Construct a GenericType given an TypeID.
Protected Member Functions
void count_up ()
void count_down ()
Friends
CASADI_EXPORT friend std::ostream & operator<< (std::ostream &stream, const GenericType &ref)
Print.
Member Typedef Documentation
typedef std::map<std::string, GenericType> casadi::GenericType::Dict
Definition at line 67 of file generic_type.hpp.
Constructor & Destructor Documentation
casadi::GenericType::GenericType ()
Definition at line 172 of file generic_type.cpp.
{
   }
casadi::GenericType::GenericType (bool b)
Definition at line 184 of file generic_type.cpp.
{
     assignNode(new BoolType(b));
   }
casadi::GenericType::GenericType (int i)
Definition at line 188 of file generic_type.cpp.
{
     assignNode(new IntType(i));
   }
casadi::GenericType::GenericType (double d)
Definition at line 192 of file generic_type.cpp.
{
     assignNode(new DoubleType(d));
   }
casadi::GenericType::GenericType (const std::string & s)
casadi::GenericType::GenericType (const std::vector< bool > & iv)
casadi::GenericType::GenericType (const std::vector< int > & iv)
casadi::GenericType::GenericType (const std::vector< std::vector< int > > & ivv)
casadi::GenericType::GenericType (const std::vector< double > & dv)
casadi::GenericType::GenericType (const std::vector< std::string > & sv)
casadi::GenericType::GenericType (const char s[])
Definition at line 222 of file generic_type.cpp.
{
     assignNode(new StringType(s));
   }
casadi::GenericType::GenericType (const Function & f)
Definition at line 226 of file generic_type.cpp.
{
     assignNode(new FunctionType(f));
   }
casadi::GenericType::GenericType (const Dict & dict)
Definition at line 424 of file generic_type.cpp.
{
     assignNode(new DictType(dict));
   }
casadi::GenericType::GenericType (void * ptr)
Definition at line 433 of file generic_type.cpp.
{
     assignNode(new VoidPointerType(ptr));
   }
Member Function Documentation
size_t casadi::SharedObject::__hash__ () const inherited
Definition at line 178 of file shared_object.cpp.
{
     return reinterpret_cast<size_t>(get());
   }
const bool & casadi::GenericType::as_bool () const
Definition at line 230 of file generic_type.cpp.
{
     casadi_assert(is_bool());
     return static_cast<const BoolType*>(get())->d_;
   }
const GenericType::Dict & casadi::GenericType::as_dict () const
Definition at line 270 of file generic_type.cpp.
{
     casadi_assert(is_dict());
     return static_cast<const DictType*>(get())->d_;
   }
const double & casadi::GenericType::as_double () const
Definition at line 240 of file generic_type.cpp.
{
     casadi_assert(is_double());
     return static_cast<const DoubleType*>(get())->d_;
   }
const std::vector< double > & casadi::GenericType::as_double_vector () const
Definition at line 260 of file generic_type.cpp.
{
     casadi_assert(is_double_vector());
     return static_cast<const DoubleVectorType*>(get())->d_;
   }
const Function & casadi::GenericType::as_function () const
Definition at line 275 of file generic_type.cpp.
{
     casadi_assert(is_function());
     return static_cast<const FunctionType*>(get())->d_;
   }
const int & casadi::GenericType::as_int () const
Definition at line 235 of file generic_type.cpp.
{
     casadi_assert(is_int());
     return static_cast<const IntType*>(get())->d_;
   }
const std::vector< int > & casadi::GenericType::as_int_vector () const
Definition at line 250 of file generic_type.cpp.
{
     casadi_assert(is_int_vector());
     return static_cast<const IntVectorType*>(get())->d_;
   }
const std::vector< std::vector< int > > & casadi::GenericType::as_int_vector_vector () const
Definition at line 255 of file generic_type.cpp.
{
     casadi_assert(is_int_vector_vector());
     return static_cast<const IntVectorVectorType*>(get())->d_;
   }
const std::string & casadi::GenericType::as_string () const
Definition at line 245 of file generic_type.cpp.
{
     casadi_assert(is_string());
     return static_cast<const StringType*>(get())->d_;
   }
const std::vector< std::string > & casadi::GenericType::as_string_vector () const
Definition at line 265 of file generic_type.cpp.
{
     casadi_assert(is_string_vector());
     return static_cast<const StringVectorType*>(get())->d_;
   }
void *const & casadi::GenericType::as_void_pointer () const
Definition at line 280 of file generic_type.cpp.
{
     casadi_assert(is_void_pointer());
     return static_cast<const VoidPointerType*>(get())->d_;
   }
void casadi::SharedObject::assignNode (SharedObjectNode * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 57 of file shared_object.cpp.
Referenced by casadi::Function::conditional(), casadi::Callback::construct(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::Sparsity::create(), casadi::Function::create(), casadi::external(), casadi::Function::if_else(), casadi::MXFunction::init(), casadi::integrator(), casadi::jit(), casadi::Function::kernel_sum(), casadi::linsol(), casadi::nlpsol(), casadi::qpsol(), casadi::rootfinder(), and casadi::WeakRef::shared().
{
     count_down();
     node = node_;
     count_up();
   }
void casadi::SharedObject::assignNodeNoCount (SharedObjectNode * node) inherited
improper use will cause memory leaks!
Definition at line 63 of file shared_object.cpp.
{
     node = node_;
   }
bool casadi::GenericType::can_cast_to (TypeID other) const
Definition at line 52 of file generic_type.cpp.
References casadi::OT_BOOL, casadi::OT_BOOLVECTOR, casadi::OT_DOUBLE, casadi::OT_DOUBLEVECTOR, casadi::OT_INT, casadi::OT_INTVECTOR, and casadi::OT_STRINGVECTOR.
{
     switch (other) {
     case OT_BOOL:
       return is_bool() || is_int() || is_double();
     case OT_BOOLVECTOR:
       return is_int_vector() || is_double_vector();
     case OT_INT:
     case OT_DOUBLE:
       return is_int() || is_double();
     case OT_INTVECTOR:
     case OT_DOUBLEVECTOR:
       return is_double_vector() || is_int_vector();
     case OT_STRINGVECTOR:
       return is_string_vector() || is_string();
     default:
       return getType() == other;
     }
   }
bool casadi::GenericType::can_cast_to (const GenericType & other) const inline
Definition at line 117 of file generic_type.hpp.
References can_cast_to(), and getType().
Referenced by can_cast_to().
 { return can_cast_to(other.getType()) ;}
void casadi::SharedObject::count_down () protected inherited
Definition at line 92 of file shared_object.cpp.
Referenced by casadi::Callback::transfer_ownership().
{
     if (node && --node->count == 0) {
       delete node;
       node = 0;
     }
   }
void casadi::SharedObject::count_up () protected inherited
Definition at line 88 of file shared_object.cpp.
{
     if (node) node->count++;
   }
GenericType casadi::GenericType::from_type (TypeID type) static
Definition at line 71 of file generic_type.cpp.
References casadi::OT_BOOLVECTOR, casadi::OT_DOUBLEVECTOR, casadi::OT_INTVECTOR, and casadi::OT_STRINGVECTOR.
{
     switch (type) {
     case OT_INTVECTOR:
       return std::vector<int>();
     case OT_INTVECTORVECTOR:
       return std::vector< std::vector<int> >();
     case OT_BOOLVECTOR:
       return std::vector<bool>();
     case OT_DOUBLEVECTOR:
       return std::vector<double>();
     case OT_STRINGVECTOR:
       return std::vector<std::string>();
     default:
       casadi_error("empty_from_type. Unsupported type " << type);
     }
   }
SharedObjectNode * casadi::SharedObject::get () const inherited
Definition at line 80 of file shared_object.cpp.
Referenced by casadi::CodeGenerator::addSparsity(), casadi::CodeGenerator::get_sparsity(), casadi::SparsityInternal::is_equal(), casadi::SparsityInternal::maxTransversal(), and casadi::shared_cast().
{
     return node;
   }
std::string casadi::GenericType::get_description () const inline
Definition at line 93 of file generic_type.hpp.
 { return get_type_description(getType()); }
std::string casadi::GenericType::get_type_description (TypeID type) static
Definition at line 88 of file generic_type.cpp.
References casadi::OT_BOOL, casadi::OT_BOOLVECTOR, casadi::OT_DICT, casadi::OT_DOUBLE, casadi::OT_DOUBLEVECTOR, casadi::OT_FUNCTION, casadi::OT_INT, casadi::OT_INTVECTOR, casadi::OT_STRING, casadi::OT_STRINGVECTOR, and casadi::OT_VOIDPTR.
{
     switch (type) {
     case OT_BOOL:
       return "OT_BOOL";
     case OT_INT:
       return "OT_INT";
     case OT_DOUBLE:
       return "OT_DOUBLE";
     case OT_STRING:
       return "OT_STRING";
     case OT_INTVECTOR:
       return "OT_INTVECTOR";
     case OT_INTVECTORVECTOR:
       return "OT_INTVECTORVECTOR";
     case OT_BOOLVECTOR:
       return "OT_BOOLVECTOR";
     case OT_DOUBLEVECTOR:
       return "OT_DOUBLEVECTOR";
     case OT_STRINGVECTOR:
       return "OT_STRINGVECTOR";
     case OT_DICT:
       return "OT_DICT";
     case OT_FUNCTION:
       return "OT_FUNCTION";
     case OT_VOIDPTR:
       return "OT_VOIDPTR";
     default:
       return "OT_UNKNOWN";
     }
   }
int casadi::SharedObject::getCount () const inherited
Definition at line 159 of file shared_object.cpp.
References casadi::SharedObjectNode::getCount().
Referenced by casadi::Callback::transfer_ownership().
{
     return (*this)->getCount();
   }
std::string casadi::PrintableObject< SharedObject >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< SharedObject >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
TypeID casadi::GenericType::getType () const
Definition at line 437 of file generic_type.cpp.
References casadi::GenericTypeBase::getType(), and casadi::OT_NULL.
Referenced by can_cast_to().
{
     if (is_null()) {
       return OT_NULL;
     } else {
       return static_cast<const GenericTypeBase*>(get())->getType();
     }
   }
bool casadi::GenericType::is_bool () const
Definition at line 121 of file generic_type.cpp.
References casadi::OT_BOOL.
{
     return getType()==OT_BOOL;
   }
bool casadi::GenericType::is_dict () const
Definition at line 168 of file generic_type.cpp.
References casadi::OT_DICT.
{
     return getType()==OT_DICT;
   }
bool casadi::GenericType::is_double () const
Definition at line 129 of file generic_type.cpp.
References casadi::OT_DOUBLE.
Referenced by operator!=().
{
     return getType()==OT_DOUBLE;
   }
bool casadi::GenericType::is_double_vector () const
Definition at line 152 of file generic_type.cpp.
References casadi::OT_DOUBLEVECTOR.
Referenced by operator!=().
{
     return getType()==OT_DOUBLEVECTOR;
   }
bool casadi::GenericType::is_empty_vector () const
Definition at line 137 of file generic_type.cpp.
{
     return (is_int_vector() && to_int_vector().size()==0) ||
       (is_int_vector_vector() && to_int_vector_vector().size()==0) ||
       (is_double_vector() && to_double_vector().size()==0) ||
       (is_string_vector() && to_string_vector().size()==0);
   }
bool casadi::GenericType::is_function () const
Definition at line 160 of file generic_type.cpp.
References casadi::OT_FUNCTION.
{
     return getType()==OT_FUNCTION;
   }
bool casadi::GenericType::is_int () const
Definition at line 125 of file generic_type.cpp.
References casadi::OT_INT.
Referenced by operator!=().
{
     return getType()==OT_INT;
   }
bool casadi::GenericType::is_int_vector () const
Definition at line 144 of file generic_type.cpp.
References casadi::OT_INTVECTOR.
Referenced by operator!=().
{
     return getType()==OT_INTVECTOR;
   }
bool casadi::GenericType::is_int_vector_vector () const
Definition at line 148 of file generic_type.cpp.
Referenced by operator!=().
{
     return getType()==OT_INTVECTORVECTOR;
   }
bool casadi::SharedObject::is_null () const inherited
Definition at line 84 of file shared_object.cpp.
Referenced by casadi::FunctionInternal::alloc(), casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::Integrator::fun2problem(), casadi::Switch::generateBody(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), casadi::SundialsInterface::getBandwidth(), casadi::SundialsInterface::getBandwidthB(), casadi::FunctionInternal::getPartition(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Newton::init(), casadi::Integrator::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::FixedStepIntegrator::init(), casadi::CvodesInterface::init_memory(), casadi::IdasInterface::init_memory(), casadi::FixedStepIntegrator::init_memory(), casadi::CvodesInterface::initIterativeLinsol(), casadi::IdasInterface::initIterativeLinsol(), casadi::CvodesInterface::initIterativeLinsolB(), casadi::IdasInterface::initIterativeLinsolB(), casadi::CvodesInterface::initUserDefinedLinsol(), casadi::IdasInterface::initUserDefinedLinsol(), casadi::CvodesInterface::initUserDefinedLinsolB(), casadi::IdasInterface::initUserDefinedLinsolB(), casadi::Integrator::Integrator(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::Linsol(), casadi::SparsityInternal::maxTransversal(), casadi::operator<<(), casadi::IdasInterface::psolveB(), casadi::Qpsol::Qpsol(), casadi::SnoptInterface::set_work(), casadi::RkIntegrator::setupFG(), casadi::CollocationIntegrator::setupFG(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Integrator::spAdj(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), casadi::Integrator::spFwd(), casadi::FunctionInternal::spFwd(), casadi::Callback::transfer_ownership(), casadi::Sparsity::uni_coloring(), casadi::SnoptInterface::userfun(), and casadi::Callback::~Callback().
{
     return node==0;
   }
bool casadi::GenericType::is_string () const
Definition at line 133 of file generic_type.cpp.
References casadi::OT_STRING.
Referenced by operator!=().
{
     return getType()==OT_STRING;
   }
bool casadi::GenericType::is_string_vector () const
Definition at line 156 of file generic_type.cpp.
References casadi::OT_STRINGVECTOR.
{
     return getType()==OT_STRINGVECTOR;
   }
bool casadi::GenericType::is_void_pointer () const
Definition at line 164 of file generic_type.cpp.
References casadi::OT_VOIDPTR.
{
     return getType()==OT_VOIDPTR;
   }
casadi::GenericType::operator bool () const inline
Implicit typecasting
Definition at line 100 of file generic_type.hpp.
 { return to_bool();}
casadi::GenericType::operator const Dict & () const inline
Implicit typecasting
Definition at line 110 of file generic_type.hpp.
 { return as_dict();}
casadi::GenericType::operator const Function & () const inline
Implicit typecasting
Definition at line 109 of file generic_type.hpp.
 { return as_function();}
casadi::GenericType::operator double () const inline
Implicit typecasting
Definition at line 102 of file generic_type.hpp.
 { return to_double();}
casadi::GenericType::operator int () const inline
Implicit typecasting
Definition at line 101 of file generic_type.hpp.
 { return to_int();}
casadi::GenericType::operator std::string () const inline
Implicit typecasting
Definition at line 103 of file generic_type.hpp.
 { return to_string();}
casadi::GenericType::operator std::vector< bool > () const inline
Implicit typecasting
Definition at line 104 of file generic_type.hpp.
 { return to_bool_vector();}
casadi::GenericType::operator std::vector< double > () const inline
Implicit typecasting
Definition at line 107 of file generic_type.hpp.
 { return to_double_vector();}
casadi::GenericType::operator std::vector< int > () const inline
Implicit typecasting
Definition at line 105 of file generic_type.hpp.
 { return to_int_vector();}
casadi::GenericType::operator std::vector< std::string > () const inline
Implicit typecasting
Definition at line 108 of file generic_type.hpp.
 { return to_string_vector();}
casadi::GenericType::operator std::vector< std::vector< int > > () const inline
Implicit typecasting
Definition at line 106 of file generic_type.hpp.
 { return to_int_vector_vector();}
bool casadi::GenericType::operator!= (const GenericType & op2) const
Definition at line 376 of file generic_type.cpp.
References is_double(), is_double_vector(), is_int(), is_int_vector(), is_int_vector_vector(), is_string(), to_double(), to_double_vector(), to_int(), to_int_vector(), to_int_vector_vector(), and to_string().
{
     if (is_string() && op2.is_string()) {
       return to_string().compare(op2.to_string()) != 0;
     }
     if (is_int() && op2.is_int()) {
       return to_int() != op2.to_int();
     }
     if (is_double() && op2.is_double()) {
       return to_double() != op2.to_double();
     }
     if (is_double_vector() && op2.is_double_vector()) {
       const vector<double> &v1 = to_double_vector();
       const vector<double> &v2 = op2.to_double_vector();
       if (v1.size() != v2.size()) return true;
       for (int i=0; i<v1.size(); ++i)
         if (v1[i] != v2[i]) return true;
       return false;
     }
     if (is_int_vector() && op2.is_int_vector()) {
       const vector<int> &v1 = to_int_vector();
       const vector<int> &v2 = op2.to_int_vector();
       if (v1.size() != v2.size()) return true;
       for (int i=0; i<v1.size(); ++i)
         if (v1[i] != v2[i]) return true;
       return false;
     }
     if (is_int_vector_vector() && op2.is_int_vector_vector()) {
       const vector< vector<int> > &v1 = to_int_vector_vector();
       const vector< vector<int> > &v2 = op2.to_int_vector_vector();
       if (v1.size() != v2.size()) return true;
       for (int i=0; i<v1.size(); ++i) {
         if (v1[i].size() != v2[i].size()) return true;
         for (int j=0; j<v1[i].size(); ++j) {
           if (v1[i][j] != v2[i][j]) return true;
         }
       }
       return false;
     }
     // Different types
     return true;
   }
SharedObjectNode * casadi::SharedObject::operator-> () const inherited
Definition at line 99 of file shared_object.cpp.
{
     casadi_assert(!is_null());
     return node;
   }
bool casadi::GenericType::operator== (const GenericType & op2) const
Definition at line 372 of file generic_type.cpp.
{
     return !(*this != op2);
   }
void casadi::SharedObject::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 135 of file shared_object.cpp.
Referenced by casadi::CsparseInterface::linsol_factorize().
{
     if (is_null()) {
       stream << "Null pointer of class \"" << typeid(this).name() << "\"";
     } else {
       (*this)->print(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::SharedObject::printPtr (std::ostream & stream = casadi::userOut()) const inherited
Print the pointer to the internal class
Definition at line 144 of file shared_object.cpp.
{
     stream << node;
   }
void casadi::SharedObject::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 121 of file shared_object.cpp.
{
     if (is_null()) {
       stream << 0;
     } else {
       (*this)->repr(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 153 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
bool casadi::GenericType::to_bool () const
Definition at line 285 of file generic_type.cpp.
{
     if (is_bool()) {
       return as_bool();
     } else if (is_int()) {
       return static_cast<bool>(to_int());
     } else {
       casadi_assert_message(is_bool(), "type mismatch");
       return false;
     }
   }
vector< bool > casadi::GenericType::to_bool_vector () const
Definition at line 326 of file generic_type.cpp.
{
     casadi_assert_message(is_int_vector(), "type mismatch");
     vector<int> v = to_int_vector();
     vector<bool> ret(v.size());
     for (int i=0; i<v.size(); ++i) {
       casadi_assert_message(v[i]==0 || v[i]==1, "Entries must be zero or one");
       ret[i] = v[i]==1;
     }
     return ret;
   }
Dict casadi::GenericType::to_dict () const
Definition at line 362 of file generic_type.cpp.
{
     casadi_assert_message(is_dict(), "type mismatch");
     return as_dict();
   }
double casadi::GenericType::to_double () const
Definition at line 307 of file generic_type.cpp.
Referenced by operator!=().
{
     if (is_int()) {
       return static_cast<double>(to_int());
     } else {
       casadi_assert_message(is_double(), "type mismatch");
       return as_double();
     }
   }
vector< double > casadi::GenericType::to_double_vector () const
Definition at line 342 of file generic_type.cpp.
Referenced by operator!=().
{
     if (is_int_vector()) {
       auto v = as_int_vector();
       return vector<double>(v.begin(), v.end());
     } else {
       casadi_assert_message(is_double_vector(), "type mismatch");
       return as_double_vector();
     }
   }
Function casadi::GenericType::to_function () const
Definition at line 367 of file generic_type.cpp.
{
     casadi_assert_message(is_function(), "type mismatch");
     return as_function();
   }
int casadi::GenericType::to_int () const
Definition at line 296 of file generic_type.cpp.
Referenced by operator!=().
{
     if (is_double()) {
       return static_cast<int>(to_double());
     } else if (is_bool()) {
       return static_cast<int>(to_bool());
     } else {
       casadi_assert_message(is_int(), "type mismatch");
       return as_int();
     }
   }
vector< int > casadi::GenericType::to_int_vector () const
Definition at line 321 of file generic_type.cpp.
Referenced by operator!=().
{
     casadi_assert_message(is_int_vector(), "type mismatch");
     return as_int_vector();
   }
vector< vector< int > > casadi::GenericType::to_int_vector_vector () const
Definition at line 337 of file generic_type.cpp.
Referenced by operator!=().
{
     casadi_assert_message(is_int_vector_vector(), "type mismatch");
     return as_int_vector_vector();
   }
string casadi::GenericType::to_string () const
Definition at line 316 of file generic_type.cpp.
Referenced by operator!=().
{
     casadi_assert_message(is_string(), "type mismatch");
     return as_string();
   }
vector< string > casadi::GenericType::to_string_vector () const
Definition at line 352 of file generic_type.cpp.
{
     if (is_string()) {
       std::string s = as_string();
       return vector<string>(1, s);
     } else {
       casadi_assert_message(is_string_vector(), "type mismatch");
       return as_string_vector();
     }
   }
void * casadi::GenericType::to_void_pointer () const
Definition at line 428 of file generic_type.cpp.
References casadi::OT_VOIDPTR.
{
     casadi_assert_message(getType()==OT_VOIDPTR, "type mismatch");
     return as_void_pointer();
   }
WeakRef * casadi::SharedObject::weak () inherited
Definition at line 167 of file shared_object.cpp.
References casadi::SharedObjectNode::weak().
Referenced by casadi::WeakRef::WeakRef().
{
     return (*this)->weak();
   }
Friends And Related Function Documentation
CASADI_EXPORT friend std::ostream& operator<< (std::ostream & stream, const GenericType & ref) friend
The documentation for this class was generated from the following files:
generic_type.hpp
generic_type.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge