CasADi: casadi::SparsityInternal Class Reference
casadi::SparsityInternal Class Reference
#include <sparsity_internal.hpp>
Detailed Description
Definition at line 34 of file sparsity_internal.hpp.
Public Member Functions
SparsityInternal (int nrow, int ncol, const int *colind, const int *row)
Construct a sparsity pattern from arrays.
const std::vector< int > & sp () const
Get number of rows (see public class)
int size1 () const
Get number of rows (see public class)
int size2 () const
Get number of columns (see public class)
const int * colind () const
Get column offsets (see public class)
const int * row () const
Get row indices (see public class)
int nnz () const
Number of structural non-zeros.
void sanity_check (bool complete=false) const
Check if the dimensions and colind, row vectors are compatible.
Sparsity get_diag (std::vector< int > &mapping) const
Get the diagonal of the matrix/create a diagonal matrix.
std::vector< int > etree (bool ata) const
Calculate the elimination tree: See cs_etree in CSparse.
int dfs (int j, int top, std::vector< int > &xi, std::vector< int > &pstack, const std::vector< int > &pinv, std::vector< bool > &marked) const
Find strongly connected components: See cs_dfs in CSparse.
int scc (std::vector< int > &p, std::vector< int > &r) const
Find the strongly connected components of a square matrix: See cs_scc in CSparse.
Sparsity T () const
Transpose the matrix.
Sparsity transpose (std::vector< int > &mapping, bool invert_mapping=false) const
Transpose the matrix and get the reordering of the non-zero entries,.
bool is_transpose (const SparsityInternal &y) const
Check if the sparsity is the transpose of another.
bool isReshape (const SparsityInternal &y) const
Check if the sparsity is a reshape of another.
void breadthFirstSearch (int n, std::vector< int > &wi, std::vector< int > &wj, std::vector< int > &queue, const std::vector< int > &imatch, const std::vector< int > &jmatch, int mark) const
Breadth-first search for coarse decomposition: see cs_bfs in CSparse.
int btf (std::vector< int > &rowperm, std::vector< int > &colperm, std::vector< int > &rowblock, std::vector< int > &colblock, std::vector< int > &coarse_rowblock, std::vector< int > &coarse_colblock, int seed) const
Compute the Dulmage-Mendelsohn decomposition : see cs_dmperm in CSparse.
int btfUpper (std::vector< int > &rowperm, std::vector< int > &colperm, std::vector< int > &rowblock, std::vector< int > &colblock, std::vector< int > &coarse_rowblock, std::vector< int > &coarse_colblock, int seed) const
Compute the Dulmage-Mendelsohn decomposition.
void maxTransversal (std::vector< int > &imatch, std::vector< int > &jmatch, Sparsity &trans, int seed) const
Compute the maximum transversal (maximum matching): see cs_maxtrans in CSparse.
void augmentingPath (int k, std::vector< int > &jmatch, int *cheap, std::vector< int > &w, int *js, int *is, int *ps) const
Find an augmenting path: see cs_augment in CSparse.
Sparsity permute (const std::vector< int > &pinv, const std::vector< int > &q, int values) const
C = A(p, q) where p and q are permutations of 0..m-1 and 0..n-1.: see cs_permute in CSparse.
void permute (const std::vector< int > &pinv, const std::vector< int > &q, int values, std::vector< int > &colind_C, std::vector< int > &row_C) const
C = A(p, q) where p and q are permutations of 0..m-1 and 0..n-1.: see cs_permute in CSparse.
int vcount (std::vector< int > &pinv, std::vector< int > &parent, std::vector< int > &leftmost, int &S_m2, double &S_lnz) const
void init_ata (const int *post, int *w, int **head, int **next) const
row counts of LL'=A or LL'=A'A, given parent & post ordering: see init_ata in CSparse
std::vector< int > counts (const int *parent, const int *post, int ata) const
Row counts: See cs_counts in CSparse.
std::vector< int > amd (int order) const
void prefactorize (int order, int qr, std::vector< int > &pinv, std::vector< int > &q, std::vector< int > &parent, std::vector< int > &cp, std::vector< int > &leftmost, int &m2, double &lnz, double &unz) const
symbolic ordering and analysis for QR or LU: See cs_sqr in CSparse
Sparsity multiply (const Sparsity &B) const
C = A*B: See cs_multiply in CSparse.
int scatter (int j, std::vector< int > &w, int mark, int *Ci, int nz) const
std::vector< int > get_row () const
Get row() as a vector.
std::vector< int > get_colind () const
Get colind() as a vector.
std::vector< int > get_col () const
Get the column for each nonzero.
Sparsity _resize (int nrow, int ncol) const
Resize.
Sparsity _reshape (int nrow, int ncol) const
Reshape a sparsity, order of nonzeros remains the same.
int numel () const
Number of elements.
int nnz_lower (bool strictly=false) const
Number of non-zeros in the lower triangular half.
int nnz_upper (bool strictly=false) const
Number of non-zeros in the upper triangular half.
int nnz_diag () const
Number of non-zeros on the diagonal.
int bw_upper () const
Upper half-bandwidth.
int bw_lower () const
Lower half-bandwidth.
std::pair< int, int > size () const
Shape.
bool is_scalar (bool scalar_and_dense) const
Is scalar?
bool is_empty (bool both=false) const
Check if the sparsity is empty.
bool is_dense () const
Is dense?
bool is_row () const
Check if the pattern is a row vector (i.e. size1()==1)
bool is_column () const
Check if the pattern is a column vector (i.e. size2()==1)
bool is_vector () const
Check if the pattern is a row or column vector.
bool is_diag () const
Is diagonal?
bool is_square () const
Is square?
bool is_symmetric () const
Is symmetric?
bool is_tril () const
Is lower triangular?
bool is_triu () const
is upper triangular?
Sparsity _triu (bool includeDiagonal) const
Get upper triangular part.
Sparsity _tril (bool includeDiagonal) const
Get lower triangular part.
std::vector< int > get_lower () const
Get nonzeros in lower triangular part.
std::vector< int > get_upper () const
Get nonzeros in upper triangular part.
std::string dim () const
Get the dimension as a string.
Sparsity _mtimes (const Sparsity &y) const
Sparsity pattern for a matrix-matrix product (details in public class)
Sparsity pattern_inverse () const
Take the inverse of a sparsity pattern; flip zeros and non-zeros.
bool is_equal (const Sparsity &y) const
Check if two sparsity patterns are the same.
bool is_equal (int y_nrow, int y_ncol, const std::vector< int > &y_colind, const std::vector< int > &y_row) const
Check if two sparsity patterns are the same.
bool is_equal (int y_nrow, int y_ncol, const int *y_colind, const int *y_row) const
Check if two sparsity patterns are the same.
Sparsity _enlargeRows (int nrow, const std::vector< int > &rr, bool ind1) const
Enlarge the matrix along the first dimension (i.e. insert rows)
Sparsity _enlargeColumns (int ncol, const std::vector< int > &cc, bool ind1) const
Enlarge the matrix along the second dimension (i.e. insert columns)
Sparsity makeDense (std::vector< int > &mapping) const
Make a patten dense.
Sparsity _erase (const std::vector< int > &rr, const std::vector< int > &cc, bool ind1, std::vector< int > &mapping) const
Erase rows and/or columns - does bounds checking.
Sparsity _erase (const std::vector< int > &rr, bool ind1, std::vector< int > &mapping) const
Erase elements.
Sparsity _appendVector (const SparsityInternal &sp) const
Append another sparsity patten vertically (vectors only)
Sparsity _appendColumns (const SparsityInternal &sp) const
Append another sparsity patten horizontally.
Sparsity sub (const std::vector< int > &rr, const std::vector< int > &cc, std::vector< int > &mapping, bool ind1) const
Get a submatrix Does bounds checking rr and rr are not required to be monotonous.
Sparsity sub (const std::vector< int > &rr, const SparsityInternal &sp, std::vector< int > &mapping, bool ind1) const
Get a set of elements Does bounds checking rr is not required to be monotonous.
int get_nz (int rr, int cc) const
Get the index of an existing non-zero element.
std::vector< int > get_nz (const std::vector< int > &rr, const std::vector< int > &cc) const
Get a set of non-zero element - does bounds checking.
void get_nz (std::vector< int > &indices) const
Get the nonzero index for a set of elements (see description in public class)
bool rowsSequential (bool strictly) const
Does the rows appear sequentially on each col.
Sparsity _removeDuplicates (std::vector< int > &mapping) const
Remove duplicate entries.
void find (std::vector< int > &loc, bool ind1) const
Get element index for each nonzero.
std::size_t hash () const
Hash the sparsity pattern.
virtual void repr (std::ostream &stream) const
Print representation.
virtual void print (std::ostream &stream) const
Print description.
Sparsity uni_coloring (const Sparsity &AT, int cutoff) const
Perform a unidirectional coloring.
Sparsity star_coloring (int ordering, int cutoff) const
A greedy distance-2 coloring algorithm See description in public class.
Sparsity star_coloring2 (int ordering, int cutoff) const
An improved distance-2 coloring algorithm See description in public class.
std::vector< int > largest_first () const
Order the columns by decreasing degree.
Sparsity pmult (const std::vector< int > &p, bool permute_rows=true, bool permute_cols=true, bool invert_permutation=false) const
Permute rows and/or columns.
void spy (std::ostream &stream) const
Print a textual representation of sparsity.
void print_compact (std::ostream &stream) const
Print a compact description of the sparsity pattern.
void spy_matlab (const std::string &mfile) const
Generate a script for Matlab or Octave which visualizes the sparsity using the spy command.
template<bool with_mapping, bool f0x_is_zero, bool function0_is_zero>
Sparsity combineGen (const Sparsity &y, vector< unsigned char > &mapping) const
int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
Sparsity combine (const Sparsity &y, bool f0x_is_zero, bool function0_is_zero, std::vector< unsigned char > &mapping) const
Sparsity combine (const Sparsity &y, bool f0x_is_zero, bool function0_is_zero) const
template<bool with_mapping>
Sparsity combineGen1 (const Sparsity &y, bool f0x_is_zero, bool function0_is_zero, std::vector< unsigned char > &mapping) const
template<bool with_mapping, bool f0x_is_zero, bool function0_is_zero>
Sparsity combineGen (const Sparsity &y, std::vector< unsigned char > &mapping) const
Static Public Member Functions
static void matched (int n, const std::vector< int > &wj, const std::vector< int > &imatch, std::vector< int > &p, std::vector< int > &q, std::vector< int > &cc, std::vector< int > &rr, int set, int mark)
Collect matched cols and rows into p and q: see cs_matched in CSparse.
static void unmatched (int m, const std::vector< int > &wi, std::vector< int > &p, std::vector< int > &rr, int set)
Collect unmatched cols into the permutation vector p : see cs_unmatched in CSparse.
static int rprune (int i, int j, double aij, void *other)
return 1 if col i is in R2 : see cs_rprune in CSparse
static int drop (int(*fkeep)(int, int, double, void *), void *other, int nrow, int ncol, std::vector< int > &colind, std::vector< int > &row)
drop entries for which fkeep(A(i, j)) is false; return nz if OK, else -1: : see cs_fkeep in CSparse
static std::vector< int > randomPermutation (int n, int seed)
static std::vector< int > invertPermutation (const std::vector< int > &p)
Invert a permutation matrix: see cs_pinv in CSparse.
static int leaf (int i, int j, const int *first, int *maxfirst, int *prevleaf, int *ancestor, int *jleaf)
consider A(i, j), node j in ith col subtree and return lca(jprev, j): See cs_leaf in CSparse
static std::vector< int > postorder (const std::vector< int > &parent, int n)
post order a forest: See cs_post in CSparse
static int dfs_postorder (int j, int k, int *head, const int *next, int *post, int *stack)
Depth-first search and postorder of a tree rooted at node j: See cs_tdfs in CSparse.
static int wclear (int mark, int lemax, int *w, int n)
clear w: cs_wclear in CSparse
static int diag (int i, int j, double aij, void *other)
keep off-diagonal entries; drop diagonal entries: See cs_diag in CSparse
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Constructor & Destructor Documentation
casadi::SparsityInternal::SparsityInternal (int nrow, int ncol, const int * colind, const int * row) inline
Definition at line 46 of file sparsity_internal.hpp.
                                                                             :
       sp_(2 + ncol+1 + colind[ncol]) {
       sp_[0] = nrow;
       sp_[1] = ncol;
       std::copy(colind, colind+ncol+1, sp_.begin()+2);
       std::copy(row, row+colind[ncol], sp_.begin()+2+ncol+1);
       sanity_check(false);
     }
Member Function Documentation
Sparsity casadi::SparsityInternal::_appendColumns (const SparsityInternal & sp) const
Definition at line 2705 of file sparsity_internal.cpp.
References colind(), nnz(), row(), size1(), and size2().
Referenced by casadi::Sparsity::appendColumns().
{
     casadi_assert_message(size1()== sp.size1(),
       "SparsityInternal::_appendColumns(sp): row sizes must match but got " << size1()
                           << " for lhs, and " << sp.size1() << " for rhs.");
     // Append rows
     vector<int> new_row = get_row();
     const int* sp_row = sp.row();
     new_row.insert(new_row.end(), sp_row, sp_row+sp.nnz());
     // Get column indices
     vector<int> new_colind = get_colind();
     const int* sp_colind = sp.colind();
     new_colind.resize(size2() + sp.size2() + 1);
     for (int i = size2()+1; i<new_colind.size(); ++i)
       new_colind[i] = sp_colind[i-size2()] + nnz();
     return Sparsity(size1(), size2()+sp.size2(), new_colind, new_row);
   }
Sparsity casadi::SparsityInternal::_appendVector (const SparsityInternal & sp) const
Definition at line 2684 of file sparsity_internal.cpp.
References nnz(), row(), size1(), and size2().
Referenced by casadi::Sparsity::append().
{
     casadi_assert_message(size2() == 1 && sp.size2() == 1,
       "SparsityInternal::_appendVector(sp): Both arguments must be vectors but got "
        << size2() << " columns for lhs, and " << sp.size2() << " columns for rhs.");
     // Get current number of non-zeros
     int sz = nnz();
     // Add row indices
     vector<int> new_row = get_row();
     const int* sp_row = sp.row();
     new_row.resize(sz + sp.nnz());
     for (int i=sz; i<new_row.size(); ++i)
       new_row[i] = sp_row[i-sz] + size1();
     // New column indices
     vector<int> new_colind(2, 0);
     new_colind[1] = new_row.size();
     return Sparsity(size1()+sp.size1(), 1, new_colind, new_row);
   }
Sparsity casadi::SparsityInternal::_enlargeColumns (int ncol, const std::vector< int > & cc, bool ind1) const
Definition at line 2725 of file sparsity_internal.cpp.
References casadi::hasNegative(), and casadi::inBounds().
{
     if (!inBounds(cc, -ncol+ind1, ncol+ind1)) {
       casadi_error("enlargeColumns: out of bounds. Your cc contains "
                    << *std::min_element(cc.begin(), cc.end()) << " up to "
                    << *std::max_element(cc.begin(), cc.end())
                    << ", which is outside the range [" << -ncol+ind1 << ","<< ncol+ind1 <<  ").");
     }
     // Handle index-1, negative indices
     if (ind1 || hasNegative(cc)) {
       std::vector<int> cc_mod = cc;
       for (vector<int>::iterator i=cc_mod.begin(); i!=cc_mod.end(); ++i) {
         if (ind1) (*i)--;
         if (*i<0) *i += ncol;
       }
       return _enlargeColumns(ncol, cc_mod, false); // Call recursively
     }
     // Sparsify the columns
     vector<int> new_colind = get_colind();
     new_colind.resize(ncol+1, nnz());
     int ik=cc.back(); // need only to update from the last new index
     int nz=nnz(); // number of nonzeros up till this column
     for (int i=cc.size()-1; i>=0; --i) {
       // Update colindex for new columns
       for (; ik>cc[i]; --ik) {
         new_colind[ik] = nz;
       }
       // Update non-zero counter
       nz = new_colind[i];
       // Update colindex for old colums
       new_colind[cc[i]] = nz;
     }
     // Append zeros to the beginning
     for (; ik>=0; --ik) {
       new_colind[ik] = 0;
     }
     return Sparsity(size1(), ncol, new_colind, get_row());
   }
Sparsity casadi::SparsityInternal::_enlargeRows (int nrow, const std::vector< int > & rr, bool ind1) const
Definition at line 2770 of file sparsity_internal.cpp.
References casadi::hasNegative(), and casadi::inBounds().
{
     if (!inBounds(rr, -nrow+ind1, nrow+ind1)) {
       casadi_error("enlargeRows: out of bounds. Your rr contains " <<
                    *std::min_element(rr.begin(), rr.end()) << " up to " <<
                    *std::max_element(rr.begin(), rr.end()) <<
                    ", which is outside the range [" << -nrow+ind1 << ","<< nrow+ind1 <<  ").");
     }
     // Handle index-1, negative indices
     if (ind1 || hasNegative(rr)) {
       std::vector<int> rr_mod = rr;
       for (vector<int>::iterator i=rr_mod.begin(); i!=rr_mod.end(); ++i) {
         if (ind1) (*i)--;
         if (*i<0) *i += nrow;
       }
       return _enlargeRows(nrow, rr_mod, false); // Call recursively
     }
     // Assert dimensions
     casadi_assert(rr.size() == size1());
     // Begin by sparsify the rows
     vector<int> new_row = get_row();
     for (int k=0; k<nnz(); ++k) {
       new_row[k] = rr[new_row[k]];
     }
     return Sparsity(nrow, size2(), get_colind(), new_row);
   }
Sparsity casadi::SparsityInternal::_erase (const std::vector< int > & rr, const std::vector< int > & cc, bool ind1, std::vector< int > & mapping) const
Referenced by casadi::Sparsity::erase().
Sparsity casadi::SparsityInternal::_erase (const std::vector< int > & rr, bool ind1, std::vector< int > & mapping) const
Sparsity casadi::SparsityInternal::_mtimes (const Sparsity & y) const
Definition at line 1898 of file sparsity_internal.cpp.
References casadi::Sparsity::colind(), casadi::Sparsity::is_dense(), casadi::Sparsity::is_diag(), casadi::Sparsity::is_empty(), casadi::Sparsity::is_scalar(), casadi::Sparsity::row(), casadi::Sparsity::size(), and casadi::Sparsity::size2().
Referenced by casadi::Sparsity::mtimes().
{
     // Dimensions of the result
     int d1 = size1();
     int d2 = y.size2();
     // Elementwise multiplication if one factor is scalar
     if (is_scalar(false)) {
       return is_dense() ? y : Sparsity(y.size());
     } else if (y.is_scalar(false)) {
       return y.is_dense() ? shared_from_this<Sparsity>() : Sparsity(size());
     }
     // Quick return if both are dense
     if (is_dense() && y.is_dense()) {
       return !is_empty() && !y.is_empty() ? Sparsity::dense(d1, d2) :
         Sparsity(d1, d2);
     }
     // Quick return if first factor is diagonal
     if (is_diag()) return y;
     // Quick return if second factor is diagonal
     if (y.is_diag()) return shared_from_this<Sparsity>();
     // Direct access to the vectors
     const int* x_row = row();
     const int* x_colind = colind();
     const int* y_row = y.row();
     const int* y_colind = y.colind();
     // Sparsity pattern of the result
     vector<int> row, col;
     // Temporary vector for avoiding duplicate nonzeros
     vector<int> tmp(d1, -1);
     // Loop over the nonzeros of y
     for (int cc=0; cc<d2; ++cc) {
       for (int kk=y_colind[cc]; kk<y_colind[cc+1]; ++kk) {
         int rr = y_row[kk];
         // Loop over corresponding columns of x
         for (int kk1=x_colind[rr]; kk1<x_colind[rr+1]; ++kk1) {
           int rr1 = x_row[kk1];
           // Add to pattern if not already encountered
           if (tmp[rr1]!=cc) {
             tmp[rr1] = cc;
             row.push_back(rr1);
             col.push_back(cc);
           }
         }
       }
     }
     // Assemble sparsity pattern and return
     return Sparsity::triplet(d1, d2, row, col);
   }
Sparsity casadi::SparsityInternal::_removeDuplicates (std::vector< int > & mapping) const
The same indices will be removed from the mapping vector, which must have the same length as the number of nonzeros
Definition at line 2926 of file sparsity_internal.cpp.
{
     casadi_assert(mapping.size()==nnz());
     // Return value (to be hashed)
     vector<int> ret_colind = get_colind(), ret_row = get_row();
     // Nonzero counter without duplicates
     int k_strict=0;
     // Loop over columns
     for (int i=0; i<size2(); ++i) {
       // Last row encountered on the col so far
       int lastrow = -1;
       // Save new col offset (cannot set it yet, since we will need the old value below)
       int new_colind = k_strict;
       // Loop over nonzeros (including duplicates)
       for (int k=ret_colind[i]; k<ret_colind[i+1]; ++k) {
         // Make sure that the rows appear sequentially
         casadi_assert_message(ret_row[k] >= lastrow, "rows are not sequential");
         // Skip if duplicate
         if (ret_row[k] == lastrow) continue;
         // update last row encounterd on the col
         lastrow = ret_row[k];
         // Update mapping
         mapping[k_strict] = mapping[k];
         // Update row index
         ret_row[k_strict] = ret_row[k];
         // Increase the strict nonzero counter
         k_strict++;
       }
       // Update col offset
       ret_colind[i] = new_colind;
     }
     // Finalize the sparsity pattern
     ret_colind[size2()] = k_strict;
     ret_row.resize(k_strict);
     mapping.resize(k_strict);
     return Sparsity(size1(), size2(), ret_colind, ret_row);
   }
Sparsity casadi::SparsityInternal::_reshape (int nrow, int ncol) const
Definition at line 2843 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::reshape().
{
     // If a dimension is negative, call recursively
     if (nrow<0 && ncol>0) {
       return _reshape(numel()/ncol, ncol);
     } else if (nrow>0 && ncol<0) {
       return _reshape(nrow, numel()/nrow);
     }
     casadi_assert_message(numel() == nrow*ncol,
                           "reshape: number of elements must remain the same. Old shape is "
                           << dim() << ". New shape is " << nrow << "x" << ncol
                           << "=" << nrow*ncol << ".");
     std::vector<int> ret_col(nnz());
     std::vector<int> ret_row(nnz());
     const int* colind = this->colind();
     const int* row = this->row();
     for (int i=0; i<size2(); ++i) {
       for (int el=colind[i]; el<colind[i+1]; ++el) {
         int j = row[el];
         // Element number
         int k_ret = j+i*size1();
         // Col and row in the new matrix
         int i_ret = k_ret/nrow;
         int j_ret = k_ret%nrow;
         ret_col[el] = i_ret;
         ret_row[el] = j_ret;
       }
     }
     return Sparsity::triplet(nrow, ncol, ret_row, ret_col);
   }
Sparsity casadi::SparsityInternal::_resize (int nrow, int ncol) const
Definition at line 2876 of file sparsity_internal.cpp.
{
     // Col and row index of the new
     vector<int> row_new, colind_new(ncol+1, 0);
     const int* colind = this->colind();
     const int* row = this->row();
     // Loop over the columns which may contain nonzeros
     int i;
     for (i=0; i<size2() && i<ncol; ++i) {
       // First nonzero element of the col
       colind_new[i] = row_new.size();
       // Record rows of the nonzeros
       for (int el=colind[i]; el<colind[i+1] && row[el]<nrow; ++el) {
         row_new.push_back(row[el]);
       }
     }
     // Save col-indices for the rest of the columns
     for (; i<ncol+1; ++i) {
       colind_new[i] = row_new.size();
     }
     return Sparsity(nrow, ncol, colind_new, row_new);
   }
Sparsity casadi::SparsityInternal::_tril (bool includeDiagonal) const
Definition at line 3817 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::tril().
{
     const int* colind = this->colind();
     const int* row = this->row();
     vector<int> ret_colind, ret_row;
     ret_colind.reserve(size2()+1);
     ret_colind.push_back(0);
     for (int cc=0; cc<size2(); ++cc) {
       for (int el=colind[cc]; el<colind[cc+1]; ++el) {
         int rr=row[el];
         if (rr>cc || (includeDiagonal && rr==cc)) {
           ret_row.push_back(rr);
         }
       }
       ret_colind.push_back(ret_row.size());
     }
     return Sparsity(size1(), size2(), ret_colind, ret_row);
   }
Sparsity casadi::SparsityInternal::_triu (bool includeDiagonal) const
Definition at line 3835 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::triu().
{
     const int* colind = this->colind();
     const int* row = this->row();
     vector<int> ret_colind, ret_row;
     ret_colind.reserve(size2()+1);
     ret_colind.push_back(0);
     for (int cc=0; cc<size2(); ++cc) {
       for (int el=colind[cc]; el<colind[cc+1]; ++el) {
         int rr=row[el];
         if (rr<cc || (includeDiagonal && rr==cc)) {
           ret_row.push_back(rr);
         }
       }
       ret_colind.push_back(ret_row.size());
     }
     return Sparsity(size1(), size2(), ret_colind, ret_row);
   }
std::vector< int > casadi::SparsityInternal::amd (int order) const
Approximate minimal degree, p = amd(A+A') if symmetric is true, or amd(A'A) otherwise. order 0:natural, 1:Chol, 2:LU, 3:QR. See cs_amd in CSparse
Definition at line 1160 of file sparsity_internal.cpp.
References casadi::Sparsity::get_colind(), casadi::Sparsity::get_row(), multiply(), casadi::Sparsity::nnz(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), and casadi::Sparsity::T().
{
     int *Cp, *Ci, *last, *len, *nv, *next, *head, *elen, *degree, *w;
     int *hhead, d, dk, dext, lemax = 0, e, elenk, eln, i, j, k, k1;
     int k2, k3, jlast, ln, nzmax, mindeg = 0, nvi, nvj, nvk, mark, wnvi;
     int ok, cnz, nel = 0, p, p1, p2, p3, p4, pj, pk, pk1, pk2, pn, q;
     unsigned int h;
     //-- Construct matrix C -----------------------------------------------
     Sparsity AT = T() ;              // compute A'
     vector<int> AT_colind = AT.get_colind();
     vector<int> AT_row = AT.get_row();
     int m = size1();
     int n = size2();
     // find dense threshold:
     int dense = std::max(16, 10 * static_cast<int>(sqrt(static_cast<double>(n))));
     dense = std::min(n-2, dense);
     Sparsity C;
     if (order == 1 && n == m) {
       // C = A+A
       C = combine(AT, false, false);
     } else if (order==2) {
       // drop dense rows from AT
       for (p2=0, j=0; j<m; ++j) {
         // row j of AT starts here
         p = AT_colind[j];
         // new row j starts here
         AT_colind[j] = p2;
         // skip dense row j
         if (AT_colind[j+1] - p > dense)
           continue ;
         for ( ; p < AT_colind[j+1] ; p++)
           AT_row[p2++] = AT_row[p];
       }
       // finalize AT
       AT_colind[m] = p2;
       // Resize row vector
       AT_row.resize(p2);
       AT = Sparsity(AT.size1(), AT.size2(), AT_colind, AT_row);
       // A2 = AT'
       Sparsity A2 = AT.T();
       // C=A'*A with no dense columns
       C = AT->multiply(A2);
     } else {
       // C=A'*A
       C = AT->multiply(shared_from_this<Sparsity>());
     }
     vector<int> C_colind = C.get_colind();
     vector<int> C_row = C.get_row();
     // Free memory
     AT = Sparsity();
     // drop diagonal entries
     drop(diag, 0, C.size1(), C.size2(), C_colind, C_row);
     Cp = &C_colind.front();
     cnz = Cp[n] ;
     // allocate result
     vector<int> P(n+1);
     // get workspace
     vector<int> W(8*(n+1));
     len = &W.front();
     nv = &W.front()  + (n+1);
     next = &W.front() + 2*(n+1);
     head = &W.front() + 3*(n+1);
     elen = &W.front() + 4*(n+1);
     degree = &W.front() + 5*(n+1);
     w= &W.front() + 6*(n+1);
     hhead = &W.front() + 7*(n+1);
     // use P as workspace for last
     last = &P.front();
     // --- Initialize quotient graph ----------------------------------------
     for (k=0; k<n; ++k)
       len[k] = Cp[k+1]-Cp[k];
     len[n] = 0;
     nzmax = C.nnz();
     Ci = &C_row.front() ;
     for (i=0; i<=n; ++i) {
       // degree list i is empty
       head[i] = -1;
       last[i] = -1;
       next[i] = -1;
       // hash list i is empty
       hhead[i] = -1;
       // node i is just one node
       nv[i] = 1;
       // node i is alive
       w[i] = 1;
       // Ek of node i is empty
       elen[i] = 0;
       // degree of node i
       degree[i] = len[i];
     }
     // clear w
     mark = wclear(0, 0, w, n);
     // n is a dead element
     elen[n] = -2;
     // n is a root of assembly tree
     Cp[n] = -1;
     // n is a dead element
     w[n] = 0;
     // --- Initialize degree lists ------------------------------------------
     for (i = 0; i<n; ++i) {
       d = degree[i];
       // node i is empty
       if (d == 0) {
         // element i is dead
         elen[i] = -2;
         nel++;
         // i is a root of assembly tree
         Cp[i] = -1;
         w[i] = 0;
       } else if (d > dense) { // node i is dense
         // absorb i into element n
         nv[i] = 0;
         // node i is dead
         elen[i] = -1;
         nel++;
         Cp[i] = CS_FLIP(n) ;
         nv[n]++ ;
       } else {
         if (head[d] != -1)
           last[head[d]] = i;
         // put node i in degree list d
         next[i] = head[d];
         head[d] = i;
       }
     }
     // while (selecting pivots) do
     while (nel < n) {
       // --- Select node of minimum approximate degree --------------------
       for (k = -1 ; mindeg < n && (k = head[mindeg]) == -1; mindeg++) {}
       if (next[k] != -1) last[next[k]] = -1 ;
       // remove k from degree list
       head[mindeg] = next[k];
       // elenk = |Ek|
       elenk = elen[k];
       // # of nodes k represents
       nvk = nv[k];
       // nv[k] nodes of A eliminated
       nel += nvk;
       // --- Garbage collection -------------------------------------------
       if (elenk > 0 && cnz + mindeg >= nzmax) {
         for (j=0; j<n; ++j) {
           // j is a live node or element
           if ((p = Cp[j]) >= 0) {
             // save first entry of object
             Cp[j] = Ci[p];
             // first entry is now CS_FLIP(j)
             Ci[p] = CS_FLIP(j);
           }
         }
         // scan all of memory
         for (q = 0, p = 0 ; p < cnz ;) {
           // found object j
           if ((j = CS_FLIP(Ci[p++])) >= 0) {
             // restore first entry of object
             Ci[q] = Cp[j];
             // new pointer to object j
             Cp[j] = q++;
             for (k3 = 0 ; k3 < len[j]-1 ; k3++)
               Ci[q++] = Ci[p++] ;
           }
         }
         // Ci[cnz...nzmax-1] now free
         cnz = q;
       }
       // --- Construct new element ----------------------------------------
       dk = 0 ;
       // flag k as in Lk
       nv[k] = -nvk;
       p = Cp[k] ;
       // do in place if elen[k] == 0
       pk1 = (elenk == 0) ? p : cnz;
       pk2 = pk1 ;
       for (k1 = 1 ; k1 <= elenk + 1 ; k1++) {
         if (k1 > elenk) {
           // search the nodes in k
           e = k;
           // list of nodes starts at Ci[pj]
           pj = p;
           // length of list of nodes in k
           ln = len[k] - elenk;
         } else {
           // search the nodes in e
           e = Ci[p++];
           pj = Cp[e] ;
           // length of list of nodes in e
           ln = len[e];
         }
         for (k2=1; k2<=ln ; ++k2) {
           i = Ci[pj++] ;
           // node i dead, or seen
           if ((nvi = nv[i]) <= 0) continue;
           // degree[Lk] += size of node i
           dk += nvi;
           // negate nv[i] to denote i in Lk
           nv[i] = -nvi;
           // place i in Lk
           Ci[pk2++] = i;
           if (next[i] != -1)
             last[next[i]] = last[i];
           // remove i from degree list
           if (last[i] != -1) {
             next[last[i]] = next[i] ;
           } else {
             head[degree[i]] = next[i] ;
           }
         }
         if (e != k) {
           // absorb e into k
           Cp[e] = CS_FLIP(k);
           // e is now a dead element
           w[e] = 0;
         }
       }
       // Ci[cnz...nzmax] is free
       if (elenk != 0)
         cnz = pk2;
       // external degree of k - |Lk\i|
       degree[k] = dk;
       // element k is in Ci[pk1..pk2-1]
       Cp[k] = pk1;
       len[k] = pk2 - pk1 ;
       // k is now an element
       elen[k] = -2;
       // --- Find set differences -----------------------------------------
       // clear w if necessary
       mark = wclear(mark, lemax, w, n);
       // scan 1: find |Le\Lk|
       for (pk = pk1 ; pk < pk2 ; ++pk) {
         i = Ci[pk] ;
         // skip if elen[i] empty
         if ((eln = elen[i]) <= 0)
           continue;
         // nv[i] was negated
         nvi = -nv[i];
         wnvi = mark - nvi ;
         // scan Ei
         for (p = Cp[i] ; p <= Cp[i] + eln - 1 ; ++p) {
           e = Ci[p];
           if (w[e] >= mark) {
             // decrement |Le\Lk|
             w[e] -= nvi;
           } else if (w[e] != 0) {        /* ensure e is a live element */
             w[e] = degree[e] + wnvi ; /* 1st time e seen in scan 1 */
           }
         }
       }
       // --- Degree update ------------------------------------------------
       // scan2: degree update
       for (pk = pk1 ; pk < pk2 ; ++pk) {
         // consider node i in Lk
         i = Ci[pk];
         p1 = Cp[i] ;
         p2 = p1 + elen[i] - 1 ;
         pn = p1 ;
         // scan Ei
         for (h = 0, d = 0, p = p1 ; p <= p2 ; p++) {
           e = Ci[p] ;
           // e is an unabsorbed element
           if (w[e] != 0) {
             // dext = |Le\Lk|
             dext = w[e] - mark;
             if (dext > 0) {
               // sum up the set differences
               d += dext;
               // keep e in Ei
               Ci[pn++] = e;
               // compute the hash of node i
               h += e;
             } else {
               // aggressive absorb. e->k
               Cp[e] = CS_FLIP(k);
               // e is a dead element
               w[e] = 0;
             }
           }
         }
         // elen[i] = |Ei|
         elen[i] = pn - p1 + 1;
         p3 = pn ;
         p4 = p1 + len[i] ;
         // prune edges in Ai
         for (p = p2 + 1 ; p < p4 ; p++) {
           j = Ci[p] ;
           // node j dead or in Lk
           if ((nvj = nv[j]) <= 0)
             continue;
           // degree(i) += |j|
           d += nvj;
           // place j in node list of i
           Ci[pn++] = j;
           // compute hash for node i
           h += j;
         }
         // check for mass elimination
         if (d == 0) {
           // absorb i into k
           Cp[i] = CS_FLIP(k);
           nvi = -nv[i];
           // |Lk| -= |i|
           dk -= nvi;
           // |k| += nv[i]
           nvk += nvi;
           nel += nvi;
           nv[i] = 0 ;
           // node i is dead
           elen[i] = -1;
         } else {
           // update degree(i)
           degree[i] = std::min(degree[i], d);
           // move first node to end
           Ci[pn] = Ci[p3];
           // move 1st el. to end of Ei
           Ci[p3] = Ci[p1];
           // add k as 1st element in of Ei
           Ci[p1] = k;
           // new len of adj. list of node i
           len[i] = pn - p1 + 1;
           // finalize hash of i
           h %= n;
           // place i in hash bucket
           next[i] = hhead[h];
           hhead[h] = i ;
           // save hash of i in last[i]
           last[i] = h;
         }
       } // scan2 is done
       // finalize |Lk|
       degree[k] = dk;
       lemax = std::max(lemax, dk);
       // clear w
       mark = wclear(mark+lemax, lemax, w, n);
       // --- Supernode detection ------------------------------------------
       for (pk = pk1 ; pk < pk2 ; pk++) {
         i = Ci[pk] ;
         // skip if i is dead
         if (nv[i] >= 0)
           continue;
         // scan hash bucket of node i
         h = last[i];
         i = hhead[h];
         // hash bucket will be empty
         hhead[h] = -1;
         for ( ; i != -1 && next[i] != -1 ; i = next[i], mark++) {
           ln = len[i] ;
           eln = elen[i] ;
           for (p = Cp[i]+1 ; p <= Cp[i] + ln-1 ; p++)
             w[Ci[p]] = mark;
           jlast = i;
           // compare i with all j
           for (j = next[i] ; j != -1 ;) {
             ok = (len[j] == ln) && (elen[j] == eln) ;
             for (p = Cp[j] + 1 ; ok && p <= Cp[j] + ln - 1 ; p++) {
               if (w[Ci[p]] != mark) ok = 0 ;    /* compare i and j*/
             }
             // i and j are identical
             if (ok) {
               // absorb j into i
               Cp[j] = CS_FLIP(i);
               nv[i] += nv[j] ;
               nv[j] = 0;
               // node j is dead
               elen[j] = -1;
               // delete j from hash bucket
               j = next[j];
               next[jlast] = j ;
             } else {
               // j and i are different
               jlast = j;
               j = next[j] ;
             }
           }
         }
       }
       //  --- Finalize new element------------------------------------------
       // finalize Lk
       for (p = pk1, pk = pk1 ; pk < pk2 ; pk++) {
         i = Ci[pk] ;
         // skip if i is dead
         if ((nvi = -nv[i]) <= 0)
           continue;
         // restore nv[i]
         nv[i] = nvi;
         // compute external degree(i)
         d = degree[i] + dk - nvi ;
         d = std::min(d, n - nel - nvi);
         if (head[d] != -1)
           last[head[d]] = i;
         // put i back in degree list
         next[i] = head[d];
         last[i] = -1 ;
         head[d] = i ;
         // find new minimum degree
         mindeg = std::min(mindeg, d);
         degree[i] = d ;
         // place i in Lk
         Ci[p++] = i;
       }
       // # nodes absorbed into k
       nv[k] = nvk;
       // length of adj list of element k
       if ((len[k] = p-pk1) == 0) {
         // k is a root of the tree
         Cp[k] = -1;
         // k is now a dead element
         w[k] = 0;
       }
       // free unused space in Lk
       if (elenk != 0)
         cnz = p;
     }
     // --- Postordering -----------------------------------------------------
     // fix assembly tree
     for (i=0; i<n; ++i)
       Cp[i] = CS_FLIP(Cp[i]);
     for (j = 0 ; j <= n ; j++)
       head[j] = -1 ;
     // place unordered nodes in lists
     for (j = n ; j >= 0 ; j--) {
       // skip if j is an element
       if (nv[j] > 0) continue;
       // place j in list of its parent
       next[j] = head[Cp[j]];
       head[Cp[j]] = j;
     }
     // place elements in lists
     for (e = n ; e >= 0 ; e--) {
       // skip unless e is an element
       if (nv[e] <= 0) continue;
       if (Cp[e] != -1) {
         // place e in list of its parent
         next[e] = head[Cp[e]];
         head[Cp[e]] = e ;
       }
     }
     // postorder the assembly tree
     for (k = 0, i = 0 ; i <= n ; i++) {
       if (Cp[i] == -1)
         k = dfs_postorder(i, k, head, next, &P.front(), w) ;
     }
     return P;
   }
void casadi::SparsityInternal::augmentingPath (int k, std::vector< int > & jmatch, int * cheap, std::vector< int > & w, int * js, int * is, int * ps) const
Definition at line 420 of file sparsity_internal.cpp.
Referenced by maxTransversal().
{
     // NOTE: This implementation has been copied from CSparse and then modified,
     // it needs cleaning up to be proper C++
     const int* colind = this->colind();
     const int* row = this->row();
     int found = 0, p, i = -1, head = 0, j ;
     // start with just node k in jstack
     js[0] = k ;
     while (head >= 0) {
       // --- Start (or continue) depth-first-search at node j -------------
       // get j from top of jstack
       j = js[head];
       // 1st time j visited for kth path
       if (w[j] != k) {
         // mark j as visited for kth path
         w[j] = k;
         for (p = cheap[j] ; p < colind[j+1] && !found; ++p) {
           i = row[p] ;            /* try a cheap assignment (i, j) */
           found = (jmatch[i] == -1) ;
         }
         // start here next time j is traversed
         cheap[j] = p;
         if (found) {
           // row j matched with col i
           is[head] = i;
           // end of augmenting path
           break;
         }
         // no cheap match: start dfs for j
         ps[head] = colind[j];
       }
       // --- Depth-first-search of neighbors of j -------------------------
       for (p = ps[head]; p<colind[j+1]; ++p) {
         // consider col i
         i = row[p];
         // skip jmatch[i] if marked
         if (w[jmatch[i]] == k) continue;
         // pause dfs of node j
         ps[head] = p + 1;
         // i will be matched with j if found
         is[head] = i;
         // start dfs at row jmatch[i]
         js[++head] = jmatch[i];
         break ;
       }
       // node j is done; pop from stack
       if (p == colind[j+1]) head--;
     } // augment the match if path found:
     if (found)
       for (p = head; p>=0; --p)
         jmatch[is[p]] = js[p];
   }
void casadi::SparsityInternal::breadthFirstSearch (int n, std::vector< int > & wi, std::vector< int > & wj, std::vector< int > & queue, const std::vector< int > & imatch, const std::vector< int > & jmatch, int mark) const
Definition at line 319 of file sparsity_internal.cpp.
References casadi::Sparsity::colind(), casadi::Sparsity::row(), and casadi::trans().
{
     // NOTE: This implementation has been copied from CSparse and then modified,
     // it needs cleaning up to be proper C++
     int head = 0, tail = 0, j, i, p, j2 ;
     // place all unmatched nodes in queue
     for (j=0; j<n; ++j) {
       // skip j if matched
       if (imatch[j] >= 0) continue;
       // j in set C0 (R0 if transpose)
       wj[j] = 0;
       // place unmatched row j in queue
       queue[tail++] = j;
     }
     // quick return if no unmatched nodes
     if (tail == 0) return;
     Sparsity trans;
     const int *C_row, *C_colind;
     if (mark == 1) {
       C_row = row();
       C_colind = colind();
     } else {
       trans = T();
       C_row = trans.row();
       C_colind = trans.colind();
     }
     // while queue is not empty
     while (head < tail) {
       // get the head of the queue
       j = queue[head++];
       for (p = C_colind[j] ; p < C_colind[j+1] ; p++) {
         i = C_row[p] ;
         // skip if i is marked
         if (wi[i] >= 0) continue;
         // i in set R1 (C3 if transpose)
         wi[i] = mark;
         // traverse alternating path to j2
         j2 = jmatch[i];
         // skip j2 if it is marked
         if (wj[j2] >= 0) continue;
         // j2 in set C1 (R3 if transpose)
         wj[j2] = mark;
         // add j2 to queue
         queue[tail++] = j2;
       }
     }
   }
int casadi::SparsityInternal::btf (std::vector< int > & rowperm, std::vector< int > & colperm, std::vector< int > & rowblock, std::vector< int > & colblock, std::vector< int > & coarse_rowblock, std::vector< int > & coarse_colblock, int seed) const inline
Definition at line 132 of file sparsity_internal.hpp.
{
       return T()->btfUpper(colperm, rowperm, colblock, rowblock,
                                                  coarse_colblock, coarse_rowblock, seed);
     }
int casadi::SparsityInternal::btfUpper (std::vector< int > & rowperm, std::vector< int > & colperm, std::vector< int > & rowblock, std::vector< int > & colblock, std::vector< int > & coarse_rowblock, std::vector< int > & coarse_colblock, int seed) const
– upper triangular TODO: refactor and merge with the above
Definition at line 578 of file sparsity_internal.cpp.
References casadi::fill(), casadi::Sparsity::scc(), and casadi::trans().
{
     // The transpose of the expression
     Sparsity trans;
     // Part 1: Maximum matching
     // col permutation
     rowperm.resize(size1());
     // row permutation
     colperm.resize(size2());
     // size nb+1, block k is columns r[k] to r[k+1]-1 in A(p, q)
     rowblock.resize(size1()+6);
     // size nb+1, block k is rows s[k] to s[k+1]-1 in A(p, q)
     colblock.resize(size2()+6);
     // coarse col decomposition
     coarse_rowblock.resize(5);
     fill(coarse_rowblock.begin(), coarse_rowblock.end(), 0);
     // coarse row decomposition
     coarse_colblock.resize(5);
     fill(coarse_colblock.begin(), coarse_colblock.end(), 0);
     // max transversal
     vector<int> imatch, jmatch;
     maxTransversal(imatch, jmatch, trans, seed);
     // Coarse decomposition
     // use rowblock and colblock as workspace
     vector<int>& wi = rowblock;
     vector<int>& wj = colblock;
     // unmark all rows for bfs
     for (int j=0; j<size2(); ++j)
       wj[j] = -1;
     // unmark all columns for bfs
     for (int i=0; i<size1(); ++i)
       wi[i] = -1 ;
     // find C1, R1 from C0
     breadthFirstSearch(size2(), wi, wj, colperm, imatch, jmatch, 1);
     // find R3, C3 from R0
     breadthFirstSearch(size1(), wj, wi, rowperm, jmatch, imatch, 3);
     // unmatched set C0
     unmatched(size2(), wj, colperm, coarse_colblock, 0);
     // set R1 and C1
     matched(size2(), wj, imatch, rowperm, colperm, coarse_colblock, coarse_rowblock, 1, 1);
     // set R2 and C2
     matched(size2(), wj, imatch, rowperm, colperm, coarse_colblock, coarse_rowblock, 2, -1);
     // set R3 and C3
     matched(size2(), wj, imatch, rowperm, colperm, coarse_colblock, coarse_rowblock, 3, 3);
     // unmatched set R0
     unmatched(size1(), wi, rowperm, coarse_rowblock, 3);
     // --- Fine decomposition -----------------------------------------------
     // pinv=p'
     vector<int> pinv = invertPermutation(rowperm);
     // C=A(p, q) (it will hold A(R2, C2))
     std::vector<int> colind_C, row_C;
     permute(pinv, colperm, 0, colind_C, row_C);
     // delete rows C0, C1, and C3 from C
     int nc = coarse_colblock[3] - coarse_colblock[2];
     if (coarse_colblock[2] > 0) {
       for (int j = coarse_colblock[2]; j <= coarse_colblock[3]; ++j)
         colind_C[j-coarse_colblock[2]] = colind_C[j];
     }
     int ncol_C = nc;
     colind_C.resize(nc+1);
     // delete columns R0, R1, and R3 from C
     if (coarse_rowblock[2] - coarse_rowblock[1] < size1()) {
       drop(rprune, &coarse_rowblock, size1(), ncol_C, colind_C, row_C);
       int cnz = colind_C[nc];
       if (coarse_rowblock[1] > 0)
         for (int k=0; k<cnz; ++k)
           row_C[k] -= coarse_rowblock[1];
     }
     row_C.resize(colind_C.back());
     int nrow_C = nc ;
     Sparsity C(nrow_C, ncol_C, colind_C, row_C);
     // find strongly connected components of C
     vector<int> scc_p, scc_r;
     int scc_nb = C.scc(scc_p, scc_r);
     // --- Combine coarse and fine decompositions ---------------------------
     // C(ps, ps) is the permuted matrix
     vector<int> ps = scc_p;
     // kth block is rs[k]..rs[k+1]-1
     vector<int> rs = scc_r;
     // # of blocks of A(R2, C2)
     int nb1 = scc_nb;
     for (int k=0; k<nc; ++k)
       wj[k] = colperm[ps[k] + coarse_colblock[2]];
     for (int k=0; k<nc; ++k)
       colperm[k + coarse_colblock[2]] = wj[k];
     for (int k=0; k<nc; ++k)
       wi[k] = rowperm[ps[k] + coarse_rowblock[1]];
     for (int k=0; k<nc; ++k)
       rowperm[k + coarse_rowblock[1]] = wi[k];
     // create the fine block partitions
     int nb2 = 0;
     rowblock[0] = colblock[0] = 0;
     // leading coarse block A (R1, [C0 C1])
     if (coarse_colblock[2] > 0)
       nb2++ ;
     // coarse block A (R2, C2)
     for (int k=0; k<nb1; ++k) {
       // A (R2, C2) splits into nb1 fine blocks
       rowblock[nb2] = rs[k] + coarse_rowblock[1];
       colblock[nb2] = rs[k] + coarse_colblock[2] ;
       nb2++ ;
     }
     if (coarse_rowblock[2] < size1()) {
       // trailing coarse block A ([R3 R0], C3)
       rowblock[nb2] = coarse_rowblock[2];
       colblock[nb2] = coarse_colblock[3];
       nb2++ ;
     }
     rowblock[nb2] = size1();
     colblock[nb2] = size2() ;
     // Shrink rowblock and colblock
     rowblock.resize(nb2+1);
     colblock.resize(nb2+1);
     return nb2;
   }
int casadi::SparsityInternal::bw_lower () const
Definition at line 3892 of file sparsity_internal.cpp.
{
     int bw = 0;
     const int* colind = this->colind();
     const int* row = this->row();
     for (int cc=0; cc<size2(); ++cc) {
       if (colind[cc] != colind[cc+1]) { // if there are any elements of the column
         int rr = row[colind[cc+1]-1];
         bw = std::max(bw, rr-cc);
       }
     }
     return bw;
   }
int casadi::SparsityInternal::bw_upper () const
Definition at line 3879 of file sparsity_internal.cpp.
{
     int bw = 0;
     const int* colind = this->colind();
     const int* row = this->row();
     for (int cc=0; cc<size2(); ++cc) {
       if (colind[cc] != colind[cc+1]) { // if there are any elements of the column
         int rr = row[colind[cc]];
         bw = std::max(bw, cc-rr);
       }
     }
     return bw;
   }
const int* casadi::SparsityInternal::colind () const inline
Definition at line 65 of file sparsity_internal.hpp.
Referenced by _appendColumns(), is_transpose(), isReshape(), and maxTransversal().
 { return &sp_.front()+2;}
Sparsity casadi::SparsityInternal::combine (const Sparsity & y, bool f0x_is_zero, bool function0_is_zero, std::vector< unsigned char > & mapping) const
Union of two sparsity patterns
Referenced by casadi::Sparsity::combine(), casadi::Sparsity::intersect(), and casadi::Sparsity::unite().
Sparsity casadi::SparsityInternal::combine (const Sparsity & y, bool f0x_is_zero, bool function0_is_zero) const
Union of two sparsity patterns
Definition at line 2496 of file sparsity_internal.cpp.
{
     static vector<unsigned char> mapping;
     return combineGen1<false>(y, f0x_is_zero, function0_is_zero, mapping);
   }
template<bool with_mapping, bool f0x_is_zero, bool function0_is_zero> Sparsity casadi::SparsityInternal::combineGen (const Sparsity & y, std::vector< unsigned char > & mapping) const
Union of two sparsity patterns
template<bool with_mapping, bool f0x_is_zero, bool function0_is_zero> Sparsity casadi::SparsityInternal::combineGen (const Sparsity & y, vector< unsigned char > & mapping) const
Definition at line 2536 of file sparsity_internal.cpp.
References casadi::Sparsity::colind(), casadi::Sparsity::row(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
{
     // Assert dimensions
     casadi_assert_message(size2()==y.size2() && size1()==y.size1(), "Dimension mismatch");
     // Sparsity pattern of the argument
     const int* y_colind = y.colind();
     const int* y_row = y.row();
     const int* colind = this->colind();
     const int* row = this->row();
     // Sparsity pattern of the result
     vector<int> ret_colind(size2()+1, 0);
     vector<int> ret_row;
     // Clear the mapping
     if (with_mapping) mapping.clear();
     // Loop over columns of both patterns
     for (int i=0; i<size2(); ++i) {
       // Non-zero element of the two matrices
       int el1 = colind[i];
       int el2 = y_colind[i];
       // End of the non-zero elements of the col for the two matrices
       int el1_last = colind[i+1];
       int el2_last = y_colind[i+1];
       // Loop over the non-zeros of both matrices
       while (el1<el1_last || el2<el2_last) {
         // Get the rows
         int row1 = el1<el1_last ? row[el1] : size1();
         int row2 = el2<el2_last ? y_row[el2] : size1();
         // Add to the return matrix
         if (row1==row2) { //  both nonzero
           ret_row.push_back(row1);
           if (with_mapping) mapping.push_back( 1 | 2);
           el1++; el2++;
         } else if (row1<row2) { //  only first argument is nonzero
           if (!function0_is_zero) {
             ret_row.push_back(row1);
             if (with_mapping) mapping.push_back(1);
           } else {
             if (with_mapping) mapping.push_back(1 | 4);
           }
           el1++;
         } else { //  only second argument is nonzero
           if (!f0x_is_zero) {
             ret_row.push_back(row2);
             if (with_mapping) mapping.push_back(2);
           } else {
             if (with_mapping) mapping.push_back(2 | 4);
           }
           el2++;
         }
       }
       // Save the index of the last nonzero on the col
       ret_colind[i+1] = ret_row.size();
     }
     // Return cached object
     return Sparsity(size1(), size2(), ret_colind, ret_row);
   }
template<bool with_mapping> Sparsity casadi::SparsityInternal::combineGen1 (const Sparsity & y, bool f0x_is_zero, bool function0_is_zero, std::vector< unsigned char > & mapping) const
Union of two sparsity patterns
Definition at line 2509 of file sparsity_internal.cpp.
References casadi::fill(), casadi::is_equal(), casadi::Sparsity::nnz(), and casadi::Sparsity::resize().
{
     // Quick return if identical
     if (is_equal(y)) {
       if (with_mapping) {
         mapping.resize(y.nnz());
         fill(mapping.begin(), mapping.end(), 1 | 2);
       }
       return y;
     }
     if (f0x_is_zero) {
       if (function0_is_zero) {
         return combineGen<with_mapping, true, true>(y, mapping);
       } else {
         return combineGen<with_mapping, true, false>(y, mapping);
       }
     } else if (function0_is_zero) {
       return combineGen<with_mapping, false, true>(y, mapping);
     } else {
       return combineGen<with_mapping, false, false>(y, mapping);
     }
   }
std::vector< int > casadi::SparsityInternal::counts (const int * parent, const int * post, int ata) const
Definition at line 1060 of file sparsity_internal.cpp.
References casadi::Sparsity::colind(), init_ata(), and casadi::Sparsity::row().
Referenced by prefactorize().
{
     int i, j, k, n, m, J, s, p, q, jleaf=0, *maxfirst, *prevleaf, *ancestor,
         *head = 0, *next = 0, *first;
     m = size1();
     n = size2();
     s = 4*n + (ata ? (n+m+1) : 0);
     // allocate result
     vector<int> rowcount(n);
     vector<int>& delta = rowcount;
     // get workspace
     vector<int> w(s);
     // AT = A'
     Sparsity AT = T();
     ancestor = &w.front();
     maxfirst = &w.front()+n;
     prevleaf = &w.front()+2*n;
     first = &w.front()+3*n;
     // clear workspace w[0..s-1]
     for (k=0; k<s; ++k)
       w[k] = -1;
     // find first[j]
     for (k=0; k<n; ++k) {
       j = post[k];
       // delta[j]=1 if j is a leaf
       delta[j] = (first[j] == -1) ? 1 : 0;
       for (; j!=-1 && first[j] == -1; j=parent[j])
         first[j] = k;
     }
     const int* ATp = AT.colind();
     const int* ATi = AT.row();
     if (ata) AT->init_ata(post, &w.front(), &head, &next);
     // each node in its own set
     for (i=0; i<n; ++i)
       ancestor[i] = i;
     for (k=0; k<n; ++k) {
       // j is the kth node in postordered etree
       j = post[k];
       // j is not a root
       if (parent[j] != -1)
         delta[parent[j]]--;
       // J=j for LL'=A case
       for (J=HEAD(k, j); J != -1; J=NEXT(J)) {
         for (p = ATp[J]; p<ATp[J+1]; ++p) {
           i = ATi[p] ;
           q = leaf(i, j, first, maxfirst, prevleaf, ancestor, &jleaf);
           // A(i, j) is in skeleton
           if (jleaf >= 1)
             delta[j]++ ;
           // account for overlap in q
           if (jleaf == 2)
             delta[q]-- ;
         }
       }
       if (parent[j] != -1)
         ancestor[j] = parent[j] ;
     }
     // sum up delta's of each child
     for (j = 0 ; j < n ; ++j) {
       if (parent[j] != -1)
         rowcount[parent[j]] += rowcount[j] ;
     }
     // success
     return rowcount;
   }
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
int casadi::SparsityInternal::dfs (int j, int top, std::vector< int > & xi, std::vector< int > & pstack, const std::vector< int > & pinv, std::vector< bool > & marked) const
Definition at line 185 of file sparsity_internal.cpp.
{
     int head = 0;
     const int* colind = this->colind();
     const int* row = this->row();
     // initialize the recursion stack
     xi[0] = j;
     while (head >= 0) {
       // get j from the top of the recursion stack
       j = xi[head];
       int jnew = !pinv.empty() ? (pinv[j]) : j;
       if (!marked[j]) {
         // mark node j as visited
         marked[j]=true;
         pstack[head] = (jnew < 0) ? 0 : colind[jnew];
       }
       // node j done if no unvisited neighbors
       int done = 1;
       int p2 = (jnew < 0) ? 0 : colind[jnew+1];
       // examine all neighbors of j
       for (int p = pstack[head]; p< p2; ++p) {
         // consider neighbor node i
         int i = row[p];
         // skip visited node i
         if (marked[i]) continue ;
         // pause depth-first search of node j
         pstack[head] = p;
         // start dfs at node i
         xi[++head] = i;
         // node j is not done
         done = 0;
         // break, to start dfs (i)
         break;
       }
       //depth-first search at node j is done
       if (done) {
         // remove j from the recursion stack
         head--;
         // and place in the output stack
         xi[--top] = j ;
       }
     }
     return (top) ;
   }
int casadi::SparsityInternal::dfs_postorder (int j, int k, int * head, const int * next, int * post, int * stack) static
Definition at line 1006 of file sparsity_internal.cpp.
{
     int i, p, top = 0;
     // place j on the stack
     stack[0] = j;
     // while (stack is not empty)
     while (top >= 0) {
       // p = top of stack
       p = stack[top];
       // i = youngest child of p
       i = head[p];
       if (i == -1) {
         // p has no unordered children left
         top--;
         // node p is the kth postordered node
         post[k++] = p;
       } else {
         // remove i from children of p
         head[p] = next[i];
         // start dfs on child node i
         stack[++top] = i;
       }
     }
     return k;
   }
int casadi::SparsityInternal::diag (int i, int j, double aij, void * other) static
Definition at line 1154 of file sparsity_internal.cpp.
{
     return (i != j) ;
   }
std::string casadi::SparsityInternal::dim () const
Definition at line 1888 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::dim().
{
     std::stringstream ss;
     if (numel()==nnz()) {
       ss << size1() << "-by-" << size2() << " (dense)";
     } else {
       ss << size1() << "-by-" << size2() << " (" << nnz() << "/" << numel() << " nz)";
     }
     return ss.str();
   }
int casadi::SparsityInternal::drop (int(*)(int, int, double, void *) fkeep, void * other, int nrow, int ncol, std::vector< int > & colind, std::vector< int > & row) static
Definition at line 822 of file sparsity_internal.cpp.
{
     int nz = 0;
     for (int j = 0; j<ncol; ++j) {
       // get current location of row j
       int p = colind[j];
       // record new location of row j
       colind[j] = nz;
       for ( ; p < colind[j+1] ; ++p) {
         if (fkeep(row[p], j, 1, other)) {
           // keep A(i, j)
           row[nz++] = row[p] ;
         }
       }
     }
     // finalize A
     colind[ncol] = nz;
     return nz ;
   }
std::vector< int > casadi::SparsityInternal::etree (bool ata) const
Definition at line 134 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::etree(), and prefactorize().
{
     const int* colind = this->colind();
     const int* row = this->row();
     // Allocate result
     vector<int> parent(size2());
     // Allocate workspace
     vector<int> ancestor(size2());
     vector<int> prev(ata ? size1() : 0, -1);
     // Loop over columns
     for (int k=0; k<size2(); ++k) {
       // Start with no parent or ancestor
       parent[k] = -1;
       ancestor[k] = -1;
       // Loop over nonzeros
       for (int p=colind[k]; p<colind[k+1]; ++p) {
         // What is this?
         int i=ata ? (prev[row[p]]) : (row[p]);
         // Transverse from i to k
         while (i!=-1 && i<k) {
           // Next i is the ancestor of i
           int inext = ancestor[i];
           // Path compression
           ancestor[i] = k;
           // No ancestor, parent is k
           if (inext==-1)
             parent[i] = k;
           // Update i
           i=inext;
         }
         // What is this?
         if (ata) {
           prev[row[p]] = k;
         }
       }
     }
     return parent;
   }
void casadi::SparsityInternal::find (std::vector< int > & loc, bool ind1) const
Definition at line 2977 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     // Element for each nonzero
     loc.resize(nnz());
     // Loop over columns
     for (int cc=0; cc<size2(); ++cc) {
       // Loop over the nonzeros
       for (int el=colind[cc]; el<colind[cc+1]; ++el) {
         // Get row
         int rr = row[el];
         // Get the element
         loc[el] = rr+cc*size1()+ind1;
       }
     }
   }
vector< int > casadi::SparsityInternal::get_col () const
Definition at line 107 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     vector<int> col(nnz());
     for (int r=0; r<size2(); ++r) {
       for (int el = colind[r]; el < colind[r+1]; ++el) {
         col[el] = r;
       }
     }
     return col;
   }
vector< int > casadi::SparsityInternal::get_colind () const
Definition at line 3905 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     return vector<int>(colind, colind+size2()+1);
   }
Sparsity casadi::SparsityInternal::get_diag (std::vector< int > & mapping) const
Parameters
[out] mapping will contain the nonzero mapping
Definition at line 1835 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::get_diag().
{
     int nrow = this->size1();
     int ncol = this->size2();
     const int* colind = this->colind();
     const int* row = this->row();
     // Mapping
     mapping.clear();
     if (nrow==ncol) {
       // Sparsity pattern
       vector<int> ret_colind(2, 0), ret_row;
       // Loop over diagonal entries
       for (int cc=0; cc<ncol; ++cc) {
         for (int el = colind[cc]; el<colind[cc+1]; ++el) {
           if (row[el]==cc) {
             ret_row.push_back(row[el]);
             mapping.push_back(el);
           }
         }
       }
       ret_colind[1] = ret_row.size();
       // Construct sparsity pattern
       return Sparsity(ncol, 1, ret_colind, ret_row);
     } else if (nrow==1 || ncol==1) {
       // Sparsity pattern
       int ret_nrow = std::max(nrow, ncol);
       vector<int> ret_colind(ret_nrow+1, 0), ret_row;
       // Loop over all entries
       int ret_i=0;
       for (int cc=0; cc<ncol; ++cc) {
         for (int k = colind[cc]; k<colind[cc+1]; ++k) {
           int rr=row[k];
           int el=rr+nrow*cc; // Corresponding row in the return matrix
           while (ret_i<=el) ret_colind[ret_i++]=ret_row.size();
           ret_row.push_back(el);
           mapping.push_back(k);
         }
       }
       while (ret_i<=ret_nrow) ret_colind[ret_i++]=ret_row.size();
       // Construct sparsity pattern
       return Sparsity(ret_nrow, ret_nrow, ret_colind, ret_row);
     } else {
       casadi_error("diag: wrong argument shape. Expecting square matrix or vector-like, but got "
                    << dim() << " instead.");
     }
   }
std::vector< int > casadi::SparsityInternal::get_lower () const
Definition at line 3853 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::get_lower().
{
     const int* colind = this->colind();
     const int* row = this->row();
     vector<int> ret;
     for (int cc=0; cc<size2(); ++cc) {
       for (int el = colind[cc]; el<colind[cc+1]; ++el) {
         if (row[el]>=cc) {
           ret.push_back(el);
         }
       }
     }
     return ret;
   }
int casadi::SparsityInternal::get_nz (int rr, int cc) const
Definition at line 2813 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::get_nz().
{
     // If negative index, count from the back
     if (rr<0) rr += size1();
     if (cc<0) cc += size2();
     const int* colind = this->colind();
     const int* row = this->row();
     // Check consistency
     casadi_assert_message(rr>=0 && rr<size1(), "Row index " << rr
                           << " out of bounds [0, " << size1() << ")");
     casadi_assert_message(cc>=0 && cc<size2(), "Column index " << cc
                           << " out of bounds [0, " << size2() << ")");
     // Quick return if matrix is dense
     if (is_dense()) return rr+cc*size1();
     // Quick return if past the end
     if (colind[cc]==nnz() || (colind[cc+1]==nnz() && row[nnz()-1]<rr)) return -1;
     // Find sparse element
     for (int ind=colind[cc]; ind<colind[cc+1]; ++ind) {
       if (row[ind] == rr) {
         return ind;     // element exists
       } else if (row[ind] > rr) {
         break;          // break at the place where the element should be added
       }
     }
     return -1;
   }
std::vector<int> casadi::SparsityInternal::get_nz (const std::vector< int > & rr, const std::vector< int > & cc) const
void casadi::SparsityInternal::get_nz (std::vector< int > & indices) const
Definition at line 2999 of file sparsity_internal.cpp.
References casadi::fill(), and casadi::sort().
{
     // Quick return if no elements
     if (indices.empty()) return;
     const int* colind = this->colind();
     const int* row = this->row();
     // Make a sanity check
     int last=-1;
     for (vector<int>::iterator it=indices.begin(); it!=indices.end(); ++it) {
       if (*it>=0) {
         int el = *it;
         if (el<last) {
           // Sort rr in nondecreasing order, if needed
           std::vector<int> indices_sorted, mapping;
           sort(indices, indices_sorted, mapping, false);
           get_nz(indices_sorted);
           for (size_t i=0; i<indices.size(); ++i) {
             indices[mapping[i]] = indices_sorted[i];
           }
           return;
         }
         last = el;
       }
     }
     // Quick return if no elements
     if (last<0) return;
     // Iterator to input/output
     vector<int>::iterator it=indices.begin();
     while (*it<0) it++; // first non-ignored
     // Current element sought
     int el_row = *it % size1();
     int el_col = *it / size1();
     // Loop over columns
     for (int i=0; i<size2(); ++i) {
       // Loop over the nonzeros
       for (int el=colind[i]; el<colind[i+1] && el_col<=i; ++el) {
         // Get row
         int j = row[el];
         // Add leading elements not in pattern
         while (i>el_col || (i==el_col && j>el_row)) {
           // Mark as not found
           *it = -1;
           // Increase index and terminate if end of vector reached
           if (++it==indices.end()) return;
           // Next element sought
           el_row = *it % size1();
           el_col = *it / size1();
         }
         // Add elements in pattern
         while (i==el_col && j==el_row) {
           // Save element index
           *it = el;
           // Increase index and terminate if end of vector reached
           do {
             if (++it==indices.end()) return;
           } while (*it<0);
           // Next element sought
           el_row = *it % size1();
           el_col = *it / size1();
         }
       }
     }
     // Add trailing elements not in pattern
     fill(it, indices.end(), -1);
   }
vector< int > casadi::SparsityInternal::get_row () const
Definition at line 3910 of file sparsity_internal.cpp.
{
     const int* row = this->row();
     return vector<int>(row, row+nnz());
   }
std::vector< int > casadi::SparsityInternal::get_upper () const
Definition at line 3867 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     vector<int> ret;
     for (int cc=0; cc<size2(); ++cc) {
       for (int el = colind[cc]; el<colind[cc+1] && row[el]<=cc; ++el) {
         ret.push_back(el);
       }
     }
     return ret;
   }
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
std::size_t casadi::SparsityInternal::hash () const
Definition at line 3779 of file sparsity_internal.cpp.
References casadi::hash_sparsity().
{
     return hash_sparsity(size1(), size2(), colind(), row());
   }
void casadi::SparsityInternal::init_ata (const int * post, int * w, int ** head, int ** next) const
Definition at line 1038 of file sparsity_internal.cpp.
Referenced by counts().
{
     int i, k, p, m = size2(), n = size1();
     const int *ATp = colind();
     const int *ATi = row();
     *head = w+4*n, *next = w+5*n+1;
     // invert post
     for (k=0; k<n; ++k)
       w[post[k]] = k;
     for (i=0; i<m; ++i) {
       for (k=n, p=ATp[i]; p<ATp[i+1]; ++p)
         k = std::min(k, w[ATi[p]]);
       // place col i in linked list k
       (*next)[i] = (*head)[k];
       (*head)[k] = i ;
     }
   }
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
std::vector< int > casadi::SparsityInternal::invertPermutation (const std::vector< int > & p) static
Definition at line 773 of file sparsity_internal.cpp.
{
     // pinv = p', or p = pinv'
     // allocate result
     vector<int> pinv(p.size());
     // invert the permutation
     for (int k=0; k<p.size(); ++k)
       pinv[p[k]] = k;
     // return result
     return pinv;
   }
bool casadi::SparsityInternal::is_column () const
Definition at line 1969 of file sparsity_internal.cpp.
{
     return size2()==1;
   }
bool casadi::SparsityInternal::is_dense () const
Definition at line 1961 of file sparsity_internal.cpp.
{
     return nnz() == numel();
   }
bool casadi::SparsityInternal::is_diag () const
Definition at line 1981 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     // Check if matrix is square
     if (size2() != size1()) return false;
     // Check if correct number of non-zeros (one per col)
     if (nnz() != size2()) return false;
     // Check that the row indices are correct
     for (int i=0; i<nnz(); ++i) {
       if (row[i]!=i)
         return false;
     }
     // Make sure that the col indices are correct
     for (int i=0; i<size2(); ++i) {
       if (colind[i]!=i)
         return false;
     }
     // Diagonal if reached this point
     return true;
   }
bool casadi::SparsityInternal::is_empty (bool both = false) const
A sparsity is considered empty if one of the dimensions is zero (or optionally both dimensions)
Definition at line 1977 of file sparsity_internal.cpp.
{
     return both ? size2()==0 && size1()==0 : size2()==0 || size1()==0;
   }
bool casadi::SparsityInternal::is_equal (const Sparsity & y) const
Definition at line 2603 of file sparsity_internal.cpp.
References casadi::Sparsity::colind(), casadi::SharedObject::get(), casadi::is_equal(), casadi::Sparsity::row(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
Referenced by casadi::Sparsity::is_equal().
{
     // Quick true if the objects are the same
     if (this == y.get()) return true;
     // Otherwise, compare the patterns
     return is_equal(y.size1(), y.size2(), y.colind(), y.row());
   }
bool casadi::SparsityInternal::is_equal (int y_nrow, int y_ncol, const std::vector< int > & y_colind, const std::vector< int > & y_row) const
Definition at line 2653 of file sparsity_internal.cpp.
References casadi::get_ptr(), and casadi::is_equal().
{
     casadi_assert(y_colind.size()==y_ncol+1);
     casadi_assert(y_row.size()==y_colind.back());
     return is_equal(y_nrow, y_ncol, get_ptr(y_colind), get_ptr(y_row));
   }
bool casadi::SparsityInternal::is_equal (int y_nrow, int y_ncol, const int * y_colind, const int * y_row) const
Definition at line 2660 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     // Get number of nonzeros
     int nz = y_colind[y_ncol];
     // First check dimensions and number of non-zeros
     if (nnz()!=nz || size2()!=y_ncol || size1()!=y_nrow) return false;
     // Check if dense
     if (nnz()==numel()) return true;
     // Check the number of non-zeros per col
     if (!equal(colind, colind+size2()+1, y_colind)) return false;
     // Finally check the row indices
     if (!equal(row, row+nz, y_row)) return false;
     // Equal if reached this point
     return true;
   }
bool casadi::SparsityInternal::is_row () const
Definition at line 1965 of file sparsity_internal.cpp.
{
     return size1()==1;
   }
bool casadi::SparsityInternal::is_scalar (bool scalar_and_dense) const
Definition at line 1957 of file sparsity_internal.cpp.
{
     return size2()==1 && size1()==1 && (!scalar_and_dense || nnz()==1);
   }
bool casadi::SparsityInternal::is_square () const
Definition at line 2007 of file sparsity_internal.cpp.
{
     return size2() == size1();
   }
bool casadi::SparsityInternal::is_symmetric () const
Definition at line 2011 of file sparsity_internal.cpp.
{
     return is_transpose(*this);
   }
bool casadi::SparsityInternal::is_transpose (const SparsityInternal & y) const
Definition at line 3619 of file sparsity_internal.cpp.
References colind(), is_transpose(), nnz(), row(), size1(), and size2().
Referenced by is_transpose().
{
     // Assert dimensions and number of nonzeros
     if (size2()!=y.size1() || size1()!=y.size2() || nnz()!=y.nnz())
       return false;
     // Quick return if empty interior or dense
     if (nnz()==0 || is_dense())
       return true;
     // Run algorithm on the pattern with the least number of rows
     if (size1()>size2()) return y.is_transpose(*this);
     // Index counter for columns of the possible transpose
     vector<int> y_col_count(y.size2(), 0);
     const int* colind = this->colind();
     const int* row = this->row();
     const int* y_colind = y.colind();
     const int* y_row = y.row();
     // Loop over the columns
     for (int i=0; i<size2(); ++i) {
       // Loop over the nonzeros
       for (int el=colind[i]; el<colind[i+1]; ++el) {
         // Get the row
         int j=row[el];
         // Get the element of the possible transpose
         int el_y = y_colind[j] + y_col_count[j]++;
         // Quick return if element doesn't exist
         if (el_y>=y_colind[j+1]) return false;
         // Get the row of the possible transpose
         int j_y = y_row[el_y];
         // Quick return if mismatch
         if (j_y != i) return false;
       }
     }
     // Transpose if reached this point
     return true;
   }
bool casadi::SparsityInternal::is_tril () const
Definition at line 3783 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     // loop over columns
     for (int i=0; i<size2(); ++i) {
       if (colind[i] != colind[i+1]) { // if there are any elements of the column
         // check row of the top-most element of the column
         int rr = row[colind[i]];
         // not lower triangular if row>i
         if (rr<i) return false;
       }
     }
     // all columns ok
     return true;
   }
bool casadi::SparsityInternal::is_triu () const
Definition at line 3800 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     // loop over columns
     for (int i=0; i<size2(); ++i) {
       if (colind[i] != colind[i+1]) { // if there are any elements of the column
         // check row of the bottom-most element of the column
         int rr = row[colind[i+1]-1];
         // not upper triangular if row>i
         if (rr>i) return false;
       }
     }
     // all columns ok
     return true;
   }
bool casadi::SparsityInternal::is_vector () const
Definition at line 1973 of file sparsity_internal.cpp.
{
     return is_row() || is_column();
   }
bool casadi::SparsityInternal::isReshape (const SparsityInternal & y) const
Definition at line 3665 of file sparsity_internal.cpp.
References colind(), casadi::is_equal(), nnz(), numel(), row(), size1(), and size2().
{
     // Quick return if the objects are the same
     if (this==&y) return true;
     // Check if same number of entries and nonzeros
     if (numel()!=y.numel() || nnz()!=y.nnz()) return false;
     // Quick return if empty interior or dense
     if (nnz()==0 || is_dense()) return true;
     // Get Pattern
     const int* colind = this->colind();
     const int* row = this->row();
     const int* y_colind = y.colind();
     const int* y_row = y.row();
     // If same number of rows, check if patterns are identical
     if (size1()==y.size1()) return is_equal(y.size1(), y.size2(), y_colind, y_row);
     // Loop over the elements
     for (int cc=0; cc<size2(); ++cc) {
       for (int el=colind[cc]; el<colind[cc+1]; ++el) {
         int rr=row[el];
         // Get row and column of y
         int loc = rr+size1()*cc;
         int rr_y = loc % y.size1();
         int cc_y = loc / y.size1();
         // Make sure matching
         if (rr_y != y_row[el] || el<y_colind[cc_y] || el>=y_colind[cc_y+1])
           return false;
       }
     }
     // Reshape if reached this point
     return true;
   }
std::vector< int > casadi::SparsityInternal::largest_first () const
Definition at line 3529 of file sparsity_internal.cpp.
References casadi::copy().
Referenced by casadi::Sparsity::largest_first().
{
     vector<int> degree = get_colind();
     int max_degree = 0;
     for (int k=0; k<size2(); ++k) {
       degree[k] = degree[k+1]-degree[k];
       max_degree = max(max_degree, 1+degree[k]);
     }
     degree.resize(size2());
     // Vector for binary sort
     vector<int> degree_count(max_degree+1, 0);
     for (vector<int>::const_iterator it=degree.begin(); it!=degree.end(); ++it) {
       degree_count.at(*it+1)++;
     }
     // Cumsum to get the offset for each degree
     for (int d=0; d<max_degree; ++d) {
       degree_count[d+1] += degree_count[d];
     }
     // Now a bucket sort
     vector<int> ordering(size2());
     for (int k=size2()-1; k>=0; --k) {
       ordering[degree_count[degree[k]]++] = k;
     }
     // Invert the ordering
     vector<int>& reverse_ordering = degree_count; // reuse memory
     reverse_ordering.resize(ordering.size());
     copy(ordering.begin(), ordering.end(), reverse_ordering.rbegin());
     // Return the ordering
     return reverse_ordering;
   }
int casadi::SparsityInternal::leaf (int i, int j, const int * first, int * maxfirst, int * prevleaf, int * ancestor, int * jleaf) static
Definition at line 846 of file sparsity_internal.cpp.
{
     int q, s, sparent, jprev ;
     if (!first || !maxfirst || !prevleaf || !ancestor || !jleaf) return (-1) ;
     *jleaf = 0 ;
     if (i <= j || first[j] <= maxfirst[i]) return (-1) ;  /* j not a leaf */
     maxfirst[i] = first[j] ;      /* update max first[j] seen so far */
     jprev = prevleaf[i] ;          /* jprev = previous leaf of ith subtree */
     prevleaf[i] = j ;
     *jleaf = (jprev == -1) ? 1: 2 ; /* j is first or subsequent leaf */
     if (*jleaf == 1) return (i) ;   /* if 1st leaf, q = root of ith subtree */
     for (q = jprev ; q != ancestor[q] ; q = ancestor[q]) ;
     for (s = jprev ; s != q ; s = sparent) {
         sparent = ancestor[s] ;    /* path compression */
         ancestor[s] = q ;
     }
     return (q) ;                    /* q = least common ancester (jprev, j) */
   }
Sparsity casadi::SparsityInternal::makeDense (std::vector< int > & mapping) const
Definition at line 2799 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::makeDense().
{
     const int* colind = this->colind();
     const int* row = this->row();
     mapping.resize(nnz());
     for (int i=0; i<size2(); ++i) {
       for (int el=colind[i]; el<colind[i+1]; ++el) {
         int j = row[el];
         mapping[el] = j + i*size1();
       }
     }
     return Sparsity::dense(size1(), size2());
   }
void casadi::SparsityInternal::matched (int n, const std::vector< int > & wj, const std::vector< int > & imatch, std::vector< int > & p, std::vector< int > & q, std::vector< int > & cc, std::vector< int > & rr, int set, int mark) static
Definition at line 381 of file sparsity_internal.cpp.
{
     // NOTE: This implementation has been copied from CSparse and then modified,
     // it needs cleaning up to be proper C++
     int kc = cc[set];
     int kr = rr[set-1] ;
     for (int j=0; j<n; ++j) {
       // skip if j is not in C set
       if (wj[j] != mark) continue;
       p[kr++] = imatch[j] ;
       q[kc++] = j ;
     }
     cc[set+1] = kc ;
     rr[set] = kr ;
   }
void casadi::SparsityInternal::maxTransversal (std::vector< int > & imatch, std::vector< int > & jmatch, Sparsity & trans, int seed) const
Definition at line 491 of file sparsity_internal.cpp.
References augmentingPath(), colind(), casadi::SharedObject::get(), casadi::SharedObject::is_null(), size1(), and size2().
{
     // NOTE: This implementation has been copied from CSparse and then modified,
     // it needs cleaning up to be proper C++
     const int* colind = this->colind();
     const int* row = this->row();
     int n2 = 0, m2 = 0;
     // allocate result
     jmatch.resize(size1());
     imatch.resize(size2());
     vector<int> w(size1()+size2());
     // count nonempty columns and rows
     int k=0;
     for (int j=0; j<size2(); ++j) {
       n2 += (colind[j] < colind[j+1]);
       for (int p=colind[j]; p < colind[j+1]; ++p) {
         w[row[p]] = 1;
         // count entries already on diagonal
         k += (j == row[p]);
       }
     }
     // quick return if diagonal zero-free
     if (k == std::min(size1(), size2())) {
       int i;
       for (i=0; i<k; ++i) jmatch[i] = i;
       for (;    i<size1(); ++i) jmatch[i] = -1;
       int j;
       for (j=0; j<k; ++j) imatch[j] = j;
       for (;    j<size2(); ++j) imatch[j] = -1;
     }
     for (int i=0; i<size1(); ++i) m2 += w[i];
     // transpose if needed
     if (m2 < n2 && trans.is_null())
       trans = T();
     // Get pointer to sparsity
     const SparsityInternal* C = m2 < n2 ? static_cast<const SparsityInternal*>(trans.get()) : this;
     const int* C_colind = C->colind();
     std::vector<int>& Cjmatch = m2 < n2 ? imatch : jmatch;
     std::vector<int>& Cimatch = m2 < n2 ? jmatch : imatch;
     // get workspace
     w.resize(5 * C->size2());
     int *cheap = &w.front() + C->size2();
     int *js = &w.front() + 2*C->size2();
     int *is = &w.front() + 3*C->size2();
     int *ps = &w.front() + 4*C->size2();
     // for cheap assignment
     for (int j=0; j<C->size2(); ++j)
       cheap[j] = C_colind[j];
     // all rows unflagged
     for (int j=0; j<C->size2(); ++j)
       w[j] = -1;
     // nothing matched yet
     for (int i=0; i<C->size1(); ++i)
       Cjmatch[i] = -1;
     // q = random permutation
     std::vector<int> q = randomPermutation(C->size2(), seed);
     // augment, starting at row q[k]
     for (k=0; k<C->size2(); ++k) {
       C->augmentingPath(!q.empty() ? q[k]: k, Cjmatch, cheap, w, js, is, ps);
     }
     // find col match
     for (int j=0; j<C->size2(); ++j)
       Cimatch[j] = -1;
     for (int i = 0; i<C->size1(); ++i)
       if (Cjmatch[i] >= 0)
         Cimatch[Cjmatch[i]] = i;
   }
Sparsity casadi::SparsityInternal::multiply (const Sparsity & B) const
Definition at line 1747 of file sparsity_internal.cpp.
References casadi::Sparsity::colind(), casadi::Sparsity::row(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
Referenced by amd().
{
     int nz = 0;
     casadi_assert_message(size2() == B.size1(), "Dimension mismatch.");
     int m = size1();
     int anz = nnz();
     int n = B.size2();
     const int* Bp = B.colind();
     const int* Bi = B.row();
     int bnz = Bp[n];
     // get workspace
     vector<int> w(m);
     // allocate result
     vector<int> C_colind(n+1, 0), C_row;
     C_colind.resize(anz + bnz);
     int* Cp = &C_colind.front();
     for (int j=0; j<n; ++j) {
       if (nz+m > C_row.size()) {
         C_row.resize(2*(C_row.size())+m);
       }
       // row j of C starts here
       Cp[j] = nz;
       for (int p = Bp[j] ; p<Bp[j+1] ; ++p) {
         nz = scatter(Bi[p], w, j+1, &C_row.front(), nz);
       }
     }
     // finalize the last row of C
     Cp[n] = nz;
     C_row.resize(nz);
     // Success
     return Sparsity(m, n, C_colind, C_row);
   }
int casadi::SparsityInternal::nnz () const inline
Definition at line 71 of file sparsity_internal.hpp.
Referenced by _appendColumns(), _appendVector(), is_transpose(), and isReshape().
 { return colind()[size2()];}
int casadi::SparsityInternal::nnz_diag () const
Definition at line 2027 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     int nnz = 0;
     for (int cc=0; cc<size2(); ++cc) {
       for (int el = colind[cc]; el < colind[cc+1]; ++el) {
         nnz += row[el]==cc;
       }
     }
     return nnz;
   }
int casadi::SparsityInternal::nnz_lower (bool strictly = false) const
Definition at line 2015 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::nnz_lower().
{
     const int* colind = this->colind();
     const int* row = this->row();
     int nnz = 0;
     for (int cc=0; cc<size2(); ++cc) {
       for (int el = colind[cc]; el<colind[cc+1]; ++el) {
         if (cc<row[el] || (!strictly && cc==row[el])) nnz++;
       }
     }
     return nnz;
   }
int casadi::SparsityInternal::nnz_upper (bool strictly = false) const
Definition at line 2039 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     int nnz = 0;
     for (int cc=0; cc<size2(); ++cc) {
       for (int el = colind[cc]; el<colind[cc+1]; ++el) {
         if (cc>row[el] || (!strictly && cc==row[el])) nnz++;
       }
     }
     return nnz;
   }
int casadi::SparsityInternal::numel () const
Definition at line 37 of file sparsity_internal.cpp.
Referenced by isReshape().
{
     return size1()*size2();
   }
Sparsity casadi::SparsityInternal::pattern_inverse () const
Definition at line 2611 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::pattern_inverse().
{
     // Quick return clauses
     if (is_empty()) return Sparsity::dense(size1(), size2());
     if (is_dense()) return Sparsity(size1(), size2());
     // Sparsity of the result
     std::vector<int> row_ret;
     std::vector<int> colind_ret=get_colind();
     const int* colind = this->colind();
     const int* row = this->row();
     // Loop over columns
     for (int i=0;i<size2();++i) {
       // Update colind vector of the result
       colind_ret[i+1]=colind_ret[i]+size1()-(colind[i+1]-colind[i]);
       // Counter of new row indices
       int j=0;
       // Loop over all nonzeros
       for (int k=colind[i];k<colind[i+1];++k) {
         // Try to reach current nonzero
         while (j<row[k])  {
           // And meanwhile, add nonzeros to the result
           row_ret.push_back(j);
           j++;
         }
         j++;
       }
       // Process the remainder up to the row size
       while (j < size1())  {
         row_ret.push_back(j);
         j++;
       }
     }
     // Return result
     return Sparsity(size1(), size2(), colind_ret, row_ret);
   }
Sparsity casadi::SparsityInternal::permute (const std::vector< int > & pinv, const std::vector< int > & q, int values) const
Definition at line 787 of file sparsity_internal.cpp.
{
     std::vector<int> colind_C, row_C;
     permute(pinv, q, values, colind_C, row_C);
     return Sparsity(size1(), size2(), colind_C, row_C);
   }
void casadi::SparsityInternal::permute (const std::vector< int > & pinv, const std::vector< int > & q, int values, std::vector< int > & colind_C, std::vector< int > & row_C) const
Definition at line 794 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     // alloc column offsets
     colind_C.resize(size2()+1);
     // Row for each nonzero
     row_C.resize(nnz());
     int nz = 0;
     for (int k = 0; k<size2(); ++k) {
       // row k of C is row q[k] of A
       colind_C[k] = nz;
       int j = !q.empty() ? (q[k]) : k;
       for (int t = colind[j]; t<colind[j+1]; ++t) {
         row_C[nz++] = !pinv.empty() ? (pinv[row[t]]) : row[t] ;
       }
     }
     // finalize the last row of C
     colind_C[size2()] = nz;
   }
Sparsity casadi::SparsityInternal::pmult (const std::vector< int > & p, bool permute_rows = true, bool permute_cols = true, bool invert_permutation = false) const
Definition at line 3564 of file sparsity_internal.cpp.
References casadi::copy(), and casadi::Sparsity::resize().
Referenced by casadi::Sparsity::pmult().
{
     // Invert p, possibly
     vector<int> p_inv;
     if (invert_permutation) {
       p_inv.resize(p.size());
       for (int k=0; k<p.size(); ++k) {
         p_inv[p[k]] = k;
       }
     }
     const vector<int>& pp = invert_permutation ? p_inv : p;
     // Get columns
     vector<int> col = get_col();
     // Get rows
     const int* row = this->row();
     // Sparsity of the return matrix
     vector<int> new_row(col.size()), new_col(col.size());
     // Possibly permute columns
     if (permute_columns) {
       // Assert dimensions
       casadi_assert(p.size()==size2());
       // Permute
       for (int k=0; k<col.size(); ++k) {
         new_col[k] = pp[col[k]];
       }
     } else {
       // No permutation of columns
       copy(col.begin(), col.end(), new_col.begin());
     }
     // Possibly permute rows
     if (permute_rows) {
       // Assert dimensions
       casadi_assert(p.size()==size1());
       // Permute
       for (int k=0; k<nnz(); ++k) {
         new_row[k] = pp[row[k]];
       }
     } else {
       // No permutation of rows
       copy(row, row+nnz(), new_row.begin());
     }
     // Return permuted matrix
     return Sparsity::triplet(size1(), size2(), new_row, new_col);
   }
std::vector< int > casadi::SparsityInternal::postorder (const std::vector< int > & parent, int n) static
Definition at line 968 of file sparsity_internal.cpp.
{
     int j, k = 0, *head, *next, *stack ;
     // allocate result
     vector<int> post(n);
     // get workspace
     vector<int> w(3*n);
     head = &w.front() ;
     next = &w.front() + n ;
     stack = &w.front() + 2*n;
     // empty linked lists
     for (j=0; j<n; ++j)
       head[j] = -1;
     // traverse nodes in reverse order
     for (j=n-1; j>=0; --j) {
       // j is a root
       if (parent[j] == -1) continue;
       // add j to list of its parent
       next[j] = head[parent[j]];
       head[parent[j]] = j ;
     }
     for (j=0; j<n; ++j) {
       // skip j if it is not a root
       if (parent[j] != -1) continue;
       k = dfs_postorder(j, k, head, next, &post.front(), stack);
     }
     // success; return post
     return post;
   }
void casadi::SparsityInternal::prefactorize (int order, int qr, std::vector< int > & pinv, std::vector< int > & q, std::vector< int > & parent, std::vector< int > & cp, std::vector< int > & leftmost, int & m2, double & lnz, double & unz) const
Definition at line 1786 of file sparsity_internal.cpp.
References counts(), etree(), and vcount().
{
     const int* colind = this->colind();
     int k;
     int n = size2();
     vector<int> post;
     // fill-reducing ordering
     if (order!=0) {
       S_q = amd(order);
     }
     // QR symbolic analysis
     if (qr) {
       Sparsity C;
       if (order!=0) {
         std::vector<int> pinv_tmp;
         C = permute(pinv_tmp, S_q, 0);
       } else {
         C = shared_from_this<Sparsity>();
       }
       // etree of C'*C, where C=A(:, q)
       S_parent = C->etree(1);
       post = postorder(S_parent, n);
       // row counts chol(C'*C)
       S_cp = C->counts(&S_parent.front(), &post.front(), 1);
       post.clear();
       C->vcount(S_pinv, S_parent, S_leftmost, S_m2, S_lnz);
       for (S_unz = 0, k = 0; k<n; k++)
         S_unz += S_cp[k];
       // int overflow guard
       casadi_assert(S_lnz >= 0);
       casadi_assert(S_unz >= 0);
     } else {
       // for LU factorization only
       S_unz = 4*(colind[n]) + n ;
       // guess nnz(L) and nnz(U)
       S_lnz = S_unz;
     }
   }
void casadi::SparsityInternal::print (std::ostream & stream) const virtual
Reimplemented from casadi::SharedObjectNode.
Definition at line 100 of file sparsity_internal.cpp.
References casadi::repr().
{
     repr(stream);
     stream << endl;
     stream << "colind: " << get_colind() << endl;
     stream << "row:    " << get_row() << endl;
   }
void casadi::SparsityInternal::print_compact (std::ostream & stream) const
Definition at line 46 of file sparsity_internal.cpp.
{
     // Print dimensions
     stream << size1() << "x" << size2();
     // Print shape
     if (is_empty()) {
       // Print nothing, shape clear anyway
     } else if (is_dense()) {
       stream << ", dense";
     } else if (is_diag()) {
       stream << ", diagonal";
     } else {
       stream << ", " << nnz() << " nnz";
     }
   }
std::vector< int > casadi::SparsityInternal::randomPermutation (int n, int seed) static
return a random permutation vector, the identity perm, or p = n-1:-1:0. seed = -1 means p = n-1:-1:0. seed = 0 means p = identity. otherwise p = random permutation. See cs_randperm in CSparse
Definition at line 736 of file sparsity_internal.cpp.
{
     // Return object
     std::vector<int> p;
     // return p = empty (identity)
     if (seed==0) return p;
     // allocate result
     p.resize(n);
     for (int k=0; k<n; ++k)
       p[k] = n-k-1;
     // return reverse permutation
     if (seed==-1) return p;
     #if defined(_WIN32)
     srand(seed);
     #else
     unsigned int seedu = seed;
     #endif
     for (int k=0; k<n; ++k) {
       // j = rand int in range k to n-1
       #if defined(_WIN32)
       int j = k + (rand() % (n-k)); // NOLINT(runtime/threadsafe_fn)
       #else
       int j = k + (rand_r(&seedu) % (n-k));
       #endif
       // swap p[k] and p[j]
       int t = p[j];
       p[j] = p[k];
       p[k] = t;
     }
     return p;
   }
void casadi::SparsityInternal::repr (std::ostream & stream) const virtual
Reimplemented from casadi::SharedObjectNode.
Definition at line 41 of file sparsity_internal.cpp.
{
     stream << "Compressed Column Storage: ";
     print_compact(stream);
   }
const int* casadi::SparsityInternal::row () const inline
Definition at line 68 of file sparsity_internal.hpp.
Referenced by _appendColumns(), _appendVector(), is_transpose(), and isReshape().
 { return colind()+size2()+1;}
bool casadi::SparsityInternal::rowsSequential (bool strictly) const
Definition at line 2902 of file sparsity_internal.cpp.
{
     const int* colind = this->colind();
     const int* row = this->row();
     for (int i=0; i<size2(); ++i) {
       int lastrow = -1;
       for (int k=colind[i]; k<colind[i+1]; ++k) {
         // check if not in sequence
         if (row[k] < lastrow)
           return false;
         // Check if duplicate
         if (strictly && row[k] == lastrow)
           return false;
         // update last row of the col
         lastrow = row[k];
       }
     }
     // sequential if reached this point
     return true;
   }
int casadi::SparsityInternal::rprune (int i, int j, double aij, void * other) static
Definition at line 413 of file sparsity_internal.cpp.
{
     // NOTE: This implementation has been copied from CSparse and then modified,
     // it needs cleaning up to be proper C++
     vector<int> &rr = *static_cast<vector<int> *>(other);
     return (i >= rr[1] && i < rr[2]) ;
   }
void casadi::SparsityInternal::sanity_check (bool complete = false) const
Definition at line 62 of file sparsity_internal.cpp.
{
     int nrow = size1();
     int ncol = size2();
     const int* colind = this->colind();
     const int* row = this->row();
     int nnz = this->nnz();
     casadi_assert_message(nrow >=0,
                           "SparsityInternal: number of rows must be positive, but got "
                           << nrow << ".");
     casadi_assert_message(ncol>=0 ,
                           "SparsityInternal: number of columns must be positive, but got "
                           << ncol << ".");
     if (complete) {
       for (int k=0; k<ncol; k++) {
         casadi_assert_message(colind[k+1]>=colind[k],
                               "SparsityInternal:Compressed Column Storage is not sane. "
                               "colind must be monotone.");
       }
       casadi_assert_message(colind[0]==0,
                             "SparsityInternal:Compressed Column Storage is not sane. "
                             "First element of colind must be zero.");
       for (int k=0; k<nnz; k++) {
         if (row[k]>=nrow || row[k] < 0) {
           std::stringstream s;
           s << "SparsityInternal:Compressed Column Storage is not sane. The following must hold:"
             << std::endl;
           s << "  0 <= row[i] < nrow for each i, but got   row[i] = " << row[k]
             << "   and   nrow = "  << nrow << std::endl;
           casadi_error(s.str());
         }
       }
     }
   }
int casadi::SparsityInternal::scatter (int j, std::vector< int > & w, int mark, int * Ci, int nz) const
x = x + beta * A(:, j), where x is a dense vector and A(:, j) is sparse: See cs_scatter in CSparse
Definition at line 1727 of file sparsity_internal.cpp.
{
     int i, p;
     const int *Ap = colind();
     const int *Ai = row();
     for (p = Ap[j]; p<Ap[j+1]; ++p) {
       // A(i, j) is nonzero
       i = Ai[p];
       if (w[i] < mark) {
         // i is new entry in row j
         w[i] = mark;
         // add i to pattern of C(:, j)
         Ci[nz++] = i;
       }
     }
     return nz;
   }
int casadi::SparsityInternal::scc (std::vector< int > & p, std::vector< int > & r) const
Definition at line 244 of file sparsity_internal.cpp.
References casadi::Sparsity::dfs(), and casadi::fill().
{
     // NOTE: This implementation has been copied from CSparse and then modified,
     // it needs cleaning up to be proper C++
     vector<int> tmp;
     Sparsity AT = T();
     vector<int> xi(2*size2()+1);
     vector<int>& Blk = xi;
     vector<int> pstack(size2()+1);
     p.resize(size2());
     r.resize(size2()+6);
     vector<bool> marked(size2(), false);
     int top = size2();
     //first dfs(A) to find finish times (xi)
     for (int i = 0; i<size2(); ++i) {
       if (!marked[i]) {
         top = dfs(i, top, xi, pstack, tmp, marked);
       }
     }
     //restore A; unmark all nodes
     fill(marked.begin(), marked.end(), false);
     top = size2();
     int nb = size2();
     // dfs(A') to find strongly connnected comp
     for (int k=0 ; k < size2() ; ++k) {
       // get i in reverse order of finish times
       int i = xi[k];
       // skip node i if already ordered
       if (marked[i]) continue;
       // node i is the start of a component in p
       r[nb--] = top;
       top = AT.dfs(i, top, p, pstack, tmp, marked);
     }
     // first block starts at zero; shift r up
     r[nb] = 0;
     for (int k = nb ; k <= size2() ; ++k)
       r[k-nb] = r[k] ;
     // nb = # of strongly connected components
     nb = size2()-nb;
     // sort each block in natural order
     for (int b = 0 ; b < nb ; b++) {
       for (int k = r[b]; k<r[b+1] ; ++k)
         Blk[p[k]] = b ;
     }
     // Get p; shift r down (side effect)
     for (int i=0; i<size2(); ++i) {
       p[r[Blk[i]]++] = i;
     }
     // Shift up r
     r.resize(nb+1);
     for (int i=nb; i>0; --i) {
       r[i]=r[i-1];
     }
     r[0]=0;
     return nb;
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
std::pair< int, int > casadi::SparsityInternal::size () const
Definition at line 2051 of file sparsity_internal.cpp.
{
     return std::pair<int, int>(size1(), size2());
   }
int casadi::SparsityInternal::size1 () const inline
Definition at line 59 of file sparsity_internal.hpp.
Referenced by _appendColumns(), _appendVector(), casadi::Sparsity::horzcat(), is_transpose(), isReshape(), maxTransversal(), casadi::Sparsity::size1(), and casadi::Sparsity::vertcat().
 { return sp_[0];}
int casadi::SparsityInternal::size2 () const inline
Definition at line 62 of file sparsity_internal.hpp.
Referenced by _appendColumns(), _appendVector(), is_transpose(), isReshape(), and maxTransversal().
 { return sp_[1];}
const std::vector<int>& casadi::SparsityInternal::sp () const inline
Definition at line 56 of file sparsity_internal.hpp.
 { return sp_;}
void casadi::SparsityInternal::spy (std::ostream & stream) const
Definition at line 3704 of file sparsity_internal.cpp.
{
     // Index counter for each column
     std::vector<int> cind = get_colind();
     const int* colind = this->colind();
     const int* row = this->row();
     // Loop over rows
     for (int rr=0; rr<size1(); ++rr) {
       // Loop over columns
       for (int cc=0; cc<size2(); ++cc) {
         // Check if nonzero
         if (cind[cc]<colind[cc+1] && row[cind[cc]]==rr) {
           stream << "*";
           cind[cc]++;
         } else {
           stream << ".";
         }
       }
       // End of row
       stream << endl;
     }
   }
void casadi::SparsityInternal::spy_matlab (const std::string & mfile) const
Definition at line 3730 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::spy_matlab().
{
     // Create the .m file
     ofstream mfile;
     mfile.open(mfile_name.c_str());
     // Header
     mfile << "% This function was automatically generated by CasADi" << endl;
     // Print dimensions
     mfile << "n = " << size1() << ";" << endl;
     mfile << "m = " << size2() << ";" << endl;
     // Matlab indices are one-based
     const int index_offset = 1;
     // Print columns
     const int* colind = this->colind();
     const int* row = this->row();
     mfile << "i = [";
     bool first = true;
     for (int i=0; i<size2(); ++i) {
       for (int el=colind[i]; el<colind[i+1]; ++el) {
         if (!first) mfile << ", ";
         mfile << (i+index_offset);
         first = false;
       }
     }
     mfile << "];" << endl;
     // Print rows
     mfile << "j = [";
     first = true;
     int nz = nnz();
     for (int i=0; i<nz; ++i) {
       if (!first) mfile << ", ";
       mfile << (row[i]+index_offset);
       first = false;
     }
     mfile << "];" << endl;
     // Generate matrix
     mfile << "A = sparse(i, j, ones(size(i)), m, n)';" << endl;
     // Issue spy command
     mfile << "spy(A);" << endl;
     mfile.close();
   }
Sparsity casadi::SparsityInternal::star_coloring (int ordering, int cutoff) const
Definition at line 3419 of file sparsity_internal.cpp.
References casadi::Sparsity::pmult(), casadi::range(), and casadi::Sparsity::star_coloring().
Referenced by casadi::Sparsity::star_coloring().
{
     casadi_assert_warning(size2()==size1(), "StarColoring requires a square matrix, but got "
                           << dim() << ".");
     // Reorder, if necessary
     if (ordering!=0) {
       casadi_assert(ordering==1);
       // Ordering
       vector<int> ord = largest_first();
       // Create a new sparsity pattern
       Sparsity sp_permuted = pmult(ord, true, true, true);
       // Star coloring for the permuted matrix
       Sparsity ret_permuted = sp_permuted.star_coloring(0);
       // Permute result back
       return ret_permuted.pmult(ord, true, false, false);
     }
     // Allocate temporary vectors
     const int* colind = this->colind();
     const int* row = this->row();
     vector<int> forbiddenColors;
     forbiddenColors.reserve(size2());
     vector<int> color(size2(), -1);
     // 4: for i <- 1 to |V | do
     for (int i=0; i<size2(); ++i) {
       // 5: for each w \in N1 (vi) do
       for (int w_el=colind[i]; w_el<colind[i+1]; ++w_el) {
         int w = row[w_el];
         // 6: if w is colored then
         if (color[w]!=-1) {
           // 7: forbiddenColors[color[w]] <- v
           forbiddenColors[color[w]] = i;
         } // 8: end if
         // 9: for each colored vertex x \in N1 (w) do
         for (int x_el=colind[w]; x_el<colind[w+1]; ++x_el) {
           int x = row[x_el];
           if (color[x]==-1) continue;
           // 10: if w is not colored then
           if (color[w]==-1) {
             //11: forbiddenColors[color[x]] <- vi
             forbiddenColors[color[x]] = i;
           } else { // 12: else
             // 13: for each colored vertex y \in N1 (x), y != w do
             for (int y_el=colind[x]; y_el<colind[x+1]; ++y_el) {
               int y = row[y_el];
               if (color[y]==-1 || y==w) continue;
               // 14: if color[y] = color[w] then
               if (color[y]==color[w]) {
                 // 15: forbiddenColors[color[x]] <- vi
                 forbiddenColors[color[x]] = i;
                 // 16: break
                 break;
               } // 17: end if
             } // 18: end for
           } // 19: end if
         } // 20 end for
       } // 21 end for
       // 22: color[v] <- min {c > 0 : forbiddenColors[c] = v}
       bool new_color = true;
       for (int color_i=0; color_i<forbiddenColors.size(); ++color_i) {
         // Break if color is ok
         if (forbiddenColors[color_i]!=i) {
           color[i] = color_i;
           new_color = false;
           break;
         }
       }
       // New color if reached end
       if (new_color) {
         color[i] = forbiddenColors.size();
         forbiddenColors.push_back(-1);
         // Cutoff if too many colors
         if (forbiddenColors.size()>cutoff) {
           return Sparsity();
         }
       }
     } // 23 end for
     // Number of colors used
     int num_colors = forbiddenColors.size();
     // Return sparsity in sparse triplet format
     return Sparsity::triplet(size2(), num_colors, range(color.size()), color);
   }
Sparsity casadi::SparsityInternal::star_coloring2 (int ordering, int cutoff) const
Definition at line 3167 of file sparsity_internal.cpp.
References casadi::Sparsity::pmult(), and casadi::Sparsity::star_coloring2().
Referenced by casadi::Sparsity::star_coloring2().
{
     casadi_assert_warning(size2()==size1(),
                           "StarColoring requires a square matrix, but got "
                           << dim() << ".");
     // TODO(Joel): What we need here, is a distance-2 smallest last ordering
     // Reorder, if necessary
     const int* colind = this->colind();
     const int* row = this->row();
     if (ordering!=0) {
       casadi_assert(ordering==1);
       // Ordering
       vector<int> ord = largest_first();
       // Create a new sparsity pattern
       Sparsity sp_permuted = pmult(ord, true, true, true);
       // Star coloring for the permuted matrix
       Sparsity ret_permuted = sp_permuted.star_coloring2(0);
       // Permute result back
       return ret_permuted.pmult(ord, true, false, false);
     }
     // Allocate temporary vectors
     vector<int> forbiddenColors;
     forbiddenColors.reserve(size2());
     vector<int> color(size2(), -1);
     vector<int> firstNeighborP(size2(), -1);
     vector<int> firstNeighborQ(size2(), -1);
     vector<int> firstNeighborQ_el(size2(), -1);
     vector<int> treated(size2(), -1);
     vector<int> hub(nnz_upper(), -1);
     vector<int> Tmapping;
     transpose(Tmapping);
     vector<int> star(nnz());
     int k = 0;
     for (int i=0; i<size2(); ++i) {
       for (int j_el=colind[i]; j_el<colind[i+1]; ++j_el) {
         int j = row[j_el];
         if (i<j) {
           star[j_el] = k;
           star[Tmapping[j]] = k;
           k++;
         }
       }
     }
     int starID = 0;
     // 3: for each v \in V do
     for (int v=0; v<size2(); ++v) {
       // 4: for each colored w \in N1(v) do
       for (int w_el=colind[v]; w_el<colind[v+1]; ++w_el) {
           int w = row[w_el];
           int colorW = color[w];
           if (colorW==-1) continue;
           // 5: forbiddenColors[color[w]] <- v
           forbiddenColors[colorW] = v;
           // 6: (p, q) <- firstNeighbor[color[w]]
           int p = firstNeighborP[colorW];
           int q = firstNeighborQ[colorW];
           // 7: if p = v then    <   Case 1
           if (v==p) {
             // 8: if treated[q] != v then
             if (treated[q]!=v) {
               // 9: treat(v, q)  < forbid colors of neighbors of q
                 // treat@2: for each colored x \in N1 (q) do
                 for (int x_el=colind[q]; x_el<colind[q+1]; ++x_el) {
                   int x = row[x_el];
                   if (color[x]==-1) continue;
                   // treat@3: forbiddenColors[color[x]] <- v
                   forbiddenColors[color[x]] = v;
                 }
                 // treat@4: treated[q] <- v
                 treated[q] = v;
             }
             // 10: treat(v, w) < forbid colors of neighbors of w
               // treat@2: for each colored x \in N1 (w) do
               for (int x_el=colind[w]; x_el<colind[w+1]; ++x_el) {
                 int x = row[x_el];
                 if (color[x]==-1) continue;
                 // treat@3: forbiddenColors[color[x]] <- v
                 forbiddenColors[color[x]] = v;
               }
               // treat@4: treated[w] <- v
               treated[w] = v;
           // 11: else
           } else {
             // 12: firstNeighbor[color[w]] <- (v, w)
             firstNeighborP[colorW] = v;
             firstNeighborQ[colorW] = w;
             firstNeighborQ_el[colorW] = w_el;
             // 13: for each colored vertex x \in N1 (w) do
             int x_el_end = colind[w+1];
             int x, colorx;
             for (int x_el=colind[w]; x_el < x_el_end; ++x_el) {
               x = row[x_el];
               colorx = color[x];
               if (colorx==-1 || x==v) continue;
               // 14: if x = hub[star[wx]] then potential Case 2
               if (hub[star[x_el]]==x) {
                 // 15: forbiddenColors[color[x]] <- v
                 forbiddenColors[colorx] = v;
               }
             }
           }
       }
       // 16: color[v] <- min {c > 0 : forbiddenColors[c] != v}
       bool new_color = true;
       for (int color_i=0; color_i<forbiddenColors.size(); ++color_i) {
         // Break if color is ok
         if (forbiddenColors[color_i]!=v) {
           color[v] = color_i;
           new_color = false;
           break;
         }
       }
       // New color if reached end
       if (new_color) {
         color[v] = forbiddenColors.size();
         forbiddenColors.push_back(-1);
         // Cutoff if too many colors
         if (forbiddenColors.size()>cutoff) {
           return Sparsity();
         }
       }
       // 17: updateStars(v)
         // updateStars@2: for each colored w \in N1 (v) do
         for (int w_el=colind[v]; w_el<colind[v+1]; ++w_el) {
             int w = row[w_el];
             int colorW = color[w];
             if (colorW==-1) continue;
             // updateStars@3: if exits x \in N1 (w) where x = v and color[x] = color[v] then
             bool check = false;
             int x;
             int x_el;
             for (x_el=colind[w]; x_el<colind[w+1]; ++x_el) {
               x = row[x_el];
               if (x==v || color[x]!=color[v]) continue;
               check = true;
               break;
             }
             if (check) {
               // updateStars@4: hub[star[wx]] <- w
               int starwx = star[x_el];
               hub[starwx] = w;
               // updateStars@5: star[vw] <- star[wx]
               star[w_el]  = starwx;
               star[Tmapping[w_el]] = starwx;
             // updateStars@6: else
             } else {
               // updateStars@7: (p, q) <- firstNeighbor[color[w]]
               int p = firstNeighborP[colorW];
               int q = firstNeighborQ[colorW];
               int q_el = firstNeighborQ_el[colorW];
               // updateStars@8: if (p = v) and (q = w) then
               if (p==v && q!=w) {
                 // updateStars@9: hub[star[vq]] <- v
                 int starvq = star[q_el];
                 hub[starvq] = v;
                 // updateStars@10: star[vw] <- star[vq]
                 star[w_el]  = starvq;
                 star[Tmapping[w_el]] = starvq;
               // updateStars@11: else
               } else {
                 // updateStars@12: starID <- starID + 1
                 starID+= 1;
                 // updateStars@13: star[vw] <- starID
                 star[w_el] = starID;
                 star[Tmapping[w_el]]= starID;
               }
             }
          }
     }
     // Create return sparsity containing the coloring
     vector<int> ret_colind(forbiddenColors.size()+1, 0), ret_row;
     // Get the number of rows for each col
     for (int i=0; i<color.size(); ++i) {
       ret_colind[color[i]+1]++;
     }
     // Cumsum
     for (int j=0; j<forbiddenColors.size(); ++j) {
       ret_colind[j+1] += ret_colind[j];
     }
     // Get row for each col
     ret_row.resize(color.size());
     for (int j=0; j<ret_row.size(); ++j) {
       ret_row[ret_colind[color[j]]++] = j;
     }
     // Swap index back one step
     for (int j=ret_colind.size()-2; j>=0; --j) {
       ret_colind[j+1] = ret_colind[j];
     }
     ret_colind[0] = 0;
     // Return the coloring
     return Sparsity(size2(), forbiddenColors.size(), ret_colind, ret_row);
   }
Sparsity casadi::SparsityInternal::sub (const std::vector< int > & rr, const std::vector< int > & cc, std::vector< int > & mapping, bool ind1) const
Referenced by casadi::Sparsity::sub().
Sparsity casadi::SparsityInternal::sub (const std::vector< int > & rr, const SparsityInternal & sp, std::vector< int > & mapping, bool ind1) const
Sparsity casadi::SparsityInternal::T () const
Definition at line 118 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::T().
{
     // Dummy mapping
     vector<int> mapping;
     return transpose(mapping);
   }
Sparsity casadi::SparsityInternal::transpose (std::vector< int > & mapping, bool invert_mapping = false) const
Parameters
[out] mapping the non-zeros of the original matrix for each non-zero of the new matrix
Definition at line 125 of file sparsity_internal.cpp.
Referenced by casadi::Sparsity::transpose().
{
     // Get the sparsity of the transpose in sparse triplet form
     vector<int> trans_col = get_row();
     vector<int> trans_row = get_col();
     // Create the sparsity pattern
     return Sparsity::triplet(size2(), size1(), trans_row, trans_col, mapping, invert_mapping);
   }
Sparsity casadi::SparsityInternal::uni_coloring (const Sparsity & AT, int cutoff) const
A greedy distance-2 coloring algorithm (Algorithm 3.1 in A. H. GEBREMEDHIN, F. MANNE, A. POTHEN)
Definition at line 3078 of file sparsity_internal.cpp.
References casadi::Sparsity::colind(), and casadi::Sparsity::row().
Referenced by casadi::Sparsity::uni_coloring().
{
     // Allocate temporary vectors
     vector<int> forbiddenColors;
     forbiddenColors.reserve(size2());
     vector<int> color(size2(), 0);
     // Access the sparsity of the transpose
     const int* AT_colind = AT.colind();
     const int* AT_row = AT.row();
     const int* colind = this->colind();
     const int* row = this->row();
     // Loop over columns
     for (int i=0; i<size2(); ++i) {
       // Loop over nonzero elements
       for (int el=colind[i]; el<colind[i+1]; ++el) {
         // Get row
         int c = row[el];
         // Loop over previous columns that have an element in row c
         for (int el_prev=AT_colind[c]; el_prev<AT_colind[c+1]; ++el_prev) {
           // Get the col
           int i_prev = AT_row[el_prev];
           // Escape loop if we have arrived at the current col
           if (i_prev>=i)
             break;
           // Get the color of the col
           int color_prev = color[i_prev];
           // Mark the color as forbidden for the current col
           forbiddenColors[color_prev] = i;
         }
       }
       // Get the first nonforbidden color
       int color_i;
       for (color_i=0; color_i<forbiddenColors.size(); ++color_i) {
         // Break if color is ok
         if (forbiddenColors[color_i]!=i) break;
       }
       color[i] = color_i;
       // Add color if reached end
       if (color_i==forbiddenColors.size()) {
         forbiddenColors.push_back(0);
         // Cutoff if too many colors
         if (forbiddenColors.size()>cutoff) {
           return Sparsity();
         }
       }
     }
     // Create return sparsity containing the coloring
     vector<int> ret_colind(forbiddenColors.size()+1, 0), ret_row;
     // Get the number of rows for each col
     for (int i=0; i<color.size(); ++i) {
       ret_colind[color[i]+1]++;
     }
     // Cumsum
     for (int j=0; j<forbiddenColors.size(); ++j) {
       ret_colind[j+1] += ret_colind[j];
     }
     // Get row for each col
     ret_row.resize(color.size());
     for (int j=0; j<ret_row.size(); ++j) {
       ret_row[ret_colind[color[j]]++] = j;
     }
     // Swap index back one step
     for (int j=ret_colind.size()-2; j>=0; --j) {
       ret_colind[j+1] = ret_colind[j];
     }
     ret_colind[0] = 0;
     // Return the coloring
     return Sparsity(size2(), forbiddenColors.size(), ret_colind, ret_row);
 ;
   }
void casadi::SparsityInternal::unmatched (int m, const std::vector< int > & wi, std::vector< int > & p, std::vector< int > & rr, int set) static
Definition at line 401 of file sparsity_internal.cpp.
{
     // NOTE: This implementation has been copied from CSparse and then modified,
     // it needs cleaning up to be proper C++
     int i, kr = rr[set] ;
     for (i=0; i<m; i++)
       if (wi[i] == 0)
         p[kr++] = i;
     rr[set+1] = kr;
   }
int casadi::SparsityInternal::vcount (std::vector< int > & pinv, std::vector< int > & parent, std::vector< int > & leftmost, int & S_m2, double & S_lnz) const
compute nnz(V) = S->lnz, S->pinv, S->leftmost, S->m2 from A and S->parent: See cs_vcount in CSparse
Definition at line 865 of file sparsity_internal.cpp.
References casadi::fill().
Referenced by prefactorize().
{
     int i, k, p, pa;
     int n = size2(), m = size1();
     const int* Ap = colind();
     const int* Ai = row();
     // allocate pinv
     pinv.resize(m+n);
     fill(pinv.begin(), pinv.end(), 0);
     // and leftmost
     leftmost.resize(m);
     // get workspace
     vector<int> w(m+3*n);
     int *next = &w.front();
     int *head = &w.front() + m;
     int *tail = &w.front() + m + n;
     int *nque = &w.front() + m + 2*n;
     // queue k is empty
     for (k = 0 ; k < n ; k++)
       head[k] = -1;
     for (k=0; k<n; ++k)
       tail[k] = -1;
     for (k=0; k<n; ++k)
       nque[k] = 0;
     for (i=0; i<m; ++i)
       leftmost[i] = -1;
     for (k=n-1; k>=0; --k) {
       for (p=Ap[k]; p<Ap[k+1]; ++p) {
         // leftmost[i] = min(find(A(i, :)))
         leftmost[Ai[p]] = k;
       }
     }
     // scan columns in reverse order
     for (i = m-1; i >= 0; i--) {
       // col i is not yet ordered
       pinv[i] = -1;
       k = leftmost[i] ;
       // col i is empty
       if (k == -1) continue;
       // first col in queue k
       if (nque[k]++ == 0)
         tail[k] = i;
       // put i at head of queue k
       next[i] = head[k];
       head[k] = i;
     }
     S_lnz = 0;
     S_m2 = m;
     // find col permutation and nnz(V)
     for (k=0; k<n; ++k) {
       // remove col i from queue k
       i = head[k];
       // count V(k, k) as nonzero
       S_lnz++;
       // add a fictitious col
       if (i < 0)
         i = S_m2++;
       // associate col i with V(:, k)
       pinv[i] = k;
       // skip if V(k+1:m, k) is empty
       if (--nque[k] <= 0) continue;
       // nque [k] is nnz (V(k+1:m, k))
       S_lnz += nque[k];
       // move all columns to parent of k
       if ((pa = parent[k]) != -1) {
         if (nque[pa] == 0)
           tail[pa] = tail[k];
         next[tail[k]] = head[pa] ;
         head[pa] = next[i] ;
         nque[pa] += nque[k] ;
       }
     }
     for (i=0; i<m ; ++i)
       if (pinv[i] < 0)
         pinv[i] = k++;
     pinv.resize(m);
     return 1;
   }
int casadi::SparsityInternal::wclear (int mark, int lemax, int * w, int n) static
Definition at line 1145 of file sparsity_internal.cpp.
{
     int k ;
     if (mark < 2 || (mark + lemax < 0)) {
         for (k = 0 ; k < n ; k++) if (w[k] != 0) w[k] = 1 ;
         mark = 2 ;
       }
     return (mark) ;     /* at this point, w[0..n-1] < mark holds */
   }
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
The documentation for this class was generated from the following files:
sparsity_internal.hpp
sparsity_internal.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge