CasADi: casadi::casadi_limits< SXElem > Class Template Reference
casadi::casadi_limits< SXElem > Class Template Reference
#include <sx_elem.hpp>
Detailed Description
template<>
class casadi::casadi_limits< SXElem >
Definition at line 231 of file sx_elem.hpp.
Static Public Member Functions
static bool is_zero (const SXElem &val)
static bool is_equal (const SXElem &x, const SXElem &y, int depth)
static bool isAlmostZero (const SXElem &val, double tol)
static bool is_one (const SXElem &val)
static bool is_minus_one (const SXElem &val)
static bool is_constant (const SXElem &val)
static bool is_integer (const SXElem &val)
static bool isInf (const SXElem &val)
static bool isMinusInf (const SXElem &val)
static bool isNaN (const SXElem &val)
Static Public Attributes
static const SXElem zero
static const SXElem one
static const SXElem two
static const SXElem minus_one
static const SXElem nan
static const SXElem inf
static const SXElem minus_inf
Member Function Documentation
bool casadi::casadi_limits< SXElem >::is_constant (const SXElem & val) static
Definition at line 548 of file sx_elem.cpp.
References casadi::SXElem::is_constant().
{
     return val.is_constant();
   }
bool casadi::casadi_limits< SXElem >::is_equal (const SXElem & x, const SXElem & y, int depth) static
Definition at line 532 of file sx_elem.cpp.
References casadi::SXElem::is_equal().
{
     return SXElem::is_equal(x, y, depth);
   }
bool casadi::casadi_limits< SXElem >::is_integer (const SXElem & val) static
Definition at line 552 of file sx_elem.cpp.
References casadi::SXElem::is_integer().
{
     return val.is_integer();
   }
bool casadi::casadi_limits< SXElem >::is_minus_one (const SXElem & val) static
Definition at line 544 of file sx_elem.cpp.
References casadi::SXElem::is_minus_one().
{
     return val.is_minus_one();
   }
bool casadi::casadi_limits< SXElem >::is_one (const SXElem & val) static
Definition at line 540 of file sx_elem.cpp.
References casadi::SXElem::is_one().
{
     return val.is_one();
   }
bool casadi::casadi_limits< SXElem >::is_zero (const SXElem & val) static
Definition at line 528 of file sx_elem.cpp.
References casadi::SXElem::is_zero().
{
     return val.is_zero();
   }
bool casadi::casadi_limits< SXElem >::isAlmostZero (const SXElem & val, double tol) static
Definition at line 536 of file sx_elem.cpp.
References casadi::SXElem::isAlmostZero().
{
     return val.isAlmostZero(tol);
   }
bool casadi::casadi_limits< SXElem >::isInf (const SXElem & val) static
Definition at line 556 of file sx_elem.cpp.
References casadi::SXElem::isInf().
{
     return val.isInf();
   }
bool casadi::casadi_limits< SXElem >::isMinusInf (const SXElem & val) static
Definition at line 560 of file sx_elem.cpp.
References casadi::SXElem::isMinusInf().
{
     return val.isMinusInf();
   }
bool casadi::casadi_limits< SXElem >::isNaN (const SXElem & val) static
Definition at line 564 of file sx_elem.cpp.
References casadi::SXElem::isNan().
{
     return val.isNan();
   }
Member Data Documentation
const SXElem casadi::casadi_limits< SXElem >::inf static
Definition at line 249 of file sx_elem.hpp.
const SXElem casadi::casadi_limits< SXElem >::minus_inf static
Definition at line 250 of file sx_elem.hpp.
const SXElem casadi::casadi_limits< SXElem >::minus_one static
Definition at line 247 of file sx_elem.hpp.
const SXElem casadi::casadi_limits< SXElem >::nan static
Definition at line 248 of file sx_elem.hpp.
const SXElem casadi::casadi_limits< SXElem >::one static
Definition at line 245 of file sx_elem.hpp.
const SXElem casadi::casadi_limits< SXElem >::two static
Definition at line 246 of file sx_elem.hpp.
const SXElem casadi::casadi_limits< SXElem >::zero static
Definition at line 244 of file sx_elem.hpp.
The documentation for this class was generated from the following files:
sx_elem.hpp
sx_elem.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge