CasADi: casadi::MX Class Reference
casadi::MX Class Reference
MX - Matrix expression.
#include <mx.hpp>
Detailed Description
The MX class is used to build up trees made up from MXNodes. It is a more general graph representation than the scalar expression, SX, and much less efficient for small objects. On the other hand, the class allows much more general operations than does SX, in particular matrix valued operations and calls to arbitrary differentiable functions.
The MX class is designed to have identical syntax with the Matrix<> template class, and uses Matrix<double> as its internal representation of the values at a node. By keeping the syntaxes identical, it is possible to switch from one class to the other, as well as inlining MX functions to SXElem functions.
Note that an operation is always "lazy", making a matrix multiplication will create a matrix multiplication node, not perform the actual multiplication.
Author
Joel Andersson
Date
2010-2011
Definition at line 58 of file mx.hpp.
Public Types
typedef MX ScalarType
typedef GenericMatrix< MX > B
Base class.
typedef std::map< std::string, MX > MXDict
Public Member Functions
MX ()
Default constructor.
MX (int nrow, int ncol)
Create a sparse matrix with all structural zeros.
MX (const std::pair< int, int > &rc)
Create a sparse matrix with all structural zeros.
MX (const Sparsity &sp)
Create a sparse matrix from a sparsity pattern. Same as MX::ones(sparsity)
MX (const Sparsity &sp, const MX &val)
Construct matrix with a given sparsity and nonzeros.
MX (double x)
Create scalar constant (also implicit type conversion)
MX (const MX &x)
Copy constructor.
MX (const std::vector< double > &x)
Create vector constant (also implicit type conversion)
MX (const Matrix< double > &x)
Create sparse matrix constant (also implicit type conversion)
~MX ()
Destructor.
const Sparsity & sparsity () const
Get the sparsity pattern.
bool __nonzero__ () const
Returns the truth value of an MX expression.
Sparsity get_sparsity () const
Get an owning reference to the sparsity pattern.
void erase (const std::vector< int > &rr, const std::vector< int > &cc, bool ind1=false)
Erase a submatrix (leaving structural zeros in its place) Erase rows and/or columns of a matrix.
void erase (const std::vector< int > &rr, bool ind1=false)
Erase a submatrix (leaving structural zeros in its place) Erase elements of a matrix.
void enlarge (int nrow, int ncol, const std::vector< int > &rr, const std::vector< int > &cc, bool ind1=false)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
MX operator- () const
MX dep (int ch=0) const
Get the nth dependency as MX.
int n_out () const
Number of outputs.
MX getOutput (int oind=0) const
Get an output.
int n_dep () const
Get the number of dependencies of a binary SXElem.
std::string name () const
Get the name.
operator double () const
Get the value (only for scalar constant nodes)
operator Matrix< double > () const
Get the value (only for constant nodes)
bool is_symbolic () const
Check if symbolic.
bool is_constant () const
Check if constant.
bool is_call () const
Check if evaluation.
bool is_output () const
Check if evaluation output.
int get_output () const
Get the index of evaluation output - only valid when is_calloutput() is true.
bool is_op (int op) const
Is it a certain operation.
bool is_multiplication () const
Check if multiplication.
bool is_commutative () const
Check if commutative operation.
bool is_norm () const
Check if norm.
bool is_valid_input () const
Check if matrix can be used to define function inputs. Valid inputs for MXFunctions are combinations of Reshape, concatenations and SymbolicMX.
int n_primitives () const
Get the number of symbolic primitive Assumes is_valid_input() returns true.
std::vector< MX > primitives () const
Get symbolic primitives.
std::vector< MX > split_primitives (const MX &x) const
Split up an expression along symbolic primitives.
MX join_primitives (std::vector< MX > &v) const
Join an expression along symbolic primitives.
bool has_duplicates ()
Detect duplicate symbolic expressions If there are symbolic primitives appearing more than once, the function will return true and the names of the duplicate expressions will be printed to userOut<true, PL_WARN>(). Note: Will mark the node using MX::setTemp. Make sure to call resetInput() after usage.
void resetInput ()
Reset the marker for an input expression.
bool is_identity () const
check if identity
bool is_zero () const
check if zero (note that false negative answers are possible)
bool is_one () const
check if zero (note that false negative answers are possible)
bool is_minus_one () const
check if zero (note that false negative answers are possible)
bool is_transpose () const
Is the expression a transpose?
bool is_regular () const
Checks if expression does not contain NaN or Inf.
int numFunctions () const
Number of functions.
Function getFunction (int i=0)
Get function.
bool is_binary () const
Is binary operation.
bool is_unary () const
Is unary operation.
int op () const
Get operation type.
int getTemp () const
void setTemp (int t)
Set the temporary variable.
MXNode * get () const
Get a const pointer to the node.
void set (const MX &m, bool ind1, const Slice &rr, const Slice &cc)
void set (const MX &m, bool ind1, const Slice &rr, const Matrix< int > &cc)
void set (const MX &m, bool ind1, const Matrix< int > &rr, const Slice &cc)
void set (const MX &m, bool ind1, const Matrix< int > &rr, const Matrix< int > &cc)
MX printme (const MX &y) const
MX attachAssert (const MX &y, const std::string &fail_message="") const
returns itself, but with an assertion attached
MX monitor (const std::string &comment) const
Monitor an expression Returns itself, but with the side effect of printing the nonzeros along with a comment.
MX T () const
Transpose the matrix.
Matrix< int > mapping () const
Get an IM representation of a GetNonzeros or SetNonzeros node.
MX (const Sparsity &sp, int val, bool dummy)
Construct constant matrix with a given sparsity and values.
MX (const Sparsity &sp, double val, bool dummy)
int nnz () const
Get the number of (structural) non-zero elements.
int nnz_lower () const
Get the number of non-zeros in the lower triangular half.
int nnz_upper () const
Get the number of non-zeros in the upper triangular half.
int nnz_diag () const
Get get the number of non-zeros on the diagonal.
int numel () const
Get the number of elements.
int numel (int i) const
Get the number of elements in slice (cf. MATLAB)
int size1 () const
Get the first dimension (i.e. number of rows)
int size2 () const
Get the second dimension (i.e. number of columns)
std::string dim () const
Get string representation of dimensions. The representation is (nrow x ncol = numel | size)
std::pair< int, int > size () const
Get the shape.
int size (int axis) const
Get the size along a particular dimensions.
bool is_empty (bool both=false) const
Check if the sparsity is empty, i.e. if one of the dimensions is zero (or optionally both dimensions)
bool is_dense () const
Check if the matrix expression is dense.
bool is_scalar (bool scalar_and_dense=false) const
Check if the matrix expression is scalar.
bool is_square () const
Check if the matrix expression is square.
bool is_vector () const
Check if the matrix is a row or column vector.
bool is_row () const
Check if the matrix is a row vector (i.e. size1()==1)
bool is_column () const
Check if the matrix is a column vector (i.e. size2()==1)
bool is_triu () const
Check if the matrix is upper triangular.
bool is_tril () const
Check if the matrix is lower triangular.
std::vector< int > find (bool ind1=SWIG_IND1) const
Get the location of all non-zero elements as they would appear in a Dense matrix A : DenseMatrix 4 x 3 B : SparseMatrix 4 x 3 , 5 structural non-zeros.
SWIG_CONSTREF (Sparsity) sparsity() const
Get the sparsity pattern.
Sparsity & sparsityRef ()
Access the sparsity, make a copy if there are multiple references to it.
const MX operator[] (const K &k) const
Get vector nonzero or slice of nonzeros.
NonZeros< MX, K > operator[] (const K &k)
Access vector nonzero or slice of nonzeros.
const MX operator() (const RR &rr) const
Get vector element or slice.
const MX operator() (const RR &rr, const CC &cc) const
Get Matrix element or slice.
SubIndex< MX, RR > operator() (const RR &rr)
Access Matrix elements (one argument)
SubMatrix< MX, RR, CC > operator() (const RR &rr, const CC &cc)
Access Matrix elements (two arguments)
void assignNode (SharedObjectNode *node)
void assignNodeNoCount (SharedObjectNode *node)
Assign the node to a node class pointer without reference counting.
int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void printPtr (std::ostream &stream=casadi::userOut()) const
bool is_null () const
Is a null pointer?
WeakRef * weak ()
Get a weak reference to the object.
size_t __hash__ () const
Returns a number that is unique for a given Node. If the Object does not point to any node, "0" is returned.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
MXNode * operator-> ()
Access a member of the node.
const MXNode * operator-> () const
Const access a member of the node.
void get (MX &output_m, bool ind1, const Slice &rr) const
void get (MX &output_m, bool ind1, const Matrix< int > &rr) const
void get (MX &output_m, bool ind1, const Sparsity &sp) const
void get (MX &output_m, bool ind1, const Slice &rr, const Slice &cc) const
void get (MX &output_m, bool ind1, const Slice &rr, const Matrix< int > &cc) const
void get (MX &output_m, bool ind1, const Matrix< int > &rr, const Slice &cc) const
void get (MX &output_m, bool ind1, const Matrix< int > &rr, const Matrix< int > &cc) const
void set (const MX &m, bool ind1, const Slice &rr)
void set (const MX &m, bool ind1, const Matrix< int > &rr)
void set (const MX &m, bool ind1, const Sparsity &sp)
void get_nz (MX &output_m, bool ind1, const Slice &kk) const
void get_nz (MX &output_m, bool ind1, const Matrix< int > &kk) const
void set_nz (const MX &m, bool ind1, const Slice &kk)
void set_nz (const MX &m, bool ind1, const Matrix< int > &kk)
MX & operator+= (const MX &y)
In-place addition.
MX & operator-= (const MX &y)
In-place subtraction.
MX & operator*= (const MX &y)
In-place elementwise multiplication.
MX & operator/= (const MX &y)
In-place elementwise division.
MX operator! () const
Logical not Returns (an expression evaluating to) 1 if expression is zero and 0 otherwise.
std::vector< int > get_row () const
Get the sparsity pattern. See the Sparsity class for details.
std::vector< int > get_colind () const
Get the sparsity pattern. See the Sparsity class for details.
const int * row () const
Get the sparsity pattern. See the Sparsity class for details.
int row (int el) const
Get the sparsity pattern. See the Sparsity class for details.
const int * colind () const
Get the sparsity pattern. See the Sparsity class for details.
int colind (int col) const
Get the sparsity pattern. See the Sparsity class for details.
Static Public Member Functions
static MX create (MXNode *node)
Create from node.
static std::vector< MX > createMultipleOutput (MXNode *node)
Create from node (multiple-outputs)
static MX eye (int ncol)
Identity matrix.
static void setEqualityCheckingDepth (int eq_depth=1)
Set or reset the depth to which equalities are being checked for simplifications.
static int getEqualityCheckingDepth ()
Get the depth to which equalities are being checked for simplifications.
static bool test_cast (const SharedObjectNode *ptr)
Check if a particular cast is allowed.
static std::vector< MX > get_input (const Function &f)
Get function inputs.
static std::string type_name ()
Get name of the class.
static std::vector
< std::vector< MX > > blocksplit (const MX &x, const std::vector< int > &vert_offset, const std::vector< int > &horz_offset)
static std::vector
< std::vector< MX > > blocksplit (const MX &x, int vert_incr, int horz_incr)
static MX veccat (const std::vector< MX > &x)
static MX vec (const MX &x)
static MX repmat (const MX &A, const std::pair< int, int > &rc)
static std::vector< int > offset (const std::vector< MX > &v, bool vert=true)
static std::vector< MX > diagsplit (const MX &x, const std::vector< int > &output_offset)
static std::vector< MX > diagsplit (const MX &x, int incr)
static std::vector< MX > diagsplit (const MX &x, int incr1, int incr2)
static MX mtimes (const std::vector< MX > &args)
static std::vector< MX > horzsplit (const MX &x, int incr)
static std::vector< MX > vertsplit (const MX &x, int incr)
static MX binary (int op, const MX &x, const MX &y)
Create nodes by their ID.
static MX unary (int op, const MX &x)
Create nodes by their ID.
static MX inf (const Sparsity &sp)
create a matrix with all inf
static MX inf (int nrow=1, int ncol=1)
create a matrix with all inf
static MX inf (const std::pair< int, int > &rc)
create a matrix with all inf
static MX nan (const Sparsity &sp)
create a matrix with all nan
static MX nan (int nrow=1, int ncol=1)
create a matrix with all nan
static MX nan (const std::pair< int, int > &rc)
create a matrix with all nan
static bool is_equal (const MX &x, const MX &y, int depth=0)
static MX horzcat (const std::vector< MX > &x)
static MX diagcat (const std::vector< MX > &x)
static MX vertcat (const std::vector< MX > &x)
static std::vector< MX > horzsplit (const MX &x, const std::vector< int > &offset)
static std::vector< MX > diagsplit (const MX &x, const std::vector< int > &offset1, const std::vector< int > &offset2)
static std::vector< MX > vertsplit (const MX &x, const std::vector< int > &offset)
static MX blockcat (const std::vector< std::vector< MX > > &v)
static MX mtimes (const MX &x, const MX &y)
static MX mac (const MX &x, const MX &y, const MX &z)
static MX reshape (const MX &x, int nrow, int ncol)
static MX reshape (const MX &x, const Sparsity &sp)
static MX kron (const MX &x, const MX &b)
static MX repmat (const MX &x, int n, int m=1)
static MX jacobian (const MX &f, const MX &x, bool symmetric=false)
static MX gradient (const MX &f, const MX &x)
static MX tangent (const MX &f, const MX &x)
static MX hessian (const MX &f, const MX &x)
static MX hessian (const MX &f, const MX &x, MX &g)
static MX jtimes (const MX &ex, const MX &arg, const MX &v, bool tr=false)
static std::vector< bool > nl_var (const MX &expr, const MX &var)
static MX substitute (const MX &ex, const MX &v, const MX &vdef)
static std::vector< MX > substitute (const std::vector< MX > &ex, const std::vector< MX > &v, const std::vector< MX > &vdef)
static void substitute_inplace (const std::vector< MX > &v, std::vector< MX > &vdef, std::vector< MX > &ex, bool reverse)
static MX solve (const MX &A, const MX &b, const std::string &lsolver="symbolicqr", const Dict &dict=Dict())
static MX pinv (const MX &A, const std::string &lsolver="symbolicqr", const Dict &dict=Dict())
static int n_nodes (const MX &x)
static std::string print_operator (const MX &x, const std::vector< std::string > &args)
static void shared (std::vector< MX > &ex, std::vector< MX > &v, std::vector< MX > &vdef, const std::string &v_prefix, const std::string &v_suffix)
static MX if_else (const MX &cond, const MX &if_true, const MX &if_false, bool short_circuit=true)
static MX conditional (const MX &ind, const std::vector< MX > &x, const MX &x_default, bool short_circuit=true)
static bool depends_on (const MX &x, const MX &arg)
static MX logic_not (const MX &x)
static MX simplify (const MX &x)
static MX mpower (const MX &a, const MX &b)
static MX dot (const MX &x, const MX &y)
static MX mrdivide (const MX &a, const MX &b)
static MX mldivide (const MX &a, const MX &b)
static MX norm_2 (const MX &x)
static MX norm_F (const MX &x)
static MX norm_1 (const MX &x)
static MX norm_inf (const MX &x)
static MX unite (const MX &A, const MX &B)
static MX trace (const MX &x)
static MX diag (const MX &x)
static MX sum2 (const MX &x)
static MX sum1 (const MX &x)
static MX polyval (const MX &p, const MX &x)
static MX det (const MX &x)
static MX inv (const MX &x)
static std::vector< MX > symvar (const MX &x)
static MX nullspace (const MX &A)
static MX repsum (const MX &x, int n, int m=1)
static MX densify (const MX &x, const MX &val=0)
static MX _bilin (const MX &A, const MX &x, const MX &y)
static MX _rank1 (const MX &A, const MX &alpha, const MX &x, const MX &y)
static MX project (const MX &x, const Sparsity &sp, bool intersect=false)
static MX find (const MX &x)
static MX graph_substitute (const MX &x, const std::vector< MX > &v, const std::vector< MX > &vdef)
static std::vector< MX > graph_substitute (const std::vector< MX > &ex, const std::vector< MX > &expr, const std::vector< MX > &exprs)
static MX matrix_expand (const MX &e, const std::vector< MX > &boundary, const Dict &options)
static std::vector< MX > matrix_expand (const std::vector< MX > &e, const std::vector< MX > &boundary, const Dict &options)
static MX lift (const MX &x, const MX &x_guess)
static MX jac (const Function &f, int iind=0, int oind=0, bool compact=false, bool symmetric=false)
Jacobian expression.
static MX jac (const Function &f, const std::string &iname, int oind=0, bool compact=false, bool symmetric=false)
Jacobian expression.
static MX jac (const Function &f, int iind, const std::string &oname, bool compact=false, bool symmetric=false)
Jacobian expression.
static MX jac (const Function &f, const std::string &iname, const std::string &oname, bool compact=false, bool symmetric=false)
Jacobian expression.
static MX grad (const Function &f, int iind=0, int oind=0)
Gradient expression.
static MX grad (const Function &f, const std::string &iname, int oind=0)
Gradient expression.
static MX grad (const Function &f, int iind, const std::string &oname)
Gradient expression.
static MX grad (const Function &f, const std::string &iname, const std::string &oname)
Gradient expression.
static MX tang (const Function &f, int iind=0, int oind=0)
Tangent expression.
static MX tang (const Function &f, const std::string &iname, int oind=0)
Tangent expression.
static MX tang (const Function &f, int iind, const std::string &oname)
Tangent expression.
static MX tang (const Function &f, const std::string &iname, const std::string &oname)
Tangent expression.
static int sprank (const MX &x)
Accessed by friend functions.
static int norm_0_mul (const MX &x, const MX &y)
Accessed by friend functions.
static MX tril (const MX &x, bool includeDiagonal=true)
Accessed by friend functions.
static MX triu (const MX &x, bool includeDiagonal=true)
Accessed by friend functions.
static MX sum_square (const MX &x)
Accessed by friend functions.
static MX linspace (const MX &a, const MX &b, int nsteps)
Accessed by friend functions.
static MX cross (const MX &a, const MX &b, int dim=-1)
Accessed by friend functions.
static MX skew (const MX &a)
Accessed by friend functions.
static MX inv_skew (const MX &a)
Accessed by friend functions.
static MX tril2symm (const MX &x)
Accessed by friend functions.
static MX triu2symm (const MX &x)
Accessed by friend functions.
static MX bilin (const MX &A, const MX &x, const MX &y)
Matrix power x^n.
static MX rank1 (const MX &A, const MX &alpha, const MX &x, const MX &y)
Make a rank-1 update to a matrix A Calculates A + 1/2 * alpha * x*y'.
Construct symbolic primitives
The "sym" function is intended to work in a similar way as "sym" used in the Symbolic Toolbox for Matlab but instead creating a CasADi symbolic primitive.
static MX sym (const std::string &name, int nrow=1, int ncol=1)
Create an nrow-by-ncol symbolic primitive.
static MX sym (const std::string &name, const std::pair< int, int > &rc)
Construct a symbolic primitive with given dimensions.
static MX sym (const std::string &name, const Sparsity &sp)
Create symbolic primitive with a given sparsity pattern.
static std::vector< MX > sym (const std::string &name, const Sparsity &sp, int p)
Create a vector of length p with with matrices with symbolic primitives of given sparsity.
static std::vector< MX > sym (const std::string &name, int nrow, int ncol, int p)
Create a vector of length p with nrow-by-ncol symbolic primitives.
static std::vector
< std::vector< MX > > sym (const std::string &name, const Sparsity &sp, int p, int r)
Create a vector of length r of vectors of length p with symbolic primitives with given sparsity.
static std::vector
< std::vector< MX > > sym (const std::string &name, int nrow, int ncol, int p, int r)
Create a vector of length r of vectors of length p with nrow-by-ncol symbolic primitives.
static MX zeros (int nrow=1, int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MX zeros (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MX zeros (const std::pair< int, int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MX ones (int nrow=1, int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static MX ones (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static MX ones (const std::pair< int, int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries one.
Protected Member Functions
const MX & self () const
MX & self ()
const MX & self () const
MX & self ()
void count_up ()
void count_down ()
Friends
MX find (const MX &x)
Find first nonzero If failed, returns the number of rows.
MX graph_substitute (const MX &ex, const std::vector< MX > &v, const std::vector< MX > &vdef)
Substitute single expression in graph Substitute variable v with expression vdef in an expression ex, preserving nodes.
std::vector< MX > graph_substitute (const std::vector< MX > &ex, const std::vector< MX > &v, const std::vector< MX > &vdef)
Substitute multiple expressions in graph Substitute variable var with expression expr in multiple expressions, preserving nodes.
MX matrix_expand (const MX &e, const std::vector< MX > &boundary=std::vector< MX >(), const Dict &options=Dict())
Expand MX graph to SXFunction call.
std::vector< MX > matrix_expand (const std::vector< MX > &e, const std::vector< MX > &boundary=std::vector< MX >(), const Dict &options=Dict())
Expand MX graph to SXFunction call.
MX lift (const MX &x, const MX &x_guess)
Lift the expression Experimental feature.
Member Typedef Documentation
typedef GenericMatrix<MX> casadi::MX::B
Definition at line 118 of file mx.hpp.
typedef std::map<std::string, MX> casadi::MX::MXDict
Readability typedefs
Definition at line 556 of file mx.hpp.
typedef MX casadi::MX::ScalarType
Scalar type
Definition at line 114 of file mx.hpp.
Constructor & Destructor Documentation
casadi::MX::MX ()
Definition at line 44 of file mx.cpp.
          {
     assignNode(ZeroByZero::getInstance());
   }
casadi::MX::MX (int nrow, int ncol)
Definition at line 93 of file mx.cpp.
{
     assignNode(ConstantMX::create(Sparsity(nrow, ncol), 0));
   }
casadi::MX::MX (const std::pair< int, int > & rc) explicit
Definition at line 97 of file mx.cpp.
{
     assignNode(ConstantMX::create(Sparsity(rc), 0));
   }
casadi::MX::MX (const Sparsity & sp) explicit
Definition at line 89 of file mx.cpp.
{
     assignNode(ConstantMX::create(sp, 1));
   }
casadi::MX::MX (const Sparsity & sp, const MX & val)
Definition at line 68 of file mx.cpp.
References casadi::densify(), casadi::MXNode::getGetNonzeros(), casadi::GenericMatrix< MatType >::is_column(), is_constant(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Sparsity::isReshape(), casadi::Sparsity::nnz(), casadi::range(), casadi::Sparsity::size(), casadi::GenericMatrix< MatType >::size1(), and sparsity().
{
     if (sp.isReshape(val.sparsity())) {
       *this = reshape(val, sp);
     } else if (val.is_scalar()) {
       // Dense matrix if val dense
       if (val.is_dense()) {
         if (val.is_constant()) {
           assignNode(ConstantMX::create(sp, static_cast<double>(val)));
         } else {
           *this = val->getGetNonzeros(sp, std::vector<int>(sp.nnz(), 0));
         }
       } else {
         // Empty matrix
         assignNode(ConstantMX::create(Sparsity(sp.size()), 0));
       }
     } else {
       casadi_assert(val.is_column() && sp.nnz()==val.size1());
       *this = densify(val)->getGetNonzeros(sp, range(sp.nnz()));
     }
   }
casadi::MX::MX (double x)
Definition at line 56 of file mx.cpp.
                  {
     assignNode(ConstantMX::create(Sparsity::dense(1, 1), x));
   }
casadi::MX::MX (const MX & x)
Definition at line 529 of file mx.cpp.
                     : SharedObject(x) {
   }
casadi::MX::MX (const std::vector< double > & x)
Definition at line 64 of file mx.cpp.
{
     assignNode(ConstantMX::create(DM(x)));
   }
casadi::MX::MX (const Matrix< double > & x)
Definition at line 60 of file mx.cpp.
{
     assignNode(ConstantMX::create(x));
   }
casadi::MX::~MX ()
Definition at line 41 of file mx.cpp.
           {
   }
casadi::MX::MX (const Sparsity & sp, int val, bool dummy)
Definition at line 101 of file mx.cpp.
{
     assignNode(ConstantMX::create(sp, val));
   }
casadi::MX::MX (const Sparsity & sp, double val, bool dummy)
Definition at line 105 of file mx.cpp.
{
     assignNode(ConstantMX::create(sp, val));
   }
Member Function Documentation
size_t casadi::SharedObject::__hash__ () const inherited
Definition at line 178 of file shared_object.cpp.
{
     return reinterpret_cast<size_t>(get());
   }
bool casadi::MX::__nonzero__ () const
Definition at line 124 of file mx.cpp.
{
     return (*this)->__nonzero__();
   }
MX casadi::MX::_bilin (const MX & A, const MX & x, const MX & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1740 of file mx.cpp.
References casadi::MXNode::getBilin().
{
    return A->getBilin(x, y);
  }
MX casadi::MX::_rank1 (const MX & A, const MX & alpha, const MX & x, const MX & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1744 of file mx.cpp.
References casadi::MXNode::getRank1().
{
    return A->getRank1(alpha, x, y);
  }
void casadi::SharedObject::assignNode (SharedObjectNode * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 57 of file shared_object.cpp.
Referenced by casadi::Function::conditional(), casadi::Callback::construct(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::Sparsity::create(), casadi::Function::create(), casadi::external(), casadi::Function::if_else(), casadi::MXFunction::init(), casadi::integrator(), casadi::jit(), casadi::Function::kernel_sum(), casadi::linsol(), casadi::nlpsol(), casadi::qpsol(), casadi::rootfinder(), and casadi::WeakRef::shared().
{
     count_down();
     node = node_;
     count_up();
   }
void casadi::SharedObject::assignNodeNoCount (SharedObjectNode * node) inherited
improper use will cause memory leaks!
Definition at line 63 of file shared_object.cpp.
{
     node = node_;
   }
MX casadi::MX::attachAssert (const MX & y, const std::string & fail_message = "") const
If y does not evaluate to 1, a runtime error is raised
Examples:
misc/assertion.py.
Definition at line 614 of file mx.cpp.
References casadi::GenericMatrix< MatType >::dim(), and casadi::GenericMatrix< MatType >::is_scalar().
{
     casadi_assert_message(y.is_scalar(),
                           "Error in attachAssert: assertion expression y must be scalar, "
                           "but got " << y.dim());
     return(*this)->getAssertion(y, fail_message);
   }
static MX casadi::GenericMatrix< MX >::bilin (const MX & A, const MX & x, const MX & y) static inherited
MX casadi::MX::binary (int op, const MX & x, const MX & y) static
Definition at line 473 of file mx.cpp.
References casadi::MXNode::getBinarySwitch().
Referenced by printme().
{
     return x->getBinarySwitch(op, y);
   }
MX casadi::MX::blockcat (const std::vector< std::vector< MX > > & v) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1006 of file mx.cpp.
References casadi::GenericMatrix< MatType >::size().
{
     // Quick return if no block rows
     if (v.empty()) return MX(0, 0);
     // Make sure same number of block columns
     int ncols = v.front().size();
     for (vector<vector<MX> >::const_iterator it=v.begin(); it!=v.end(); ++it) {
       casadi_assert_message(it->size()==ncols, "blockcat: Inconsistent number of blocl columns");
     }
     // Quick return if no block columns
     if (v.front().empty()) return MX(0, 0);
     // Horizontally concatenate all columns for each row, then vertically concatenate rows
     std::vector<MX> rows;
     for (vector<vector<MX> >::const_iterator it=v.begin(); it!=v.end(); ++it) {
       rows.push_back(horzcat(*it));
     }
     return vertcat(rows);
   }
static std::vector< std::vector< MX > > casadi::SparsityInterface< MX >::blocksplit (const MX & x, const std::vector< int > & vert_offset, const std::vector< int > & horz_offset) static inherited
static std::vector< std::vector< MX > > casadi::SparsityInterface< MX >::blocksplit (const MX & x, int vert_incr, int horz_incr) static inherited
const int* casadi::GenericMatrix< MX >::colind () const inline inherited
Definition at line 147 of file generic_matrix.hpp.
 { return sparsity().colind(); }
int casadi::GenericMatrix< MX >::colind (int col) const inline inherited
Definition at line 150 of file generic_matrix.hpp.
 { return sparsity().colind(col); }
MX casadi::MX::conditional (const MX & ind, const std::vector< MX > & x, const MX & x_default, bool short_circuit = true) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1091 of file mx.cpp.
References casadi::if_else().
{
     if (short_circuit) {
       // Get symbolic primitives
       std::vector<MX> arg = x;
       arg.push_back(x_default);
       arg = symvar(veccat(arg));
       // Form functions for cases
       vector<Function> f(x.size());
       for (int k=0; k<x.size(); ++k) {
         stringstream ss;
         ss << "f_case" << k;
         f[k] = Function(ss.str(), arg, {x[k]});
       }
       Function f_default("f_default", arg, {x_default});
       // Form Switch
       Function sw = Function::conditional("switch", f, f_default);
       // Call the Switch
       vector<MX> sw_arg;
       sw_arg.push_back(ind);
       sw_arg.insert(sw_arg.end(), arg.begin(), arg.end());
       return sw(sw_arg).at(0);
     } else {
       MX ret = x_default;
       for (int k=0; k<x.size(); ++k) {
         ret = if_else(ind==k, x[k], ret);
       }
       return ret;
     }
   }
void casadi::SharedObject::count_down () protected inherited
Definition at line 92 of file shared_object.cpp.
Referenced by casadi::Callback::transfer_ownership().
{
     if (node && --node->count == 0) {
       delete node;
       node = 0;
     }
   }
void casadi::SharedObject::count_up () protected inherited
Definition at line 88 of file shared_object.cpp.
{
     if (node) node->count++;
   }
MX casadi::MX::create (MXNode * node) static
Definition at line 52 of file mx.cpp.
Referenced by casadi::Constant< Value >::getGetNonzeros(), casadi::Constant< Value >::getProject(), casadi::Constant< Value >::getReshape(), casadi::Constant< Value >::getTranspose(), and casadi::MXFunction::init().
{
     return MX(node, false, false, false, false);
   }
std::vector< MX > casadi::MX::createMultipleOutput (MXNode * node) static
Definition at line 109 of file mx.cpp.
References casadi::MXNode::nout().
Referenced by casadi::Call::create().
{
     casadi_assert(dynamic_cast<MultipleOutput*>(node)!=0);
     MX x =  MX::create(node);
     std::vector<MX> ret(x->nout());
     for (int i=0; i<ret.size(); ++i) {
       ret[i] = MX::create(new OutputNode(x, i));
       if (ret[i].is_empty(true)) {
         ret[i] = MX(0, 0);
       } else if (ret[i].nnz()==0) {
         ret[i] = MX(ret[i].size());
       }
     }
     return ret;
   }
static MX casadi::GenericMatrix< MX >::cross (const MX & a, const MX & b, int dim = -1) static inherited
MX casadi::MX::densify (const MX & x, const MX & val = 0) static
Functions called by friend functions defined for GenericMatrix
Definition at line 722 of file mx.cpp.
References casadi::Sparsity::dense(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::MXNode::is_zero(), project(), repmat(), casadi::GenericMatrix< MatType >::size(), and sparsity().
{
     casadi_assert(val.is_scalar());
     if (x.is_dense()) {
       return x; // Already ok
     } else if (val->is_zero()) {
       return project(x, Sparsity::dense(x.size()));
     } else {
       MX ret = MX::repmat(val, x.size());
       ret(x.sparsity()) = x;
       return ret;
     }
   }
MX casadi::MX::dep (int ch = 0) const
Definition at line 645 of file mx.cpp.
References casadi::MXNode::dep().
 { return (*this)->dep(ch); }
bool casadi::MX::depends_on (const MX & x, const MX & arg) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1659 of file mx.cpp.
References casadi::get_ptr(), and casadi::GenericMatrix< MatType >::nnz().
{
     if (x.nnz()==0) return false;
     // Construct a temporary algorithm
     Function temp("tmp", {arg}, {x});
     // Perform a single dependency sweep
     vector<bvec_t> t_in(arg.nnz(), 1), t_out(x.nnz());
     temp({get_ptr(t_in)}, {get_ptr(t_out)});
     // Loop over results
     for (int i=0; i<t_out.size(); ++i) {
       if (t_out[i]) return true;
     }
     return false;
   }
MX casadi::MX::det (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1567 of file mx.cpp.
References casadi::MXNode::getDeterminant().
{
     return x->getDeterminant();
   }
MX casadi::MX::diag (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1160 of file mx.cpp.
References casadi::Sparsity::get_diag(), casadi::MXNode::getGetNonzeros(), and sparsity().
{
     // Nonzero mapping
     std::vector<int> mapping;
     // Get the sparsity
     Sparsity sp = x.sparsity().get_diag(mapping);
     // Create a reference to the nonzeros
     return x->getGetNonzeros(sp, mapping);
   }
MX casadi::MX::diagcat (const std::vector< MX > & x) static
Functions called by friend functions defined for SparsityInterface
Definition at line 885 of file mx.cpp.
References casadi::has_empty(), and casadi::trim_empty().
{
     if (x.empty()) {
       return MX();
     } else if (x.size()==1) {
       return x.front();
     } else if (has_empty(x)) {
       std::vector<MX> ret = trim_empty(x);
       if (ret.empty()) {
         // We still want diagcat(zeros(5,0),zeros(5,0)) -> zeros(10,0)
         ret = trim_empty(x, true);
         int s1 = 0;
         int s2 = 0;
         for (int i=0;i<ret.size();++i) {
           s1+= ret[i].size1();
           s2+= ret[i].size2();
         }
         return MX::zeros(s1, s2);
       } else {
         return diagcat(ret);
       }
     } else {
       return x.front()->get_diagcat(x);
     }
   }
static std::vector< MX > casadi::SparsityInterface< MX >::diagsplit (const MX & x, const std::vector< int > & output_offset) static inherited
static std::vector< MX > casadi::SparsityInterface< MX >::diagsplit (const MX & x, int incr) static inherited
static std::vector< MX > casadi::SparsityInterface< MX >::diagsplit (const MX & x, int incr1, int incr2) static inherited
std::vector< MX > casadi::MX::diagsplit (const MX & x, const std::vector< int > & offset1, const std::vector< int > & offset2) static
Functions called by friend functions defined for SparsityInterface
Definition at line 966 of file mx.cpp.
References casadi::MXNode::get_diagsplit(), casadi::isMonotone(), casadi::GenericMatrix< MatType >::size1(), and casadi::GenericMatrix< MatType >::size2().
{
     // Consistency check
     casadi_assert(offset1.size()>=1);
     casadi_assert(offset1.front()==0);
     casadi_assert(offset1.back()==x.size1());
     casadi_assert(isMonotone(offset1));
     // Consistency check
     casadi_assert(offset2.size()>=1);
     casadi_assert(offset2.front()==0);
     casadi_assert(offset2.back()==x.size2());
     casadi_assert(isMonotone(offset2));
     return x->get_diagsplit(offset1, offset2);
   }
std::string casadi::GenericMatrix< MX >::dim () const inherited
MX casadi::MX::dot (const MX & x, const MX & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 606 of file mx.cpp.
References casadi::MXNode::getDot().
{
     return x->getDot(y);
   }
void casadi::MX::enlarge (int nrow, int ncol, const std::vector< int > & rr, const std::vector< int > & cc, bool ind1 = false)
Definition at line 564 of file mx.cpp.
References casadi::Sparsity::enlarge(), casadi::MXNode::getGetNonzeros(), casadi::GenericMatrix< MX >::nnz(), casadi::range(), and sparsity().
{
     Sparsity sp = sparsity();
     sp.enlarge(nrow, ncol, rr, cc, ind1);
     MX ret = (*this)->getGetNonzeros(sp, range(nnz())); // FIXME?
     *this = ret;
   }
void casadi::MX::erase (const std::vector< int > & rr, const std::vector< int > & cc, bool ind1 = false)
Definition at line 536 of file mx.cpp.
References casadi::Sparsity::erase(), casadi::MXNode::getGetNonzeros(), mapping(), casadi::GenericMatrix< MX >::nnz(), and sparsity().
{
     // Get sparsity of the new matrix
     Sparsity sp = sparsity();
     // Erase from sparsity pattern
     std::vector<int> mapping = sp.erase(rr, cc, ind1);
     // Create new matrix
     if (mapping.size()!=nnz()) {
       MX ret = (*this)->getGetNonzeros(sp, mapping);
       *this = ret;
     }
   }
void casadi::MX::erase (const std::vector< int > & rr, bool ind1 = false)
Definition at line 550 of file mx.cpp.
References casadi::Sparsity::erase(), casadi::MXNode::getGetNonzeros(), mapping(), casadi::GenericMatrix< MX >::nnz(), and sparsity().
{
     // Get sparsity of the new matrix
     Sparsity sp = sparsity();
     // Erase from sparsity pattern
     std::vector<int> mapping = sp.erase(rr, ind1);
     // Create new matrix
     if (mapping.size()!=nnz()) {
       MX ret = (*this)->getGetNonzeros(sp, mapping);
       *this = ret;
     }
   }
MX casadi::MX::eye (int ncol) static
Definition at line 517 of file mx.cpp.
                   {
     return MX(Matrix<double>::eye(n));
   }
std::vector<int> casadi::GenericMatrix< MX >::find (bool ind1 = SWIG_IND1) const inline inherited
k = A.find() A[k] will contain the elements of A that are non-zero in B
Definition at line 160 of file generic_matrix.hpp.
 { return sparsity().find(ind1);}
MX casadi::MX::find (const MX & x) static
Functions called by friend functions defined for this class
Definition at line 1677 of file mx.cpp.
References casadi::MXNode::getFind().
{
     return x->getFind();
   }
MXNode * casadi::MX::get () const
Definition at line 481 of file mx.cpp.
Referenced by casadi::Constant< Value >::getBinary(), casadi::MXNode::getBinary(), and is_equal().
{
     return static_cast<MXNode*>(SharedObject::get());
   }
void casadi::MX::get (MX & output_m, bool ind1, const Slice & rr) const
Get a submatrix, single argument
Definition at line 158 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on IM
     get(m, ind1, rr.all(numel(), ind1));
   }
void casadi::MX::get (MX & output_m, bool ind1, const Matrix< int > & rr) const
Get a submatrix, single argument
Definition at line 163 of file mx.cpp.
References casadi::MXNode::getGetNonzeros(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_row(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), casadi::Sparsity::sub(), and casadi::Sparsity::T().
{
     // If the indexed matrix is dense, use nonzero indexing
     if (is_dense()) {
       return get_nz(m, ind1, rr);
     }
     // If indexed matrix was a row/column vector, make sure that the result is too
     bool tr = (is_column() && rr.is_row()) || (is_row() && rr.is_column());
     // Get the sparsity pattern - does bounds checking
     std::vector<int> mapping;
     Sparsity sp = sparsity().sub(rr.nonzeros(), tr ? rr.sparsity().T() : rr.sparsity(),
                                  mapping, ind1);
     // Create return MX
     m = (*this)->getGetNonzeros(sp, mapping);
   }
void casadi::MX::get (MX & output_m, bool ind1, const Sparsity & sp) const
Get a submatrix, single argument
Definition at line 181 of file mx.cpp.
References casadi::project(), and casadi::Sparsity::size().
{
     casadi_assert_message(size()==sp.size(),
                           "get(Sparsity sp): shape mismatch. This matrix has shape "
                           << size() << ", but supplied sparsity index has shape "
                           << sp.size() << ".");
     m = project(*this, sp);
   }
void casadi::MX::get (MX & output_m, bool ind1, const Slice & rr, const Slice & cc) const
Get a submatrix, two arguments
Definition at line 128 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     return get(m, ind1, rr.all(size1(), ind1), cc.all(size2(), ind1));
   }
void casadi::MX::get (MX & output_m, bool ind1, const Slice & rr, const Matrix< int > & cc) const
Get a submatrix, two arguments
Definition at line 133 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     get(m, ind1, rr.all(size1(), ind1), cc);
   }
void casadi::MX::get (MX & output_m, bool ind1, const Matrix< int > & rr, const Slice & cc) const
Get a submatrix, two arguments
Definition at line 138 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     get(m, ind1, rr, cc.all(size2(), ind1));
   }
void casadi::MX::get (MX & output_m, bool ind1, const Matrix< int > & rr, const Matrix< int > & cc) const
Get a submatrix, two arguments
Definition at line 143 of file mx.cpp.
References casadi::MXNode::getGetNonzeros(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_vector(), casadi::Matrix< Scalar >::nonzeros(), and casadi::Sparsity::sub().
{
     // Make sure dense vectors
     casadi_assert_message(rr.is_dense() && rr.is_vector(),
                           "Marix::get: First index must be a dense vector");
     casadi_assert_message(cc.is_dense() && cc.is_vector(),
                           "Marix::get: Second index must be a dense vector");
     // Get the sparsity pattern - does bounds checking
     std::vector<int> mapping;
     Sparsity sp = sparsity().sub(rr.nonzeros(), cc.nonzeros(), mapping, ind1);
     // Create return MX
     m = (*this)->getGetNonzeros(sp, mapping);
   }
std::vector<int> casadi::GenericMatrix< MX >::get_colind () const inline inherited
Definition at line 144 of file generic_matrix.hpp.
 { return sparsity().get_colind(); }
std::vector< MX > casadi::MX::get_input (const Function & f) static
Definition at line 1681 of file mx.cpp.
References casadi::Function::mx_in().
{
     return f.mx_in();
   }
void casadi::MX::get_nz (MX & output_m, bool ind1, const Slice & kk) const
Get a set of nonzeros
Definition at line 364 of file mx.cpp.
References casadi::Slice::all().
{
     // Fallback on IM
     get_nz(m, ind1, kk.all(nnz(), ind1));
   }
void casadi::MX::get_nz (MX & output_m, bool ind1, const Matrix< int > & kk) const
Get a set of nonzeros
Definition at line 369 of file mx.cpp.
References casadi::MXNode::getGetNonzeros(), casadi::inBounds(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_row(), casadi::GenericMatrix< MatType >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), and casadi::Sparsity::T().
{
     // If indexed matrix was a row/column vector, make sure that the result is too
     bool tr = (is_column() && kk.is_row()) || (is_row() && kk.is_column());
     // Quick return if no entries
     if (kk.nnz()==0) {
       m = MX::zeros(tr ? kk.sparsity().T() : kk.sparsity());
       return;
     }
     // Check bounds
     int sz = nnz();
     if (!inBounds(kk.nonzeros(), -sz+ind1, sz+ind1)) {
       casadi_error("get_nz[kk] out of bounds. Your kk contains "
                    << *std::min_element(kk->begin(), kk->end()) << " up to "
                    << *std::max_element(kk->begin(), kk->end())
                    << ", which is outside the range [" << -sz+ind1 << "," << sz+ind1 <<  ").");
     }
     // Handle index-1, negative indices
     if (ind1 || *std::min_element(kk->begin(), kk->end())<0) {
       Matrix<int> kk_mod = kk;
       for (auto&& i : kk_mod.nonzeros()) {
         casadi_assert_message(!(ind1 && i<=0), "Matlab is 1-based, but requested index " <<
                               i <<  ". Note that negative slices are" <<
                               " disabled in the Matlab interface. " <<
                               "Possibly you may want to use 'end'.");
         if (ind1) i--;
         if (i<0) i += sz;
       }
       get_nz(m, false, kk_mod); // Call recursively
       return;
     }
     // Return reference to the nonzeros
     m = (*this)->getGetNonzeros(tr ? kk.sparsity().T() : kk.sparsity(), kk.nonzeros());
   }
int casadi::MX::get_output () const
Definition at line 655 of file mx.cpp.
 { return (*this)->getFunctionOutput(); }
std::vector<int> casadi::GenericMatrix< MX >::get_row () const inline inherited
Definition at line 143 of file generic_matrix.hpp.
 { return sparsity().get_row(); }
Sparsity casadi::MX::get_sparsity () const inline
Definition at line 132 of file mx.hpp.
 { return sparsity();}
int casadi::SharedObject::getCount () const inherited
Definition at line 159 of file shared_object.cpp.
References casadi::SharedObjectNode::getCount().
Referenced by casadi::Callback::transfer_ownership().
{
     return (*this)->getCount();
   }
std::string casadi::PrintableObject< SharedObject >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
int casadi::MX::getEqualityCheckingDepth () static
Definition at line 741 of file mx.cpp.
Referenced by casadi::MXNode::maxDepth().
{
     return eq_depth_;
   }
Function casadi::MX::getFunction (int i = 0)
Definition at line 661 of file mx.cpp.
 {  return (*this)->getFunction(i); }
MX casadi::MX::getOutput (int oind = 0) const
Definition at line 706 of file mx.cpp.
References casadi::MXNode::getOutput().
{
     return (*this)->getOutput(oind);
   }
std::string casadi::PrintableObject< SharedObject >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
int casadi::MX::getTemp () const
Get the temporary variable
Definition at line 694 of file mx.cpp.
{
     return (*this)->temp;
   }
MX casadi::MX::grad (const Function & f, int iind = 0, int oind = 0) static
Definition at line 1693 of file mx.cpp.
References casadi::FunctionInternal::grad_mx().
{
     return Function(f)->grad_mx(iind, oind);
   }
MX casadi::MX::grad (const Function & f, const std::string & iname, int oind = 0) static
Definition at line 1716 of file mx.cpp.
References casadi::Function::index_in().
{
     return grad(f, f.index_in(iname), oind);
   }
MX casadi::MX::grad (const Function & f, int iind, const std::string & oname) static
Definition at line 1720 of file mx.cpp.
References casadi::Function::index_out().
{
     return grad(f, iind, f.index_out(oname));
   }
MX casadi::MX::grad (const Function & f, const std::string & iname, const std::string & oname) static
Definition at line 1724 of file mx.cpp.
References casadi::Function::index_in(), and casadi::Function::index_out().
{
     return grad(f, f.index_in(iname), f.index_out(oname));
   }
MX casadi::MX::gradient (const MX & f, const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1538 of file mx.cpp.
{
     Function temp("helper_gradient_MX", {x}, {f});
     return MX::grad(temp);
   }
MX casadi::MX::graph_substitute (const MX & x, const std::vector< MX > & v, const std::vector< MX > & vdef) static
Functions called by friend functions defined for this class
Definition at line 1293 of file mx.cpp.
{
     return graph_substitute(std::vector<MX>{x}, v, vdef).at(0);
   }
std::vector< MX > casadi::MX::graph_substitute (const std::vector< MX > & ex, const std::vector< MX > & expr, const std::vector< MX > & exprs) static
Functions called by friend functions defined for this class
Definition at line 1298 of file mx.cpp.
References casadi::MXFunction::algorithm_, casadi::OP_INPUT, casadi::OP_OUTPUT, and casadi::OP_PARAMETER.
{
     casadi_assert_message(expr.size()==exprs.size(),
                           "Mismatch in the number of expression to substitute: "
                           << expr.size() << " <-> " << exprs.size() << ".");
     // Sort the expression
     Function f("tmp", vector<MX>{}, ex);
     auto *ff = dynamic_cast<MXFunction *>(f.get());
     // Get references to the internal data structures
     const vector<MXAlgEl>& algorithm = ff->algorithm_;
     vector<MX> swork(ff->workloc_.size()-1);
     // A boolean vector indicated whoch nodes are tainted by substitutions
     vector<bool> tainted(swork.size());
     // Temporary stringstream
     stringstream ss;
     // Construct lookup table for expressions
     std::map<const MXNode*, int> expr_lookup;
     for (int i=0;i<expr.size();++i) {
       expr_lookup[expr[i].operator->()] = i;
     }
     // Construct found map
     std::vector<bool> expr_found(expr.size());
     // Allocate output vector
     vector<MX> f_out(f.n_out());
     vector<MX> oarg, ores;
     // expr_lookup iterator
     std::map<const MXNode*, int>::const_iterator it_lookup;
     for (auto it=algorithm.begin(); it!=algorithm.end(); ++it) {
       if (!(it->data).is_null()) {
         // Check if it->data points to a supplied expr
         it_lookup = expr_lookup.find((it->data).operator->());
         if (it->res.front()>=0 && it_lookup!=expr_lookup.end()) {
           // Fill in that expression in-place
           swork[it->res.front()] = exprs[it_lookup->second];
           tainted[it->res.front()] = true;
           expr_found[it_lookup->second] = true;
           continue;
         }
       }
       switch (it->op) {
       case OP_INPUT:
         tainted[it->res.front()] = false;
       case OP_PARAMETER:
         swork[it->res.front()] = it->data;
         tainted[it->res.front()] = false;
         break;
       case OP_OUTPUT:
         f_out[it->res.front()] = swork[it->arg.front()];
         break;
       default:
         {
           bool node_tainted = false;
           // Arguments of the operation
           oarg.resize(it->arg.size());
           for (int i=0; i<oarg.size(); ++i) {
             int el = it->arg[i];
             if (el>=0) node_tainted =  node_tainted || tainted[el];
             oarg[i] = el<0 ? MX(it->data->dep(i).size()) : swork.at(el);
           }
           // Perform the operation
           ores.resize(it->res.size());
           if (it->res.size()==1 && it->res[0]>=0 && !node_tainted) {
             ores.at(0) = it->data;
           } else {
             const_cast<MX&>(it->data)->eval_mx(oarg, ores);
           }
           // Get the result
           for (int i=0; i<ores.size(); ++i) {
             int el = it->res[i];
             if (el>=0) swork.at(el) = ores[i];
             if (el>=0) tainted[el] = node_tainted;
           }
         }
       }
     }
     bool all_found=true;
     for (int i=0;i<expr.size();++i) {
       all_found = all_found && expr_found[i];
     }
     //casadi_assert_message(all_found,
     //             "MXFunction::extractNodes(const std::vector<MX>& expr):"
     //             " failed to locate all input expr."
     //             << std::endl << "Here's a boolean list showing which ones where found: "
     //             << expr_found);
     return f_out;
   }
bool casadi::MX::has_duplicates ()
Definition at line 787 of file mx.cpp.
References casadi::MXNode::has_duplicates().
{
     return (*this)->has_duplicates();
   }
MX casadi::MX::hessian (const MX & f, const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1548 of file mx.cpp.
{
     MX g;
     return hessian(f, x, g);
   }
MX casadi::MX::hessian (const MX & f, const MX & x, MX & g) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1553 of file mx.cpp.
{
     g = gradient(f, x);
     Function gfcn("gfcn", {x}, {g});
     return MX::jac(gfcn, 0, 0, false, true);
   }
MX casadi::MX::horzcat (const std::vector< MX > & x) static
Functions called by friend functions defined for SparsityInterface
Definition at line 851 of file mx.cpp.
References casadi::has_empty(), and casadi::trim_empty().
{
     // Check dimensions
     if (x.size()>1) {
       vector<MX> ne = trim_empty(x, true);
       for (int i=0;i<ne.size();i++) {
         casadi_assert_message(ne[i].size1()==ne[0].size1(),
                       "horzcat dimension mismatch  " <<
                       "x[" << i << "]:" << ne[i].dim() <<
                       " and x[0]: " << ne[0].dim() << ".");
       }
     }
     if (x.empty()) {
       return MX();
     } else if (x.size()==1) {
       return x.front();
     } else if (has_empty(x)) {
       std::vector<MX> ret = trim_empty(x);
       if (ret.empty()) {
         // We still want horzcat(zeros(0,5),zeros(0,5)) -> zeros(0,10)
         ret = trim_empty(x, true);
         int s = 0;
         for (int i=0;i<ret.size();++i) {
           s+= ret[i].size2();
         }
         return MX::zeros(0, s);
       } else {
         return horzcat(ret);
       }
     } else {
       return x.front()->getHorzcat(x);
     }
   }
static std::vector<MX > casadi::SparsityInterface< MX >::horzsplit (const MX & x, int incr) static inherited
std::vector< MX > casadi::MX::horzsplit (const MX & x, const std::vector< int > & offset) static
Functions called by friend functions defined for SparsityInterface
Definition at line 949 of file mx.cpp.
References casadi::MXNode::getHorzsplit(), casadi::isMonotone(), and casadi::GenericMatrix< MatType >::size2().
{
     // Consistency check
     casadi_assert(offset.size()>=1);
     casadi_assert(offset.front()==0);
     casadi_assert(offset.back()==x.size2());
     casadi_assert(isMonotone(offset));
     // Trivial return if possible
     if (offset.size()==1) {
       return vector<MX>(0);
     } else if (offset.size()==2) {
       return vector<MX>(1, x);
     } else {
       return x->getHorzsplit(offset);
     }
   }
MX casadi::MX::if_else (const MX & cond, const MX & if_true, const MX & if_false, bool short_circuit = true) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1069 of file mx.cpp.
References casadi::if_else_zero().
{
     if (short_circuit) {
       // Get symbolic primitives
       vector<MX> arg = symvar(veccat(vector<MX>{x_true, x_false}));
       // Form functions for cases
       Function f_true("f_true", arg, {x_true});
       Function f_false("f_false", arg, {x_false});
       // Form Switch
       Function sw = Function::if_else("switch", f_true, f_false);
       // Call the Switch
       vector<MX> sw_arg;
       sw_arg.push_back(cond);
       sw_arg.insert(sw_arg.end(), arg.begin(), arg.end());
       return sw(sw_arg).at(0);
     } else {
       return if_else_zero(cond, x_true) + if_else_zero(!cond, x_false);
     }
   }
MX casadi::MX::inf (const Sparsity & sp) static
Definition at line 501 of file mx.cpp.
{
     return create(ConstantMX::create(sp, numeric_limits<double>::infinity()));
   }
MX casadi::MX::inf (int nrow = 1, int ncol = 1) static
Definition at line 493 of file mx.cpp.
References casadi::inf.
{
     return inf(Sparsity::dense(nrow, ncol));
   }
MX casadi::MX::inf (const std::pair< int, int > & rc) static
Definition at line 497 of file mx.cpp.
References casadi::inf.
{
     return inf(rc.first, rc.second);
   }
MX casadi::MX::inv (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1571 of file mx.cpp.
References casadi::MXNode::getInverse().
{
     return x->getInverse();
   }
static MX casadi::GenericMatrix< MX >::inv_skew (const MX & a) static inherited
bool casadi::MX::is_binary () const
Definition at line 671 of file mx.cpp.
Referenced by is_commutative().
 { return (*this)->is_binaryOp();}
bool casadi::MX::is_call () const
Definition at line 653 of file mx.cpp.
References casadi::OP_CALL.
 { return (*this)->op()==OP_CALL; }
bool casadi::GenericMatrix< MX >::is_column () const inline inherited
Definition at line 133 of file generic_matrix.hpp.
 { return sparsity().is_column();}
bool casadi::MX::is_commutative () const
Definition at line 683 of file mx.cpp.
References is_binary(), is_unary(), and op().
{
     if (is_unary()) return true;
     casadi_assert_message(is_binary() || is_unary(),
                           "MX::is_commutative: must be binary or unary operation");
     return operation_checker<CommChecker>(op());
   }
bool casadi::MX::is_constant () const
Definition at line 652 of file mx.cpp.
References casadi::OP_CONST.
Referenced by casadi::ConstantMX::getDot(), casadi::Constant< Value >::getSetNonzeros(), and MX().
 { return (*this)->op()==OP_CONST; }
bool casadi::GenericMatrix< MX >::is_dense () const inline inherited
Definition at line 118 of file generic_matrix.hpp.
 { return sparsity().is_dense();}
bool casadi::GenericMatrix< MX >::is_empty (bool both = false) const inline inherited
Definition at line 115 of file generic_matrix.hpp.
 { return sparsity().is_empty(both);}
bool casadi::MX::is_equal (const MX & x, const MX & y, int depth = 0) static
Functions called by friend functions defined for GenericExpression
Definition at line 679 of file mx.cpp.
References get(), and casadi::MXNode::is_equal().
Referenced by casadi::UnaryMX::getBinary(), casadi::BinaryMX< ScX, ScY >::getBinary(), and casadi::BinaryMX< ScX, ScY >::is_equal().
{
     return MXNode::is_equal(x.get(), y.get(), depth);
   }
bool casadi::MX::is_identity () const
Definition at line 795 of file mx.cpp.
Referenced by mac().
{
     return (*this)->is_identity();
   }
bool casadi::MX::is_minus_one () const
Definition at line 811 of file mx.cpp.
{
     return (*this)->isValue(-1);
   }
bool casadi::MX::is_multiplication () const
Definition at line 657 of file mx.cpp.
References casadi::OP_MTIMES.
 { return (*this)->op()==OP_MTIMES; }
bool casadi::MX::is_norm () const
Definition at line 658 of file mx.cpp.
 { return dynamic_cast<const Norm*>(get())!=0; }
bool casadi::SharedObject::is_null () const inherited
Definition at line 84 of file shared_object.cpp.
Referenced by casadi::FunctionInternal::alloc(), casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::Integrator::fun2problem(), casadi::Switch::generateBody(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), casadi::SundialsInterface::getBandwidth(), casadi::SundialsInterface::getBandwidthB(), casadi::FunctionInternal::getPartition(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Newton::init(), casadi::Integrator::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::FixedStepIntegrator::init(), casadi::CvodesInterface::init_memory(), casadi::IdasInterface::init_memory(), casadi::FixedStepIntegrator::init_memory(), casadi::CvodesInterface::initIterativeLinsol(), casadi::IdasInterface::initIterativeLinsol(), casadi::CvodesInterface::initIterativeLinsolB(), casadi::IdasInterface::initIterativeLinsolB(), casadi::CvodesInterface::initUserDefinedLinsol(), casadi::IdasInterface::initUserDefinedLinsol(), casadi::CvodesInterface::initUserDefinedLinsolB(), casadi::IdasInterface::initUserDefinedLinsolB(), casadi::Integrator::Integrator(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::Linsol(), casadi::SparsityInternal::maxTransversal(), casadi::operator<<(), casadi::IdasInterface::psolveB(), casadi::Qpsol::Qpsol(), casadi::SnoptInterface::set_work(), casadi::RkIntegrator::setupFG(), casadi::CollocationIntegrator::setupFG(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Integrator::spAdj(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), casadi::Integrator::spFwd(), casadi::FunctionInternal::spFwd(), casadi::Callback::transfer_ownership(), casadi::Sparsity::uni_coloring(), casadi::SnoptInterface::userfun(), and casadi::Callback::~Callback().
{
     return node==0;
   }
bool casadi::MX::is_one () const
Definition at line 807 of file mx.cpp.
{
     return (*this)->is_one();
   }
bool casadi::MX::is_op (int op) const
Definition at line 656 of file mx.cpp.
References op().
 { return (*this)->op()==op; }
bool casadi::MX::is_output () const
Definition at line 654 of file mx.cpp.
 { return (*this)->isOutputNode(); }
bool casadi::MX::is_regular () const
Definition at line 819 of file mx.cpp.
References casadi::Matrix< Scalar >::is_regular().
{
     if (is_constant()) {
       return static_cast<DM>(*this).is_regular();
     } else {
       casadi_error("Cannot check regularity for symbolic MX");
     }
   }
bool casadi::GenericMatrix< MX >::is_row () const inline inherited
Definition at line 130 of file generic_matrix.hpp.
 { return sparsity().is_row();}
bool casadi::GenericMatrix< MX >::is_scalar (bool scalar_and_dense = false) const inherited
bool casadi::GenericMatrix< MX >::is_square () const inline inherited
Definition at line 124 of file generic_matrix.hpp.
 { return sparsity().is_square();}
bool casadi::MX::is_symbolic () const
Definition at line 651 of file mx.cpp.
References casadi::OP_PARAMETER.
Referenced by casadi::DaeBuilder::der().
 { return (*this)->op()==OP_PARAMETER; }
bool casadi::MX::is_transpose () const
Definition at line 815 of file mx.cpp.
References casadi::OP_TRANSPOSE.
{
     return op()==OP_TRANSPOSE;
   }
bool casadi::GenericMatrix< MX >::is_tril () const inline inherited
Definition at line 139 of file generic_matrix.hpp.
 { return sparsity().is_tril();}
bool casadi::GenericMatrix< MX >::is_triu () const inline inherited
Definition at line 136 of file generic_matrix.hpp.
 { return sparsity().is_triu();}
bool casadi::MX::is_unary () const
Definition at line 673 of file mx.cpp.
Referenced by is_commutative().
 { return (*this)->is_unaryOp();}
bool casadi::MX::is_valid_input () const
Definition at line 754 of file mx.cpp.
Referenced by casadi::DaeBuilder::attribute(), casadi::DaeBuilder::nominal(), casadi::DaeBuilder::set_attribute(), casadi::DaeBuilder::set_nominal(), and casadi::DaeBuilder::unit().
{
     return (*this)->is_valid_input();
   }
bool casadi::GenericMatrix< MX >::is_vector () const inline inherited
Definition at line 127 of file generic_matrix.hpp.
 { return sparsity().is_vector();}
bool casadi::MX::is_zero () const
Definition at line 799 of file mx.cpp.
Referenced by mac().
{
     if (nnz()==0) {
       return true;
     } else {
       return (*this)->is_zero();
     }
   }
MX casadi::MX::jac (const Function & f, int iind = 0, int oind = 0, bool compact = false, bool symmetric = false) static
Definition at line 1689 of file mx.cpp.
References casadi::FunctionInternal::jac_mx().
Referenced by casadi::FunctionInternal::getFullJacobian(), and casadi::Scpgen::init().
{
     return Function(f)->jac_mx(iind, oind, compact, symmetric);
   }
MX casadi::MX::jac (const Function & f, const std::string & iname, int oind = 0, bool compact = false, bool symmetric = false) static
Definition at line 1701 of file mx.cpp.
References casadi::Function::index_in().
{
     return jac(f, f.index_in(iname), oind, compact, symmetric);
   }
MX casadi::MX::jac (const Function & f, int iind, const std::string & oname, bool compact = false, bool symmetric = false) static
Definition at line 1706 of file mx.cpp.
References casadi::Function::index_out().
{
     return jac(f, iind, f.index_out(oname), compact, symmetric);
   }
MX casadi::MX::jac (const Function & f, const std::string & iname, const std::string & oname, bool compact = false, bool symmetric = false) static
Definition at line 1711 of file mx.cpp.
References casadi::Function::index_in(), and casadi::Function::index_out().
{
     return jac(f, f.index_in(iname), f.index_out(oname), compact, symmetric);
   }
MX casadi::MX::jacobian (const MX & f, const MX & x, bool symmetric = false) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1533 of file mx.cpp.
{
     Function temp("helper_jacobian_MX", {x}, {f});
     return MX::jac(temp, 0, 0, false, symmetric);
   }
MX casadi::MX::join_primitives (std::vector< MX > & v) const
Definition at line 779 of file mx.cpp.
References casadi::MXNode::join_primitives().
{
     casadi_assert_message(v.size()==n_primitives(), "Wrong number of primitives supplied");
     std::vector<MX>::const_iterator it=v.begin();
     MX ret = (*this)->join_primitives(it);
     casadi_assert(it==v.end());
     return ret;
   }
MX casadi::MX::jtimes (const MX & ex, const MX & arg, const MX & v, bool tr = false) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1559 of file mx.cpp.
References casadi::_jtimes().
{
     return _jtimes(ex, arg, v, tr);
   }
MX casadi::MX::kron (const MX & x, const MX & b) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1611 of file mx.cpp.
References casadi::Sparsity::get_nz(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), and sparsity().
{
     const Sparsity &a_sp = a.sparsity();
     MX filler(b.size());
     std::vector< std::vector< MX > > blocks(a.size1(), std::vector< MX >(a.size2(), filler));
     for (int i=0; i<a.size1(); ++i) {
       for (int j=0; j<a.size2(); ++j) {
         int k = a_sp.get_nz(i, j);
         if (k!=-1) {
           blocks[i][j] = a[k]*b;
         }
       }
     }
     return blockcat(blocks);
   }
MX casadi::MX::lift (const MX & x, const MX & x_guess) static
Functions called by friend functions defined for this class
Definition at line 625 of file mx.cpp.
References casadi::MXNode::getBinary(), casadi::OP_LIFT, and sparsity().
{
     casadi_assert(x.sparsity()==x_guess.sparsity());
     return x->getBinary(OP_LIFT, x_guess, false, false);
   }
static MX casadi::GenericMatrix< MX >::linspace (const MX & a, const MX & b, int nsteps) static inherited
static MX casadi::MX::logic_not (const MX & x) static
Functions called by friend functions defined for GenericMatrix
MX casadi::MX::mac (const MX & x, const MX & y, const MX & z) static
Functions called by friend functions defined for SparsityInterface
Definition at line 583 of file mx.cpp.
References casadi::GenericMatrix< MatType >::dim(), casadi::MXNode::getMultiplication(), is_identity(), casadi::GenericMatrix< MatType >::is_scalar(), is_zero(), casadi::GenericMatrix< MatType >::size1(), and casadi::GenericMatrix< MatType >::size2().
Referenced by mtimes().
{
     if (x.is_scalar() || y.is_scalar()) {
       // Use element-wise multiplication if at least one factor scalar
       return z + x*y;
     }
     // Check matching dimensions
     casadi_assert_message(x.size2()==y.size1(),
                           "Matrix product with incompatible dimensions. Lhs is "
                           << x.dim() << " and rhs is " << y.dim() << ".");
     // Check if we can simplify the product
     if (x.is_identity()) {
       return y + z;
     } else if (y.is_identity()) {
       return x + z;
     } else if (x.is_zero() || y.is_zero()) {
       return z;
     } else {
       return x->getMultiplication(y, z);
     }
   }
Matrix< int > casadi::MX::mapping () const
Definition at line 690 of file mx.cpp.
Referenced by erase().
{
     return (*this)->mapping();
   }
MX casadi::MX::matrix_expand (const MX & e, const std::vector< MX > & boundary, const Dict & options) static
Functions called by friend functions defined for this class
Definition at line 1580 of file mx.cpp.
{
     return matrix_expand(vector<MX>{e}, boundary, options).at(0);
   }
std::vector< MX > casadi::MX::matrix_expand (const std::vector< MX > & e, const std::vector< MX > & boundary, const Dict & options) static
Functions called by friend functions defined for this class
Definition at line 1584 of file mx.cpp.
References casadi::Function::call(), casadi::Function::expand(), and casadi::Function::name().
{
     // Create symbols for boundary nodes
     std::vector<MX> syms(boundary.size());
     for (int i=0;i<syms.size();++i) {
       syms[i] = MX::sym("x", boundary[i].sparsity());
     }
     // Substitute symbols for boundary nodes
     std::vector<MX> ret = graph_substitute(e, boundary, syms);
     // Obtain list of dependents
     std::vector<MX> v = symvar(veccat(ret));
     // Construct an MXFunction with it
     Function f("tmp", v, ret);
     // Expand to SXFunction
     Function s = f.expand("expand_" + f.name(), options);
     std::vector<MX> r;
     s.call(graph_substitute(v, syms, boundary), r, true);
     return r;
   }
MX casadi::MX::mldivide (const MX & a, const MX & b) static
Functions called by friend functions defined for GenericMatrix
Definition at line 635 of file mx.cpp.
References casadi::GenericMatrix< MatType >::is_scalar().
{
     casadi_assert_message(a.is_scalar() || b.is_scalar(), "Not implemented");
     return b/a;
   }
MX casadi::MX::monitor (const std::string & comment) const
Definition at line 621 of file mx.cpp.
References casadi::MXNode::getMonitor().
{
     return(*this)->getMonitor(comment);
   }
MX casadi::MX::mpower (const MX & a, const MX & b) static
Functions called by friend functions defined for GenericMatrix
Definition at line 640 of file mx.cpp.
References casadi::GenericMatrix< MatType >::is_scalar(), and casadi::GenericExpression< MX >::pow.
{
     casadi_assert_message(a.is_scalar() || b.is_scalar(), "Not implemented");
     return pow(a, b);
   }
MX casadi::MX::mrdivide (const MX & a, const MX & b) static
Functions called by friend functions defined for GenericMatrix
Definition at line 630 of file mx.cpp.
References casadi::GenericMatrix< MatType >::is_scalar().
{
     casadi_assert_message(a.is_scalar() || b.is_scalar(), "Not implemented");
     return a/b;
   }
static MX casadi::SparsityInterface< MX >::mtimes (const std::vector< MX > & args) static inherited
MX casadi::MX::mtimes (const MX & x, const MX & y) static
Functions called by friend functions defined for SparsityInterface
Definition at line 573 of file mx.cpp.
References casadi::GenericMatrix< MatType >::is_scalar(), mac(), casadi::Sparsity::mtimes(), sparsity(), and casadi::GenericMatrix< MX >::zeros().
{
     if (x.is_scalar() || y.is_scalar()) {
       // Use element-wise multiplication if at least one factor scalar
       return x*y;
     } else {
       MX z = MX::zeros(Sparsity::mtimes(x.sparsity(), y.sparsity()));
       return mac(x, y, z);
     }
   }
int casadi::MX::n_dep () const
Definition at line 647 of file mx.cpp.
 { return (*this)->ndep(); }
int casadi::MX::n_nodes (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1171 of file mx.cpp.
References casadi::Function::n_nodes().
{
     Function f("tmp", vector<MX>{}, {x});
     return f.n_nodes();
   }
int casadi::MX::n_out () const
Definition at line 702 of file mx.cpp.
                       {
     return (*this)->nout();
   }
int casadi::MX::n_primitives () const
Definition at line 758 of file mx.cpp.
{
     casadi_assert_message(is_valid_input(), "Not a valid input expression");
     return (*this)->n_primitives();
   }
std::string casadi::MX::name () const
Definition at line 649 of file mx.cpp.
 { return (*this)->name(); }
MX casadi::MX::nan (const Sparsity & sp) static
Definition at line 513 of file mx.cpp.
{
     return create(ConstantMX::create(sp, numeric_limits<double>::quiet_NaN()));
   }
MX casadi::MX::nan (int nrow = 1, int ncol = 1) static
Definition at line 505 of file mx.cpp.
References casadi::nan.
{
     return nan(Sparsity::dense(nrow, ncol));
   }
MX casadi::MX::nan (const std::pair< int, int > & rc) static
Definition at line 509 of file mx.cpp.
References casadi::nan.
{
     return nan(rc.first, rc.second);
   }
std::vector< bool > casadi::MX::nl_var (const MX & expr, const MX & var) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1563 of file mx.cpp.
References casadi::_nl_var().
{
     return _nl_var(expr, var);
   }
int casadi::GenericMatrix< MX >::nnz () const inherited
Referenced by enlarge(), and erase().
int casadi::GenericMatrix< MX >::nnz_diag () const inherited
int casadi::GenericMatrix< MX >::nnz_lower () const inherited
int casadi::GenericMatrix< MX >::nnz_upper () const inherited
static int casadi::GenericMatrix< MX >::norm_0_mul (const MX & x, const MX & y) inline static inherited
Definition at line 176 of file generic_matrix.hpp.
{
       return Sparsity::norm_0_mul(x.sparsity(), y.sparsity());
     }
MX casadi::MX::norm_1 (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1039 of file mx.cpp.
References casadi::MXNode::getNorm1().
{
     return x->getNorm1();
   }
MX casadi::MX::norm_2 (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1027 of file mx.cpp.
References casadi::MXNode::getNorm2(), and casadi::GenericMatrix< MatType >::is_column().
{
     if (x.is_column()) {
       return norm_F(x);
     } else {
       return x->getNorm2();
     }
   }
MX casadi::MX::norm_F (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1035 of file mx.cpp.
References casadi::MXNode::getNormF().
{
     return x->getNormF();
   }
MX casadi::MX::norm_inf (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1043 of file mx.cpp.
References casadi::MXNode::getNormInf().
{
     return x->getNormInf();
   }
MX casadi::MX::nullspace (const MX & A) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1653 of file mx.cpp.
References sparsity().
{
     SX A_sx = SX::sym("A", A.sparsity());
     Function f("nullspace", {A_sx}, {SX::nullspace(A_sx)});
     return f(A).at(0);
   }
int casadi::GenericMatrix< MX >::numel () const inherited
int casadi::GenericMatrix< MX >::numel (int i) const inline inherited
Definition at line 94 of file generic_matrix.hpp.
 { return 1;}
int casadi::MX::numFunctions () const
Definition at line 660 of file mx.cpp.
 { return (*this)->numFunctions(); }
static std::vector<int> casadi::SparsityInterface< MX >::offset (const std::vector< MX > & v, bool vert = true) static inherited
static MX casadi::GenericMatrix< MX >::ones (int nrow = 1, int ncol = 1) inline static inherited
Definition at line 658 of file generic_matrix.hpp.
Referenced by casadi::UnaryMX::getBinary(), and casadi::Constant< Value >::getBinary().
 { return ones(Sparsity::dense(nrow, ncol)); }
static MX casadi::GenericMatrix< MX >::ones (const Sparsity & sp) inline static inherited
Definition at line 659 of file generic_matrix.hpp.
 { return MatType(sp, 1, false);}
static MX casadi::GenericMatrix< MX >::ones (const std::pair< int, int > & rc) inline static inherited
Definition at line 660 of file generic_matrix.hpp.
 { return ones(rc.first, rc.second);}
int casadi::MX::op () const
Definition at line 675 of file mx.cpp.
Referenced by casadi::UnaryMX::getBinary(), is_commutative(), and is_op().
                    {
     return (*this)->op();
   }
casadi::MX::operator double () const explicit
Definition at line 663 of file mx.cpp.
{
     return (*this)->to_double();
   }
casadi::MX::operator Matrix< double > () const explicit
Definition at line 667 of file mx.cpp.
{
     return (*this)->getMatrixValue();
   }
MX casadi::GenericExpression< MX >::operator! () const inline inherited
Definition at line 325 of file generic_expression.hpp.
{
       return ExType::unary(OP_NOT, self());
     }
const MX casadi::GenericMatrix< MX >::operator() (const RR & rr) const inline inherited
Definition at line 212 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr);
       return ret;
     }
const MX casadi::GenericMatrix< MX >::operator() (const RR & rr, const CC & cc) const inline inherited
Definition at line 220 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr, cc);
       return ret;
     }
SubIndex<MX , RR> casadi::GenericMatrix< MX >::operator() (const RR & rr) inline inherited
Definition at line 228 of file generic_matrix.hpp.
{
       return SubIndex<MatType, RR>(self(), rr);
     }
SubMatrix<MX , RR, CC> casadi::GenericMatrix< MX >::operator() (const RR & rr, const CC & cc) inline inherited
Definition at line 234 of file generic_matrix.hpp.
{
       return SubMatrix<MatType, RR, CC>(self(), rr, cc);
     }
MX & casadi::GenericExpression< MX >::operator*= (const MX & y) inline inherited
Definition at line 316 of file generic_expression.hpp.
 {return self() = self() * y;}
MX & casadi::GenericExpression< MX >::operator+= (const MX & y) inline inherited
Definition at line 310 of file generic_expression.hpp.
 { return self() = self() + y; }
MX casadi::MX::operator- () const
Definition at line 521 of file mx.cpp.
References casadi::MXNode::dep(), casadi::MXNode::getUnary(), and casadi::OP_NEG.
{
     if ((*this)->op()==OP_NEG) {
       return (*this)->dep(0);
     } else {
       return (*this)->getUnary(OP_NEG);
     }
   }
MX & casadi::GenericExpression< MX >::operator-= (const MX & y) inline inherited
Definition at line 313 of file generic_expression.hpp.
 { return self() = self() - y; }
MXNode * casadi::MX::operator-> ()
Definition at line 485 of file mx.cpp.
{
     return static_cast<MXNode*>(SharedObject::operator->());
   }
const MXNode * casadi::MX::operator-> () const
Definition at line 489 of file mx.cpp.
{
     return static_cast<const MXNode*>(SharedObject::operator->());
   }
MX & casadi::GenericExpression< MX >::operator/= (const MX & y) inline inherited
Definition at line 319 of file generic_expression.hpp.
 {return self() = self() / y;}
const MX casadi::GenericMatrix< MX >::operator[] (const K & k) const inline inherited
Definition at line 198 of file generic_matrix.hpp.
{
       MatType ret;
       self().get_nz(ret, false, k);
       return ret;
     }
NonZeros<MX , K> casadi::GenericMatrix< MX >::operator[] (const K & k) inline inherited
Definition at line 206 of file generic_matrix.hpp.
{
       return NonZeros<MatType, K>(self(), k);
     }
MX casadi::MX::pinv (const MX & A, const std::string & lsolver = "symbolicqr", const Dict & dict = Dict()) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1645 of file mx.cpp.
References casadi::mtimes(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), and T().
{
     if (A.size1()>=A.size2()) {
       return solve(mtimes(A.T(), A), A.T(), lsolver, dict);
     } else {
       return solve(mtimes(A, A.T()), A, lsolver, dict).T();
     }
   }
MX casadi::MX::polyval (const MX & p, const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1184 of file mx.cpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_dense(), and casadi::GenericMatrix< MatType >::nnz().
{
     casadi_assert_message(p.is_dense(), "polynomial coefficients vector must be a vector");
     casadi_assert_message(p.is_column() && p.nnz()>0, "polynomial coefficients must be a vector");
     MX ret = p[0];
     for (int i=1; i<p.nnz(); ++i) {
       ret = ret*x + p[i];
     }
     return ret;
   }
std::vector< MX > casadi::MX::primitives () const
Definition at line 763 of file mx.cpp.
Referenced by casadi::DaeBuilder::attribute(), casadi::DaeBuilder::nominal(), casadi::DaeBuilder::set_attribute(), casadi::DaeBuilder::set_nominal(), and casadi::DaeBuilder::unit().
{
     std::vector<MX> ret(n_primitives());
     std::vector<MX>::iterator it=ret.begin();
     (*this)->primitives(it);
     casadi_assert(it==ret.end());
     return ret;
   }
void casadi::SharedObject::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 135 of file shared_object.cpp.
Referenced by casadi::CsparseInterface::linsol_factorize().
{
     if (is_null()) {
       stream << "Null pointer of class \"" << typeid(this).name() << "\"";
     } else {
       (*this)->print(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
std::string casadi::MX::print_operator (const MX & x, const std::vector< std::string > & args) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1194 of file mx.cpp.
References casadi::MXNode::print().
{
     return x->print(args);
   }
MX casadi::MX::printme (const MX & y) const
Definition at line 610 of file mx.cpp.
References binary(), and casadi::OP_PRINTME.
{
     return binary(OP_PRINTME, *this, b);
   }
void casadi::SharedObject::printPtr (std::ostream & stream = casadi::userOut()) const inherited
Print the pointer to the internal class
Definition at line 144 of file shared_object.cpp.
{
     stream << node;
   }
MX casadi::MX::project (const MX & x, const Sparsity & sp, bool intersect = false) static
Functions called by friend functions defined for GenericMatrix
Definition at line 710 of file mx.cpp.
References casadi::MXNode::getProject(), casadi::Sparsity::intersect(), casadi::GenericMatrix< MatType >::is_empty(), and sparsity().
Referenced by densify().
{
     if (x.is_empty() || (sp==x.sparsity())) {
       return x;
     } else {
       if (intersect) {
         return x->getProject(sp.intersect(x.sparsity()));
       } else {
         return x->getProject(sp);
       }
     }
   }
static MX casadi::GenericMatrix< MX >::rank1 (const MX & A, const MX & alpha, const MX & x, const MX & y) static inherited
static MX casadi::SparsityInterface< MX >::repmat (const MX & A, const std::pair< int, int > & rc) inline static inherited
Definition at line 179 of file sparsity_interface.hpp.
{
       return MatType::repmat(A, rc.first, rc.second);
     }
MX casadi::MX::repmat (const MX & x, int n, int m = 1) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1626 of file mx.cpp.
References casadi::MXNode::getRepmat().
Referenced by densify().
{
     if (n==0 || m==0) {
       return MX();
     } else if (n==1 && m==1) {
       return x;
     } else {
       return x->getRepmat(n, m);
     }
   }
void casadi::SharedObject::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 121 of file shared_object.cpp.
{
     if (is_null()) {
       stream << 0;
     } else {
       (*this)->repr(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
MX casadi::MX::repsum (const MX & x, int n, int m = 1) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1636 of file mx.cpp.
References casadi::MXNode::getRepsum().
{
     return x->getRepsum(n, m);
   }
void casadi::MX::resetInput ()
Definition at line 791 of file mx.cpp.
                       {
     (*this)->resetInput();
   }
MX casadi::MX::reshape (const MX & x, int nrow, int ncol) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1053 of file mx.cpp.
References casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), and sparsity().
{
     // Quick return if trivial
     if (nrow==x.size1() && ncol==x.size2()) return x;
     // Reshape the sparsity pattern
     return reshape(x, Sparsity::reshape(x.sparsity(), nrow, ncol));
   }
MX casadi::MX::reshape (const MX & x, const Sparsity & sp) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1061 of file mx.cpp.
References casadi::MXNode::getReshape(), and sparsity().
{
     // Quick return if trivial
     if (sp==x.sparsity()) return x;
     // Call internal method
     return x->getReshape(sp);
   }
const int* casadi::GenericMatrix< MX >::row () const inline inherited
Definition at line 146 of file generic_matrix.hpp.
 { return sparsity().row(); }
int casadi::GenericMatrix< MX >::row (int el) const inline inherited
Definition at line 149 of file generic_matrix.hpp.
 { return sparsity().row(el); }
const MX & casadi::GenericExpression< MX >::self () const inline protected inherited
Definition at line 51 of file generic_expression.hpp.
 { return static_cast<const ExType&>(*this); }
const MX & casadi::SparsityInterface< MX >::self () const inline protected inherited
Definition at line 51 of file sparsity_interface.hpp.
 { return static_cast<const MatType&>(*this); }
MX & casadi::SparsityInterface< MX >::self () inline protected inherited
Definition at line 52 of file sparsity_interface.hpp.
 { return static_cast<MatType&>(*this); }
MX & casadi::GenericExpression< MX >::self () inline protected inherited
Definition at line 52 of file generic_expression.hpp.
 { return static_cast<ExType&>(*this); }
void casadi::MX::set (const MX & m, bool ind1, const Slice & rr)
Set a submatrix, single argument
Definition at line 274 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on IM
     set(m, ind1, rr.all(size1(), ind1));
   }
void casadi::MX::set (const MX & m, bool ind1, const Matrix< int > & rr)
Set a submatrix, single argument
Definition at line 279 of file mx.cpp.
References casadi::MXNode::getSetNonzeros(), casadi::inBounds(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< MatType >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::project(), casadi::simplify(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), sparsity(), casadi::Matrix< Scalar >::sparsity(), and T().
{
     // Assert dimensions of assigning matrix
     if (rr.sparsity() != m.sparsity()) {
       if (rr.size() == m.size()) {
         // Remove submatrix to be replaced
         erase(rr.nonzeros(), ind1);
         // Find the intersection between rr's and m's sparsity patterns
         Sparsity sp = rr.sparsity() * m.sparsity();
         // Project both matrices to this sparsity
         return set(project(m, sp), ind1, Matrix<int>::project(rr, sp));
       } else if (m.is_scalar()) {
         // m scalar means "set all"
         if (m.is_dense()) {
           return set(MX(rr.sparsity(), m), ind1, rr);
         } else {
           return set(MX(rr.size()), ind1, rr);
         }
       } else if (rr.size1() == m.size2() && rr.size2() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set(m.T(), ind1, rr);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch." << "lhs is " << rr.size()
                      << ", while rhs is " << m.size());
       }
     }
     // Dimensions of this
     int sz1 = size1(), sz2 = size2(), sz = nnz(), nel = numel(), rrsz = rr.nnz();
     // Quick return if nothing to set
     if (rrsz==0) return;
     // Check bounds
     if (!inBounds(rr.nonzeros(), -nel+ind1, nel+ind1)) {
       casadi_error("set[rr] out of bounds. Your rr contains "
                    << *std::min_element(rr->begin(), rr->end()) << " up to "
                    << *std::max_element(rr->begin(), rr->end())
                    << ", which is outside the range [" << -nel+ind1 << ","<< nel+ind1 <<  ").");
     }
     // Dense mode
     if (is_dense() && m.is_dense()) {
       return set_nz(m, ind1, rr);
     }
     // Construct new sparsity pattern
     std::vector<int> new_row=sparsity().get_row(), new_col=sparsity().get_col(), nz(rr.nonzeros());
     new_row.reserve(sz+rrsz);
     new_col.reserve(sz+rrsz);
     nz.reserve(rrsz);
     for (std::vector<int>::iterator i=nz.begin(); i!=nz.end(); ++i) {
       if (ind1) (*i)--;
       if (*i<0) *i += nel;
       new_row.push_back(*i % sz1);
       new_col.push_back(*i / sz1);
     }
     Sparsity sp = Sparsity::triplet(sz1, sz2, new_row, new_col);
     // If needed, update pattern
     if (sp != sparsity()) *this = project(*this, sp);
     // Find the nonzeros corresponding to rr
     sparsity().get_nz(nz);
     // Create a nonzero assignment node
     *this = simplify(m->getSetNonzeros(*this, nz));
   }
void casadi::MX::set (const MX & m, bool ind1, const Sparsity & sp)
Set a submatrix, single argument
Definition at line 351 of file mx.cpp.
References casadi::densify(), casadi::Sparsity::find(), casadi::GenericMatrix< MatType >::is_scalar(), and casadi::Sparsity::size().
{
     casadi_assert_message(size()==sp.size(),
                           "set(Sparsity sp): shape mismatch. This matrix has shape "
                           << size() << ", but supplied sparsity index has shape "
                           << sp.size() << ".");
     std::vector<int> ii = sp.find();
     if (m.is_scalar()) {
       (*this)(ii) = densify(m);
     } else {
       (*this)(ii) = densify(m(ii));
     }
   }
void casadi::MX::set (const MX & m, bool ind1, const Slice & rr, const Slice & cc)
Definition at line 189 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     set(m, ind1, rr.all(size1(), ind1), cc.all(size2(), ind1));
   }
void casadi::MX::set (const MX & m, bool ind1, const Slice & rr, const Matrix< int > & cc)
Definition at line 194 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     set(m, ind1, rr.all(size1(), ind1), cc);
   }
void casadi::MX::set (const MX & m, bool ind1, const Matrix< int > & rr, const Slice & cc)
Definition at line 199 of file mx.cpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     set(m, ind1, rr, cc.all(size2(), ind1));
   }
void casadi::MX::set (const MX & m, bool ind1, const Matrix< int > & rr, const Matrix< int > & cc)
Definition at line 204 of file mx.cpp.
References casadi::GenericMatrix< MatType >::colind(), casadi::inBounds(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< MatType >::row(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), sparsity(), casadi::Matrix< Scalar >::T(), and T().
{
     // Row vector rr (e.g. in MATLAB) is transposed to column vector
     if (rr.size1()==1 && rr.size2()>1) {
       return set(m, ind1, rr.T(), cc);
     }
     // Row vector cc (e.g. in MATLAB) is transposed to column vector
     if (cc.size1()==1 && cc.size2()>1) {
       return set(m, ind1, rr, cc.T());
     }
     // Make sure rr and cc are dense vectors
     casadi_assert_message(rr.is_dense() && rr.is_column(),
                           "MX::set: First index not dense vector");
     casadi_assert_message(cc.is_dense() && cc.is_column(),
                           "MX::set: Second index not dense vector");
     // Assert dimensions of assigning matrix
     if (rr.size1() != m.size1() || cc.size1() != m.size2()) {
       if (m.is_scalar()) {
         // m scalar means "set all"
         return set(repmat(m, rr.size1(), cc.size1()), ind1, rr, cc);
       } else if (rr.size1() == m.size2() && cc.size1() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set(m.T(), ind1, rr, cc);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch." << "lhs is " << rr.size1() << "-by-"
                      << cc.size1() << ", while rhs is " << m.size());
       }
     }
     // Dimensions
     int sz1 = size1(), sz2 = size2();
     // Report out-of-bounds
     if (!inBounds(rr.nonzeros(), -sz1+ind1, sz1+ind1)) {
       casadi_error("set[., rr, cc] out of bounds. Your rr contains "
                    << *std::min_element(rr->begin(), rr->end()) << " up to "
                    << *std::max_element(rr->begin(), rr->end())
                    << ", which is outside the range [" << -sz1+ind1 << ","<< sz1+ind1 <<  ").");
     }
     if (!inBounds(cc.nonzeros(), -sz2+ind1, sz2+ind1)) {
       casadi_error("set [., rr, cc] out of bounds. Your cc contains "
                    << *std::min_element(cc->begin(), cc->end()) << " up to "
                    << *std::max_element(cc->begin(), cc->end())
                    << ", which is outside the range [" << -sz2+ind1 << ","<< sz2+ind1 <<  ").");
     }
     // If we are assigning with something sparse, first remove existing entries
     if (!m.is_dense()) {
       erase(rr.nonzeros(), cc.nonzeros(), ind1);
     }
     // Collect all assignments
     IM el = IM::zeros(m.sparsity());
     for (int j=0; j<el.size2(); ++j) { // Loop over columns of m
       int this_j = cc->at(j) - ind1; // Corresponding column in this
       if (this_j<0) this_j += sz2;
       for (int k=el.colind(j); k<el.colind(j+1); ++k) { // Loop over rows of m
         int i = m.row(k);
         int this_i = rr->at(i) - ind1; // Corresponding row in this
         if (this_i<0) this_i += sz1;
         el->at(k) = this_i + this_j*sz1;
       }
     }
     return set(m, false, el);
   }
void casadi::MX::set_nz (const MX & m, bool ind1, const Slice & kk)
Set a set of nonzeros
Definition at line 407 of file mx.cpp.
References casadi::Slice::all().
{
     // Fallback on IM
     set_nz(m, ind1, kk.all(nnz(), ind1));
   }
void casadi::MX::set_nz (const MX & m, bool ind1, const Matrix< int > & kk)
Set a set of nonzeros
Definition at line 412 of file mx.cpp.
References casadi::MXNode::getSetNonzeros(), casadi::inBounds(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< MatType >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::project(), casadi::simplify(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), sparsity(), casadi::Matrix< Scalar >::sparsity(), and T().
{
     casadi_assert_message(kk.nnz()==m.nnz() || m.nnz()==1,
                           "MX::set_nz: length of non-zero indices (" << kk.nnz() << ") " <<
                           "must match size of rhs (" << m.nnz() << ").");
     // Assert dimensions of assigning matrix
     if (kk.sparsity() != m.sparsity()) {
       if (m.is_scalar()) {
         // m scalar means "set all"
         if (!m.is_dense()) return; // Nothing to set
         return set_nz(MX(kk.sparsity(), m), ind1, kk);
       } else if (kk.size() == m.size()) {
         // Project sparsity if needed
         return set_nz(project(m, kk.sparsity()), ind1, kk);
       } else if (kk.size1() == m.size2() && kk.size2() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set_nz(m.T(), ind1, kk);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch." << "lhs is " << kk.size()
                      << ", while rhs is " << m.size());
       }
     }
     // Call recursively if points both objects point to the same node
     if (this==&m) {
       MX m_copy = m;
       return set_nz(m_copy, ind1, kk);
     }
     // Check bounds
     int sz = nnz();
     if (!inBounds(kk.nonzeros(), -sz+ind1, sz+ind1)) {
       casadi_error("set_nz[kk] out of bounds. Your kk contains "
                    << *std::min_element(kk->begin(), kk->end()) << " up to "
                    << *std::max_element(kk->begin(), kk->end())
                    << ", which is outside the range [" << -sz+ind1 << ","<< sz+ind1 <<  ").");
     }
     // Quick return if no assignments to be made
     if (kk.nnz()==0) return;
     // Handle index-1, negative indices
     if (ind1 || *std::min_element(kk->begin(), kk->end())<0) {
       Matrix<int> kk_mod = kk;
       for (auto&& i : kk_mod.nonzeros()) {
         casadi_assert_message(!(ind1 && i<=0), "Matlab is 1-based, but requested index " <<
                               i <<  ". Note that negative slices are" <<
                               " disabled in the Matlab interface. " <<
                               "Possibly you may want to use 'end'.");
         if (ind1) i--;
         if (i<0) i += sz;
       }
       return set_nz(m, false, kk_mod); // Call recursively
     }
     // Create a nonzero assignment node
     *this = simplify(m->getSetNonzeros(*this, kk.nonzeros()));
   }
void casadi::MX::setEqualityCheckingDepth (int eq_depth = 1) static
Definition at line 737 of file mx.cpp.
{
     eq_depth_ = eq_depth;
   }
void casadi::MX::setTemp (int t)
Definition at line 698 of file mx.cpp.
{
     (*this)->temp = t;
   }
void casadi::MX::shared (std::vector< MX > & ex, std::vector< MX > & v, std::vector< MX > & vdef, const std::string & v_prefix, const std::string & v_suffix) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1405 of file mx.cpp.
References casadi::MXFunction::algorithm_, casadi::OP_CONST, casadi::OP_OUTPUT, casadi::OP_PARAMETER, casadi::MXNode::size(), and casadi::sort().
{
     // Sort the expression
     Function f("tmp", vector<MX>{}, ex);
     auto *ff = dynamic_cast<MXFunction *>(f.get());
     // Get references to the internal data structures
     const vector<MXAlgEl>& algorithm = ff->algorithm_;
     vector<MX> work(ff->workloc_.size()-1);
     // Count how many times an expression has been used
     vector<int> usecount(work.size(), 0);
     // Remember the origin of every calculation
     vector<pair<int, int> > origin(work.size(), make_pair(-1, -1));
     // Which evaluations to replace
     vector<pair<int, int> > replace;
     // Evaluate the algorithm to identify which evaluations to replace
     int k=0;
     for (vector<MXAlgEl>::const_iterator it=algorithm.begin(); it<algorithm.end(); ++it, ++k) {
       // Increase usage counters
       switch (it->op) {
       case OP_CONST:
       case OP_PARAMETER:
         break;
       default: // Unary operation, binary operation or output
         for (int c=0; c<it->arg.size(); ++c) {
           if (usecount[it->arg[c]]==0) {
             usecount[it->arg[c]]=1;
           } else if (usecount[it->arg[c]]==1) {
             replace.push_back(origin[it->arg[c]]);
             usecount[it->arg[c]]=-1; // Extracted, do not extract again
           }
         }
       }
       // Perform the operation
       switch (it->op) {
       case OP_OUTPUT:
         break;
       case OP_CONST:
       case OP_PARAMETER:
         usecount[it->res.front()] = -1; // Never extract since it is a primitive type
         break;
       default:
         for (int c=0; c<it->res.size(); ++c) {
           if (it->res[c]>=0) {
             work[it->res[c]] = it->data.getOutput(c);
             usecount[it->res[c]] = 0; // Not (yet) extracted
             origin[it->res[c]] = make_pair(k, c);
           }
         }
         break;
       }
     }
     // New variables and definitions
     v.clear();
     v.reserve(replace.size());
     vdef.clear();
     vdef.reserve(replace.size());
     // Quick return
     if (replace.empty()) return;
     // Sort the elements to be replaced in the order of appearence in the algorithm
     sort(replace.begin(), replace.end());
     vector<pair<int, int> >::const_iterator replace_it=replace.begin();
     // Name of intermediate variables
     stringstream v_name;
     // Arguments for calling the atomic operations
     vector<MX> oarg, ores;
     // Evaluate the algorithm
     k=0;
     for (vector<MXAlgEl>::const_iterator it=algorithm.begin(); it<algorithm.end(); ++it, ++k) {
       switch (it->op) {
       case OP_OUTPUT:     ex[it->res.front()] = work[it->arg.front()];      break;
       case OP_CONST:
       case OP_PARAMETER:  work[it->res.front()] = it->data; break;
       default:
         {
           // Arguments of the operation
           oarg.resize(it->arg.size());
           for (int i=0; i<oarg.size(); ++i) {
             int el = it->arg[i];
             oarg[i] = el<0 ? MX(it->data->dep(i).size()) : work.at(el);
           }
           // Perform the operation
           ores.resize(it->res.size());
           const_cast<MX&>(it->data)->eval_mx(oarg, ores);
           // Get the result
           for (int i=0; i<ores.size(); ++i) {
             int el = it->res[i];
             if (el>=0) work.at(el) = ores[i];
           }
           // Possibly replace results with new variables
           for (int c=0; c<it->res.size(); ++c) {
             int ind = it->res[c];
             if (ind>=0 && replace_it->first==k && replace_it->second==c) {
               // Store the result
               vdef.push_back(work[ind]);
               // Create a new variable
               v_name.str(string());
               v_name << v_prefix << v.size() << v_suffix;
               v.push_back(MX::sym(v_name.str()));
               // Use in calculations
               work[ind] = v.back();
               // Go to the next element to be replaced
               replace_it++;
             }
           }
         }
       }
     }
   }
MX casadi::MX::simplify (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1047 of file mx.cpp.
References casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::simplifyMe().
{
     MX ret = x;
     if (!ret.is_empty(true)) ret->simplifyMe(ret);
     return ret;
   }
std::pair<int, int> casadi::GenericMatrix< MX >::size () const inherited
int casadi::GenericMatrix< MX >::size (int axis) const inherited
int casadi::GenericMatrix< MX >::size1 () const inherited
int casadi::GenericMatrix< MX >::size2 () const inherited
static MX casadi::GenericMatrix< MX >::skew (const MX & a) static inherited
MX casadi::MX::solve (const MX & A, const MX & b, const std::string & lsolver = "symbolicqr", const Dict & dict = Dict()) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1640 of file mx.cpp.
References casadi::linsol(), casadi::Function::linsol_solve(), casadi::GenericMatrix< MatType >::size2(), and sparsity().
{
     Function mysolver = linsol("tmp", lsolver, a.sparsity(), b.size2(), dict);
     return mysolver.linsol_solve(a, b, false);
   }
const Sparsity & casadi::MX::sparsity () const
Definition at line 532 of file mx.cpp.
Referenced by casadi::DaeBuilder::add_alg(), casadi::DaeBuilder::add_d(), casadi::DaeBuilder::add_dae(), casadi::DaeBuilder::add_ode(), casadi::DaeBuilder::add_quad(), casadi::DaeBuilder::add_y(), casadi::Assertion::Assertion(), casadi::DaeBuilder::attribute(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), densify(), casadi::DaeBuilder::der(), diag(), casadi::Diagsplit::Diagsplit(), casadi::Dot::Dot(), enlarge(), erase(), casadi::SetNonzeros< Add >::eval_mx(), casadi::GetNonzeros::evalAdj(), casadi::GetNonzeros::evalFwd(), casadi::SetNonzeros< Add >::evalFwd(), casadi::MXFunction::generate_lifted(), casadi::UnaryMX::getBinary(), casadi::Constant< Value >::getBinary(), casadi::MXNode::getBinary(), casadi::MXNode::getBinarySwitch(), casadi::MXNode::getDot(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::Horzsplit::Horzsplit(), casadi::Scpgen::init(), kron(), lift(), casadi::Linsol::linsol_reverse(), casadi::Monitor::Monitor(), mtimes(), casadi::Multiplication::Multiplication(), MX(), nullspace(), casadi::Horzcat::offset(), casadi::Vertcat::offset(), casadi::Diagcat::offset(), project(), casadi::Rank1::Rank1(), reshape(), set(), casadi::DaeBuilder::set_attribute(), set_nz(), casadi::SetNonzeros< Add >::SetNonzeros(), casadi::simpleIRK(), casadi::Solve< Tr >::Solve(), solve(), casadi::Transpose::Transpose(), unite(), and casadi::Vertsplit::Vertsplit().
{
     return (*this)->sparsity();
   }
Sparsity& casadi::GenericMatrix< MX >::sparsityRef () inherited
std::vector< MX > casadi::MX::split_primitives (const MX & x) const
Definition at line 771 of file mx.cpp.
{
     std::vector<MX> ret(n_primitives());
     std::vector<MX>::iterator it=ret.begin();
     (*this)->split_primitives(x, it);
     casadi_assert(it==ret.end());
     return ret;
   }
static int casadi::GenericMatrix< MX >::sprank (const MX & x) inline static inherited
Definition at line 175 of file generic_matrix.hpp.
 { return Sparsity::sprank(x.sparsity());}
MX casadi::MX::substitute (const MX & ex, const MX & v, const MX & vdef) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1267 of file mx.cpp.
{
     return substitute(vector<MX>{ex}, vector<MX>{v}, vector<MX>{vdef}).front();
   }
std::vector< MX > casadi::MX::substitute (const std::vector< MX > & ex, const std::vector< MX > & v, const std::vector< MX > & vdef) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1271 of file mx.cpp.
References casadi::Function::call(), and casadi::is_equal().
{
     // Assert consistent dimensions
     casadi_assert(v.size()==vdef.size());
     // Quick return if all equal
     bool all_equal = true;
     for (int k=0; k<v.size(); ++k) {
       if (v[k].size()!=vdef[k].size() || !is_equal(v[k], vdef[k])) {
         all_equal = false;
         break;
       }
     }
     if (all_equal) return ex;
     // Otherwise, evaluate symbolically
     Function F("tmp", v, ex);
     std::vector<MX> ret;
     F.call(vdef, ret, true);
     return ret;
   }
void casadi::MX::substitute_inplace (const std::vector< MX > & v, std::vector< MX > & vdef, std::vector< MX > & ex, bool reverse) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1198 of file mx.cpp.
References casadi::MXFunction::algorithm_, casadi::MXNode::eval_mx(), casadi::Function::get(), casadi::OP_CONST, casadi::OP_INPUT, casadi::OP_OUTPUT, and casadi::OP_PARAMETER.
{
     casadi_assert_message(v.size()==vdef.size(),
                           "Mismatch in the number of expression to substitute.");
     for (int k=0; k<v.size(); ++k) {
       casadi_assert_message(v[k].is_symbolic(), "Variable " << k << " is not symbolic");
       casadi_assert_message(v[k].size() == vdef[k].size(),
                             "Inconsistent shape for variable " << k << ".");
     }
     casadi_assert_message(reverse==false, "Not implemented");
     // quick return if nothing to replace
     if (v.empty()) return;
     // Function inputs
     std::vector<MX> f_in = v;
     // Function outputs
     std::vector<MX> f_out = vdef;
     f_out.insert(f_out.end(), ex.begin(), ex.end());
     // Write the mapping function
     Function f("mapping", f_in, f_out);
     auto *ff = dynamic_cast<MXFunction *>(f.get());
     // Get references to the internal data structures
     std::vector<MXAlgEl>& algorithm = ff->algorithm_;
     vector<MX> work(ff->workloc_.size()-1);
     vector<MX> oarg, ores;
     for (vector<MXAlgEl>::iterator it=algorithm.begin(); it!=algorithm.end(); ++it) {
       switch (it->op) {
       case OP_INPUT:
         work.at(it->res.front()) = vdef.at(it->arg.front());
         break;
       case OP_PARAMETER:
       case OP_CONST:
         work.at(it->res.front()) = it->data;
         break;
       case OP_OUTPUT:
         if (it->res.front()<vdef.size()) {
           vdef.at(it->res.front()) = work.at(it->arg.front());
         } else {
           ex.at(it->res.front()-vdef.size()) = work.at(it->arg.front());
         }
         break;
       default:
         {
           // Arguments of the operation
           oarg.resize(it->arg.size());
           for (int i=0; i<oarg.size(); ++i) {
             int el = it->arg[i];
             oarg[i] = el<0 ? MX(it->data->dep(i).size()) : work.at(el);
           }
           // Perform the operation
           ores.resize(it->res.size());
           it->data->eval_mx(oarg, ores);
           // Get the result
           for (int i=0; i<ores.size(); ++i) {
             int el = it->res[i];
             if (el>=0) work.at(el) = ores[i];
           }
         }
       }
     }
   }
MX casadi::MX::sum1 (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1180 of file mx.cpp.
References casadi::mtimes(), and casadi::GenericMatrix< MatType >::size1().
{
     return mtimes(MX::ones(1, x.size1()), x);
   }
MX casadi::MX::sum2 (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1176 of file mx.cpp.
References casadi::mtimes(), and casadi::GenericMatrix< MatType >::size2().
{
     return mtimes(x, MX::ones(x.size2(), 1));
   }
static MX casadi::GenericMatrix< MX >::sum_square (const MX & x) inline static inherited
Definition at line 185 of file generic_matrix.hpp.
 { return dot(x, x);}
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 153 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
casadi::GenericMatrix< MX >::SWIG_CONSTREF (Sparsity) const inherited
static MX casadi::GenericMatrix< MX >::sym (const std::string & name, int nrow = 1, int ncol = 1) inline static inherited
Definition at line 615 of file generic_matrix.hpp.
Referenced by casadi::MXFunction::generate_lifted(), casadi::Switch::get_forward(), casadi::Rootfinder::get_forward(), casadi::KernelSum::get_forward(), casadi::Integrator::get_forward(), casadi::Rootfinder::get_reverse(), casadi::KernelSum::get_reverse(), casadi::Mapaccum::get_reverse(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::getFullJacobian(), casadi::SqicInterface::init(), casadi::ImplicitToNlp::init(), casadi::Scpgen::init(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::mx_out(), casadi::RkIntegrator::setupFG(), and casadi::CollocationIntegrator::setupFG().
{
       return sym(name, Sparsity::dense(nrow, ncol));
     }
static MX casadi::GenericMatrix< MX >::sym (const std::string & name, const std::pair< int, int > & rc) inline static inherited
Definition at line 620 of file generic_matrix.hpp.
{
       return sym(name, rc.first, rc.second);
     }
static MX casadi::GenericMatrix< MX >::sym (const std::string & name, const Sparsity & sp) static inherited
static std::vector<MX > casadi::GenericMatrix< MX >::sym (const std::string & name, const Sparsity & sp, int p) static inherited
static std::vector<MX > casadi::GenericMatrix< MX >::sym (const std::string & name, int nrow, int ncol, int p) inline static inherited
Definition at line 632 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p);
     }
static std::vector<std::vector<MX > > casadi::GenericMatrix< MX >::sym (const std::string & name, const Sparsity & sp, int p, int r) static inherited
static std::vector<std::vector<MX > > casadi::GenericMatrix< MX >::sym (const std::string & name, int nrow, int ncol, int p, int r) inline static inherited
Definition at line 644 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p, r);
     }
std::vector< MX > casadi::MX::symvar (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1575 of file mx.cpp.
References casadi::Function::free_mx().
{
     Function f("f", vector<MX>{}, {x});
     return f.free_mx();
   }
MX casadi::MX::T () const
Definition at line 827 of file mx.cpp.
References casadi::MXNode::getTranspose().
Referenced by casadi::DaeBuilder::create(), casadi::Determinant::evalAdj(), casadi::Inverse::evalAdj(), casadi::Determinant::evalFwd(), casadi::SqicInterface::init(), casadi::Linsol::linsol_forward(), casadi::Linsol::linsol_reverse(), pinv(), casadi::GenericCall::projectArg(), casadi::FunctionInternal::reverse_mx(), set(), set_nz(), and vertsplit().
                  {
     return (*this)->getTranspose();
   }
MX casadi::MX::tang (const Function & f, int iind = 0, int oind = 0) static
Definition at line 1697 of file mx.cpp.
References casadi::FunctionInternal::tang_mx().
{
     return Function(f)->tang_mx(iind, oind);
   }
MX casadi::MX::tang (const Function & f, const std::string & iname, int oind = 0) static
Definition at line 1728 of file mx.cpp.
References casadi::Function::index_in().
{
     return tang(f, f.index_in(iname), oind);
   }
MX casadi::MX::tang (const Function & f, int iind, const std::string & oname) static
Definition at line 1732 of file mx.cpp.
References casadi::Function::index_out().
{
     return tang(f, iind, f.index_out(oname));
   }
MX casadi::MX::tang (const Function & f, const std::string & iname, const std::string & oname) static
Definition at line 1736 of file mx.cpp.
References casadi::Function::index_in(), and casadi::Function::index_out().
{
     return tang(f, f.index_in(iname), f.index_out(oname));
   }
MX casadi::MX::tangent (const MX & f, const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1543 of file mx.cpp.
{
     Function temp("helper_tangent_MX", {x}, {f});
     return MX::tang(temp);
   }
bool casadi::MX::test_cast (const SharedObjectNode * ptr) static
Definition at line 831 of file mx.cpp.
{
     return dynamic_cast<const MXNode*>(ptr)!=0;
   }
MX casadi::MX::trace (const MX & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1151 of file mx.cpp.
References casadi::GenericMatrix< MatType >::is_square(), and casadi::GenericMatrix< MatType >::size2().
{
     casadi_assert_message(x.is_square(), "trace: must be square");
     MX res(0);
     for (int i=0; i < x.size2(); i ++) {
       res += x(i, i);
     }
     return res;
   }
static MX casadi::GenericMatrix< MX >::tril (const MX & x, bool includeDiagonal = true) inline static inherited
Definition at line 179 of file generic_matrix.hpp.
{
       return project(x, Sparsity::tril(x.sparsity(), includeDiagonal));
     }
static MX casadi::GenericMatrix< MX >::tril2symm (const MX & x) static inherited
static MX casadi::GenericMatrix< MX >::triu (const MX & x, bool includeDiagonal = true) inline static inherited
Definition at line 182 of file generic_matrix.hpp.
{
       return project(x, Sparsity::triu(x.sparsity(), includeDiagonal));
     }
static MX casadi::GenericMatrix< MX >::triu2symm (const MX & x) static inherited
std::string casadi::MX::type_name () static
Definition at line 1685 of file mx.cpp.
{
     return "MX";
   }
MX casadi::MX::unary (int op, const MX & x) static
Definition at line 477 of file mx.cpp.
References casadi::MXNode::getUnary().
{
     return x->getUnary(Operation(op));
   }
MX casadi::MX::unite (const MX & A, const MX & B) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1125 of file mx.cpp.
References casadi::MXNode::getSetNonzeros(), sparsity(), and casadi::Sparsity::unite().
{
     // Join the sparsity patterns
     std::vector<unsigned char> mapping;
     Sparsity sp = A.sparsity().unite(B.sparsity(), mapping);
     // Split up the mapping
     std::vector<int> nzA, nzB;
     // Copy sparsity
     for (int k=0; k<mapping.size(); ++k) {
       if (mapping[k]==1) {
         nzA.push_back(k);
       } else if (mapping[k]==2) {
         nzB.push_back(k);
       } else {
         throw CasadiException("Pattern intersection not empty");
       }
     }
     // Create mapping
     MX ret = MX::zeros(sp);
     ret = A->getSetNonzeros(ret, nzA);
     ret = B->getSetNonzeros(ret, nzB);
     return ret;
   }
static MX casadi::SparsityInterface< MX >::vec (const MX & x) static inherited
static MX casadi::SparsityInterface< MX >::veccat (const std::vector< MX > & x) static inherited
MX casadi::MX::vertcat (const std::vector< MX > & x) static
Functions called by friend functions defined for SparsityInterface
Definition at line 910 of file mx.cpp.
References casadi::has_empty(), and casadi::trim_empty().
{
     // Check dimensions
     if (x.size()>1) {
       vector<MX> ne = trim_empty(x, true);
       for (int i=0;i<ne.size();i++) {
         casadi_assert_message(ne[i].size2()==ne[0].size2(),
                       "vertcat dimension mismatch  " <<
                       "x[" << i << "]:" << ne[i].dim() <<
                       " and x[0]: " << ne[0].dim() << ".");
       }
     }
     if (x.empty()) {
       return MX();
     } else if (x.size()==1) {
       return x.front();
     } else if (has_empty(x)) {
       std::vector<MX> ret = trim_empty(x);
       if (ret.empty()) {
         // We still want vertcat(zeros(5,0),zeros(5,0)) -> zeros(10,0)
         ret = trim_empty(x, true);
         int s = 0;
         for (int i=0;i<ret.size();++i) {
           s+= ret[i].size1();
         }
         return MX::zeros(s, 0);
       } else {
         return vertcat(ret);
       }
     } else if (!x.front().is_column()) {
       // Vertcat operation only supports vectors, rewrite using horzcat
       vector<MX> xT = x;
       for (vector<MX>::iterator i=xT.begin(); i!=xT.end(); ++i) *i = i->T();
       return horzcat(xT).T();
     } else {
       return x.front()->getVertcat(x);
     }
   }
static std::vector<MX > casadi::SparsityInterface< MX >::vertsplit (const MX & x, int incr) static inherited
std::vector< MX > casadi::MX::vertsplit (const MX & x, const std::vector< int > & offset) static
Functions called by friend functions defined for SparsityInterface
Definition at line 983 of file mx.cpp.
References casadi::MXNode::getVertsplit(), casadi::GenericMatrix< MatType >::is_column(), casadi::isMonotone(), casadi::GenericMatrix< MatType >::size1(), and T().
{
     if (x.is_column()) {
       // Consistency check
       casadi_assert(offset.size()>=1);
       casadi_assert(offset.front()==0);
       casadi_assert(offset.back()==x.size1());
       casadi_assert(isMonotone(offset));
       // Trivial return if possible
       if (offset.size()==1) {
         return vector<MX>();
       } else if (offset.size()==2) {
         return vector<MX>(1, x);
       } else {
         return x->getVertsplit(offset);
       }
     } else {
       std::vector<MX> ret = horzsplit(x.T(), offset);
       for (auto&& e : ret) e = e.T();
       return ret;
     }
   }
WeakRef * casadi::SharedObject::weak () inherited
Definition at line 167 of file shared_object.cpp.
References casadi::SharedObjectNode::weak().
Referenced by casadi::WeakRef::WeakRef().
{
     return (*this)->weak();
   }
static MX casadi::GenericMatrix< MX >::zeros (int nrow = 1, int ncol = 1) inline static inherited
Definition at line 651 of file generic_matrix.hpp.
Referenced by casadi::SetNonzeros< Add >::eval_mx(), casadi::SetNonzeros< Add >::evalAdj(), casadi::SetNonzeros< Add >::evalFwd(), casadi::KernelSum::get_reverse(), casadi::Constant< Value >::getBinary(), casadi::Scpgen::init(), casadi::Linsol::linsol_reverse(), mtimes(), and casadi::CollocationIntegrator::setupFG().
 { return zeros(Sparsity::dense(nrow, ncol)); }
static MX casadi::GenericMatrix< MX >::zeros (const Sparsity & sp) inline static inherited
Definition at line 652 of file generic_matrix.hpp.
 { return MatType(sp, 0, false);}
static MX casadi::GenericMatrix< MX >::zeros (const std::pair< int, int > & rc) inline static inherited
Definition at line 653 of file generic_matrix.hpp.
 { return zeros(rc.first, rc.second);}
The documentation for this class was generated from the following files:
mx.hpp
mx.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge