CasADi: casadi::Project Class Reference
casadi::Project Class Reference
Change the sparsity of an expression.
#include <project.hpp>
Detailed Description
Author
Joel Andersson
Date
2011-2013
Definition at line 37 of file project.hpp.
Public Member Functions
Project (const MX &x, const Sparsity &sp)
Constructor.
virtual ~Project ()
Destructor.
virtual std::string print (const std::vector< std::string > &arg) const
Print expression.
template<typename T >
void evalGen (const T **arg, T **res, int *iw, T *w, int mem) const
Evaluate the function (template)
virtual void eval (const double **arg, double **res, int *iw, double *w, int mem) const
Evaluate the function numerically.
virtual void eval_sx (const SXElem **arg, SXElem **res, int *iw, SXElem *w, int mem)
Evaluate the function symbolically (SX)
virtual void eval_mx (const std::vector< MX > &arg, std::vector< MX > &res)
Evaluate symbolically (MX)
virtual void evalFwd (const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens)
Calculate forward mode directional derivatives.
virtual void evalAdj (const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens)
Calculate reverse mode directional derivatives.
void generate (CodeGenerator &g, const std::string &mem, const std::vector< int > &arg, const std::vector< int > &res) const
Generate code for the operation.
virtual void spFwd (const bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem)
Propagate sparsity forward.
virtual void spAdj (bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem)
Propagate sparsity backwards.
virtual int op () const
Get the operation.
virtual size_t sz_w () const
Get required length of w field.
virtual bool __nonzero__ () const
Check the truth value of this node.
virtual bool is_zero () const
Check if identically zero.
virtual bool is_one () const
Check if identically one.
virtual bool isValue (double val) const
Check if a certain value.
virtual bool is_identity () const
Check if identity matrix.
virtual bool is_unaryOp () const
Check if unary operation.
virtual bool is_binaryOp () const
Check if binary operation.
virtual void repr (std::ostream &stream) const
Print a representation.
virtual void print (std::ostream &stream) const
Print a description.
void can_inline (std::map< const MXNode *, int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const MXNode *, int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
virtual void addDependency (CodeGenerator &g) const
Add a dependent function.
int addDependency (const MX &dep)
Add a dependency.
virtual bool has_refcount () const
Is reference counting needed in codegen?
virtual void codegen_incref (CodeGenerator &g, std::set< void * > &added) const
Codegen incref.
virtual void codegen_decref (CodeGenerator &g, std::set< void * > &added) const
Codegen decref.
virtual const std::string & name () const
Get the name.
virtual bool is_valid_input () const
Check if valid function input.
virtual int n_primitives () const
Get the number of symbolic primitives.
virtual void primitives (std::vector< MX >::iterator &it) const
Get symbolic primitives.
virtual void split_primitives (const MX &x, std::vector< MX >::iterator &it) const
Split up an expression along symbolic primitives.
virtual MX join_primitives (std::vector< MX >::const_iterator &it) const
Join an expression along symbolic primitives.
virtual bool has_duplicates ()
Detect duplicate symbolic expressions.
virtual void resetInput ()
Reset the marker for an input expression.
virtual bool isOutputNode () const
Check if evaluation output.
virtual bool isMultipleOutput () const
Check if a multiple output node.
virtual int numFunctions () const
Number of functions.
virtual const Function & getFunction (int i) const
Get function reference.
virtual int getFunction_input () const
Get function input.
virtual int getFunctionOutput () const
Get function output.
virtual bool is_equal (const MXNode *node, int depth) const
bool sameOpAndDeps (const MXNode *node, int depth) const
Checks if two nodes have the same operation and have equivalent dependencies up to a given depth.
const MX & dep (int ind=0) const
dependencies - functions that have to be evaluated before this one
MX & dep (int ind=0)
int ndep () const
Number of dependencies.
virtual bool hasDep () const
Does the node depend on other nodes.
virtual int nout () const
Number of outputs.
virtual MX getOutput (int oind) const
Get an output.
const Sparsity & sparsity () const
Get the sparsity.
virtual const Sparsity & sparsity (int oind) const
Get the sparsity of output oind.
int numel () const
Get shape.
int nnz (int i=0) const
int size1 () const
int size2 () const
std::pair< int, int > size () const
virtual bool isNonLinear ()
Is the node nonlinear.
void setSparsity (const Sparsity &sparsity)
Set the sparsity.
virtual size_t sz_arg () const
Get required length of arg field.
virtual size_t sz_res () const
Get required length of res field.
virtual size_t sz_iw () const
Get required length of iw field.
void setDependencies (const MX &dep)
Set unary dependency.
void setDependencies (const MX &dep1, const MX &dep2)
Set binary dependencies.
void setDependencies (const MX &dep1, const MX &dep2, const MX &dep3)
Set ternary dependencies.
void setDependencies (const std::vector< MX > &dep)
Set multiple dependencies.
virtual void assign (const MX &d, const std::vector< int > &inz, const std::vector< int > &onz, bool add=false)
Assign nonzeros (mapping matrix)
virtual void assign (const MX &d, const std::vector< int > &inz, bool add=false)
Assign nonzeros (mapping matrix), output indices sequential.
virtual double to_double () const
Get the value (only for scalar constant nodes)
virtual Matrix< double > getMatrixValue () const
Get the value (only for constant nodes)
virtual int numInplace () const
Can the operation be performed inplace (i.e. overwrite the result)
virtual void simplifyMe (MX &ex)
Simplify the expression (ex is a reference to the node)
virtual Matrix< int > mapping () const
Get an IM representation of a GetNonzeros or SetNonzeros node.
virtual MX getHorzcat (const std::vector< MX > &x) const
Create a horizontal concatenation node.
virtual std::vector< MX > getHorzsplit (const std::vector< int > &output_offset) const
Create a horizontal split node.
virtual MX getRepmat (int m, int n) const
Create a repeated matrix node.
virtual MX getRepsum (int m, int n) const
Create a repeated sum node.
virtual MX getVertcat (const std::vector< MX > &x) const
Create a vertical concatenation node (vectors only)
virtual std::vector< MX > getVertsplit (const std::vector< int > &output_offset) const
Create a vertical split node (vectors only)
virtual MX get_diagcat (const std::vector< MX > &x) const
Create a diagonal concatenation node.
virtual std::vector< MX > get_diagsplit (const std::vector< int > &offset1, const std::vector< int > &offset2) const
Create a diagonal split node.
virtual MX getTranspose () const
Transpose.
virtual MX getReshape (const Sparsity &sp) const
Reshape.
virtual MX getMultiplication (const MX &y, const MX &z) const
Matrix multiplication and addition.
virtual MX getBilin (const MX &x, const MX &y) const
Bilinear form.
virtual MX getRank1 (const MX &alpha, const MX &x, const MX &y) const
Bilinear form.
virtual MX getSolve (const MX &r, bool tr, const Function &linear_solver) const
Solve a system of linear equations.
virtual MX getGetNonzeros (const Sparsity &sp, const std::vector< int > &nz) const
Get the nonzeros of matrix.
virtual MX getSetNonzeros (const MX &y, const std::vector< int > &nz) const
Assign the nonzeros of a matrix to another matrix.
virtual MX getAddNonzeros (const MX &y, const std::vector< int > &nz) const
Add the nonzeros of a matrix to another matrix.
virtual MX getRef (const Slice &i, const Slice &j) const
Get submatrix reference.
virtual MX getAssign (const MX &y, const Slice &i, const Slice &j) const
Get submatrix assignment.
virtual MX getProject (const Sparsity &sp) const
Create set sparse.
virtual MX getUnary (int op) const
Get a unary operation.
MX getBinarySwitch (int op, const MX &y) const
Get a binary operation operation.
virtual MX getBinary (int op, const MX &y, bool scX, bool scY) const
Get a binary operation operation (matrix-matrix)
virtual MX getDeterminant () const
Determinant.
virtual MX getInverse () const
Inverse.
virtual MX getDot (const MX &y) const
Inner product.
virtual MX getNormF () const
Frobenius norm.
virtual MX getNorm2 () const
Spectral norm.
virtual MX getNormInf () const
Infinity norm.
virtual MX getNorm1 () const
1-norm
MX getAssertion (const MX &y, const std::string &fail_message) const
Assertion.
MX getMonitor (const std::string &comment) const
Monitor.
MX getFind () const
Find.
int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static bool is_equal (const MXNode *x, const MXNode *y, int depth)
Check if two nodes are equivalent up to a given depth.
static bool maxDepth ()
Get equality checking depth.
static MX toMatrix (const MX &x, const Sparsity &sp)
Convert scalar to matrix.
static void copyFwd (const bvec_t *arg, bvec_t *res, int len)
Propagate sparsities forward through a copy operation.
static void copyAdj (bvec_t *arg, bvec_t *res, int len)
Propagate sparsities backwards through a copy operation.
Public Attributes
int temp
std::vector< MX > dep_
dependencies - functions that have to be evaluated before this one
Sparsity sparsity_
The sparsity pattern.
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Constructor & Destructor Documentation
casadi::Project::Project (const MX & x, const Sparsity & sp)
Definition at line 35 of file project.cpp.
{
     setDependencies(x);
     setSparsity(Sparsity(sp));
   }
virtual casadi::Project::~Project () inline virtual
Definition at line 44 of file project.hpp.
 {}
Member Function Documentation
bool casadi::MXNode::__nonzero__ () const virtual inherited
Reimplemented in casadi::ConstantMX.
Definition at line 160 of file mx_node.cpp.
{
     casadi_error("Can only determine truth value of a numeric MX.");
   }
virtual void casadi::MXNode::addDependency (CodeGenerator & g) const inline virtual inherited
Reimplemented in casadi::Call.
Definition at line 127 of file mx_node.hpp.
 {}
int casadi::MXNode::addDependency (const MX & dep) inherited
Definition at line 199 of file mx_node.cpp.
References casadi::GenericMatrix< MatType >::size().
{
     dep_.push_back(dep);
     return dep_.size()-1;
   }
virtual void casadi::MXNode::assign (const MX & d, const std::vector< int > & inz, const std::vector< int > & onz, bool add = false) virtual inherited
virtual void casadi::MXNode::assign (const MX & d, const std::vector< int > & inz, bool add = false) virtual inherited
void casadi::MXNode::can_inline (std::map< const MXNode *, int > & nodeind) const inherited
Definition at line 245 of file mx_node.cpp.
References casadi::OP_PARAMETER.
{
     // Add or mark node in map
     std::map<const MXNode*, int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, make_pair(this, 0));
       // Handle dependencies with recursion
       for (int i=0; i<ndep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
virtual void casadi::MXNode::codegen_decref (CodeGenerator & g, std::set< void * > & added) const inline virtual inherited
Reimplemented in casadi::Call.
Definition at line 136 of file mx_node.hpp.
 {}
virtual void casadi::MXNode::codegen_incref (CodeGenerator & g, std::set< void * > & added) const inline virtual inherited
Reimplemented in casadi::Call.
Definition at line 133 of file mx_node.hpp.
 {}
void casadi::MXNode::copyAdj (bvec_t * arg, bvec_t * res, int len) static inherited
Definition at line 931 of file mx_node.cpp.
Referenced by casadi::UnaryMX::spAdj(), casadi::SetNonzerosVector< Add >::spAdj(), casadi::SetNonzerosSlice< Add >::spAdj(), and casadi::SetNonzerosSlice2< Add >::spAdj().
{
     if (arg!=res) {
       for (int k=0; k<len; ++k) {
         *arg++ |= *res;
         *res++ = 0;
       }
     }
   }
void casadi::MXNode::copyFwd (const bvec_t * arg, bvec_t * res, int len) static inherited
Definition at line 925 of file mx_node.cpp.
References casadi::copy().
Referenced by casadi::UnaryMX::spFwd().
{
     if (arg!=res) {
       copy(arg, arg+len, res);
     }
   }
const MX & casadi::MXNode::dep (int ind = 0) const inherited
Definition at line 165 of file mx_node.cpp.
Referenced by casadi::MX::dep(), casadi::UnaryMX::evalAdj(), casadi::Call::evalAdj(), casadi::UnaryMX::evalFwd(), casadi::Call::evalFwd(), casadi::HorzRepmat::evalGen(), casadi::Split::generate(), casadi::Monitor::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Diagsplit::get_diagcat(), casadi::UnaryMX::getBinary(), casadi::MXNode::getBinary(), casadi::Horzsplit::getHorzcat(), casadi::UnaryMX::getUnary(), casadi::Vertsplit::getVertcat(), casadi::Concat::has_duplicates(), casadi::MXFunction::init(), casadi::BinaryMX< ScX, ScY >::is_equal(), casadi::Concat::is_valid_input(), casadi::Horzcat::join_primitives(), casadi::Vertcat::join_primitives(), casadi::Diagcat::join_primitives(), casadi::Concat::n_primitives(), casadi::Horzcat::offset(), casadi::Vertcat::offset(), casadi::Diagcat::offset(), casadi::MX::operator-(), casadi::OutputNode::OutputNode(), casadi::Concat::primitives(), casadi::Concat::resetInput(), casadi::MXNode::sameOpAndDeps(), casadi::HorzRepmat::spAdj(), casadi::HorzRepmat::spFwd(), casadi::Horzcat::split_primitives(), casadi::Vertcat::split_primitives(), and casadi::Diagcat::split_primitives().
{
     return dep_.at(ind);
   }
MX & casadi::MXNode::dep (int ind = 0) inherited
Definition at line 169 of file mx_node.cpp.
{
     return dep_.at(ind);
   }
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
void casadi::Project::eval (const double ** arg, double ** res, int * iw, double * w, int mem) const virtual
Reimplemented from casadi::MXNode.
Definition at line 53 of file project.cpp.
{
     evalGen<double>(arg, res, iw, w, mem);
   }
void casadi::Project::eval_mx (const std::vector< MX > & arg, std::vector< MX > & res) virtual
Reimplemented from casadi::MXNode.
Definition at line 61 of file project.cpp.
References casadi::project().
{
     res[0] = project(arg[0], sparsity());
   }
void casadi::Project::eval_sx (const SXElem ** arg, SXElem ** res, int * iw, SXElem * w, int mem) virtual
Reimplemented from casadi::MXNode.
Definition at line 57 of file project.cpp.
{
     evalGen<SXElem>(arg, res, iw, w, mem);
   }
void casadi::Project::evalAdj (const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens) virtual
Reimplemented from casadi::MXNode.
Definition at line 73 of file project.cpp.
References casadi::project().
{
     int nadj = aseed.size();
     for (int d=0; d<nadj; ++d) {
       asens[d][0] += project(aseed[d][0], dep().sparsity(), true);
     }
   }
void casadi::Project::evalFwd (const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens) virtual
Reimplemented from casadi::MXNode.
Definition at line 65 of file project.cpp.
References casadi::project().
{
     int nfwd = fsens.size();
     for (int d=0; d<nfwd; ++d) {
       fsens[d][0] = project(fseed[d][0], sparsity(), true);
     }
   }
template<typename T > void casadi::Project::evalGen (const T ** arg, T ** res, int * iw, T * w, int mem) const
Definition at line 49 of file project.cpp.
{
     casadi_project(arg[0], dep().sparsity(), res[0], sparsity(), w);
   }
void casadi::Project::generate (CodeGenerator & g, const std::string & mem, const std::vector< int > & arg, const std::vector< int > & res) const virtual
Reimplemented from casadi::MXNode.
Definition at line 90 of file project.cpp.
References casadi::CodeGenerator::body, casadi::CodeGenerator::project(), and casadi::CodeGenerator::work().
{
     g.body << "  " << g.project(g.work(arg.front(), dep().nnz()), dep(0).sparsity(),
                                 g.work(res.front(), nnz()), sparsity(), "w") << endl;
   }
MX casadi::MXNode::get_diagcat (const std::vector< MX > & x) const virtual inherited
Reimplemented in casadi::Diagsplit.
Definition at line 802 of file mx_node.cpp.
Referenced by casadi::Diagsplit::get_diagcat().
{
     // Create a Horzcat node
     return MX::create(new Diagcat(x));
   }
vector< MX > casadi::MXNode::get_diagsplit (const std::vector< int > & offset1, const std::vector< int > & offset2) const virtual inherited
Definition at line 877 of file mx_node.cpp.
References casadi::is_zero().
Referenced by casadi::MX::diagsplit().
{
     if (is_zero()) {
       vector<MX> ret =
           MX::createMultipleOutput(new Diagsplit(shared_from_this<MX>(), offset1, offset2));
       for (int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     vector<MX> ret =
         MX::createMultipleOutput(new Diagsplit(shared_from_this<MX>(), offset1, offset2));
     return ret;
   }
MX casadi::MXNode::getAddNonzeros (const MX & y, const std::vector< int > & nz) const virtual inherited
Definition at line 494 of file mx_node.cpp.
References casadi::is_slice(), casadi::is_slice2(), casadi::is_zero(), casadi::simplify(), casadi::to_slice(), and casadi::to_slice2().
Referenced by casadi::GetNonzeros::evalAdj(), and casadi::SetNonzeros< Add >::evalFwd().
{
     if (nz.size()==0 || is_zero()) {
       return y;
     } else {
       MX ret;
       if (is_slice(nz)) {
         ret = MX::create(new SetNonzerosSlice<true>(y, shared_from_this<MX>(), to_slice(nz)));
       } else if (is_slice2(nz)) {
         pair<Slice, Slice> sl = to_slice2(nz);
         ret = MX::create(new SetNonzerosSlice2<true>(y, shared_from_this<MX>(),
                                                      sl.first, sl.second));
       } else {
         ret = MX::create(new SetNonzerosVector<true>(y, shared_from_this<MX>(), nz));
       }
       return simplify(ret);
     }
   }
MX casadi::MXNode::getAssertion (const MX & y, const std::string & fail_message) const inherited
Definition at line 716 of file mx_node.cpp.
{
     return MX::create(new Assertion(shared_from_this<MX>(), y, fail_message));
   }
MX casadi::MXNode::getAssign (const MX & y, const Slice & i, const Slice & j) const virtual inherited
Definition at line 526 of file mx_node.cpp.
{
     return MX::create(new SubAssign(shared_from_this<MX>(), y, i, j));
   }
MX casadi::MXNode::getBilin (const MX & x, const MX & y) const virtual inherited
Definition at line 434 of file mx_node.cpp.
Referenced by casadi::MX::_bilin().
{
     return MX::create(new Bilin(shared_from_this<MX>(), x, y));
   }
MX casadi::MXNode::getBinary (int op, const MX & y, bool scX, bool scY) const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ZeroByZero, casadi::BinaryMX< ScX, ScY >, and casadi::UnaryMX.
Definition at line 580 of file mx_node.cpp.
References casadi::densify(), casadi::MXNode::dep(), casadi::MX::get(), casadi::MXNode::getBinary(), casadi::GenericMatrix< MatType >::is_dense(), casadi::is_zero(), casadi::MXNode::is_zero(), casadi::MXNode::isValue(), casadi::MXNode::op(), casadi::OP_ADD, casadi::OP_CONST, casadi::OP_CONSTPOW, casadi::OP_DIV, casadi::OP_EQ, casadi::OP_INV, casadi::OP_LE, casadi::OP_LT, casadi::OP_MUL, casadi::OP_NE, casadi::OP_NEG, casadi::OP_POW, casadi::OP_SQ, casadi::OP_SUB, casadi::OP_TWICE, casadi::GenericMatrix< MatType >::size(), and casadi::MX::sparsity().
Referenced by casadi::UnaryMX::getBinary(), casadi::BinaryMX< ScX, ScY >::getBinary(), casadi::Constant< Value >::getBinary(), casadi::MXNode::getBinary(), casadi::MXNode::getBinarySwitch(), and casadi::MX::lift().
{
     casadi_assert(sparsity()==y.sparsity() || scX || scY);
     if (GlobalOptions::simplification_on_the_fly) {
       // If identically zero due to one argumebt being zero
       if ((operation_checker<F0XChecker>(op) && is_zero()) ||
          (operation_checker<FX0Checker>(op) && y->is_zero())) {
         return MX::zeros(sparsity());
       }
       // Handle special operations (independent of type)
       switch (op) {
       case OP_ADD:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return getUnary(OP_TWICE);
         break;
       case OP_SUB:
       case OP_NE:
       case OP_LT:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return MX::zeros(sparsity());
         break;
       case OP_DIV:
         if (y->is_zero()) return MX::nan(sparsity());
         // fall-through
       case OP_EQ:
       case OP_LE:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return MX::ones(sparsity());
         break;
       case OP_MUL:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return getUnary(OP_SQ);
         break;
       default: break; // no rule
       }
       // Handle special cases for the second argument
       switch (y->op()) {
       case OP_CONST:
         // Make the constant the first argument, if possible
         if (this->op()!=OP_CONST && operation_checker<CommChecker>(op)) {
           return y->getBinary(op, shared_from_this<MX>(), scY, scX);
         } else {
           switch (op) {
           case OP_POW:
             return getBinary(OP_CONSTPOW, y, scX, scY);
           case OP_CONSTPOW:
             if (y->isValue(-1)) return getUnary(OP_INV);
             else if (y->isValue(0)) return MX::ones(sparsity());
             else if (y->isValue(1)) return shared_from_this<MX>();
             else if (y->isValue(2)) return getUnary(OP_SQ);
             break;
           case OP_ADD:
           case OP_SUB:
             if (y->is_zero())
                 return scX ? repmat(shared_from_this<MX>(), y.size()) : shared_from_this<MX>();
             break;
           case OP_MUL:
             if (y->isValue(1)) return shared_from_this<MX>();
             break;
           case OP_DIV:
             if (y->isValue(1)) return shared_from_this<MX>();
             else if (y->isValue(0.5)) return getUnary(OP_TWICE);
             break;
           default: break; // no rule
           }
         }
         break;
       case OP_NEG:
         if (op==OP_ADD) {
           return getBinary(OP_SUB, y->dep(), scX, scY);
         } else if (op==OP_SUB) {
           return getBinary(OP_ADD, y->dep(), scX, scY);
         } else if (op==OP_MUL) {
           return -getBinary(OP_MUL, y->dep(), scX, scY);
         } else if (op==OP_DIV) {
           return -getBinary(OP_DIV, y->dep(), scX, scY);
         }
         break;
       case OP_INV:
         if (op==OP_MUL) {
           return getBinary(OP_DIV, y->dep(), scX, scY);
         } else if (op==OP_DIV) {
           return getBinary(OP_MUL, y->dep(), scX, scY);
         }
         break;
       default: break; // no rule
       }
     }
     if (scX) {
       // Check if it is ok to loop over nonzeros only
       if (y.is_dense() || operation_checker<FX0Checker>(op)) {
         // Loop over nonzeros
         return MX::create(new BinaryMX<true, false>(Operation(op), shared_from_this<MX>(), y));
       } else {
         // Put a densification node in between
         return getBinary(op, densify(y), true, false);
       }
     } else if (scY) {
       // Check if it is ok to loop over nonzeros only
       if (sparsity().is_dense() || operation_checker<F0XChecker>(op)) {
         // Loop over nonzeros
         return MX::create(new BinaryMX<false, true>(Operation(op), shared_from_this<MX>(), y));
       } else {
         // Put a densification node in between
         return densify(shared_from_this<MX>())->getBinary(op, y, false, true);
       }
     } else {
       // Loop over nonzeros only
       MX rr = MX::create(new BinaryMX<false, false>(Operation(op), shared_from_this<MX>(), y));
       // Handle structural zeros giving rise to nonzero result, e.g. cos(0) == 1
       if (!rr.is_dense() && !operation_checker<F00Checker>(op)) {
         // Get the value for the structural zeros
         double fcn_0(0);
         casadi_math<double>::fun(op, 0, 0, fcn_0);
         rr = densify(rr, fcn_0);
       }
       return rr;
     }
   }
MX casadi::MXNode::getBinarySwitch (int op, const MX & y) const inherited
Definition at line 540 of file mx_node.cpp.
References casadi::Sparsity::combine(), casadi::GenericMatrix< MatType >::dim(), casadi::MXNode::getBinary(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< MatType >::nnz(), casadi::project(), casadi::GenericMatrix< MatType >::size(), casadi::Sparsity::size(), and casadi::MX::sparsity().
Referenced by casadi::MX::binary().
{
     // Make sure that dimensions match
     casadi_assert_message(sparsity().is_scalar() || y.is_scalar() || sparsity().size()==y.size(),
                           "Dimension mismatch." << "lhs is " << sparsity().dim()
                           << ", while rhs is " << y.dim());
     // Create binary node
     if (sparsity().is_scalar(false)) {
       if (nnz()==0) {
         return toMatrix(MX(0)->getBinary(op, y, true, false), y.sparsity());
       } else {
         return toMatrix(getBinary(op, y, true, false), y.sparsity());
       }
     } else if (y.is_scalar()) {
       if (y.nnz()==0) {
         return toMatrix(getBinary(op, MX(0), false, true), sparsity());
       } else {
         return toMatrix(getBinary(op, y, false, true), sparsity());
       }
     } else {
       casadi_assert_message(sparsity().size() == y.sparsity().size(), "Dimension mismatch.");
       if (sparsity()==y.sparsity()) {
         // Matching sparsities
         return getBinary(op, y, false, false);
       } else {
         // Get the sparsity pattern of the result
         // (ignoring structural zeros giving rise to nonzero result)
         const Sparsity& x_sp = sparsity();
         const Sparsity& y_sp = y.sparsity();
         Sparsity r_sp = x_sp.combine(y_sp, operation_checker<F0XChecker>(op),
                                             operation_checker<FX0Checker>(op));
         // Project the arguments to this sparsity
         MX xx = project(shared_from_this<MX>(), r_sp);
         MX yy = project(y, r_sp);
         return xx->getBinary(op, yy, false, false);
       }
     }
   }
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
MX casadi::MXNode::getDeterminant () const virtual inherited
Definition at line 732 of file mx_node.cpp.
Referenced by casadi::MX::det().
{
     return MX::create(new Determinant(shared_from_this<MX>()));
   }
MX casadi::MXNode::getDot (const MX & y) const virtual inherited
Reimplemented in casadi::ConstantMX.
Definition at line 741 of file mx_node.cpp.
References casadi::MXNode::getDot(), casadi::Sparsity::intersect(), casadi::OP_MUL, casadi::project(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), and casadi::MX::sparsity().
Referenced by casadi::MX::dot(), casadi::NormF::evalFwd(), and casadi::MXNode::getDot().
{
     casadi_assert_message(
       size2()==y.size2() && size1()==y.size1(),
       "MXNode::dot: Dimension mismatch. dot requires its "
       "two arguments to have equal shapes, but got ("
       << size2() << ", " << size1() << ") and ("
       << y.size2() << ", " << y.size1() << ").");
     if (sparsity()==y.sparsity()) {
       if (sparsity().nnz()==0) {
         return 0;
       } else if (sparsity().is_scalar()) {
         return getBinarySwitch(OP_MUL, y);
       } else {
         return MX::create(new Dot(shared_from_this<MX>(), y));
       }
     } else {
       // Project to pattern intersection
       Sparsity sp = sparsity().intersect(y.sparsity());
       MX xx = project(shared_from_this<MX>(), sp);
       MX yy = project(y, sp);
       return xx->getDot(yy);
     }
   }
MX casadi::MXNode::getFind () const inherited
Definition at line 728 of file mx_node.cpp.
Referenced by casadi::MX::find().
{
     return MX::create(new Find(shared_from_this<MX>()));
   }
const Function & casadi::MXNode::getFunction (int i) const virtual inherited
Reimplemented in casadi::Call, casadi::Solve< Tr >, and casadi::GenericCall.
Definition at line 291 of file mx_node.cpp.
{
     throw CasadiException(string("MXNode::getFunction() not defined for class ") +
                           typeid(*this).name());
   }
int casadi::MXNode::getFunction_input () const virtual inherited
Reimplemented in casadi::Call, and casadi::OutputNode.
Definition at line 301 of file mx_node.cpp.
{
     throw CasadiException(string("MXNode::getFunctionOutput() not defined for class ") +
                           typeid(*this).name());
   }
int casadi::MXNode::getFunctionOutput () const virtual inherited
Reimplemented in casadi::Call, and casadi::OutputNode.
Definition at line 296 of file mx_node.cpp.
Referenced by casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::getHorzcat(), casadi::Vertsplit::getVertcat(), and casadi::MXFunction::init().
{
     throw CasadiException(string("MXNode::getFunctionOutput() not defined for class ") +
                           typeid(*this).name());
   }
MX casadi::MXNode::getGetNonzeros (const Sparsity & sp, const std::vector< int > & nz) const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ZeroByZero, casadi::Concat, and casadi::GetNonzeros.
Definition at line 450 of file mx_node.cpp.
References casadi::is_slice(), casadi::is_slice2(), casadi::simplify(), casadi::to_slice(), and casadi::to_slice2().
Referenced by casadi::MX::diag(), casadi::MX::enlarge(), casadi::MX::erase(), casadi::GetNonzeros::evalFwd(), casadi::MX::get(), casadi::MX::get_nz(), casadi::Constant< Value >::getGetNonzeros(), and casadi::MX::MX().
{
     if (nz.size()==0) {
       return MX::zeros(sp);
     } else {
       MX ret;
       if (is_slice(nz)) {
         ret = MX::create(new GetNonzerosSlice(sp, shared_from_this<MX>(), to_slice(nz)));
       } else if (is_slice2(nz)) {
         pair<Slice, Slice> sl = to_slice2(nz);
         ret = MX::create(new GetNonzerosSlice2(sp, shared_from_this<MX>(), sl.first, sl.second));
       } else {
         ret = MX::create(new GetNonzerosVector(sp, shared_from_this<MX>(), nz));
       }
       return simplify(ret);
     }
   }
MX casadi::MXNode::getHorzcat (const std::vector< MX > & x) const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::Horzsplit, and casadi::OutputNode.
Definition at line 781 of file mx_node.cpp.
References casadi::OP_HORZCAT.
Referenced by casadi::OutputNode::getHorzcat(), casadi::Horzsplit::getHorzcat(), and casadi::Constant< Value >::getHorzcat().
{
     // Check if there is any existing horzcat operation
     for (vector<MX>::const_iterator i=x.begin(); i!=x.end(); ++i) {
       if (i->op()==OP_HORZCAT) {
         // Split up
         vector<MX> x_split(x.begin(), i);
         for (; i!=x.end(); ++i) {
           if (i->op()==OP_HORZCAT) {
             x_split.insert(x_split.end(), (*i)->dep_.begin(), (*i)->dep_.end());
           } else {
             x_split.push_back(*i);
           }
         }
         return horzcat(x_split);
       }
     }
     // Create a Horzcat node
     return MX::create(new Horzcat(x));
   }
vector< MX > casadi::MXNode::getHorzsplit (const std::vector< int > & output_offset) const virtual inherited
Definition at line 827 of file mx_node.cpp.
References casadi::is_zero(), and casadi::OP_HORZCAT.
Referenced by casadi::MX::horzsplit().
{
     if (is_zero()) {
       vector<MX> ret =
           MX::createMultipleOutput(new Horzsplit(shared_from_this<MX>(), output_offset));
       for (int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     vector<MX> ret =
         MX::createMultipleOutput(new Horzsplit(shared_from_this<MX>(), output_offset));
     if (GlobalOptions::simplification_on_the_fly) {
       // Simplify horzsplit(horzcat)
       if (op()==OP_HORZCAT) {
         int offset_deps = 0;
         int j = 0;
         for (int i=0;i<output_offset.size();++i) {
           while (offset_deps<output_offset[i]) { offset_deps+=dep(j).size2();++j; }
           if (j>=ndep()) j = ndep()-1;
           if (output_offset[i]==offset_deps &&
               (i+1<output_offset.size()?output_offset[i+1]:size2()) ==
                offset_deps +dep(j).size2()) {
             // Aligned with vertcat dependency
             ret[i] = dep(j);
           }
         }
       }
     }
     return ret;
   }
MX casadi::MXNode::getInverse () const virtual inherited
Definition at line 736 of file mx_node.cpp.
Referenced by casadi::MX::inv().
{
     return MX::create(new Inverse(shared_from_this<MX>()));
   }
Matrix< double > casadi::MXNode::getMatrixValue () const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ZeroByZero, casadi::ConstantDM, and casadi::ConstantMX.
Definition at line 390 of file mx_node.cpp.
Referenced by casadi::ConstantMX::getDot().
{
     casadi_error(string("MXNode::getMatrixValue not defined for class ")
                  + typeid(*this).name());
   }
MX casadi::MXNode::getMonitor (const std::string & comment) const inherited
Definition at line 720 of file mx_node.cpp.
Referenced by casadi::MX::monitor().
{
     if (nnz()==0) {
       return shared_from_this<MX>();
     } else {
       return MX::create(new Monitor(shared_from_this<MX>(), comment));
     }
   }
MX casadi::MXNode::getMultiplication (const MX & y, const MX & z) const virtual inherited
Definition at line 417 of file mx_node.cpp.
References casadi::GenericMatrix< MatType >::dim(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::size1(), and casadi::GenericMatrix< MatType >::size2().
Referenced by casadi::MX::mac().
{
     // Get reference to transposed first argument
     MX x = shared_from_this<MX>();
     casadi_assert_message(y.size2()==z.size2(), "Dimension error. Got y=" << y.size2()
                           << " and z=" << z.dim() << ".");
     casadi_assert_message(x.size1()==z.size1(), "Dimension error. Got x="
                           << x.dim() << " and z=" << z.dim() << ".");
     casadi_assert_message(y.size1()==x.size2(), "Dimension error. Got y=" << y.size1()
                           << " and x" << x.dim() << ".");
     if (x.is_dense() && y.is_dense() && z.is_dense()) {
       return MX::create(new DenseMultiplication(z, x, y));
     } else {
       return MX::create(new Multiplication(z, x, y));
     }
   }
MX casadi::MXNode::getNorm1 () const virtual inherited
Definition at line 777 of file mx_node.cpp.
Referenced by casadi::MX::norm_1().
{
     return MX::create(new Norm1(shared_from_this<MX>()));
   }
MX casadi::MXNode::getNorm2 () const virtual inherited
Definition at line 769 of file mx_node.cpp.
Referenced by casadi::MX::norm_2().
{
     return MX::create(new Norm2(shared_from_this<MX>()));
   }
MX casadi::MXNode::getNormF () const virtual inherited
Definition at line 765 of file mx_node.cpp.
Referenced by casadi::MX::norm_F().
{
     return MX::create(new NormF(shared_from_this<MX>()));
   }
MX casadi::MXNode::getNormInf () const virtual inherited
Definition at line 773 of file mx_node.cpp.
Referenced by casadi::MX::norm_inf().
{
     return MX::create(new NormInf(shared_from_this<MX>()));
   }
MX casadi::MXNode::getOutput (int oind) const virtual inherited
Reimplemented in casadi::MultipleOutput.
Definition at line 376 of file mx_node.cpp.
Referenced by casadi::MX::getOutput().
{
     casadi_assert_message(oind==0, "Output index out of bounds");
     return shared_from_this<MX>();
   }
MX casadi::MXNode::getProject (const Sparsity & sp) const virtual inherited
Reimplemented in casadi::Constant< Value >, and casadi::ZeroByZero.
Definition at line 512 of file mx_node.cpp.
References casadi::Sparsity::nnz().
Referenced by casadi::GetNonzeros::evalAdj(), casadi::SetNonzeros< Add >::evalFwd(), casadi::Constant< Value >::getProject(), and casadi::MX::project().
{
     if (sp==sparsity()) {
       return shared_from_this<MX>();
     } else if (sp.nnz()==0) {
       return MX::zeros(sp);
     } else {
       return MX::create(new Project(shared_from_this<MX>(), sp));
     }
   }
MX casadi::MXNode::getRank1 (const MX & alpha, const MX & x, const MX & y) const virtual inherited
Definition at line 438 of file mx_node.cpp.
Referenced by casadi::MX::_rank1().
{
     return MX::create(new Rank1(shared_from_this<MX>(), alpha, x, y));
   }
MX casadi::MXNode::getRef (const Slice & i, const Slice & j) const virtual inherited
Definition at line 522 of file mx_node.cpp.
{
     return MX::create(new SubRef(shared_from_this<MX>(), i, j));
   }
MX casadi::MXNode::getRepmat (int m, int n) const virtual inherited
Definition at line 859 of file mx_node.cpp.
Referenced by casadi::MX::repmat().
{
     if (n==1) {
       return MX::create(new HorzRepmat(shared_from_this<MX>(), m));
     } else {
       // Fallback to generic_matrix impl
       return GenericMatrix<MX>::repmat(shared_from_this<MX>(), n, m);
     }
   }
MX casadi::MXNode::getRepsum (int m, int n) const virtual inherited
Definition at line 868 of file mx_node.cpp.
Referenced by casadi::MX::repsum().
{
     if (n==1) {
       return MX::create(new HorzRepsum(shared_from_this<MX>(), m));
     } else {
       // Fallback to generic_matrix impl
       return GenericMatrix<MX>::repsum(shared_from_this<MX>(), n, m);
     }
   }
MX casadi::MXNode::getReshape (const Sparsity & sp) const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ZeroByZero, and casadi::Reshape.
Definition at line 407 of file mx_node.cpp.
References casadi::Sparsity::isReshape().
Referenced by casadi::MX::reshape().
{
     casadi_assert(sp.isReshape(sparsity()));
     if (sp==sparsity()) {
       return shared_from_this<MX>();
     } else {
       return MX::create(new Reshape(shared_from_this<MX>(), sp));
     }
   }
MX casadi::MXNode::getSetNonzeros (const MX & y, const std::vector< int > & nz) const virtual inherited
Reimplemented in casadi::Constant< Value >, and casadi::ZeroByZero.
Definition at line 467 of file mx_node.cpp.
References casadi::is_slice(), casadi::is_slice2(), casadi::simplify(), casadi::to_slice(), and casadi::to_slice2().
Referenced by casadi::SetNonzeros< Add >::eval_mx(), casadi::SetNonzeros< Add >::evalAdj(), casadi::SetNonzeros< Add >::evalFwd(), casadi::Constant< Value >::getSetNonzeros(), casadi::MX::set(), casadi::MX::set_nz(), and casadi::MX::unite().
{
     // Check if any element needs to be set at all
     bool set_any = false;
     for (vector<int>::const_iterator i=nz.begin(); i!=nz.end() && !set_any; ++i) {
       set_any = *i >= 0;
     }
     // Quick return
     if (!set_any) {
       return y;
     }
     // Check if slice
     MX ret;
     if (is_slice(nz)) {
       ret = MX::create(new SetNonzerosSlice<false>(y, shared_from_this<MX>(), to_slice(nz)));
     } else if (is_slice2(nz)) {
       pair<Slice, Slice> sl = to_slice2(nz);
       ret = MX::create(new SetNonzerosSlice2<false>(y, shared_from_this<MX>(),
                                                     sl.first, sl.second));
     } else {
       ret = MX::create(new SetNonzerosVector<false>(y, shared_from_this<MX>(), nz));
     }
     return simplify(ret);
   }
MX casadi::MXNode::getSolve (const MX & r, bool tr, const Function & linear_solver) const virtual inherited
For system Ax = b:
A->getSolve(b)
Definition at line 442 of file mx_node.cpp.
References casadi::densify().
Referenced by casadi::Rootfinder::forward(), casadi::Linsol::linsol_solve(), and casadi::Rootfinder::reverse().
{
     if (tr) {
       return MX::create(new Solve<true>(densify(r), shared_from_this<MX>(), linear_solver));
     } else {
       return MX::create(new Solve<false>(densify(r), shared_from_this<MX>(), linear_solver));
     }
   }
MX casadi::MXNode::getTranspose () const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ZeroByZero, casadi::Reshape, and casadi::Transpose.
Definition at line 395 of file mx_node.cpp.
Referenced by casadi::MX::T().
{
     if (sparsity().is_scalar()) {
       return shared_from_this<MX>();
     } else if (sparsity().is_vector()) {
       return getReshape(sparsity().T());
     } else if (sparsity().is_dense()) {
       return MX::create(new DenseTranspose(shared_from_this<MX>()));
     } else {
       return MX::create(new Transpose(shared_from_this<MX>()));
     }
   }
MX casadi::MXNode::getUnary (int op) const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ZeroByZero, casadi::BinaryMX< ScX, ScY >, and casadi::UnaryMX.
Definition at line 530 of file mx_node.cpp.
References casadi::is_zero().
Referenced by casadi::Constant< Value >::getBinary(), casadi::UnaryMX::getUnary(), casadi::BinaryMX< ScX, ScY >::getUnary(), casadi::MX::operator-(), and casadi::MX::unary().
{
     if (operation_checker<F0XChecker>(op) && is_zero()) {
       // If identically zero
       return MX::zeros(sparsity());
     } else {
       // Create a new node
       return MX::create(new UnaryMX(Operation(op), shared_from_this<MX>()));
     }
   }
MX casadi::MXNode::getVertcat (const std::vector< MX > & x) const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::Vertsplit, and casadi::OutputNode.
Definition at line 807 of file mx_node.cpp.
References casadi::OP_VERTCAT.
Referenced by casadi::OutputNode::getVertcat(), casadi::Vertsplit::getVertcat(), and casadi::Constant< Value >::getVertcat().
{
     // Check if there is any existing vertcat operation
     for (vector<MX>::const_iterator i=x.begin(); i!=x.end(); ++i) {
       if (i->op()==OP_VERTCAT) {
         // Split up
         vector<MX> x_split(x.begin(), i);
         for (; i!=x.end(); ++i) {
           if (i->op()==OP_VERTCAT) {
             x_split.insert(x_split.end(), (*i)->dep_.begin(), (*i)->dep_.end());
           } else {
             x_split.push_back(*i);
           }
         }
         return vertcat(x_split);
       }
     }
     return MX::create(new Vertcat(x));
   }
vector< MX > casadi::MXNode::getVertsplit (const std::vector< int > & output_offset) const virtual inherited
Definition at line 893 of file mx_node.cpp.
References casadi::is_zero(), and casadi::OP_VERTCAT.
Referenced by casadi::MX::vertsplit().
{
     if (is_zero()) {
       vector<MX> ret =
           MX::createMultipleOutput(new Vertsplit(shared_from_this<MX>(), output_offset));
       for (int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     vector<MX> ret =
         MX::createMultipleOutput(new Vertsplit(shared_from_this<MX>(), output_offset));
     if (GlobalOptions::simplification_on_the_fly) {
       // Simplify vertsplit(vertcat)
       if (op()==OP_VERTCAT) {
         int offset_deps = 0;
         int j = 0;
         for (int i=0;i<output_offset.size();++i) {
           while (offset_deps<output_offset[i]) { offset_deps+=dep(j).size1();++j; }
           if (j>=ndep()) j = ndep()-1;
           if (output_offset[i]==offset_deps &&
               (i+1<output_offset.size()?output_offset[i+1]:size1()) ==
                offset_deps +dep(j).size1()) {
             // Aligned with vertcat dependency
             ret[i] = dep(j);
           }
         }
       }
     }
     return ret;
   }
bool casadi::MXNode::has_duplicates () virtual inherited
Reimplemented in casadi::ConstantMX, casadi::Reshape, casadi::SymbolicMX, and casadi::Concat.
Definition at line 130 of file mx_node.cpp.
Referenced by casadi::Concat::has_duplicates(), and casadi::MX::has_duplicates().
{
     throw CasadiException(string("MXNode::has_duplicates() not defined for class ")
                           + typeid(*this).name());
   }
virtual bool casadi::MXNode::has_refcount () const inline virtual inherited
Reimplemented in casadi::Call.
Definition at line 130 of file mx_node.hpp.
 { return false;}
virtual bool casadi::MXNode::hasDep () const inline virtual inherited
Definition at line 229 of file mx_node.hpp.
 {return ndep()>0; }
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
virtual bool casadi::MXNode::is_binaryOp () const inline virtual inherited
Reimplemented in casadi::BinaryMX< ScX, ScY >.
Definition at line 108 of file mx_node.hpp.
 { return false;}
bool casadi::MXNode::is_equal (const MXNode * x, const MXNode * y, int depth) static inherited
Definition at line 940 of file mx_node.cpp.
References casadi::MXNode::is_equal().
Referenced by casadi::MXNode::is_equal(), and casadi::MX::is_equal().
{
     if (x==y) {
       return true;
     } else if (depth>0) {
       return x->is_equal(y, depth);
     } else {
       return false;
     }
   }
virtual bool casadi::MXNode::is_equal (const MXNode * node, int depth) const inline virtual inherited
Reimplemented in casadi::SetNonzerosSlice2< Add >, casadi::GetNonzerosSlice2, casadi::ConstantDM, casadi::SetNonzerosSlice< Add >, casadi::GetNonzerosSlice, casadi::SetNonzerosVector< Add >, casadi::GetNonzerosVector, casadi::BinaryMX< ScX, ScY >, casadi::Transpose, casadi::Reshape, casadi::UnaryMX, casadi::Multiplication, and casadi::Concat.
Definition at line 212 of file mx_node.hpp.
 { return false;}
virtual bool casadi::MXNode::is_identity () const inline virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ConstantDM, and casadi::GetNonzerosSlice.
Definition at line 102 of file mx_node.hpp.
 { return false;}
virtual bool casadi::MXNode::is_one () const inline virtual inherited
Reimplemented in casadi::Constant< Value >, and casadi::ConstantDM.
Definition at line 96 of file mx_node.hpp.
 { return false;}
virtual bool casadi::MXNode::is_unaryOp () const inline virtual inherited
Reimplemented in casadi::UnaryMX.
Definition at line 105 of file mx_node.hpp.
 { return false;}
virtual bool casadi::MXNode::is_valid_input () const inline virtual inherited
Reimplemented in casadi::ZeroByZero, casadi::ConstantMX, casadi::Reshape, casadi::SymbolicMX, and casadi::Concat.
Definition at line 169 of file mx_node.hpp.
Referenced by casadi::Concat::is_valid_input().
 { return false;}
virtual bool casadi::MXNode::is_zero () const inline virtual inherited
Reimplemented in casadi::Constant< Value >, and casadi::ConstantDM.
Definition at line 93 of file mx_node.hpp.
Referenced by casadi::MX::densify(), casadi::Constant< Value >::getBinary(), casadi::MXNode::getBinary(), and casadi::Constant< Value >::getSetNonzeros().
 { return false;}
virtual bool casadi::MXNode::isMultipleOutput () const inline virtual inherited
Reimplemented in casadi::MultipleOutput.
Definition at line 193 of file mx_node.hpp.
Referenced by casadi::MXFunction::init().
 {return false;}
virtual bool casadi::MXNode::isNonLinear () inline virtual inherited
Reimplemented in casadi::OutputNode.
Definition at line 251 of file mx_node.hpp.
 {return false;}
virtual bool casadi::MXNode::isOutputNode () const inline virtual inherited
Reimplemented in casadi::OutputNode.
Definition at line 190 of file mx_node.hpp.
Referenced by casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::getHorzcat(), and casadi::Vertsplit::getVertcat().
 {return false;}
virtual bool casadi::MXNode::isValue (double val) const inline virtual inherited
Reimplemented in casadi::Constant< Value >.
Definition at line 99 of file mx_node.hpp.
Referenced by casadi::MXNode::getBinary().
 { return false;}
MX casadi::MXNode::join_primitives (std::vector< MX >::const_iterator & it) const virtual inherited
Reimplemented in casadi::Diagcat, casadi::Vertcat, casadi::Horzcat, casadi::ConstantMX, casadi::Reshape, and casadi::SymbolicMX.
Definition at line 150 of file mx_node.cpp.
Referenced by casadi::Horzcat::join_primitives(), casadi::Vertcat::join_primitives(), casadi::Diagcat::join_primitives(), and casadi::MX::join_primitives().
{
     throw CasadiException(string("MXNode::join_primitives() not defined for class ")
                           + typeid(*this).name());
   }
Matrix< int > casadi::MXNode::mapping () const virtual inherited
Reimplemented in casadi::SetNonzeros< Add >, and casadi::GetNonzeros.
Definition at line 702 of file mx_node.cpp.
{
     throw CasadiException(string("MXNode::mapping not defined for class ") + typeid(*this).name());
   }
static bool casadi::MXNode::maxDepth () inline static inherited
Definition at line 215 of file mx_node.hpp.
References casadi::MX::getEqualityCheckingDepth().
Referenced by casadi::UnaryMX::getBinary().
 { return MX::getEqualityCheckingDepth();}
int casadi::MXNode::n_primitives () const virtual inherited
Reimplemented in casadi::ConstantMX, casadi::Reshape, casadi::SymbolicMX, and casadi::Concat.
Definition at line 125 of file mx_node.cpp.
Referenced by casadi::Concat::n_primitives().
{
     throw CasadiException(string("MXNode::n_primitives() not defined for class ")
                           + typeid(*this).name());
   }
const string & casadi::MXNode::name () const virtual inherited
Reimplemented in casadi::ZeroByZero, and casadi::SymbolicMX.
Definition at line 155 of file mx_node.cpp.
{
     throw CasadiException(string("MXNode::name() not defined for class ")
                           + typeid(*this).name());
   }
int casadi::MXNode::ndep () const inherited
Definition at line 173 of file mx_node.cpp.
References casadi::GenericMatrix< MatType >::size().
Referenced by casadi::Call::evalAdj(), casadi::Horzcat::evalAdj(), casadi::Vertcat::evalAdj(), casadi::Diagcat::evalAdj(), casadi::Call::evalFwd(), casadi::Concat::has_duplicates(), casadi::MXFunction::init(), casadi::Concat::is_valid_input(), casadi::Horzcat::join_primitives(), casadi::Vertcat::join_primitives(), casadi::Diagcat::join_primitives(), casadi::Concat::n_primitives(), casadi::Horzcat::offset(), casadi::Vertcat::offset(), casadi::Diagcat::offset(), casadi::Concat::primitives(), casadi::Call::print(), casadi::Horzcat::print(), casadi::Vertcat::print(), casadi::Diagcat::print(), casadi::Concat::resetInput(), and casadi::MXNode::sameOpAndDeps().
{
     return dep_.size();
   }
int casadi::MXNode::nnz (int i = 0) const inline inherited
Definition at line 245 of file mx_node.hpp.
Referenced by casadi::UnaryMX::eval(), casadi::Assertion::eval(), casadi::Monitor::eval(), casadi::UnaryMX::eval_sx(), casadi::Assertion::eval_sx(), casadi::Monitor::eval_sx(), casadi::HorzRepmat::evalGen(), casadi::HorzRepsum::evalGen(), casadi::Monitor::generate(), casadi::Split::generate(), casadi::Assertion::generate(), casadi::UnaryMX::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::SetNonzerosVector< Add >::SetNonzerosVector(), casadi::Monitor::spAdj(), casadi::Assertion::spAdj(), casadi::HorzRepmat::spAdj(), casadi::UnaryMX::spAdj(), casadi::SymbolicMX::spAdj(), casadi::HorzRepsum::spAdj(), casadi::Assertion::spFwd(), casadi::Monitor::spFwd(), casadi::UnaryMX::spFwd(), casadi::HorzRepmat::spFwd(), casadi::SymbolicMX::spFwd(), and casadi::HorzRepsum::spFwd().
 { return sparsity(i).nnz(); }
virtual int casadi::MXNode::nout () const inline virtual inherited
Reimplemented in casadi::Call, casadi::MultipleOutput, and casadi::Split.
Definition at line 232 of file mx_node.hpp.
Referenced by casadi::MX::createMultipleOutput(), and casadi::MXFunction::init().
 { return 1;}
int casadi::MXNode::numel () const inline inherited
Definition at line 244 of file mx_node.hpp.
 { return sparsity().numel(); }
virtual int casadi::MXNode::numFunctions () const inline virtual inherited
Reimplemented in casadi::Call, casadi::Solve< Tr >, and casadi::GenericCall.
Definition at line 196 of file mx_node.hpp.
 {return 0;}
virtual int casadi::MXNode::numInplace () const inline virtual inherited
Reimplemented in casadi::Reshape, casadi::Multiplication, casadi::Solve< Tr >, casadi::BinaryMX< ScX, ScY >, casadi::UnaryMX, casadi::Assertion, casadi::Monitor, casadi::Rank1, and casadi::SetNonzeros< Add >.
Definition at line 306 of file mx_node.hpp.
 { return 0;}
virtual int casadi::Project::op () const inline virtual
Implements casadi::MXNode.
Definition at line 81 of file project.hpp.
References casadi::OP_PROJECT.
 { return OP_PROJECT;}
void casadi::MXNode::primitives (std::vector< MX >::iterator & it) const virtual inherited
Reimplemented in casadi::ConstantMX, casadi::Reshape, casadi::SymbolicMX, and casadi::Concat.
Definition at line 140 of file mx_node.cpp.
Referenced by casadi::Concat::primitives().
{
     throw CasadiException(string("MXNode::primitives() not defined for class ")
                           + typeid(*this).name());
   }
std::string casadi::Project::print (const std::vector< std::string > & arg) const virtual
Implements casadi::MXNode.
Definition at line 40 of file project.cpp.
{
     if (sparsity().is_dense()) {
       return "dense(" + arg.at(0) + ")";
     } else {
       return "project(" + arg.at(0) + ")";
     }
   }
void casadi::MXNode::print (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Definition at line 228 of file mx_node.cpp.
Referenced by casadi::MXFunction::print(), and casadi::MX::print_operator().
{
     // Find out which noded can be inlined
     std::map<const MXNode*, int> nodeind;
     can_inline(nodeind);
     // Print expression
     vector<string> intermed;
     string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
std::string casadi::MXNode::print_compact (std::map< const MXNode *, int > & nodeind, std::vector< std::string > & intermed) const inherited
Definition at line 262 of file mx_node.cpp.
References casadi::print().
{
     // Get reference to node index
     int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) return "@" + CodeGenerator::to_string(ind);
     // Get expressions for dependencies
     vector<string> arg(ndep());
     for (int i=0; i<arg.size(); ++i) {
       arg[i] = dep(i)->print_compact(nodeind, intermed);
     }
     // Get expression for this
     string s = print(arg);
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       return "@" + CodeGenerator::to_string(ind);
     }
   }
void casadi::MXNode::repr (std::ostream & stream) const virtual inherited
Reimplemented from casadi::SharedObjectNode.
Definition at line 222 of file mx_node.cpp.
References casadi::print().
{
     stream << "MX(";
     print(stream);
     stream << ")";
   }
void casadi::MXNode::resetInput () virtual inherited
Reimplemented in casadi::ConstantMX, casadi::Reshape, casadi::SymbolicMX, and casadi::Concat.
Definition at line 135 of file mx_node.cpp.
Referenced by casadi::Concat::resetInput().
{
     throw CasadiException(string("MXNode::resetInput() not defined for class ")
                           + typeid(*this).name());
   }
bool casadi::MXNode::sameOpAndDeps (const MXNode * node, int depth) const inherited
Definition at line 706 of file mx_node.cpp.
References casadi::MXNode::dep(), casadi::MXNode::ndep(), and casadi::MXNode::op().
{
     if (op()!=node->op() || ndep()!=node->ndep())
       return false;
     for (int i=0; i<ndep(); ++i) {
       if (!MX::is_equal(dep(i), node->dep(i), depth-1))
         return false;
     }
     return true;
   }
void casadi::MXNode::setDependencies (const MX & dep) inherited
Definition at line 181 of file mx_node.cpp.
References casadi::Sparsity::resize().
Referenced by casadi::Assertion::Assertion(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), casadi::Call::Call(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::Monitor::Monitor(), casadi::OutputNode::OutputNode(), casadi::Solve< Tr >::Solve(), casadi::Split::Split(), casadi::SubAssign::SubAssign(), casadi::SubRef::SubRef(), and casadi::UnaryMX::UnaryMX().
{
     dep_.resize(1);
     dep_[0] = dep;
   }
void casadi::MXNode::setDependencies (const MX & dep1, const MX & dep2) inherited
Definition at line 186 of file mx_node.cpp.
{
     dep_.resize(2);
     dep_[0] = dep1;
     dep_[1] = dep2;
   }
void casadi::MXNode::setDependencies (const MX & dep1, const MX & dep2, const MX & dep3) inherited
Definition at line 192 of file mx_node.cpp.
{
     dep_.resize(3);
     dep_[0] = dep1;
     dep_[1] = dep2;
     dep_[2] = dep3;
   }
void casadi::MXNode::setDependencies (const std::vector< MX > & dep) inherited
void casadi::MXNode::setSparsity (const Sparsity & sparsity) inherited
Definition at line 177 of file mx_node.cpp.
Referenced by casadi::Assertion::Assertion(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), casadi::Call::Call(), casadi::Diagcat::Diagcat(), casadi::Horzcat::Horzcat(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::Monitor::Monitor(), casadi::OutputNode::OutputNode(), casadi::Solve< Tr >::Solve(), casadi::Split::Split(), casadi::SymbolicMX::SymbolicMX(), casadi::UnaryMX::UnaryMX(), and casadi::Vertcat::Vertcat().
{
     sparsity_ = sparsity;
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
virtual void casadi::MXNode::simplifyMe (MX & ex) inline virtual inherited
Reimplemented in casadi::SetNonzerosSlice< Add >, and casadi::GetNonzerosSlice.
Definition at line 309 of file mx_node.hpp.
Referenced by casadi::MX::simplify().
 {}
std::pair<int, int> casadi::MXNode::size () const inline inherited
Definition at line 248 of file mx_node.hpp.
Referenced by casadi::SymbolicMX::join_primitives(), and casadi::MX::shared().
 { return sparsity().size();}
int casadi::MXNode::size1 () const inline inherited
Definition at line 246 of file mx_node.hpp.
 { return sparsity().size1(); }
int casadi::MXNode::size2 () const inline inherited
Definition at line 247 of file mx_node.hpp.
 { return sparsity().size2(); }
void casadi::Project::spAdj (bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem) virtual
Reimplemented from casadi::MXNode.
Definition at line 85 of file project.cpp.
References casadi::fill().
{
     dep().sparsity().bor(arg[0], res[0], sparsity());
     fill(res[0], res[0]+nnz(), 0);
   }
const Sparsity& casadi::MXNode::sparsity () const inline inherited
Definition at line 238 of file mx_node.hpp.
Referenced by casadi::Diagcat::Diagcat(), casadi::HorzRepsum::evalGen(), casadi::UnaryMX::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Horzcat::Horzcat(), casadi::Reshape::is_equal(), casadi::GetNonzerosVector::is_equal(), casadi::SetNonzerosVector< Add >::is_equal(), casadi::GetNonzerosSlice::is_equal(), casadi::SetNonzerosSlice< Add >::is_equal(), casadi::ConstantDM::is_equal(), casadi::GetNonzerosSlice2::is_equal(), casadi::SetNonzerosSlice2< Add >::is_equal(), casadi::OutputNode::OutputNode(), casadi::Split::spAdj(), casadi::HorzRepsum::spAdj(), casadi::Split::spFwd(), casadi::HorzRepsum::spFwd(), casadi::UnaryMX::UnaryMX(), and casadi::Vertcat::Vertcat().
 { return sparsity_;}
const Sparsity & casadi::MXNode::sparsity (int oind) const virtual inherited
Reimplemented in casadi::Call, casadi::MultipleOutput, and casadi::Split.
Definition at line 217 of file mx_node.cpp.
{
     casadi_assert_message(oind==0, "Index out of bounds");
     return sparsity_;
   }
void casadi::Project::spFwd (const bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem) virtual
Reimplemented from casadi::MXNode.
Definition at line 81 of file project.cpp.
{
     sparsity().set(res[0], arg[0], dep().sparsity());
   }
void casadi::MXNode::split_primitives (const MX & x, std::vector< MX >::iterator & it) const virtual inherited
Reimplemented in casadi::Diagcat, casadi::Vertcat, casadi::Horzcat, casadi::ConstantMX, casadi::Reshape, and casadi::SymbolicMX.
Definition at line 145 of file mx_node.cpp.
Referenced by casadi::Horzcat::split_primitives(), casadi::Vertcat::split_primitives(), and casadi::Diagcat::split_primitives().
{
     throw CasadiException(string("MXNode::split_primitives() not defined for class ")
                           + typeid(*this).name());
   }
virtual size_t casadi::MXNode::sz_arg () const inline virtual inherited
Reimplemented in casadi::Call, and casadi::Solve< Tr >.
Definition at line 257 of file mx_node.hpp.
 { return ndep();}
virtual size_t casadi::MXNode::sz_iw () const inline virtual inherited
Reimplemented in casadi::Call, casadi::DenseTranspose, casadi::Solve< Tr >, and casadi::Transpose.
Definition at line 263 of file mx_node.hpp.
 { return 0;}
virtual size_t casadi::MXNode::sz_res () const inline virtual inherited
Reimplemented in casadi::Call, and casadi::Solve< Tr >.
Definition at line 260 of file mx_node.hpp.
 { return nout();}
virtual size_t casadi::Project::sz_w () const inline virtual
Reimplemented from casadi::MXNode.
Definition at line 84 of file project.hpp.
 { return size1();}
double casadi::MXNode::to_double () const virtual inherited
Reimplemented in casadi::Constant< Value >, casadi::ZeroByZero, casadi::ConstantDM, and casadi::ConstantMX.
Definition at line 386 of file mx_node.cpp.
Referenced by casadi::Constant< Value >::getBinary().
{
     casadi_error(string("MXNode::to_double not defined for class ") + typeid(*this).name());
   }
static MX casadi::MXNode::toMatrix (const MX & x, const Sparsity & sp) inline static inherited
Definition at line 291 of file mx_node.hpp.
References casadi::GenericMatrix< MatType >::size(), and casadi::Sparsity::size().
{
       if (x.size()==sp.size()) {
         return x;
       } else {
         return MX(sp, x);
       }
     }
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Member Data Documentation
std::vector<MX> casadi::MXNode::dep_ inherited
Definition at line 427 of file mx_node.hpp.
Referenced by casadi::MXNode::~MXNode().
Sparsity casadi::MXNode::sparsity_ inherited
Definition at line 430 of file mx_node.hpp.
int casadi::MXNode::temp inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 424 of file mx_node.hpp.
Referenced by casadi::SymbolicMX::has_duplicates(), casadi::MXFunction::init(), and casadi::SymbolicMX::resetInput().
The documentation for this class was generated from the following files:
project.hpp
project.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge