CasADi: Qpsol
Qpsol
Functions
CASADI_EXPORT Function casadi::qpsol (const std::string &name, const std::string &solver, const SpDict &qp, const Dict &opts=Dict())
Function casadi::qpsol (const std::string &name, const std::string &solver, const SXDict &qp, const Dict &opts)
Function casadi::qpsol (const std::string &name, const std::string &solver, const MXDict &qp, const Dict &opts)
vector< string > casadi::qpsol_in ()
Get input scheme of QP solvers.
vector< string > casadi::qpsol_out ()
Get QP solver output scheme of QP solvers.
string casadi::qpsol_in (int ind)
Get QP solver input scheme name by index.
string casadi::qpsol_out (int ind)
Get output scheme name by index.
int casadi::qpsol_n_in ()
Get the number of QP solver inputs.
int casadi::qpsol_n_out ()
Get the number of QP solver outputs.
CASADI_EXPORT bool casadi::has_qpsol (const std::string &name)
Check if a particular plugin is available.
CASADI_EXPORT void casadi::load_qpsol (const std::string &name)
Explicitly load a plugin dynamically.
CASADI_EXPORT std::string casadi::doc_qpsol (const std::string &name)
Get the documentation string for a plugin.
Detailed Description
Create a QP solver Solves the following strictly convex problem:
min          1/2 x' H x + g' x
x
subject to
LBA <= A x <= UBA
LBX <= x   <= UBX
with :
H sparse (n x n) positive definite
g dense  (n x 1)
n: number of decision variables (x)
nc: number of constraints (A)
If H is not positive-definite, the solver should throw an error.
General information
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". casadi::FunctionInternal
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
discrete OT_BOOLVECTOR Indicates which of the variables are discrete, i.e. integer-valued casadi::Qpsol
gather_stats OT_BOOL Flag to indicate whether statistics must be gathered casadi::FunctionInternal
input_scheme OT_STRINGVECTOR Custom input scheme casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
monitor OT_STRINGVECTOR Monitors to be activated casadi::FunctionInternal
output_scheme OT_STRINGVECTOR Custom output scheme casadi::FunctionInternal
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::FunctionInternal
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::FunctionInternal
Input scheme: casadi::QpsolInput (QPSOL_NUM_IN = 9) []
Full name Short Description
QPSOL_H The square matrix H: sparse, (n x n). Only the lower triangular part is actually used. The matrix is assumed to be symmetrical.
QPSOL_G The vector g: dense, (n x 1)
QPSOL_A The matrix A: sparse, (nc x n) - product with x must be dense.
QPSOL_LBA dense, (nc x 1)
QPSOL_UBA dense, (nc x 1)
QPSOL_LBX dense, (n x 1)
QPSOL_UBX dense, (n x 1)
QPSOL_X0 dense, (n x 1)
QPSOL_LAM_X0 dense
Output scheme: casadi::QpsolOutput (QPSOL_NUM_OUT = 4) []
Full name Short Description
QPSOL_X The primal solution.
QPSOL_COST The optimal cost.
QPSOL_LAM_A The dual solution corresponding to linear bounds.
QPSOL_LAM_X The dual solution corresponding to simple bounds.
List of plugins
- cplex
- gurobi
- ooqp
- qpoases
- sqic
- nlp
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Qpsol.doc("myextraplugin")
cplex
Interface to Cplex solver for sparse Quadratic Programs
List of available options
Id Type Description
cplex OT_DICT Options to be passed to CPLEX
dep_check OT_INT Detect redundant constraints.
dump_filename OT_STRING The filename to dump to.
dump_to_file OT_BOOL Dumps QP to file in CPLEX format.
qp_method OT_INT Determines which CPLEX algorithm to use.
tol OT_DOUBLE Tolerance of solver
warm_start OT_BOOL Use warm start with simplex methods (affects only the simplex methods).
gurobi
Interface to the GUROBI Solver for quadratic programming
List of available options
Id Type Description
vtype OT_STRINGVECTOR Type of variables: [CONTINUOUS|binary|integer|semicont|semiint]
ooqp
Interface to the OOQP Solver for quadratic programming The current implementation assumes that OOQP is configured with the MA27 sparse linear solver.
NOTE: when doing multiple calls to evaluate(), check if you need to reInit();
List of available options
Id Type Description
artol OT_DOUBLE tolerance as provided with setArTol to OOQP
mutol OT_DOUBLE tolerance as provided with setMuTol to OOQP
print_level OT_INT Print level. OOQP listens to print_level 0, 10 and 100
qpoases
Interface to QPOases Solver for quadratic programming
List of available options
Id Type Description
CPUtime OT_DOUBLE The maximum allowed CPU time in seconds for the whole initialisation (and the actually required one on output). Disabled if unset.
boundRelaxation OT_DOUBLE Initial relaxation of bounds to start homotopy and initial value for far bounds.
boundTolerance OT_DOUBLE If upper and lower bounds differ less than this tolerance, they are regarded equal, i.e. as equality constraint.
enableCholeskyRefactorisation OT_INT Specifies the frequency of a full re-factorisation of projected Hessian matrix: 0: turns them off, 1: uses them at each iteration etc.
enableDriftCorrection OT_INT Specifies the frequency of drift corrections: 0: turns them off.
enableEqualities OT_BOOL Specifies whether equalities should be treated as always active (True) or not (False)
enableFarBounds OT_BOOL Enables the use of far bounds.
enableFlippingBounds OT_BOOL Enables the use of flipping bounds.
enableFullLITests OT_BOOL Enables condition-hardened (but more expensive) LI test.
enableNZCTests OT_BOOL Enables nonzero curvature tests.
enableRamping OT_BOOL Enables ramping.
enableRegularisation OT_BOOL Enables automatic Hessian regularisation.
epsDen OT_DOUBLE Denominator tolerance for ratio tests.
epsFlipping OT_DOUBLE Tolerance of squared Cholesky diagonal factor which triggers flipping bound.
epsIterRef OT_DOUBLE Early termination tolerance for iterative refinement.
epsLITests OT_DOUBLE Tolerance for linear independence tests.
epsNZCTests OT_DOUBLE Tolerance for nonzero curvature tests.
epsNum OT_DOUBLE Numerator tolerance for ratio tests.
epsRegularisation OT_DOUBLE Scaling factor of identity matrix used for Hessian regularisation.
finalRamping OT_DOUBLE Final value for ramping strategy.
growFarBounds OT_DOUBLE Factor to grow far bounds.
initialFarBounds OT_DOUBLE Initial size for far bounds.
initialRamping OT_DOUBLE Start value for ramping strategy.
initialStatusBounds OT_STRING Initial status of bounds at first iteration.
maxDualJump OT_DOUBLE Maximum allowed jump in dual variables in linear independence tests.
maxPrimalJump OT_DOUBLE Maximum allowed jump in primal variables in nonzero curvature tests.
nWSR OT_INT The maximum number of working set recalculations to be performed during the initial homotopy. Default is 5(nx + nc)
numRefinementSteps OT_INT Maximum number of iterative refinement steps.
numRegularisationSteps OT_INT Maximum number of successive regularisation steps.
printLevel OT_STRING Defines the amount of text output during QP solution, see Section 5.7
sparse OT_BOOL Formulate the QP using sparse matrices. Default: false
terminationTolerance OT_DOUBLE Relative termination tolerance to stop homotopy.
sqic
Interface to the SQIC solver for quadratic programming
nlp
Solve QPs using an Nlpsol
List of available options
Id Type Description
nlpsol OT_STRING Name of solver.
nlpsol_options OT_DICT Options to be passed to solver.
Author
Joel Andersson
Date
2011-2015
Function Documentation
CASADI_EXPORT std::string casadi::doc_qpsol (const std::string & name)
CASADI_EXPORT bool casadi::has_qpsol (const std::string & name)
CASADI_EXPORT void casadi::load_qpsol (const std::string & name)
CASADI_EXPORT Function casadi::qpsol (const std::string & name, const std::string & solver, const SpDict & qp, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::qpsol (const std::string & name, const std::string & solver, const SXDict & qp, const Dict & opts)
Definition at line 199 of file qpsol.cpp.
References casadi::qpsol_nlp().
{
     return qpsol_nlp(name, solver, qp, opts);
   }
CASADI_EXPORT Function casadi::qpsol (const std::string & name, const std::string & solver, const MXDict & qp, const Dict & opts)
Definition at line 204 of file qpsol.cpp.
References casadi::qpsol_nlp().
Referenced by casadi::qpsol_nlp().
{
     return qpsol_nlp(name, solver, qp, opts);
   }
CASADI_EXPORT std::vector< std::string > casadi::qpsol_in ()
Definition at line 66 of file qpsol.cpp.
References casadi::qpsol_in(), and casadi::qpsol_n_in().
Referenced by casadi::Qpsol::get_name_in().
{
     vector<string> ret(qpsol_n_in());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=qpsol_in(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::qpsol_in (int ind)
Definition at line 78 of file qpsol.cpp.
References casadi::QPSOL_A, casadi::QPSOL_G, casadi::QPSOL_H, casadi::QPSOL_LAM_X0, casadi::QPSOL_LBA, casadi::QPSOL_LBX, casadi::QPSOL_NUM_IN, casadi::QPSOL_UBA, casadi::QPSOL_UBX, and casadi::QPSOL_X0.
Referenced by casadi::qpsol_in().
{
     switch (static_cast<QpsolInput>(ind)) {
     case QPSOL_H:      return "h";
     case QPSOL_G:      return "g";
     case QPSOL_A:      return "a";
     case QPSOL_LBA:    return "lba";
     case QPSOL_UBA:    return "uba";
     case QPSOL_LBX:    return "lbx";
     case QPSOL_UBX:    return "ubx";
     case QPSOL_X0:     return "x0";
     case QPSOL_LAM_X0: return "lam_x0";
     case QPSOL_NUM_IN: break;
     }
     return string();
   }
CASADI_EXPORT int casadi::qpsol_n_in ()
Definition at line 105 of file qpsol.cpp.
References casadi::QPSOL_NUM_IN.
Referenced by casadi::qpsol_in().
                    {
     return QPSOL_NUM_IN;
   }
CASADI_EXPORT int casadi::qpsol_n_out ()
Definition at line 109 of file qpsol.cpp.
References casadi::QPSOL_NUM_OUT.
Referenced by casadi::qpsol_out().
                     {
     return QPSOL_NUM_OUT;
   }
CASADI_EXPORT std::vector< std::string > casadi::qpsol_out ()
Definition at line 72 of file qpsol.cpp.
References casadi::qpsol_n_out(), and casadi::qpsol_out().
Referenced by casadi::Qpsol::get_name_out().
{
     vector<string> ret(qpsol_n_out());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=qpsol_out(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::qpsol_out (int ind)
Definition at line 94 of file qpsol.cpp.
References casadi::QPSOL_COST, casadi::QPSOL_LAM_A, casadi::QPSOL_LAM_X, casadi::QPSOL_NUM_OUT, and casadi::QPSOL_X.
Referenced by casadi::qpsol_out().
{
     switch (static_cast<QpsolOutput>(ind)) {
     case QPSOL_X:     return "x";
     case QPSOL_COST:  return "cost";
     case QPSOL_LAM_A: return "lam_a";
     case QPSOL_LAM_X: return "lam_x";
     case QPSOL_NUM_OUT: break;
     }
     return string();
   }
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge