CasADi: casadi::XmlFile Class Reference
casadi::XmlFile Class Reference
XML parser Can be used for parsing XML files into CasADi data structures.
#include <xml_file.hpp>
Detailed Description
Author
Joel Andersson
Date
2014
Definition at line 44 of file xml_file.hpp.
Public Member Functions
XmlFile ()
XmlFile (const std::string &name)
~XmlFile ()
XmlFileInternal * operator-> ()
Access functions of the node.
const XmlFileInternal * operator-> () const
Const access functions of the node.
XmlNode parse (const std::string &filename)
void assignNode (SharedObjectNode *node)
void assignNodeNoCount (SharedObjectNode *node)
Assign the node to a node class pointer without reference counting.
SharedObjectNode * get () const
Get a const pointer to the node.
int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void printPtr (std::ostream &stream=casadi::userOut()) const
bool is_null () const
Is a null pointer?
WeakRef * weak ()
Get a weak reference to the object.
size_t __hash__ () const
Returns a number that is unique for a given Node. If the Object does not point to any node, "0" is returned.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
Static Public Member Functions
static void loadPlugin (const std::string &name)
Load a plugin dynamically.
static std::string doc (const std::string &name)
Get solver specific documentation.
Protected Member Functions
void count_up ()
void count_down ()
Constructor & Destructor Documentation
casadi::XmlFile::XmlFile ()
Definition at line 31 of file xml_file.cpp.
                    {
   }
casadi::XmlFile::XmlFile (const std::string & name)
Definition at line 34 of file xml_file.cpp.
{
     assignNode(XmlFileInternal::getPlugin(name).creator());
   }
casadi::XmlFile::~XmlFile ()
Definition at line 38 of file xml_file.cpp.
                     {
   }
Member Function Documentation
size_t casadi::SharedObject::__hash__ () const inherited
Definition at line 178 of file shared_object.cpp.
{
     return reinterpret_cast<size_t>(get());
   }
void casadi::SharedObject::assignNode (SharedObjectNode * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 57 of file shared_object.cpp.
Referenced by casadi::Function::conditional(), casadi::Callback::construct(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::Sparsity::create(), casadi::Function::create(), casadi::external(), casadi::Function::if_else(), casadi::MXFunction::init(), casadi::integrator(), casadi::jit(), casadi::Function::kernel_sum(), casadi::linsol(), casadi::nlpsol(), casadi::qpsol(), casadi::rootfinder(), and casadi::WeakRef::shared().
{
     count_down();
     node = node_;
     count_up();
   }
void casadi::SharedObject::assignNodeNoCount (SharedObjectNode * node) inherited
improper use will cause memory leaks!
Definition at line 63 of file shared_object.cpp.
{
     node = node_;
   }
void casadi::SharedObject::count_down () protected inherited
Definition at line 92 of file shared_object.cpp.
Referenced by casadi::Callback::transfer_ownership().
{
     if (node && --node->count == 0) {
       delete node;
       node = 0;
     }
   }
void casadi::SharedObject::count_up () protected inherited
Definition at line 88 of file shared_object.cpp.
{
     if (node) node->count++;
   }
std::string casadi::XmlFile::doc (const std::string & name) static
Definition at line 57 of file xml_file.cpp.
{
     return XmlFileInternal::getPlugin(name).doc;
   }
SharedObjectNode * casadi::SharedObject::get () const inherited
Definition at line 80 of file shared_object.cpp.
Referenced by casadi::CodeGenerator::addSparsity(), casadi::CodeGenerator::get_sparsity(), casadi::SparsityInternal::is_equal(), casadi::SparsityInternal::maxTransversal(), and casadi::shared_cast().
{
     return node;
   }
int casadi::SharedObject::getCount () const inherited
Definition at line 159 of file shared_object.cpp.
References casadi::SharedObjectNode::getCount().
Referenced by casadi::Callback::transfer_ownership().
{
     return (*this)->getCount();
   }
std::string casadi::PrintableObject< SharedObject >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< SharedObject >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
bool casadi::SharedObject::is_null () const inherited
Definition at line 84 of file shared_object.cpp.
Referenced by casadi::FunctionInternal::alloc(), casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::Integrator::fun2problem(), casadi::Switch::generateBody(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), casadi::SundialsInterface::getBandwidth(), casadi::SundialsInterface::getBandwidthB(), casadi::FunctionInternal::getPartition(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Newton::init(), casadi::Integrator::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::FixedStepIntegrator::init(), casadi::CvodesInterface::init_memory(), casadi::IdasInterface::init_memory(), casadi::FixedStepIntegrator::init_memory(), casadi::CvodesInterface::initIterativeLinsol(), casadi::IdasInterface::initIterativeLinsol(), casadi::CvodesInterface::initIterativeLinsolB(), casadi::IdasInterface::initIterativeLinsolB(), casadi::CvodesInterface::initUserDefinedLinsol(), casadi::IdasInterface::initUserDefinedLinsol(), casadi::CvodesInterface::initUserDefinedLinsolB(), casadi::IdasInterface::initUserDefinedLinsolB(), casadi::Integrator::Integrator(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::Linsol(), casadi::SparsityInternal::maxTransversal(), casadi::operator<<(), casadi::IdasInterface::psolveB(), casadi::Qpsol::Qpsol(), casadi::SnoptInterface::set_work(), casadi::RkIntegrator::setupFG(), casadi::CollocationIntegrator::setupFG(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Integrator::spAdj(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), casadi::Integrator::spFwd(), casadi::FunctionInternal::spFwd(), casadi::Callback::transfer_ownership(), casadi::Sparsity::uni_coloring(), casadi::SnoptInterface::userfun(), and casadi::Callback::~Callback().
{
     return node==0;
   }
void casadi::XmlFile::loadPlugin (const std::string & name) static
Definition at line 53 of file xml_file.cpp.
{
     XmlFileInternal::loadPlugin(name);
   }
XmlFileInternal * casadi::XmlFile::operator-> ()
Definition at line 45 of file xml_file.cpp.
{
     return static_cast<XmlFileInternal*>(SharedObject::operator->());
   }
const XmlFileInternal * casadi::XmlFile::operator-> () const
Definition at line 41 of file xml_file.cpp.
{
     return static_cast<const XmlFileInternal*>(SharedObject::operator->());
   }
XmlNode casadi::XmlFile::parse (const std::string & filename)
Definition at line 49 of file xml_file.cpp.
Referenced by casadi::DaeBuilder::parse_fmi().
{
     return (*this)->parse(filename);
   }
void casadi::SharedObject::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 135 of file shared_object.cpp.
Referenced by casadi::CsparseInterface::linsol_factorize().
{
     if (is_null()) {
       stream << "Null pointer of class \"" << typeid(this).name() << "\"";
     } else {
       (*this)->print(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::SharedObject::printPtr (std::ostream & stream = casadi::userOut()) const inherited
Print the pointer to the internal class
Definition at line 144 of file shared_object.cpp.
{
     stream << node;
   }
void casadi::SharedObject::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 121 of file shared_object.cpp.
{
     if (is_null()) {
       stream << 0;
     } else {
       (*this)->repr(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 153 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
WeakRef * casadi::SharedObject::weak () inherited
Definition at line 167 of file shared_object.cpp.
References casadi::SharedObjectNode::weak().
Referenced by casadi::WeakRef::WeakRef().
{
     return (*this)->weak();
   }
The documentation for this class was generated from the following files:
xml_file.hpp
xml_file.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge