CasADi: Nlpsol
Nlpsol
Functions
CASADI_EXPORT Function casadi::nlpsol (const std::string &name, const std::string &solver, const SXDict &nlp, const Dict &opts=Dict())
CASADI_EXPORT Function casadi::nlpsol (const std::string &name, const std::string &solver, const MXDict &nlp, const Dict &opts=Dict())
CASADI_EXPORT Function casadi::nlpsol (const std::string &name, const std::string &solver, const Function &nlp, const Dict &opts=Dict())
Function casadi::nlpsol (const std::string &name, const std::string &solver, const std::string &fname, const Dict &opts)
CASADI_EXPORT Function casadi::nlpsol (const std::string &name, const std::string &solver, const Compiler &compiler, const Dict &opts=Dict())
CASADI_EXPORT Function casadi::nlpsol (const std::string &name, const std::string &solver, Oracle *nlp, const Dict &opts=Dict())
vector< string > casadi::nlpsol_in ()
Get input scheme of NLP solvers.
vector< string > casadi::nlpsol_out ()
Get NLP solver output scheme of NLP solvers.
string casadi::nlpsol_in (int ind)
Get NLP solver input scheme name by index.
string casadi::nlpsol_out (int ind)
Get output scheme name by index.
int casadi::nlpsol_n_in ()
Number of NLP solver inputs.
int casadi::nlpsol_n_out ()
Number of NLP solver outputs.
CASADI_EXPORT bool casadi::has_nlpsol (const std::string &name)
Check if a particular plugin is available.
CASADI_EXPORT void casadi::load_nlpsol (const std::string &name)
Explicitly load a plugin dynamically.
CASADI_EXPORT std::string casadi::doc_nlpsol (const std::string &name)
Get the documentation string for a plugin.
double casadi::nlpsol_default_in (int ind)
Default input for an NLP solver.
std::vector< double > casadi::nlpsol_default_in ()
Default input for an NLP solver.
Detailed Description
Create an NLP solver Creates a solver for the following parametric nonlinear program (NLP):
min          F(x, p)
x
subject to
LBX <=   x    <= UBX
LBG <= G(x, p) <= UBG
p  == P
nx: number of decision variables
ng: number of constraints
np: number of parameters
General information
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". casadi::FunctionInternal
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
eval_errors_fatal OT_BOOL When errors occur during evaluation of f,g,...,stop the iterations casadi::Nlpsol
expand OT_BOOL Replace MX with SX expressions in problem formulation [false] casadi::Nlpsol
gather_stats OT_BOOL Flag to indicate whether statistics must be gathered casadi::FunctionInternal
ignore_check_vec OT_BOOL If set to true, the input shape of F will not be checked. casadi::Nlpsol
input_scheme OT_STRINGVECTOR Custom input scheme casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
iteration_callback OT_FUNCTION A function that will be called at each iteration with the solver as input. Check documentation of Callback. casadi::Nlpsol
iteration_callback_ignore_errors OT_BOOL If set to true, errors thrown by iteration_callback will be ignored. casadi::Nlpsol
iteration_callback_step OT_INT Only call the callback function every few iterations. casadi::Nlpsol
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
monitor OT_STRINGVECTOR Monitors to be activated casadi::FunctionInternal
output_scheme OT_STRINGVECTOR Custom output scheme casadi::FunctionInternal
print_time OT_BOOL print information about execution time casadi::Nlpsol
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::FunctionInternal
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::FunctionInternal
verbose_init OT_BOOL Print out timing information about the different stages of initialization casadi::Nlpsol
warn_initial_bounds OT_BOOL Warn if the initial guess does not satisfy LBX and UBX casadi::Nlpsol
Input scheme: casadi::NlpsolInput (NLPSOL_NUM_IN = 8) []
Full name Short Description
NLPSOL_X0 Decision variables, initial guess (nx x 1)
NLPSOL_P Value of fixed parameters (np x 1)
NLPSOL_LBX Decision variables lower bound (nx x 1), default -inf.
NLPSOL_UBX Decision variables upper bound (nx x 1), default +inf.
NLPSOL_LBG Constraints lower bound (ng x 1), default -inf.
NLPSOL_UBG Constraints upper bound (ng x 1), default +inf.
NLPSOL_LAM_X0 Lagrange multipliers for bounds on X, initial guess (nx x 1)
NLPSOL_LAM_G0 Lagrange multipliers for bounds on G, initial guess (ng x 1)
Output scheme: casadi::NlpsolOutput (NLPSOL_NUM_OUT = 6) []
Full name Short Description
NLPSOL_X Decision variables at the optimal solution (nx x 1)
NLPSOL_F Cost function value at the optimal solution (1 x 1)
NLPSOL_G Constraints function at the optimal solution (ng x 1)
NLPSOL_LAM_X Lagrange multipliers for bounds on X at the solution (nx x 1)
NLPSOL_LAM_G Lagrange multipliers for bounds on G at the solution (ng x 1)
NLPSOL_LAM_P Lagrange multipliers for bounds on P at the solution (np x 1)
List of plugins
- ipopt
- knitro
- snopt
- worhp
- scpgen
- sqpmethod
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Nlpsol.doc("myextraplugin")
ipopt
When in warmstart mode, output NLPSOL_LAM_X may be used as input
NOTE: Even when max_iter == 0, it is not guaranteed that input(NLPSOL_X0) == output(NLPSOL_X). Indeed if bounds on X or constraints are unmet, they will differ.
For a good tutorial on IPOPT, see http://drops.dagstuhl.de/volltexte/2009/2089/pdf/09061.WaechterAndreas.Paper.2089.pdf
A good resource about the algorithms in IPOPT is: Wachter and L. T. Biegler, On the Implementation of an Interior-Point Filter Line-Search Algorithm for Large-Scale Nonlinear Programming, Mathematical Programming 106(1), pp. 25-57, 2006 (As Research Report RC 23149, IBM T. J. Watson Research Center, Yorktown, USA
Caveats:
with default options, multipliers for the decision variables are wrong for equality constraints. Change the 'fixed_variable_treatment' to 'make_constraint' or 'relax_bounds' to obtain correct results.
List of available options
Id Type Description
con_integer_md OT_DICT Integer metadata (a dictionary with lists of integers) about constraints to be passed to IPOPT
con_numeric_md OT_DICT Numeric metadata (a dictionary with lists of reals) about constraints to be passed to IPOPT
con_string_md OT_DICT String metadata (a dictionary with lists of strings) about constraints to be passed to IPOPT
grad_f OT_FUNCTION Function for calculating the gradient of the objective (column, autogenerated by default)
grad_f_options OT_DICT Options for the autogenerated gradient of the objective.
hess_lag OT_FUNCTION Function for calculating the Hessian of the Lagrangian (autogenerated by default)
hess_lag_options OT_DICT Options for the autogenerated Hessian of the Lagrangian.
ipopt OT_DICT Options to be passed to IPOPT
jac_g OT_FUNCTION Function for calculating the Jacobian of the constraints (autogenerated by default)
jac_g_options OT_DICT Options for the autogenerated Jacobian of the constraints.
pass_nonlinear_variables OT_BOOL Pass list of variables entering nonlinearly to IPOPT
var_integer_md OT_DICT Integer metadata (a dictionary with lists of integers) about variables to be passed to IPOPT
var_numeric_md OT_DICT Numeric metadata (a dictionary with lists of reals) about variables to be passed to IPOPT
var_string_md OT_DICT String metadata (a dictionary with lists of strings) about variables to be passed to IPOPT
knitro
KNITRO interface
List of available options
Id Type Description
contype OT_INTVECTOR Type of constraint
knitro OT_DICT Options to be passed to KNITRO
snopt
SNOPT interface
List of available options
Id Type Description
snopt OT_DICT Options to be passed to SNOPT
worhp
WORHP interface
List of available options
Id Type Description
worhp OT_DICT Options to be passed to WORHP
scpgen
A structure-exploiting sequential quadratic programming (to be come sequential convex programming) method for nonlinear programming.
List of available options
Id Type Description
beta OT_DOUBLE Line-search parameter, restoration factor of stepsize
c1 OT_DOUBLE Armijo condition, coefficient of decrease in merit
codegen OT_BOOL C-code generation
hessian_approximation OT_STRING gauss-newton|exact
lbfgs_memory OT_INT Size of L-BFGS memory.
max_iter OT_INT Maximum number of SQP iterations
max_iter_ls OT_INT Maximum number of linesearch iterations
merit_memsize OT_INT Size of memory to store history of merit function values
merit_start OT_DOUBLE Lower bound for the merit function parameter
name_x OT_STRINGVECTOR Names of the variables.
print_header OT_BOOL Print the header with problem statistics
print_x OT_INTVECTOR Which variables to print.
qpsol OT_STRING The QP solver to be used by the SQP method
qpsol_options OT_DICT Options to be passed to the QP solver
reg_threshold OT_DOUBLE Threshold for the regularization.
regularize OT_BOOL Automatic regularization of Lagrange Hessian.
tol_du OT_DOUBLE Stopping criterion for dual infeasability
tol_pr OT_DOUBLE Stopping criterion for primal infeasibility
tol_pr_step OT_DOUBLE Stopping criterion for the step size
tol_reg OT_DOUBLE Stopping criterion for regularization
sqpmethod
A textbook SQPMethod
List of available options
Id Type Description
beta OT_DOUBLE Line-search parameter, restoration factor of stepsize
c1 OT_DOUBLE Armijo condition, coefficient of decrease in merit
hessian_approximation OT_STRING limited-memory|exact
lbfgs_memory OT_INT Size of L-BFGS memory.
max_iter OT_INT Maximum number of SQP iterations
max_iter_ls OT_INT Maximum number of linesearch iterations
merit_memory OT_INT Size of memory to store history of merit function values
min_step_size OT_DOUBLE The size (inf-norm) of the step size should not become smaller than this.
print_header OT_BOOL Print the header with problem statistics
qpsol OT_STRING The QP solver to be used by the SQP method
qpsol_options OT_DICT Options to be passed to the QP solver
regularize OT_BOOL Automatic regularization of Lagrange Hessian.
tol_du OT_DOUBLE Stopping criterion for dual infeasability
tol_pr OT_DOUBLE Stopping criterion for primal infeasibility
Author
Joel Andersson
Date
2011-2015
Function Documentation
CASADI_EXPORT std::string casadi::doc_nlpsol (const std::string & name)
CASADI_EXPORT bool casadi::has_nlpsol (const std::string & name)
CASADI_EXPORT void casadi::load_nlpsol (const std::string & name)
CASADI_EXPORT Function casadi::nlpsol (const std::string & name, const std::string & solver, const std::string & fname, const Dict & opts)
Definition at line 57 of file nlpsol.cpp.
Referenced by casadi::nlpsol().
{
     return nlpsol(name, solver, Oracle::construct(fname, "nlp"), opts);
   }
CASADI_EXPORT Function casadi::nlpsol (const std::string & name, const std::string & solver, const SXDict & nlp, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::nlpsol (const std::string & name, const std::string & solver, const MXDict & nlp, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::nlpsol (const std::string & name, const std::string & solver, const Function & nlp, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::nlpsol (const std::string & name, const std::string & solver, const Compiler & compiler, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::nlpsol (const std::string & name, const std::string & solver, Oracle * nlp, const Dict & opts = Dict())
CASADI_EXPORT double casadi::nlpsol_default_in (int ind)
Definition at line 96 of file nlpsol.cpp.
References casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_UBG, and casadi::NLPSOL_UBX.
Referenced by casadi::Nlpsol::default_in(), and casadi::qpsol_nlp().
{
     switch (ind) {
     case NLPSOL_LBX:
     case NLPSOL_LBG:
       return -std::numeric_limits<double>::infinity();
     case NLPSOL_UBX:
     case NLPSOL_UBG:
       return std::numeric_limits<double>::infinity();
     default:
       return 0;
     }
   }
CASADI_EXPORT std::vector< double > casadi::nlpsol_default_in ()
Definition at line 109 of file nlpsol.cpp.
References casadi::nlpsol_n_in().
{
     vector<double> ret(nlpsol_n_in());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=nlpsol_default_in(i);
     return ret;
   }
CASADI_EXPORT std::vector< std::string > casadi::nlpsol_in ()
Definition at line 84 of file nlpsol.cpp.
References casadi::nlpsol_in(), and casadi::nlpsol_n_in().
Referenced by casadi::Nlpsol::get_name_in(), and casadi::qpsol_nlp().
{
     vector<string> ret(nlpsol_n_in());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=nlpsol_in(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::nlpsol_in (int ind)
Definition at line 115 of file nlpsol.cpp.
References casadi::NLPSOL_LAM_G0, casadi::NLPSOL_LAM_X0, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_NUM_IN, casadi::NLPSOL_P, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, and casadi::NLPSOL_X0.
Referenced by casadi::nlpsol_in().
{
     switch (static_cast<NlpsolInput>(ind)) {
     case NLPSOL_X0:     return "x0";
     case NLPSOL_P:      return "p";
     case NLPSOL_LBX:    return "lbx";
     case NLPSOL_UBX:    return "ubx";
     case NLPSOL_LBG:    return "lbg";
     case NLPSOL_UBG:    return "ubg";
     case NLPSOL_LAM_X0: return "lam_x0";
     case NLPSOL_LAM_G0: return "lam_g0";
     case NLPSOL_NUM_IN: break;
     }
     return string();
   }
CASADI_EXPORT int casadi::nlpsol_n_in ()
Definition at line 143 of file nlpsol.cpp.
References casadi::NLPSOL_NUM_IN.
Referenced by casadi::nlpsol_default_in(), and casadi::nlpsol_in().
                     {
     return NLPSOL_NUM_IN;
   }
CASADI_EXPORT int casadi::nlpsol_n_out ()
Definition at line 147 of file nlpsol.cpp.
References casadi::NLPSOL_NUM_OUT.
Referenced by casadi::nlpsol_out().
                      {
     return NLPSOL_NUM_OUT;
   }
CASADI_EXPORT std::vector< std::string > casadi::nlpsol_out ()
Definition at line 90 of file nlpsol.cpp.
References casadi::nlpsol_n_out(), and casadi::nlpsol_out().
Referenced by casadi::Nlpsol::get_name_out(), and casadi::qpsol_nlp().
{
     vector<string> ret(nlpsol_n_out());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=nlpsol_out(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::nlpsol_out (int ind)
Definition at line 130 of file nlpsol.cpp.
References casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_P, casadi::NLPSOL_LAM_X, casadi::NLPSOL_NUM_OUT, and casadi::NLPSOL_X.
Referenced by casadi::nlpsol_out().
{
     switch (static_cast<NlpsolOutput>(ind)) {
     case NLPSOL_X:     return "x";
     case NLPSOL_F:     return "f";
     case NLPSOL_G:     return "g";
     case NLPSOL_LAM_X: return "lam_x";
     case NLPSOL_LAM_G: return "lam_g";
     case NLPSOL_LAM_P: return "lam_p";
     case NLPSOL_NUM_OUT: break;
     }
     return string();
   }
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge