CasADi: casadi::BinarySX Class Reference
casadi::BinarySX Class Reference
Represents a basic binary operation on two SXElem nodes.
#include <binary_sx.hpp>
Detailed Description
Author
Joel Andersson
Date
2010
Definition at line 40 of file binary_sx.hpp.
Public Member Functions
virtual ~BinarySX ()
Destructor This is a rather complex destructor which is necessary since the default destructor can cause stack overflow due to recursive calling.
virtual bool is_smooth () const
Check if smooth.
virtual bool hasDep () const
check properties of a node
virtual bool is_equal (const SXNode *node, int depth) const
Check if two nodes are equivalent up to a given depth.
virtual int ndep () const
Number of dependencies.
virtual const SXElem & dep (int i) const
get the reference of a dependency
virtual SXElem & dep (int i)
get the reference of a child
virtual int op () const
Get the operation.
virtual std::string print (const std::string &arg1, const std::string &arg2) const
Print expression.
virtual const std::string & name () const
virtual void print (std::ostream &stream) const
print
void can_inline (std::map< const SXNode *, int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const SXNode *, int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
bool marked () const
void mark ()
virtual bool is_constant () const
check properties of a node
virtual bool is_integer () const
check properties of a node
virtual bool is_symbolic () const
check properties of a node
virtual bool is_zero () const
check properties of a node
virtual bool isAlmostZero (double tol) const
check properties of a node
virtual bool is_one () const
check properties of a node
virtual bool is_minus_one () const
check properties of a node
virtual bool isNan () const
check properties of a node
virtual bool isInf () const
check properties of a node
virtual bool isMinusInf () const
check properties of a node
virtual double to_double () const
Get value of a constant node.
virtual int to_int () const
Get value of a constant node.
Static Public Member Functions
static SXElem create (unsigned char op, const SXElem &dep0, const SXElem &dep1)
Create a binary expression.
Public Attributes
unsigned char op_
The binary operation as an 1 byte integer (allows 256 values)
SXElem dep0_
The dependencies of the node.
SXElem dep1_
int temp
unsigned int count
Static Public Attributes
static int eq_depth_ = 1
Constructor & Destructor Documentation
virtual casadi::BinarySX::~BinarySX () inline virtual
Definition at line 68 of file binary_sx.hpp.
References casadi::SXElem::assignNoDelete(), casadi::SXNode::count, casadi::SXNode::dep(), casadi::SXNode::hasDep(), and casadi::SXNode::ndep().
{
       // Start destruction method if any of the dependencies has dependencies
       for (int c1=0; c1<2; ++c1) {
         // Get the node of the dependency and remove it from the smart pointer
         SXNode* n1 = dep(c1).assignNoDelete(casadi_limits<SXElem>::nan);
         // Check if this was the last reference
         if (n1->count==0) {
           // Check if binary
           if (!n1->hasDep()) { // n1 is not binary
             delete n1; // Delete straight away
           } else { // n1 is binary
             // Stack of expressions to be deleted
             std::stack<SXNode*> deletion_stack;
             // Add the node to the deletion stack
             deletion_stack.push(n1);
             // Process stack
             while (!deletion_stack.empty()) {
               // Top element
               SXNode *t = deletion_stack.top();
               // Check if the top element has dependencies with dependencies
               bool added_to_stack = false;
               for (int c2=0; c2<t->ndep(); ++c2) { // for all dependencies of the dependency
                 // Get the node of the dependency of the top element
                 // and remove it from the smart pointer
                 SXNode *n2 = t->dep(c2).assignNoDelete(casadi_limits<SXElem>::nan);
                 // Check if this is the only reference to the element
                 if (n2->count == 0) {
                   // Check if binary
                   if (!n2->hasDep()) {
                     // Delete straight away if not binary
                     delete n2;
                   } else {
                     // Add to deletion stack
                     deletion_stack.push(n2);
                     added_to_stack = true;
                   }
                 }
               }
               // Delete and pop from stack if nothing added to the stack
               if (!added_to_stack) {
                 delete deletion_stack.top();
                 deletion_stack.pop();
               }
             } // while
           }
         }
       }
     }
Member Function Documentation
void casadi::SXNode::can_inline (std::map< const SXNode *, int > & nodeind) const inherited
Definition at line 146 of file sx_node.cpp.
References casadi::OP_PARAMETER.
{
     // Add or mark node in map
     std::map<const SXNode*, int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, make_pair(this, 0));
       // Handle dependencies with recursion
       for (int i=0; i<ndep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
static SXElem casadi::BinarySX::create (unsigned char op, const SXElem & dep0, const SXElem & dep1) inline static
Definition at line 50 of file binary_sx.hpp.
References casadi::SXElem::create(), casadi::casadi_math< T >::fun(), and casadi::SXElem::is_constant().
Referenced by casadi::SXElem::binary().
{
       if (dep0.is_constant() && dep1.is_constant()) {
         // Evaluate constant
         double dep0_val(dep0);
         double dep1_val(dep1);
         double ret_val;
         casadi_math<double>::fun(op, dep0_val, dep1_val, ret_val);
         return ret_val;
       } else {
         // Expression containing free variables
         return SXElem::create(new BinarySX(op, dep0, dep1));
       }
     }
virtual const SXElem& casadi::BinarySX::dep (int i) const inline virtual
Reimplemented from casadi::SXNode.
Definition at line 154 of file binary_sx.hpp.
 { return i==0 ? dep0_ : dep1_;}
virtual SXElem& casadi::BinarySX::dep (int i) inline virtual
Reimplemented from casadi::SXNode.
Definition at line 155 of file binary_sx.hpp.
 { return i==0 ? dep0_ : dep1_;}
virtual bool casadi::BinarySX::hasDep () const inline virtual
Reimplemented from casadi::SXNode.
Definition at line 135 of file binary_sx.hpp.
 { return true; }
bool casadi::SXNode::is_constant () const virtual inherited
Reimplemented in casadi::ConstantSX.
Definition at line 85 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), casadi::SXFunction::init(), and casadi::SXElem::is_constant().
{
     return false;
   }
virtual bool casadi::BinarySX::is_equal (const SXNode * node, int depth) const inline virtual
Reimplemented from casadi::SXNode.
Definition at line 138 of file binary_sx.hpp.
References dep0_, dep1_, casadi::SXElem::is_equal(), and op_.
{
       const BinarySX* n = dynamic_cast<const BinarySX*>(node);
       if (n==0) return false;
       if (n->op_ != op_) return false;
       if (SXElem::is_equal(n->dep0_, dep0_, depth-1)
           && SXElem::is_equal(n->dep1_, dep1_, depth-1)) return true;
       if (operation_checker<CommChecker>(op_)
           && SXElem::is_equal(n->dep1_, dep0_, depth-1)
           && SXElem::is_equal(n->dep0_, dep1_, depth-1)) return true;
       return false;
     }
bool casadi::SXNode::is_integer () const virtual inherited
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, and casadi::IntegerSX.
Definition at line 89 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_integer().
{
     return false;
   }
bool casadi::SXNode::is_minus_one () const virtual inherited
Reimplemented in casadi::MinusOneSX.
Definition at line 69 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_minus_one().
{
     return false;
   }
bool casadi::SXNode::is_one () const virtual inherited
Reimplemented in casadi::OneSX.
Definition at line 65 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_one().
{
     return false;
   }
virtual bool casadi::BinarySX::is_smooth () const inline virtual
Reimplemented from casadi::SXNode.
Definition at line 133 of file binary_sx.hpp.
 { return operation_checker<SmoothChecker>(op_);}
bool casadi::SXNode::is_symbolic () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 93 of file sx_node.cpp.
Referenced by casadi::SXFunction::init(), and casadi::SXElem::is_symbolic().
{
     return false;
   }
bool casadi::SXNode::is_zero () const virtual inherited
Reimplemented in casadi::ZeroSX.
Definition at line 57 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_zero().
{
     return false;
   }
bool casadi::SXNode::isAlmostZero (double tol) const virtual inherited
Reimplemented in casadi::ZeroSX, and casadi::RealtypeSX.
Definition at line 61 of file sx_node.cpp.
Referenced by casadi::SXElem::isAlmostZero().
{
     return false;
   }
bool casadi::SXNode::isInf () const virtual inherited
Reimplemented in casadi::InfSX.
Definition at line 77 of file sx_node.cpp.
Referenced by casadi::SXElem::isInf().
{
     return false;
   }
bool casadi::SXNode::isMinusInf () const virtual inherited
Reimplemented in casadi::MinusInfSX.
Definition at line 81 of file sx_node.cpp.
Referenced by casadi::SXElem::isMinusInf().
{
     return false;
   }
bool casadi::SXNode::isNan () const virtual inherited
Reimplemented in casadi::NanSX.
Definition at line 73 of file sx_node.cpp.
Referenced by casadi::SXElem::isNan().
{
     return false;
   }
void casadi::SXNode::mark () inherited
Definition at line 142 of file sx_node.cpp.
                     {
     temp = -temp-1;
   }
bool casadi::SXNode::marked () const inherited
Definition at line 138 of file sx_node.cpp.
{
     return temp<0;
   }
const std::string & casadi::SXNode::name () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 105 of file sx_node.cpp.
Referenced by casadi::SXElem::name().
{
     throw CasadiException("SXNode::name failed, the node must be symbolic");
   }
virtual int casadi::BinarySX::ndep () const inline virtual
Reimplemented from casadi::SXNode.
Definition at line 151 of file binary_sx.hpp.
 { return 2;}
virtual int casadi::BinarySX::op () const inline virtual
Implements casadi::SXNode.
Definition at line 158 of file binary_sx.hpp.
 { return op_;}
void casadi::SXNode::print (std::ostream & stream) const virtual inherited
Definition at line 121 of file sx_node.cpp.
Referenced by casadi::SXElem::print().
{
     // Find out which noded can be inlined
     std::map<const SXNode*, int> nodeind;
     can_inline(nodeind);
     // Print expression
     vector<string> intermed;
     string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
virtual std::string casadi::BinarySX::print (const std::string & arg1, const std::string & arg2) const inline virtual
Implements casadi::SXNode.
Definition at line 161 of file binary_sx.hpp.
References casadi::casadi_math< T >::printPost(), casadi::casadi_math< T >::printPre(), and casadi::casadi_math< T >::printSep().
{
       std::stringstream ss;
       // Print the prefix
       casadi_math<double>::printPre(op_, ss);
       // Print the first dependency
       ss << arg1;
       //Print the infix
       casadi_math<double>::printSep(op_, ss);
       // Print the second dependency
       ss << arg2;
       // Print the suffix
       casadi_math<double>::printPost(op_, ss);
       return ss.str();
     }
std::string casadi::SXNode::print_compact (std::map< const SXNode *, int > & nodeind, std::vector< std::string > & intermed) const inherited
Definition at line 163 of file sx_node.cpp.
References casadi::print().
{
     // Get reference to node index
     int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) {
       stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
     // Get expressions for dependencies
     std::string arg[2];
     for (int i=0; i<ndep(); ++i) {
       arg[i] = dep(i)->print_compact(nodeind, intermed);
     }
     // Get expression for this
     string s = print(arg[0], arg[1]);
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
   }
double casadi::SXNode::to_double () const virtual inherited
Reimplemented in casadi::NanSX, casadi::MinusInfSX, casadi::InfSX, casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, casadi::RealtypeSX, and casadi::ConstantSX.
Definition at line 47 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXFunction::init().
{
     return numeric_limits<double>::quiet_NaN();
     /*  userOut<true, PL_WARN>() << "to_double() not defined for class " << typeid(*this).name() << std::endl;
         throw "SXNode::to_double()";*/
   }
int casadi::SXNode::to_int () const virtual inherited
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 53 of file sx_node.cpp.
Referenced by casadi::SXElem::binary().
{
     throw CasadiException(string("to_int() not defined for class ") + typeid(*this).name());
   }
Member Data Documentation
unsigned int casadi::SXNode::count inherited
Definition at line 127 of file sx_node.hpp.
Referenced by casadi::SXElem::assignNoDelete(), casadi::SXElem::operator=(), casadi::SXElem::SXElem(), ~BinarySX(), and casadi::SXElem::~SXElem().
SXElem casadi::BinarySX::dep0_
Definition at line 186 of file binary_sx.hpp.
Referenced by is_equal().
SXElem casadi::BinarySX::dep1_
Definition at line 186 of file binary_sx.hpp.
Referenced by is_equal().
int casadi::SXNode::eq_depth_ = 1 static inherited
Definition at line 118 of file sx_node.hpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_doubled().
unsigned char casadi::BinarySX::op_
Definition at line 183 of file binary_sx.hpp.
Referenced by is_equal().
int casadi::SXNode::temp inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 124 of file sx_node.hpp.
Referenced by casadi::SXFunction::init().
The documentation for this class was generated from the following file:
binary_sx.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge