CasADi: casadi::CodeGenerator Class Reference
casadi::CodeGenerator Class Reference
#include <code_generator.hpp>
Detailed Description
Definition at line 36 of file code_generator.hpp.
Public Types
enum Auxiliary {
AUX_COPY, AUX_SWAP, AUX_SCAL, AUX_AXPY,
AUX_DOT, AUX_BILIN, AUX_RANK1, AUX_NRM2,
AUX_IAMAX, AUX_FILL, AUX_ASUM, AUX_SQ,
AUX_SIGN, AUX_MTIMES, AUX_PROJECT, AUX_TRANS,
AUX_TO_MEX, AUX_FROM_MEX
}
Auxiliary functions.
typedef std::map< const void
*, int > PointerMap
Public Member Functions
CodeGenerator (const Dict &opts=Dict())
Constructor.
void add (const Function &f)
Add a function (name generated)
void generate (std::ostream &s) const
Generate the code to a stream.
void generate (const std::string &name) const
Generate a file.
std::string generate () const
Generate a file, return code as string.
std::string compile (const std::string &name, const std::string &compiler="gcc -fPIC -O2")
Compile and load function.
void addInclude (const std::string &new_include, bool relative_path=false, const std::string &use_ifdef=std::string())
Add an include file optionally using a relative path "..." instead of an absolute path <...>
void addExternal (const std::string &new_external)
Add an external function declaration.
std::string sparsity (const Sparsity &sp)
int addSparsity (const Sparsity &sp)
int get_sparsity (const Sparsity &sp) const
Get the index of an existing sparsity pattern.
int getConstant (const std::vector< double > &v, bool allow_adding=false)
Get or add a constant.
int getConstant (const std::vector< int > &v, bool allow_adding=false)
Get or add an integer constant.
std::string operator() (const Function &f, const std::string &arg, const std::string &res, const std::string &iw, const std::string &w, const std::string &mem="0") const
Generate a call to a function (generic signature)
std::string operator() (const Function &f, const std::string &arg, const std::string &res) const
Generate a call to a function (simplified signature)
std::string dot (int n, const std::string &x, const std::string &y)
Codegen inner product.
std::string mtimes (const std::string &x, const Sparsity &sp_x, const std::string &y, const Sparsity &sp_y, const std::string &z, const Sparsity &sp_z, const std::string &w, bool tr)
Codegen sparse matrix-matrix multiplication.
std::string bilin (const std::string &A, const Sparsity &sp_A, const std::string &x, const std::string &y)
Codegen bilinear form.
std::string rank1 (const std::string &A, const Sparsity &sp_A, const std::string &alpha, const std::string &x, const std::string &y)
Rank-1 update.
std::string declare (std::string s)
Declare a function.
void addAuxiliary (Auxiliary f)
Add a built-in auxiliary function.
std::string work (int n, int sz) const
std::string workel (int n) const
std::string copy (const std::string &arg, std::size_t n, const std::string &res)
Create a copy operation.
std::string fill (const std::string &res, std::size_t n, const std::string &v)
Create a fill operation.
std::string project (const std::string &arg, const Sparsity &sp_arg, const std::string &res, const Sparsity &sp_res, const std::string &w)
Sparse assignment.
std::string to_mex (const Sparsity &sp, const std::string &arg)
Create matrix in MATLAB's MEX format.
std::string from_mex (std::string &arg, const std::string &res, std::size_t res_off, const Sparsity &sp_res, const std::string &w)
Get matrix from MATLAB's MEX format.
std::string printf (const std::string &str, const std::vector< std::string > &arg=std::vector< std::string >())
Printf.
std::string printf (const std::string &str, const std::string &arg1)
std::string printf (const std::string &str, const std::string &arg1, const std::string &arg2)
std::string printf (const std::string &str, const std::string &arg1, const std::string &arg2, const std::string &arg3)
Static Public Member Functions
static bool simplifiedCall (const Function &f)
Use simplified signature.
static std::string constant (double v)
Print a constant in a lossless but compact manner.
static std::string to_string (int n)
static void print_vector (std::ostream &s, const std::string &name, const std::vector< int > &v)
Print int vector to a c file.
static void print_vector (std::ostream &s, const std::string &name, const std::vector< double > &v)
Print real vector to a c file.
static void assign (std::ostream &s, const std::string &lhs, const std::string &rhs)
Assignment.
static size_t hash (const std::vector< double > &v)
static size_t hash (const std::vector< int > &v)
template<typename T >
static bool equal (const std::vector< T > &v1, const std::vector< T > &v2)
Public Attributes
std::string real_t
bool with_header
bool mex
bool verbose
bool cpp
bool main
bool codegen_scalars
Codegen scalar Use the work vector for storing work vector elements of length 1 (typically scalar) instead of using local variables.
std::stringstream includes
std::stringstream auxiliaries
std::stringstream body
std::stringstream header
std::vector< std::string > exposed_fname
std::set< std::string > added_includes_
std::set< std::string > added_externals_
std::set< Auxiliary > added_auxiliaries_
PointerMap added_sparsities_
PointerMap added_dependencies_
std::multimap< size_t, size_t > added_double_constants_
std::multimap< size_t, size_t > added_integer_constants_
std::vector< std::vector
< double > > double_constants_
std::vector< std::vector< int > > integer_constants_
Member Typedef Documentation
typedef std::map<const void*, int> casadi::CodeGenerator::PointerMap
Definition at line 232 of file code_generator.hpp.
Member Enumeration Documentation
enum casadi::CodeGenerator::Auxiliary
Enumerator
AUX_COPY
AUX_SWAP
AUX_SCAL
AUX_AXPY
AUX_DOT
AUX_BILIN
AUX_RANK1
AUX_NRM2
AUX_IAMAX
AUX_FILL
AUX_ASUM
AUX_SQ
AUX_SIGN
AUX_MTIMES
AUX_PROJECT
AUX_TRANS
AUX_TO_MEX
AUX_FROM_MEX
Definition at line 116 of file code_generator.hpp.
                    {
       AUX_COPY,
       AUX_SWAP,
       AUX_SCAL,
       AUX_AXPY,
       AUX_DOT,
       AUX_BILIN,
       AUX_RANK1,
       AUX_NRM2,
       AUX_IAMAX,
       AUX_FILL,
       AUX_ASUM,
       AUX_SQ,
       AUX_SIGN,
       AUX_MTIMES,
       AUX_PROJECT,
       AUX_TRANS,
       AUX_TO_MEX,
       AUX_FROM_MEX
     };
Constructor & Destructor Documentation
casadi::CodeGenerator::CodeGenerator (const Dict & opts = Dict())
Definition at line 35 of file code_generator.cpp.
{
     // Default options
     this->verbose = false;
     this->mex = false;
     this->cpp = false;
     this->main = false;
     this->real_t = "double";
     this->codegen_scalars = false;
     this->with_header = false;
     // Read options
     for (auto&& e : opts) {
       if (e.first=="verbose") {
         this->verbose = e.second;
       } else if (e.first=="mex") {
         this->mex = e.second;
       } else if (e.first=="cpp") {
         this->cpp = e.second;
       } else if (e.first=="main") {
         this->main = e.second;
       } else if (e.first=="real_t") {
         this->real_t = e.second.to_string();
       } else if (e.first=="codegen_scalars") {
         this->codegen_scalars = e.second;
       } else if (e.first=="with_header") {
         this->with_header = e.second;
       } else {
         casadi_error("Unrecongnized option: " << e.first);
       }
     }
     // Includes needed
     if (this->main) addInclude("stdio.h");
     // Mex and main needs string.h
     if (this->mex || this->main) {
       addInclude("string.h");
     }
     // Mex file?
     if (this->mex) {
       addInclude("mex.h", false, "MATLAB_MEX_FILE");
       // Define printf (note file should be compilable both with and without mex)
       this->auxiliaries
         << "#ifdef MATLAB_MEX_FILE" << endl
         << "#define PRINTF mexPrintf" << endl
         << "#else" << endl
         << "#define PRINTF printf" << endl
         << "#endif" << endl;
     } else {
       // Define printf as standard printf from stdio.h
       this->auxiliaries << "#define PRINTF printf" << endl;
     }
   }
Member Function Documentation
void casadi::CodeGenerator::add (const Function & f)
Definition at line 90 of file code_generator.cpp.
References casadi::FunctionInternal::generateFunction(), casadi::FunctionInternal::generateMeta(), casadi::Function::name(), and casadi::FunctionInternal::signature().
Referenced by casadi::FunctionInternal::dynamicCompilation(), casadi::FunctionInternal::finalize(), casadi::Nlpsol::generate_dependencies(), and casadi::Scpgen::init().
{
     f->generateFunction(*this, f.name(), false);
     if (this->with_header) {
       if (this->cpp) this->header << "extern \"C\" " ; // C linkage
       this->header << f->signature(f.name()) << ";" << endl;
     }
     f->generateMeta(*this, f.name());
     this->exposed_fname.push_back(f.name());
   }
void casadi::CodeGenerator::addAuxiliary (Auxiliary f)
Definition at line 488 of file code_generator.cpp.
Referenced by casadi::Transpose::generate(), casadi::KernelSum::generateBody(), casadi::Mapaccum::generateBody(), casadi::MapSum::generateBody(), and casadi::FunctionInternal::generateFunction().
{
     // Register the new auxiliary
     bool added = added_auxiliaries_.insert(f).second;
     // Quick return if it already exists
     if (!added) return;
     // Add the appropriate function
     switch (f) {
     case AUX_COPY:
       this->auxiliaries
         << codegen_str_copy
         << codegen_str_copy_define << endl
         << endl;
       break;
     case AUX_SWAP:
       this->auxiliaries << codegen_str_swap
         << codegen_str_swap_define
         << endl;
       break;
     case AUX_SCAL:
       this->auxiliaries << codegen_str_scal
         << codegen_str_scal_define
         << endl;
       break;
     case AUX_AXPY:
       this->auxiliaries << codegen_str_axpy
         << codegen_str_axpy_define
         << endl;
       break;
     case AUX_DOT:
       this->auxiliaries
         << codegen_str_dot
         << codegen_str_dot_define << endl
         << endl;
       break;
     case AUX_BILIN:
       this->auxiliaries
         << codegen_str_bilin
         << codegen_str_bilin_define << endl
         << endl;
       break;
     case AUX_RANK1:
       this->auxiliaries
         << codegen_str_rank1
         << codegen_str_rank1_define << endl
         << endl;
       break;
     case AUX_ASUM:
       this->auxiliaries << codegen_str_asum
         << codegen_str_asum_define
         << endl;
       break;
     case AUX_IAMAX:
       this->auxiliaries << codegen_str_iamax
         << codegen_str_iamax_define
         << endl;
       break;
     case AUX_NRM2:
       this->auxiliaries << codegen_str_nrm2
         << codegen_str_nrm2_define
         << endl;
       break;
     case AUX_FILL:
       this->auxiliaries
         << codegen_str_fill
         << codegen_str_fill_define << endl
         << endl;
       break;
     case AUX_MTIMES:
       this->auxiliaries << codegen_str_mtimes
         << codegen_str_mtimes_define
         << endl;
       break;
     case AUX_SQ:
       auxSq();
       break;
     case AUX_SIGN:
       auxSign();
       break;
     case AUX_PROJECT:
       this->auxiliaries
         << codegen_str_project
         << codegen_str_project_define
         << endl << endl;
       break;
     case AUX_TRANS:
       this->auxiliaries << codegen_str_trans
         << "#define trans(x, sp_x, y, sp_y, tmp) CASADI_PREFIX(trans)(x, sp_x, y, sp_y, tmp)"
         << endl << endl;
       break;
     case AUX_TO_MEX:
       this->auxiliaries
         << "#ifdef MATLAB_MEX_FILE" << endl
         << "mxArray* CASADI_PREFIX(to_mex)(const int* sp, const real_t* x) {" << endl
         << "  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];" << endl
         << "  mxArray* p = mxCreateSparse(nrow, ncol, nnz, mxREAL);" << endl
         << "  int i;" << endl
         << "  mwIndex* j;" << endl
         << "  for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *sp++;" << endl
         << "  for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *sp++;" << endl
         << "  if (x) {" << endl
         << "    double* d = (double*)mxGetData(p);" << endl
         << "    for (i=0; i<nnz; ++i) *d++ = to_double(*x++);" << endl
         << "  }" << endl
         << "  return p;" << endl
         << "}" << endl
         << "#define to_mex(sp, x) CASADI_PREFIX(to_mex)(sp, x)" << endl
         << "#endif" << endl << endl;
       break;
     case AUX_FROM_MEX:
       addAuxiliary(AUX_FILL);
       this->auxiliaries
         << "#ifdef MATLAB_MEX_FILE" << endl
         << "real_t* CASADI_PREFIX(from_mex)(const mxArray *p, "
         << "real_t* y, const int* sp, real_t* w) {" << endl
         << "  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)" << endl
         << "    mexErrMsgIdAndTxt(\"Casadi:RuntimeError\",\"\\\"from_mex\\\" failed: "
         << "Not a two-dimensional matrix of double precision.\");" << endl
         << "  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];" << endl
         << "  const int *colind=sp, *row=sp+ncol+1;" << endl
         << "  size_t p_nrow = mxGetM(p), p_ncol = mxGetN(p);" << endl
         << "  const double* p_data = (const double*)mxGetData(p);" << endl
         << "  bool is_sparse = mxIsSparse(p);" << endl
         << "  mwIndex *Jc = is_sparse ? mxGetJc(p) : 0;" << endl
         << "  mwIndex *Ir = is_sparse ? mxGetIr(p) : 0;" << endl
         << "  if (p_nrow==1 && p_ncol==1) {" << endl
         << "    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;" << endl
         << "    fill(y, nnz, v);" << endl
         << "  } else {" << endl
         << "    bool tr = false;" << endl
         << "    if (nrow!=p_nrow || ncol!=p_ncol) {" << endl
         << "      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);" << endl
         << "      if (!tr) mexErrMsgIdAndTxt(\"Casadi:RuntimeError\",\"\\\"from_mex\\\""
         << " failed: Dimension mismatch.\");" << endl
         << "    }" << endl
         << "    int r,c,k;" << endl
         << "    if (is_sparse) {" << endl
         << "      if (tr) {" << endl
         << "        for (c=0; c<ncol; ++c)" << endl
         << "          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;" << endl
         << "        for (c=0; c<p_ncol; ++c)" << endl
         << "          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];" << endl
         << "        for (c=0; c<ncol; ++c)" << endl
         << "          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];" << endl
         << "      } else {" << endl
         << "        for (c=0; c<ncol; ++c) {" << endl
         << "          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;" << endl
         << "          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];" << endl
         << "          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];" << endl
         << "        }" << endl
         << "      }" << endl
         << "    } else {" << endl
         << "      for (c=0; c<ncol; ++c) {" << endl
         << "        for (k=colind[c]; k<colind[c+1]; ++k) {" << endl
         << "          y[k] = p_data[row[k]+c*nrow];" << endl
         << "        }" << endl
         << "      }" << endl
         << "    }" << endl
         << "  }" << endl
         << "  return y;" << endl
         << "}" << endl
         << "#define from_mex(p, y, sp, w) CASADI_PREFIX(from_mex)(p, y, sp, w)" << endl
         << "#endif" << endl << endl;
       break;
     }
   }
void casadi::CodeGenerator::addExternal (const std::string & new_external)
Definition at line 386 of file code_generator.cpp.
Referenced by casadi::External::addDependency().
{
     added_externals_.insert(new_external);
   }
void casadi::CodeGenerator::addInclude (const std::string & new_include, bool relative_path = false, const std::string & use_ifdef = std::string())
Definition at line 347 of file code_generator.cpp.
Referenced by casadi::FunctionInternal::generateFunction().
{
     // Register the new element
     bool added = added_includes_.insert(new_include).second;
     // Quick return if it already exists
     if (!added) return;
     // Ifdef opening
     if (!use_ifdef.empty()) this->includes << "#ifdef " << use_ifdef << endl;
     // Print to the header section
     if (relative_path) {
       this->includes << "#include \"" << new_include << "\"" << endl;
     } else {
       this->includes << "#include <" << new_include << ">" << endl;
     }
     // Ifdef closing
     if (!use_ifdef.empty()) this->includes << "#endif" << endl;
   }
int casadi::CodeGenerator::addSparsity (const Sparsity & sp)
Definition at line 390 of file code_generator.cpp.
References casadi::Sparsity::compress(), and casadi::SharedObject::get().
Referenced by casadi::FunctionInternal::generateMeta().
{
     // Get the current number of patterns before looking for it
     size_t num_patterns_before = added_sparsities_.size();
     // Get index of the pattern
     const void* h = static_cast<const void*>(sp.get());
     int& ind = added_sparsities_[h];
     // Generate it if it does not exist
     if (added_sparsities_.size() > num_patterns_before) {
       // Compact version of the sparsity pattern
       std::vector<int> sp_compact = sp.compress();
       // Codegen vector
       ind = getConstant(sp_compact, true);
     }
     return ind;
   }
void casadi::CodeGenerator::assign (std::ostream & s, const std::string & lhs, const std::string & rhs) static
Definition at line 324 of file code_generator.cpp.
Referenced by casadi::Bilin::generate(), casadi::Dot::generate(), and casadi::NormF::generate().
{
     s << "  " << lhs << " = " << rhs << ";" << endl;
   }
std::string casadi::CodeGenerator::bilin (const std::string & A, const Sparsity & sp_A, const std::string & x, const std::string & y)
Definition at line 738 of file code_generator.cpp.
Referenced by casadi::Bilin::generate().
{
     addAuxiliary(AUX_BILIN);
     stringstream s;
     s << "bilin(" << A << ", " << sparsity(sp_A) << ", " << x << ", " << y << ")";
     return s.str();
   }
std::string casadi::CodeGenerator::compile (const std::string & name, const std::string & compiler = "gcc -fPIC -O2")
Definition at line 817 of file code_generator.cpp.
Referenced by casadi::FunctionInternal::dynamicCompilation().
{
     // Flag to get a DLL
 #ifdef __APPLE__
     string dlflag = " -dynamiclib";
 #else // __APPLE__
     string dlflag = " -shared";
 #endif // __APPLE__
     // File names
     string cname = name + (this->cpp ? ".cpp" : ".c"), dlname = "./" + name + ".so";
     // Remove existing files, if any
     string rm_command = "rm -rf " + cname + " " + dlname;
     int flag = system(rm_command.c_str());
     casadi_assert_message(flag==0, "Failed to remove old source");
     // Codegen it
     generate(name);
     // Compile it
     string compile_command = compiler + " " + dlflag + " " + cname + " -o " + dlname;
     flag = system(compile_command.c_str());
     casadi_assert_message(flag==0, "Compilation failed");
     // Return name of compiled function
     return dlname;
   }
std::string casadi::CodeGenerator::constant (double v) static
Definition at line 690 of file code_generator.cpp.
References casadi::isinf(), and casadi::isnan().
Referenced by casadi::Constant< Value >::generate(), and casadi::SXFunction::generateBody().
{
     stringstream s;
     if (isnan(v)) {
       s << "NAN";
     } else if (isinf(v)) {
       if (v<0) s << "-";
       s << "INFINITY";
     } else {
       int v_int(v);
       if (v_int==v) {
         // Print integer
         s << v_int << ".";
       } else {
         // Print real
         std::ios_base::fmtflags fmtfl = s.flags(); // get current format flags
         s << std::scientific << std::setprecision(std::numeric_limits<double>::digits10 + 1) << v;
         s.flags(fmtfl); // reset current format flags
       }
     }
     return s.str();
   }
std::string casadi::CodeGenerator::copy (const std::string & arg, std::size_t n, const std::string & res)
Definition at line 712 of file code_generator.cpp.
Referenced by casadi::Multiplication::generate(), casadi::Assertion::generate(), casadi::Monitor::generate(), casadi::Split::generate(), casadi::Rank1::generate(), casadi::Reshape::generate(), casadi::HorzRepmat::generate(), casadi::SetNonzerosVector< Add >::generate(), casadi::DenseMultiplication::generate(), casadi::ConstantDM::generate(), casadi::SetNonzerosSlice< Add >::generate(), casadi::SetNonzerosSlice2< Add >::generate(), and casadi::MXFunction::generateBody().
{
     stringstream s;
     // Perform operation
     addAuxiliary(AUX_COPY);
     s << "copy(" << arg << ", " << n << ", " << res << ");";
     return s.str();
   }
std::string casadi::CodeGenerator::declare (std::string s)
Definition at line 756 of file code_generator.cpp.
Referenced by casadi::FunctionInternal::generateMeta().
{
     // Add C linkage?
     if (this->cpp) {
       s = "extern \"C\" " + s;
     }
     // To header file
     if (this->with_header) {
       this->header << s << ";" << endl;
     }
     return s;
   }
std::string casadi::CodeGenerator::dot (int n, const std::string & x, const std::string & y)
Definition at line 730 of file code_generator.cpp.
Referenced by casadi::Dot::generate(), and casadi::NormF::generate().
{
     addAuxiliary(AUX_DOT);
     stringstream s;
     s << "dot(" << n << ", " << x << ", " << y << ")";
     return s.str();
   }
template<typename T > static bool casadi::CodeGenerator::equal (const std::vector< T > & v1, const std::vector< T > & v2) inline static
Definition at line 251 of file code_generator.hpp.
{
       if (v1.size()!=v2.size()) return false;
       for (int j=0; j<v1.size(); ++j) {
         if (v1[j]!=v2[j]) return false;
       }
       return true;
     }
std::string casadi::CodeGenerator::fill (const std::string & res, std::size_t n, const std::string & v)
Definition at line 721 of file code_generator.cpp.
Referenced by casadi::HorzRepsum::generate(), casadi::Constant< Value >::generate(), casadi::MXFunction::generateBody(), and casadi::MapSum::generateBody().
{
     stringstream s;
     // Perform operation
     addAuxiliary(AUX_FILL);
     s << "fill(" << res << ", " << n << ", " << v << ");";
     return s.str();
   }
std::string casadi::CodeGenerator::from_mex (std::string & arg, const std::string & res, std::size_t res_off, const Sparsity & sp_res, const std::string & w)
Definition at line 663 of file code_generator.cpp.
Referenced by casadi::FunctionInternal::generateMeta().
{
     // Handle offset with recursion
     if (res_off!=0) return from_mex(arg, res+"+"+to_string(res_off), 0, sp_res, w);
     addAuxiliary(AUX_FROM_MEX);
     stringstream s;
     s << "from_mex(" << arg
       << ", " << res << ", " << sparsity(sp_res) << ", " << w << ");";
     return s.str();
   }
void casadi::CodeGenerator::generate (std::ostream & s) const
Definition at line 272 of file code_generator.cpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::Nlpsol::generate_dependencies(), and casadi::Scpgen::init().
{
     // Codegen auxiliary functions
     s << this->auxiliaries.str();
     // Print integer constants
     stringstream name;
     for (int i=0; i<integer_constants_.size(); ++i) {
       name.str(string());
       name << "CASADI_PREFIX(s" << i << ")";
       print_vector(s, name.str(), integer_constants_[i]);
       s << "#define s" << i << " CASADI_PREFIX(s" << i << ")" << endl;
     }
     // Print double constants
     for (int i=0; i<double_constants_.size(); ++i) {
       name.str(string());
       name << "CASADI_PREFIX(c" << i << ")";
       print_vector(s, name.str(), double_constants_[i]);
       s << "#define c" << i << " CASADI_PREFIX(c" << i << ")" << endl;
     }
     // Codegen body
     s << this->body.str();
     // End with new line
     s << endl;
   }
void casadi::CodeGenerator::generate (const std::string & name) const
Definition at line 106 of file code_generator.cpp.
{
     // File(s) being generated, header is optional
     vector<ofstream> s(this->with_header ? 2 : 1);
     // Divide name into base and suffix (.c by default)
     string basename, suffix;
     string::size_type dotpos = name.rfind('.');
     if (dotpos==string::npos) {
       basename = name;
       suffix = this->cpp ? ".cpp" : ".c";
     } else {
       basename = name.substr(0, dotpos);
       suffix = name.substr(dotpos);
     }
     // Make sure that the base name is sane
     casadi_assert(Function::check_name(basename));
     // Create files
     for (int i=0; i<s.size(); ++i) {
       // Create file(s)
       string fname = i==0 ? basename + suffix : basename + ".h";
       s[i].open(fname.c_str());
       // Print header
       s[i] << "/* This function was automatically generated by CasADi */" << endl;
       // C linkage
       if (!this->cpp) {
         s[i] << "#ifdef __cplusplus" << endl
           << "extern \"C\" {" << endl
           << "#endif" << endl << endl;
       }
     }
     // Prefix internal symbols to avoid symbol collisions
     s[0] << "#ifdef CODEGEN_PREFIX" << endl
          << "  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)" << endl
          << "  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID" << endl
          << "  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)" << endl
          << "#else /* CODEGEN_PREFIX */" << endl
          << "  #define CASADI_PREFIX(ID) " << basename << "_ ## ID" << endl
          << "#endif /* CODEGEN_PREFIX */" << endl << endl;
     s[0] << this->includes.str();
     s[0] << endl;
     // Real type (usually double)
     for (int i=0; i<s.size(); ++i) {
       s[i]
         << "#ifndef real_t" << endl
         << "#define real_t " << this->real_t << endl
         << "#define to_double(x) "
         << (this->cpp ? "static_cast<double>(x)" : "(double) x") << endl
         << "#define to_int(x) "
         << (this->cpp ? "static_cast<int>(x)" : "(int) x") << endl
         << "#endif /* real_t */" << endl << endl;
     }
     // External function declarations
     if (!added_externals_.empty()) {
       s[0] << "/* External functions */" << endl;
       for (auto&& i : added_externals_) {
         s[0] << i << endl;
       }
       s[0] << endl << endl;
     }
     // Pre-C99
     s[0] << "/* Pre-c99 compatibility */" << endl
          << "#if __STDC_VERSION__ < 199901L" << endl
          << "real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}" << endl
          << "#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)" << endl
          << "real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}" << endl
          << "#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)" << endl
          << "#endif" << endl << endl;
     // Generate the actual function
     generate(s[0]);
     // Generate header
     if (this->with_header) {
       s[1] << this->header.str();
     }
     // Mex gateway
     if (this->mex) {
       // Begin conditional compilation
       s[0] << "#ifdef MATLAB_MEX_FILE" << endl;
       // Function prototype
       if (this->cpp) s[0] << "extern \"C\"" << endl; // C linkage
       s[0] << "void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {"
            << endl;
       // Create a buffer
       size_t buf_len = 0;
       for (int i=0; i<exposed_fname.size(); ++i) {
         buf_len = std::max(buf_len, exposed_fname[i].size());
       }
       s[0] << "  char buf[" << (buf_len+1) << "];" << endl;
       // Read string argument
       s[0] << "  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));" << endl;
       // Create switch
       s[0] << "  if (!buf_ok) {" << endl
            << "    /* name error */" << endl;
       for (int i=0; i<exposed_fname.size(); ++i) {
         s[0] << "  } else if (strcmp(buf, \"" << exposed_fname[i] << "\")==0) {" << endl
              << "    return mex_" << exposed_fname[i] << "(resc, resv, argc, argv);" << endl;
       }
       s[0] << "  }" << endl;
       // Error
       s[0] << "  mexErrMsgTxt(\"First input should be a command string. Possible values:";
       for (int i=0; i<exposed_fname.size(); ++i) {
         s[0] << " '" << exposed_fname[i] << "'";
       }
       s[0] << "\");" << endl;
       // End conditional compilation and function
       s[0] << "}" << endl
            << "#endif" << endl;
     }
     // Generate main
     if (this->main) {
       s[0] << "int main(int argc, char* argv[]) {" << endl;
       // Create switch
       s[0] << "  if (argc<2) {" << endl
            << "    /* name error */" << endl;
       for (int i=0; i<exposed_fname.size(); ++i) {
         s[0] << "  } else if (strcmp(argv[1], \"" << exposed_fname[i] << "\")==0) {" << endl
              << "    return main_" << exposed_fname[i] << "(argc-2, argv+2);" << endl;
       }
       s[0] << "  }" << endl;
       // Error
       s[0] << "  fprintf(stderr, \"First input should be a command string. Possible values:";
       for (int i=0; i<exposed_fname.size(); ++i) {
         s[0] << " '" << exposed_fname[i] << "'";
       }
       s[0] << "\\n\");" << endl;
       // End main
       s[0] << "  return 1;" << endl
            << "}" << endl;
     }
     // Finalize file(s)
     for (int i=0; i<s.size(); ++i) {
       // C linkage
       if (!this->cpp) {
         s[i] << "#ifdef __cplusplus" << endl;
         s[i] << "} /* extern \"C\" */" << endl;
         s[i] << "#endif" << endl;
       }
       // Close file(s)
       s[i].close();
     }
   }
std::string casadi::CodeGenerator::generate () const
Definition at line 100 of file code_generator.cpp.
{
     stringstream s;
     generate(s);
     return s.str();
   }
int casadi::CodeGenerator::get_sparsity (const Sparsity & sp) const
Definition at line 415 of file code_generator.cpp.
References casadi::SharedObject::get().
{
     const void* h = static_cast<const void*>(sp.get());
     PointerMap::const_iterator it=added_sparsities_.find(h);
     casadi_assert(it!=added_sparsities_.end());
     return it->second;
   }
int casadi::CodeGenerator::getConstant (const std::vector< double > & v, bool allow_adding = false)
Definition at line 442 of file code_generator.cpp.
Referenced by casadi::GetNonzerosVector::generate(), casadi::SetNonzerosVector< Add >::generate(), and casadi::ConstantDM::generate().
{
     // Hash the vector
     size_t h = hash(v);
     // Try to locate it in already added constants
     pair<multimap<size_t, size_t>::iterator, multimap<size_t, size_t>::iterator> eq =
       added_double_constants_.equal_range(h);
     for (multimap<size_t, size_t>::iterator i=eq.first; i!=eq.second; ++i) {
       if (equal(v, double_constants_[i->second])) return i->second;
     }
     if (allow_adding) {
       // Add to constants
       int ind = double_constants_.size();
       double_constants_.push_back(v);
       added_double_constants_.insert(pair<size_t, size_t>(h, ind));
       return ind;
     } else {
       casadi_error("Constant not found");
       return -1;
     }
   }
int casadi::CodeGenerator::getConstant (const std::vector< int > & v, bool allow_adding = false)
Definition at line 465 of file code_generator.cpp.
{
     // Hash the vector
     size_t h = hash(v);
     // Try to locate it in already added constants
     pair<multimap<size_t, size_t>::iterator, multimap<size_t, size_t>::iterator> eq =
       added_integer_constants_.equal_range(h);
     for (multimap<size_t, size_t>::iterator i=eq.first; i!=eq.second; ++i) {
       if (equal(v, integer_constants_[i->second])) return i->second;
     }
     if (allow_adding) {
       // Add to constants
       int ind = integer_constants_.size();
       integer_constants_.push_back(v);
       added_integer_constants_.insert(pair<size_t, size_t>(h, ind));
       return ind;
     } else {
       casadi_error("Constant not found");
       return -1;
     }
   }
size_t casadi::CodeGenerator::hash (const std::vector< double > & v) static
Definition at line 422 of file code_generator.cpp.
References casadi::hash_combine().
{
     // Calculate a hash value for the vector
     std::size_t seed=0;
     if (!v.empty()) {
       casadi_assert(sizeof(double) % sizeof(size_t)==0);
       const int int_len = v.size()*(sizeof(double)/sizeof(size_t));
       const size_t* int_v = reinterpret_cast<const size_t*>(&v.front());
       for (size_t i=0; i<int_len; ++i) {
         hash_combine(seed, int_v[i]);
       }
     }
     return seed;
   }
size_t casadi::CodeGenerator::hash (const std::vector< int > & v) static
Definition at line 436 of file code_generator.cpp.
References casadi::hash_combine().
{
     size_t seed=0;
     hash_combine(seed, v);
     return seed;
   }
std::string casadi::CodeGenerator::mtimes (const std::string & x, const Sparsity & sp_x, const std::string & y, const Sparsity & sp_y, const std::string & z, const Sparsity & sp_z, const std::string & w, bool tr)
Definition at line 846 of file code_generator.cpp.
Referenced by casadi::Multiplication::generate().
{
     addAuxiliary(CodeGenerator::AUX_MTIMES);
     stringstream s;
     s << "mtimes(" << x << ", " << sparsity(sp_x) << ", " << y << ", " << sparsity(sp_y) << ", "
       << z << ", " << sparsity(sp_z) << ", " << w << ", " <<  (tr ? "1" : "0") << ");";
     return s.str();
   }
std::string casadi::CodeGenerator::operator() (const Function & f, const std::string & arg, const std::string & res, const std::string & iw, const std::string & w, const std::string & mem = "0") const
Definition at line 374 of file code_generator.cpp.
References casadi::FunctionInternal::codegen_name().
{
     return f->codegen_name(*this) + "(" + arg + ", " + res + ", "
       + iw + ", " + w + ", " + mem + ")";
   }
std::string casadi::CodeGenerator::operator() (const Function & f, const std::string & arg, const std::string & res) const
Definition at line 381 of file code_generator.cpp.
References casadi::FunctionInternal::codegen_name().
{
     return f->codegen_name(*this) + "(" + arg + ", " + res + ")";
   }
static void casadi::CodeGenerator::print_vector (std::ostream & s, const std::string & name, const std::vector< int > & v) static
static void casadi::CodeGenerator::print_vector (std::ostream & s, const std::string & name, const std::vector< double > & v) static
std::string casadi::CodeGenerator::printf (const std::string & str, const std::vector< std::string > & arg = std::vector<std::string>())
Definition at line 785 of file code_generator.cpp.
Referenced by casadi::Monitor::generate(), and casadi::FunctionInternal::generateMeta().
{
     addInclude("stdio.h");
     stringstream s;
     s << "PRINTF(\"" << str << "\"";
     for (int i=0; i<arg.size(); ++i) s << ", " << arg[i];
     s << ");";
     return s.str();
   }
std::string casadi::CodeGenerator::printf (const std::string & str, const std::string & arg1)
Definition at line 794 of file code_generator.cpp.
{
     std::vector<std::string> arg;
     arg.push_back(arg1);
     return printf(str, arg);
   }
std::string casadi::CodeGenerator::printf (const std::string & str, const std::string & arg1, const std::string & arg2)
Definition at line 800 of file code_generator.cpp.
{
     std::vector<std::string> arg;
     arg.push_back(arg1);
     arg.push_back(arg2);
     return printf(str, arg);
   }
std::string casadi::CodeGenerator::printf (const std::string & str, const std::string & arg1, const std::string & arg2, const std::string & arg3)
Definition at line 808 of file code_generator.cpp.
{
     std::vector<std::string> arg;
     arg.push_back(arg1);
     arg.push_back(arg2);
     arg.push_back(arg3);
     return printf(str, arg);
   }
std::string casadi::CodeGenerator::project (const std::string & arg, const Sparsity & sp_arg, const std::string & res, const Sparsity & sp_res, const std::string & w)
Definition at line 771 of file code_generator.cpp.
References casadi::copy(), and casadi::Sparsity::nnz().
Referenced by casadi::Project::generate().
{
     // If sparsity match, simple copy
     if (sp_arg==sp_res) return copy(arg, sp_arg.nnz(), res);
     // Create call
     addAuxiliary(CodeGenerator::AUX_PROJECT);
     stringstream s;
     s << "  project(" << arg << ", " << sparsity(sp_arg) << ", " << res << ", "
       << sparsity(sp_res) << ", " << w << ");";
     return s.str();
   }
std::string casadi::CodeGenerator::rank1 (const std::string & A, const Sparsity & sp_A, const std::string & alpha, const std::string & x, const std::string & y)
Definition at line 746 of file code_generator.cpp.
Referenced by casadi::Rank1::generate().
{
     addAuxiliary(AUX_RANK1);
     stringstream s;
     s << "rank1(" << A << ", " << sparsity(sp_A) << ", "
       << alpha << ", " << x << ", " << y << ");";
     return s.str();
   }
bool casadi::CodeGenerator::simplifiedCall (const Function & f) static
Definition at line 369 of file code_generator.cpp.
References casadi::FunctionInternal::simplifiedCall().
Referenced by casadi::Switch::generateBody().
{
     return f->simplifiedCall();
   }
std::string casadi::CodeGenerator::sparsity (const Sparsity & sp)
Definition at line 411 of file code_generator.cpp.
Referenced by casadi::Find::generate(), and casadi::Transpose::generate().
{
     return "s" + to_string(addSparsity(sp));
   }
std::string casadi::CodeGenerator::to_mex (const Sparsity & sp, const std::string & arg)
Definition at line 656 of file code_generator.cpp.
Referenced by casadi::FunctionInternal::generateMeta().
{
     addAuxiliary(AUX_TO_MEX);
     stringstream s;
     s << "to_mex(" << sparsity(sp) << ", " << arg << ");";
     return s.str();
   }
std::string casadi::CodeGenerator::to_string (int n) static
Convert in integer to a string
Definition at line 300 of file code_generator.cpp.
Referenced by casadi::FunctionInternal::addDependency(), casadi::Split::generate(), casadi::HorzRepmat::generate(), casadi::Call::generate(), casadi::ConstantDM::generate(), casadi::MXFunction::generateBody(), casadi::FunctionInternal::generateMeta(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::mx_out(), casadi::OutputNode::print(), casadi::MXFunction::print(), casadi::FunctionInternal::sx_in(), and casadi::FunctionInternal::sx_out().
{
     stringstream ss;
     ss << n;
     return ss.str();
   }
std::string casadi::CodeGenerator::work (int n, int sz) const
Get work vector name from index
Definition at line 306 of file code_generator.cpp.
Referenced by casadi::Multiplication::generate(), casadi::Concat::generate(), casadi::Project::generate(), casadi::Find::generate(), casadi::Monitor::generate(), casadi::Split::generate(), casadi::Assertion::generate(), casadi::Dot::generate(), casadi::Rank1::generate(), casadi::Bilin::generate(), casadi::UnaryMX::generate(), casadi::Reshape::generate(), casadi::Transpose::generate(), casadi::HorzRepmat::generate(), casadi::NormF::generate(), casadi::Call::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::GetNonzerosVector::generate(), casadi::SetNonzerosVector< Add >::generate(), casadi::DenseMultiplication::generate(), casadi::DenseTranspose::generate(), casadi::HorzRepsum::generate(), casadi::ConstantDM::generate(), casadi::GetNonzerosSlice::generate(), casadi::SetNonzerosSlice< Add >::generate(), casadi::GetNonzerosSlice2::generate(), casadi::SetNonzerosSlice2< Add >::generate(), casadi::Constant< Value >::generate(), and casadi::MXFunction::generateBody().
{
     if (n<0 || sz==0) {
       return "0";
     } else if (sz==1 && !this->codegen_scalars) {
       return "(&w" + to_string(n) + ")";
     } else {
       return "w" + to_string(n);
     }
   }
std::string casadi::CodeGenerator::workel (int n) const
Get work vector element from index
Definition at line 316 of file code_generator.cpp.
Referenced by casadi::Concat::generate(), casadi::Find::generate(), casadi::Monitor::generate(), casadi::Assertion::generate(), casadi::Split::generate(), casadi::Rank1::generate(), casadi::Dot::generate(), casadi::Bilin::generate(), casadi::UnaryMX::generate(), casadi::NormF::generate(), casadi::Call::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::Constant< Value >::generate(), and casadi::MXFunction::generateBody().
{
     if (n<0) return "0";
     stringstream s;
     if (this->codegen_scalars) s << "*";
     s << "w" << n;
     return s.str();
   }
Member Data Documentation
std::set<Auxiliary> casadi::CodeGenerator::added_auxiliaries_
Definition at line 235 of file code_generator.hpp.
PointerMap casadi::CodeGenerator::added_dependencies_
Definition at line 237 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::addDependency(), and casadi::FunctionInternal::codegen_name().
std::multimap<size_t, size_t> casadi::CodeGenerator::added_double_constants_
Definition at line 238 of file code_generator.hpp.
std::set<std::string> casadi::CodeGenerator::added_externals_
Definition at line 234 of file code_generator.hpp.
std::set<std::string> casadi::CodeGenerator::added_includes_
Definition at line 233 of file code_generator.hpp.
std::multimap<size_t, size_t> casadi::CodeGenerator::added_integer_constants_
Definition at line 239 of file code_generator.hpp.
PointerMap casadi::CodeGenerator::added_sparsities_
Definition at line 236 of file code_generator.hpp.
std::stringstream casadi::CodeGenerator::auxiliaries
Definition at line 224 of file code_generator.hpp.
std::stringstream casadi::CodeGenerator::body
Definition at line 225 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::addDependency(), casadi::Call::codegen_decref(), casadi::Call::codegen_incref(), casadi::Multiplication::generate(), casadi::Concat::generate(), casadi::Project::generate(), casadi::Assertion::generate(), casadi::Split::generate(), casadi::Monitor::generate(), casadi::Find::generate(), casadi::Bilin::generate(), casadi::Dot::generate(), casadi::Rank1::generate(), casadi::UnaryMX::generate(), casadi::Reshape::generate(), casadi::Transpose::generate(), casadi::HorzRepmat::generate(), casadi::NormF::generate(), casadi::Call::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::GetNonzerosVector::generate(), casadi::SetNonzerosVector< Add >::generate(), casadi::DenseMultiplication::generate(), casadi::DenseTranspose::generate(), casadi::HorzRepsum::generate(), casadi::MXNode::generate(), casadi::ConstantDM::generate(), casadi::GetNonzerosSlice::generate(), casadi::SetNonzerosSlice< Add >::generate(), casadi::GetNonzerosSlice2::generate(), casadi::SetNonzerosSlice2< Add >::generate(), casadi::Constant< Value >::generate(), casadi::Jit::generateBody(), casadi::Switch::generateBody(), casadi::KernelSum::generateBody(), casadi::MXFunction::generateBody(), casadi::Mapaccum::generateBody(), casadi::PureMap::generateBody(), casadi::SXFunction::generateBody(), casadi::MapSum::generateBody(), casadi::FunctionInternal::generateFunction(), and casadi::FunctionInternal::generateMeta().
bool casadi::CodeGenerator::codegen_scalars
Definition at line 220 of file code_generator.hpp.
Referenced by casadi::MXFunction::generateBody().
bool casadi::CodeGenerator::cpp
Definition at line 211 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::generateFunction().
std::vector<std::vector<double> > casadi::CodeGenerator::double_constants_
Definition at line 242 of file code_generator.hpp.
std::vector<std::string> casadi::CodeGenerator::exposed_fname
Definition at line 229 of file code_generator.hpp.
std::stringstream casadi::CodeGenerator::header
Definition at line 226 of file code_generator.hpp.
std::stringstream casadi::CodeGenerator::includes
Definition at line 223 of file code_generator.hpp.
std::vector<std::vector<int> > casadi::CodeGenerator::integer_constants_
Definition at line 243 of file code_generator.hpp.
bool casadi::CodeGenerator::main
Definition at line 214 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::generateMeta().
bool casadi::CodeGenerator::mex
Definition at line 205 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::generateMeta().
std::string casadi::CodeGenerator::real_t
Definition at line 199 of file code_generator.hpp.
bool casadi::CodeGenerator::verbose
Definition at line 208 of file code_generator.hpp.
Referenced by casadi::MXFunction::generateBody().
bool casadi::CodeGenerator::with_header
Definition at line 202 of file code_generator.hpp.
The documentation for this class was generated from the following files:
code_generator.hpp
code_generator.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge