CasADi: casadi::CompilerInternal Class Reference
casadi::CompilerInternal Class Reference
Compiler internal class.
#include <compiler_internal.hpp>
Detailed Description
Author
Joel Andersson
Date
2010-2013
Definition at line 44 of file compiler_internal.hpp.
Classes
struct Exposed
Public Types
typedef CompilerInternal *(* Creator)(const std::string &name)
typedef int(* RegFcn)(Plugin *plugin)
Public Member Functions
CompilerInternal (const std::string &name)
Constructor.
virtual ~CompilerInternal ()
Destructor.
virtual void print (std::ostream &stream) const
Print.
virtual void repr (std::ostream &stream) const
Print representation.
void construct (const Dict &opts)
Construct Prepares the function for evaluation.
virtual void init (const Dict &opts)
Initialize.
virtual const char * plugin_name () const
Queery plugin name.
virtual void * getFunction (const std::string &symname)
Get a function pointer for numerical evaluation.
void get_meta (std::vector< std::string > &lines, int &offset) const
Get meta information, if any.
int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static std::string shortname ()
Short name.
static bool hasPlugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin loadPlugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static CompilerInternal * instantiatePlugin (const std::string &fname, const std::string &pname, Problem problem)
Public Attributes
std::string name_
C filename.
ParsedFile meta_
Meta information.
Static Public Attributes
static std::map< std::string,
Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "compiler"
Infix.
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
static Options options_
Options.
virtual const Options & get_options () const
Options.
Member Typedef Documentation
typedef CompilerInternal*(* casadi::CompilerInternal::Creator)(const std::string &name)
Definition at line 62 of file compiler_internal.hpp.
typedef int(* casadi::PluginInterface< CompilerInternal >::RegFcn)(Plugin *plugin) inherited
Definition at line 85 of file plugin_interface.hpp.
Constructor & Destructor Documentation
casadi::CompilerInternal::CompilerInternal (const std::string & name) explicit
Definition at line 31 of file compiler_internal.cpp.
                                                           : name_(name) {
   }
casadi::CompilerInternal::~CompilerInternal () virtual
Definition at line 34 of file compiler_internal.cpp.
{
   }
Member Function Documentation
void casadi::CompilerInternal::construct (const Dict & opts)
Definition at line 55 of file compiler_internal.cpp.
References casadi::Options::find(), get_options(), init(), and casadi::Options::Entry::type.
{
     // Get a reference to the options structure
     const Options& options = get_options();
     // Make sure all options exist and have the correct type
     for (auto&& op : opts) {
       const Options::Entry* entry = options.find(op.first);
       casadi_assert_message(entry!=0, "No such option: " + op.first);
       casadi_assert_message(op.second.can_cast_to(entry->type),
                             "Illegal type for " + op.first);
     }
     init(opts);
   }
void casadi::SharedObjectNode::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 199 of file shared_object.hpp.
{
       count--;
     }
void casadi::CompilerInternal::get_meta (std::vector< std::string > & lines, int & offset) const
Definition at line 78 of file compiler_internal.cpp.
References name_.
Referenced by init().
{
     // Open source file and search for meta information
     ifstream file(name_);
     std::string line;
     offset = 0;
     lines.clear();
     while (getline(file, line)) {
       // Update offset
       offset++;
       // Try to find a /*CASADI delimiter
       if (line.find("/*CASADIMETA") != string::npos) {
         // Delimimiter found, find */ delimiter
         while (getline(file, line)) {
           if (line.find("*/") != string::npos) return; // Successful return
           lines.push_back(line);
         }
         casadi_error("End-of-file reached while searching for \"*/\"");
       }
     }
   }
virtual const Options& casadi::CompilerInternal::get_options () const inline virtual
Reimplemented in casadi::ClangCompiler, and casadi::ShellCompiler.
Definition at line 72 of file compiler_internal.hpp.
Referenced by construct().
 { return options_;}
int casadi::SharedObjectNode::getCount () const inherited
Definition at line 163 of file shared_object.cpp.
Referenced by casadi::SharedObject::getCount().
{
     return count;
   }
virtual void* casadi::CompilerInternal::getFunction (const std::string & symname) inline virtual
Reimplemented in casadi::ClangCompiler, and casadi::ShellCompiler.
Definition at line 94 of file compiler_internal.hpp.
 { return 0;}
static Plugin& casadi::PluginInterface< CompilerInternal >::getPlugin (const std::string & pname) static inherited
static bool casadi::PluginInterface< CompilerInternal >::hasPlugin (const std::string & pname, bool verbose = false) static inherited
void casadi::CompilerInternal::init (const Dict & opts) virtual
Reimplemented in casadi::ClangCompiler, and casadi::ShellCompiler.
Definition at line 70 of file compiler_internal.cpp.
References get_meta(), and meta_.
Referenced by construct(), casadi::ShellCompiler::init(), and casadi::ClangCompiler::init().
{
     // Read meta information from file
     std::vector<std::string> lines;
     int offset;
     get_meta(lines, offset);
     meta_ = ParsedFile(lines, offset);
   }
void casadi::SharedObjectNode::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 193 of file shared_object.hpp.
{
       casadi_assert(count==0);
       count++;
     }
static CompilerInternal * casadi::PluginInterface< CompilerInternal >::instantiatePlugin (const std::string & fname, const std::string & pname, Problem problem) static inherited
static Plugin casadi::PluginInterface< CompilerInternal >::loadPlugin (const std::string & pname, bool register_plugin = true) static inherited
virtual const char* casadi::CompilerInternal::plugin_name () const inline virtual
Implements casadi::PluginInterface< CompilerInternal >.
Reimplemented in casadi::ClangCompiler, and casadi::ShellCompiler.
Definition at line 91 of file compiler_internal.hpp.
 { return "none";}
static Plugin casadi::PluginInterface< CompilerInternal >::pluginFromRegFcn (RegFcn regfcn) static inherited
void casadi::CompilerInternal::print (std::ostream & stream) const virtual
Reimplemented from casadi::SharedObjectNode.
Definition at line 37 of file compiler_internal.cpp.
{
     stream << "Compiler" << endl;
   }
static void casadi::PluginInterface< CompilerInternal >::registerPlugin (const Plugin & plugin) static inherited
static void casadi::PluginInterface< CompilerInternal >::registerPlugin (RegFcn regfcn) static inherited
void casadi::CompilerInternal::repr (std::ostream & stream) const virtual
Reimplemented from casadi::SharedObjectNode.
Definition at line 41 of file compiler_internal.cpp.
{
     stream << "Compiler" << endl;
   }
template<class B > B casadi::SharedObjectNode::shared_from_this () protected inherited
Template function implementations
Definition at line 271 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(this);
     return ret;
   }
template<class B > const B casadi::SharedObjectNode::shared_from_this () const protected inherited
Definition at line 279 of file shared_object.hpp.
{
     casadi_assert(B::test_cast(this));
     B ret;
     ret.assignNode(const_cast<SharedObjectNode*>(this));
     return ret;
   }
static std::string casadi::CompilerInternal::shortname () inline static
Definition at line 88 of file compiler_internal.hpp.
 { return "compiler";}
WeakRef * casadi::SharedObjectNode::weak () inherited
Definition at line 171 of file shared_object.cpp.
Referenced by casadi::SharedObject::weak().
{
     if (weak_ref_==0) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Member Data Documentation
const std::string casadi::CompilerInternal::infix_ = "compiler" static
Definition at line 85 of file compiler_internal.hpp.
ParsedFile casadi::CompilerInternal::meta_
Definition at line 103 of file compiler_internal.hpp.
Referenced by init().
std::string casadi::CompilerInternal::name_
Definition at line 100 of file compiler_internal.hpp.
Referenced by get_meta(), casadi::ShellCompiler::init(), and casadi::ClangCompiler::init().
Options casadi::CompilerInternal::options_ static
Initial value:
= {{},
     {{}
     }
  }
Definition at line 71 of file compiler_internal.hpp.
std::map< std::string, CompilerInternal::Plugin > casadi::CompilerInternal::solvers_ static
Definition at line 82 of file compiler_internal.hpp.
The documentation for this class was generated from the following files:
compiler_internal.hpp
compiler_internal.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge