CasADi: casadi::InfSX Class Reference
casadi::InfSX Class Reference
Represents an infinity SX.
#include <constant_sx.hpp>
Detailed Description
Author
Joel Andersson
Date
2010
Definition at line 266 of file constant_sx.hpp.
Public Member Functions
InfSX ()
virtual ~InfSX ()
virtual double to_double () const
Get the value.
virtual bool isInf () const
Properties.
virtual bool is_constant () const
Properties.
virtual int op () const
Get the operation.
virtual bool is_equal (const SXNode *node, int depth) const
Check if two nodes are equivalent up to a given depth.
virtual void print (std::ostream &stream) const
print
virtual const std::string & name () const
virtual int ndep () const
Number of dependencies.
virtual const SXElem & dep (int i) const
get the reference of a child
virtual SXElem & dep (int i)
get the reference of a child
virtual bool is_smooth () const
Check if smooth.
void can_inline (std::map< const SXNode *, int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const SXNode *, int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
bool marked () const
void mark ()
virtual bool is_integer () const
check properties of a node
virtual bool is_symbolic () const
check properties of a node
virtual bool hasDep () const
check properties of a node
virtual bool is_zero () const
check properties of a node
virtual bool isAlmostZero (double tol) const
check properties of a node
virtual bool is_one () const
check properties of a node
virtual bool is_minus_one () const
check properties of a node
virtual bool isNan () const
check properties of a node
virtual bool isMinusInf () const
check properties of a node
virtual int to_int () const
Get value of a constant node.
Public Attributes
int temp
unsigned int count
Static Public Attributes
static int eq_depth_ = 1
Protected Member Functions
virtual std::string print (const std::string &arg1, const std::string &arg2) const
Print expression.
Constructor & Destructor Documentation
casadi::InfSX::InfSX () inline explicit
Definition at line 269 of file constant_sx.hpp.
 {}
virtual casadi::InfSX::~InfSX () inline virtual
Definition at line 270 of file constant_sx.hpp.
 {}
Member Function Documentation
void casadi::SXNode::can_inline (std::map< const SXNode *, int > & nodeind) const inherited
Definition at line 146 of file sx_node.cpp.
References casadi::OP_PARAMETER.
{
     // Add or mark node in map
     std::map<const SXNode*, int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, make_pair(this, 0));
       // Handle dependencies with recursion
       for (int i=0; i<ndep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
const SXElem & casadi::SXNode::dep (int i) const virtual inherited
Reimplemented in casadi::BinarySX, and casadi::UnarySX.
Definition at line 109 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), casadi::SXElem::dep(), casadi::SXFunction::evalAdj(), casadi::SXFunction::evalFwd(), casadi::SXFunction::init(), and casadi::BinarySX::~BinarySX().
{
     casadi_error("child() not defined for class " << typeid(*this).name());
   }
SXElem & casadi::SXNode::dep (int i) virtual inherited
Reimplemented in casadi::BinarySX, and casadi::UnarySX.
Definition at line 113 of file sx_node.cpp.
{
     casadi_error("child() not defined for class " << typeid(*this).name());
   }
bool casadi::SXNode::hasDep () const virtual inherited
Reimplemented in casadi::BinarySX, and casadi::UnarySX.
Definition at line 97 of file sx_node.cpp.
Referenced by casadi::SXElem::hasDep(), and casadi::BinarySX::~BinarySX().
{
     return false;
   }
virtual bool casadi::ConstantSX::is_constant () const inline virtual inherited
Reimplemented from casadi::SXNode.
Definition at line 54 of file constant_sx.hpp.
 { return true; }
virtual bool casadi::ConstantSX::is_equal (const SXNode * node, int depth) const inline virtual inherited
Reimplemented from casadi::SXNode.
Definition at line 60 of file constant_sx.hpp.
References casadi::ConstantSX::to_double().
{
   const ConstantSX* n = dynamic_cast<const ConstantSX*>(node);
   return n && n->to_double()==to_double();
 }
bool casadi::SXNode::is_integer () const virtual inherited
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, and casadi::IntegerSX.
Definition at line 89 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_integer().
{
     return false;
   }
bool casadi::SXNode::is_minus_one () const virtual inherited
Reimplemented in casadi::MinusOneSX.
Definition at line 69 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_minus_one().
{
     return false;
   }
bool casadi::SXNode::is_one () const virtual inherited
Reimplemented in casadi::OneSX.
Definition at line 65 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_one().
{
     return false;
   }
bool casadi::SXNode::is_smooth () const virtual inherited
Reimplemented in casadi::BinarySX, and casadi::UnarySX.
Definition at line 117 of file sx_node.cpp.
{
     return true; // nodes are smooth by default
   }
bool casadi::SXNode::is_symbolic () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 93 of file sx_node.cpp.
Referenced by casadi::SXFunction::init(), and casadi::SXElem::is_symbolic().
{
     return false;
   }
bool casadi::SXNode::is_zero () const virtual inherited
Reimplemented in casadi::ZeroSX.
Definition at line 57 of file sx_node.cpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_zero().
{
     return false;
   }
bool casadi::SXNode::isAlmostZero (double tol) const virtual inherited
Reimplemented in casadi::ZeroSX, and casadi::RealtypeSX.
Definition at line 61 of file sx_node.cpp.
Referenced by casadi::SXElem::isAlmostZero().
{
     return false;
   }
virtual bool casadi::InfSX::isInf () const inline virtual
Reimplemented from casadi::SXNode.
Definition at line 276 of file constant_sx.hpp.
 { return true; }
bool casadi::SXNode::isMinusInf () const virtual inherited
Reimplemented in casadi::MinusInfSX.
Definition at line 81 of file sx_node.cpp.
Referenced by casadi::SXElem::isMinusInf().
{
     return false;
   }
bool casadi::SXNode::isNan () const virtual inherited
Reimplemented in casadi::NanSX.
Definition at line 73 of file sx_node.cpp.
Referenced by casadi::SXElem::isNan().
{
     return false;
   }
void casadi::SXNode::mark () inherited
Definition at line 142 of file sx_node.cpp.
                     {
     temp = -temp-1;
   }
bool casadi::SXNode::marked () const inherited
Definition at line 138 of file sx_node.cpp.
{
     return temp<0;
   }
const std::string & casadi::SXNode::name () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 105 of file sx_node.cpp.
Referenced by casadi::SXElem::name().
{
     throw CasadiException("SXNode::name failed, the node must be symbolic");
   }
virtual int casadi::SXNode::ndep () const inline virtual inherited
Reimplemented in casadi::BinarySX, and casadi::UnarySX.
Definition at line 87 of file sx_node.hpp.
Referenced by casadi::BinarySX::~BinarySX().
 { return 0;}
virtual int casadi::ConstantSX::op () const inline virtual inherited
Implements casadi::SXNode.
Definition at line 57 of file constant_sx.hpp.
References casadi::OP_CONST.
 { return OP_CONST;}
virtual std::string casadi::ConstantSX::print (const std::string & arg1, const std::string & arg2) const inline protected virtual inherited
Implements casadi::SXNode.
Definition at line 68 of file constant_sx.hpp.
{
    std::stringstream ss;
    ss << to_double();
    return ss.str();
  }
void casadi::SXNode::print (std::ostream & stream) const virtual inherited
Definition at line 121 of file sx_node.cpp.
Referenced by casadi::SXElem::print().
{
     // Find out which noded can be inlined
     std::map<const SXNode*, int> nodeind;
     can_inline(nodeind);
     // Print expression
     vector<string> intermed;
     string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
std::string casadi::SXNode::print_compact (std::map< const SXNode *, int > & nodeind, std::vector< std::string > & intermed) const inherited
Definition at line 163 of file sx_node.cpp.
References casadi::print().
{
     // Get reference to node index
     int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) {
       stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
     // Get expressions for dependencies
     std::string arg[2];
     for (int i=0; i<ndep(); ++i) {
       arg[i] = dep(i)->print_compact(nodeind, intermed);
     }
     // Get expression for this
     string s = print(arg[0], arg[1]);
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
   }
virtual double casadi::InfSX::to_double () const inline virtual
Implements casadi::ConstantSX.
Definition at line 273 of file constant_sx.hpp.
 { return std::numeric_limits<double>::infinity();}
int casadi::SXNode::to_int () const virtual inherited
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 53 of file sx_node.cpp.
Referenced by casadi::SXElem::binary().
{
     throw CasadiException(string("to_int() not defined for class ") + typeid(*this).name());
   }
Member Data Documentation
unsigned int casadi::SXNode::count inherited
Definition at line 127 of file sx_node.hpp.
Referenced by casadi::SXElem::assignNoDelete(), casadi::SXElem::operator=(), casadi::SXElem::SXElem(), casadi::BinarySX::~BinarySX(), and casadi::SXElem::~SXElem().
int casadi::SXNode::eq_depth_ = 1 static inherited
Definition at line 118 of file sx_node.hpp.
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_doubled().
int casadi::SXNode::temp inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 124 of file sx_node.hpp.
Referenced by casadi::SXFunction::init().
The documentation for this class was generated from the following file:
constant_sx.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge