CasADi: casadi::SXElem Class Reference
casadi::SXElem Class Reference
The basic scalar symbolic class of CasADi.
#include <sx_elem.hpp>
Detailed Description
SXElem is exposed only as an empty struct to SWIG
Author
Joel Andersson
Date
2010-2014
Definition at line 58 of file sx_elem.hpp.
Public Member Functions
SXElem ()
Default constructor (not-a-number) Object is initialized as not-a-number.
SXElem (double val)
Numerical constant constructor.
SXElem (SXNode *node, bool dummy)
SXElem (const SXElem &scalar)
Copy constructor.
~SXElem ()
Destructor.
SXElem & operator= (const SXElem &scalar)
Assignment.
SXElem & operator= (double scalar)
operator Matrix< SXElem > () const
Convert to a 1-by-1 Matrix.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
SXNode * get () const
Get a pointer to the node.
const SXNode * operator-> () const
Access functions of the node.
SXNode * operator-> ()
bool __nonzero__ () const
Check the truth value of this node Introduced to catch bool(x) situations in python.
bool is_leaf () const
check if this SXElem is a leaf of the SX graph
bool is_constant () const
bool is_integer () const
bool is_symbolic () const
bool hasDep () const
bool is_commutative () const
Check whether a binary SXElem is commutative.
bool is_zero () const
bool isAlmostZero (double tol) const
bool is_one () const
bool is_minus_one () const
bool isNan () const
bool isInf () const
bool isMinusInf () const
const std::string & name () const
int op () const
bool is_op (int op) const
bool is_regular () const
Checks if expression does not contain NaN or Inf.
bool isNonNegative () const
Check if a value is always nonnegative (false negatives are allowed)
SXElem dep (int ch=0) const
operator double () const
Type conversion to double.
operator int () const
Type conversion to int.
bool is_doubled () const
Check if the node is the sum of two equal expressions.
int n_dep () const
Get the number of dependencies of a binary SXElem.
size_t __hash__ () const
Returns a number that is unique for a given SXNode. If the SXElem does not point to any node, 0 is returned.
SXElem operator- () const
Negation.
SXElem inv () const
Elementwise inverse.
int getTemp () const
void setTemp (int t)
Set the temporary variable.
bool marked () const
Check if marked (i.e. temporary is negative)
void mark ()
Mark by flipping the sign of the temporary and decreasing by one.
void assignIfDuplicate (const SXElem &scalar, int depth=1)
Assign to another expression, if a duplicate. Check for equality up to a given depth.
SXNode * assignNoDelete (const SXElem &scalar)
Assign the node to something, without invoking the deletion of the node, if the count reaches 0.
bool is_null ()
SXElem nodes are not allowed to be null.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
SXElem & operator+= (const SXElem &y)
In-place addition.
SXElem & operator-= (const SXElem &y)
In-place subtraction.
SXElem & operator*= (const SXElem &y)
In-place elementwise multiplication.
SXElem & operator/= (const SXElem &y)
In-place elementwise division.
SXElem operator! () const
Logical not Returns (an expression evaluating to) 1 if expression is zero and 0 otherwise.
Static Public Member Functions
static SXElem sym (const std::string &name)
Create a symbolic primitive.
static SXElem create (SXNode *node)
static SXElem binary (int op, const SXElem &x, const SXElem &y)
Perform operations by ID.
static SXElem unary (int op, const SXElem &x)
static bool is_equal (const SXElem &x, const SXElem &y, int depth=0)
Check equality up to a given depth.
Protected Member Functions
const SXElem & self () const
SXElem & self ()
Friends
class SXNode
class BinarySXNode
class Matrix< SXElem >
SXElem if_else (const SXElem &cond, const SXElem &if_true, const SXElem &if_false, bool short_circuit)
inline if-test
Constructor & Destructor Documentation
casadi::SXElem::SXElem ()
Definition at line 45 of file sx_elem.cpp.
Referenced by create(), and operator=().
                  {
     node = casadi_limits<SXElem>::nan.node;
     node->count++;
   }
casadi::SXElem::SXElem (double val)
Parameters
val Numerical value
Definition at line 63 of file sx_elem.cpp.
References casadi::SXNode::count, casadi::RealtypeSX::create(), casadi::IntegerSX::create(), casadi::isinf(), and casadi::isnan().
{
     int intval = static_cast<int>(val);
     if (val-intval == 0) { // check if integer
       if (intval == 0)             node = casadi_limits<SXElem>::zero.node;
       else if (intval == 1)        node = casadi_limits<SXElem>::one.node;
       else if (intval == 2)        node = casadi_limits<SXElem>::two.node;
       else if (intval == -1)       node = casadi_limits<SXElem>::minus_one.node;
       else                        node = IntegerSX::create(intval);
       node->count++;
     } else {
       if (isnan(val))              node = casadi_limits<SXElem>::nan.node;
       else if (isinf(val))         node = val > 0 ? casadi_limits<SXElem>::inf.node :
                                       casadi_limits<SXElem>::minus_inf.node;
       else                        node = RealtypeSX::create(val);
       node->count++;
     }
   }
casadi::SXElem::SXElem (SXNode * node, bool dummy)
Create an expression from a node: extra dummy argument to avoid ambiguity for 0/NULL
Definition at line 50 of file sx_elem.cpp.
References casadi::SXNode::count.
                                           : node(node_) {
     node->count++;
   }
casadi::SXElem::SXElem (const SXElem & scalar)
Definition at line 58 of file sx_elem.cpp.
References casadi::SXNode::count.
{
     node = scalar.node;
     node->count++;
   }
casadi::SXElem::~SXElem ()
Definition at line 85 of file sx_elem.cpp.
References casadi::SXNode::count.
                   {
     if (--node->count == 0) delete node;
   }
Member Function Documentation
size_t casadi::SXElem::__hash__ () const
Definition at line 512 of file sx_elem.cpp.
{
     return reinterpret_cast<size_t>(node);
   }
bool casadi::SXElem::__nonzero__ () const
Definition at line 153 of file sx_elem.cpp.
References is_constant(), and is_zero().
{
     if (is_constant()) return !is_zero();
     casadi_error("Cannot compute the truth value of a CasADi SXElem symbolic expression.")
   }
void casadi::SXElem::assignIfDuplicate (const SXElem & scalar, int depth = 1)
Definition at line 102 of file sx_elem.cpp.
References is_equal().
Referenced by casadi::SXFunction::eval_sx().
{
     casadi_assert(depth>=1);
     if (!is_equal(*this, scalar, 0) && is_equal(*this, scalar, depth)) {
       *this = scalar;
     }
   }
SXNode * casadi::SXElem::assignNoDelete (const SXElem & scalar)
Definition at line 109 of file sx_elem.cpp.
References casadi::SXNode::count.
Referenced by casadi::BinarySX::~BinarySX().
{
     // Return value
     SXNode* ret = node;
     // quick return if the old and new pointers point to the same object
     if (node == scalar.node) return ret;
     // decrease the counter but do not delete if this was the last pointer
     --node->count;
     // save the new pointer
     node = scalar.node;
     node->count++;
     // Return a pointer to the old node
     return ret;
   }
SXElem casadi::SXElem::binary (int op, const SXElem & x, const SXElem & y) static
Definition at line 187 of file sx_elem.cpp.
References casadi::BinarySX::create(), casadi::SXNode::dep(), dep(), casadi::SXNode::eq_depth_, casadi::GenericExpression< SXElem >::fabs, inv(), casadi::SXNode::is_constant(), is_constant(), is_doubled(), is_equal(), casadi::SXNode::is_integer(), casadi::SXNode::is_minus_one(), is_minus_one(), casadi::SXNode::is_one(), is_one(), is_op(), casadi::SXNode::is_zero(), is_zero(), isNonNegative(), casadi::OP_ACOSH, casadi::OP_ADD, casadi::OP_ASINH, casadi::OP_ATANH, casadi::OP_CONSTPOW, casadi::OP_COS, casadi::OP_COSH, casadi::OP_DIV, casadi::OP_EQ, casadi::OP_FABS, casadi::OP_IF_ELSE_ZERO, casadi::OP_INV, casadi::OP_LE, casadi::OP_LT, casadi::OP_MUL, casadi::OP_NE, casadi::OP_NEG, casadi::OP_NOT, casadi::OP_POW, casadi::OP_SIN, casadi::OP_SINH, casadi::OP_SQ, casadi::OP_SQRT, casadi::OP_SUB, casadi::OP_TANH, casadi::GenericExpression< SXElem >::pow, casadi::GlobalOptions::simplification_on_the_fly, casadi::GenericExpression< SXElem >::sq, casadi::GenericExpression< SXElem >::sqrt, casadi::SXNode::to_double(), and casadi::SXNode::to_int().
{
     // Simplifications
     if (GlobalOptions::simplification_on_the_fly) {
       switch (op) {
       case OP_ADD:
         if (x.is_zero())
           return y;
         else if (y->is_zero()) // term2 is zero
           return x;
         else if (y.is_op(OP_NEG))  // x + (-y) -> x - y
           return x - (-y);
         else if (x.is_op(OP_NEG)) // (-x) + y -> y - x
           return y - x.dep();
         else if (x.is_op(OP_MUL) && y.is_op(OP_MUL) &&
                  x.dep(0).is_constant() && static_cast<double>(x.dep(0))==0.5 &&
                  y.dep(0).is_constant() && static_cast<double>(y.dep(0))==0.5 &&
                  is_equal(y.dep(1), x.dep(1), SXNode::eq_depth_)) // 0.5x+0.5x = x
           return x.dep(1);
         else if (x.is_op(OP_DIV) && y.is_op(OP_DIV) &&
                  x.dep(1).is_constant() && static_cast<double>(x.dep(1))==2 &&
                  y.dep(1).is_constant() && static_cast<double>(y.dep(1))==2 &&
                  is_equal(y.dep(0), x.dep(0), SXNode::eq_depth_)) // x/2+x/2 = x
           return x.dep(0);
         else if (x.is_op(OP_SUB) && is_equal(x.dep(1), y, SXNode::eq_depth_))
           return x.dep(0);
         else if (y.is_op(OP_SUB) && is_equal(x, y.dep(1), SXNode::eq_depth_))
           return y.dep(0);
         else if (x.is_op(OP_SQ) && y.is_op(OP_SQ) &&
                  ((x.dep().is_op(OP_SIN) && y.dep().is_op(OP_COS))
                   || (x.dep().is_op(OP_COS) && y.dep().is_op(OP_SIN)))
                  && is_equal(x.dep().dep(), y.dep().dep(), SXNode::eq_depth_))
           return 1; // sin^2 + cos^2 -> 1
         break;
       case OP_SUB:
         if (y->is_zero()) // term2 is zero
           return x;
         if (x.is_zero()) // term1 is zero
           return -y;
         if (is_equal(x, y, SXNode::eq_depth_)) // the terms are equal
           return 0;
         else if (y.is_op(OP_NEG)) // x - (-y) -> x + y
           return x + y.dep();
         else if (x.is_op(OP_ADD) && is_equal(x.dep(1), y, SXNode::eq_depth_))
           return x.dep(0);
         else if (x.is_op(OP_ADD) && is_equal(x.dep(0), y, SXNode::eq_depth_))
           return x.dep(1);
         else if (y.is_op(OP_ADD) && is_equal(x, y.dep(1), SXNode::eq_depth_))
           return -y.dep(0);
         else if (y.is_op(OP_ADD) && is_equal(x, y.dep(0), SXNode::eq_depth_))
           return -y.dep(1);
         else if (x.is_op(OP_NEG))
           return -(x.dep() + y);
         break;
       case OP_MUL:
         if (is_equal(y, x, SXNode::eq_depth_))
           return sq(x);
         else if (!x.is_constant() && y.is_constant())
           return y * x;
         else if (x.is_zero() || y->is_zero()) // one of the terms is zero
           return 0;
         else if (x.is_one()) // term1 is one
           return y;
         else if (y->is_one()) // term2 is one
           return x;
         else if (y->is_minus_one())
           return -x;
         else if (x.is_minus_one())
           return -y;
         else if (y.is_op(OP_INV))
           return x/y.inv();
         else if (x.is_op(OP_INV))
           return y / x.inv();
         else if (x.is_constant() && y.is_op(OP_MUL) && y.dep(0).is_constant() &&
                  static_cast<double>(x)*static_cast<double>(y.dep(0))==1) // 5*(0.2*x) = x
           return y.dep(1);
         else if (x.is_constant() && y.is_op(OP_DIV) && y.dep(1).is_constant() &&
                  static_cast<double>(x)==static_cast<double>(y.dep(1))) // 5*(x/5) = x
           return y.dep(0);
         else if (x.is_op(OP_DIV) && is_equal(x.dep(1), y, SXNode::eq_depth_)) // ((2/x)*x)
           return x.dep(0);
         else if (y.is_op(OP_DIV) &&
                  is_equal(y.dep(1), x, SXNode::eq_depth_)) // ((2/x)*x)
           return y.dep(0);
         else if (x.is_op(OP_NEG))
           return -(x.dep() * y);
         else if (y.is_op(OP_NEG))
           return -(x * y.dep());
         break;
       case OP_DIV:
         if (y->is_zero()) // term2 is zero
           return casadi_limits<SXElem>::nan;
         else if (x.is_zero()) // term1 is zero
           return 0;
         else if (y->is_one()) // term2 is one
           return x;
         else if (y->is_minus_one())
           return -x;
         else if (is_equal(x, y, SXNode::eq_depth_)) // terms are equal
           return 1;
         else if (x.is_doubled() && is_equal(y, 2))
           return x.dep(0);
         else if (x.is_op(OP_MUL) && is_equal(y, x.dep(0), SXNode::eq_depth_))
           return x.dep(1);
         else if (x.is_op(OP_MUL) && is_equal(y, x.dep(1), SXNode::eq_depth_))
           return x.dep(0);
         else if (x.is_one())
           return y.inv();
         else if (y.is_op(OP_INV))
           return x*y.inv();
         else if (x.is_doubled() && y.is_doubled())
           return x.dep(0) / y->dep(0);
         else if (y.is_constant() && x.is_op(OP_DIV) && x.dep(1).is_constant() &&
                  static_cast<double>(y)*static_cast<double>(x.dep(1))==1) // (x/5)/0.2
           return x.dep(0);
         else if (y.is_op(OP_MUL) &&
                  is_equal(y.dep(1), x, SXNode::eq_depth_)) // x/(2*x) = 1/2
           return BinarySX::create(OP_DIV, 1, y.dep(0));
         else if (x.is_op(OP_NEG) &&
                  is_equal(x.dep(0), y, SXNode::eq_depth_))      // (-x)/x = -1
           return -1;
         else if (y.is_op(OP_NEG) &&
                  is_equal(y.dep(0), x, SXNode::eq_depth_))      // x/(-x) = 1
           return -1;
         else if (y.is_op(OP_NEG) && x.is_op(OP_NEG) &&
                  is_equal(x.dep(0), y.dep(0), SXNode::eq_depth_))  // (-x)/(-x) = 1
           return 1;
         else if (x.is_op(OP_DIV) && is_equal(y, x.dep(0), SXNode::eq_depth_))
           return x.dep(1).inv();
         else if (x.is_op(OP_NEG))
           return -(x.dep() / y);
         else if (y.is_op(OP_NEG))
           return -(x / y.dep());
         break;
       case OP_POW:
         if (y->is_constant()) {
           if (y->is_integer()) {
             int nn = y->to_int();
             if (nn == 0) {
               return 1;
             } else if (nn>100 || nn<-100) { // maximum depth
               return binary(OP_CONSTPOW, x, nn);
             } else if (nn<0) { // negative power
               return 1/pow(x, -nn);
             } else if (nn%2 == 1) { // odd power
               return x*pow(x, nn-1);
             } else { // even power
               SXElem rt = pow(x, nn/2);
               return rt*rt;
             }
           } else if (y->to_double()==0.5) {
             return sqrt(x);
           } else {
             return binary(OP_CONSTPOW, x, y);
           }
         }
         break;
         case OP_LE:
         if ((y-x).isNonNegative())
           return 1;
         break;
       case OP_LT:
         if (((x)-y).isNonNegative())
           return 0;
         break;
       case OP_EQ:
         if (is_equal(x, y))
           return 1;
         break;
       case OP_NE:
         if (is_equal(x, y))
           return 0;
         break;
       case OP_SINH:
       case OP_TANH:
       case OP_ATANH:
       case OP_ACOSH:
       case OP_ASINH:
         if (x.is_zero())
           return 0;
         break;
       case OP_COSH:
         if (x.is_zero())
           return 1;
         break;
       case OP_SQRT:
         if (x.is_op(OP_SQ))
           return fabs(x.dep());
         break;
       case OP_SQ:
         if (x.is_op(OP_SQRT))
           return x.dep();
         else if (x.is_op(OP_NEG))
           return sq(x.dep());
         break;
       case OP_FABS:
         if (x.is_op(OP_FABS) || x.is_op(OP_SQ))
           return x;
         break;
       case OP_NOT:
         if (x.is_op(OP_NOT))
           return x.dep();
         break;
       case OP_IF_ELSE_ZERO:
         if (y->is_zero()) {
           return y;
         } else if (x.is_constant()) {
           if (static_cast<double>(x)!=0) {
             return y;
           } else {
             return 0;
           }
         }
       }
     }
     return BinarySX::create(Operation(op), x, y);
   }
SXElem casadi::SXElem::create (SXNode * node) static
Create an object given a node
Definition at line 54 of file sx_elem.cpp.
References SXElem().
Referenced by casadi::UnarySX::create(), casadi::BinarySX::create(), casadi::SXFunction::init(), and sym().
{
     return SXElem(node, false);
   }
SXElem casadi::SXElem::dep (int ch = 0) const
Definition at line 502 of file sx_elem.cpp.
References casadi::SXNode::dep().
Referenced by binary(), inv(), is_doubled(), and operator-().
{
     casadi_assert(ch==0 || ch==1;)
       return node->dep(ch);
   }
SXNode * casadi::SXElem::get () const
Definition at line 170 of file sx_elem.cpp.
Referenced by casadi::SXFunction::init(), and is_equal().
{
     return node;
   }
std::string casadi::PrintableObject< SXElem >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< SXElem >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
int casadi::SXElem::getTemp () const
Get the temporary variable
Definition at line 572 of file sx_elem.cpp.
{
     return (*this)->temp;
   }
bool casadi::SXElem::hasDep () const
Definition at line 430 of file sx_elem.cpp.
References casadi::SXNode::hasDep().
Referenced by is_commutative(), is_op(), and n_dep().
{
     return node->hasDep();
   }
SXElem casadi::SXElem::inv () const
Definition at line 162 of file sx_elem.cpp.
References casadi::UnarySX::create(), dep(), is_op(), and casadi::OP_INV.
Referenced by binary().
{
     if (is_op(OP_INV)) {
       return dep(0);
     } else {
       return UnarySX::create(OP_INV, *this);
     }
   }
bool casadi::SXElem::is_commutative () const
Definition at line 413 of file sx_elem.cpp.
References hasDep(), and op().
{
     if (!hasDep()) throw CasadiException("SX::is_commutative: must be binary");
     return operation_checker<CommChecker>(op());
   }
bool casadi::SXElem::is_constant () const
Definition at line 418 of file sx_elem.cpp.
References casadi::SXNode::is_constant().
Referenced by __nonzero__(), binary(), casadi::UnarySX::create(), casadi::BinarySX::create(), casadi::casadi_limits< SXElem >::is_constant(), is_leaf(), is_regular(), and isNonNegative().
{
     return node->is_constant();
   }
bool casadi::SXElem::is_doubled () const
Definition at line 158 of file sx_elem.cpp.
References dep(), casadi::SXNode::eq_depth_, is_equal(), is_op(), and casadi::OP_ADD.
Referenced by binary().
{
     return is_op(OP_ADD) && is_equal(dep(0), dep(1), SXNode::eq_depth_);
   }
bool casadi::SXElem::is_equal (const SXElem & x, const SXElem & y, int depth = 0) static
Definition at line 474 of file sx_elem.cpp.
References get(), and casadi::SXNode::is_equal().
Referenced by assignIfDuplicate(), binary(), is_doubled(), casadi::UnarySX::is_equal(), casadi::BinarySX::is_equal(), and casadi::casadi_limits< SXElem >::is_equal().
{
     SXNode *x_node = x.get(), *y_node = y.get();
     if (x_node==y_node) {
       return true;
     } else if (depth>0) {
       return x_node->is_equal(y_node, depth);
     } else {
       return false;
     }
   }
bool casadi::SXElem::is_integer () const
Definition at line 422 of file sx_elem.cpp.
References casadi::SXNode::is_integer().
Referenced by casadi::casadi_limits< SXElem >::is_integer().
{
     return node->is_integer();
   }
bool casadi::SXElem::is_leaf () const
An SXElem qualifies as leaf when it has no dependencies.
Definition at line 408 of file sx_elem.cpp.
References is_constant(), and is_symbolic().
{
     if (!node) return true;
     return is_constant() || is_symbolic();
   }
bool casadi::SXElem::is_minus_one () const
Definition at line 446 of file sx_elem.cpp.
References casadi::SXNode::is_minus_one().
Referenced by binary(), casadi::casadi_limits< SXElem >::is_minus_one(), and operator-().
{
     return node->is_minus_one();
   }
bool casadi::SXElem::is_null () inline
Definition at line 213 of file sx_elem.hpp.
 {return false;}
bool casadi::SXElem::is_one () const
Definition at line 442 of file sx_elem.cpp.
References casadi::SXNode::is_one().
Referenced by binary(), casadi::casadi_limits< SXElem >::is_one(), and operator-().
{
     return node->is_one();
   }
bool casadi::SXElem::is_op (int op) const
Definition at line 470 of file sx_elem.cpp.
References hasDep(), and op().
Referenced by binary(), inv(), is_doubled(), isNonNegative(), and operator-().
{
     return hasDep() && op==this->op();
   }
bool casadi::SXElem::is_regular () const
Definition at line 588 of file sx_elem.cpp.
References is_constant(), isInf(), isMinusInf(), and isNan().
{
     if (is_constant()) {
       return !(isNan() || isInf() || isMinusInf());
     } else {
       casadi_error("Cannot check regularity for symbolic SXElem");
     }
   }
bool casadi::SXElem::is_symbolic () const
Definition at line 426 of file sx_elem.cpp.
References casadi::SXNode::is_symbolic().
Referenced by is_leaf().
{
     return node->is_symbolic();
   }
bool casadi::SXElem::is_zero () const
Definition at line 434 of file sx_elem.cpp.
References casadi::SXNode::is_zero().
Referenced by __nonzero__(), binary(), casadi::casadi_limits< SXElem >::is_zero(), and operator-().
{
     return node->is_zero();
   }
bool casadi::SXElem::isAlmostZero (double tol) const
Definition at line 438 of file sx_elem.cpp.
References casadi::SXNode::isAlmostZero().
Referenced by casadi::casadi_limits< SXElem >::isAlmostZero().
{
     return node->isAlmostZero(tol);
   }
bool casadi::SXElem::isInf () const
Definition at line 454 of file sx_elem.cpp.
References casadi::SXNode::isInf().
Referenced by is_regular(), and casadi::casadi_limits< SXElem >::isInf().
{
     return node->isInf();
   }
bool casadi::SXElem::isMinusInf () const
Definition at line 458 of file sx_elem.cpp.
References casadi::SXNode::isMinusInf().
Referenced by is_regular(), and casadi::casadi_limits< SXElem >::isMinusInf().
{
     return node->isMinusInf();
   }
bool casadi::SXElem::isNan () const
Definition at line 450 of file sx_elem.cpp.
References casadi::SXNode::isNan().
Referenced by is_regular(), and casadi::casadi_limits< SXElem >::isNaN().
{
     return node->isNan();
   }
bool casadi::SXElem::isNonNegative () const
Definition at line 485 of file sx_elem.cpp.
References is_constant(), is_op(), casadi::OP_FABS, and casadi::OP_SQ.
Referenced by binary().
{
     if (is_constant())
       return static_cast<double>(*this)>=0;
     else if (is_op(OP_SQ) || is_op(OP_FABS))
       return true;
     else
       return false;
   }
void casadi::SXElem::mark ()
Definition at line 584 of file sx_elem.cpp.
                     {
     (*this)->mark();
   }
bool casadi::SXElem::marked () const
Definition at line 580 of file sx_elem.cpp.
{
     return (*this)->marked();
   }
int casadi::SXElem::n_dep () const
Definition at line 507 of file sx_elem.cpp.
References hasDep(), casadi::casadi_math< T >::ndeps(), and op().
{
     if (!hasDep()) return 0;
     return casadi_math<double>::ndeps(op());
   }
const std::string & casadi::SXElem::name () const
Definition at line 462 of file sx_elem.cpp.
References casadi::SXNode::name().
{
     return node->name();
   }
int casadi::SXElem::op () const
Definition at line 466 of file sx_elem.cpp.
References casadi::SXNode::op().
Referenced by is_commutative(), is_op(), and n_dep().
{
     return node->op();
   }
casadi::SXElem::operator double () const explicit
Definition at line 494 of file sx_elem.cpp.
{
     return node->to_double();
   }
casadi::SXElem::operator int () const explicit
Definition at line 498 of file sx_elem.cpp.
{
     return node->to_int();
   }
casadi::SXElem::operator Matrix< SXElem > () const
SXElem casadi::GenericExpression< SXElem >::operator! () const inline inherited
Definition at line 325 of file generic_expression.hpp.
{
       return ExType::unary(OP_NOT, self());
     }
SXElem & casadi::GenericExpression< SXElem >::operator*= (const SXElem & y) inline inherited
Definition at line 316 of file generic_expression.hpp.
 {return self() = self() * y;}
SXElem & casadi::GenericExpression< SXElem >::operator+= (const SXElem & y) inline inherited
Definition at line 310 of file generic_expression.hpp.
 { return self() = self() + y; }
SXElem casadi::SXElem::operator- () const
Definition at line 140 of file sx_elem.cpp.
References casadi::UnarySX::create(), dep(), is_minus_one(), is_one(), is_op(), is_zero(), and casadi::OP_NEG.
{
     if (is_op(OP_NEG))
       return dep();
     else if (is_zero())
       return 0;
     else if (is_minus_one())
       return 1;
     else if (is_one())
       return -1;
     else
       return UnarySX::create(OP_NEG, *this);
   }
SXElem & casadi::GenericExpression< SXElem >::operator-= (const SXElem & y) inline inherited
Definition at line 313 of file generic_expression.hpp.
 { return self() = self() - y; }
const SXNode * casadi::SXElem::operator-> () const
Definition at line 174 of file sx_elem.cpp.
{
     return node;
   }
SXNode * casadi::SXElem::operator-> ()
Definition at line 178 of file sx_elem.cpp.
{
     return node;
   }
SXElem & casadi::GenericExpression< SXElem >::operator/= (const SXElem & y) inline inherited
Definition at line 319 of file generic_expression.hpp.
 {return self() = self() / y;}
SXElem & casadi::SXElem::operator= (const SXElem & scalar)
Definition at line 89 of file sx_elem.cpp.
References casadi::SXNode::count.
{
     // quick return if the old and new pointers point to the same object
     if (node == scalar.node) return *this;
     // decrease the counter and delete if this was the last pointer
     if (--node->count == 0) delete node;
     // save the new pointer
     node = scalar.node;
     node->count++;
     return *this;
   }
SXElem & casadi::SXElem::operator= (double scalar)
Definition at line 127 of file sx_elem.cpp.
References SXElem().
{
     return *this = SXElem(scalar);
   }
void casadi::SXElem::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 135 of file sx_elem.cpp.
References casadi::SXNode::print().
Referenced by repr().
{
     node->print(stream);
     if (trailing_newline) stream << std::endl;
   }
void casadi::SXElem::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 131 of file sx_elem.cpp.
References print().
{
     print(stream, trailing_newline);
   }
const SXElem & casadi::GenericExpression< SXElem >::self () const inline protected inherited
Definition at line 51 of file generic_expression.hpp.
 { return static_cast<const ExType&>(*this); }
SXElem & casadi::GenericExpression< SXElem >::self () inline protected inherited
Definition at line 52 of file generic_expression.hpp.
 { return static_cast<ExType&>(*this); }
void casadi::SXElem::setTemp (int t)
Definition at line 576 of file sx_elem.cpp.
{
     (*this)->temp = t;
   }
SXElem casadi::SXElem::sym (const std::string & name) static
Parameters
name Name of the symbolic primitive
This is the name that will be used by the "operator<<" and "to_string" methods. The name is not used as identifier; you may construct distinct SXElem objects with non-unique names.
Definition at line 81 of file sx_elem.cpp.
References create().
{
     return create(new SymbolicSX(name));
   }
SXElem casadi::SXElem::unary (int op, const SXElem & x) static
Definition at line 404 of file sx_elem.cpp.
References casadi::UnarySX::create().
{
     return UnarySX::create(Operation(op), x);
   }
Friends And Related Function Documentation
friend class BinarySXNode friend
Definition at line 61 of file sx_elem.hpp.
friend class Matrix< SXElem > friend
Definition at line 62 of file sx_elem.hpp.
friend class SXNode friend
Definition at line 60 of file sx_elem.hpp.
The documentation for this class was generated from the following files:
sx_elem.hpp
sx_elem.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge