CasADi: casadi::ParsedFile Class Reference
casadi::ParsedFile Class Reference
A parsed file.
#include <casadi_file.hpp>
Detailed Description
Author
Joel Andersson
Date
2016
Definition at line 45 of file casadi_file.hpp.
Public Member Functions
ParsedFile ()
Default constructor (no commands)
ParsedFile (const std::string &fname)
Construct from a file.
ParsedFile (const std::vector< std::string > &lines, int offset=0)
Construct from a file.
void parse (const std::string &fname)
Parse a file.
void parse (const std::vector< std::string > &lines, int offset)
Parse a list of strings.
void print (std::ostream &stream=casadi::userOut()) const
Print parsed file.
bool has (const std::string &cmd, int ind=-1) const
Does an entry exist?
std::string to_text (const std::string &cmd, int ind=-1) const
Get entry as a text.
template<typename T >
T to (const std::string &cmd, int ind=-1) const
Convert to a type.
std::string to_string (const std::string &cmd, int ind=-1) const
Get entry as a string.
template<typename T >
std::vector< T > to_vector (const std::string &cmd, int ind=-1) const
Get entry as a vector.
template<typename T >
std::set< T > to_set (const std::string &cmd, int ind=-1) const
Get entry as a set.
int to_int (const std::string &cmd, int ind=-1) const
Get entry as an integer.
Static Public Member Functions
static std::string indexed (const std::string &cmd, int ind)
Public Attributes
std::map< std::string,
std::pair< int, std::string > > commands
Map of commands.
Constructor & Destructor Documentation
casadi::ParsedFile::ParsedFile () inline
Definition at line 48 of file casadi_file.hpp.
 {}
casadi::ParsedFile::ParsedFile (const std::string & fname) explicit
Definition at line 33 of file casadi_file.cpp.
{
     parse(fname);
   }
casadi::ParsedFile::ParsedFile (const std::vector< std::string > & lines, int offset = 0) explicit
Definition at line 37 of file casadi_file.cpp.
{
     parse(lines, offset);
   }
Member Function Documentation
bool casadi::ParsedFile::has (const std::string & cmd, int ind = -1) const
Definition at line 123 of file casadi_file.cpp.
Referenced by casadi::External::get_n_in(), casadi::External::get_n_out(), casadi::External::get_name_in(), casadi::External::get_name_out(), casadi::GenericExternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_out(), casadi::External::init(), casadi::GenericExternal::init(), casadi::jit(), and casadi::JitLibrary::JitLibrary().
{
     if (ind>=0) return has(indexed(cmd, ind));
     return commands.find(cmd) != commands.end();
   }
static std::string casadi::ParsedFile::indexed (const std::string & cmd, int ind) inline static
Convert indexed command
Definition at line 72 of file casadi_file.hpp.
{
       std::stringstream ss;
       ss << cmd << "[" << ind << "]";
       return ss.str();
     }
void casadi::ParsedFile::parse (const std::string & fname)
Definition at line 41 of file casadi_file.cpp.
{
     // Lines to be extracted
     std::vector<std::string> lines;
     // Open file and read line-by-line
     ifstream file(fname);
     casadi_assert_message(file.good(), "File \"" + fname + "\" cannot be opened.");
     string line;
     while (true) {
       // Read line
       getline(file, line);
       if (file.eof()) break;
       casadi_assert(file.good());
       // Save to class
       lines.push_back(line);
     }
     // Parse the extracted lines
     parse(lines, 0);
   }
void casadi::ParsedFile::parse (const std::vector< std::string > & lines, int offset)
Definition at line 63 of file casadi_file.cpp.
{
     // Loop over the lines
     auto line_it = lines.cbegin();
     while (line_it!=lines.cend()) {
       // If comment or empty line, skip
       if (line_it->empty() || line_it->at(0)=='#') {
         line_it++;
         continue;
       }
       // Current line number
       int line_no = line_it - lines.cbegin() + 1 + offset;
       // Get command string
       casadi_assert_message(line_it->at(0)==':',
                             "Syntax error: " + *line_it + " is not a command string");
       string cmd = line_it->substr(1, line_it->find(' ')-1);
       // New entry
       stringstream ss;
       // Collect the meta data
       size_t start = cmd.size()+2;
       while (true) {
         // Find the backslash, if any
         size_t stop = line_it->find('\\');
         // Add to entry
         ss << line_it->substr(start, stop-start);
         // Break if no more lines or not multiline
         if (++line_it==lines.cend() || stop == string::npos) break;
         // Multiline entry
         if (start!=stop) ss << std::endl;
         // No offset for subsequent lines
         start = 0;
       }
       // Insert new element in map
       auto new_el = commands.insert(make_pair(cmd, make_pair(line_no, ss.str())));
       casadi_assert_message(new_el.second, "Duplicate entry: \"" + cmd + "\"");
     }
   }
void casadi::ParsedFile::print (std::ostream & stream = casadi::userOut()) const
Definition at line 109 of file casadi_file.cpp.
{
     // Print all the commands
     for (auto&& c : commands) {
       stream << c.first << " (line " << c.second.first << "):" << endl;
       stream << c.second.second;
     }
   }
template<typename T > T casadi::ParsedFile::to (const std::string & cmd, int ind = -1) const inline
Definition at line 80 of file casadi_file.hpp.
{
       std::istringstream ss(to_text(cmd, ind));
       T ret;
       ss >> ret;
       return ret;
     }
int casadi::ParsedFile::to_int (const std::string & cmd, int ind = -1) const inline
Definition at line 111 of file casadi_file.hpp.
Referenced by casadi::External::get_n_in(), casadi::External::get_n_out(), casadi::GenericExternal::init(), and casadi::jit().
 { return to<int>(cmd, ind);}
template<typename T > std::set<T> casadi::ParsedFile::to_set (const std::string & cmd, int ind = -1) const inline
Definition at line 104 of file casadi_file.hpp.
Referenced by casadi::JitLibrary::JitLibrary().
{
       std::set<T> ret;
       for (auto&& e : to_vector<T>(cmd, ind)) ret.insert(e);
       return ret;
     }
std::string casadi::ParsedFile::to_string (const std::string & cmd, int ind = -1) const inline
Definition at line 88 of file casadi_file.hpp.
Referenced by casadi::Function::Function(), casadi::External::get_name_in(), casadi::External::get_name_out(), and casadi::jit().
{
       return to<std::string>(cmd, ind);
     }
std::string casadi::ParsedFile::to_text (const std::string & cmd, int ind = -1) const
Definition at line 117 of file casadi_file.cpp.
Referenced by casadi::jit().
{
     if (ind>=0) return to_text(indexed(cmd, ind));
     casadi_assert_message(has(cmd), "No such command: " + cmd);
     return commands.at(cmd).second;
   }
template<typename T > std::vector<T> casadi::ParsedFile::to_vector (const std::string & cmd, int ind = -1) const inline
Definition at line 94 of file casadi_file.hpp.
Referenced by casadi::GenericExternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_out(), and casadi::External::init().
{
       std::istringstream ss(to_text(cmd, ind));
       T tmp;
       std::vector<T> ret;
       while (ss >> tmp) ret.push_back(tmp);
       return ret;
     }
Member Data Documentation
std::map<std::string, std::pair<int, std::string> > casadi::ParsedFile::commands
Definition at line 114 of file casadi_file.hpp.
The documentation for this class was generated from the following files:
casadi_file.hpp
casadi_file.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge