CasADi: casadi::Slice Class Reference
casadi::Slice Class Reference
Class representing a Slice.
#include <slice.hpp>
Detailed Description
Note that Python or Octave do not need to use this class. They can just use slicing utility from the host language (M[0:6] in Python, M(1:7))
Definition at line 42 of file slice.hpp.
Public Member Functions
Slice ()
Default constructor - all elements.
Slice (int i, bool ind1=false)
A single element (explicit to avoid ambiguity with IM overload.
Slice (int start, int stop, int step=1)
A slice.
std::vector< int > all (int len, bool ind1=false) const
Get a vector of indices.
std::vector< int > all (const Slice &outer, int len) const
Get a vector of indices (nested slice)
bool is_scalar (int len) const
Is the slice a scalar.
int scalar (int len) const
Get scalar (if is_scalar)
bool operator== (const Slice &other) const
Check equality.
bool operator!= (const Slice &other) const
Check inequality.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
Public Attributes
int start
start value: negative values will get added to length
int stop
stop value: use std::numeric_limits<int>::max() to indicate unboundedness
int step
Constructor & Destructor Documentation
casadi::Slice::Slice ()
Definition at line 32 of file slice.cpp.
                : start(0), stop(std::numeric_limits<int>::max()), step(1) {
   }
casadi::Slice::Slice (int i, bool ind1 = false) explicit
Definition at line 35 of file slice.cpp.
References stop.
                                : start(i-ind1), stop(i-ind1+1), step(1) {
     casadi_assert_message(!(ind1 && i<=0),
                           "Matlab is 1-based, but requested index " <<
                           i <<  ". Note that negative slices are" <<
                           " disabled in the Matlab interface. " <<
                           "Possibly you may want to use 'end'.");
     if (i==-1) stop = std::numeric_limits<int>::max();
   }
casadi::Slice::Slice (int start, int stop, int step = 1)
Definition at line 44 of file slice.cpp.
                                             : start(start), stop(stop), step(step) {
   }
Member Function Documentation
std::vector< int > casadi::Slice::all (int len, bool ind1 = false) const
Definition at line 47 of file slice.cpp.
References casadi::range(), start, step, and stop.
Referenced by casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::Matrix< Scalar >::get_nz(), casadi::MX::get_nz(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), and casadi::MX::set_nz().
{
     int start = this->start;
     if (start==std::numeric_limits<int>::min()) {
       start = (step < 0) ? len - 1 : 0;
     } else if (start<0) {
       start+=len;
     }
     int stop = this->stop;
     if (stop==std::numeric_limits<int>::max()) {
       stop = (step < 0) ? -1 : len;
     } else if (stop<0) {
       stop+=len;
     }
     casadi_assert_message(stop<=len,
                           "Slice (start=" << start << ", stop=" << stop << ", step=" << step
                           << ") out of bounds with supplied length of " << len);
     casadi_assert_message(start>=0,
                           "Slice (start=" << start << ", stop=" << stop << ", step=" << step
                           << ") out of bounds with start<0.");
     if ((stop>=start && step<0) || (stop<=start && step>0)) return std::vector<int>();
     return range(start+ind1, stop+ind1, step, len+ind1);
   }
std::vector< int > casadi::Slice::all (const Slice & outer, int len) const
Definition at line 91 of file slice.cpp.
References start, step, and stop.
{
     std::vector<int> ret;
     for (int i=outer.start; i!=outer.stop; i+=outer.step) {
       for (int j=i+start; j!=i+stop; j+=step) {
         ret.push_back(j);
       }
     }
     return ret;
   }
std::string casadi::PrintableObject< Slice >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< Slice >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
bool casadi::Slice::is_scalar (int len) const
Definition at line 101 of file slice.cpp.
References start, step, and stop.
Referenced by casadi::Matrix< Scalar >::get(), casadi::Matrix< Scalar >::get_nz(), scalar(), casadi::Matrix< Scalar >::set(), and casadi::Matrix< Scalar >::set_nz().
{
     int start = std::min(this->start, len);
     int stop = std::min(this->stop, len);
     int nret = (stop-start)/step + ((stop-start)%step!=0);
     return nret==1;
   }
bool casadi::Slice::operator!= (const Slice & other) const inline
Definition at line 77 of file slice.hpp.
 { return !(*this == other);}
bool casadi::Slice::operator== (const Slice & other) const inline
Definition at line 72 of file slice.hpp.
References start, step, and stop.
{
       return start==other.start && stop==other.stop && step==other.step;
     }
void casadi::Slice::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 76 of file slice.cpp.
References start, step, and stop.
Referenced by repr().
{
     bool from_beginning = start == 0;
     bool till_end = stop == std::numeric_limits<int>::max();
     bool skip_none = step==1;
     if (stop==start+1) {
       stream << start;
     } else {
       if (!from_beginning) stream << start;
       stream << ":";
       if (!till_end) stream << stop;
       if (!skip_none) stream << ":" << step;
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::Slice::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 72 of file slice.cpp.
References print().
{
     print(stream, trailing_newline);
   }
int casadi::Slice::scalar (int len) const
Definition at line 108 of file slice.cpp.
References is_scalar(), and start.
Referenced by casadi::Matrix< Scalar >::get(), casadi::Matrix< Scalar >::get_nz(), casadi::Matrix< Scalar >::set(), and casadi::Matrix< Scalar >::set_nz().
{
     casadi_assert(is_scalar(len));
     casadi_assert_message(start >= -len && start < len, "Slice::getScalar: out of bounds");
     return start >= 0 ? start : start+len;
   }
Member Data Documentation
int casadi::Slice::start
Definition at line 45 of file slice.hpp.
Referenced by all(), is_scalar(), operator==(), print(), scalar(), casadi::to_slice(), and casadi::to_slice2().
int casadi::Slice::step
Definition at line 48 of file slice.hpp.
Referenced by all(), is_scalar(), operator==(), print(), casadi::to_slice(), and casadi::to_slice2().
int casadi::Slice::stop
Definition at line 47 of file slice.hpp.
Referenced by all(), is_scalar(), operator==(), print(), Slice(), casadi::to_slice(), and casadi::to_slice2().
The documentation for this class was generated from the following files:
slice.hpp
slice.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge