CasADi: Integrator
Integrator
Functions
CASADI_EXPORT Function casadi::integrator (const std::string &name, const std::string &solver, const SXDict &dae, const Dict &opts=Dict())
CASADI_EXPORT Function casadi::integrator (const std::string &name, const std::string &solver, const MXDict &dae, const Dict &opts=Dict())
CASADI_EXPORT Function casadi::integrator (const std::string &name, const std::string &solver, const Function &dae, const Dict &opts=Dict())
CASADI_EXPORT Function casadi::integrator (const std::string &name, const std::string &solver, const std::pair< Function, Function > &dae, const Dict &opts=Dict())
CASADI_EXPORT Function casadi::integrator (const std::string &name, const std::string &solver, Oracle *dae, const Dict &opts=Dict())
CASADI_EXPORT bool casadi::has_integrator (const std::string &name)
Check if a particular plugin is available.
CASADI_EXPORT void casadi::load_integrator (const std::string &name)
Explicitly load a plugin dynamically.
CASADI_EXPORT std::string casadi::doc_integrator (const std::string &name)
Get the documentation string for a plugin.
vector< string > casadi::integrator_in ()
Get input scheme of integrators.
vector< string > casadi::integrator_out ()
Get integrator output scheme of integrators.
string casadi::integrator_in (int ind)
Get integrator input scheme name by index.
string casadi::integrator_out (int ind)
Get output scheme name by index.
int casadi::integrator_n_in ()
Get the number of integrator inputs.
int casadi::integrator_n_out ()
Get the number of integrator outputs.
Detailed Description
Create an ODE/DAE integrator Solves an initial value problem (IVP) coupled to a terminal value problem with differential equation given as an implicit ODE coupled to an algebraic equation and a set of quadratures:
Initial conditions at t=t0
x(t0)  = x0
q(t0)  = 0
Forward integration from t=t0 to t=tf
der(x) = function(x, z, p, t)                  Forward ODE
0 = fz(x, z, p, t)                  Forward algebraic equations
der(q) = fq(x, z, p, t)                  Forward quadratures
Terminal conditions at t=tf
rx(tf)  = rx0
rq(tf)  = 0
Backward integration from t=tf to t=t0
der(rx) = gx(rx, rz, rp, x, z, p, t)        Backward ODE
0 = gz(rx, rz, rp, x, z, p, t)        Backward algebraic equations
der(rq) = gq(rx, rz, rp, x, z, p, t)        Backward quadratures
where we assume that both the forward and backwards integrations are index-1
(i.e. dfz/dz, dgz/drz are invertible) and furthermore that
gx, gz and gq have a linear dependency on rx, rz and rp.
General information
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". casadi::FunctionInternal
augmented_options OT_DICT Options to be passed down to the augmented integrator, if one is constructed. casadi::Integrator
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
expand OT_BOOL Replace MX with SX expressions in problem formulation [false] casadi::Integrator
gather_stats OT_BOOL Flag to indicate whether statistics must be gathered casadi::FunctionInternal
grid OT_DOUBLEVECTOR Time grid casadi::Integrator
input_scheme OT_STRINGVECTOR Custom input scheme casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
monitor OT_STRINGVECTOR Monitors to be activated casadi::FunctionInternal
number_of_finite_elements OT_INT Number of finite elements casadi::Integrator
output_scheme OT_STRINGVECTOR Custom output scheme casadi::FunctionInternal
output_t0 OT_BOOL Output the state at the initial time casadi::Integrator
print_stats OT_BOOL Print out statistics after integration casadi::Integrator
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::FunctionInternal
rootfinder OT_STRING An implicit function solver casadi::Integrator
rootfinder_options OT_DICT Options to be passed to the NLP Solver casadi::Integrator
t0 OT_DOUBLE Beginning of the time horizon casadi::Integrator
tf OT_DOUBLE End of the time horizon casadi::Integrator
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::FunctionInternal
Input scheme: casadi::IntegratorInput (INTEGRATOR_NUM_IN = 6) []
Full name Short Description
INTEGRATOR_X0 Differential state at the initial time.
INTEGRATOR_P Parameters.
INTEGRATOR_Z0 Initial guess for the algebraic variable.
INTEGRATOR_RX0 Backward differential state at the final time.
INTEGRATOR_RP Backward parameter vector.
INTEGRATOR_RZ0 Initial guess for the backwards algebraic variable.
Output scheme: casadi::IntegratorOutput (INTEGRATOR_NUM_OUT = 6) []
Full name Short Description
INTEGRATOR_XF Differential state at the final time.
INTEGRATOR_QF Quadrature state at the final time.
INTEGRATOR_ZF Algebraic variable at the final time.
INTEGRATOR_RXF Backward differential state at the initial time.
INTEGRATOR_RQF Backward quadrature state at the initial time.
INTEGRATOR_RZF Backward algebraic variable at the initial time.
List of plugins
- cvodes
- idas
- collocation
- rk
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Integrator.doc("myextraplugin")
cvodes
Interface to CVodes from the Sundials suite.
A call to evaluate will integrate to the end.
You can retrieve the entire state trajectory as follows, after the evaluate call: Call reset. Then call integrate(t_i) and getOuput for a series of times t_i.
Note: depending on the dimension and structure of your problem, you may experience a dramatic speed-up by using a sparse linear solver:
   intg.setOption("linear_solver","csparse")
   intg.setOption("linear_solver_type","user_defined")
List of available options
Id Type Description
abstol OT_DOUBLE Absolute tolerence for the IVP solution
abstolB OT_DOUBLE Absolute tolerence for the adjoint sensitivity solution [default: equal to abstol]
disable_internal_warnings OT_BOOL Disable SUNDIALS internal warning messages
exact_jacobian OT_BOOL Use exact Jacobian information for the forward integration
exact_jacobianB OT_BOOL Use exact Jacobian information for the backward integration [default: equal to exact_jacobian]
finite_difference_fsens OT_BOOL Use finite differences to approximate the forward sensitivity equations (if AD is not available)
fsens_abstol OT_DOUBLE Absolute tolerence for the forward sensitivity solution [default: equal to abstol]
fsens_all_at_once OT_BOOL Calculate all right hand sides of the sensitivity equations at once
fsens_err_con OT_BOOL include the forward sensitivities in all error controls
fsens_reltol OT_DOUBLE Relative tolerence for the forward sensitivity solution [default: equal to reltol]
fsens_scaling_factors OT_DOUBLEVECTOR Scaling factor for the components if finite differences is used
fsens_sensitiviy_parameters OT_INTVECTOR Specifies which components will be used when estimating the sensitivity equations
interpolation_type OT_STRING Type of interpolation for the adjoint sensitivities
iterative_solver OT_STRING Iterative solver: GMRES|bcgstab|tfqmr
iterative_solverB OT_STRING Iterative solver for backward integration
linear_multistep_method OT_STRING Integrator scheme: BDF|adams
linear_solver OT_STRING A custom linear solver creator function
linear_solverB OT_STRING A custom linear solver creator function for backwards integration [default: equal to linear_solver]
linear_solver_options OT_DICT Options to be passed to the linear solver
linear_solver_optionsB OT_DICT Options to be passed to the linear solver for backwards integration [default: equal to linear_solver_options]
linear_solver_type OT_STRING Type of iterative solver: user_defined|DENSE|banded|iterative
linear_solver_typeB OT_STRING Linear solver for backward integration
lower_bandwidth OT_INT Lower band-width of banded Jacobian (estimations)
lower_bandwidthB OT_INT lower band-width of banded jacobians for backward integration [default: equal to lower_bandwidth]
max_krylov OT_INT Maximum Krylov subspace size
max_krylovB OT_INT Maximum krylov subspace size for backward integration
max_multistep_order OT_INT Maximum order for the (variable-order) multistep method
max_num_steps OT_INT Maximum number of integrator steps
nonlinear_solver_iteration OT_STRING Nonlinear solver type: NEWTON|functional
pretype OT_STRING Type of preconditioning: NONE|left|right|both
pretypeB OT_STRING Preconditioner for backward integration
quad_err_con OT_BOOL Should the quadratures affect the step size control
reltol OT_DOUBLE Relative tolerence for the IVP solution
reltolB OT_DOUBLE Relative tolerence for the adjoint sensitivity solution [default: equal to reltol]
sensitivity_method OT_STRING Sensitivity method: SIMULTANEOUS|staggered
steps_per_checkpoint OT_INT Number of steps between two consecutive checkpoints
stop_at_end OT_BOOL Stop the integrator at the end of the interval
upper_bandwidth OT_INT Upper band-width of banded Jacobian (estimations)
upper_bandwidthB OT_INT Upper band-width of banded jacobians for backward integration [default: equal to upper_bandwidth]
use_preconditioner OT_BOOL Precondition an iterative solver
use_preconditionerB OT_BOOL Precondition an iterative solver for the backwards problem [default: equal to use_preconditioner]
idas
Interface to IDAS from the Sundials suite.
Note: depending on the dimension and structure of your problem, you may experience a dramatic speed-up by using a sparse linear solver:
   intg.setOption("linear_solver","csparse")
   intg.setOption("linear_solver_type","user_defined")
List of available options
Id Type Description
abstol OT_DOUBLE Absolute tolerence for the IVP solution
abstolB OT_DOUBLE Absolute tolerence for the adjoint sensitivity solution [default: equal to abstol]
abstolv OT_DOUBLEVECTOR Absolute tolerarance for each component
calc_ic OT_BOOL Use IDACalcIC to get consistent initial conditions.
calc_icB OT_BOOL Use IDACalcIC to get consistent initial conditions for backwards system [default: equal to calc_ic].
cj_scaling OT_BOOL IDAS scaling on cj for the user-defined linear solver module
disable_internal_warnings OT_BOOL Disable SUNDIALS internal warning messages
exact_jacobian OT_BOOL Use exact Jacobian information for the forward integration
exact_jacobianB OT_BOOL Use exact Jacobian information for the backward integration [default: equal to exact_jacobian]
extra_fsens_calc_ic OT_BOOL Call calc ic an extra time, with fsens=0
finite_difference_fsens OT_BOOL Use finite differences to approximate the forward sensitivity equations (if AD is not available)
first_time OT_DOUBLE First requested time as a fraction of the time interval
fsens_abstol OT_DOUBLE Absolute tolerence for the forward sensitivity solution [default: equal to abstol]
fsens_abstolv OT_DOUBLEVECTOR Absolute tolerarance for each component, forward sensitivities
fsens_err_con OT_BOOL include the forward sensitivities in all error controls
fsens_reltol OT_DOUBLE Relative tolerence for the forward sensitivity solution [default: equal to reltol]
fsens_scaling_factors OT_DOUBLEVECTOR Scaling factor for the components if finite differences is used
fsens_sensitiviy_parameters OT_INTVECTOR Specifies which components will be used when estimating the sensitivity equations
init_xdot OT_DOUBLEVECTOR Initial values for the state derivatives
interpolation_type OT_STRING Type of interpolation for the adjoint sensitivities
iterative_solver OT_STRING Iterative solver: GMRES|bcgstab|tfqmr
iterative_solverB OT_STRING Iterative solver for backward integration
linear_solver OT_STRING A custom linear solver creator function
linear_solverB OT_STRING A custom linear solver creator function for backwards integration [default: equal to linear_solver]
linear_solver_options OT_DICT Options to be passed to the linear solver
linear_solver_optionsB OT_DICT Options to be passed to the linear solver for backwards integration [default: equal to linear_solver_options]
linear_solver_type OT_STRING Type of iterative solver: user_defined|DENSE|banded|iterative
linear_solver_typeB OT_STRING Linear solver for backward integration
lower_bandwidth OT_INT Lower band-width of banded Jacobian (estimations)
lower_bandwidthB OT_INT lower band-width of banded jacobians for backward integration [default: equal to lower_bandwidth]
max_krylov OT_INT Maximum Krylov subspace size
max_krylovB OT_INT Maximum krylov subspace size for backward integration
max_multistep_order OT_INT Maximum order for the (variable-order) multistep method
max_num_steps OT_INT Maximum number of integrator steps
max_step_size OT_DOUBLE Maximim step size
pretype OT_STRING Type of preconditioning: NONE|left|right|both
pretypeB OT_STRING Preconditioner for backward integration
quad_err_con OT_BOOL Should the quadratures affect the step size control
reltol OT_DOUBLE Relative tolerence for the IVP solution
reltolB OT_DOUBLE Relative tolerence for the adjoint sensitivity solution [default: equal to reltol]
sensitivity_method OT_STRING Sensitivity method: SIMULTANEOUS|staggered
steps_per_checkpoint OT_INT Number of steps between two consecutive checkpoints
stop_at_end OT_BOOL Stop the integrator at the end of the interval
suppress_algebraic OT_BOOL Suppress algebraic variables in the error testing
upper_bandwidth OT_INT Upper band-width of banded Jacobian (estimations)
upper_bandwidthB OT_INT Upper band-width of banded jacobians for backward integration [default: equal to upper_bandwidth]
use_preconditioner OT_BOOL Precondition an iterative solver
use_preconditionerB OT_BOOL Precondition an iterative solver for the backwards problem [default: equal to use_preconditioner]
collocation
Fixed-step implicit Runge-Kutta integrator ODE/DAE integrator based on collocation schemes
The method is still under development
List of available options
Id Type Description
augmented_options OT_DICT Options to be passed down to the augmented integrator, if one is constructed.
collocation_scheme OT_STRING Collocation scheme: radau|legendre
expand OT_BOOL Replace MX with SX expressions in problem formulation [false]
grid OT_DOUBLEVECTOR Time grid
interpolation_order OT_INT Order of the interpolating polynomials
number_of_finite_elements OT_INT Number of finite elements
output_t0 OT_BOOL Output the state at the initial time
print_stats OT_BOOL Print out statistics after integration
rootfinder OT_STRING An implicit function solver
rootfinder_options OT_DICT Options to be passed to the NLP Solver
t0 OT_DOUBLE Beginning of the time horizon
tf OT_DOUBLE End of the time horizon
rk
Fixed-step explicit Runge-Kutta integrator for ODEs Currently implements RK4.
The method is still under development
Author
Joel Andersson
Date
2011-2015
Function Documentation
CASADI_EXPORT std::string casadi::doc_integrator (const std::string & name)
CASADI_EXPORT bool casadi::has_integrator (const std::string & name)
CASADI_EXPORT Function casadi::integrator (const std::string & name, const std::string & solver, const SXDict & dae, const Dict & opts = Dict())
Referenced by casadi::integrator(), and casadi::simpleIntegrator().
CASADI_EXPORT Function casadi::integrator (const std::string & name, const std::string & solver, const MXDict & dae, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::integrator (const std::string & name, const std::string & solver, const Function & dae, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::integrator (const std::string & name, const std::string & solver, const std::pair< Function, Function > & dae, const Dict & opts = Dict())
CASADI_EXPORT Function casadi::integrator (const std::string & name, const std::string & solver, Oracle * dae, const Dict & opts = Dict())
CASADI_EXPORT std::vector< std::string > casadi::integrator_in ()
Definition at line 92 of file integrator.cpp.
References casadi::integrator_in(), and casadi::integrator_n_in().
Referenced by casadi::Integrator::get_forward(), casadi::Integrator::get_name_in(), and casadi::Integrator::get_reverse().
{
     vector<string> ret(integrator_n_in());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=integrator_in(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::integrator_in (int ind)
Definition at line 104 of file integrator.cpp.
References casadi::INTEGRATOR_NUM_IN, casadi::INTEGRATOR_P, casadi::INTEGRATOR_RP, casadi::INTEGRATOR_RX0, casadi::INTEGRATOR_RZ0, casadi::INTEGRATOR_X0, and casadi::INTEGRATOR_Z0.
Referenced by casadi::integrator_in().
{
     switch (static_cast<IntegratorInput>(ind)) {
     case INTEGRATOR_X0:  return "x0";
     case INTEGRATOR_P:   return "p";
     case INTEGRATOR_Z0:  return "z0";
     case INTEGRATOR_RX0: return "rx0";
     case INTEGRATOR_RP:  return "rp";
     case INTEGRATOR_RZ0: return "rz0";
     case INTEGRATOR_NUM_IN: break;
     }
     return string();
   }
CASADI_EXPORT int casadi::integrator_n_in ()
Definition at line 130 of file integrator.cpp.
References casadi::INTEGRATOR_NUM_IN.
Referenced by casadi::integrator_in().
{
     return INTEGRATOR_NUM_IN;
   }
CASADI_EXPORT int casadi::integrator_n_out ()
Definition at line 134 of file integrator.cpp.
References casadi::INTEGRATOR_NUM_OUT.
Referenced by casadi::integrator_out().
{
     return INTEGRATOR_NUM_OUT;
   }
CASADI_EXPORT std::vector< std::string > casadi::integrator_out ()
Definition at line 98 of file integrator.cpp.
References casadi::integrator_n_out(), and casadi::integrator_out().
Referenced by casadi::Integrator::get_forward(), casadi::Integrator::get_name_out(), and casadi::Integrator::get_reverse().
{
     vector<string> ret(integrator_n_out());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=integrator_out(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::integrator_out (int ind)
Definition at line 117 of file integrator.cpp.
References casadi::INTEGRATOR_NUM_OUT, casadi::INTEGRATOR_QF, casadi::INTEGRATOR_RQF, casadi::INTEGRATOR_RXF, casadi::INTEGRATOR_RZF, casadi::INTEGRATOR_XF, and casadi::INTEGRATOR_ZF.
Referenced by casadi::integrator_out().
{
     switch (static_cast<IntegratorOutput>(ind)) {
     case INTEGRATOR_XF:  return "xf";
     case INTEGRATOR_QF:  return "qf";
     case INTEGRATOR_ZF:  return "zf";
     case INTEGRATOR_RXF: return "rxf";
     case INTEGRATOR_RQF: return "rqf";
     case INTEGRATOR_RZF: return "rzf";
     case INTEGRATOR_NUM_OUT: break;
     }
     return string();
   }
CASADI_EXPORT void casadi::load_integrator (const std::string & name)
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge