CasADi: casadi::Matrix< Scalar > Class Template Reference
casadi::Matrix< Scalar > Class Template Reference
Sparse matrix class. SX and DM are specializations.
#include <casadi_types.hpp>
Detailed Description
template<typename Scalar>
class casadi::Matrix< Scalar >
General sparse matrix class that is designed with the idea that "everything is a matrix", that is, also scalars and vectors.
This philosophy makes it easy to use and to interface in particularly with Python and Matlab/Octave.
Index starts with 0.
Index vec happens as follows: (rr, cc) -> k = rr+cc*size1()
Vectors are column vectors.
The storage format is Compressed Column Storage (CCS), similar to that used for sparse matrices in Matlab,
but unlike this format, we do allow for elements to be structurally non-zero but numerically zero.
Matrix<Scalar> is polymorphic with a std::vector<Scalar> that contain all non-identical-zero elements.
The sparsity can be accessed with Sparsity& sparsity()
Author
Joel Andersson
Date
2010-2014
Definition at line 57 of file casadi_types.hpp.
Public Types
typedef Scalar ScalarType
Scalar type.
typedef GenericMatrix< Matrix
< Scalar > > B
Base class.
Public Member Functions
Matrix ()
constructors
Matrix (const Matrix< Scalar > &m)
Copy constructor.
Matrix< Scalar > & operator= (const Matrix< Scalar > &m)
Assignment (normal)
Matrix (int nrow, int ncol)
Create a sparse matrix with all structural zeros.
Matrix (const std::pair< int, int > &rc)
Create a sparse matrix with all structural zeros.
std::vector< Scalar > * operator-> ()
Access functions of the node.
const std::vector< Scalar > * operator-> () const
Const access functions of the node.
Matrix (const Sparsity &sp)
Create a sparse matrix from a sparsity pattern. Same as Matrix::ones(sparsity)
Matrix (const Sparsity &sp, const Matrix< Scalar > &d)
Construct matrix with a given sparsity and nonzeros.
void sanity_check (bool complete=false) const
Check if the dimensions and colind, row vectors are compatible.
Matrix (double val)
This constructor enables implicit type conversion from a numeric type.
Matrix (const std::vector< std::vector< double > > &m)
Dense matrix constructor with data given as vector of vectors.
template<typename A >
Matrix (const Matrix< A > &x)
Create a matrix from another matrix with a different entry type Assumes that the scalar conversion is valid.
template<typename A >
Matrix (const std::vector< A > &x)
Create an expression from a vector.
Matrix (const std::vector< Scalar > &x)
Construct from a vector.
const Scalar scalar () const
Convert to scalar type.
bool has_nz (int rr, int cc) const
Returns true if the matrix has a non-zero at location rr, cc.
bool __nonzero__ () const
Returns the truth value of a Matrix.
Matrix< Scalar > operator+ () const
Matrix< Scalar > operator- () const
Matrix< Scalar > printme (const Matrix< Scalar > &y) const
Matrix< Scalar > T () const
Transpose the matrix.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void print_split (std::vector< std::string > &output_nz, std::vector< std::string > &output_inter) const
Get strings corresponding to the nonzeros and the interdependencies.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print_scalar (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print scalar.
void print_vector (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print vector-style.
void print_dense (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print dense matrix-stype.
void print_sparse (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print sparse matrix style.
void clear ()
void resize (int nrow, int ncol)
void reserve (int nnz)
void reserve (int nnz, int ncol)
void erase (const std::vector< int > &rr, const std::vector< int > &cc, bool ind1=false)
Erase a submatrix (leaving structural zeros in its place) Erase rows and/or columns of a matrix.
void erase (const std::vector< int > &rr, bool ind1=false)
Erase a submatrix (leaving structural zeros in its place) Erase elements of a matrix.
void remove (const std::vector< int > &rr, const std::vector< int > &cc)
Remove columns and rows Remove/delete rows and/or columns of a matrix.
void enlarge (int nrow, int ncol, const std::vector< int > &rr, const std::vector< int > &cc, bool ind1=false)
Enlarge matrix Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros.
const Sparsity & sparsity () const
Const access the sparsity - reference to data member.
Sparsity get_sparsity () const
Get an owning reference to the sparsity pattern.
size_t element_hash () const
Returns a number that is unique for a given symbolic scalar.
bool is_regular () const
Checks if expression does not contain NaN or Inf.
bool is_smooth () const
Check if smooth.
bool is_leaf () const
Check if SX is a leaf of the SX graph.
bool is_commutative () const
Check whether a binary SX is commutative.
bool is_symbolic () const
Check if symbolic (Dense) Sparse matrices invariable return false.
bool is_valid_input () const
Check if matrix can be used to define function inputs. Sparse matrices can return true if all non-zero elements are symbolic.
bool has_duplicates ()
Detect duplicate symbolic expressions If there are symbolic primitives appearing more than once, the function will return true and the names of the duplicate expressions will be printed to userOut<true, PL_WARN>(). Note: Will mark the node using SXElem::setTemp. Make sure to call resetInput() after usage.
void resetInput ()
Reset the marker for an input expression.
bool is_constant () const
Check if the matrix is constant (note that false negative answers are possible)
bool is_integer () const
Check if the matrix is integer-valued (note that false negative answers are possible)
bool is_zero () const
check if the matrix is 0 (note that false negative answers are possible)
bool is_one () const
check if the matrix is 1 (note that false negative answers are possible)
bool is_minus_one () const
check if the matrix is -1 (note that false negative answers are possible)
bool is_identity () const
check if the matrix is an identity matrix (note that false negative answers are possible)
bool has_zeros () const
Check if the matrix has any zero entries which are not structural zeros.
std::vector< Scalar > get_nonzeros () const
Get all nonzeros.
template<typename A >
std::vector< A > get_nonzeros () const
Get all nonzeros.
operator double () const
Type conversion to double.
operator int () const
Type conversion to int.
template<typename A >
operator std::vector< A > () const
Type conversion to a vector.
std::string name () const
Get name (only if symbolic scalar)
Matrix< Scalar > dep (int ch=0) const
Get expressions of the children of the expression Only defined if symbolic scalar. Wraps SXElem SXElem::dep(int ch=0) const.
int n_dep () const
Get the number of dependencies of a binary SXElem Only defined if symbolic scalar.
Matrix (const Sparsity &sp, const Scalar &val, bool dummy)
Sparse matrix with a given sparsity with all values same.
Matrix (const Sparsity &sp, const std::vector< Scalar > &d, bool dummy)
Sparse matrix with a given sparsity and non-zero elements.
template<>
Matrix< double > solve (const Matrix< double > &A, const Matrix< double > &b, const string &lsolver, const Dict &dict)
template<>
Matrix< double > pinv (const Matrix< double > &A, const string &lsolver, const Dict &dict)
template<>
bool __nonzero__ () const
template<>
CASADI_EXPORT Matrix< double > solve (const Matrix< double > &a, const Matrix< double > &b, const std::string &lsolver, const Dict &dict)
template<>
CASADI_EXPORT Matrix< double > pinv (const Matrix< double > &A, const std::string &lsolver, const Dict &dict)
template<>
CASADI_EXPORT bool __nonzero__ () const
int nnz () const
Get the number of (structural) non-zero elements.
int nnz_lower () const
Get the number of non-zeros in the lower triangular half.
int nnz_upper () const
Get the number of non-zeros in the upper triangular half.
int nnz_diag () const
Get get the number of non-zeros on the diagonal.
int numel () const
Get the number of elements.
int numel (int i) const
Get the number of elements in slice (cf. MATLAB)
int size1 () const
Get the first dimension (i.e. number of rows)
int size2 () const
Get the second dimension (i.e. number of columns)
std::string dim () const
Get string representation of dimensions. The representation is (nrow x ncol = numel | size)
std::pair< int, int > size () const
Get the shape.
int size (int axis) const
Get the size along a particular dimensions.
bool is_empty (bool both=false) const
Check if the sparsity is empty, i.e. if one of the dimensions is zero (or optionally both dimensions)
bool is_dense () const
Check if the matrix expression is dense.
bool is_scalar (bool scalar_and_dense=false) const
Check if the matrix expression is scalar.
bool is_square () const
Check if the matrix expression is square.
bool is_vector () const
Check if the matrix is a row or column vector.
bool is_row () const
Check if the matrix is a row vector (i.e. size1()==1)
bool is_column () const
Check if the matrix is a column vector (i.e. size2()==1)
bool is_triu () const
Check if the matrix is upper triangular.
bool is_tril () const
Check if the matrix is lower triangular.
std::vector< int > find (bool ind1=SWIG_IND1) const
Get the location of all non-zero elements as they would appear in a Dense matrix A : DenseMatrix 4 x 3 B : SparseMatrix 4 x 3 , 5 structural non-zeros.
SWIG_CONSTREF (Sparsity) sparsity() const
Get the sparsity pattern.
Sparsity & sparsityRef ()
Access the sparsity, make a copy if there are multiple references to it.
const Matrix< Scalar > operator[] (const K &k) const
Get vector nonzero or slice of nonzeros.
NonZeros< Matrix< Scalar >, K > operator[] (const K &k)
Access vector nonzero or slice of nonzeros.
const Matrix< Scalar > operator() (const RR &rr) const
Get vector element or slice.
const Matrix< Scalar > operator() (const RR &rr, const CC &cc) const
Get Matrix element or slice.
SubIndex< Matrix< Scalar >, RR > operator() (const RR &rr)
Access Matrix elements (one argument)
SubMatrix< Matrix< Scalar >
, RR, CC > operator() (const RR &rr, const CC &cc)
Access Matrix elements (two arguments)
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
void get (Matrix< Scalar > &output_m, bool ind1, const Slice &rr) const
void get (Matrix< Scalar > &output_m, bool ind1, const Matrix< int > &rr) const
void get (Matrix< Scalar > &output_m, bool ind1, const Sparsity &sp) const
void get (Matrix< Scalar > &output_m, bool ind1, const Slice &rr, const Slice &cc) const
void get (Matrix< Scalar > &output_m, bool ind1, const Slice &rr, const Matrix< int > &cc) const
void get (Matrix< Scalar > &output_m, bool ind1, const Matrix< int > &rr, const Slice &cc) const
void get (Matrix< Scalar > &output_m, bool ind1, const Matrix< int > &rr, const Matrix< int > &cc) const
void set (const Matrix< Scalar > &m, bool ind1, const Slice &rr)
void set (const Matrix< Scalar > &m, bool ind1, const Matrix< int > &rr)
void set (const Matrix< Scalar > &m, bool ind1, const Sparsity &sp)
void set (const Matrix< Scalar > &m, bool ind1, const Slice &rr, const Slice &cc)
void set (const Matrix< Scalar > &m, bool ind1, const Slice &rr, const Matrix< int > &cc)
void set (const Matrix< Scalar > &m, bool ind1, const Matrix< int > &rr, const Slice &cc)
void set (const Matrix< Scalar > &m, bool ind1, const Matrix< int > &rr, const Matrix< int > &cc)
void get_nz (Matrix< Scalar > &output_m, bool ind1, const Slice &k) const
void get_nz (Matrix< Scalar > &output_m, bool ind1, const Matrix< int > &k) const
void set_nz (const Matrix< Scalar > &m, bool ind1, const Slice &k)
void set_nz (const Matrix< Scalar > &m, bool ind1, const Matrix< int > &k)
std::vector< Scalar > & nonzeros ()
const std::vector< Scalar > & nonzeros () const
Matrix< Scalar > & operator+= (const Matrix< Scalar > &y)
In-place addition.
Matrix< Scalar > & operator-= (const Matrix< Scalar > &y)
In-place subtraction.
Matrix< Scalar > & operator*= (const Matrix< Scalar > &y)
In-place elementwise multiplication.
Matrix< Scalar > & operator/= (const Matrix< Scalar > &y)
In-place elementwise division.
Matrix< Scalar > operator! () const
Logical not Returns (an expression evaluating to) 1 if expression is zero and 0 otherwise.
std::vector< int > get_row () const
Get the sparsity pattern. See the Sparsity class for details.
std::vector< int > get_colind () const
Get the sparsity pattern. See the Sparsity class for details.
const int * row () const
Get the sparsity pattern. See the Sparsity class for details.
int row (int el) const
Get the sparsity pattern. See the Sparsity class for details.
const int * colind () const
Get the sparsity pattern. See the Sparsity class for details.
int colind (int col) const
Get the sparsity pattern. See the Sparsity class for details.
Static Public Member Functions
static void setEqualityCheckingDepth (int eq_depth=1)
Set or reset the depth to which equalities are being checked for simplifications.
static int getEqualityCheckingDepth ()
Get the depth to which equalities are being checked for simplifications.
static std::vector< Matrix
< Scalar > > get_input (const Function &f)
Get function input.
static std::string type_name ()
Get name of the class.
static Matrix< Scalar > eye (int ncol)
create an n-by-n identity matrix
static std::vector
< std::vector< Matrix< Scalar > > > blocksplit (const Matrix< Scalar > &x, const std::vector< int > &vert_offset, const std::vector< int > &horz_offset)
static std::vector
< std::vector< Matrix< Scalar > > > blocksplit (const Matrix< Scalar > &x, int vert_incr, int horz_incr)
static Matrix< Scalar > veccat (const std::vector< Matrix< Scalar > > &x)
static Matrix< Scalar > vec (const Matrix< Scalar > &x)
static Matrix< Scalar > repmat (const Matrix< Scalar > &x, int n, int m=1)
static Matrix< Scalar > repmat (const Matrix< Scalar > &A, const std::pair< int, int > &rc)
static std::vector< int > offset (const std::vector< Matrix< Scalar > > &v, bool vert=true)
static std::vector< Matrix
< Scalar > > diagsplit (const Matrix< Scalar > &x, const std::vector< int > &output_offset)
static std::vector< Matrix
< Scalar > > diagsplit (const Matrix< Scalar > &x, int incr)
static std::vector< Matrix
< Scalar > > diagsplit (const Matrix< Scalar > &x, int incr1, int incr2)
static Matrix< Scalar > mtimes (const std::vector< Matrix< Scalar > > &args)
static std::vector< Matrix
< Scalar > > horzsplit (const Matrix< Scalar > &x, int incr)
static std::vector< Matrix
< Scalar > > vertsplit (const Matrix< Scalar > &x, int incr)
static Matrix< Scalar > binary (int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static Matrix< Scalar > unary (int op, const Matrix< Scalar > &x)
Create nodes by their ID.
static Matrix< Scalar > scalar_matrix (int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static Matrix< Scalar > matrix_scalar (int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static Matrix< Scalar > matrix_matrix (int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static bool is_equal (const Matrix< Scalar > &x, const Matrix< Scalar > &y, int depth=0)
static Matrix< Scalar > simplify (const Matrix< Scalar > &x)
static Matrix< Scalar > jacobian (const Matrix< Scalar > &f, const Matrix< Scalar > &x, bool symmetric=false)
static Matrix< Scalar > gradient (const Matrix< Scalar > &f, const Matrix< Scalar > &x)
static Matrix< Scalar > tangent (const Matrix< Scalar > &f, const Matrix< Scalar > &x)
static Matrix< Scalar > hessian (const Matrix< Scalar > &f, const Matrix< Scalar > &x)
static Matrix< Scalar > hessian (const Matrix< Scalar > &f, const Matrix< Scalar > &x, Matrix< Scalar > &g)
static Matrix< Scalar > substitute (const Matrix< Scalar > &ex, const Matrix< Scalar > &v, const Matrix< Scalar > &vdef)
static std::vector< Matrix
< Scalar > > substitute (const std::vector< Matrix< Scalar > > &ex, const std::vector< Matrix< Scalar > > &v, const std::vector< Matrix< Scalar > > &vdef)
static void substitute_inplace (const std::vector< Matrix< Scalar > > &v, std::vector< Matrix< Scalar > > &vdef, std::vector< Matrix< Scalar > > &ex, bool revers)
static Matrix< Scalar > pinv (const Matrix< Scalar > &x)
static Matrix< Scalar > pinv (const Matrix< Scalar > &A, const std::string &lsolver, const Dict &opts)
static Matrix< Scalar > solve (const Matrix< Scalar > &A, const Matrix< Scalar > &b)
static Matrix< Scalar > solve (const Matrix< Scalar > &A, const Matrix< Scalar > &b, const std::string &lsolver, const Dict &opts)
static int n_nodes (const Matrix< Scalar > &x)
static std::string print_operator (const Matrix< Scalar > &x, const std::vector< std::string > &args)
static void shared (std::vector< Matrix< Scalar > > &ex, std::vector< Matrix< Scalar > > &v, std::vector< Matrix< Scalar > > &vdef, const std::string &v_prefix, const std::string &v_suffix)
static Matrix< Scalar > _bilin (const Matrix< Scalar > &A, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > _rank1 (const Matrix< Scalar > &A, const Matrix< Scalar > &alpha, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > if_else (const Matrix< Scalar > &x, const Matrix< Scalar > &if_true, const Matrix< Scalar > &if_false, bool short_circuit)
static Matrix< Scalar > conditional (const Matrix< Scalar > &ind, const std::vector< Matrix< Scalar > > &x, const Matrix< Scalar > &x_default, bool short_circuit)
static bool depends_on (const Matrix< Scalar > &x, const Matrix< Scalar > &arg)
static Matrix< Scalar > mpower (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > mrdivide (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > mldivide (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static std::vector< Matrix
< Scalar > > symvar (const Matrix< Scalar > &x)
static Matrix< Scalar > det (const Matrix< Scalar > &x)
static Matrix< Scalar > inv (const Matrix< Scalar > &x)
static Matrix< Scalar > trace (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_1 (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_2 (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_F (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_inf (const Matrix< Scalar > &x)
static Matrix< Scalar > sum2 (const Matrix< Scalar > &x)
static Matrix< Scalar > sum1 (const Matrix< Scalar > &x)
static Matrix< Scalar > dot (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > nullspace (const Matrix< Scalar > &x)
static Matrix< Scalar > diag (const Matrix< Scalar > &x)
static Matrix< Scalar > unite (const Matrix< Scalar > &A, const Matrix< Scalar > &B)
static Matrix< Scalar > project (const Matrix< Scalar > &x, const Sparsity &sp, bool intersect=false)
static Matrix< Scalar > polyval (const Matrix< Scalar > &p, const Matrix< Scalar > &x)
static Matrix< Scalar > densify (const Matrix< Scalar > &x, const Matrix< Scalar > &val)
static Matrix< Scalar > densify (const Matrix< Scalar > &x)
static Matrix< Scalar > blockcat (const std::vector< std::vector< Matrix< Scalar > > > &v)
static Matrix< Scalar > horzcat (const std::vector< Matrix< Scalar > > &v)
static std::vector< Matrix
< Scalar > > horzsplit (const Matrix< Scalar > &x, const std::vector< int > &offset)
static Matrix< Scalar > vertcat (const std::vector< Matrix< Scalar > > &v)
static std::vector< Matrix
< Scalar > > vertsplit (const Matrix< Scalar > &x, const std::vector< int > &offset)
static std::vector< Matrix
< Scalar > > diagsplit (const Matrix< Scalar > &x, const std::vector< int > &offset1, const std::vector< int > &offset2)
static Matrix< Scalar > reshape (const Matrix< Scalar > &x, int nrow, int ncol)
static Matrix< Scalar > reshape (const Matrix< Scalar > &x, const Sparsity &sp)
static Matrix< Scalar > kron (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > mtimes (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > mac (const Matrix< Scalar > &x, const Matrix< Scalar > &y, const Matrix< Scalar > &z)
static Matrix< Scalar > sparsify (const Matrix< Scalar > &x, double tol=0)
static void expand (const Matrix< Scalar > &x, Matrix< Scalar > &weights, Matrix< Scalar > &terms)
static Matrix< Scalar > pw_const (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
static Matrix< Scalar > pw_lin (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
static Matrix< Scalar > heaviside (const Matrix< Scalar > &x)
static Matrix< Scalar > rectangle (const Matrix< Scalar > &x)
static Matrix< Scalar > triangle (const Matrix< Scalar > &x)
static Matrix< Scalar > ramp (const Matrix< Scalar > &x)
static Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, int order=5)
static Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, int order, const Matrix< Scalar > &w)
static Matrix< Scalar > jtimes (const Matrix< Scalar > &ex, const Matrix< Scalar > &arg, const Matrix< Scalar > &v, bool tr=false)
static std::vector< bool > nl_var (const Matrix< Scalar > &expr, const Matrix< Scalar > &var)
static Matrix< Scalar > taylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, int order)
static Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, int order)
static Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, int order, const std::vector< int > &order_contributions)
static Matrix< Scalar > poly_coeff (const Matrix< Scalar > &ex, const Matrix< Scalar > &x)
static Matrix< Scalar > poly_roots (const Matrix< Scalar > &p)
static Matrix< Scalar > eig_symbolic (const Matrix< Scalar > &m)
static void qr (const Matrix< Scalar > &A, Matrix< Scalar > &Q, Matrix< Scalar > &R)
static Matrix< Scalar > all (const Matrix< Scalar > &x)
static Matrix< Scalar > any (const Matrix< Scalar > &x)
static Matrix< Scalar > adj (const Matrix< Scalar > &x)
static Matrix< Scalar > getMinor (const Matrix< Scalar > &x, int i, int j)
static Matrix< Scalar > cofactor (const Matrix< Scalar > &A, int i, int j)
static Matrix< Scalar > chol (const Matrix< Scalar > &A)
static Matrix< Scalar > norm_inf_mul (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > diagcat (const std::vector< Matrix< Scalar > > &A)
Construct a matrix with given block on the diagonal.
static Matrix< Scalar > jac (const Function &f, int iind=0, int oind=0, bool compact=false, bool symmetric=false)
Jacobian expression.
static Matrix< Scalar > jac (const Function &f, const std::string &iname, int oind=0, bool compact=false, bool symmetric=false)
Jacobian expression.
static Matrix< Scalar > jac (const Function &f, int iind, const std::string &oname, bool compact=false, bool symmetric=false)
Jacobian expression.
static Matrix< Scalar > jac (const Function &f, const std::string &iname, const std::string &oname, bool compact=false, bool symmetric=false)
Jacobian expression.
static Matrix< Scalar > grad (const Function &f, int iind=0, int oind=0)
Gradient expression.
static Matrix< Scalar > grad (const Function &f, const std::string &iname, int oind=0)
Gradient expression.
static Matrix< Scalar > grad (const Function &f, int iind, const std::string &oname)
Gradient expression.
static Matrix< Scalar > grad (const Function &f, const std::string &iname, const std::string &oname)
Gradient expression.
static Matrix< Scalar > tang (const Function &f, int iind=0, int oind=0)
Tangent expression.
static Matrix< Scalar > tang (const Function &f, const std::string &iname, int oind=0)
Tangent expression.
static Matrix< Scalar > tang (const Function &f, int iind, const std::string &oname)
Tangent expression.
static Matrix< Scalar > tang (const Function &f, const std::string &iname, const std::string &oname)
Tangent expression.
static Matrix< Scalar > hess (const Function &f, int iind=0, int oind=0)
static Matrix< Scalar > hess (const Function &f, const std::string &iname, int oind=0)
static Matrix< Scalar > hess (const Function &f, int iind, const std::string &oname)
static Matrix< Scalar > hess (const Function &f, const std::string &iname, const std::string &oname)
static Matrix< Scalar > triplet (const std::vector< int > &row, const std::vector< int > &col, const Matrix< Scalar > &d)
static Matrix< Scalar > triplet (const std::vector< int > &row, const std::vector< int > &col, const Matrix< Scalar > &d, int nrow, int ncol)
static Matrix< Scalar > triplet (const std::vector< int > &row, const std::vector< int > &col, const Matrix< Scalar > &d, const std::pair< int, int > &rc)
static Matrix< Scalar > inf (const Sparsity &sp)
create a matrix with all inf
static Matrix< Scalar > inf (int nrow=1, int ncol=1)
create a matrix with all inf
static Matrix< Scalar > inf (const std::pair< int, int > &rc)
create a matrix with all inf
static Matrix< Scalar > nan (const Sparsity &sp)
create a matrix with all nan
static Matrix< Scalar > nan (int nrow=1, int ncol=1)
create a matrix with all nan
static Matrix< Scalar > nan (const std::pair< int, int > &rc)
create a matrix with all nan
static void setPrecision (int precision)
Set the 'precision, width & scientific' used in printing and serializing to streams.
static void setWidth (int width)
Set the 'precision, width & scientific' used in printing and serializing to streams.
static void setScientific (bool scientific)
Set the 'precision, width & scientific' used in printing and serializing to streams.
static int sprank (const Matrix< Scalar > &x)
Accessed by friend functions.
static int norm_0_mul (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Accessed by friend functions.
static Matrix< Scalar > tril (const Matrix< Scalar > &x, bool includeDiagonal=true)
Accessed by friend functions.
static Matrix< Scalar > triu (const Matrix< Scalar > &x, bool includeDiagonal=true)
Accessed by friend functions.
static Matrix< Scalar > sum_square (const Matrix< Scalar > &x)
Accessed by friend functions.
static Matrix< Scalar > linspace (const Matrix< Scalar > &a, const Matrix< Scalar > &b, int nsteps)
Accessed by friend functions.
static Matrix< Scalar > cross (const Matrix< Scalar > &a, const Matrix< Scalar > &b, int dim=-1)
Accessed by friend functions.
static Matrix< Scalar > skew (const Matrix< Scalar > &a)
Accessed by friend functions.
static Matrix< Scalar > inv_skew (const Matrix< Scalar > &a)
Accessed by friend functions.
static Matrix< Scalar > tril2symm (const Matrix< Scalar > &x)
Accessed by friend functions.
static Matrix< Scalar > triu2symm (const Matrix< Scalar > &x)
Accessed by friend functions.
static Matrix< Scalar > repsum (const Matrix< Scalar > &x, int n, int m=1)
Accessed by friend functions.
static Matrix< Scalar > bilin (const Matrix< Scalar > &A, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Matrix power x^n.
static Matrix< Scalar > rank1 (const Matrix< Scalar > &A, const Matrix< Scalar > &alpha, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Make a rank-1 update to a matrix A Calculates A + 1/2 * alpha * x*y'.
Construct symbolic primitives
The "sym" function is intended to work in a similar way as "sym" used in the Symbolic Toolbox for Matlab but instead creating a CasADi symbolic primitive.
static Matrix< Scalar > sym (const std::string &name, int nrow=1, int ncol=1)
Create an nrow-by-ncol symbolic primitive.
static Matrix< Scalar > sym (const std::string &name, const std::pair< int, int > &rc)
Construct a symbolic primitive with given dimensions.
static Matrix< Scalar > sym (const std::string &name, const Sparsity &sp)
Create symbolic primitive with a given sparsity pattern.
static std::vector< Matrix
< Scalar > > sym (const std::string &name, const Sparsity &sp, int p)
Create a vector of length p with with matrices with symbolic primitives of given sparsity.
static std::vector< Matrix
< Scalar > > sym (const std::string &name, int nrow, int ncol, int p)
Create a vector of length p with nrow-by-ncol symbolic primitives.
static std::vector
< std::vector< Matrix< Scalar > > > sym (const std::string &name, const Sparsity &sp, int p, int r)
Create a vector of length r of vectors of length p with symbolic primitives with given sparsity.
static std::vector
< std::vector< Matrix< Scalar > > > sym (const std::string &name, int nrow, int ncol, int p, int r)
Create a vector of length r of vectors of length p with nrow-by-ncol symbolic primitives.
static Matrix< Scalar > zeros (int nrow=1, int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static Matrix< Scalar > zeros (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static Matrix< Scalar > zeros (const std::pair< int, int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static Matrix< Scalar > ones (int nrow=1, int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static Matrix< Scalar > ones (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static Matrix< Scalar > ones (const std::pair< int, int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries one.
Protected Member Functions
const Matrix< Scalar > & self () const
Matrix< Scalar > & self ()
const Matrix< Scalar > & self () const
Matrix< Scalar > & self ()
Friends
Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, int order=1)
multivariate Taylor series expansion
Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, int order, const std::vector< int > &order_contributions)
multivariate Taylor series expansion
Matrix< Scalar > poly_coeff (const Matrix< Scalar > &f, const Matrix< Scalar > &x)
extracts polynomial coefficients from an expression
Matrix< Scalar > poly_roots (const Matrix< Scalar > &p)
Attempts to find the roots of a polynomial.
Matrix< Scalar > eig_symbolic (const Matrix< Scalar > &m)
Attempts to find the eigenvalues of a symbolic matrix This will only work for up to 3x3 matrices.
Matrix< Scalar > adj (const Matrix< Scalar > &A)
Matrix adjoint.
Matrix< Scalar > getMinor (const Matrix< Scalar > &x, int i, int j)
Get the (i,j) minor matrix.
Matrix< Scalar > cofactor (const Matrix< Scalar > &x, int i, int j)
Get the (i,j) cofactor matrix.
void qr (const Matrix< Scalar > &A, Matrix< Scalar > &Q, Matrix< Scalar > &R)
QR factorization using the modified Gram-Schmidt algorithm More stable than the classical Gram-Schmidt, but may break down if the rows of A are nearly linearly dependent See J. Demmel: Applied Numerical Linear Algebra (algorithm 3.1.). Note that in SWIG, Q and R are returned by value.
Matrix< Scalar > chol (const Matrix< Scalar > &A)
Obtain a Cholesky factorisation of a matrix Returns an upper triangular R such that R'R = A. Matrix A must be positive definite.
Matrix< Scalar > any (const Matrix< Scalar > &x)
Returns true only if any element in the matrix is true.
Matrix< Scalar > all (const Matrix< Scalar > &x)
Returns true only if every element in the matrix is true.
Matrix< Scalar > norm_inf_mul (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Inf-norm of a Matrix-Matrix product.
Matrix< Scalar > sparsify (const Matrix< Scalar > &A, double tol=0)
Make a matrix sparse by removing numerical zeros.
void expand (const Matrix< Scalar > &ex, Matrix< Scalar > &weights, Matrix< Scalar > &terms)
Expand the expression as a weighted sum (with constant weights)
Matrix< Scalar > pw_const (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
Create a piecewise constant function Create a piecewise constant function with n=val.size() intervals.
Matrix< Scalar > pw_lin (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
t a scalar variable (e.g. time)
Matrix< Scalar > heaviside (const Matrix< Scalar > &x)
Heaviside function.
Matrix< Scalar > rectangle (const Matrix< Scalar > &x)
rectangle function
Matrix< Scalar > triangle (const Matrix< Scalar > &x)
triangle function
Matrix< Scalar > ramp (const Matrix< Scalar > &x)
ramp function
Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, int order=5)
Integrate f from a to b using Gaussian quadrature with n points.
Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, int order, const Matrix< Scalar > &w)
Matrix adjoint.
Matrix< Scalar > taylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, int order=1)
univariate Taylor series expansion
Matrix< Scalar > taylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x)
univariate Taylor series expansion
Scalar * ptr ()
const Scalar * ptr () const
Scalar * get_ptr (Matrix< Scalar > &v)
const Scalar * get_ptr (const Matrix< Scalar > &v)
Member Typedef Documentation
template<typename Scalar> typedef GenericMatrix<Matrix<Scalar> > casadi::Matrix< Scalar >::B
Definition at line 161 of file matrix.hpp.
template<typename Scalar> typedef Scalar casadi::Matrix< Scalar >::ScalarType
Definition at line 158 of file matrix.hpp.
Constructor & Destructor Documentation
template<typename Scalar > casadi::Matrix< Scalar >::Matrix ()
empty 0-by-0 matrix constructor
Definition at line 525 of file matrix_impl.hpp.
                          : sparsity_(Sparsity(0, 0)) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const Matrix< Scalar > & m)
Definition at line 529 of file matrix_impl.hpp.
                                                 : sparsity_(m.sparsity_), nonzeros_(m.nonzeros_) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (int nrow, int ncol)
Definition at line 809 of file matrix_impl.hpp.
                                            : sparsity_(nrow, ncol) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const std::pair< int, int > & rc) explicit
Definition at line 813 of file matrix_impl.hpp.
                                                     : sparsity_(rc) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const Sparsity & sp) explicit
Definition at line 805 of file matrix_impl.hpp.
                                            : sparsity_(sp), nonzeros_(sp.nnz(), 1) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const Sparsity & sp, const Matrix< Scalar > & d)
Definition at line 830 of file matrix_impl.hpp.
References casadi::densify(), casadi::GenericMatrix< Matrix< Scalar > >::is_column(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::Sparsity::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< Matrix< Scalar > >::numel(), casadi::Matrix< Scalar >::scalar(), and casadi::GenericMatrix< Matrix< Scalar > >::size1().
{
     if (d.is_scalar()) {
       *this = Matrix<Scalar>(sp, d.scalar(), false);
     } else if (d.is_column() || d.size1()==1) {
       casadi_assert(sp.nnz()==d.numel());
       if (d.is_dense()) {
         *this = Matrix<Scalar>(sp, d.nonzeros(), false);
       } else {
         *this = Matrix<Scalar>(sp, densify(d).nonzeros(), false);
       }
     } else {
       casadi_error("Matrix(Sparsisty, Matrix): Only allowed for scalars and vectors");
     }
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (double val)
Definition at line 772 of file matrix_impl.hpp.
                                    :
       sparsity_(Sparsity::dense(1, 1)), nonzeros_(std::vector<Scalar>(1, val)) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const std::vector< std::vector< double > > & m) explicit
Definition at line 777 of file matrix_impl.hpp.
References casadi::Sparsity::dense().
{
     // Get dimensions
     int nrow=d.size();
     int ncol=d.empty() ? 1 : d.front().size();
     // Assert consistency
     for (int rr=0; rr<nrow; ++rr) {
       casadi_assert_message(ncol==d[rr].size(),
         "Matrix<Scalar>::Matrix(const std::vector< std::vector<Scalar> >& d): "
         "shape mismatch" << std::endl
         << "Attempting to construct a matrix from a nested list." << std::endl
         << "I got convinced that the desired size is ("<< nrow << " x " << ncol
         << " ), but now I encounter a vector of size ("
         << d[rr].size() <<  " )" << std::endl);
     }
     // Form matrix
     sparsity_ = Sparsity::dense(nrow, ncol);
     nonzeros().resize(nrow*ncol);
     typename std::vector<Scalar>::iterator it=nonzeros_.begin();
     for (int cc=0; cc<ncol; ++cc) {
       for (int rr=0; rr<nrow; ++rr) {
         *it++ = d[rr][cc];
       }
     }
   }
template<typename Scalar> template<typename A > casadi::Matrix< Scalar >::Matrix (const Matrix< A > & x) inline
Definition at line 137 of file matrix.hpp.
                                : sparsity_(x.sparsity()), nonzeros_(std::vector<Scalar>(x.nnz())) {
       auto x_it = x->begin();
       for (auto&& d : nonzeros_) d = static_cast<Scalar>(*x_it++);
     }
template<typename Scalar> template<typename A > casadi::Matrix< Scalar >::Matrix (const std::vector< A > & x) inline
Definition at line 144 of file matrix.hpp.
                                   : sparsity_(Sparsity::dense(x.size(), 1)),
       nonzeros_(std::vector<Scalar>(x.size())) {
         auto x_it = x.begin();
         for (auto&& d : nonzeros_) d = static_cast<Scalar>(*x_it++);
     }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const std::vector< Scalar > & x)
Definition at line 533 of file matrix_impl.hpp.
                                                    :
       sparsity_(Sparsity::dense(x.size(), 1)), nonzeros_(x) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const Sparsity & sp, const Scalar & val, bool dummy)
Definition at line 817 of file matrix_impl.hpp.
                                                                           :
       sparsity_(sp), nonzeros_(sp.nnz(), val) {
   }
template<typename Scalar> casadi::Matrix< Scalar >::Matrix (const Sparsity & sp, const std::vector< Scalar > & d, bool dummy)
Definition at line 822 of file matrix_impl.hpp.
References casadi::Sparsity::dim(), and casadi::Sparsity::nnz().
                                                                                    :
       sparsity_(sp), nonzeros_(d) {
     casadi_assert_message(sp.nnz()==d.size(), "Size mismatch." << std::endl
                           << "You supplied a sparsity of " << sp.dim()
                           << ", but the supplied vector is of length " << d.size());
   }
Member Function Documentation
template<> bool casadi::Matrix< SXElem >::__nonzero__ () const
Definition at line 71 of file matrix.cpp.
{
     if (numel()!=1) {casadi_error("Only scalar Matrix could have a truth value, but you "
                                   "provided a shape" << dim());}
     return nonzeros().at(0).__nonzero__();
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::__nonzero__ () const
Definition at line 46 of file matrix_impl.hpp.
{
     if (numel()!=1) {casadi_error("Only scalar Matrix could have a truth value, but you "
                                   "provided a shape" << dim());}
     return nonzeros().at(0)!=0;
   }
template<> CASADI_EXPORT bool casadi::Matrix< SXElem >::__nonzero__ () const
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::_bilin (const Matrix< Scalar > & A, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1030 of file matrix_impl.hpp.
References casadi::Matrix< Scalar >::ptr(), and casadi::Matrix< Scalar >::sparsity().
{
     return casadi_bilin(A.ptr(), A.sparsity(), x.ptr(), y.ptr());
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::_rank1 (const Matrix< Scalar > & A, const Matrix< Scalar > & alpha, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1037 of file matrix_impl.hpp.
References casadi::Matrix< Scalar >::ptr(), and casadi::Matrix< Scalar >::sparsity().
{
     Matrix<Scalar> ret = A;
     casadi_rank1(ret.ptr(), ret.sparsity(), *alpha.ptr(), x.ptr(), y.ptr());
     return ret;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::adj (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 1569 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::T().
{
     int n = x.size2();
     casadi_assert_message(n == x.size1(), "adj: matrix must be square");
     // Temporary placeholder
     Matrix<Scalar> temp;
     // Cofactor matrix
     Matrix<Scalar> C = Matrix<Scalar>(n, n);
     for (int i=0; i<n; ++i)
       for (int j=0; j<n; ++j) {
         temp = cofactor(x, i, j);
         if (!temp.is_zero()) C(j, i) = temp;
       }
     return C.T();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::all (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 1732 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), and casadi::GenericMatrix< Matrix< Scalar > >::nnz().
{
     if (!x.is_dense()) return false;
     Scalar ret=1;
     for (int i=0; i<x.nnz(); ++i) {
       ret = ret && x->at(i)==1;
     }
     return ret;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::any (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 1742 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), and casadi::GenericMatrix< Matrix< Scalar > >::nnz().
{
     if (!x.is_dense()) return false;
     Scalar ret=0;
     for (int i=0; i<x.nnz(); ++i) {
       ret = ret || x->at(i)==1;
     }
     return ret;
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::bilin (const Matrix< Scalar > & A, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::binary (int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Definition at line 1076 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::numel().
{
     if (x.numel()==1)
       return scalar_matrix(op, x, y);
     else if (y.numel()==1)
       return matrix_scalar(op, x, y);
     else
       return matrix_matrix(op, x, y);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::blockcat (const std::vector< std::vector< Matrix< Scalar > > > & v) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1629 of file matrix_impl.hpp.
{
     std::vector< Matrix<Scalar> > ret;
     for (int i=0; i<v.size(); ++i)
       ret.push_back(horzcat(v[i]));
     return vertcat(ret);
   }
static std::vector< std::vector< Matrix< Scalar > > > casadi::SparsityInterface< Matrix< Scalar > >::blocksplit (const Matrix< Scalar > & x, const std::vector< int > & vert_offset, const std::vector< int > & horz_offset) static inherited
static std::vector< std::vector< Matrix< Scalar > > > casadi::SparsityInterface< Matrix< Scalar > >::blocksplit (const Matrix< Scalar > & x, int vert_incr, int horz_incr) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::chol (const Matrix< Scalar > & A) static
Functions called by friend functions defined here
Definition at line 1864 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::dim(), casadi::Sparsity::lower(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), and casadi::GenericMatrix< Matrix< Scalar > >::size2().
{
     // Cholesky-Banachiewicz algorithm
     // Naive, dense implementation O(n^3)
     // check dimensions
     casadi_assert_message(A.size1() == A.size2(), "Cholesky decomposition requires square matrix."
                                               "Got " << A.dim() << " instead.");
     Matrix<Scalar> ret = Matrix<Scalar>(Sparsity::lower(A.size1()));
     for (int i=0; i<A.size1(); ++i) { // loop over rows
       for (int j=0; j<i; ++j) {
         // Loop over columns before diagonal
         Matrix<Scalar> sum=0;
         for (int k=0;k<j;++k) {
           sum += ret(i, k)*ret(j, k);
         }
         ret(i, j) = (A(i, j)-sum)/ret(j, j);
       }
       // Treat the diagonal element separately
       int j = i;
       Matrix<Scalar> sum = 0;
       for (int k=0;k<j;++k) {
         sum += pow(ret(j, k), 2);
       }
       ret(j, j) = sqrt(A(j, j)-sum);
     }
     return ret.T();
   }
template<typename Scalar > void casadi::Matrix< Scalar >::clear ()
Definition at line 766 of file matrix_impl.hpp.
{
     sparsity_ = Sparsity(0, 0);
     nonzeros().clear();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::cofactor (const Matrix< Scalar > & A, int i, int j) static
Functions called by friend functions defined here
Definition at line 1558 of file matrix_impl.hpp.
{
     // Calculate the i, j minor
     Matrix<Scalar> minor_ij = getMinor(A, i, j);
     // Calculate the cofactor
     int sign_i = 1-2*((i+j) % 2);
     return sign_i * minor_ij;
   }
const int* casadi::GenericMatrix< Matrix< Scalar > >::colind () const inline inherited
Definition at line 147 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::solve(), casadi::Matrix< Scalar >::sparsify(), and casadi::Matrix< Scalar >::trace().
 { return sparsity().colind(); }
int casadi::GenericMatrix< Matrix< Scalar > >::colind (int col) const inline inherited
Definition at line 150 of file generic_matrix.hpp.
 { return sparsity().colind(col); }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::conditional (const Matrix< Scalar > & ind, const std::vector< Matrix< Scalar > > & x, const Matrix< Scalar > & x_default, bool short_circuit) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2142 of file matrix_impl.hpp.
References casadi::if_else().
{
     Matrix<Scalar> ret = x_default;
     for (int k=0; k<x.size(); ++k) {
       ret = if_else(ind==k, x[k], ret, short_circuit);
     }
     return ret;
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::cross (const Matrix< Scalar > & a, const Matrix< Scalar > & b, int dim = -1) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::densify (const Matrix< Scalar > & x, const Matrix< Scalar > & val) static
Functions called by friend functions defined for GenericMatrix
Definition at line 495 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::colind(), casadi::Sparsity::dense(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< Matrix< Scalar > >::row(), casadi::Matrix< Scalar >::scalar(), casadi::GenericMatrix< Matrix< Scalar > >::size(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), and casadi::GenericMatrix< Matrix< Scalar > >::size2().
{
     // Check argument
     casadi_assert(val.is_scalar());
     // Quick return if possible
     if (x.is_dense()) return x;
     // Get sparsity pattern
     int nrow = x.size1();
     int ncol = x.size2();
     const int* colind = x.colind();
     const int* row = x.row();
     auto it = x.nonzeros().cbegin();
     // New data vector
     std::vector<Scalar> d(nrow*ncol, val.scalar());
     // Copy nonzeros
     for (int cc=0; cc<ncol; ++cc) {
       for (int el=colind[cc]; el<colind[cc+1]; ++el) {
         d[cc*nrow + row[el]] = *it++;
       }
     }
     // Construct return matrix
     return Matrix<Scalar>(Sparsity::dense(x.size()), d);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::densify (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 490 of file matrix_impl.hpp.
References casadi::densify().
{
     return densify(x, 0);
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::dep (int ch = 0) const
Definition at line 1418 of file matrix_impl.hpp.
{
     throw CasadiException("\"dep\" not defined for instantiation");
   }
template<typename Scalar> bool casadi::Matrix< Scalar >::depends_on (const Matrix< Scalar > & x, const Matrix< Scalar > & arg) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2222 of file matrix_impl.hpp.
{
     throw CasadiException("\"depends_on\" not defined for instantiation");
     return false;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::det (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1451 of file matrix_impl.hpp.
References casadi::Sparsity::get_col(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< Matrix< int > >::ones(), casadi::GenericMatrix< Matrix< Scalar > >::row(), casadi::Sparsity::row(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::Matrix< Scalar >::sum1(), and casadi::Matrix< Scalar >::sum2().
{
     int n = x.size2();
     casadi_assert_message(n == x.size1(), "matrix must be square");
     // Trivial return if scalar
     if (x.is_scalar()) return x;
     // Trivial case 2 x 2
     if (n==2) return x(0, 0) * x(1, 1) - x(0, 1) * x(1, 0);
     // Return expression
     Matrix<Scalar> ret = 0;
     // Find out which is the best direction to expand along
     // Build up an IM with ones on the non-zeros
     Matrix<int> sp = IM::ones(x.sparsity());
     // Have a count of the nonzeros for each row
     Matrix<int> row_count = Matrix<int>::sum2(sp);
     // A blank row? determinant is structurally zero
     if (!row_count.is_dense()) return 0;
     // Have a count of the nonzeros for each col
     Matrix<int> col_count = Matrix<int>::sum1(sp).T();
     // A blank col? determinant is structurally zero
     if (!row_count.is_dense()) return 0;
     int min_row = std::distance(row_count.nonzeros().begin(),
                                 std::min_element(row_count.nonzeros().begin(),
                                                  row_count.nonzeros().end()));
     int min_col = std::distance(col_count.nonzeros().begin(),
                                 std::min_element(col_count.nonzeros().begin(),
                                                  col_count.nonzeros().end()));
     if (min_row <= min_col) {
       // Expand along row j
       int j = row_count.sparsity().row(min_row);
       Matrix<Scalar> row = x(j, Slice(0, n));
       std::vector< int > col_i = row.sparsity().get_col();
       for (int k=0; k<row.nnz(); ++k) {
         // Sum up the cofactors
         ret += row->at(k)*cofactor(x, col_i.at(k), j);
       }
       return ret;
     } else {
       // Expand along col i
       int i = col_count.sparsity().row(min_col);
       Matrix<Scalar> col = x(Slice(0, n), i);
       const int* row_i = col.row();
       for (int k=0; k<col.nnz(); ++k) {
         // Sum up the cofactors
         ret += col->at(k)*cofactor(x, i, row_i[k]);
       }
       return ret;
     }
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::diag (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2032 of file matrix_impl.hpp.
References casadi::Sparsity::get_diag(), and casadi::Matrix< Scalar >::sparsity().
{
     // Nonzero mapping
     std::vector<int> mapping;
     // Get the sparsity
     Sparsity sp = A.sparsity().get_diag(mapping);
     Matrix<Scalar> ret = zeros(sp);
     for (int k=0; k<mapping.size(); k++) ret[k] = A[mapping[k]];
     return ret;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::diagcat (const std::vector< Matrix< Scalar > > & A) static
Definition at line 2046 of file matrix_impl.hpp.
References casadi::Sparsity::diagcat().
{
     std::vector<Scalar> data;
     std::vector<Sparsity> sp;
     for (int i=0;i<A.size();++i) {
       data.insert(data.end(), A[i].nonzeros().begin(), A[i].nonzeros().end());
       sp.push_back(A[i].sparsity());
     }
     return Matrix<Scalar>(Sparsity::diagcat(sp), data, false);
   }
static std::vector< Matrix< Scalar > > casadi::SparsityInterface< Matrix< Scalar > >::diagsplit (const Matrix< Scalar > & x, const std::vector< int > & output_offset) static inherited
static std::vector< Matrix< Scalar > > casadi::SparsityInterface< Matrix< Scalar > >::diagsplit (const Matrix< Scalar > & x, int incr) static inherited
static std::vector< Matrix< Scalar > > casadi::SparsityInterface< Matrix< Scalar > >::diagsplit (const Matrix< Scalar > & x, int incr1, int incr2) static inherited
template<typename Scalar> std::vector< Matrix< Scalar > > casadi::Matrix< Scalar >::diagsplit (const Matrix< Scalar > & x, const std::vector< int > & offset1, const std::vector< int > & offset2) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1692 of file matrix_impl.hpp.
References casadi::isMonotone(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), and casadi::GenericMatrix< Matrix< Scalar > >::size2().
{
     // Consistency check
     casadi_assert(offset1.size()>=1);
     casadi_assert(offset1.front()==0);
     casadi_assert(offset1.back()==x.size1());
     casadi_assert(isMonotone(offset1));
     // Consistency check
     casadi_assert(offset2.size()>=1);
     casadi_assert(offset2.front()==0);
     casadi_assert(offset2.back()==x.size2());
     casadi_assert(isMonotone(offset2));
     // Number of outputs
     int n = offset1.size()-1;
     // Return value
     std::vector< Matrix<Scalar> > ret;
     // Caveat: this is a very silly implementation
     for (int i=0; i<n; ++i) {
       ret.push_back(x(Slice(offset1[i], offset1[i+1]), Slice(offset2[i], offset2[i+1])));
     }
     return ret;
   }
std::string casadi::GenericMatrix< Matrix< Scalar > >::dim () const inherited
Referenced by casadi::Matrix< Scalar >::chol(), casadi::Matrix< Scalar >::mac(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::Matrix< Scalar >::norm_inf_mul(), casadi::Matrix< Scalar >::nullspace(), and casadi::Matrix< Scalar >::solve().
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::dot (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1721 of file matrix_impl.hpp.
References casadi::dot(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::project(), casadi::Matrix< Scalar >::ptr(), casadi::GenericMatrix< Matrix< Scalar > >::size(), and casadi::Matrix< Scalar >::sparsity().
{
     casadi_assert_message(x.size()==y.size(), "dot: Dimension mismatch");
     if (x.sparsity()!=y.sparsity()) {
       Sparsity sp = x.sparsity() * y.sparsity();
       return dot(project(x, sp), project(y, sp));
     }
     return casadi_dot(x.nnz(), x.ptr(), y.ptr());
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::eig_symbolic (const Matrix< Scalar > & m) static
Functions called by friend functions defined here
Definition at line 2346 of file matrix_impl.hpp.
{
     throw CasadiException("\"eig_symbolic\" not defined for instantiation");
   }
template<typename Scalar > size_t casadi::Matrix< Scalar >::element_hash () const
Only defined if symbolic scalar.
Definition at line 1289 of file matrix_impl.hpp.
{
     throw CasadiException("\"element_hash\" not defined for instantiation");
   }
template<typename Scalar > void casadi::Matrix< Scalar >::enlarge (int nrow, int ncol, const std::vector< int > & rr, const std::vector< int > & cc, bool ind1 = false)
Definition at line 960 of file matrix_impl.hpp.
{
     sparsity_.enlarge(nrow, ncol, rr, cc, ind1);
   }
template<typename Scalar > void casadi::Matrix< Scalar >::erase (const std::vector< int > & rr, const std::vector< int > & cc, bool ind1 = false)
Definition at line 909 of file matrix_impl.hpp.
{
     // Erase from sparsity pattern
     std::vector<int> mapping = sparsity_.erase(rr, cc, ind1);
     // Update non-zero entries
     for (int k=0; k<mapping.size(); ++k)
       nonzeros()[k] = nonzeros()[mapping[k]];
     // Truncate nonzero vector
     nonzeros().resize(mapping.size());
   }
template<typename Scalar > void casadi::Matrix< Scalar >::erase (const std::vector< int > & rr, bool ind1 = false)
Definition at line 922 of file matrix_impl.hpp.
{
     // Erase from sparsity pattern
     std::vector<int> mapping = sparsity_.erase(rr, ind1);
     // Update non-zero entries
     for (int k=0; k<mapping.size(); ++k)
       nonzeros()[k] = nonzeros()[mapping[k]];
     // Truncate nonzero vector
     nonzeros().resize(mapping.size());
   }
template<typename Scalar> void casadi::Matrix< Scalar >::expand (const Matrix< Scalar > & x, Matrix< Scalar > & weights, Matrix< Scalar > & terms) static
Functions called by friend functions defined here
Definition at line 2112 of file matrix_impl.hpp.
{
     throw CasadiException("\"expand\" not defined for instantiation");
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::eye (int ncol) static
Definition at line 1239 of file matrix_impl.hpp.
References casadi::Sparsity::diag(), and casadi::GenericMatrix< Matrix< Scalar > >::ones().
{
     return Matrix<Scalar>::ones(Sparsity::diag(n));
   }
std::vector<int> casadi::GenericMatrix< Matrix< Scalar > >::find (bool ind1 = SWIG_IND1) const inline inherited
k = A.find() A[k] will contain the elements of A that are non-zero in B
Definition at line 160 of file generic_matrix.hpp.
 { return sparsity().find(ind1);}
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::gauss_quadrature (const Matrix< Scalar > & f, const Matrix< Scalar > & x, const Matrix< Scalar > & a, const Matrix< Scalar > & b, int order = 5) static
Functions called by friend functions defined here
Definition at line 2175 of file matrix_impl.hpp.
{
     return gauss_quadrature(f, x, a, b, order, Matrix<Scalar>());
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::gauss_quadrature (const Matrix< Scalar > & f, const Matrix< Scalar > & x, const Matrix< Scalar > & a, const Matrix< Scalar > & b, int order, const Matrix< Scalar > & w) static
Functions called by friend functions defined here
Definition at line 2182 of file matrix_impl.hpp.
{
     throw CasadiException("\"gauss_quadrature\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get (Matrix< Scalar > & output_m, bool ind1, const Slice & rr) const
Get a submatrix, single argument
Definition at line 108 of file matrix_impl.hpp.
References casadi::Slice::all(), casadi::Slice::is_scalar(), and casadi::Slice::scalar().
{
     // Scalar
     if (rr.is_scalar(numel())) {
       int r = rr.scalar(numel());
       int k = sparsity().get_nz(r % size1(), r / size1());
       if (k>=0) {
         m = nonzeros().at(k);
       } else {
         m = Matrix<Scalar>(1, 1);
       }
       return;
     }
     // Fall back on IM
     get(m, ind1, rr.all(numel(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get (Matrix< Scalar > & output_m, bool ind1, const Matrix< int > & rr) const
Get a submatrix, single argument
Definition at line 126 of file matrix_impl.hpp.
References casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_row(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), casadi::Sparsity::sub(), casadi::Sparsity::T(), casadi::to_slice(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     // Scalar
     if (rr.is_scalar(true)) {
       return get(m, ind1, to_slice(rr, ind1));
     }
     // If the indexed matrix is dense, use nonzero indexing
     if (is_dense()) {
       return get_nz(m, ind1, rr);
     }
     // Get the sparsity pattern - does bounds checking
     std::vector<int> mapping;
     Sparsity sp = sparsity().sub(rr.nonzeros(), rr.sparsity(), mapping, ind1);
     // If indexed matrix was a row/column vector, make sure that the result is too
     bool tr = (is_column() && rr.is_row()) || (is_row() && rr.is_column());
     // Copy nonzeros
     m = Matrix<Scalar>::zeros(tr ? sp.T() : sp);
     for (int k=0; k<mapping.size(); ++k) m->at(k) = nonzeros().at(mapping[k]);
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get (Matrix< Scalar > & output_m, bool ind1, const Sparsity & sp) const
Get a submatrix, single argument
Definition at line 150 of file matrix_impl.hpp.
References casadi::project(), and casadi::Sparsity::size().
{
     casadi_assert_message(size()==sp.size(),
                           "get(Sparsity sp): shape mismatch. This matrix has shape "
                           << size() << ", but supplied sparsity index has shape "
                           << sp.size() << ".");
     m = project(*this, sp);
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get (Matrix< Scalar > & output_m, bool ind1, const Slice & rr, const Slice & cc) const
Get a submatrix, two arguments
Definition at line 53 of file matrix_impl.hpp.
References casadi::Slice::all(), casadi::Slice::is_scalar(), and casadi::Slice::scalar().
{
     // Both are scalar
     if (rr.is_scalar(size1()) && cc.is_scalar(size2())) {
       int k = sparsity().get_nz(rr.scalar(size1()), cc.scalar(size2()));
       if (k>=0) {
         m = nonzeros().at(k);
       } else {
         m = Matrix<Scalar>(1, 1);
       }
       return;
     }
     // Fall back on IM-IM
     get(m, ind1, rr.all(size1(), ind1), cc.all(size2(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get (Matrix< Scalar > & output_m, bool ind1, const Slice & rr, const Matrix< int > & cc) const
Get a submatrix, two arguments
Definition at line 71 of file matrix_impl.hpp.
References casadi::Slice::all().
{
     // Fall back on IM-IM
     get(m, ind1, rr.all(size1(), ind1), cc);
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get (Matrix< Scalar > & output_m, bool ind1, const Matrix< int > & rr, const Slice & cc) const
Get a submatrix, two arguments
Definition at line 78 of file matrix_impl.hpp.
References casadi::Slice::all().
{
     // Fall back on IM-IM
     get(m, ind1, rr, cc.all(size2(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get (Matrix< Scalar > & output_m, bool ind1, const Matrix< int > & rr, const Matrix< int > & cc) const
Get a submatrix, two arguments
Definition at line 85 of file matrix_impl.hpp.
References casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< MatType >::is_vector(), casadi::Matrix< Scalar >::nonzeros(), casadi::Sparsity::sub(), casadi::to_slice(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     // Scalar
     if (rr.is_scalar(true) && cc.is_scalar(true)) {
       return get(m, ind1, to_slice(rr, ind1), to_slice(cc, ind1));
     }
     // Make sure dense vectors
     casadi_assert_message(rr.is_dense() && rr.is_vector(),
                           "Marix::get: First index must be a dense vector");
     casadi_assert_message(cc.is_dense() && cc.is_vector(),
                           "Marix::get: Second index must be a dense vector");
     // Get the sparsity pattern - does bounds checking
     std::vector<int> mapping;
     Sparsity sp = sparsity().sub(rr.nonzeros(), cc.nonzeros(), mapping, ind1);
     // Copy nonzeros
     m = Matrix<Scalar>::zeros(sp);
     for (int k=0; k<mapping.size(); ++k) m->at(k) = nonzeros().at(mapping[k]);
   }
std::vector<int> casadi::GenericMatrix< Matrix< Scalar > >::get_colind () const inline inherited
Definition at line 144 of file generic_matrix.hpp.
 { return sparsity().get_colind(); }
template<typename Scalar > std::vector< Matrix< Scalar > > casadi::Matrix< Scalar >::get_input (const Function & f) static
Definition at line 2395 of file matrix_impl.hpp.
{
     throw CasadiException("\"get_input\" not defined for " + type_name());
   }
template<typename Scalar> std::vector< A > casadi::Matrix< Scalar >::get_nonzeros () const inline
Definition at line 922 of file matrix.hpp.
 { return nonzeros_;}
template<typename Scalar> template<typename A > std::vector<A> casadi::Matrix< Scalar >::get_nonzeros () const
template<typename Scalar> void casadi::Matrix< Scalar >::get_nz (Matrix< Scalar > & output_m, bool ind1, const Slice & k) const
Get a set of nonzeros
Definition at line 382 of file matrix_impl.hpp.
References casadi::Slice::all(), casadi::Slice::is_scalar(), and casadi::Slice::scalar().
{
     // Scalar
     if (kk.is_scalar(nnz())) {
       m = nonzeros().at(kk.scalar(nnz()));
       return;
     }
     // Fall back on IM
     get_nz(m, ind1, kk.all(nnz(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::get_nz (Matrix< Scalar > & output_m, bool ind1, const Matrix< int > & k) const
Get a set of nonzeros
Definition at line 394 of file matrix_impl.hpp.
References casadi::inBounds(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_row(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), casadi::Sparsity::T(), and casadi::to_slice().
{
     // Scalar
     if (kk.is_scalar(true)) {
       return get_nz(m, ind1, to_slice(kk, ind1));
     }
     // Get nonzeros of kk
     const std::vector<int>& k = kk.nonzeros();
     int sz = nnz();
     // Check bounds
     if (!inBounds(k, -sz+ind1, sz+ind1)) {
       casadi_error("get_nz[kk] out of bounds. Your kk contains "
                    << *std::min_element(k.begin(), k.end()) << " up to "
                    << *std::max_element(k.begin(), k.end())
                    << ", which is outside the range [" << -sz+ind1 << ","<< sz+ind1 <<  ").");
     }
     // If indexed matrix was a row/column vector, make sure that the result is too
     bool tr = (is_column() && kk.is_row()) || (is_row() && kk.is_column());
     // Copy nonzeros
     m = zeros(tr ? kk.sparsity().T() : kk.sparsity());
     for (int el=0; el<k.size(); ++el) {
       casadi_assert_message(!(ind1 && k[el]<=0), "Matlab is 1-based, but requested index " <<
                                                 k[el] <<  ". Note that negative slices are" <<
                                                 " disabled in the Matlab interface. " <<
                                                 "Possibly you may want to use 'end'.");
       int k_el = k[el]-ind1;
       m->at(el) = nonzeros().at(k_el>=0 ? k_el : k_el+sz);
     }
   }
std::vector<int> casadi::GenericMatrix< Matrix< Scalar > >::get_row () const inline inherited
Definition at line 143 of file generic_matrix.hpp.
 { return sparsity().get_row(); }
template<typename Scalar> Sparsity casadi::Matrix< Scalar >::get_sparsity () const inline
Definition at line 820 of file matrix.hpp.
 { return sparsity();}
std::string casadi::PrintableObject< Matrix< Scalar > >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
template<typename Scalar > int casadi::Matrix< Scalar >::getEqualityCheckingDepth () static
Definition at line 1446 of file matrix_impl.hpp.
{
     throw CasadiException("\"getEqualityCheckingDepth\" not defined for instantiation");
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::getMinor (const Matrix< Scalar > & x, int i, int j) static
Functions called by friend functions defined here
Definition at line 1529 of file matrix_impl.hpp.
References casadi::Sparsity::get_col(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::Sparsity::row(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::sparsity().
{
     int n = x.size2();
     casadi_assert_message(n == x.size1(), "getMinor: matrix must be square");
     // Trivial return if scalar
     if (n==1) return 1;
     // Remove col i and row j
     Matrix<Scalar> M = Matrix<Scalar>(n-1, n-1);
     std::vector<int> col = x.sparsity().get_col();
     const int* row = x.sparsity().row();
     for (int k=0; k<x.nnz(); ++k) {
       int i1 = col[k];
       int j1 = row[k];
       if (i1 == i || j1 == j) continue;
       int i2 = (i1<i)?i1:i1-1;
       int j2 = (j1<j)?j1:j1-1;
       M(j2, i2) = x(j1, i1);
     }
     return det(M);
   }
std::string casadi::PrintableObject< Matrix< Scalar > >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::grad (const Function & f, int iind = 0, int oind = 0) static
Definition at line 2406 of file matrix_impl.hpp.
{
     throw CasadiException("\"grad\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::grad (const Function & f, const std::string & iname, int oind = 0) static
Definition at line 2436 of file matrix_impl.hpp.
{
     throw CasadiException("\"grad\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::grad (const Function & f, int iind, const std::string & oname) static
Definition at line 2441 of file matrix_impl.hpp.
{
     throw CasadiException("\"grad\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::grad (const Function & f, const std::string & iname, const std::string & oname) static
Definition at line 2446 of file matrix_impl.hpp.
{
     throw CasadiException("\"grad\" not defined for " + type_name());
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::gradient (const Matrix< Scalar > & f, const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2236 of file matrix_impl.hpp.
{
     casadi_error("\"gradient\" not defined for " + type_name());
     return Matrix<Scalar>();
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::has_duplicates ()
Definition at line 1314 of file matrix_impl.hpp.
{
     throw CasadiException("\"has_duplicates\" not defined for instantiation");
   }
template<typename Scalar> bool casadi::Matrix< Scalar >::has_nz (int rr, int cc) const inline
Definition at line 194 of file matrix.hpp.
Referenced by casadi::Matrix< Scalar >::qr(), and casadi::Matrix< Scalar >::solve().
 { return sparsity().has_nz(rr, cc); }
template<typename Scalar > bool casadi::Matrix< Scalar >::has_zeros () const
Definition at line 1404 of file matrix_impl.hpp.
Referenced by casadi::Matrix< Scalar >::solve().
{
     // Check if the structural nonzero is known to be zero
     for (auto&& e : nonzeros()) if (casadi_limits<Scalar>::is_zero(e)) return true;
     // No known zeros amongst the structurally nonzero entries
     return false;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::heaviside (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 2154 of file matrix_impl.hpp.
References casadi::sign().
{
     return (1+sign(x))/2;
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::hess (const Function & f, int iind = 0, int oind = 0) static
Hessian expression
Definition at line 2468 of file matrix_impl.hpp.
{
     throw CasadiException("'hess' not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::hess (const Function & f, const std::string & iname, int oind = 0) static
Hessian expression
Definition at line 2474 of file matrix_impl.hpp.
{
     throw CasadiException("'hess' not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::hess (const Function & f, int iind, const std::string & oname) static
Hessian expression
Definition at line 2480 of file matrix_impl.hpp.
{
     throw CasadiException("'hess' not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::hess (const Function & f, const std::string & iname, const std::string & oname) static
Hessian expression
Definition at line 2486 of file matrix_impl.hpp.
{
     throw CasadiException("'hess' not defined for " + type_name());
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::hessian (const Matrix< Scalar > & f, const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2250 of file matrix_impl.hpp.
{
     throw CasadiException("\"hessian\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::hessian (const Matrix< Scalar > & f, const Matrix< Scalar > & x, Matrix< Scalar > & g) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2257 of file matrix_impl.hpp.
{
     casadi_error("\"hessian\" not defined for " + type_name());
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::horzcat (const std::vector< Matrix< Scalar > > & v) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1637 of file matrix_impl.hpp.
References casadi::Sparsity::horzcat(), and casadi::GenericMatrix< Matrix< Scalar > >::nnz().
Referenced by casadi::Matrix< Scalar >::qr().
{
     // Concatenate sparsity patterns
     std::vector<Sparsity> sp(v.size());
     for (int i=0; i<v.size(); ++i) sp[i] = v[i].sparsity();
     Matrix<Scalar> ret = zeros(Sparsity::horzcat(sp));
     // Copy nonzeros
     auto i=ret->begin();
     for (auto&& j : v) {
       std::copy(j->begin(), j->end(), i);
       i += j.nnz();
     }
     return ret;
   }
static std::vector<Matrix< Scalar > > casadi::SparsityInterface< Matrix< Scalar > >::horzsplit (const Matrix< Scalar > & x, int incr) static inherited
template<typename Scalar> std::vector< Matrix< Scalar > > casadi::Matrix< Scalar >::horzsplit (const Matrix< Scalar > & x, const std::vector< int > & offset) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1654 of file matrix_impl.hpp.
References casadi::Sparsity::horzsplit(), casadi::Matrix< Scalar >::nonzeros(), and casadi::Matrix< Scalar >::sparsity().
{
     // Split up the sparsity pattern
     std::vector<Sparsity> sp = Sparsity::horzsplit(x.sparsity(), offset);
     // Return object
     std::vector<Matrix<Scalar> > ret;
     ret.reserve(sp.size());
     // Copy data
     auto i=x.nonzeros().begin();
     for (auto&& j : sp) {
       auto i_next = i + j.nnz();
       ret.push_back(Matrix<Scalar>(j, std::vector<Scalar>(i, i_next), false));
       i = i_next;
     }
     // Return the assembled matrix
     casadi_assert(i==x.nonzeros().end());
     return ret;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::if_else (const Matrix< Scalar > & x, const Matrix< Scalar > & if_true, const Matrix< Scalar > & if_false, bool short_circuit) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2134 of file matrix_impl.hpp.
{
     return cond*if_true + !cond*if_false;
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::inf (const Sparsity & sp) static
Definition at line 1244 of file matrix_impl.hpp.
{
     casadi_assert_message(std::numeric_limits<Scalar>::has_infinity,
                           "Datatype cannot represent infinity");
     return Matrix<Scalar>(sp, std::numeric_limits<Scalar>::infinity(), false);
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::inf (int nrow = 1, int ncol = 1) static
Definition at line 1257 of file matrix_impl.hpp.
References casadi::Sparsity::dense(), and casadi::inf.
{
     return inf(Sparsity::dense(nrow, ncol));
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::inf (const std::pair< int, int > & rc) static
Definition at line 1252 of file matrix_impl.hpp.
References casadi::inf.
{
     return inf(rc.first, rc.second);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::inv (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1588 of file matrix_impl.hpp.
{
     // laplace formula
     return adj(x)/det(x);
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::inv_skew (const Matrix< Scalar > & a) static inherited
bool casadi::GenericMatrix< Matrix< Scalar > >::is_column () const inline inherited
Definition at line 133 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::Matrix().
 { return sparsity().is_column();}
template<typename Scalar > bool casadi::Matrix< Scalar >::is_commutative () const
Only defined if symbolic scalar.
Definition at line 1299 of file matrix_impl.hpp.
{
     throw CasadiException("\"is_commutative\" not defined for instantiation");
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::is_constant () const
Definition at line 1333 of file matrix_impl.hpp.
{
     // Look for non-constants
     for (auto&& e : nonzeros()) if (!casadi_limits<Scalar>::is_constant(e)) return false;
     // Constant if we reach this point
     return true;
   }
bool casadi::GenericMatrix< Matrix< Scalar > >::is_dense () const inline inherited
Definition at line 118 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::all(), casadi::Matrix< Scalar >::any(), casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::Matrix(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::Matrix< Scalar >::matrix_scalar(), casadi::Matrix< Scalar >::polyval(), casadi::Matrix< Scalar >::scalar_matrix(), casadi::Matrix< Scalar >::set(), casadi::Matrix< Scalar >::set_nz(), and casadi::Matrix< Scalar >::unary().
 { return sparsity().is_dense();}
bool casadi::GenericMatrix< Matrix< Scalar > >::is_empty (bool both = false) const inline inherited
Definition at line 115 of file generic_matrix.hpp.
 { return sparsity().is_empty(both);}
template<typename Scalar> bool casadi::Matrix< Scalar >::is_equal (const Matrix< Scalar > & x, const Matrix< Scalar > & y, int depth = 0) static
Functions called by friend functions defined for GenericExpression
Definition at line 1383 of file matrix_impl.hpp.
References casadi::is_equal(), casadi::Matrix< Scalar >::nonzeros(), casadi::project(), casadi::GenericMatrix< Matrix< Scalar > >::size(), and casadi::Matrix< Scalar >::sparsity().
{
     // Assert matching dimensions
     casadi_assert_message(x.size() == y.size(), "Dimension mismatch");
     // Project to union of patterns and call recursively if different sparsity
     if (x.sparsity() != y.sparsity()) {
       Sparsity sp = x.sparsity() + y.sparsity();
       return is_equal(project(x, sp), project(y, sp), depth);
     }
     // Check individual elements
     auto y_it = y.nonzeros().begin();
     for (auto&& e : x.nonzeros()) {
       if (!casadi_limits<Scalar>::is_equal(e, *y_it++, depth)) return false;
     }
     // True if reched this point
     return true;
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::is_identity () const
Definition at line 1371 of file matrix_impl.hpp.
Referenced by casadi::Matrix< Scalar >::mac().
{
     // Make sure that the matrix is diagonal
     if (!sparsity().is_diag()) return false;
     // Make sure that all entries are one
     for (auto&& e : nonzeros()) if (!casadi_limits<Scalar>::is_one(e)) return false;
     return true;
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::is_integer () const
Definition at line 1324 of file matrix_impl.hpp.
{
     // Look for non-integers
     for (auto&& e : nonzeros()) if (!casadi_limits<Scalar>::is_integer(e)) return false;
     // Integer if reached this point
     return true;
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::is_leaf () const
Only defined if symbolic scalar.
Definition at line 1294 of file matrix_impl.hpp.
{
     throw CasadiException("\"is_leaf\" not defined for instantiation");
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::is_minus_one () const
Definition at line 1352 of file matrix_impl.hpp.
{
     if (!is_dense()) return false;
     // Look for non-minus-ones
     for (auto&& e : nonzeros()) if (!casadi_limits<Scalar>::is_minus_one(e)) return false;
     return true;
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::is_one () const
Definition at line 1342 of file matrix_impl.hpp.
{
     if (!is_dense()) return false;
     // Look for non-ones
     for (auto&& e : nonzeros()) if (!casadi_limits<Scalar>::is_one(e)) return false;
     return true;
   }
template<typename Scalar > bool casadi::Matrix< Scalar >::is_regular () const
Definition at line 1279 of file matrix_impl.hpp.
References casadi::is_regular().
Referenced by casadi::MX::is_regular().
{
     return casadi::is_regular(nonzeros_);
   }
bool casadi::GenericMatrix< Matrix< Scalar > >::is_row () const inline inherited
Definition at line 130 of file generic_matrix.hpp.
 { return sparsity().is_row();}
bool casadi::GenericMatrix< Matrix< Scalar > >::is_scalar (bool scalar_and_dense = false) const inherited
Referenced by casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::det(), casadi::Matrix< Scalar >::mac(), casadi::Matrix< Scalar >::Matrix(), casadi::Matrix< Scalar >::mldivide(), casadi::Matrix< Scalar >::mpower(), casadi::Matrix< Scalar >::mrdivide(), casadi::Matrix< Scalar >::mtimes(), casadi::Matrix< Scalar >::set(), and casadi::Matrix< Scalar >::set_nz().
template<typename Scalar > bool casadi::Matrix< Scalar >::is_smooth () const
Definition at line 1284 of file matrix_impl.hpp.
{
     return true;
   }
bool casadi::GenericMatrix< Matrix< Scalar > >::is_square () const inline inherited
Definition at line 124 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::trace().
 { return sparsity().is_square();}
template<typename Scalar > bool casadi::Matrix< Scalar >::is_symbolic () const
Definition at line 1304 of file matrix_impl.hpp.
{
     return false;
   }
bool casadi::GenericMatrix< Matrix< Scalar > >::is_tril () const inline inherited
Definition at line 139 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::solve().
 { return sparsity().is_tril();}
bool casadi::GenericMatrix< Matrix< Scalar > >::is_triu () const inline inherited
Definition at line 136 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::solve().
 { return sparsity().is_triu();}
template<typename Scalar > bool casadi::Matrix< Scalar >::is_valid_input () const
Definition at line 1309 of file matrix_impl.hpp.
{
     return false;
   }
bool casadi::GenericMatrix< Matrix< Scalar > >::is_vector () const inline inherited
Definition at line 127 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::norm_2(), and casadi::Matrix< Scalar >::polyval().
 { return sparsity().is_vector();}
template<typename Scalar > bool casadi::Matrix< Scalar >::is_zero () const
Definition at line 1362 of file matrix_impl.hpp.
Referenced by casadi::Matrix< Scalar >::mac().
{
     // Look for non-zeros
     for (auto&& e : nonzeros()) if (!casadi_limits<Scalar>::is_zero(e)) return false;
     return true;
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::jac (const Function & f, int iind = 0, int oind = 0, bool compact = false, bool symmetric = false) static
Definition at line 2400 of file matrix_impl.hpp.
{
     throw CasadiException("\"jac\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::jac (const Function & f, const std::string & iname, int oind = 0, bool compact = false, bool symmetric = false) static
Definition at line 2416 of file matrix_impl.hpp.
{
     throw CasadiException("\"jac\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::jac (const Function & f, int iind, const std::string & oname, bool compact = false, bool symmetric = false) static
Definition at line 2422 of file matrix_impl.hpp.
{
     throw CasadiException("\"jac\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::jac (const Function & f, const std::string & iname, const std::string & oname, bool compact = false, bool symmetric = false) static
Definition at line 2429 of file matrix_impl.hpp.
{
     throw CasadiException("\"jac\" not defined for " + type_name());
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::jacobian (const Matrix< Scalar > & f, const Matrix< Scalar > & x, bool symmetric = false) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2228 of file matrix_impl.hpp.
{
     casadi_error("\"jacobian\" not defined for " + type_name());
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::jtimes (const Matrix< Scalar > & ex, const Matrix< Scalar > & arg, const Matrix< Scalar > & v, bool tr = false) static
Functions called by friend functions defined here
Definition at line 2265 of file matrix_impl.hpp.
{
     casadi_error("\"jtimes\" not defined for " + type_name());
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::kron (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for SparsityInterface
Definition at line 2015 of file matrix_impl.hpp.
References casadi::Sparsity::get_nz(), casadi::GenericMatrix< Matrix< Scalar > >::size(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::sparsity().
{
     const Sparsity &a_sp = a.sparsity();
     Matrix<Scalar> filler = Matrix<Scalar>(b.size());
     std::vector< std::vector< Matrix<Scalar> > >
       blocks(a.size1(), std::vector< Matrix<Scalar> >(a.size2(), filler));
     for (int i=0; i<a.size1(); ++i) {
       for (int j=0; j<a.size2(); ++j) {
         int k = a_sp.get_nz(i, j);
         if (k!=-1) {
           blocks[i][j] = a[k]*b;
         }
       }
     }
     return blockcat(blocks);
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::linspace (const Matrix< Scalar > & a, const Matrix< Scalar > & b, int nsteps) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::mac (const Matrix< Scalar > & x, const Matrix< Scalar > & y, const Matrix< Scalar > & z) static
Functions called by friend functions defined for SparsityInterface
Definition at line 990 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::dim(), casadi::get_ptr(), casadi::Matrix< Scalar >::is_identity(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::Matrix< Scalar >::is_zero(), casadi::mtimes(), casadi::Matrix< Scalar >::ptr(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::sparsity().
{
     if (x.is_scalar() || y.is_scalar()) {
       // Use element-wise multiplication if at least one factor scalar
       return z + x*y;
     }
     // Check matching dimensions
     casadi_assert_message(x.size2()==y.size1(),
                           "Matrix product with incompatible dimensions. Lhs is "
                           << x.dim() << " and rhs is " << y.dim() << ".");
     casadi_assert_message(y.size2()==z.size2(),
                           "Matrix addition with incompatible dimensions. Lhs is "
                           << mtimes(x, y).dim() << " and rhs is " << z.dim() << ".");
     casadi_assert_message(x.size1()==z.size1(),
                           "Matrix addition with incompatible dimensions. Lhs is "
                           << mtimes(x, y).dim() << " and rhs is " << z.dim() << ".");
     // Check if we can simplify the product
     if (x.is_identity()) {
       return y + z;
     } else if (y.is_identity()) {
       return x + z;
     } else if (x.is_zero() || y.is_zero()) {
       return z;
     } else {
       // Carry out the matrix product
       Matrix<Scalar> ret = z;
       std::vector<Scalar> work(x.size1());
       casadi_mtimes(x.ptr(), x.sparsity(), y.ptr(), y.sparsity(),
                     ret.ptr(), ret.sparsity(), get_ptr(work), false);
       return ret;
     }
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::matrix_matrix (int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Definition at line 1150 of file matrix_impl.hpp.
References casadi::Sparsity::combine(), casadi::densify(), casadi::GenericMatrix< Matrix< Scalar > >::dim(), casadi::casadi_math< T >::fun(), casadi::get_ptr(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::Sparsity::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::casadi_math< T >::print(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::sparsity().
{
     if (!(x.size2() == y.size2() && x.size1() == y.size1())) {
       std::stringstream ss;
       casadi_math<Scalar>::print(op, ss, "lhs", "rhs");
       casadi_error("matrix_matrix: dimension mismatch in element-wise matrix operation "
                    << ss.str() <<"." << std::endl << "Left argument has shape " << x.dim()
                    << ", right has shape " << y.dim() << ". They should be equal.");
     }
     // Get the sparsity pattern of the result
     // (ignoring structural zeros giving rise to nonzero result)
     const Sparsity& x_sp = x.sparsity();
     const Sparsity& y_sp = y.sparsity();
     Sparsity r_sp = x_sp.combine(y_sp,
                                         operation_checker<F0XChecker>(op),
                                         operation_checker<FX0Checker>(op));
     // Return value
     Matrix<Scalar> r = zeros(r_sp);
     // Perform the operations elementwise
     if (x_sp==y_sp) {
       // Matching sparsities
       casadi_math<Scalar>::fun(op, get_ptr(x.nonzeros()), get_ptr(y.nonzeros()),
                                  get_ptr(r.nonzeros()), r_sp.nnz());
     } else if (y_sp==r_sp) {
       // Project first argument
       Matrix<Scalar> x_mod = x(r_sp);
       casadi_math<Scalar>::fun(op, get_ptr(x_mod.nonzeros()), get_ptr(y.nonzeros()),
                                  get_ptr(r.nonzeros()), r_sp.nnz());
     } else if (x_sp==r_sp) {
       // Project second argument
       Matrix<Scalar> y_mod = y(r_sp);
       casadi_math<Scalar>::fun(op, get_ptr(x.nonzeros()),
                                  get_ptr(y_mod.nonzeros()), get_ptr(r.nonzeros()), r_sp.nnz());
     } else {
       // Project both arguments
       Matrix<Scalar> x_mod = x(r_sp);
       Matrix<Scalar> y_mod = y(r_sp);
       casadi_math<Scalar>::fun(op, get_ptr(x_mod.nonzeros()), get_ptr(y_mod.nonzeros()),
                                  get_ptr(r.nonzeros()), r_sp.nnz());
     }
     // Handle structural zeros giving rise to nonzero result, e.g. cos(0) == 1
     if (!r.is_dense() && !operation_checker<F00Checker>(op)) {
       // Get the value for the structural zeros
       Scalar fcn_0;
       casadi_math<Scalar>::fun(op, casadi_limits<Scalar>::zero,
                                  casadi_limits<Scalar>::zero, fcn_0);
       r = densify(r, fcn_0);
     }
     return r;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::matrix_scalar (int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Definition at line 1119 of file matrix_impl.hpp.
References casadi::densify(), casadi::casadi_math< T >::fun(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     // Return value
     Matrix<Scalar> ret = Matrix<Scalar>::zeros(x.sparsity());
     // Nonzeros
     std::vector<Scalar>& ret_data = ret.nonzeros();
     const std::vector<Scalar>& x_data = x.nonzeros();
     const std::vector<Scalar>& y_data = y.nonzeros();
     const Scalar& y_val = y_data.empty() ? casadi_limits<Scalar>::zero : y->front();
     // Do the operation on all non-zero elements
     for (int el=0; el<x.nnz(); ++el) {
       casadi_math<Scalar>::fun(op, x_data[el], y_val, ret_data[el]);
     }
     // Check the value of the structural zero-entries, if there are any
     if (!x.is_dense() && !operation_checker<F0XChecker>(op)) {
       // Get the value for the structural zeros
       Scalar fcn_0;
       casadi_math<Scalar>::fun(op, casadi_limits<Scalar>::zero, y_val, fcn_0);
       if (!casadi_limits<Scalar>::is_zero(fcn_0)) { // Remove this if?
         ret = densify(ret, fcn_0);
       }
     }
     return ret;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::mldivide (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 890 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_scalar().
{
     casadi_assert_message(a.is_scalar() || b.is_scalar(), "Not implemented");
     return b/a;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::mpower (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 897 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_scalar().
{
     casadi_assert_message(a.is_scalar() || b.is_scalar(), "Not implemented");
     return pow(a, b);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::mrdivide (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
Definition at line 883 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_scalar().
{
     casadi_assert_message(a.is_scalar() || b.is_scalar(), "Not implemented");
     return a/b;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::mtaylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, int order) static
Functions called by friend functions defined here
Definition at line 2289 of file matrix_impl.hpp.
{
     throw CasadiException("\"mtaylor\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::mtaylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, int order, const std::vector< int > & order_contributions) static
Functions called by friend functions defined here
Definition at line 2297 of file matrix_impl.hpp.
{
     throw CasadiException("\"mtaylor\" not defined for instantiation");
     return Matrix<Scalar>();
   }
static Matrix< Scalar > casadi::SparsityInterface< Matrix< Scalar > >::mtimes (const std::vector< Matrix< Scalar > > & args) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::mtimes (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for SparsityInterface
Definition at line 979 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::Sparsity::mtimes(), casadi::Matrix< Scalar >::sparsity(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     if (x.is_scalar() || y.is_scalar()) {
       // Use element-wise multiplication if at least one factor scalar
       return x*y;
     } else {
       Matrix<Scalar> z = Matrix<Scalar>::zeros(Sparsity::mtimes(x.sparsity(), y.sparsity()));
       return mac(x, y, z);
     }
   }
template<typename Scalar > int casadi::Matrix< Scalar >::n_dep () const
Definition at line 1423 of file matrix_impl.hpp.
{
     throw CasadiException("\"n_dep\" not defined for instantiation");
   }
template<typename Scalar> int casadi::Matrix< Scalar >::n_nodes (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2306 of file matrix_impl.hpp.
Referenced by casadi::Function::n_nodes().
{
     throw CasadiException("\"n_nodes\" not defined for instantiation");
     return 0;
   }
template<typename Scalar > std::string casadi::Matrix< Scalar >::name () const
Definition at line 1413 of file matrix_impl.hpp.
{
     throw CasadiException("\"name\" not defined for instantiation");
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::nan (const Sparsity & sp) static
Definition at line 1262 of file matrix_impl.hpp.
{
     casadi_assert_message(std::numeric_limits<Scalar>::has_quiet_NaN,
                           "Datatype cannot represent not-a-number");
     return Matrix<Scalar>(sp, std::numeric_limits<Scalar>::quiet_NaN(), false);
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::nan (int nrow = 1, int ncol = 1) static
Definition at line 1274 of file matrix_impl.hpp.
References casadi::Sparsity::dense(), and casadi::nan.
{
     return nan(Sparsity::dense(nrow, ncol));
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::nan (const std::pair< int, int > & rc) static
Definition at line 1269 of file matrix_impl.hpp.
References casadi::nan.
{
     return nan(rc.first, rc.second);
   }
template<typename Scalar> std::vector< bool > casadi::Matrix< Scalar >::nl_var (const Matrix< Scalar > & expr, const Matrix< Scalar > & var) static
Functions called by friend functions defined here
Definition at line 2275 of file matrix_impl.hpp.
{
     casadi_error("\"nl_var\" not defined for " + type_name());
     return std::vector<bool>();
   }
int casadi::GenericMatrix< Matrix< Scalar > >::nnz () const inherited
Referenced by casadi::Matrix< Scalar >::all(), casadi::Matrix< Scalar >::any(), casadi::Matrix< Scalar >::det(), casadi::Matrix< Scalar >::dot(), casadi::Matrix< Scalar >::getMinor(), casadi::Matrix< Scalar >::horzcat(), casadi::Matrix< Scalar >::matrix_scalar(), casadi::Matrix< Scalar >::polyval(), casadi::Matrix< Scalar >::scalar_matrix(), casadi::Matrix< Scalar >::triplet(), casadi::Matrix< Scalar >::unary(), and casadi::Matrix< Scalar >::unite().
int casadi::GenericMatrix< Matrix< Scalar > >::nnz_diag () const inherited
int casadi::GenericMatrix< Matrix< Scalar > >::nnz_lower () const inherited
int casadi::GenericMatrix< Matrix< Scalar > >::nnz_upper () const inherited
template<typename Scalar> std::vector<Scalar>& casadi::Matrix< Scalar >::nonzeros () inline
Access the non-zero elements
Definition at line 802 of file matrix.hpp.
Referenced by casadi::ConstantMX::create(), casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::det(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::Matrix< Scalar >::get_nz(), casadi::MX::get_nz(), casadi::Matrix< Scalar >::horzsplit(), casadi::QpToNlp::init(), casadi::Matrix< Scalar >::is_equal(), casadi::is_slice(), casadi::Matrix< Scalar >::Matrix(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::Matrix< Scalar >::matrix_scalar(), casadi::Matrix< Scalar >::norm_inf(), casadi::Matrix< Scalar >::reshape(), casadi::Matrix< Scalar >::scalar_matrix(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::SnoptInterface::solve(), casadi::Matrix< Scalar >::solve(), casadi::Matrix< Scalar >::sparsify(), casadi::to_slice(), casadi::Matrix< Scalar >::unary(), casadi::Matrix< Scalar >::unite(), and casadi::SnoptInterface::userfun().
 { return nonzeros_;}
template<typename Scalar> const std::vector<Scalar>& casadi::Matrix< Scalar >::nonzeros () const inline
Access the non-zero elements
Definition at line 803 of file matrix.hpp.
 { return nonzeros_;}
static int casadi::GenericMatrix< Matrix< Scalar > >::norm_0_mul (const Matrix< Scalar > & x, const Matrix< Scalar > & y) inline static inherited
Definition at line 176 of file generic_matrix.hpp.
{
       return Sparsity::norm_0_mul(x.sparsity(), y.sparsity());
     }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::norm_1 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1752 of file matrix_impl.hpp.
References casadi::dot(), casadi::fabs(), and casadi::Matrix< Scalar >::sparsity().
{
     return dot(fabs(x), Matrix<Scalar>::ones(x.sparsity()));
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::norm_2 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1757 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_vector().
{
     if (x.is_vector()) {
       return norm_F(x);
     } else {
       casadi_error("2-norms currently only supported for vectors. "
                    "Did you intend to calculate a Frobenius norms (norm_F)?");
     }
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::norm_F (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1767 of file matrix_impl.hpp.
{
     return sqrt(sum_square(x));
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::norm_inf (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1772 of file matrix_impl.hpp.
References casadi::fabs(), casadi::fmax(), and casadi::Matrix< Scalar >::nonzeros().
{
     // Get largest element by absolute value
     Matrix<Scalar> s = 0;
     for (auto i=x.nonzeros().begin(); i!=x.nonzeros().end(); ++i) {
       s = fmax(s, fabs(Matrix<Scalar>(*i)));
     }
     return s;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::norm_inf_mul (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined here
Definition at line 2097 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::dim(), casadi::get_ptr(), casadi::Matrix< Scalar >::ptr(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::sparsity().
{
     casadi_assert_message(y.size1()==x.size2(), "Dimension error. Got " << x.dim()
                           << " times " << y.dim() << ".");
     // Allocate work vectors
     std::vector<Scalar> dwork(x.size1());
     std::vector<int> iwork(x.size1()+1+y.size2());
     // Call C runtime
     return casadi_norm_inf_mul(x.ptr(), x.sparsity(), y.ptr(), y.sparsity(),
                                get_ptr(dwork), get_ptr(iwork));
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::nullspace (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1822 of file matrix_impl.hpp.
References casadi::copysign(), casadi::GenericMatrix< Matrix< Scalar > >::dim(), casadi::Matrix< double >::eye(), casadi::mtimes(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::T().
{
     Matrix<Scalar> X = A;
     int n = X.size1();
     int m = X.size2();
     casadi_assert_message(m>=n, "nullspace(): expecting a flat matrix (more columns than rows), "
                           "but got " << X.dim() << ".");
     Matrix<Scalar> seed = DM::eye(m)(Slice(0, m), Slice(n, m));
     std::vector< Matrix<Scalar> > us;
     std::vector< Matrix<Scalar> > betas;
     Matrix<Scalar> beta;
     for (int i=0;i<n;++i) {
       Matrix<Scalar> x = X(i, Slice(i, m));
       Matrix<Scalar> u = Matrix<Scalar>(x);
       Matrix<Scalar> sigma = sqrt(sum2(x*x));
       const Matrix<Scalar>& x0 = x(0, 0);
       u(0, 0) = 1;
       Matrix<Scalar> b = -copysign(sigma, x0);
       u(Slice(0), Slice(1, m-i))*= 1/(x0-b);
       beta = 1-x0/b;
       X(Slice(i, n), Slice(i, m)) -=
         beta*mtimes(mtimes(X(Slice(i, n), Slice(i, m)), u.T()), u);
       us.push_back(u);
       betas.push_back(beta);
     }
     for (int i=n-1;i>=0;--i) {
       seed(Slice(i, m), Slice(0, m-n)) -=
         betas[i]*mtimes(us[i].T(), mtimes(us[i], seed(Slice(i, m), Slice(0, m-n))));
     }
     return seed;
   }
int casadi::GenericMatrix< Matrix< Scalar > >::numel () const inherited
Referenced by casadi::Matrix< Scalar >::binary(), casadi::Matrix< Scalar >::Matrix(), and casadi::Matrix< Scalar >::polyval().
int casadi::GenericMatrix< Matrix< Scalar > >::numel (int i) const inline inherited
Definition at line 94 of file generic_matrix.hpp.
 { return 1;}
static std::vector<int> casadi::SparsityInterface< Matrix< Scalar > >::offset (const std::vector< Matrix< Scalar > > & v, bool vert = true) static inherited
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::ones (int nrow = 1, int ncol = 1) inline static inherited
Definition at line 658 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::eye().
 { return ones(Sparsity::dense(nrow, ncol)); }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::ones (const Sparsity & sp) inline static inherited
Definition at line 659 of file generic_matrix.hpp.
 { return MatType(sp, 1, false);}
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::ones (const std::pair< int, int > & rc) inline static inherited
Definition at line 660 of file generic_matrix.hpp.
 { return ones(rc.first, rc.second);}
template<typename Scalar > casadi::Matrix< Scalar >::operator double () const explicit
Definition at line 2492 of file matrix_impl.hpp.
{
     casadi_assert(is_scalar());
     return static_cast<double>(scalar());
   }
template<typename Scalar > casadi::Matrix< Scalar >::operator int () const explicit
Definition at line 2524 of file matrix_impl.hpp.
{
     casadi_assert(is_scalar());
     return static_cast<int>(scalar());
   }
template<typename Scalar > template<typename A > casadi::Matrix< Scalar >::operator std::vector< A > () const explicit
Definition at line 2508 of file matrix_impl.hpp.
{
     // Get sparsity pattern
     int size1 = this->size1(), size2 = this->size2();
     const int *colind = this->colind(), *row = this->row();
     // Copy the nonzeros
     auto it = nonzeros().begin();
     std::vector<A> ret(numel(), 0);
     for (int cc=0; cc<size2; ++cc) {
       for (int el=colind[cc]; el<colind[cc+1]; ++el) {
         ret[row[el] + cc*size1] = static_cast<A>(*it++);
       }
     }
     return ret;
   }
Matrix< Scalar > casadi::GenericExpression< Matrix< Scalar > >::operator! () const inline inherited
Definition at line 325 of file generic_expression.hpp.
{
       return ExType::unary(OP_NOT, self());
     }
const Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr) const inline inherited
Definition at line 212 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr);
       return ret;
     }
const Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr, const CC & cc) const inline inherited
Definition at line 220 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr, cc);
       return ret;
     }
SubIndex<Matrix< Scalar > , RR> casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr) inline inherited
Definition at line 228 of file generic_matrix.hpp.
{
       return SubIndex<MatType, RR>(self(), rr);
     }
SubMatrix<Matrix< Scalar > , RR, CC> casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr, const CC & cc) inline inherited
Definition at line 234 of file generic_matrix.hpp.
{
       return SubMatrix<MatType, RR, CC>(self(), rr, cc);
     }
Matrix< Scalar > & casadi::GenericExpression< Matrix< Scalar > >::operator*= (const Matrix< Scalar > & y) inline inherited
Definition at line 316 of file generic_expression.hpp.
 {return self() = self() * y;}
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::operator+ () const
Definition at line 878 of file matrix_impl.hpp.
{
     return *this;
   }
Matrix< Scalar > & casadi::GenericExpression< Matrix< Scalar > >::operator+= (const Matrix< Scalar > & y) inline inherited
Definition at line 310 of file generic_expression.hpp.
 { return self() = self() + y; }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::operator- () const
Definition at line 873 of file matrix_impl.hpp.
References casadi::OP_NEG.
{
     return unary(OP_NEG, *this);
   }
Matrix< Scalar > & casadi::GenericExpression< Matrix< Scalar > >::operator-= (const Matrix< Scalar > & y) inline inherited
Definition at line 313 of file generic_expression.hpp.
 { return self() = self() - y; }
template<typename Scalar> std::vector<Scalar>* casadi::Matrix< Scalar >::operator-> () inline
Definition at line 107 of file matrix.hpp.
 { return &nonzeros_;}
template<typename Scalar> const std::vector<Scalar>* casadi::Matrix< Scalar >::operator-> () const inline
Definition at line 110 of file matrix.hpp.
 { return &nonzeros_;}
Matrix< Scalar > & casadi::GenericExpression< Matrix< Scalar > >::operator/= (const Matrix< Scalar > & y) inline inherited
Definition at line 319 of file generic_expression.hpp.
 {return self() = self() / y;}
template<typename Scalar> Matrix< Scalar > & casadi::Matrix< Scalar >::operator= (const Matrix< Scalar > & m)
Definition at line 538 of file matrix_impl.hpp.
{
     sparsity_ = m.sparsity_;
     nonzeros_ = m.nonzeros_;
     return *this;
   }
const Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::operator[] (const K & k) const inline inherited
Definition at line 198 of file generic_matrix.hpp.
{
       MatType ret;
       self().get_nz(ret, false, k);
       return ret;
     }
NonZeros<Matrix< Scalar > , K> casadi::GenericMatrix< Matrix< Scalar > >::operator[] (const K & k) inline inherited
Definition at line 206 of file generic_matrix.hpp.
{
       return NonZeros<MatType, K>(self(), k);
     }
template<> Matrix< double > casadi::Matrix< double >::pinv (const Matrix< double > & A, const string & lsolver, const Dict & dict)
Definition at line 61 of file matrix.cpp.
References casadi::mtimes(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), and casadi::Matrix< Scalar >::T().
{
     if (A.size1()>=A.size2()) {
       return solve(mtimes(A.T(), A), A.T(), lsolver, dict);
     } else {
       return solve(mtimes(A, A.T()), A, lsolver, dict).T();
     }
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::pinv (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1999 of file matrix_impl.hpp.
References casadi::mtimes(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::T().
{
     if (A.size2()>=A.size1()) {
       return solve(mtimes(A, A.T()), A).T();
     } else {
       return solve(mtimes(A.T(), A), A.T());
     }
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::pinv (const Matrix< Scalar > & A, const std::string & lsolver, const Dict & opts) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2009 of file matrix_impl.hpp.
{
     throw CasadiException("\"solve\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<> CASADI_EXPORT Matrix< double > casadi::Matrix< double >::pinv (const Matrix< double > & A, const std::string & lsolver, const Dict & dict)
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::poly_coeff (const Matrix< Scalar > & ex, const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 2335 of file matrix_impl.hpp.
{
     throw CasadiException("\"poly_coeff\" not defined for instantiation");
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::poly_roots (const Matrix< Scalar > & p) static
Functions called by friend functions defined here
Definition at line 2341 of file matrix_impl.hpp.
{
     throw CasadiException("\"poly_roots\" not defined for instantiation");
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::polyval (const Matrix< Scalar > & p, const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2086 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< Matrix< Scalar > >::is_vector(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::GenericMatrix< Matrix< Scalar > >::numel(), and casadi::Matrix< Scalar >::ptr().
{
     casadi_assert_message(p.is_dense(), "polynomial coefficients vector must be dense");
     casadi_assert_message(p.is_vector() && p.nnz()>0, "polynomial coefficients must be a vector");
     Matrix<Scalar> ret = x;
     for (auto&& e : ret.nonzeros()) {
       e = casadi_polyval(p.ptr(), p.numel()-1, e);
     }
     return ret;
   }
template<typename Scalar > void casadi::Matrix< Scalar >::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 725 of file matrix_impl.hpp.
{
     if (is_empty()) {
       stream << "[]";
     } else if (numel()==1) {
       print_scalar(stream, false);
     } else if (is_column()) {
       print_vector(stream, false);
     } else if (std::max(size1(), size2())<=10 || static_cast<double>(nnz())/numel()>=0.5) {
       // if "small" or "dense"
       print_dense(stream, false);
     } else {
       print_sparse(stream, false);
     }
     if (trailing_newline) stream << std::endl;
   }
template<typename Scalar > void casadi::Matrix< Scalar >::print_dense (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 616 of file matrix_impl.hpp.
{
     // Print as a single line
     bool oneliner=this->size1()<=1;
     // Get components
     std::vector<std::string> nz, inter;
     print_split(nz, inter);
     // Print intermediate expressions
     for (int i=0; i<inter.size(); ++i)
       stream << "@" << (i+1) << "=" << inter[i] << ", ";
     inter.clear();
     // Index counter for each column
     const int* cptr = this->colind();
     int ncol = size2();
     std::vector<int> cind(cptr, cptr+ncol+1);
     // Loop over rows
     for (int rr=0; rr<size1(); ++rr) {
       // Beginning of row
       if (rr==0) {
         if (!oneliner) stream << std::endl;
         stream << "[[";
       } else {
         stream << " [";
       }
       // Loop over columns
       for (int cc=0; cc<ncol; ++cc) {
         // Separating comma
         if (cc>0) stream << ", ";
         // Check if nonzero
         if (cind[cc]<colind(cc+1) && row(cind[cc])==rr) {
           stream << nz.at(cind[cc]++);
         } else {
           stream << "00";
         }
       }
       // End of row
       if (rr<size1()-1) {
         stream << "], ";
         if (!oneliner) stream << std::endl;
       } else {
         stream << "]]";
       }
     }
     if (trailing_newline) stream << std::endl;
     stream << std::flush;
   }
template<typename Scalar> std::string casadi::Matrix< Scalar >::print_operator (const Matrix< Scalar > & x, const std::vector< std::string > & args) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2313 of file matrix_impl.hpp.
{
     throw CasadiException("\"print_operator\" not defined for instantiation");
     return std::string();
   }
template<typename Scalar > void casadi::Matrix< Scalar >::print_scalar (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 548 of file matrix_impl.hpp.
{
     casadi_assert_message(numel()==1, "Not a scalar");
     std::streamsize precision = stream.precision();
     std::streamsize width = stream.width();
     std::ios_base::fmtflags flags = stream.flags();
     stream.precision(stream_precision_);
     stream.width(stream_width_);
     if (stream_scientific_) {
       stream.setf(std::ios::scientific);
     } else {
       stream.unsetf(std::ios::scientific);
     }
     if (nnz()==0) {
       stream << "00";
     } else {
       stream << scalar();
     }
     if (trailing_newline) stream << std::endl;
     stream << std::flush;
     stream.precision(precision);
     stream.width(width);
     stream.flags(flags);
   }
template<typename Scalar > void casadi::Matrix< Scalar >::print_sparse (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 671 of file matrix_impl.hpp.
References casadi::InterruptHandler::check().
Referenced by casadi::CsparseInterface::linsol_factorize().
{
     if (nnz()==0) {
       stream << "all zero sparse: " << size1() << "-by-" << size2();
     } else {
       // Print header
       stream << "sparse: " << size1() << "-by-" << size2() << ", " << nnz() << " nnz";
       // Get components
       std::vector<std::string> nz, inter;
       print_split(nz, inter);
       // Print intermediate expressions
       for (int i=0; i<inter.size(); ++i)
         stream << std::endl << " @" << (i+1) << "=" << inter[i] << ",";
       inter.clear();
       // Print nonzeros
       for (int cc=0; cc<size2(); ++cc) {
         for (int el=colind(cc); el<colind(cc+1); ++el) {
           int rr=row(el);
           stream << std::endl << " (" << rr << ", " << cc << ") -> " << nz.at(el);
           InterruptHandler::check();
         }
       }
     }
     if (trailing_newline) stream << std::endl;
     stream << std::flush;
   }
template<typename Scalar > void casadi::Matrix< Scalar >::print_split (std::vector< std::string > & output_nz, std::vector< std::string > & output_inter) const
Definition at line 701 of file matrix_impl.hpp.
{
     nz.resize(nnz());
     inter.resize(0);
     // Temporary
     std::stringstream ss;
     ss.precision(stream_precision_);
     ss.width(stream_width_);
     if (stream_scientific_) {
       ss.setf(std::ios::scientific);
     } else {
       ss.unsetf(std::ios::scientific);
     }
     // Print nonzeros
     for (int i=0; i<nz.size(); ++i) {
       ss.str(std::string());
       ss << nonzeros().at(i);
       nz[i] = ss.str();
     }
   }
template<typename Scalar > void casadi::Matrix< Scalar >::print_vector (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 577 of file matrix_impl.hpp.
{
     casadi_assert_message(is_column(), "Not a vector");
     // Get components
     std::vector<std::string> nz, inter;
     print_split(nz, inter);
     // Print intermediate expressions
     for (int i=0; i<inter.size(); ++i)
       stream << "@" << (i+1) << "=" << inter[i] << ", ";
     inter.clear();
     // Access data structures
     const int* r = row();
     int sz = nnz();
     // Nonzero
     int el=0;
     // Loop over rows
     stream << "[";
     for (int rr=0; rr<size1(); ++rr) {
       // Add delimiter
       if (rr!=0) stream << ", ";
       // Check if nonzero
       if (el<sz && rr==r[el]) {
         stream << nz.at(el++);
       } else {
         stream << "00";
       }
     }
     stream << "]";
     if (trailing_newline) stream << std::endl;
     stream << std::flush;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::printme (const Matrix< Scalar > & y) const
Definition at line 904 of file matrix_impl.hpp.
References casadi::OP_PRINTME.
{
     return binary(OP_PRINTME, *this, y);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::project (const Matrix< Scalar > & x, const Sparsity & sp, bool intersect = false) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1428 of file matrix_impl.hpp.
References casadi::get_ptr(), casadi::Sparsity::intersect(), casadi::project(), casadi::Matrix< Scalar >::ptr(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::Matrix< Scalar >::sparsity(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     if (intersect) {
       return project(x, sp.intersect(x.sparsity()), false);
     } else {
       Matrix<Scalar> ret = Matrix<Scalar>::zeros(sp);
       std::vector<Scalar> w(x.size1());
       casadi_project(x.ptr(), x.sparsity(), ret.ptr(), sp, get_ptr(w));
       return ret;
     }
   }
template<typename Scalar> Scalar* casadi::Matrix< Scalar >::ptr () inline
Get a pointer to the data
Definition at line 808 of file matrix.hpp.
Referenced by casadi::Matrix< Scalar >::_bilin(), casadi::Matrix< Scalar >::_rank1(), casadi::Matrix< Scalar >::dot(), casadi::Linsol::linsol_spsolve(), casadi::Matrix< Scalar >::mac(), casadi::Matrix< Scalar >::norm_inf_mul(), casadi::Matrix< Scalar >::polyval(), casadi::Matrix< Scalar >::project(), and casadi::Matrix< Scalar >::trace().
 { return nonzeros_.empty() ? 0 : &nonzeros_.front(); }
template<typename Scalar> const Scalar* casadi::Matrix< Scalar >::ptr () const inline
Get a pointer to the data
Definition at line 809 of file matrix.hpp.
 { return nonzeros_.empty() ? 0 : &nonzeros_.front(); }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::pw_const (const Matrix< Scalar > & t, const Matrix< Scalar > & tval, const Matrix< Scalar > & val) static
Functions called by friend functions defined here
Definition at line 2118 of file matrix_impl.hpp.
{
     throw CasadiException("\"pw_const\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::pw_lin (const Matrix< Scalar > & t, const Matrix< Scalar > & tval, const Matrix< Scalar > & val) static
Functions called by friend functions defined here
Definition at line 2126 of file matrix_impl.hpp.
{
     throw CasadiException("\"pw_lin\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<typename Scalar> void casadi::Matrix< Scalar >::qr (const Matrix< Scalar > & A, Matrix< Scalar > & Q, Matrix< Scalar > & R) static
Functions called by friend functions defined here
Definition at line 1782 of file matrix_impl.hpp.
References casadi::Matrix< Scalar >::has_nz(), casadi::Matrix< Scalar >::horzcat(), casadi::mtimes(), casadi::norm_2(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), and casadi::Matrix< Scalar >::T().
{
     // The following algorithm is taken from J. Demmel:
     // Applied Numerical Linear Algebra (algorithm 3.1.)
     casadi_assert_message(A.size1()>=A.size2(), "qr: fewer rows than columns");
     // compute Q and R column by column
     Q = R = Matrix<Scalar>();
     for (int i=0; i<A.size2(); ++i) {
       // Initialize qi to be the i-th column of *this
       Matrix<Scalar> ai = A(Slice(), i);
       Matrix<Scalar> qi = ai;
       // The i-th column of R
       Matrix<Scalar> ri = Matrix<Scalar>(A.size2(), 1);
       // subtract the projection of qi in the previous directions from ai
       for (int j=0; j<i; ++j) {
         // Get the j-th column of Q
         Matrix<Scalar> qj = Q(Slice(), j);
         ri(j, 0) = mtimes(qi.T(), qj); // Modified Gram-Schmidt
         // ri[j] = dot(qj, ai); // Classical Gram-Schmidt
         // Remove projection in direction j
         if (ri.has_nz(j, 0))
           qi -= ri(j, 0) * qj;
       }
       // Normalize qi
       ri(i, 0) = norm_2(qi);
       qi /= ri(i, 0);
       // Update R and Q
       Q = Matrix<Scalar>::horzcat({Q, qi});
       R = Matrix<Scalar>::horzcat({R, ri});
     }
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::ramp (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 2169 of file matrix_impl.hpp.
{
     return x*heaviside(x);
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::rank1 (const Matrix< Scalar > & A, const Matrix< Scalar > & alpha, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::rectangle (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 2159 of file matrix_impl.hpp.
References casadi::sign().
{
     return 0.5*(sign(x+0.5)-sign(x-0.5));
   }
template<typename Scalar > void casadi::Matrix< Scalar >::remove (const std::vector< int > & rr, const std::vector< int > & cc)
Definition at line 935 of file matrix_impl.hpp.
References casadi::complement(), and casadi::inBounds().
{
     if (!inBounds(rr, size1())) {
       casadi_error("Remove(rr, cc) out of bounds. Your rr contains "
                    << *std::min_element(rr.begin(), rr.end()) << " up to "
                    << *std::max_element(rr.begin(), rr.end())
                    << ", which is outside of the matrix shape " << dim() << ".");
     }
     if (!inBounds(cc, size2())) {
       casadi_error("Remove(rr, cc) out of bounds. Your cc contains "
                    << *std::min_element(cc.begin(), cc.end()) << " up to "
                    << *std::max_element(cc.begin(), cc.end())
                    << ", which is outside of the matrix shape " << dim() << ".");
     }
     // Remove by performing a complementary slice
     std::vector<int> rrc = complement(rr, size1());
     std::vector<int> ccc = complement(cc, size2());
     Matrix<Scalar> ret = (*this)(rrc, ccc);
     operator=(ret);
   }
static Matrix< Scalar > casadi::SparsityInterface< Matrix< Scalar > >::repmat (const Matrix< Scalar > & x, int n, int m = 1) static inherited
static Matrix< Scalar > casadi::SparsityInterface< Matrix< Scalar > >::repmat (const Matrix< Scalar > & A, const std::pair< int, int > & rc) inline static inherited
Definition at line 179 of file sparsity_interface.hpp.
{
       return MatType::repmat(A, rc.first, rc.second);
     }
template<typename Scalar > void casadi::Matrix< Scalar >::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const
Definition at line 742 of file matrix_impl.hpp.
References casadi::print().
{
     stream << type_name() << "(";
     print(stream, false);
     stream << ")";
     if (trailing_newline) stream << std::endl;
     stream << std::flush;
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::repsum (const Matrix< Scalar > & x, int n, int m = 1) static inherited
template<typename Scalar > void casadi::Matrix< Scalar >::reserve (int nnz)
Definition at line 751 of file matrix_impl.hpp.
{
     reserve(nnz, size2());
   }
template<typename Scalar > void casadi::Matrix< Scalar >::reserve (int nnz, int ncol)
Definition at line 756 of file matrix_impl.hpp.
{
     nonzeros().reserve(nnz);
   }
template<typename Scalar > void casadi::Matrix< Scalar >::resetInput ()
Definition at line 1319 of file matrix_impl.hpp.
{
     throw CasadiException("\"resetInput\" not defined for instantiation");
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::reshape (const Matrix< Scalar > & x, int nrow, int ncol) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1594 of file matrix_impl.hpp.
References casadi::Matrix< Scalar >::nonzeros(), casadi::Sparsity::reshape(), and casadi::Matrix< Scalar >::sparsity().
{
     Sparsity sp = Sparsity::reshape(x.sparsity(), nrow, ncol);
     return Matrix<Scalar>(sp, x.nonzeros(), false);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::reshape (const Matrix< Scalar > & x, const Sparsity & sp) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1600 of file matrix_impl.hpp.
References casadi::Sparsity::isReshape(), casadi::Matrix< Scalar >::nonzeros(), and casadi::Matrix< Scalar >::sparsity().
{
     // quick return if already the right shape
     if (sp==x.sparsity()) return x;
     // make sure that the patterns match
     casadi_assert(sp.isReshape(x.sparsity()));
     return Matrix<Scalar>(sp, x.nonzeros(), false);
   }
template<typename Scalar > void casadi::Matrix< Scalar >::resize (int nrow, int ncol)
Definition at line 761 of file matrix_impl.hpp.
Referenced by casadi::FixedStepIntegrator::init_memory().
{
     sparsity_.resize(nrow, ncol);
   }
const int* casadi::GenericMatrix< Matrix< Scalar > >::row () const inline inherited
Definition at line 146 of file generic_matrix.hpp.
Referenced by casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::det(), casadi::Matrix< Scalar >::set(), casadi::Matrix< Scalar >::solve(), casadi::Matrix< Scalar >::sparsify(), and casadi::Matrix< Scalar >::trace().
 { return sparsity().row(); }
int casadi::GenericMatrix< Matrix< Scalar > >::row (int el) const inline inherited
Definition at line 149 of file generic_matrix.hpp.
 { return sparsity().row(el); }
template<typename Scalar > void casadi::Matrix< Scalar >::sanity_check (bool complete = false) const
Parameters
complete set to true to also check elementwise throws an error as possible result
Definition at line 966 of file matrix_impl.hpp.
{
     sparsity_.sanity_check(complete);
     if (nonzeros_.size()!=sparsity_.nnz()) {
       std::stringstream s;
       s << "Matrix is not sane. The following must hold:" << std::endl;
       s << "  nonzeros().size() = sparsity().nnz(), but got nonzeros().size()  = "
         << nonzeros_.size()
         << "   and sparsity().nnz() = "  << sparsity_.nnz() << std::endl;
       casadi_error(s.str());
     }
   }
template<typename Scalar > const Scalar casadi::Matrix< Scalar >::scalar () const
Definition at line 1064 of file matrix_impl.hpp.
Referenced by casadi::ConstantMX::create(), casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::Matrix(), casadi::Matrix< Scalar >::set(), casadi::Matrix< Scalar >::set_nz(), and casadi::to_slice().
{
     // Make sure that the matrix is 1-by-1
     casadi_assert_message(is_scalar(), "Can only convert 1-by-1 matrices to scalars");
     // return zero or the nonzero element
     if (nnz()==1)
       return nonzeros()[0];
     else
       return casadi_limits<Scalar>::zero;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::scalar_matrix (int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Definition at line 1088 of file matrix_impl.hpp.
References casadi::densify(), casadi::casadi_math< T >::fun(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     // Return value
     Matrix<Scalar> ret = Matrix<Scalar>::zeros(y.sparsity());
     // Nonzeros
     std::vector<Scalar>& ret_data = ret.nonzeros();
     const std::vector<Scalar>& x_data = x.nonzeros();
     const Scalar& x_val = x_data.empty() ? casadi_limits<Scalar>::zero : x->front();
     const std::vector<Scalar>& y_data = y.nonzeros();
     // Do the operation on all non-zero elements
     for (int el=0; el<y.nnz(); ++el) {
       casadi_math<Scalar>::fun(op, x_val, y_data[el], ret_data[el]);
     }
     // Check the value of the structural zero-entries, if there are any
     if (!y.is_dense() && !operation_checker<FX0Checker>(op)) {
       // Get the value for the structural zeros
       Scalar fcn_0;
       casadi_math<Scalar>::fun(op, x_val, casadi_limits<Scalar>::zero, fcn_0);
       if (!casadi_limits<Scalar>::is_zero(fcn_0)) { // Remove this if?
         ret = densify(ret, fcn_0);
       }
     }
     return ret;
   }
const Matrix< Scalar > & casadi::GenericExpression< Matrix< Scalar > >::self () const inline protected inherited
Definition at line 51 of file generic_expression.hpp.
 { return static_cast<const ExType&>(*this); }
const Matrix< Scalar > & casadi::SparsityInterface< Matrix< Scalar > >::self () const inline protected inherited
Definition at line 51 of file sparsity_interface.hpp.
 { return static_cast<const MatType&>(*this); }
Matrix< Scalar > & casadi::GenericExpression< Matrix< Scalar > >::self () inline protected inherited
Definition at line 52 of file generic_expression.hpp.
 { return static_cast<ExType&>(*this); }
Matrix< Scalar > & casadi::SparsityInterface< Matrix< Scalar > >::self () inline protected inherited
Definition at line 52 of file sparsity_interface.hpp.
 { return static_cast<MatType&>(*this); }
template<typename Scalar> void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Slice & rr)
Set a submatrix, single argument
Definition at line 269 of file matrix_impl.hpp.
References casadi::Slice::all(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::Slice::is_scalar(), casadi::Slice::scalar(), and casadi::Matrix< Scalar >::scalar().
{
     // Scalar
     if (rr.is_scalar(numel()) && m.is_dense()) {
       int r = rr.scalar(numel());
       int oldsize = sparsity_.nnz();
       int ind = sparsity_.add_nz(r % size1(), r / size1());
       if (oldsize == sparsity_.nnz()) {
         nonzeros_.at(ind) = m.scalar();
       } else {
         nonzeros_.insert(nonzeros_.begin()+ind, m.scalar());
       }
       return;
     }
     // Fall back on IM
     set(m, ind1, rr.all(numel(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Matrix< int > & rr)
Set a submatrix, single argument
Definition at line 288 of file matrix_impl.hpp.
References casadi::inBounds(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::GenericMatrix< MatType >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::project(), casadi::GenericMatrix< Matrix< Scalar > >::size(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), casadi::GenericMatrix< MatType >::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::Matrix< Scalar >::T(), casadi::to_slice(), and casadi::Sparsity::triplet().
{
     // Scalar
     if (rr.is_scalar(true) && m.is_dense()) {
       return set(m, ind1, to_slice(rr, ind1));
     }
     // Assert dimensions of assigning matrix
     if (rr.sparsity() != m.sparsity()) {
       if (rr.size() == m.size()) {
         // Remove submatrix to be replaced
         erase(rr.nonzeros(), ind1);
         // Find the intersection between rr's and m's sparsity patterns
         Sparsity sp = rr.sparsity() * m.sparsity();
         // Project both matrices to this sparsity
         return set(project(m, sp), ind1, Matrix<int>::project(rr, sp));
       } else if (m.is_scalar()) {
         // m scalar means "set all"
         if (m.is_dense()) {
           return set(Matrix<Scalar>(rr.sparsity(), m), ind1, rr);
         } else {
           return set(Matrix<Scalar>(rr.size()), ind1, rr);
         }
       } else if (rr.size1() == m.size2() && rr.size2() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set(m.T(), ind1, rr);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch." << "lhs is " << rr.size()
                      << ", while rhs is " << m.size());
       }
     }
     // Dimensions of this
     int sz1 = size1(), sz2 = size2(), sz = nnz(), nel = numel(), rrsz = rr.nnz();
     // Quick return if nothing to set
     if (rrsz==0) return;
     // Check bounds
     if (!inBounds(rr.nonzeros(), -nel+ind1, nel+ind1)) {
       casadi_error("set[rr] out of bounds. Your rr contains "
                    << *std::min_element(rr->begin(), rr->end()) << " up to "
                    << *std::max_element(rr->begin(), rr->end())
                    << ", which is outside the range [" << -nel+ind1 << ","<< nel+ind1 <<  ").");
     }
     // Dense mode
     if (is_dense() && m.is_dense()) {
       return set_nz(m, ind1, rr);
     }
     // Construct new sparsity pattern
     std::vector<int> new_row=sparsity().get_row(), new_col=sparsity().get_col(), nz(rr.nonzeros());
     new_row.reserve(sz+rrsz);
     new_col.reserve(sz+rrsz);
     nz.reserve(rrsz);
     for (std::vector<int>::iterator i=nz.begin(); i!=nz.end(); ++i) {
       if (ind1) (*i)--;
       if (*i<0) *i += nel;
       new_row.push_back(*i % sz1);
       new_col.push_back(*i / sz1);
     }
     Sparsity sp = Sparsity::triplet(sz1, sz2, new_row, new_col);
     // If needed, update pattern
     if (sp != sparsity()) *this = project(*this, sp);
     // Find the nonzeros corresponding to rr
     sparsity().get_nz(nz);
     // Carry out the assignments
     for (int i=0; i<nz.size(); ++i) {
       nonzeros().at(nz[i]) = m->at(i);
     }
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Sparsity & sp)
Set a submatrix, single argument
Definition at line 368 of file matrix_impl.hpp.
References casadi::densify(), casadi::Sparsity::find(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), and casadi::Sparsity::size().
{
     casadi_assert_message(size()==sp.size(),
                           "set(Sparsity sp): shape mismatch. This matrix has shape "
                           << size() << ", but supplied sparsity index has shape "
                           << sp.size() << ".");
     std::vector<int> ii = sp.find();
     if (m.is_scalar()) {
       (*this)(ii) = densify(m);
     } else {
       (*this)(ii) = densify(m(ii));
     }
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Slice & rr, const Slice & cc)
Set a submatrix, two arguments
Definition at line 159 of file matrix_impl.hpp.
References casadi::Slice::all(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::Slice::is_scalar(), casadi::Slice::scalar(), and casadi::Matrix< Scalar >::scalar().
{
     // Both are scalar
     if (rr.is_scalar(size1()) && cc.is_scalar(size2()) && m.is_dense()) {
       int oldsize = sparsity_.nnz();
       int ind = sparsity_.add_nz(rr.scalar(size1()), cc.scalar(size2()));
       if (oldsize == sparsity_.nnz()) {
         nonzeros_.at(ind) = m.scalar();
       } else {
         nonzeros_.insert(nonzeros_.begin()+ind, m.scalar());
       }
       return;
     }
     // Fall back on (IM, IM)
     set(m, ind1, rr.all(size1(), ind1), cc.all(size2(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Slice & rr, const Matrix< int > & cc)
Set a submatrix, two arguments
Definition at line 178 of file matrix_impl.hpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     set(m, ind1, rr.all(size1(), ind1), cc);
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Matrix< int > & rr, const Slice & cc)
Set a submatrix, two arguments
Definition at line 185 of file matrix_impl.hpp.
References casadi::Slice::all().
{
     // Fall back on (IM, IM)
     set(m, ind1, rr, cc.all(size2(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Matrix< int > & rr, const Matrix< int > & cc)
Set a submatrix, two arguments
Definition at line 192 of file matrix_impl.hpp.
References casadi::GenericMatrix< MatType >::colind(), casadi::inBounds(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< Matrix< Scalar > >::row(), casadi::GenericMatrix< Matrix< Scalar > >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::Matrix< Scalar >::T(), casadi::to_slice(), and casadi::GenericMatrix< Matrix< int > >::zeros().
{
     // Scalar
     if (rr.is_scalar(true) && cc.is_scalar(true) && m.is_dense()) {
       return set(m, ind1, to_slice(rr, ind1), to_slice(cc, ind1));
     }
     // Row vector rr (e.g. in MATLAB) is transposed to column vector
     if (rr.size1()==1 && rr.size2()>1) {
       return set(m, ind1, rr.T(), cc);
     }
     // Row vector cc (e.g. in MATLAB) is transposed to column vector
     if (cc.size1()==1 && cc.size2()>1) {
       return set(m, ind1, rr, cc.T());
     }
     // Make sure rr and cc are dense vectors
     casadi_assert_message(rr.is_dense() && rr.is_column(),
                           "Matrix::set: First index not dense vector");
     casadi_assert_message(cc.is_dense() && cc.is_column(),
                           "Matrix::set: Second index not dense vector");
     // Assert dimensions of assigning matrix
     if (rr.size1() != m.size1() || cc.size1() != m.size2()) {
       if (m.is_scalar()) {
         // m scalar means "set all"
         return set(repmat(m, rr.size1(), cc.size1()), ind1, rr, cc);
       } else if (rr.size1() == m.size2() && cc.size1() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set(m.T(), ind1, rr, cc);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch." << "lhs is " << rr.size1() << "-by-"
                      << cc.size1() << ", while rhs is " << m.size());
       }
     }
     // Dimensions
     int sz1 = size1(), sz2 = size2();
     // Report out-of-bounds
     if (!inBounds(rr.nonzeros(), -sz1+ind1, sz1+ind1)) {
       casadi_error("set[., r, c] out of bounds. Your rr contains "
                    << *std::min_element(rr->begin(), rr->end()) << " up to "
                    << *std::max_element(rr->begin(), rr->end())
                    << ", which is outside the range [" << -sz1+ind1 << ","<< sz1+ind1 <<  ").");
     }
     if (!inBounds(cc.nonzeros(), -sz2+ind1, sz2+ind1)) {
       casadi_error("set [., r, c] out of bounds. Your cc contains "
                    << *std::min_element(cc->begin(), cc->end()) << " up to "
                    << *std::max_element(cc->begin(), cc->end())
                    << ", which is outside the range [" << -sz2+ind1 << ","<< sz2+ind1 <<  ").");
     }
     // If we are assigning with something sparse, first remove existing entries
     if (!m.is_dense()) {
       erase(rr.nonzeros(), cc.nonzeros(), ind1);
     }
     // Collect all assignments
     IM el = IM::zeros(m.sparsity());
     for (int j=0; j<el.size2(); ++j) { // Loop over columns of m
       int this_j = cc->at(j) - ind1; // Corresponding column in this
       if (this_j<0) this_j += sz2;
       for (int k=el.colind(j); k<el.colind(j+1); ++k) { // Loop over rows of m
         int i = m.row(k);
         int this_i = rr->at(i) - ind1; // Corresponding row in this
         if (this_i<0) this_i += sz1;
         el->at(k) = this_i + this_j*sz1;
       }
     }
     return set(m, false, el);
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set_nz (const Matrix< Scalar > & m, bool ind1, const Slice & k)
Set a set of nonzeros
Definition at line 428 of file matrix_impl.hpp.
References casadi::Slice::all(), casadi::Slice::is_scalar(), casadi::Slice::scalar(), and casadi::Matrix< Scalar >::scalar().
{
     // Scalar
     if (kk.is_scalar(nnz())) {
       nonzeros().at(kk.scalar(nnz())) = m.scalar();
       return;
     }
     // Fallback on IM
     set_nz(m, ind1, kk.all(nnz(), ind1));
   }
template<typename Scalar> void casadi::Matrix< Scalar >::set_nz (const Matrix< Scalar > & m, bool ind1, const Matrix< int > & k)
Set a set of nonzeros
Definition at line 440 of file matrix_impl.hpp.
References casadi::inBounds(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< Matrix< Scalar > >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::project(), casadi::GenericMatrix< Matrix< Scalar > >::size(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), casadi::GenericMatrix< MatType >::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::Matrix< Scalar >::T(), and casadi::to_slice().
{
     // Scalar
     if (kk.is_scalar(true)) {
       return set_nz(m, ind1, to_slice(kk, ind1));
     }
     // Assert dimensions of assigning matrix
     if (kk.sparsity() != m.sparsity()) {
       if (m.is_scalar()) {
         // m scalar means "set all"
         if (!m.is_dense()) return; // Nothing to set
         return set_nz(Matrix<Scalar>(kk.sparsity(), m), ind1, kk);
       } else if (kk.size() == m.size()) {
         // Project sparsity if needed
         return set_nz(project(m, kk.sparsity()), ind1, kk);
       } else if (kk.size1() == m.size2() && kk.size2() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set_nz(m.T(), ind1, kk);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch." << "lhs is " << kk.size()
                      << ", while rhs is " << m.size());
       }
     }
     // Get nonzeros
     const std::vector<int>& k = kk.nonzeros();
     int sz = nnz();
     // Check bounds
     if (!inBounds(k, -sz+ind1, sz+ind1)) {
       casadi_error("set_nz[kk] out of bounds. Your kk contains "
                    << *std::min_element(k.begin(), k.end()) << " up to "
                    << *std::max_element(k.begin(), k.end())
                    << ", which is outside the range [" << -sz+ind1 << ","<< sz+ind1 <<  ").");
     }
     // Set nonzeros, ignoring negative indices
     for (int el=0; el<k.size(); ++el) {
       casadi_assert_message(!(ind1 && k[el]<=0), "Matlab is 1-based, but requested index " <<
                                                 k[el] <<  ". Note that negative slices are" <<
                                                 " disabled in the Matlab interface. " <<
                                                 "Possibly you may want to use 'end'.");
       int k_el = k[el]-ind1;
       nonzeros().at(k_el>=0 ? k_el : k_el+sz) = m->at(el);
     }
   }
template<typename Scalar > void casadi::Matrix< Scalar >::setEqualityCheckingDepth (int eq_depth = 1) static
Definition at line 1441 of file matrix_impl.hpp.
{
     throw CasadiException("\"setEqualityCheckingDepth\" not defined for instantiation");
   }
template<typename Scalar> static void casadi::Matrix< Scalar >::setPrecision (int precision) inline static
Definition at line 958 of file matrix.hpp.
 { stream_precision_ = precision; }
template<typename Scalar> static void casadi::Matrix< Scalar >::setScientific (bool scientific) inline static
Definition at line 960 of file matrix.hpp.
 { stream_scientific_ = scientific; }
template<typename Scalar> static void casadi::Matrix< Scalar >::setWidth (int width) inline static
Definition at line 959 of file matrix.hpp.
 { stream_width_ = width; }
template<typename Scalar> void casadi::Matrix< Scalar >::shared (std::vector< Matrix< Scalar > > & ex, std::vector< Matrix< Scalar > > & v, std::vector< Matrix< Scalar > > & vdef, const std::string & v_prefix, const std::string & v_suffix) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2326 of file matrix_impl.hpp.
{
     throw CasadiException("\"shared\" not defined for instantiation");
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::simplify (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2192 of file matrix_impl.hpp.
{
     return x;
   }
std::pair<int, int> casadi::GenericMatrix< Matrix< Scalar > >::size () const inherited
Referenced by casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::dot(), casadi::Matrix< Scalar >::is_equal(), casadi::Matrix< Scalar >::kron(), casadi::Matrix< Scalar >::set(), and casadi::Matrix< Scalar >::set_nz().
int casadi::GenericMatrix< Matrix< Scalar > >::size (int axis) const inherited
int casadi::GenericMatrix< Matrix< Scalar > >::size1 () const inherited
Referenced by casadi::Matrix< Scalar >::adj(), casadi::Matrix< Scalar >::chol(), casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::det(), casadi::Matrix< Scalar >::diagsplit(), casadi::Matrix< Scalar >::getMinor(), casadi::Matrix< Scalar >::kron(), casadi::Matrix< Scalar >::mac(), casadi::Matrix< Scalar >::Matrix(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::Matrix< Scalar >::norm_inf_mul(), casadi::Matrix< Scalar >::nullspace(), casadi::Matrix< Scalar >::pinv(), casadi::Matrix< Scalar >::project(), casadi::Matrix< Scalar >::qr(), casadi::Matrix< Scalar >::set(), casadi::Matrix< Scalar >::set_nz(), casadi::Matrix< Scalar >::solve(), casadi::Matrix< Scalar >::sparsify(), and casadi::Matrix< Scalar >::sum1().
int casadi::GenericMatrix< Matrix< Scalar > >::size2 () const inherited
Referenced by casadi::Matrix< Scalar >::adj(), casadi::Matrix< Scalar >::chol(), casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::det(), casadi::Matrix< Scalar >::diagsplit(), casadi::Matrix< Scalar >::getMinor(), casadi::Matrix< Scalar >::kron(), casadi::Matrix< Scalar >::mac(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::Matrix< Scalar >::norm_inf_mul(), casadi::Matrix< Scalar >::nullspace(), casadi::Matrix< Scalar >::pinv(), casadi::Matrix< Scalar >::qr(), casadi::Matrix< Scalar >::set(), casadi::Matrix< Scalar >::set_nz(), casadi::Matrix< Scalar >::solve(), casadi::Matrix< Scalar >::sparsify(), casadi::Matrix< Scalar >::sum2(), and casadi::Matrix< Scalar >::trace().
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::skew (const Matrix< Scalar > & a) static inherited
template<> Matrix< double > casadi::Matrix< double >::solve (const Matrix< double > & A, const Matrix< double > & b, const string & lsolver, const Dict & dict)
Definition at line 50 of file matrix.cpp.
References casadi::linsol(), casadi::LINSOL_A, casadi::LINSOL_B, casadi::LINSOL_NUM_IN, casadi::LINSOL_X, casadi::GenericMatrix< MatType >::size2(), and casadi::Matrix< Scalar >::sparsity().
{
     Function mysolver = linsol("tmp", lsolver, A.sparsity(), b.size2(), dict);
     vector<DM> arg(LINSOL_NUM_IN);
     arg.at(LINSOL_A) = A;
     arg.at(LINSOL_B) = b;
     return mysolver(arg).at(LINSOL_X);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::solve (const Matrix< Scalar > & A, const Matrix< Scalar > & b) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1896 of file matrix_impl.hpp.
References casadi::Sparsity::btf(), casadi::GenericMatrix< Matrix< Scalar > >::colind(), casadi::GenericMatrix< Matrix< Scalar > >::dim(), casadi::Matrix< Scalar >::has_nz(), casadi::Matrix< Scalar >::has_zeros(), casadi::GenericMatrix< Matrix< Scalar > >::is_tril(), casadi::GenericMatrix< Matrix< Scalar > >::is_triu(), casadi::mtimes(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< Matrix< Scalar > >::row(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), casadi::GenericMatrix< Matrix< Scalar > >::size2(), casadi::sparsify(), casadi::Matrix< Scalar >::sparsity(), and casadi::Matrix< Scalar >::T().
{
     // check dimensions
     casadi_assert_message(a.size1() == b.size1(), "solve Ax=b: dimension mismatch: b has "
                           << b.size1() << " rows while A has " << a.size1() << ".");
     casadi_assert_message(a.size1() == a.size2(), "solve: A not square but " << a.dim());
     if (a.is_tril()) {
       // forward substitution if lower triangular
       Matrix<Scalar> x = b;
       const int*  Arow = a.row();
       const int*  Acolind = a.colind();
       const std::vector<Scalar> & Adata = a.nonzeros();
       for (int i=0; i<a.size2(); ++i) { // loop over columns forwards
         for (int k=0; k<b.size2(); ++k) { // for every right hand side
           if (!x.has_nz(i, k)) continue;
           x(i, k) /= a(i, i);
           for (int kk=Acolind[i+1]-1; kk>=Acolind[i] && Arow[kk]>i; --kk) {
             int j = Arow[kk];
             x(j, k) -= Adata[kk]*x(i, k);
           }
         }
       }
       return x;
     } else if (a.is_triu()) {
       // backward substitution if upper triangular
       Matrix<Scalar> x = b;
       const int*  Arow = a.row();
       const int*  Acolind = a.colind();
       const std::vector<Scalar> & Adata = a.nonzeros();
       for (int i=a.size2()-1; i>=0; --i) { // loop over columns backwards
         for (int k=0; k<b.size2(); ++k) { // for every right hand side
           if (!x.has_nz(i, k)) continue;
           x(i, k) /= a(i, i);
           for (int kk=Acolind[i]; kk<Acolind[i+1] && Arow[kk]<i; ++kk) {
             int j = Arow[kk];
             x(j, k) -= Adata[kk]*x(i, k);
           }
         }
       }
       return x;
     } else if (a.has_zeros()) {
       // If there are structurally nonzero entries that are known to be zero,
       // remove these and rerun the algorithm
       return solve(sparsify(a), b);
     } else {
       // Make a BLT transformation of A
       std::vector<int> rowperm, colperm, rowblock, colblock, coarse_rowblock, coarse_colblock;
       a.sparsity().btf(rowperm, colperm, rowblock, colblock,
                        coarse_rowblock, coarse_colblock);
       // Permute the right hand side
       Matrix<Scalar> bperm = b(rowperm, Slice());
       // Permute the linear system
       Matrix<Scalar> Aperm = a(rowperm, colperm);
       // Solution
       Matrix<Scalar> xperm;
       // Solve permuted system
       if (Aperm.is_tril()) {
         // Forward substitution if lower triangular
         xperm = solve(Aperm, bperm);
       } else if (a.size2()<=3) {
         // Form inverse by minor expansion and multiply if very small (up to 3-by-3)
         xperm = mtimes(inv(Aperm), bperm);
       } else {
         // Make a QR factorization
         Matrix<Scalar> Q, R;
         qr(Aperm, Q, R);
         // Solve the factorized system (note that solve will now be fast since it is triangular)
         xperm = solve(R, mtimes(Q.T(), bperm));
       }
       // get the inverted column permutation
       std::vector<int> inv_colperm(colperm.size());
       for (int k=0; k<colperm.size(); ++k)
         inv_colperm[colperm[k]] = k;
       // Permute back the solution and return
       Matrix<Scalar> x = xperm(inv_colperm, Slice());
       return x;
     }
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::solve (const Matrix< Scalar > & A, const Matrix< Scalar > & b, const std::string & lsolver, const Dict & opts) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1992 of file matrix_impl.hpp.
{
     throw CasadiException("\"solve\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<> CASADI_EXPORT Matrix< double > casadi::Matrix< double >::solve (const Matrix< double > & a, const Matrix< double > & b, const std::string & lsolver, const Dict & dict)
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::sparsify (const Matrix< Scalar > & x, double tol = 0) static
Functions called by friend functions defined here
Definition at line 2351 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::colind(), casadi::casadi_limits< T >::isAlmostZero(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< Matrix< Scalar > >::row(), casadi::GenericMatrix< Matrix< Scalar > >::size1(), and casadi::GenericMatrix< Matrix< Scalar > >::size2().
{
     // Quick return if there are no entries to be removed
     bool remove_nothing = true;
     for (auto it=x.nonzeros().begin(); it!=x.nonzeros().end() && remove_nothing; ++it) {
       remove_nothing = !casadi_limits<Scalar>::isAlmostZero(*it, tol);
     }
     if (remove_nothing) return x;
     // Get the current sparsity pattern
     int size1 = x.size1();
     int size2 = x.size2();
     const int* colind = x.colind();
     const int* row = x.row();
     // Construct the new sparsity pattern
     std::vector<int> new_colind(1, 0), new_row;
     std::vector<Scalar> new_data;
     // Loop over the columns
     for (int cc=0; cc<size2; ++cc) {
       // Loop over existing nonzeros
       for (int el=colind[cc]; el<colind[cc+1]; ++el) {
         // If it is not known to be a zero
         if (!casadi_limits<Scalar>::isAlmostZero(x->at(el), tol)) {
           // Save the nonzero in its new location
           new_data.push_back(x->at(el));
           // Add to pattern
           new_row.push_back(row[el]);
         }
       }
       // Save the new column offset
       new_colind.push_back(new_row.size());
     }
     // Construct the sparsity pattern
     Sparsity sp(size1, size2, new_colind, new_row);
     // Construct matrix and return
     return Matrix<Scalar>(sp, new_data);
   }
template<typename Scalar> const Sparsity& casadi::Matrix< Scalar >::sparsity () const inline
Definition at line 815 of file matrix.hpp.
Referenced by casadi::Matrix< Scalar >::_bilin(), casadi::Matrix< Scalar >::_rank1(), casadi::ConstantMX::create(), casadi::Matrix< Scalar >::det(), casadi::Matrix< Scalar >::diag(), casadi::Matrix< Scalar >::dot(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::Matrix< Scalar >::get_nz(), casadi::MX::get_nz(), casadi::FunctionInternal::getJacSparsityHierarchical(), casadi::FunctionInternal::getJacSparsityHierarchicalSymm(), casadi::Matrix< Scalar >::getMinor(), casadi::Matrix< Scalar >::horzsplit(), casadi::SymbolicQr::init(), casadi::SnoptInterface::init(), casadi::Sqpmethod::init(), casadi::Matrix< Scalar >::is_equal(), casadi::Matrix< Scalar >::kron(), casadi::CsparseInterface::linsol_factorize(), casadi::Matrix< Scalar >::mac(), casadi::Matrix< Scalar >::matrix_matrix(), casadi::Matrix< Scalar >::matrix_scalar(), casadi::Matrix< Scalar >::mtimes(), casadi::Matrix< Scalar >::norm_1(), casadi::Matrix< Scalar >::norm_inf_mul(), casadi::Matrix< Scalar >::project(), casadi::Matrix< Scalar >::reshape(), casadi::Matrix< Scalar >::scalar_matrix(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::Matrix< Scalar >::solve(), casadi::Matrix< Scalar >::unary(), casadi::Matrix< Scalar >::unite(), and casadi::SnoptInterface::userfun().
 { return sparsity_; }
Sparsity& casadi::GenericMatrix< Matrix< Scalar > >::sparsityRef () inherited
static int casadi::GenericMatrix< Matrix< Scalar > >::sprank (const Matrix< Scalar > & x) inline static inherited
Definition at line 175 of file generic_matrix.hpp.
 { return Sparsity::sprank(x.sparsity());}
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::substitute (const Matrix< Scalar > & ex, const Matrix< Scalar > & v, const Matrix< Scalar > & vdef) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2197 of file matrix_impl.hpp.
{
     throw CasadiException("\"substitute\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<typename Scalar> std::vector< Matrix< Scalar > > casadi::Matrix< Scalar >::substitute (const std::vector< Matrix< Scalar > > & ex, const std::vector< Matrix< Scalar > > & v, const std::vector< Matrix< Scalar > > & vdef) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2206 of file matrix_impl.hpp.
{
     throw CasadiException("\"substitute\" not defined for instantiation");
     return std::vector<Matrix<Scalar> >();
   }
template<typename Scalar> void casadi::Matrix< Scalar >::substitute_inplace (const std::vector< Matrix< Scalar > > & v, std::vector< Matrix< Scalar > > & vdef, std::vector< Matrix< Scalar > > & ex, bool revers) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2214 of file matrix_impl.hpp.
{
     throw CasadiException("\"substitute_inplace\" not defined for instantiation");
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::sum1 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1524 of file matrix_impl.hpp.
References casadi::mtimes(), and casadi::GenericMatrix< Matrix< Scalar > >::size1().
Referenced by casadi::Matrix< Scalar >::det().
{
     return mtimes(Matrix<Scalar>::ones(1, x.size1()), x);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::sum2 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1519 of file matrix_impl.hpp.
References casadi::mtimes(), and casadi::GenericMatrix< Matrix< Scalar > >::size2().
Referenced by casadi::Matrix< Scalar >::det().
{
     return mtimes(x, Matrix<Scalar>::ones(x.size2(), 1));
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sum_square (const Matrix< Scalar > & x) inline static inherited
Definition at line 185 of file generic_matrix.hpp.
 { return dot(x, x);}
casadi::GenericMatrix< Matrix< Scalar > >::SWIG_CONSTREF (Sparsity) const inherited
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, int nrow = 1, int ncol = 1) inline static inherited
Definition at line 615 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol));
     }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const std::pair< int, int > & rc) inline static inherited
Definition at line 620 of file generic_matrix.hpp.
{
       return sym(name, rc.first, rc.second);
     }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const Sparsity & sp) static inherited
static std::vector<Matrix< Scalar > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const Sparsity & sp, int p) static inherited
static std::vector<Matrix< Scalar > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, int nrow, int ncol, int p) inline static inherited
Definition at line 632 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p);
     }
static std::vector<std::vector<Matrix< Scalar > > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const Sparsity & sp, int p, int r) static inherited
static std::vector<std::vector<Matrix< Scalar > > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, int nrow, int ncol, int p, int r) inline static inherited
Definition at line 644 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p, r);
     }
template<typename Scalar> std::vector< Matrix< Scalar > > casadi::Matrix< Scalar >::symvar (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2320 of file matrix_impl.hpp.
{
     throw CasadiException("\"symvar\" not defined for instantiation");
     return std::vector<Matrix<Scalar> >();
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::T () const
Definition at line 1045 of file matrix_impl.hpp.
References casadi::Sparsity::transpose().
Referenced by casadi::Matrix< Scalar >::adj(), casadi::QpToNlp::init(), casadi::SymbolicQr::init(), casadi::Sqpmethod::init(), casadi::Matrix< Scalar >::nullspace(), casadi::Matrix< Scalar >::pinv(), casadi::Matrix< Scalar >::qr(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::Matrix< Scalar >::solve(), and casadi::Matrix< Scalar >::vertsplit().
{
     // quick return if empty or scalar
     if ((size1()==0 && size2()==0) || is_scalar()) return *this;
     // Create the new sparsity pattern and the mapping
     std::vector<int> mapping;
     Sparsity s = sparsity().transpose(mapping);
     // create the return matrix
     Matrix<Scalar> ret = zeros(s);
     // Copy the content
     for (int i=0; i<mapping.size(); ++i)
       ret->at(i) = nonzeros().at(mapping[i]);
     return ret;
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::tang (const Function & f, int iind = 0, int oind = 0) static
Definition at line 2411 of file matrix_impl.hpp.
{
     throw CasadiException("\"tang\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::tang (const Function & f, const std::string & iname, int oind = 0) static
Definition at line 2452 of file matrix_impl.hpp.
{
     throw CasadiException("\"tang\" not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::tang (const Function & f, int iind, const std::string & oname) static
Definition at line 2457 of file matrix_impl.hpp.
{
     throw CasadiException("'tang' not defined for " + type_name());
   }
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::tang (const Function & f, const std::string & iname, const std::string & oname) static
Definition at line 2462 of file matrix_impl.hpp.
{
     throw CasadiException("'tang' not defined for " + type_name());
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::tangent (const Matrix< Scalar > & f, const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2243 of file matrix_impl.hpp.
{
     casadi_error("\"tangent\" not defined for " + type_name());
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::taylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, int order) static
Functions called by friend functions defined here
Definition at line 2281 of file matrix_impl.hpp.
{
     throw CasadiException("\"taylor\" not defined for instantiation");
     return Matrix<Scalar>();
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::trace (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 1611 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::colind(), casadi::GenericMatrix< Matrix< Scalar > >::is_square(), casadi::Matrix< Scalar >::ptr(), casadi::GenericMatrix< Matrix< Scalar > >::row(), and casadi::GenericMatrix< Matrix< Scalar > >::size2().
{
     casadi_assert_message(x.is_square(), "trace: must be square");
     Scalar res=0;
     const Scalar* d=x.ptr();
     int size2 = x.size2();
     const int *colind=x.colind(), *row=x.row();
     for (int c=0; c<size2; c++) {
       for (int k=colind[c]; k!=colind[c+1]; ++k) {
         if (row[k]==c) {
           res += d[k];
         }
       }
     }
     return res;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::triangle (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
Definition at line 2164 of file matrix_impl.hpp.
References casadi::fabs().
{
     return rectangle(x/2)*(1-fabs(x));
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::tril (const Matrix< Scalar > & x, bool includeDiagonal = true) inline static inherited
Definition at line 179 of file generic_matrix.hpp.
{
       return project(x, Sparsity::tril(x.sparsity(), includeDiagonal));
     }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::tril2symm (const Matrix< Scalar > & x) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::triplet (const std::vector< int > & row, const std::vector< int > & col, const Matrix< Scalar > & d) static
Definition at line 1209 of file matrix_impl.hpp.
{
     return triplet(row, col, d, *std::max_element(row.begin(), row.end()),
                    *std::max_element(col.begin(), col.end()));
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::triplet (const std::vector< int > & row, const std::vector< int > & col, const Matrix< Scalar > & d, int nrow, int ncol) static
Definition at line 1225 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::nnz(), and casadi::Sparsity::triplet().
{
     casadi_assert_message(col.size()==row.size() && col.size()==d.nnz(),
                           "Argument error in Matrix<Scalar>::triplet(row, col, d): "
                           "supplied lists must all be of equal length, but got: "
                           << row.size() << ", " << col.size()  << " and " << d.nnz());
     std::vector<int> mapping;
     Sparsity sp = Sparsity::triplet(nrow, ncol, row, col, mapping);
     return Matrix<Scalar>(sp, d[mapping]);
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::triplet (const std::vector< int > & row, const std::vector< int > & col, const Matrix< Scalar > & d, const std::pair< int, int > & rc) static
Definition at line 1217 of file matrix_impl.hpp.
{
     return triplet(row, col, d, rc.first, rc.second);
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::triu (const Matrix< Scalar > & x, bool includeDiagonal = true) inline static inherited
Definition at line 182 of file generic_matrix.hpp.
{
       return project(x, Sparsity::triu(x.sparsity(), includeDiagonal));
     }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::triu2symm (const Matrix< Scalar > & x) static inherited
template<typename Scalar > std::string casadi::Matrix< Scalar >::type_name () static
Definition at line 545 of file matrix_impl.hpp.
 { return matrixName<Scalar>(); }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::unary (int op, const Matrix< Scalar > & x) static
Definition at line 846 of file matrix_impl.hpp.
References casadi::densify(), casadi::casadi_math< T >::fun(), casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
{
     // Return value
     Matrix<Scalar> ret = Matrix<Scalar>::zeros(x.sparsity());
     // Nonzeros
     std::vector<Scalar>& ret_data = ret.nonzeros();
     const std::vector<Scalar>& x_data = x.nonzeros();
     // Do the operation on all non-zero elements
     for (int el=0; el<x.nnz(); ++el) {
       casadi_math<Scalar>::fun(op, x_data[el], x_data[el], ret_data[el]);
     }
     // Check the value of the structural zero-entries, if there are any
     if (!x.is_dense() && !operation_checker<F0XChecker>(op)) {
       // Get the value for the structural zeros
       Scalar fcn_0;
       casadi_math<Scalar>::fun(op, 0, 0, fcn_0);
       if (!casadi_limits<Scalar>::is_zero(fcn_0)) { // Remove this if?
         ret = densify(ret, fcn_0);
       }
     }
     return ret;
   }
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::unite (const Matrix< Scalar > & A, const Matrix< Scalar > & B) static
Functions called by friend functions defined for GenericMatrix
Definition at line 2059 of file matrix_impl.hpp.
References casadi::GenericMatrix< Matrix< Scalar > >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), and casadi::Sparsity::unite().
{
     // Join the sparsity patterns
     std::vector<unsigned char> mapping;
     Sparsity sp = A.sparsity().unite(B.sparsity(), mapping);
     // Create return matrix
     Matrix<Scalar> ret = zeros(sp);
     // Copy sparsity
     int elA=0, elB=0;
     for (int k=0; k<mapping.size(); ++k) {
       if (mapping[k]==1) {
         ret.nonzeros()[k] = A.nonzeros()[elA++];
       } else if (mapping[k]==2) {
         ret.nonzeros()[k] = B.nonzeros()[elB++];
       } else {
         throw CasadiException("Pattern intersection not empty");
       }
     }
     casadi_assert(A.nnz()==elA);
     casadi_assert(B.nnz()==elB);
     return ret;
   }
static Matrix< Scalar > casadi::SparsityInterface< Matrix< Scalar > >::vec (const Matrix< Scalar > & x) static inherited
static Matrix< Scalar > casadi::SparsityInterface< Matrix< Scalar > >::veccat (const std::vector< Matrix< Scalar > > & x) static inherited
template<typename Scalar> Matrix< Scalar > casadi::Matrix< Scalar >::vertcat (const std::vector< Matrix< Scalar > > & v) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1676 of file matrix_impl.hpp.
{
     std::vector<Matrix<Scalar> > vT(v.size());
     for (int i=0; i<v.size(); ++i) vT[i] = v[i].T();
     return horzcat(vT).T();
   }
static std::vector<Matrix< Scalar > > casadi::SparsityInterface< Matrix< Scalar > >::vertsplit (const Matrix< Scalar > & x, int incr) static inherited
template<typename Scalar> std::vector< Matrix< Scalar > > casadi::Matrix< Scalar >::vertsplit (const Matrix< Scalar > & x, const std::vector< int > & offset) static
Functions called by friend functions defined for SparsityInterface
Definition at line 1684 of file matrix_impl.hpp.
References casadi::Matrix< Scalar >::T().
{
     std::vector< Matrix<Scalar> > ret = horzsplit(x.T(), offset);
     for (auto&& e : ret) e = e.T();
     return ret;
   }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::zeros (int nrow = 1, int ncol = 1) inline static inherited
Definition at line 651 of file generic_matrix.hpp.
Referenced by casadi::FunctionInternal::_call(), casadi::Matrix< Scalar >::get(), casadi::Matrix< Scalar >::matrix_scalar(), casadi::Matrix< Scalar >::mtimes(), casadi::Matrix< Scalar >::project(), casadi::Matrix< Scalar >::scalar_matrix(), and casadi::Matrix< Scalar >::unary().
 { return zeros(Sparsity::dense(nrow, ncol)); }
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::zeros (const Sparsity & sp) inline static inherited
Definition at line 652 of file generic_matrix.hpp.
 { return MatType(sp, 0, false);}
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::zeros (const std::pair< int, int > & rc) inline static inherited
Definition at line 653 of file generic_matrix.hpp.
 { return zeros(rc.first, rc.second);}
Friends And Related Function Documentation
template<typename Scalar> Matrix<Scalar> eig_symbolic (const Matrix< Scalar > & m) friend
Definition at line 696 of file matrix.hpp.
{
       return Matrix<Scalar>::eig_symbolic(m);
     }
template<typename Scalar> Scalar* get_ptr (Matrix< Scalar > & v) friend
Get a pointer to the data
Definition at line 810 of file matrix.hpp.
 { return v.ptr(); }
template<typename Scalar> const Scalar* get_ptr (const Matrix< Scalar > & v) friend
Get a pointer to the data
Definition at line 811 of file matrix.hpp.
 { return v.ptr(); }
template<typename Scalar> Matrix<Scalar> mtaylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, int order = 1) friend
Do Taylor expansions until the aggregated order of a term is equal to 'order'. The aggregated order of equals .
Definition at line 636 of file matrix.hpp.
{
       return Matrix<Scalar>::mtaylor(ex, x, a, order);
     }
template<typename Scalar> Matrix<Scalar> mtaylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, int order, const std::vector< int > & order_contributions) friend
Do Taylor expansions until the aggregated order of a term is equal to 'order'. The aggregated order of equals .
The argument order_contributions can denote how match each variable contributes to the aggregated order. If x=[x, y] and order_contributions=[1, 2], then the aggregated order of equals .
Example usage
taylor(sin(x+y),[x, y],[a, b], 1)
taylor(sin(x+y),[x, y],[0, 0], 4)
taylor(sin(x+y),[x, y],[0, 0], 4,[1, 2])
Definition at line 667 of file matrix.hpp.
{
       return Matrix<Scalar>::mtaylor(ex, x, a, order, order_contributions);
     }
template<typename Scalar> Matrix<Scalar> poly_coeff (const Matrix< Scalar > & f, const Matrix< Scalar > & x) friend
Parameters
ex Scalar expression that represents a polynomial
x Scalar symbol that the polynomial is build up with
Definition at line 678 of file matrix.hpp.
{
       return Matrix<Scalar>::poly_coeff(f, x);
     }
template<typename Scalar> Matrix<Scalar> poly_roots (const Matrix< Scalar > & p) friend
This will only work for polynomials up to order 3 It is assumed that the roots are real.
Definition at line 689 of file matrix.hpp.
{
       return Matrix<Scalar>::poly_roots(p);
     }
template<typename Scalar> Matrix<Scalar> taylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, int order = 1) friend
Calculate the Taylor expansion of expression 'ex' up to order 'order' with respect to variable 'x' around the point 'a'
Example usage:
taylor(sin(x), x)
>>   x
Definition at line 620 of file matrix.hpp.
{
       return Matrix<Scalar>::taylor(ex, x, a, order);
     }
template<typename Scalar> Matrix<Scalar> taylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x) friend
Calculate the Taylor expansion of expression 'ex' up to order 'order' with respect to variable 'x' around the point 'a'
Example usage:
taylor(sin(x), x)
>>   x
Definition at line 624 of file matrix.hpp.
{
       return Matrix<Scalar>::taylor(ex, x, 0, 1);
     }
The documentation for this class was generated from the following files:
casadi_types.hpp
matrix.hpp
matrix_impl.hpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge