CasADi: casadi::Callback Class Reference
casadi::Callback Class Reference
Callback function functionality This class provides a public API to the FunctionInternal class that can be subclassed by the user, who is then able to implement the different virtual method. Note that the Function class also provides a public API to FunctionInternal, but only allows calling, not being called.
#include <callback.hpp>
Detailed Description
The user is responsible for not deleting this class for the lifetime of the internal function object.
Author
Joris Gillis, Joel Andersson
Date
2015
Examples:
Function/callback.py, Function/callback_c.cc, and misc/assertion.py.
Definition at line 47 of file casadi/core/function/callback.hpp.
Public Member Functions
Callback ()
Default constructor.
Callback (const Callback &obj)
Copy constructor (throws an error)
void construct (const std::string &name, const Dict &opts=Dict())
Construct internal object This is the step that actually construct the internal object, as the class constructor only creates a null pointer. It should be called from the user constructor.
void transfer_ownership ()
Transfer ownership to the internal class With a call to this function, the public class will be owned by the internal class. For this to work, the object must have been created with "new" (and must not be deleted with "delete" as this is handled internally. There also has to be at least one owning reference to the class.
virtual ~Callback ()
Destructor.
virtual void init ()
Initialize the object This function is called after the object construction (for the whole class hierarchy) is complete, but before the finalization step. It is called recursively for the whole class hierarchy, starting with the lowest level.
virtual void finalize ()
Finalize the object This function is called after the construction and init steps are completed, but before user functions are called. It is called recursively for the whole class hierarchy, starting with the highest level.
virtual std::vector< DM > eval (const std::vector< DM > &arg)
Evaluate numerically, temporary matrices and work vectors.
virtual void eval (const double **arg, double **res, int *iw, double *w, int mem)
Evaluate numerically, work vectors given.
virtual int get_n_in ()
Get the number of inputs This function is called during construction.
virtual int get_n_out ()
Get the number of outputs This function is called during construction.
virtual Sparsity get_sparsity_in (int i)
Get the sparsity of an input This function is called during construction.
virtual Sparsity get_sparsity_out (int i)
Get the sparsity of an output This function is called during construction.
virtual std::string get_name_in (int i)
Get the sparsity of an input This function is called during construction.
virtual std::string get_name_out (int i)
Get the sparsity of an output This function is called during construction.
int n_in () const
Get the number of function inputs.
int n_out () const
Get the number of function outputs.
std::vector< std::string > name_in () const
Get input scheme.
std::string name_in (int ind) const
Get input scheme name by index.
std::vector< std::string > name_out () const
Get output scheme.
std::string name_out (int ind) const
Get output scheme name by index.
int index_in (const std::string &name) const
Find the index for a string describing a particular entry of an input scheme.
int index_out (const std::string &name) const
Find the index for a string describing a particular entry of an output scheme.
double default_in (int ind) const
Get default input value (NOTE: constant reference)
void printDimensions (std::ostream &stream=casadi::userOut()) const
Print dimensions of inputs and outputs.
void printOptions (std::ostream &stream=casadi::userOut()) const
Print options to a stream.
void printOption (const std::string &name, std::ostream &stream=casadi::userOut()) const
Print all information there is to know about a certain option.
void setJacobian (const Function &jac, int iind=0, int oind=0, bool compact=false)
Function fullJacobian ()
Generate a Jacobian function of all the inputs elements with respect to all the output elements).
void setFullJacobian (const Function &jac)
void operator() (const double **arg, double **res, int *iw, double *w, int mem=0) const
Evaluate memory-less, numerically.
void operator() (const SXElem **arg, SXElem **res, int *iw, SXElem *w, int mem=0) const
Evaluate memory-less SXElem Same syntax as the double version, allowing use in templated code.
void operator() (const bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem=0) const
Propagate sparsity forward.
template<typename M >
void _call (const std::map< std::string, M > &arg, std::map< std::string, M > &res, bool always_inline, bool never_inline)
Call using a map.
template<typename D >
void _call (vector< const D * > arg, vector< D * > res)
template<typename M >
void _call (const std::map< string, M > &arg, std::map< string, M > &res, bool always_inline, bool never_inline)
void rev (bvec_t **arg, bvec_t **res, int *iw, bvec_t *w, int mem=0)
Propagate sparsity backward.
void rev (std::vector< bvec_t * > arg, std::vector< bvec_t * > res)
Propagate sparsity backward with temporary memory allocation.
void forward (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &output_fsens, bool always_inline=false, bool never_inline=false)
Create call to (cached) derivative function, forward mode.
void forward (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &fseed, std::vector< std::vector< SX > > &output_fsens, bool always_inline=false, bool never_inline=false)
Create call to (cached) derivative function, forward mode.
void forward (const std::vector< DM > &arg, const std::vector< DM > &res, const std::vector< std::vector< DM > > &fseed, std::vector< std::vector< DM > > &output_fsens, bool always_inline=false, bool never_inline=false)
Create call to (cached) derivative function, forward mode.
Function forward (int nfwd)
Get a function that calculates nfwd forward derivatives.
void reverse (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &output_asens, bool always_inline=false, bool never_inline=false)
Create call to (cached) derivative function, reverse mode.
void reverse (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &aseed, std::vector< std::vector< SX > > &output_asens, bool always_inline=false, bool never_inline=false)
Create call to (cached) derivative function, reverse mode.
void reverse (const std::vector< DM > &arg, const std::vector< DM > &res, const std::vector< std::vector< DM > > &aseed, std::vector< std::vector< DM > > &output_asens, bool always_inline=false, bool never_inline=false)
Create call to (cached) derivative function, reverse mode.
Function reverse (int nadj)
Get a function that calculates nadj adjoint derivatives.
Function derivative (int nfwd, int nadj)
Get a function that calculates nfwd forward derivatives and nadj adjoint derivatives Legacy function: Use forward and reverse instead.
std::vector< MX > map (const std::vector< MX > &arg, const std::string &parallelization="serial")
Evaluate symbolically in parallel (matrix graph)
std::map< std::string, MX > map (const std::map< std::string, MX > &arg, const std::string &parallelization="serial")
Evaluate symbolically in parallel (matrix graph)
std::vector< MX > mapsum (const std::vector< MX > &arg, const std::string &parallelization="serial")
Evaluate symbolically in parallel and sum (matrix graph)
Function slice (const std::vector< int > &order_in, const std::vector< int > &order_out, const Dict &opts=Dict())
returns a new function with a selection of inputs/outputs of the original
Function kernel_sum (const std::string &name, const std::pair< int, int > &size, double r, int n, const Dict &opts=Dict()) const
void set_forward (const Function &fcn, int nfwd)
Set a function that calculates nfwd forward derivatives NOTE: Does not take ownership, only weak references to the derivatives are kept internally.
void set_reverse (const Function &fcn, int nadj)
Set a function that calculates nadj adjoint derivatives NOTE: Does not take ownership, only weak references to the derivatives are kept internally.
void generate (const std::string &fname, const Dict &opts=Dict())
Export / Generate C code for the function.
void generate (const Dict &opts=Dict())
Export / Generate C code for the function.
void generate_dependencies (const std::string &fname, const Dict &opts=Dict())
Export / Generate C code for the dependency function.
FunctionInternal * get () const
Dict stats (int mem=0) const
Get all statistics obtained at the end of the last evaluate call.
SX free_sx () const
Get all the free variables of the function.
std::vector< MX > free_mx () const
Get all the free variables of the function.
bool has_free () const
Does the function have free variables.
void generate_lifted (Function &output_vdef_fcn, Function &output_vinit_fcn)
Extract the functions needed for the Lifted Newton method.
int getAlgorithmSize () const
Get the number of atomic operations.
int getWorkSize () const
Get the length of the work vector.
int getAtomicOperation (int k) const
Get an atomic operation operator index.
std::pair< int, int > getAtomicInput (int k) const
Get the (integer) input arguments of an atomic operation.
double getAtomicInputReal (int k) const
Get the floating point output argument of an atomic operation.
int getAtomicOutput (int k) const
Get the (integer) output argument of an atomic operation.
int n_nodes () const
Number of nodes in the algorithm.
bool spCanEvaluate (bool fwd)
Is the class able to propagate seeds through the algorithm?
size_t sz_arg () const
Get required length of arg field.
size_t sz_res () const
Get required length of res field.
size_t sz_iw () const
Get required length of iw field.
size_t sz_w () const
Get required length of w field.
void sz_work (size_t &sz_arg, size_t &sz_res, size_t &sz_iw, size_t &sz_w) const
Get number of temporary variables needed.
void set_work (const double **&arg, double **&res, int *&iw, double *&w, int mem=0) const
Set the (persistent) work vectors.
void set_temp (const double **arg, double **res, int *iw, double *w, int mem=0) const
Set the (temporary) work vectors.
void setup (const double **arg, double **res, int *iw, double *w, int mem=0) const
Set the (persistent and temporary) work vectors.
void addMonitor (const std::string &mon)
Add modules to be monitored.
void removeMonitor (const std::string &mon)
Remove modules to be monitored.
void checkInputs () const
Check if the numerical values of the supplied bounds make sense.
std::string name () const
Name of the function.
std::string type_name () const
Get type name.
bool is_a (const std::string &type, bool recursive=true) const
Check if the function is of a particular type Optionally check if name matches one of the base classes (default true)
int checkout ()
Checkout a memory object.
void release (int mem)
Release a memory object.
MX linsol_solve (const MX &A, const MX &B, bool tr=false)
Create a solve node.
void linsol_solve (double *x, int nrhs=1, bool tr=false, int mem=0) const
void * memory (int ind) const
Get memory object.
void linsol_factorize (const double *A, int mem=0) const
void linsol_solveL (double *x, int nrhs, bool tr, int mem=0) const
Solve the system of equations Lx = b Only when a Cholesky factorization is available.
Sparsity linsol_cholesky_sparsity (bool tr=false, int mem=0) const
Obtain a symbolic Cholesky factorization Only for Cholesky solvers.
DM linsol_cholesky (bool tr=false, int mem=0) const
Obtain a numeric Cholesky factorization Only for Cholesky solvers.
Function rootfinder_fun ()
Access rhs function for a rootfinder.
Function rootfinder_jac ()
Access Jacobian of the ths function for a rootfinder.
Function rootfinder_linsol ()
Access linear solver of a rootfinder.
Function integrator_dae ()
Get the DAE for an integrator.
void qpsol_debug (const std::string &filename) const
void qpsol_debug (std::ostream &file) const
template<typename M >
void construct (const string &name, const std::map< string, M > &dict, const vector< string > &argn, const vector< string > &resn, const Dict &opts)
template<typename M >
void construct (const string &name, const vector< M > &arg, const vector< M > &res, const vector< string > &argn, const vector< string > &resn, const Dict &opts)
void assignNode (SharedObjectNode *node)
void assignNodeNoCount (SharedObjectNode *node)
Assign the node to a node class pointer without reference counting.
int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
void repr (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a representation of the object.
void print (std::ostream &stream=casadi::userOut(), bool trailing_newline=true) const
Print a description of the object.
void printPtr (std::ostream &stream=casadi::userOut()) const
bool is_null () const
Is a null pointer?
WeakRef * weak ()
Get a weak reference to the object.
size_t __hash__ () const
Returns a number that is unique for a given Node. If the Object does not point to any node, "0" is returned.
std::string getDescription () const
Return a string with a description (for SWIG)
std::string getRepresentation () const
Return a string with a representation (for SWIG)
virtual bool has_jacobian () const
Return Jacobian of all input elements with respect to all output elements.
virtual Function get_jacobian (const std::string &name, const Dict &opts)
Return Jacobian of all input elements with respect to all output elements.
virtual Function get_forward (const std::string &name, int nfwd, Dict &opts)
Return function that calculates forward derivatives forward(nfwd) returns a cached instance if available, and calls Function get_forward(int nfwd) if no cached version is available.
virtual int get_n_forward () const
Return function that calculates forward derivatives forward(nfwd) returns a cached instance if available, and calls Function get_forward(int nfwd) if no cached version is available.
virtual Function get_reverse (const std::string &name, int nadj, Dict &opts)
Return function that calculates adjoint derivatives reverse(nadj) returns a cached instance if available, and calls Function get_reverse(int nadj) if no cached version is available.
virtual int get_n_reverse () const
Return function that calculates adjoint derivatives reverse(nadj) returns a cached instance if available, and calls Function get_reverse(int nadj) if no cached version is available.
Function expand () const
Expand a function to SX.
Function expand (const std::string &name, const Dict &opts=Dict()) const
Expand a function to SX.
int size1_in (int ind) const
Get input dimension.
int size1_in (const std::string &iname) const
Get input dimension.
int size2_in (int ind) const
Get input dimension.
int size2_in (const std::string &iname) const
Get input dimension.
std::pair< int, int > size_in (int ind) const
Get input dimension.
std::pair< int, int > size_in (const std::string &iname) const
Get input dimension.
int size1_out (int ind) const
Get output dimension.
int size1_out (const std::string &oname) const
Get output dimension.
int size2_out (int ind) const
Get output dimension.
int size2_out (const std::string &oname) const
Get output dimension.
std::pair< int, int > size_out (int ind) const
Get output dimension.
std::pair< int, int > size_out (const std::string &oname) const
Get output dimension.
int nnz_in () const
Get of number of input nonzeros For a particular input or for all for all of the inputs.
int nnz_in (int ind) const
Get of number of input nonzeros For a particular input or for all for all of the inputs.
int nnz_in (const std::string &iname) const
Get of number of input nonzeros For a particular input or for all for all of the inputs.
int nnz_out () const
Get of number of output nonzeros For a particular output or for all for all of the outputs.
int nnz_out (int ind) const
Get of number of output nonzeros For a particular output or for all for all of the outputs.
int nnz_out (const std::string &oname) const
Get of number of output nonzeros For a particular output or for all for all of the outputs.
int numel_in () const
Get of number of input elements For a particular input or for all for all of the inputs.
int numel_in (int ind) const
Get of number of input elements For a particular input or for all for all of the inputs.
int numel_in (const std::string &iname) const
Get of number of input elements For a particular input or for all for all of the inputs.
int numel_out () const
Get of number of output elements For a particular output or for all for all of the outputs.
int numel_out (int ind) const
Get of number of output elements For a particular output or for all for all of the outputs.
int numel_out (const std::string &oname) const
Get of number of output elements For a particular output or for all for all of the outputs.
const Sparsity & sparsity_in (int ind) const
Get sparsity of a given input.
const Sparsity & sparsity_in (const std::string &iname) const
Get sparsity of a given input.
const Sparsity & sparsity_out (int ind) const
Get sparsity of a given output.
const Sparsity & sparsity_out (const std::string &iname) const
Get sparsity of a given output.
Function jacobian (int iind=0, int oind=0, bool compact=false, bool symmetric=false)
Generate a Jacobian function of output oind with respect to input iind.
Function jacobian (const std::string &iind, int oind=0, bool compact=false, bool symmetric=false)
Generate a Jacobian function of output oind with respect to input iind.
Function jacobian (int iind, const std::string &oind, bool compact=false, bool symmetric=false)
Generate a Jacobian function of output oind with respect to input iind.
Function jacobian (const std::string &iind, const std::string &oind, bool compact=false, bool symmetric=false)
Generate a Jacobian function of output oind with respect to input iind.
Function gradient (int iind=0, int oind=0)
Generate a gradient function of output oind with respect to input iind.
Function gradient (const std::string &iind, int oind=0)
Generate a gradient function of output oind with respect to input iind.
Function gradient (int iind, const std::string &oind)
Generate a gradient function of output oind with respect to input iind.
Function gradient (const std::string &iind, const std::string &oind)
Generate a gradient function of output oind with respect to input iind.
Function tangent (int iind=0, int oind=0)
Generate a tangent function of output oind with respect to input iind.
Function tangent (const std::string &iind, int oind=0)
Generate a tangent function of output oind with respect to input iind.
Function tangent (int iind, const std::string &oind)
Generate a tangent function of output oind with respect to input iind.
Function tangent (const std::string &iind, const std::string &oind)
Generate a tangent function of output oind with respect to input iind.
Function hessian (int iind=0, int oind=0)
Generate a Hessian function of output oind with respect to input iind.
Function hessian (const std::string &iind, int oind=0)
Generate a Hessian function of output oind with respect to input iind.
Function hessian (int iind, const std::string &oind)
Generate a Hessian function of output oind with respect to input iind.
Function hessian (const std::string &iind, const std::string &oind)
Generate a Hessian function of output oind with respect to input iind.
void call (const std::vector< DM > &arg, std::vector< DM > &output_res, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically.
void call (const std::vector< SX > &arg, std::vector< SX > &output_res, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically.
void call (const std::vector< MX > &arg, std::vector< MX > &output_res, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically.
void call (const DMDict &arg, DMDict &output_res, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically.
void call (const SXDict &arg, SXDict &output_res, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically.
void call (const MXDict &arg, MXDict &output_res, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically.
std::vector< DM > operator() (const std::vector< DM > &arg)
std::vector< SX > operator() (const std::vector< SX > &arg)
std::vector< MX > operator() (const std::vector< MX > &arg)
const DMDict operator() (const DMDict &arg)
const SXDict operator() (const SXDict &arg)
const MXDict operator() (const MXDict &arg)
void operator() (std::vector< const double * > arg, std::vector< double * > res)
Evaluate with temporary memory allocation.
void operator() (std::vector< const bvec_t * > arg, std::vector< bvec_t * > res)
Evaluate with temporary memory allocation.
void operator() (std::vector< const SXElem * > arg, std::vector< SXElem * > res)
Evaluate with temporary memory allocation.
template<typename D >
void _call (std::vector< const D * > arg, std::vector< D * > res)
Evaluate with temporary memory allocation.
void operator() (VecArg arg, VecRes res)
Numerical evaluation.
void operator() (VecArg arg, MapRes res)
Numerical evaluation.
void operator() (VecArg arg, VPrRes res)
Numerical evaluation.
void operator() (VecArg arg, MPrRes res)
Numerical evaluation.
void operator() (MapArg arg, VecRes res)
Numerical evaluation.
void operator() (MapArg arg, MapRes res)
Numerical evaluation.
void operator() (MapArg arg, VPrRes res)
Numerical evaluation.
void operator() (MapArg arg, MPrRes res)
Numerical evaluation.
std::vector< DM > operator() (const DM &arg0)
std::vector< SX > operator() (const SX &arg0)
std::vector< MX > operator() (const MX &arg0)
void derivative (const DMVector &arg, DMVector &output_res, const DMVectorVector &fseed, DMVectorVector &output_fsens, const DMVectorVector &aseed, DMVectorVector &output_asens, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically with directional derivatives The first two arguments are the nondifferentiated inputs and results of the evaluation, the next two arguments are a set of forward directional seeds and the resulting forward directional derivatives, the length of the vector being the number of forward directions. The next two arguments are a set of adjoint directional seeds and the resulting adjoint directional derivatives, the length of the vector being the number of adjoint directions.
void derivative (const SXVector &arg, SXVector &output_res, const SXVectorVector &fseed, SXVectorVector &output_fsens, const SXVectorVector &aseed, SXVectorVector &output_asens, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically with directional derivatives The first two arguments are the nondifferentiated inputs and results of the evaluation, the next two arguments are a set of forward directional seeds and the resulting forward directional derivatives, the length of the vector being the number of forward directions. The next two arguments are a set of adjoint directional seeds and the resulting adjoint directional derivatives, the length of the vector being the number of adjoint directions.
void derivative (const MXVector &arg, MXVector &output_res, const MXVectorVector &fseed, MXVectorVector &output_fsens, const MXVectorVector &aseed, MXVectorVector &output_asens, bool always_inline=false, bool never_inline=false)
Evaluate the function symbolically or numerically with directional derivatives The first two arguments are the nondifferentiated inputs and results of the evaluation, the next two arguments are a set of forward directional seeds and the resulting forward directional derivatives, the length of the vector being the number of forward directions. The next two arguments are a set of adjoint directional seeds and the resulting adjoint directional derivatives, the length of the vector being the number of adjoint directions.
Function map (const std::string &name, const std::string &parallelization, int n, const std::vector< int > &reduce_in, const std::vector< int > &reduce_out, const Dict &opts=Dict())
Create a mapped version of this function.
Function map (const std::string &name, const std::string &parallelization, int n, const Dict &opts=Dict())
Create a mapped version of this function.
Function mapaccum (const std::string &name, int n, const Dict &opts=Dict())
Create a mapaccumulated version of this function.
Function mapaccum (const std::string &name, int n, const std::vector< int > &accum_in, const std::vector< int > &accum_out, const Dict &opts=Dict())
Create a mapaccumulated version of this function.
const Sparsity sparsity_jac (int iind=0, int oind=0, bool compact=false, bool symmetric=false)
const Sparsity sparsity_jac (const std::string &iind, int oind=0, bool compact=false, bool symmetric=false)
const Sparsity sparsity_jac (int iind, const std::string &oind, bool compact=false, bool symmetric=false)
const Sparsity sparsity_jac (const std::string &iind, const std::string &oind, bool compact=false, bool symmetric=false)
void set_jac_sparsity (const Sparsity &sp, int iind, int oind, bool compact=false)
void set_jac_sparsity (const Sparsity &sp, const std::string &iind, int oind, bool compact=false)
void set_jac_sparsity (const Sparsity &sp, int iind, const std::string &oind, bool compact=false)
void set_jac_sparsity (const Sparsity &sp, const std::string &iind, const std::string &oind, bool compact=false)
const SX sx_in (int iind) const
Get symbolic primitives equivalent to the input expressions There is no guarantee that subsequent calls return unique answers.
const SX sx_in (const std::string &iname) const
Get symbolic primitives equivalent to the input expressions There is no guarantee that subsequent calls return unique answers.
const std::vector< SX > sx_in () const
Get symbolic primitives equivalent to the input expressions There is no guarantee that subsequent calls return unique answers.
const MX mx_in (int ind) const
Get symbolic primitives equivalent to the input expressions There is no guarantee that subsequent calls return unique answers.
const MX mx_in (const std::string &iname) const
Get symbolic primitives equivalent to the input expressions There is no guarantee that subsequent calls return unique answers.
const std::vector< MX > mx_in () const
Get symbolic primitives equivalent to the input expressions There is no guarantee that subsequent calls return unique answers.
const SX sx_out (int oind) const
Get symbolic primitives equivalent to the output expressions There is no guarantee that subsequent calls return unique answers.
const SX sx_out (const std::string &oname) const
Get symbolic primitives equivalent to the output expressions There is no guarantee that subsequent calls return unique answers.
const std::vector< SX > sx_out () const
Get symbolic primitives equivalent to the output expressions There is no guarantee that subsequent calls return unique answers.
const MX mx_out (int ind) const
Get symbolic primitives equivalent to the output expressions There is no guarantee that subsequent calls return unique answers.
const MX mx_out (const std::string &oname) const
Get symbolic primitives equivalent to the output expressions There is no guarantee that subsequent calls return unique answers.
const std::vector< MX > mx_out () const
Get symbolic primitives equivalent to the output expressions There is no guarantee that subsequent calls return unique answers.
void linsol_spsolve (bvec_t *X, const bvec_t *B, bool tr=false) const
void linsol_spsolve (DM &X, const DM &B, bool tr=false) const
Static Public Member Functions
static Function create (const std::string &name, Callback *n, const Dict &opts=Dict())
Create an owning reference, given a pointer to a derived object.
static Function create (FunctionInternal *node)
Create from node.
static Function conditional (const std::string &name, const std::vector< Function > &f, const Function &f_def, const Dict &opts=Dict())
Constuct a switch function.
static Function if_else (const std::string &name, const Function &f_true, const Function &f_false, const Dict &opts=Dict())
Constructor (if-else)
static bool test_cast (const SharedObjectNode *ptr)
Check if a particular cast is allowed.
static bool check_name (const std::string &name)
Check if a string is a valid function name Valid function names consist of.
static std::string fix_name (const std::string &name)
Turn a string into a valid function name as defined by "check_name" Non-alphanumeric characters are converted into underscores and multiple consecutive undercores are dropped.
Protected Member Functions
void count_up ()
void count_down ()
void construct (const std::string &name, const std::vector< SX > &arg, const std::vector< SX > &res, const Dict &opts)
Called by constructors.
void construct (const std::string &name, const std::vector< MX > &arg, const std::vector< MX > &res, const Dict &opts)
Called by constructors.
template<typename M >
void construct (const std::string &name, const std::vector< M > &arg, const std::vector< M > &res, const std::vector< std::string > &argn, const std::vector< std::string > &resn, const Dict &opts)
Called by constructors.
template<typename M >
void construct (const std::string &name, const std::map< std::string, M > &dict, const std::vector< std::string > &argn, const std::vector< std::string > &resn, const Dict &opts)
Called by constructors.
Static Protected Member Functions
static bool proceed_to (std::istream &file, const std::string &str)
Helper function for parsing .casadi files.
std::vector< const double * > buf_in (VecArg arg) const
Supported arguments for numerical evaluation and converters.
std::vector< const double * > buf_in (MapArg arg) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (VecRes res) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (VPrRes res) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (MapRes res) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (MPrRes res) const
Supported arguments for numerical evaluation and converters.
typedef const std::vector
< std::vector< double > > & VecArg
Supported arguments for numerical evaluation and converters.
typedef std::vector
< std::vector< double > > & VecRes
Supported arguments for numerical evaluation and converters.
typedef std::vector
< std::vector< double > * > VPrRes
Supported arguments for numerical evaluation and converters.
typedef const std::map
< std::string, std::vector
< double > > & MapArg
Supported arguments for numerical evaluation and converters.
typedef std::map< std::string,
std::vector< double > > & MapRes
Supported arguments for numerical evaluation and converters.
typedef std::map< std::string,
std::vector< double > * > MPrRes
Supported arguments for numerical evaluation and converters.
Member Typedef Documentation
typedef const std::map<std::string, std::vector<double> >& casadi::Function::MapArg inherited
Definition at line 439 of file function.hpp.
typedef std::map<std::string, std::vector<double> >& casadi::Function::MapRes inherited
Definition at line 441 of file function.hpp.
typedef std::map<std::string, std::vector<double>*> casadi::Function::MPrRes inherited
Definition at line 443 of file function.hpp.
typedef const std::vector<std::vector<double> >& casadi::Function::VecArg inherited
Definition at line 432 of file function.hpp.
typedef std::vector<std::vector<double> >& casadi::Function::VecRes inherited
Definition at line 434 of file function.hpp.
typedef std::vector<std::vector<double>*> casadi::Function::VPrRes inherited
Definition at line 436 of file function.hpp.
Constructor & Destructor Documentation
casadi::Callback::Callback ()
Definition at line 31 of file callback.cpp.
                      {
   }
casadi::Callback::Callback (const Callback & obj)
Definition at line 34 of file callback.cpp.
                                         : Function(obj) {
     casadi_error("Callback objects cannot be copied");
   }
casadi::Callback::~Callback () virtual
Definition at line 43 of file callback.cpp.
References casadi::SharedObject::is_null().
                       {
     // Make sure that this object isn't used after its deletion
     if (!is_null()) {
       (*this)->self_ = 0;
     }
   }
Member Function Documentation
size_t casadi::SharedObject::__hash__ () const inherited
Definition at line 178 of file shared_object.cpp.
{
     return reinterpret_cast<size_t>(get());
   }
template<typename D > void casadi::Function::_call (vector< const D * > arg, vector< D * > res) inherited
Definition at line 356 of file function.cpp.
References casadi::get_ptr().
{
     // Input buffer
     casadi_assert(arg.size()>=n_in());
     arg.resize(sz_arg());
     // Output buffer
     casadi_assert(res.size()>=n_out());
     res.resize(sz_res());
     // Work vectors
     vector<int> iw(sz_iw());
     vector<D> w(sz_w());
     // Evaluate memoryless
     (*this)(get_ptr(arg), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
   }
template<typename D > void casadi::Function::_call (std::vector< const D * > arg, std::vector< D * > res) inherited
template<typename M > void casadi::Function::_call (const std::map< std::string, M > & arg, std::map< std::string, M > & res, bool always_inline, bool never_inline) inherited
template<typename M > void casadi::Function::_call (const std::map< string, M > & arg, std::map< string, M > & res, bool always_inline, bool never_inline) inherited
Definition at line 1059 of file function.cpp.
{
     // Get default inputs
     vector<M> arg_v(n_in());
     for (int i=0; i<arg_v.size(); ++i) {
       arg_v[i] = default_in(i);
     }
     // Assign provided inputs
     for (auto&& e : arg) {
       arg_v.at(index_in(e.first)) = e.second;
     }
     // Make call
     vector<M> res_v;
     call(arg_v, res_v, always_inline, never_inline);
     // Save to map
     res.clear();
     for (int i=0; i<res_v.size(); ++i) {
       res[name_out(i)] = res_v[i];
     }
   }
void casadi::Function::addMonitor (const std::string & mon) inherited
Definition at line 604 of file function.cpp.
References casadi::FunctionInternal::monitors_.
{
     (*this)->monitors_.insert(mon);
   }
void casadi::SharedObject::assignNode (SharedObjectNode * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 57 of file shared_object.cpp.
Referenced by casadi::Function::conditional(), construct(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::Sparsity::create(), casadi::Function::create(), casadi::external(), casadi::Function::if_else(), casadi::MXFunction::init(), casadi::integrator(), casadi::jit(), casadi::Function::kernel_sum(), casadi::linsol(), casadi::nlpsol(), casadi::qpsol(), casadi::rootfinder(), and casadi::WeakRef::shared().
{
     count_down();
     node = node_;
     count_up();
   }
void casadi::SharedObject::assignNodeNoCount (SharedObjectNode * node) inherited
improper use will cause memory leaks!
Definition at line 63 of file shared_object.cpp.
{
     node = node_;
   }
vector< const double * > casadi::Function::buf_in (Function::VecArg arg) const inherited
Definition at line 278 of file function.cpp.
References casadi::get_ptr().
{
     casadi_assert(arg.size()==n_in());
     auto arg_it=arg.begin();
     vector<const double*> buf_arg(sz_arg());
     for (unsigned int i=0; i<arg.size(); ++i) {
       casadi_assert(arg_it->size()==nnz_in(i));
       buf_arg[i] = get_ptr(*arg_it++);
     }
     return buf_arg;
   }
vector< const double * > casadi::Function::buf_in (Function::MapArg arg) const inherited
Definition at line 312 of file function.cpp.
References casadi::get_ptr().
{
     // Return value (RVO)
     vector<const double*> ret(sz_arg(), 0);
     // Read inputs
     for (auto i=arg.begin(); i!=arg.end(); ++i) {
       int ind = index_in(i->first);
       casadi_assert(i->second.size()==nnz_in(ind));
       ret[ind] = get_ptr(i->second);
     }
     return ret;
   }
vector< double * > casadi::Function::buf_out (Function::VecRes res) const inherited
Definition at line 289 of file function.cpp.
References casadi::get_ptr().
{
     res.resize(n_out());
     auto res_it=res.begin();
     vector<double*> buf_res(sz_res());
     for (unsigned int i=0; i<res.size(); ++i) {
       res_it->resize(nnz_out(i));
       buf_res[i] = get_ptr(*res_it++);
     }
     return buf_res;
   }
vector< double * > casadi::Function::buf_out (Function::VPrRes res) const inherited
Definition at line 300 of file function.cpp.
References casadi::get_ptr().
{
     casadi_assert(res.size()==n_out());
     auto res_it=res.begin();
     vector<double*> buf_res(sz_res());
     for (unsigned int i=0; i<res.size(); ++i) {
       casadi_assert(*res_it!=0);
       (*res_it)->resize(nnz_out(i));
       buf_res[i] = get_ptr(**res_it++);
     }
     return buf_res;
   }
vector< double * > casadi::Function::buf_out (Function::MapRes res) const inherited
Definition at line 326 of file function.cpp.
References casadi::get_ptr().
{
     // Return value (RVO)
     vector<double*> ret(sz_res(), 0);
     // Read outputs
     for (auto i=res.begin(); i!=res.end(); ++i) {
       int ind = index_out(i->first);
       i->second.resize(nnz_out(ind));
       ret[ind] = get_ptr(i->second);
     }
     return ret;
   }
vector< double * > casadi::Function::buf_out (Function::MPrRes res) const inherited
Definition at line 340 of file function.cpp.
References casadi::get_ptr().
{
     // Return value (RVO)
     vector<double*> ret(sz_res(), 0);
     // Read outputs
     for (auto i=res.begin(); i!=res.end(); ++i) {
       int ind = index_out(i->first);
       casadi_assert(i->second!=0);
       i->second->resize(nnz_out(ind));
       ret[ind] = get_ptr(*i->second);
     }
     return ret;
   }
void casadi::Function::call (const std::vector< DM > & arg, std::vector< DM > & output_res, bool always_inline = false, bool never_inline = false) inherited
Referenced by casadi::FunctionInternal::eval_mx(), casadi::MX::matrix_expand(), and casadi::MX::substitute().
void casadi::Function::call (const std::vector< SX > & arg, std::vector< SX > & output_res, bool always_inline = false, bool never_inline = false) inherited
void casadi::Function::call (const std::vector< MX > & arg, std::vector< MX > & output_res, bool always_inline = false, bool never_inline = false) inherited
void casadi::Function::call (const DMDict & arg, DMDict & output_res, bool always_inline = false, bool never_inline = false) inherited
Definition at line 1101 of file function.cpp.
{
     return _call(arg, res, always_inline, never_inline);
   }
void casadi::Function::call (const SXDict & arg, SXDict & output_res, bool always_inline = false, bool never_inline = false) inherited
Definition at line 1106 of file function.cpp.
{
     return _call(arg, res, always_inline, never_inline);
   }
void casadi::Function::call (const MXDict & arg, MXDict & output_res, bool always_inline = false, bool never_inline = false) inherited
Definition at line 1111 of file function.cpp.
{
     return _call(arg, res, always_inline, never_inline);
   }
bool casadi::Function::check_name (const std::string & name) static inherited
At least one character
Upper and lower case letters: a-zA-Z
Numbers 0-9, but never as first character
Underscore, but never as first character and never next to another underscore
May not be one of the following keywords: "null", "jac", "hess"
Definition at line 935 of file function.cpp.
Referenced by casadi::FunctionInternal::FunctionInternal().
{
     // Check if empty
     if (name.empty()) return false;
     // Check if keyword
     for (const char* kw : {"null", "jac", "hess"}) {
       if (name.compare(kw)==0) return false;
     }
     // Make sure that the first character is a letter
     auto it=name.begin();
     if (!std::isalpha(*it++)) return false;
     // Check remain_ing characters
     for (; it!=name.end(); ++it) {
       if (*it=='_') {
         // Make sure that the next character isn't also an underscore
         if (it+1!=name.end() && *(it+1)=='_') return false;
       } else {
         // Make sure alphanumeric
         if (!std::isalnum(*it)) return false;
       }
     }
     // Valid function name if reached this point
     return true;
   }
void casadi::Function::checkInputs () const inherited
Definition at line 896 of file function.cpp.
{
     return (*this)->checkInputs();
   }
int casadi::Function::checkout () inherited
Definition at line 1212 of file function.cpp.
{
     return (*this)->checkout();
   }
Function casadi::Function::conditional (const std::string & name, const std::vector< Function > & f, const Function & f_def, const Dict & opts = Dict()) static inherited
Definition at line 482 of file function.cpp.
References casadi::SharedObject::assignNode(), and casadi::FunctionInternal::construct().
Referenced by casadi::Switch::get_forward(), and casadi::Switch::get_reverse().
{
     Function ret;
     ret.assignNode(new Switch(name, f, f_def));
     ret->construct(opts);
     return ret;
   }
void casadi::Callback::construct (const std::string & name, const Dict & opts = Dict())
Definition at line 38 of file callback.cpp.
References casadi::SharedObject::assignNode().
{
     assignNode(new CallbackInternal(name, this));
     (*this)->construct(opts);
   }
template<typename M > void casadi::Function::construct (const string & name, const std::map< string, M > & dict, const vector< string > & argn, const vector< string > & resn, const Dict & opts) inherited
Definition at line 188 of file function.cpp.
{
     vector<M> arg(argn.size()), res(resn.size());
     for (auto&& i : dict) {
       vector<string>::const_iterator it;
       if ((it=find(argn.begin(), argn.end(), i.first))!=argn.end()) {
         // Input expression
         arg[it-argn.begin()] = i.second;
       } else if ((it=find(resn.begin(), resn.end(), i.first))!=resn.end()) {
         // Output expression
         res[it-resn.begin()] = i.second;
       } else {
         // Neither
         casadi_error("Unknown dictionary entry: '" + i.first + "'");
       }
     }
     construct(name, arg, res, argn, resn, opts);
   }
template<typename M > void casadi::Function::construct (const string & name, const vector< M > & arg, const vector< M > & res, const vector< string > & argn, const vector< string > & resn, const Dict & opts) inherited
Definition at line 224 of file function.cpp.
{
     Dict opts2 = opts;
     opts2["input_scheme"] = argn;
     opts2["output_scheme"] = resn;
     construct(name, arg, res, opts2);
   }
void casadi::Function::construct (const std::string & name, const std::vector< SX > & arg, const std::vector< SX > & res, const Dict & opts) protected inherited
void casadi::Function::construct (const std::string & name, const std::vector< MX > & arg, const std::vector< MX > & res, const Dict & opts) protected inherited
template<typename M > void casadi::Function::construct (const std::string & name, const std::vector< M > & arg, const std::vector< M > & res, const std::vector< std::string > & argn, const std::vector< std::string > & resn, const Dict & opts) protected inherited
template<typename M > void casadi::Function::construct (const std::string & name, const std::map< std::string, M > & dict, const std::vector< std::string > & argn, const std::vector< std::string > & resn, const Dict & opts) protected inherited
void casadi::SharedObject::count_down () protected inherited
Definition at line 92 of file shared_object.cpp.
Referenced by transfer_ownership().
{
     if (node && --node->count == 0) {
       delete node;
       node = 0;
     }
   }
void casadi::SharedObject::count_up () protected inherited
Definition at line 88 of file shared_object.cpp.
{
     if (node) node->count++;
   }
Function casadi::Callback::create (const std::string & name, Callback * n, const Dict & opts = Dict()) static
Examples:
Function/callback_c.cc.
Definition at line 50 of file callback.cpp.
References casadi::FunctionInternal::construct().
{
     n->construct(name, opts);
     Function ret = *n;
     n->transfer_ownership();
     return ret;
   }
Function casadi::Function::create (FunctionInternal * node) static inherited
Definition at line 249 of file function.cpp.
References casadi::SharedObject::assignNode().
{
     Function ret;
     ret.assignNode(node);
     return ret;
   }
double casadi::Function::default_in (int ind) const inherited
Definition at line 1116 of file function.cpp.
{
     return (*this)->default_in(ind);
   }
void casadi::Function::derivative (const DMVector & arg, DMVector & output_res, const DMVectorVector & fseed, DMVectorVector & output_fsens, const DMVectorVector & aseed, DMVectorVector & output_asens, bool always_inline = false, bool never_inline = false) inherited
Definition at line 900 of file function.cpp.
References casadi::reverse().
Referenced by casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::KinsolInterface::init(), casadi::IdasInterface::init(), casadi::CvodesInterface::init(), and casadi::Scpgen::init().
{
     call(arg, res, always_inline, never_inline);
     forward(arg, res, fseed, fsens, always_inline, never_inline);
     reverse(arg, res, aseed, asens, always_inline, never_inline);
   }
void casadi::Function::derivative (const SXVector & arg, SXVector & output_res, const SXVectorVector & fseed, SXVectorVector & output_fsens, const SXVectorVector & aseed, SXVectorVector & output_asens, bool always_inline = false, bool never_inline = false) inherited
Definition at line 909 of file function.cpp.
References casadi::reverse().
{
     call(arg, res, always_inline, never_inline);
     forward(arg, res, fseed, fsens, always_inline, never_inline);
     reverse(arg, res, aseed, asens, always_inline, never_inline);
   }
void casadi::Function::derivative (const MXVector & arg, MXVector & output_res, const MXVectorVector & fseed, MXVectorVector & output_fsens, const MXVectorVector & aseed, MXVectorVector & output_asens, bool always_inline = false, bool never_inline = false) inherited
Definition at line 918 of file function.cpp.
References casadi::reverse().
{
     call(arg, res, always_inline, never_inline);
     forward(arg, res, fseed, fsens, always_inline, never_inline);
     reverse(arg, res, aseed, asens, always_inline, never_inline);
   }
Function casadi::Function::derivative (int nfwd, int nadj) inherited
Returns a function with (1+nfwd)*n_in+nadj*n_out inputs and (1+nfwd)*n_out + nadj*n_in outputs. The first n_in inputs correspond to nondifferentiated inputs. The next nfwd*n_in inputs correspond to forward seeds, one direction at a time and the last nadj*n_out inputs correspond to adjoint seeds, one direction at a time. The first n_out outputs correspond to nondifferentiated outputs. The next nfwd*n_out outputs correspond to forward sensitivities, one direction at a time and the last nadj*n_in outputs corresponds to adjoint sensitivities, one direction at a time.
(n_in = n_in(), n_out = n_out())
Definition at line 703 of file function.cpp.
References casadi::copy(), casadi::Function::mx_in(), casadi::project(), and casadi::reverse().
{
     // Quick return
     if (nfwd==0 && nadj==0) return *this;
     // Call self
     vector<MX> arg = mx_in();
     vector<MX> res = (*this)(arg);
     vector<MX> ret_in(arg), ret_out(res);
     // Number inputs and outputs
     int num_in = n_in();
     int num_out = n_out();
     // Forward sensitivities
     if (nfwd>0) {
       Function dfcn = forward(nfwd);
       arg = dfcn.mx_in();
       copy(ret_in.begin(), ret_in.begin()+num_in, arg.begin());
       copy(ret_out.begin(), ret_out.begin()+num_out, arg.begin()+num_in);
       ret_in.insert(ret_in.end(), arg.begin()+num_in+num_out, arg.end());
       res = dfcn(arg);
       vector<MX>::iterator it=res.begin();
       for (int d=0; d<nfwd; ++d)
         for (int i=0; i<num_out; ++i, ++it)
           *it = project(*it, sparsity_out(i));
       ret_out.insert(ret_out.end(), res.begin(), res.end());
     }
     // Adjoint sensitivities
     if (nadj>0) {
       Function dfcn = reverse(nadj);
       arg = dfcn.mx_in();
       copy(ret_in.begin(), ret_in.begin()+num_in, arg.begin());
       copy(ret_out.begin(), ret_out.begin()+num_out, arg.begin()+num_in);
       ret_in.insert(ret_in.end(), arg.begin()+num_in+num_out, arg.end());
       res = dfcn(arg);
       vector<MX>::iterator it=res.begin();
       for (int d=0; d<nadj; ++d)
         for (int i=0; i<num_in; ++i, ++it)
           *it = project(*it, sparsity_in(i));
       ret_out.insert(ret_out.end(), res.begin(), res.end());
     }
     // Name of return function
     stringstream ss;
     ss << "derivative_" << name() << "_" << nfwd << "_" << nadj;
     // Names of inputs
     vector<string> i_names;
     i_names.reserve(n_in()*(1+nfwd)+n_out()*nadj);
     const vector<string>& ischeme=(*this)->ischeme_;
     const vector<string>& oscheme=(*this)->oscheme_;
     // Nondifferentiated inputs
     for (int i=0; i<n_in(); ++i) {
       i_names.push_back("der_" + ischeme.at(i));
     }
     // Forward seeds
     for (int d=0; d<nfwd; ++d) {
       for (int i=0; i<n_in(); ++i) {
         ss.str(string());
         ss << "fwd" << d << "_" << ischeme.at(i);
         i_names.push_back(ss.str());
       }
     }
     // Adjoint seeds
     for (int d=0; d<nadj; ++d) {
       for (int i=0; i<n_out(); ++i) {
         ss.str(string());
         ss << "adj" << d << "_" << oscheme.at(i);
         i_names.push_back(ss.str());
       }
     }
     // Names of outputs
     vector<string> o_names;
     o_names.reserve(n_out()*(1+nfwd)+n_in()*nadj);
     // Nondifferentiated inputs
     for (int i=0; i<n_out(); ++i) {
       o_names.push_back("der_" + oscheme.at(i));
     }
     // Forward sensitivities
     for (int d=0; d<nfwd; ++d) {
       for (int i=0; i<n_out(); ++i) {
         ss.str(string());
         ss << "fwd" << d << "_" << oscheme.at(i);
         o_names.push_back(ss.str());
       }
     }
     // Adjoint sensitivities
     for (int d=0; d<nadj; ++d) {
       for (int i=0; i<n_in(); ++i) {
         ss.str(string());
         ss << "adj" << d << "_" << ischeme.at(i);
         o_names.push_back(ss.str());
       }
     }
     // Construct return function
     Function ret(ss.str(), ret_in, ret_out,
                  {{"input_scheme", i_names}, {"output_scheme", o_names}});
     // Consistency check for inputs
     int ind=0;
     for (int d=-1; d<nfwd; ++d) {
       for (int i=0; i<n_in(); ++i, ++ind) {
         if (ret.nnz_in(ind)!=0 && ret.sparsity_in(ind)!=sparsity_in(i)) {
           casadi_error("Incorrect sparsity for " << ret << " input " << ind << " \""
                        << i_names.at(ind) << "\". Expected " << size_in(i)
                        << " but got " << ret.size_in(ind));
         }
       }
     }
     for (int d=0; d<nadj; ++d) {
       for (int i=0; i<n_out(); ++i, ++ind) {
         if (ret.nnz_in(ind)!=0 && ret.sparsity_in(ind)!=sparsity_out(i)) {
           casadi_error("Incorrect sparsity for " << ret << " input " << ind <<
                        " \"" << i_names.at(ind) << "\". Expected " << size_out(i)
                        << " but got " << ret.size_in(ind));
         }
       }
     }
     // Consistency check for outputs
     ind=0;
     for (int d=-1; d<nfwd; ++d) {
       for (int i=0; i<n_out(); ++i, ++ind) {
         if (ret.nnz_out(ind)!=0 && ret.sparsity_out(ind)!=sparsity_out(i)) {
           casadi_error("Incorrect sparsity for " << ret << " output " << ind <<
                        " \"" <<  o_names.at(ind) << "\". Expected " << size_out(i)
                        << " but got " << ret.size_out(ind));
         }
       }
     }
     for (int d=0; d<nadj; ++d) {
       for (int i=0; i<n_in(); ++i, ++ind) {
         if (ret.nnz_out(ind)!=0 && ret.sparsity_out(ind)!=sparsity_in(i)) {
           casadi_error("Incorrect sparsity for " << ret << " output " << ind << " \""
                        << o_names.at(ind) << "\". Expected " << size_in(i)
                        << " but got " << ret.size_out(ind));
         }
       }
     }
     return ret;
   }
std::vector< DM > casadi::Callback::eval (const std::vector< DM > & arg) virtual
Definition at line 57 of file callback.cpp.
Referenced by eval().
{
     casadi_error("Callback::eval has not been implemented");
     return std::vector<DM>();
   }
void casadi::Callback::eval (const double ** arg, double ** res, int * iw, double * w, int mem) virtual
Definition at line 62 of file callback.cpp.
References eval(), casadi::Function::n_in(), casadi::Function::n_out(), and casadi::Function::sparsity_in().
{
     // Allocate input matrices
     int n_in = this->n_in();
     std::vector<DM> argv(n_in);
     for (int i=0; i<n_in; ++i) {
       argv[i] = DM(sparsity_in(i));
       casadi_copy(arg[i], argv[i].nnz(), argv[i].ptr());
     }
     // Evaluate
     std::vector<DM> resv = eval(argv);
     // Get the outputs
     int n_out = this->n_out();
     for (int i=0; i<n_out; ++i) {
       casadi_copy(resv[i].ptr(), resv[i].nnz(), res[i]);
     }
   }
Function casadi::Function::expand () const inherited
Examples:
Function/expand.py, and MX/matrix_expand.py.
Definition at line 234 of file function.cpp.
Referenced by casadi::Oracle::expand(), and casadi::MX::matrix_expand().
{
     return expand(name());
   }
Function casadi::Function::expand (const std::string & name, const Dict & opts = Dict()) const inherited
virtual void casadi::Callback::finalize () inline virtual
Definition at line 94 of file casadi/core/function/callback.hpp.
 {}
string casadi::Function::fix_name (const std::string & name) static inherited
Definition at line 963 of file function.cpp.
{
     // Quick return if already valid name
     if (check_name(name)) return name;
     // If empty, name it "unnamed"
     if (name.empty()) return "unnamed";
     // Construct a sane name
     stringstream ss;
     // If the first character isn't a character, prepend an "a"
     if (!std::isalpha(name.front())) ss << "a";
     // Treat other characters
     bool previous_is_underscore = false;
     for (char c : name) {
       if (std::isalnum(c)) {
         // Alphanumeric characters
         ss << c;
         previous_is_underscore = false;
       } else if (!previous_is_underscore) {
         // Everything else becomes an underscore
         ss << '_';
         previous_is_underscore = true;
       }
     }
     // If name became a keyword, append 1
     for (const char* kw : {"null", "jac", "hess"}) {
       if (ss.str().compare(kw)==0) ss << "1";
     }
     return ss.str();
   }
void casadi::Function::forward (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & output_fsens, bool always_inline = false, bool never_inline = false) inherited
Referenced by casadi::Call::evalFwd(), casadi::Rootfinder::forward(), casadi::Switch::get_forward(), casadi::KernelSum::get_forward(), casadi::Mapaccum::get_forward(), casadi::PureMap::get_forward(), and casadi::MapSum::get_forward().
void casadi::Function::forward (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & fseed, std::vector< std::vector< SX > > & output_fsens, bool always_inline = false, bool never_inline = false) inherited
void casadi::Function::forward (const std::vector< DM > & arg, const std::vector< DM > & res, const std::vector< std::vector< DM > > & fseed, std::vector< std::vector< DM > > & output_fsens, bool always_inline = false, bool never_inline = false) inherited
Function casadi::Function::forward (int nfwd) inherited
Returns a function with n_in + n_out +nfwd*n_in inputs and nfwd*n_out outputs. The first n_in inputs correspond to nondifferentiated inputs. The next n_out inputs correspond to nondifferentiated outputs. and the last nfwd*n_in inputs correspond to forward seeds, one direction at a time The nfwd*n_out outputs correspond to forward sensitivities, one direction at a time. * (n_in = n_in(), n_out = n_out())
The functions returned are cached, meaning that if called multiple timed with the same value, then multiple references to the same function will be returned.
Definition at line 854 of file function.cpp.
References casadi::FunctionInternal::forward().
{
     return (*this)->forward(nfwd);
   }
vector< MX > casadi::Function::free_mx () const inherited
Definition at line 1172 of file function.cpp.
Referenced by casadi::XOracle< XType >::create(), and casadi::MX::symvar().
{
     return (*this)->free_mx();
   }
SX casadi::Function::free_sx () const inherited
Definition at line 1168 of file function.cpp.
Referenced by casadi::XOracle< XType >::create().
{
     return (*this)->free_sx();
   }
Function casadi::Function::fullJacobian () inherited
Definition at line 592 of file function.cpp.
References casadi::FunctionInternal::fullJacobian().
{
     return (*this)->fullJacobian();
   }
void casadi::Function::generate (const std::string & fname, const Dict & opts = Dict()) inherited
Examples:
SX/generateCode.py.
void casadi::Function::generate (const Dict & opts = Dict()) inherited
Definition at line 882 of file function.cpp.
{
     generate(name(), opts);
   }
void casadi::Function::generate_dependencies (const std::string & fname, const Dict & opts = Dict()) inherited
Definition at line 892 of file function.cpp.
{
     (*this)->generate_dependencies(fname, opts);
   }
void casadi::Function::generate_lifted (Function & output_vdef_fcn, Function & output_vinit_fcn) inherited
Definition at line 1180 of file function.cpp.
Referenced by casadi::Scpgen::init().
{
     (*this)->generate_lifted(vdef_fcn, vinit_fcn);
   }
FunctionInternal * casadi::Function::get () const inherited
Get a const pointer to the node
Definition at line 259 of file function.cpp.
Referenced by casadi::Call::codegen_decref(), casadi::Call::codegen_incref(), casadi::XFunction< DerivedType, MatType, NodeType >::forward_x(), casadi::XFunction< DerivedType, MatType, NodeType >::reverse_x(), and casadi::MX::substitute_inplace().
{
     return static_cast<FunctionInternal*>(SharedObject::get());
   }
Function casadi::Callback::get_forward (const std::string & name, int nfwd, Dict & opts) virtual
Definition at line 121 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_forward(name, nfwd, opts);
   }
Function casadi::Callback::get_jacobian (const std::string & name, const Dict & opts) virtual
Definition at line 117 of file callback.cpp.
{
     return (*this)->FunctionInternal::getFullJacobian(name, opts);
   }
int casadi::Callback::get_n_forward () const virtual
Definition at line 125 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_n_forward();
   }
int casadi::Callback::get_n_in () virtual
Definition at line 89 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_n_in();
   }
int casadi::Callback::get_n_out () virtual
Definition at line 93 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_n_out();
   }
int casadi::Callback::get_n_reverse () const virtual
Definition at line 133 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_n_reverse();
   }
std::string casadi::Callback::get_name_in (int i) virtual
Definition at line 105 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_name_in(i);
   }
std::string casadi::Callback::get_name_out (int i) virtual
Definition at line 109 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_name_out(i);
   }
Function casadi::Callback::get_reverse (const std::string & name, int nadj, Dict & opts) virtual
Definition at line 129 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_reverse(name, nadj, opts);
   }
Sparsity casadi::Callback::get_sparsity_in (int i) virtual
Definition at line 97 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_sparsity_in(i);
   }
Sparsity casadi::Callback::get_sparsity_out (int i) virtual
Definition at line 101 of file callback.cpp.
{
     return (*this)->FunctionInternal::get_sparsity_out(i);
   }
int casadi::Function::getAlgorithmSize () const inherited
Definition at line 1184 of file function.cpp.
{
     return (*this)->getAlgorithmSize();
   }
pair< int, int > casadi::Function::getAtomicInput (int k) const inherited
Definition at line 1196 of file function.cpp.
{
     return (*this)->getAtomicInput(k);
   }
double casadi::Function::getAtomicInputReal (int k) const inherited
Definition at line 1200 of file function.cpp.
{
     return (*this)->getAtomicInputReal(k);
   }
int casadi::Function::getAtomicOperation (int k) const inherited
Definition at line 1192 of file function.cpp.
{
     return (*this)->getAtomicOperation(k);
   }
int casadi::Function::getAtomicOutput (int k) const inherited
Definition at line 1204 of file function.cpp.
{
     return (*this)->getAtomicOutput(k);
   }
int casadi::SharedObject::getCount () const inherited
Definition at line 159 of file shared_object.cpp.
References casadi::SharedObjectNode::getCount().
Referenced by transfer_ownership().
{
     return (*this)->getCount();
   }
std::string casadi::PrintableObject< SharedObject >::getDescription () const inline inherited
Definition at line 49 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->print(ss, false);
       return ss.str();
     }
std::string casadi::PrintableObject< SharedObject >::getRepresentation () const inline inherited
Definition at line 56 of file printable_object.hpp.
{
       std::stringstream ss;
       static_cast<const Derived*>(this)->repr(ss, false);
       return ss.str();
     }
int casadi::Function::getWorkSize () const inherited
Definition at line 1188 of file function.cpp.
{
     return (*this)->getWorkSize();
   }
Function casadi::Function::gradient (int iind = 0, int oind = 0) inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the output must be scalar. In other cases, use the Jacobian instead.
Definition at line 580 of file function.cpp.
References casadi::FunctionInternal::gradient().
Referenced by casadi::FunctionInternal::getGradient().
{
     return (*this)->gradient(iind, oind);
   }
Function casadi::Function::gradient (const std::string & iind, int oind = 0) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the output must be scalar. In other cases, use the Jacobian instead.
Definition at line 339 of file function.hpp.
{
         return gradient(index_in(iind), oind);
     }
Function casadi::Function::gradient (int iind, const std::string & oind) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the output must be scalar. In other cases, use the Jacobian instead.
Definition at line 342 of file function.hpp.
{
         return gradient(iind, index_out(oind));
     }
Function casadi::Function::gradient (const std::string & iind, const std::string & oind) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the output must be scalar. In other cases, use the Jacobian instead.
Definition at line 345 of file function.hpp.
{
         return gradient(index_in(iind), index_out(oind));
     }
bool casadi::Function::has_free () const inherited
Definition at line 1176 of file function.cpp.
Referenced by casadi::XOracle< XType >::create().
{
     return (*this)->has_free();
   }
bool casadi::Callback::has_jacobian () const virtual
Definition at line 113 of file callback.cpp.
{
     return (*this)->FunctionInternal::hasFullJacobian();
   }
Function casadi::Function::hessian (int iind = 0, int oind = 0) inherited
Parameters
iind The index of the input
oind The index of the output
The generated Hessian has two more outputs than the calling function corresponding to the Hessian and the gradients.
Definition at line 588 of file function.cpp.
References casadi::FunctionInternal::hessian().
{
     return (*this)->hessian(iind, oind);
   }
Function casadi::Function::hessian (const std::string & iind, int oind = 0) inline inherited
Parameters
iind The index of the input
oind The index of the output
The generated Hessian has two more outputs than the calling function corresponding to the Hessian and the gradients.
Definition at line 378 of file function.hpp.
     { return hessian(index_in(iind), oind); }
Function casadi::Function::hessian (int iind, const std::string & oind) inline inherited
Parameters
iind The index of the input
oind The index of the output
The generated Hessian has two more outputs than the calling function corresponding to the Hessian and the gradients.
Definition at line 380 of file function.hpp.
     { return hessian(iind, index_out(oind)); }
Function casadi::Function::hessian (const std::string & iind, const std::string & oind) inline inherited
Parameters
iind The index of the input
oind The index of the output
The generated Hessian has two more outputs than the calling function corresponding to the Hessian and the gradients.
Definition at line 382 of file function.hpp.
     { return hessian(index_in(iind), index_out(oind)); }
Function casadi::Function::if_else (const std::string & name, const Function & f_true, const Function & f_false, const Dict & opts = Dict()) static inherited
Definition at line 490 of file function.cpp.
References casadi::SharedObject::assignNode(), and casadi::FunctionInternal::construct().
{
     Function ret;
     ret.assignNode(new Switch(name, vector<Function>(1, f_false), f_true));
     ret->construct(opts);
     return ret;
   }
int casadi::Function::index_in (const std::string & name) const inherited
example: schemeEntry("x_opt") -> returns NLPSOL_X if FunctionInternal adheres to SCHEME_NLPINput
Definition at line 632 of file function.cpp.
Referenced by casadi::MX::grad(), casadi::MX::jac(), and casadi::MX::tang().
{
     return (*this)->index_in(name);
   }
int casadi::Function::index_out (const std::string & name) const inherited
example: schemeEntry("x_opt") -> returns NLPSOL_X if FunctionInternal adheres to SCHEME_NLPINput
Definition at line 636 of file function.cpp.
Referenced by casadi::MX::grad(), casadi::MX::jac(), and casadi::MX::tang().
{
     return (*this)->index_out(name);
   }
virtual void casadi::Callback::init () inline virtual
Definition at line 86 of file casadi/core/function/callback.hpp.
 {}
Function casadi::Function::integrator_dae () inherited
Definition at line 85 of file integrator.cpp.
References casadi::Integrator::f_.
{
     casadi_assert(!is_null());
     Integrator* n = dynamic_cast<Integrator*>(get());
     casadi_assert_message(n!=0, "Not an integrator");
     return n->f_;
   }
bool casadi::Function::is_a (const std::string & type, bool recursive = true) const inherited
Definition at line 1164 of file function.cpp.
Referenced by casadi::XOracle< XType >::create(), casadi::Oracle::expand(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), casadi::CvodesInterface::getJac(), casadi::IdasInterface::getJac(), casadi::CvodesInterface::getJacB(), casadi::IdasInterface::getJacB(), casadi::integrator(), and casadi::nlpsol().
{
     return (*this)->is_a(type, recursive);
   }
bool casadi::SharedObject::is_null () const inherited
Definition at line 84 of file shared_object.cpp.
Referenced by casadi::FunctionInternal::alloc(), casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::Integrator::fun2problem(), casadi::Switch::generateBody(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_out(), casadi::FunctionInternal::get_sparsity_out(), casadi::SundialsInterface::getBandwidth(), casadi::SundialsInterface::getBandwidthB(), casadi::FunctionInternal::getPartition(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Newton::init(), casadi::Integrator::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::FixedStepIntegrator::init(), casadi::CvodesInterface::init_memory(), casadi::IdasInterface::init_memory(), casadi::FixedStepIntegrator::init_memory(), casadi::CvodesInterface::initIterativeLinsol(), casadi::IdasInterface::initIterativeLinsol(), casadi::CvodesInterface::initIterativeLinsolB(), casadi::IdasInterface::initIterativeLinsolB(), casadi::CvodesInterface::initUserDefinedLinsol(), casadi::IdasInterface::initUserDefinedLinsol(), casadi::CvodesInterface::initUserDefinedLinsolB(), casadi::IdasInterface::initUserDefinedLinsolB(), casadi::Integrator::Integrator(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::Linsol::Linsol(), casadi::SparsityInternal::maxTransversal(), casadi::operator<<(), casadi::IdasInterface::psolveB(), casadi::Qpsol::Qpsol(), casadi::SnoptInterface::set_work(), casadi::RkIntegrator::setupFG(), casadi::CollocationIntegrator::setupFG(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Integrator::spAdj(), casadi::FunctionInternal::spAdj(), casadi::FunctionInternal::sparsity_jac(), casadi::Integrator::spFwd(), casadi::FunctionInternal::spFwd(), transfer_ownership(), casadi::Sparsity::uni_coloring(), casadi::SnoptInterface::userfun(), and ~Callback().
{
     return node==0;
   }
Function casadi::Function::jacobian (int iind = 0, int oind = 0, bool compact = false, bool symmetric = false) inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. If compact is set to true, only the nonzeros of the input and output expressions are considered. If symmetric is set to true, the Jacobian being calculated is known to be symmetric (usually a Hessian), which can be exploited by the algorithm.
The generated Jacobian has one more output than the calling function corresponding to the Jacobian and the same number of inputs.
Definition at line 572 of file function.cpp.
References casadi::FunctionInternal::jacobian().
Referenced by casadi::FunctionInternal::getHessian(), and casadi::Rootfinder::init().
{
     return (*this)->jacobian(iind, oind, compact, symmetric);
   }
Function casadi::Function::jacobian (const std::string & iind, int oind = 0, bool compact = false, bool symmetric = false) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. If compact is set to true, only the nonzeros of the input and output expressions are considered. If symmetric is set to true, the Jacobian being calculated is known to be symmetric (usually a Hessian), which can be exploited by the algorithm.
The generated Jacobian has one more output than the calling function corresponding to the Jacobian and the same number of inputs.
Definition at line 312 of file function.hpp.
{
         return jacobian(index_in(iind), oind, compact, symmetric);
     }
Function casadi::Function::jacobian (int iind, const std::string & oind, bool compact = false, bool symmetric = false) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. If compact is set to true, only the nonzeros of the input and output expressions are considered. If symmetric is set to true, the Jacobian being calculated is known to be symmetric (usually a Hessian), which can be exploited by the algorithm.
The generated Jacobian has one more output than the calling function corresponding to the Jacobian and the same number of inputs.
Definition at line 316 of file function.hpp.
{
         return jacobian(iind, index_out(oind), compact, symmetric);
     }
Function casadi::Function::jacobian (const std::string & iind, const std::string & oind, bool compact = false, bool symmetric = false) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. If compact is set to true, only the nonzeros of the input and output expressions are considered. If symmetric is set to true, the Jacobian being calculated is known to be symmetric (usually a Hessian), which can be exploited by the algorithm.
The generated Jacobian has one more output than the calling function corresponding to the Jacobian and the same number of inputs.
Definition at line 319 of file function.hpp.
{
         return jacobian(index_in(iind), index_out(oind), compact, symmetric);
     }
Function casadi::Function::kernel_sum (const std::string & name, const std::pair< int, int > & size, double r, int n, const Dict & opts = Dict()) const inherited
kernel_sum Consider a dense matrix V.
KernelSum computes
F(V,X) = sum_i sum_j f ([i;j], V(i,j), X)
with X: [x;y]
where the summation is taken for all entries (i,j) that are a distance r away from X.
This function assumes that V is fixed: sensitivities with respect to it are not computed.
This allows for improved speed of evaluation.
Having V fixed is a common use case: V may be a large bitmap (observation), onto which a kernel is fitted.
Author
Joris Gillis
Date
2015
Definition at line 498 of file function.cpp.
References casadi::SharedObject::assignNode(), and casadi::FunctionInternal::construct().
Referenced by casadi::KernelSum::get_forward(), and casadi::KernelSum::get_reverse().
{
     Function ret;
     ret.assignNode(new KernelSum(name, *this, size, r, n));
     ret->construct(opts);
     return ret;
   }
DM casadi::Function::linsol_cholesky (bool tr = false, int mem = 0) const inherited
Definition at line 115 of file linsol.cpp.
{
     return (*this)->linsol_cholesky(memory(mem), tr);
   }
Sparsity casadi::Function::linsol_cholesky_sparsity (bool tr = false, int mem = 0) const inherited
Definition at line 111 of file linsol.cpp.
{
     return (*this)->linsol_cholesky_sparsity(memory(mem), tr);
   }
void casadi::Function::linsol_factorize (const double * A, int mem = 0) const inherited
Definition at line 103 of file linsol.cpp.
Referenced by casadi::Newton::eval(), casadi::KinsolInterface::psetup(), casadi::CvodesInterface::psetup(), casadi::IdasInterface::psetup(), casadi::CvodesInterface::psetupB(), and casadi::IdasInterface::psetupB().
{
     (*this)->linsol_factorize(memory(mem), A);
   }
MX casadi::Function::linsol_solve (const MX & A, const MX & B, bool tr = false) inherited
Definition at line 95 of file linsol.cpp.
Referenced by casadi::Newton::eval(), casadi::KinsolInterface::psolve(), casadi::CvodesInterface::psolve(), casadi::IdasInterface::psolve(), casadi::CvodesInterface::psolveB(), casadi::IdasInterface::psolveB(), and casadi::MX::solve().
{
     return (*this)->linsol_solve(A, B, tr);
   }
void casadi::Function::linsol_solve (double * x, int nrhs = 1, bool tr = false, int mem = 0) const inherited
Definition at line 107 of file linsol.cpp.
{
     (*this)->linsol_solve(memory(mem), x, nrhs, tr);
   }
void casadi::Function::linsol_solveL (double * x, int nrhs, bool tr, int mem = 0) const inherited
Definition at line 99 of file linsol.cpp.
{
     (*this)->linsol_solveL(memory(mem), x, nrhs, tr);
   }
void casadi::Function::linsol_spsolve (bvec_t * X, const bvec_t * B, bool tr = false) const inherited
Propagate sparsity through a linear solve
Definition at line 119 of file linsol.cpp.
Referenced by casadi::Rootfinder::spAdj(), casadi::Integrator::spAdj(), casadi::Rootfinder::spFwd(), and casadi::Integrator::spFwd().
{
     (*this)->linsol_spsolve(X, B, tr);
   }
void casadi::Function::linsol_spsolve (DM & X, const DM & B, bool tr = false) const inherited
Propagate sparsity through a linear solve
Definition at line 123 of file linsol.cpp.
{
     (*this)->linsol_spsolve(X, B, tr);
   }
std::vector<MX> casadi::Function::map (const std::vector< MX > & arg, const std::string & parallelization = "serial") inherited
Parameters
parallelization Type of parallelization used: unroll|serial|openmp
Referenced by casadi::PureMap::get_forward(), casadi::MapSum::get_forward(), casadi::PureMap::get_reverse(), and casadi::MapSum::get_reverse().
std::map< std::string, MX > casadi::Function::map (const std::map< std::string, MX > & arg, const std::string & parallelization = "serial") inherited
Parameters
parallelization Type of parallelization used: unroll|serial|openmp
Definition at line 460 of file function.cpp.
{
     // Convert inputs map to vector
     std::vector<MX> args(n_in());
     for (auto& e : arg) args[index_in(e.first)] = e.second;
     // Delegate the actual map call
     std::vector<MX> res = map(args, parallelization);
     // Result vector to map
     std::map<std::string, MX> ret;
     for (int i=0;i<res.size();++i) ret[name_out(i)] = res[i];
     return ret;
   }
Function casadi::Function::map (const std::string & name, const std::string & parallelization, int n, const std::vector< int > & reduce_in, const std::vector< int > & reduce_out, const Dict & opts = Dict()) inherited
Suppose the function has a signature of:
   f: (a, p) -> ( s )
The the mapaccumulated version has the signature:
   F: (A, P) -> (S )
    with
        A: horzcat([a0, a1, ..., a_(N-1)])
        P: horzcat([p0, p1, ..., p_(N-1)])
        S: horzcat([s0, s1, ..., s_(N-1)])
    and
        s0 <- f(a0, p0)
        s1 <- f(a1, p1)
        ...
        s_(N-1) <- f(a_(N-1), p_(N-1))
Parameters
parallelization Type of parallelization used: unroll|serial|openmp
Function casadi::Function::map (const std::string & name, const std::string & parallelization, int n, const Dict & opts = Dict()) inherited
Suppose the function has a signature of:
   f: (a, p) -> ( s )
The the mapaccumulated version has the signature:
   F: (A, P) -> (S )
    with
        A: horzcat([a0, a1, ..., a_(N-1)])
        P: horzcat([p0, p1, ..., p_(N-1)])
        S: horzcat([s0, s1, ..., s_(N-1)])
    and
        s0 <- f(a0, p0)
        s1 <- f(a1, p1)
        ...
        s_(N-1) <- f(a_(N-1), p_(N-1))
Parameters
parallelization Type of parallelization used: unroll|serial|openmp
Function casadi::Function::mapaccum (const std::string & name, int n, const Dict & opts = Dict()) inherited
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
Function casadi::Function::mapaccum (const std::string & name, int n, const std::vector< int > & accum_in, const std::vector< int > & accum_out, const Dict & opts = Dict()) inherited
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
vector< MX > casadi::Function::mapsum (const std::vector< MX > & arg, const std::string & parallelization = "serial") inherited
Parameters
parallelization Type of parallelization used: unroll|serial|openmp
Definition at line 477 of file function.cpp.
{
     return (*this)->mapsum_mx(x, parallelization);
   }
void * casadi::Function::memory (int ind) const inherited
Definition at line 1220 of file function.cpp.
{
     return (*this)->memory(ind);
   }
const MX casadi::Function::mx_in (int ind) const inherited
Definition at line 1144 of file function.cpp.
Referenced by casadi::Function::derivative(), casadi::MX::get_input(), and casadi::Jit::getFullJacobian().
{
     return (*this)->mx_in(ind);
   }
const MX casadi::Function::mx_in (const std::string & iname) const inline inherited
Definition at line 814 of file function.hpp.
{
       return mx_in(index_in(iname));
     }
const vector< MX > casadi::Function::mx_in () const inherited
Definition at line 1152 of file function.cpp.
{
     return (*this)->mx_in();
   }
const MX casadi::Function::mx_out (int ind) const inherited
Definition at line 1148 of file function.cpp.
{
     return (*this)->mx_out(ind);
   }
const MX casadi::Function::mx_out (const std::string & oname) const inline inherited
Definition at line 830 of file function.hpp.
{
       return mx_out(index_out(oname));
     }
const vector< MX > casadi::Function::mx_out () const inherited
Definition at line 1156 of file function.cpp.
{
     return (*this)->mx_out();
   }
int casadi::Function::n_in () const inherited
Definition at line 508 of file function.cpp.
References casadi::FunctionInternal::n_in().
Referenced by casadi::FixedStepIntegrator::advance(), casadi::Integrator::aug_adj(), casadi::Integrator::aug_fwd(), casadi::KinsolInterface::bjac(), casadi::Nlpsol::calc_function(), casadi::Call::Call(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::LibOracle< LibType >::create(), casadi::KernelSum::eval(), eval(), casadi::Scpgen::eval_exp(), casadi::Scpgen::eval_mat(), casadi::Scpgen::eval_res(), casadi::Scpgen::eval_vec(), casadi::Mapaccum::evalGen(), casadi::MapSum::evalGen(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::fullJacobian(), casadi::KernelSum::generateBody(), casadi::Mapaccum::generateBody(), casadi::MapSum::generateBody(), casadi::Switch::get_forward(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_reverse(), casadi::KernelSum::get_reverse(), casadi::Switch::init(), casadi::Mapaccum::init(), casadi::Rootfinder::init(), casadi::Newton::init(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::MapSum::init(), casadi::IpoptInterface::intermediate_callback(), casadi::KernelSum::KernelSum(), casadi::SymbolicQr::linsol_factorize(), casadi::SymbolicQr::linsol_solve(), casadi::Mapaccum::Mapaccum(), casadi::MapSum::MapSum(), casadi::KinsolInterface::psetup(), casadi::FixedStepIntegrator::retreat(), casadi::FunctionInternal::reverse(), casadi::simpleIntegrator(), casadi::simpleIRK(), casadi::simpleRK(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Scpgen::solve(), casadi::Scpgen::solve_qp(), casadi::Mapaccum::spAdj(), casadi::MapSum::spAdj(), casadi::KernelSum::spFwd(), and casadi::SnoptInterface::userfun().
{
     return (*this)->n_in();
   }
int casadi::Function::n_nodes () const inherited
Definition at line 1208 of file function.cpp.
References casadi::Matrix< Scalar >::n_nodes().
Referenced by casadi::Scpgen::init(), and casadi::MX::n_nodes().
{
     return (*this)->n_nodes();
   }
int casadi::Function::n_out () const inherited
Definition at line 512 of file function.cpp.
Referenced by casadi::FixedStepIntegrator::advance(), casadi::KinsolInterface::bjac(), casadi::CvodesInterface::bjac(), casadi::IdasInterface::bjac(), casadi::CvodesInterface::bjacB(), casadi::IdasInterface::bjacB(), casadi::Nlpsol::calc_function(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::LibOracle< LibType >::create(), casadi::KinsolInterface::djac(), casadi::CvodesInterface::djac(), casadi::IdasInterface::djac(), casadi::CvodesInterface::djacB(), casadi::IdasInterface::djacB(), casadi::KernelSum::eval(), eval(), casadi::Scpgen::eval_exp(), casadi::Scpgen::eval_mat(), casadi::Scpgen::eval_res(), casadi::Scpgen::eval_vec(), casadi::Mapaccum::evalGen(), casadi::MapSum::evalGen(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::fullJacobian(), casadi::KernelSum::generateBody(), casadi::Mapaccum::generateBody(), casadi::MapSum::generateBody(), casadi::Switch::get_n_out(), casadi::Switch::init(), casadi::Mapaccum::init(), casadi::Rootfinder::init(), casadi::KernelSum::init(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::IpoptInterface::init(), casadi::MapSum::init(), casadi::IpoptInterface::intermediate_callback(), casadi::KinsolInterface::jtimes(), casadi::SymbolicQr::linsol_factorize(), casadi::SymbolicQr::linsol_solve(), casadi::Mapaccum::Mapaccum(), casadi::MapSum::MapSum(), casadi::Call::nout(), casadi::KinsolInterface::psetup(), casadi::CvodesInterface::psetup(), casadi::IdasInterface::psetup(), casadi::CvodesInterface::psetupB(), casadi::IdasInterface::psetupB(), casadi::FixedStepIntegrator::retreat(), casadi::FunctionInternal::reverse(), casadi::simpleIntegrator(), casadi::simpleIRK(), casadi::simpleRK(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Sqpmethod::solve(), casadi::Scpgen::solve(), casadi::Scpgen::solve_qp(), casadi::Mapaccum::spAdj(), casadi::MapSum::spAdj(), casadi::KernelSum::spFwd(), and casadi::SnoptInterface::userfun().
{
     return (*this)->n_out();
   }
string casadi::Function::name () const inherited
Definition at line 927 of file function.cpp.
Referenced by casadi::CodeGenerator::add(), casadi::Nlpsol::calc_function(), casadi::Call::Call(), casadi::FunctionInternal::dynamicCompilation(), casadi::FunctionInternal::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::FunctionInternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::MX::matrix_expand(), casadi::Call::print(), casadi::Switch::print(), casadi::KernelSum::print(), casadi::Mapaccum::print(), casadi::MapSum::print(), and casadi::Nlpsol::register_function().
{
     if (is_null()) {
       return "null";
     } else {
       return (*this)->name();
     }
   }
vector< string > casadi::Function::name_in () const inherited
Definition at line 624 of file function.cpp.
Referenced by casadi::Oracle::expand().
{
     return (*this)->ischeme_;
   }
string casadi::Function::name_in (int ind) const inherited
Definition at line 640 of file function.cpp.
{
     return (*this)->name_in(ind);
   }
vector< string > casadi::Function::name_out () const inherited
Definition at line 628 of file function.cpp.
Referenced by casadi::Nlpsol::calc_function(), and casadi::Oracle::expand().
{
     return (*this)->oscheme_;
   }
string casadi::Function::name_out (int ind) const inherited
Definition at line 644 of file function.cpp.
{
     return (*this)->name_out(ind);
   }
int casadi::Function::nnz_in () const inherited
Definition at line 540 of file function.cpp.
Referenced by casadi::ImplicitToNlp::eval(), casadi::PureMap::evalGen(), casadi::Call::generate(), casadi::PureMap::generateBody(), casadi::FunctionInternal::get_sparsity_out(), casadi::Mapaccum::init(), casadi::Rootfinder::init(), casadi::ImplicitToNlp::init(), casadi::MapSum::init(), casadi::FixedStepIntegrator::init(), casadi::PureMap::spAdj(), and casadi::DaeBuilder::split_dae().
{
     return (*this)->nnz_in();
   }
int casadi::Function::nnz_in (int ind) const inherited
Definition at line 556 of file function.cpp.
{
     return (*this)->nnz_in(ind);
   }
int casadi::Function::nnz_in (const std::string & iname) const inline inherited
Definition at line 215 of file function.hpp.
 {return numel_in(index_in(iname));}
int casadi::Function::nnz_out () const inherited
Definition at line 544 of file function.cpp.
Referenced by casadi::Nlpsol::calc_function(), casadi::Newton::eval(), casadi::PureMap::evalGen(), casadi::Call::generate(), casadi::PureMap::generateBody(), casadi::FunctionInternal::get_sparsity_out(), casadi::Mapaccum::init(), casadi::Rootfinder::init(), casadi::KernelSum::init(), casadi::Newton::init(), casadi::SundialsInterface::init(), casadi::KinsolInterface::init(), casadi::SnoptInterface::init(), casadi::MapSum::init(), casadi::SymbolicQr::init_memory(), casadi::KinsolInterface::psetup(), casadi::CvodesInterface::psetup(), casadi::IdasInterface::psetup(), casadi::CvodesInterface::psetupB(), casadi::IdasInterface::psetupB(), casadi::CvodesInterface::psolve(), casadi::IdasInterface::psolve(), casadi::CvodesInterface::psolveB(), casadi::IdasInterface::psolveB(), casadi::SnoptInterface::set_work(), casadi::Mapaccum::spAdj(), casadi::PureMap::spAdj(), and casadi::MapSum::spAdj().
{
     return (*this)->nnz_out();
   }
int casadi::Function::nnz_out (int ind) const inherited
Definition at line 560 of file function.cpp.
{
     return (*this)->nnz_out(ind);
   }
int casadi::Function::nnz_out (const std::string & oname) const inline inherited
Definition at line 224 of file function.hpp.
 {return numel_out(index_out(oname));}
int casadi::Function::numel_in () const inherited
Definition at line 548 of file function.cpp.
{
     return (*this)->numel_in();
   }
int casadi::Function::numel_in (int ind) const inherited
Definition at line 564 of file function.cpp.
{
     return (*this)->numel_in(ind);
   }
int casadi::Function::numel_in (const std::string & iname) const inline inherited
Definition at line 233 of file function.hpp.
References casadi::Function::numel_in().
Referenced by casadi::Function::numel_in().
 {return numel_in(index_in(iname));}
int casadi::Function::numel_out () const inherited
Definition at line 552 of file function.cpp.
Referenced by casadi::Nlpsol::init().
{
     return (*this)->numel_out();
   }
int casadi::Function::numel_out (int ind) const inherited
Definition at line 568 of file function.cpp.
{
     return (*this)->numel_out(ind);
   }
int casadi::Function::numel_out (const std::string & oname) const inline inherited
Definition at line 242 of file function.hpp.
References casadi::Function::numel_out().
Referenced by casadi::Function::numel_out().
 {return numel_out(index_out(oname));}
std::vector<DM> casadi::Function::operator() (const std::vector< DM > & arg) inherited
Functor shorthand for evaluation
std::vector<SX> casadi::Function::operator() (const std::vector< SX > & arg) inherited
Functor shorthand for evaluation
std::vector<MX> casadi::Function::operator() (const std::vector< MX > & arg) inherited
Functor shorthand for evaluation
const DMDict casadi::Function::operator() (const DMDict & arg) inherited
Functor shorthand for evaluation
Definition at line 1083 of file function.cpp.
{
     DMDict res;
     call(arg, res);
     return res;
   }
const SXDict casadi::Function::operator() (const SXDict & arg) inherited
Functor shorthand for evaluation
Definition at line 1089 of file function.cpp.
{
     SXDict res;
     call(arg, res);
     return res;
   }
const MXDict casadi::Function::operator() (const MXDict & arg) inherited
Functor shorthand for evaluation
Definition at line 1095 of file function.cpp.
{
     MXDict res;
     call(arg, res);
     return res;
   }
void casadi::Function::operator() (std::vector< const double * > arg, std::vector< double * > res) inherited
void casadi::Function::operator() (std::vector< const bvec_t * > arg, std::vector< bvec_t * > res) inherited
void casadi::Function::operator() (std::vector< const SXElem * > arg, std::vector< SXElem * > res) inherited
void casadi::Function::operator() (VecArg arg, VecRes res) inline inherited
Definition at line 449 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
void casadi::Function::operator() (VecArg arg, MapRes res) inline inherited
Definition at line 450 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
void casadi::Function::operator() (VecArg arg, VPrRes res) inline inherited
Definition at line 451 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
void casadi::Function::operator() (VecArg arg, MPrRes res) inline inherited
Definition at line 452 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
void casadi::Function::operator() (MapArg arg, VecRes res) inline inherited
Definition at line 454 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
void casadi::Function::operator() (MapArg arg, MapRes res) inline inherited
Definition at line 455 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
void casadi::Function::operator() (MapArg arg, VPrRes res) inline inherited
Definition at line 456 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
void casadi::Function::operator() (MapArg arg, MPrRes res) inline inherited
Definition at line 457 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
std::vector<DM> casadi::Function::operator() (const DM & arg0) inline inherited
Functor shorthand for evaluation, single argument (only C++)
Definition at line 462 of file function.hpp.
{
       return operator()(std::vector<DM>{arg0});
     }
std::vector<SX> casadi::Function::operator() (const SX & arg0) inline inherited
Functor shorthand for evaluation, single argument (only C++)
Definition at line 465 of file function.hpp.
{
       return operator()(std::vector<SX>{arg0});
     }
std::vector<MX> casadi::Function::operator() (const MX & arg0) inline inherited
Functor shorthand for evaluation, single argument (only C++)
Definition at line 468 of file function.hpp.
{
       return operator()(std::vector<MX>{arg0});
     }
void casadi::Function::operator() (const double ** arg, double ** res, int * iw, double * w, int mem = 0) const inherited
Definition at line 1120 of file function.cpp.
{
     (*this)->_eval(arg, res, iw, w, mem);
   }
void casadi::Function::operator() (const SXElem ** arg, SXElem ** res, int * iw, SXElem * w, int mem = 0) const inherited
Definition at line 1124 of file function.cpp.
{
     (*this)->eval_sx(arg, res, iw, w, mem);
   }
void casadi::Function::operator() (const bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem = 0) const inherited
Definition at line 676 of file function.cpp.
{
     (*const_cast<Function*>(this))->spFwd(arg, res, iw, w, mem);
   }
void casadi::SharedObject::print (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 135 of file shared_object.cpp.
Referenced by casadi::CsparseInterface::linsol_factorize().
{
     if (is_null()) {
       stream << "Null pointer of class \"" << typeid(this).name() << "\"";
     } else {
       (*this)->print(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::Function::printDimensions (std::ostream & stream = casadi::userOut()) const inherited
Definition at line 870 of file function.cpp.
{
     (*this)->printDimensions(stream);
   }
void casadi::Function::printOption (const std::string & name, std::ostream & stream = casadi::userOut()) const inherited
Definition at line 878 of file function.cpp.
{
     (*this)->printOption(name, stream);
   }
void casadi::Function::printOptions (std::ostream & stream = casadi::userOut()) const inherited
Definition at line 874 of file function.cpp.
{
     (*this)->printOptions(stream);
   }
void casadi::SharedObject::printPtr (std::ostream & stream = casadi::userOut()) const inherited
Print the pointer to the internal class
Definition at line 144 of file shared_object.cpp.
{
     stream << node;
   }
bool casadi::Function::proceed_to (std::istream & file, const std::string & str) static protected inherited
Definition at line 53 of file function.cpp.
{
     // Make sure that the file is ready for reading
     if (!file.good()) return false;
     // Have we already wrapped around once?
     bool wrapped_around = false;
     // Read line-by-line
     string tmp;
     while (true) {
       // Read a word
       streampos cur_pos = file.tellg();
       file >> tmp;
       if (!file.good()) return false;
       // Check if match
       if (str==tmp) return true;
       // If comment, continue to the end of the line
       if (tmp.at(0)=='#') {
         file.ignore(numeric_limits<streamsize>::max(), '\n');
         continue;
       }
       // If mismatching name, rewind and break
       file.seekg(cur_pos);
       return false;
     }
   }
void casadi::Function::qpsol_debug (const std::string & filename) const inherited
Generate native code in the interfaced language for debugging
void casadi::Function::qpsol_debug (std::ostream & file) const inherited
Generate native code in the interfaced language for debugging
Definition at line 59 of file qpsol.cpp.
References casadi::Qpsol::generateNativeCode().
{
     casadi_assert(!is_null());
     const Qpsol* n = dynamic_cast<const Qpsol*>(get());
     casadi_assert_message(n!=0, "Not a QP solver");
     return n->generateNativeCode(file);
   }
void casadi::Function::release (int mem) inherited
Definition at line 1216 of file function.cpp.
{
     (*this)->release(mem);
   }
void casadi::Function::removeMonitor (const std::string & mon) inherited
Definition at line 608 of file function.cpp.
{
     (*this)->monitors_.erase(mon);
   }
void casadi::SharedObject::repr (std::ostream & stream = casadi::userOut(), bool trailing_newline = true) const inherited
Examples:
SX/generateCode.py.
Definition at line 121 of file shared_object.cpp.
{
     if (is_null()) {
       stream << 0;
     } else {
       (*this)->repr(stream);
     }
     if (trailing_newline) stream << std::endl;
   }
void casadi::Function::rev (bvec_t ** arg, bvec_t ** res, int * iw, bvec_t * w, int mem = 0) inherited
Definition at line 680 of file function.cpp.
Referenced by casadi::_nl_var(), casadi::Rootfinder::spAdj(), casadi::Call::spAdj(), and casadi::Integrator::spAdj().
{
     (*this)->spAdj(arg, res, iw, w, mem);
   }
void casadi::Function::rev (std::vector< bvec_t * > arg, std::vector< bvec_t * > res) inherited
Definition at line 386 of file function.cpp.
References casadi::get_ptr().
{
     // Input buffer
     casadi_assert(arg.size()>=n_in());
     arg.resize(sz_arg());
     // Output buffer
     casadi_assert(res.size()>=n_out());
     res.resize(sz_res());
     // Work vectors
     vector<int> iw(sz_iw());
     vector<bvec_t> w(sz_w());
     // Evaluate memoryless
     rev(get_ptr(arg), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
   }
void casadi::Function::reverse (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & output_asens, bool always_inline = false, bool never_inline = false) inherited
Referenced by casadi::Call::evalAdj(), casadi::Switch::get_reverse(), casadi::KernelSum::get_reverse(), casadi::Mapaccum::get_reverse(), casadi::PureMap::get_reverse(), casadi::MapSum::get_reverse(), and casadi::Rootfinder::reverse().
void casadi::Function::reverse (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & aseed, std::vector< std::vector< SX > > & output_asens, bool always_inline = false, bool never_inline = false) inherited
void casadi::Function::reverse (const std::vector< DM > & arg, const std::vector< DM > & res, const std::vector< std::vector< DM > > & aseed, std::vector< std::vector< DM > > & output_asens, bool always_inline = false, bool never_inline = false) inherited
Function casadi::Function::reverse (int nadj) inherited
Returns a function with n_in + n_out +nadj*n_out inputs and nadj*n_in outputs. The first n_in inputs correspond to nondifferentiated inputs. The next n_out inputs correspond to nondifferentiated outputs. and the last nadj*n_out inputs correspond to adjoint seeds, one direction at a time The nadj*n_in outputs correspond to adjoint sensitivities, one direction at a time. * (n_in = n_in(), n_out = n_out())
(n_in = n_in(), n_out = n_out())
The functions returned are cached, meaning that if called multiple timed with the same value, then multiple references to the same function will be returned.
Definition at line 858 of file function.cpp.
References casadi::FunctionInternal::reverse().
{
     return (*this)->reverse(nadj);
   }
Function casadi::Function::rootfinder_fun () inherited
Definition at line 48 of file rootfinder.cpp.
References casadi::Rootfinder::f_.
{
     casadi_assert(!is_null());
     Rootfinder* n = dynamic_cast<Rootfinder*>(get());
     casadi_assert_message(n!=0, "Not a rootfinder");
     return n->f_;
   }
Function casadi::Function::rootfinder_jac () inherited
Definition at line 55 of file rootfinder.cpp.
References casadi::Rootfinder::jac_.
{
     casadi_assert(!is_null());
     Rootfinder* n = dynamic_cast<Rootfinder*>(get());
     casadi_assert_message(n!=0, "Not a rootfinder");
     return n->jac_;
   }
Function casadi::Function::rootfinder_linsol () inherited
Definition at line 62 of file rootfinder.cpp.
References casadi::Rootfinder::linsol_.
{
     casadi_assert(!is_null());
     Rootfinder* n = dynamic_cast<Rootfinder*>(get());
     casadi_assert_message(n!=0, "Not a rootfinder");
     return n->linsol_;
   }
void casadi::Function::set_forward (const Function & fcn, int nfwd) inherited
Definition at line 862 of file function.cpp.
{
     (*this)->set_forward(fcn, nfwd);
   }
void casadi::Function::set_jac_sparsity (const Sparsity & sp, int iind, int oind, bool compact = false) inherited
Generate the sparsity of a Jacobian block
Definition at line 620 of file function.cpp.
{
     (*this)->set_jac_sparsity(sp, iind, oind, compact);
   }
void casadi::Function::set_jac_sparsity (const Sparsity & sp, const std::string & iind, int oind, bool compact = false) inline inherited
Generate the sparsity of a Jacobian block
Definition at line 765 of file function.hpp.
{
       set_jac_sparsity(sp, index_in(iind), oind, compact);
     }
void casadi::Function::set_jac_sparsity (const Sparsity & sp, int iind, const std::string & oind, bool compact = false) inline inherited
Generate the sparsity of a Jacobian block
Definition at line 769 of file function.hpp.
{
       set_jac_sparsity(sp, iind, index_out(oind), compact);
     }
void casadi::Function::set_jac_sparsity (const Sparsity & sp, const std::string & iind, const std::string & oind, bool compact = false) inline inherited
Generate the sparsity of a Jacobian block
Definition at line 773 of file function.hpp.
{
       set_jac_sparsity(sp, index_in(iind), index_out(oind), compact);
     }
void casadi::Function::set_reverse (const Function & fcn, int nadj) inherited
Definition at line 866 of file function.cpp.
{
     (*this)->set_reverse(fcn, nadj);
   }
void casadi::Function::set_temp (const double ** arg, double ** res, int * iw, double * w, int mem = 0) const inherited
Definition at line 689 of file function.cpp.
{
     (*this)->_set_temp(arg, res, iw, w, mem);
   }
void casadi::Function::set_work (const double **& arg, double **& res, int *& iw, double *& w, int mem = 0) const inherited
Definition at line 684 of file function.cpp.
{
     (*this)->_set_work(arg, res, iw, w, mem);
   }
void casadi::Function::setFullJacobian (const Function & jac) inherited
Set the Jacobian of all the input nonzeros with respect to all output nonzeros NOTE: Does not take ownership, only weak references to the Jacobian are kept internally
Definition at line 596 of file function.cpp.
References casadi::FunctionInternal::full_jacobian_.
{
     (*this)->full_jacobian_ = jac;
   }
void casadi::Function::setJacobian (const Function & jac, int iind = 0, int oind = 0, bool compact = false) inherited
Set the Jacobian function of output oind with respect to input iind NOTE: Does not take ownership, only weak references to the Jacobians are kept internally
Definition at line 576 of file function.cpp.
References casadi::FunctionInternal::setJacobian().
{
     (*this)->setJacobian(jac, iind, oind, compact);
   }
void casadi::Function::setup (const double ** arg, double ** res, int * iw, double * w, int mem = 0) const inherited
Definition at line 694 of file function.cpp.
Referenced by casadi::Newton::eval(), casadi::KinsolInterface::psetup(), casadi::CvodesInterface::psetup(), casadi::IdasInterface::psetup(), casadi::CvodesInterface::psetupB(), and casadi::IdasInterface::psetupB().
{
     (*this)->_setup(arg, res, iw, w, mem);
   }
int casadi::Function::size1_in (int ind) const inherited
Definition at line 516 of file function.cpp.
{
     return (*this)->size1_in(ind);
   }
int casadi::Function::size1_in (const std::string & iname) const inline inherited
Definition at line 190 of file function.hpp.
References casadi::Function::size1_in().
Referenced by casadi::Function::size1_in().
 {return size1_in(index_in(iname));}
int casadi::Function::size1_out (int ind) const inherited
Definition at line 524 of file function.cpp.
Referenced by casadi::Rootfinder::init(), and casadi::SundialsInterface::init().
{
     return (*this)->size1_out(ind);
   }
int casadi::Function::size1_out (const std::string & oname) const inline inherited
Definition at line 200 of file function.hpp.
References casadi::Function::size1_out().
Referenced by casadi::Function::size1_out().
 {return size1_out(index_out(oname));}
int casadi::Function::size2_in (int ind) const inherited
Definition at line 520 of file function.cpp.
{
     return (*this)->size2_in(ind);
   }
int casadi::Function::size2_in (const std::string & iname) const inline inherited
Definition at line 192 of file function.hpp.
References casadi::Function::size2_in().
Referenced by casadi::Function::size2_in().
 {return size2_in(index_in(iname));}
int casadi::Function::size2_out (int ind) const inherited
Definition at line 528 of file function.cpp.
Referenced by casadi::KinsolInterface::bjac(), casadi::CvodesInterface::bjac(), casadi::IdasInterface::bjac(), casadi::CvodesInterface::bjacB(), casadi::IdasInterface::bjacB(), casadi::KinsolInterface::djac(), casadi::CvodesInterface::djac(), casadi::IdasInterface::djac(), casadi::CvodesInterface::djacB(), casadi::IdasInterface::djacB(), and casadi::SundialsInterface::init().
{
     return (*this)->size2_out(ind);
   }
int casadi::Function::size2_out (const std::string & oname) const inline inherited
Definition at line 202 of file function.hpp.
References casadi::Function::size2_out().
Referenced by casadi::Function::size2_out().
 {return size2_out(index_out(oname));}
pair< int, int > casadi::Function::size_in (int ind) const inherited
Definition at line 532 of file function.cpp.
Referenced by casadi::FunctionInternal::forward(), casadi::Nlpsol::init(), and casadi::FunctionInternal::reverse().
{
     return (*this)->size_in(ind);
   }
std::pair<int, int> casadi::Function::size_in (const std::string & iname) const inline inherited
Definition at line 194 of file function.hpp.
References casadi::Function::size_in().
Referenced by casadi::Function::size_in().
 {return size_in(index_in(iname));}
pair< int, int > casadi::Function::size_out (int ind) const inherited
Definition at line 536 of file function.cpp.
Referenced by casadi::FunctionInternal::forward(), casadi::SqicInterface::generateNativeCode(), casadi::SqicInterface::init(), casadi::Integrator::init(), and casadi::FunctionInternal::reverse().
{
     return (*this)->size_out(ind);
   }
std::pair<int, int> casadi::Function::size_out (const std::string & oname) const inline inherited
Definition at line 204 of file function.hpp.
{
       return size_out(index_out(oname));
     }
Function casadi::Function::slice (const std::vector< int > & order_in, const std::vector< int > & order_out, const Dict & opts = Dict()) inherited
Definition at line 434 of file function.cpp.
Referenced by casadi::Mapaccum::create().
{
     // Get symbolic inputs
     std::vector<MX> in = mx_in();
     // Get symbolic outputs
     std::vector<MX> out = (*this)(in);
     // Shuffle the inputs
     std::vector<MX> new_in;
     for (int k : order_in) new_in.push_back(in.at(k));
     // Shuffle the outputs
     std::vector<MX> new_out;
     for (int k : order_out) new_out.push_back(out.at(k));
     // Return a wrapping function
     return Function(std::string("slice_") + name(), new_in, new_out, opts);
   }
const Sparsity & casadi::Function::sparsity_in (int ind) const inherited
Definition at line 648 of file function.cpp.
Referenced by casadi::Call::Call(), casadi::MapBase::create(), casadi::Mapaccum::create(), casadi::Switch::eval(), eval(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::FixedStepIntegrator::init_memory(), casadi::Integrator::Integrator(), casadi::KernelSum::KernelSum(), casadi::Mapaccum::Mapaccum(), casadi::simpleIntegrator(), casadi::simpleIRK(), and casadi::simpleRK().
{
     return (*this)->sparsity_in(ind);
   }
const Sparsity& casadi::Function::sparsity_in (const std::string & iname) const inherited
const Sparsity casadi::Function::sparsity_jac (int iind = 0, int oind = 0, bool compact = false, bool symmetric = false) inherited
Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 616 of file function.cpp.
Referenced by casadi::Integrator::spJacF(), and casadi::Integrator::spJacG().
{
     return (*this)->sparsity_jac(iind, oind, compact, symmetric);
   }
const Sparsity casadi::Function::sparsity_jac (const std::string & iind, int oind = 0, bool compact = false, bool symmetric = false) inline inherited
Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 748 of file function.hpp.
{
       return sparsity_jac(index_in(iind), oind, compact, symmetric);
     }
const Sparsity casadi::Function::sparsity_jac (int iind, const std::string & oind, bool compact = false, bool symmetric = false) inline inherited
Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 752 of file function.hpp.
{
       return sparsity_jac(iind, index_out(oind), compact, symmetric);
     }
const Sparsity casadi::Function::sparsity_jac (const std::string & iind, const std::string & oind, bool compact = false, bool symmetric = false) inline inherited
Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 756 of file function.hpp.
{
       return sparsity_jac(index_in(iind), index_out(oind), compact, symmetric);
     }
const Sparsity & casadi::Function::sparsity_out (int ind) const inherited
Definition at line 656 of file function.cpp.
Referenced by casadi::KinsolInterface::bjac(), casadi::CvodesInterface::bjac(), casadi::IdasInterface::bjac(), casadi::CvodesInterface::bjacB(), casadi::IdasInterface::bjacB(), casadi::Mapaccum::create(), casadi::KinsolInterface::djac(), casadi::CvodesInterface::djac(), casadi::IdasInterface::djac(), casadi::CvodesInterface::djacB(), casadi::IdasInterface::djacB(), casadi::Switch::eval(), casadi::Switch::get_sparsity_out(), casadi::SundialsInterface::getBandwidth(), casadi::SundialsInterface::getBandwidthB(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Integrator::init(), casadi::KnitroInterface::init(), casadi::SundialsInterface::init(), casadi::SnoptInterface::init(), casadi::WorhpInterface::init(), casadi::Sqpmethod::init(), casadi::Scpgen::init(), casadi::IpoptInterface::init(), casadi::Integrator::Integrator(), casadi::Mapaccum::Mapaccum(), casadi::Call::sparsity(), and casadi::SnoptInterface::userfun().
{
     return (*this)->sparsity_out(ind);
   }
const Sparsity& casadi::Function::sparsity_out (const std::string & iname) const inherited
bool casadi::Function::spCanEvaluate (bool fwd) inherited
(for usage, see the example propagating_sparsity.cpp)
Definition at line 699 of file function.cpp.
{
     return (*this)->spCanEvaluate(fwd);
   }
Dict casadi::Function::stats (int mem = 0) const inherited
Definition at line 612 of file function.cpp.
Referenced by casadi::ImplicitToNlp::eval().
{
     return (*this)->_get_stats(mem);
   }
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 153 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
const SX casadi::Function::sx_in (int iind) const inherited
Definition at line 1128 of file function.cpp.
Referenced by casadi::Oracle::expand().
{
     return (*this)->sx_in(ind);
   }
const SX casadi::Function::sx_in (const std::string & iname) const inline inherited
Definition at line 809 of file function.hpp.
{
       return sx_in(index_in(iname));
     }
const vector< SX > casadi::Function::sx_in () const inherited
Definition at line 1136 of file function.cpp.
{
     return (*this)->sx_in();
   }
const SX casadi::Function::sx_out (int oind) const inherited
Definition at line 1132 of file function.cpp.
{
     return (*this)->sx_out(ind);
   }
const SX casadi::Function::sx_out (const std::string & oname) const inline inherited
Definition at line 825 of file function.hpp.
{
       return sx_out(index_out(oname));
     }
const vector< SX > casadi::Function::sx_out () const inherited
Definition at line 1140 of file function.cpp.
{
     return (*this)->sx_out();
   }
size_t casadi::Function::sz_arg () const inherited
Definition at line 668 of file function.cpp.
Referenced by casadi::KernelSum::eval(), casadi::Mapaccum::evalGen(), casadi::MapSum::evalGen(), casadi::KernelSum::generateBody(), casadi::Mapaccum::generateBody(), casadi::MapSum::generateBody(), casadi::Mapaccum::init(), casadi::KernelSum::init(), casadi::PureMap::init(), casadi::MapSum::init(), casadi::CvodesInterface::jtimesB(), casadi::IdasInterface::jtimesB(), casadi::Mapaccum::spAdj(), casadi::MapSum::spAdj(), casadi::KernelSum::spFwd(), and casadi::Call::sz_arg().
 { return (*this)->sz_arg();}
size_t casadi::Function::sz_iw () const inherited
Definition at line 672 of file function.cpp.
Referenced by casadi::Mapaccum::init(), casadi::KernelSum::init(), casadi::PureMap::init(), casadi::MapSum::init(), casadi::IdasInterface::jtimesB(), casadi::CvodesInterface::jtimesB(), and casadi::Call::sz_iw().
 { return (*this)->sz_iw();}
size_t casadi::Function::sz_res () const inherited
Definition at line 670 of file function.cpp.
Referenced by casadi::KernelSum::eval(), casadi::Mapaccum::evalGen(), casadi::MapSum::evalGen(), casadi::KernelSum::generateBody(), casadi::Mapaccum::generateBody(), casadi::MapSum::generateBody(), casadi::Mapaccum::init(), casadi::KernelSum::init(), casadi::PureMap::init(), casadi::MapSum::init(), casadi::CvodesInterface::jtimesB(), casadi::IdasInterface::jtimesB(), casadi::Mapaccum::spAdj(), casadi::MapSum::spAdj(), casadi::KernelSum::spFwd(), and casadi::Call::sz_res().
 { return (*this)->sz_res();}
size_t casadi::Function::sz_w () const inherited
Definition at line 674 of file function.cpp.
Referenced by casadi::KinsolInterface::bjac(), casadi::CvodesInterface::bjac(), casadi::IdasInterface::bjac(), casadi::CvodesInterface::bjacB(), casadi::IdasInterface::bjacB(), casadi::KinsolInterface::djac(), casadi::CvodesInterface::djac(), casadi::IdasInterface::djac(), casadi::CvodesInterface::djacB(), casadi::IdasInterface::djacB(), casadi::KernelSum::eval(), casadi::Mapaccum::evalGen(), casadi::MapSum::evalGen(), casadi::KernelSum::generateBody(), casadi::Mapaccum::generateBody(), casadi::MapSum::generateBody(), casadi::Switch::init(), casadi::Rootfinder::init(), casadi::Mapaccum::init(), casadi::KernelSum::init(), casadi::Integrator::init(), casadi::PureMap::init(), casadi::MapSum::init(), casadi::IdasInterface::jtimesB(), casadi::CvodesInterface::jtimesB(), casadi::Mapaccum::spAdj(), casadi::MapSum::spAdj(), casadi::KernelSum::spFwd(), and casadi::Call::sz_w().
 { return (*this)->sz_w();}
void casadi::Function::sz_work (size_t & sz_arg, size_t & sz_res, size_t & sz_iw, size_t & sz_w) const inherited
Definition at line 664 of file function.cpp.
Referenced by casadi::FunctionInternal::alloc().
{
     (*this)->sz_work(sz_arg, sz_res, sz_iw, sz_w);
   }
Function casadi::Function::tangent (int iind = 0, int oind = 0) inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the input must be scalar. In other cases, use the Jacobian instead.
Definition at line 584 of file function.cpp.
References casadi::FunctionInternal::tangent().
Referenced by casadi::collocationInterpolators(), and casadi::FunctionInternal::getTangent().
{
     return (*this)->tangent(iind, oind);
   }
Function casadi::Function::tangent (const std::string & iind, int oind = 0) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the input must be scalar. In other cases, use the Jacobian instead.
Definition at line 360 of file function.hpp.
     { return tangent(index_in(iind), oind); }
Function casadi::Function::tangent (int iind, const std::string & oind) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the input must be scalar. In other cases, use the Jacobian instead.
Definition at line 362 of file function.hpp.
     { return tangent(iind, index_out(oind)); }
Function casadi::Function::tangent (const std::string & iind, const std::string & oind) inline inherited
Parameters
iind The index of the input
oind The index of the output
The default behavior of this class is defined by the derived class. Note that the input must be scalar. In other cases, use the Jacobian instead.
Definition at line 364 of file function.hpp.
     { return tangent(index_in(iind), index_out(oind)); }
bool casadi::Function::test_cast (const SharedObjectNode * ptr) static inherited
Definition at line 600 of file function.cpp.
{
     return dynamic_cast<const FunctionInternal*>(ptr)!=0;
   }
void casadi::Callback::transfer_ownership ()
Definition at line 137 of file callback.cpp.
References casadi::SharedObject::count_down(), casadi::SharedObject::getCount(), and casadi::SharedObject::is_null().
{
     casadi_assert_message(!is_null(), "Null pointer.");
     casadi_assert_message(!(*this)->own_, "Ownership has already been transferred.");
     casadi_assert_message(getCount()>1, "There are no owning references");
     // Decrease the reference counter to offset the effect of the owning reference
     count_down();
     // Mark internal class as owning
     (*this)->own_ = true;
   }
string casadi::Function::type_name () const inherited
Definition at line 1160 of file function.cpp.
{
     return (*this)->type_name();
   }
WeakRef * casadi::SharedObject::weak () inherited
Definition at line 167 of file shared_object.cpp.
References casadi::SharedObjectNode::weak().
Referenced by casadi::WeakRef::WeakRef().
{
     return (*this)->weak();
   }
The documentation for this class was generated from the following files:
casadi/core/function/callback.hpp
callback.cpp
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge