CasADi: Linsol
Linsol
Functions
Function casadi::linsol (const std::string &name, const std::string &solver, const Sparsity &sp, int nrhs, const Dict &opts)
CASADI_EXPORT bool casadi::has_linsol (const std::string &name)
Check if a particular plugin is available.
CASADI_EXPORT void casadi::load_linsol (const std::string &name)
Explicitly load a plugin dynamically.
CASADI_EXPORT std::string casadi::doc_linsol (const std::string &name)
Get the documentation string for a plugin.
int casadi::linsol_n_in ()
Number of linear solver inputs.
int casadi::linsol_n_out ()
Number of linear solver outputs.
vector< string > casadi::linsol_in ()
Linear solver input scheme.
string casadi::linsol_in (int ind)
Linear solver input scheme.
vector< string > casadi::linsol_out ()
Linear solver output scheme.
string casadi::linsol_out (int ind)
Linear solver output scheme.
Detailed Description
Create a solver for linear systems of equations Solves the linear system A*X = B or A^T*X = B for X with A square and non-singular
If A is structurally singular, an error will be thrown during init. If A is numerically singular, the prepare step will fail.
The usual procedure to use Linsol is:
init()
set the first input (A)
prepare()
set the second input (b)
solve()
Repeat steps 4 and 5 to work with other b vectors.
The standard evaluation combines the prepare() and solve() step and may therefore more expensive if A is invariant.
General information
Input scheme: casadi::LinsolInput (LINSOL_NUM_IN = 2) []
Full name Short Description
LINSOL_A The square matrix A: sparse, (n x n)
LINSOL_B The right-hand-side matrix b: dense, (n x m)
Output scheme: casadi::LinsolOutput (LINSOL_NUM_OUT = 1) []
Full name Short Description
LINSOL_X Solution to the linear system of equations.
List of plugins
- csparsecholesky
- csparse
- lapacklu
- lapackqr
- symbolicqr
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Linsol.doc("myextraplugin")
csparsecholesky
Linsol with CSparseCholesky Interface
csparse
Linsol with CSparse Interface
lapacklu
This class solves the linear system A.x=b by making an LU factorization of A:
A = L.U, with L lower and U upper triangular
List of available options
Id Type Description
allow_equilibration_failure OT_BOOL Non-fatal error when equilibration fails
equilibration OT_BOOL Equilibrate the matrix
lapackqr
This class solves the linear system A.x=b by making an QR factorization of A:
A = Q.R, with Q orthogonal and R upper triangular
symbolicqr
Linsol based on QR factorization with sparsity pattern based reordering without partial pivoting
List of available options
Id Type Description
codegen OT_BOOL C-code generation
compiler OT_STRING Compiler command to be used for compiling generated code
Author
Joel Andersson
Date
2011-2015
Function Documentation
CASADI_EXPORT std::string casadi::doc_linsol (const std::string & name)
CASADI_EXPORT bool casadi::has_linsol (const std::string & name)
CASADI_EXPORT Function casadi::linsol (const std::string & name, const std::string & solver, const Sparsity & sp, int nrhs, const Dict & opts = Dict())
Definition at line 83 of file linsol.cpp.
References casadi::SharedObject::assignNode(), and casadi::FunctionInternal::construct().
Referenced by casadi::Rootfinder::init(), casadi::Integrator::init(), casadi::SundialsInterface::init(), casadi::Matrix< Scalar >::solve(), and casadi::MX::solve().
{
     Function ret;
     if (solver=="none") {
       ret.assignNode(new Linsol(name, sp, nrhs));
     } else {
       ret.assignNode(Linsol::getPlugin(solver).creator(name, sp, nrhs));
     }
     ret->construct(opts);
     return ret;
   }
CASADI_EXPORT std::vector< std::string > casadi::linsol_in ()
Definition at line 42 of file linsol.cpp.
References casadi::linsol_in(), and casadi::linsol_n_in().
Referenced by casadi::Linsol::get_name_in().
{
     vector<string> ret(linsol_n_in());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=linsol_in(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::linsol_in (int ind)
Definition at line 54 of file linsol.cpp.
References casadi::LINSOL_A, casadi::LINSOL_B, and casadi::LINSOL_NUM_IN.
Referenced by casadi::linsol_in().
{
     switch (static_cast<LinsolInput>(ind)) {
     case LINSOL_A:     return "A";
     case LINSOL_B:      return "B";
     case LINSOL_NUM_IN: break;
     }
     return string();
   }
CASADI_EXPORT int casadi::linsol_n_in ()
Definition at line 34 of file linsol.cpp.
References casadi::LINSOL_NUM_IN.
Referenced by casadi::linsol_in().
                     {
     return LINSOL_NUM_IN;
   }
CASADI_EXPORT int casadi::linsol_n_out ()
Definition at line 38 of file linsol.cpp.
References casadi::LINSOL_NUM_OUT.
Referenced by casadi::linsol_out().
                      {
     return LINSOL_NUM_OUT;
   }
CASADI_EXPORT std::vector< std::string > casadi::linsol_out ()
Definition at line 48 of file linsol.cpp.
References casadi::linsol_n_out(), and casadi::linsol_out().
Referenced by casadi::Linsol::get_name_out().
{
     vector<string> ret(linsol_n_out());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=linsol_out(i);
     return ret;
   }
CASADI_EXPORT std::string casadi::linsol_out (int ind)
Definition at line 63 of file linsol.cpp.
References casadi::LINSOL_NUM_OUT, and casadi::LINSOL_X.
Referenced by casadi::linsol_out().
{
     switch (static_cast<LinsolOutput>(ind)) {
     case LINSOL_X:     return "X";
     case LINSOL_NUM_OUT: break;
     }
     return string();
   }
CASADI_EXPORT void casadi::load_linsol (const std::string & name)
Release pointers: extensive python examples, tutorials, Users Guide (pdf | html)
Official releases: 3.0.0-rc1 2.4.2 2.3.0 2.2.0 2.1.1 2.0.0 1.9.0 1.8.0 1.7.1 1.7.0 1.6.1 1.6.0 1.5.0 1.4.0 1.3.0 bleeding edge